### ISSUE TITLE
JTReg test fail - Windows : java/nio/channels/AsynchronousFileChannel/Basic.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4612] opened 2019-02-06 14:32 UTC
Intermittent failure ...

```
Stacktrace

Execution failed: `main' threw exception: java.lang.AssertionError    

Standard Output

testUsingCompletionHandlers
testUsingWaitOnResult
testInterruptHandlerThread
testClosedChannel
testLocking
testCustomThreadPool
testAsynchronousClose
testCancel
    

Standard Error

java.lang.AssertionError
	at java.base/sun.nio.ch.PendingIoCache.clearPendingIoMap(PendingIoCache.java:146)
	at java.base/sun.nio.ch.PendingIoCache.close(PendingIoCache.java:116)
	at java.base/sun.nio.ch.WindowsAsynchronousFileChannelImpl.close(WindowsAsynchronousFileChannelImpl.java:145)
	at Basic.testCancel(Basic.java:482)
	at Basic.main(Basic.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.base/java.lang.Thread.run(Thread.java:825)

JavaTest Message: Test threw exception: java.lang.AssertionError
JavaTest Message: shutting down test
```

... observed on Windows of test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/nio/channels/AsynchronousFileChannel/Basic.java.

See https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_windows/124/testReport/junit/java_nio_channels_AsynchronousFileChannel_Basic/java/Basic.

I have kicked off a 100x run to determine failure rate - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/989

I have also kicked off a 100x run against Linux for comparison purposes - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/992

**Comment by ben-walsh** [comment] 2019-02-06 14:35
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/989 showed a 0% failure rate.
400x run - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/995.

**Comment by sophia-guo** [comment] 2019-02-06 21:47
This is reported in https://bugs.openjdk.java.net/browse/JDK-8210968 and duplicate of https://bugs.openjdk.java.net/browse/JDK-7052549, which shouldn't be related with openj9. Will update the problemlist and close this one.

**Comment by ben-walsh** [comment] 2019-02-07 16:32
Closed per above comment.

**Closed** 2019-02-07 16:32 UTC
Labels: test failure
