### ISSUE TITLE
Performance problem of modded Minecraft

### ISSUE THREAD

**Issue by scikirbypoke** [eclipse/openj9#8353] opened 2020-01-21 12:47 UTC
java -version output
--------------------
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-202001120429-b06)
Eclipse OpenJ9 VM (build master-6b1f6d9b5, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200112_500 (JIT enabled, AOT enabled)
OpenJ9   - 6b1f6d9b5
OMR      - aabbee909
JCL      - a9857e68ed based on jdk8u242-b06)

Summary of problem
------------------
Running large modpacks on openj9 may lead to longer [tick time](https://minecraft.gamepedia.com/Tick) and lower performance compare to hotspot. Here are screenshots of  F3 in-game debug screen from [Omnifactory](https://www.curseforge.com/minecraft/modpacks/omnifactory/) modpack:
![2020-01-21_11 48 33](https://user-images.githubusercontent.com/11038263/72787441-e4bccd80-3c6a-11ea-9f78-dc40240475ad.png)
Run [Omnifactory](https://www.curseforge.com/minecraft/modpacks/omnifactory/) on openj9. Tick time and profiling chart in the right.
![2020-01-21_11 57 21](https://user-images.githubusercontent.com/11038263/72787444-e5556400-3c6a-11ea-894a-8f07f4f09717.png)
Running on hotspot. Have shorter tick time and lesser tick share in profiling.

This problem would not affect TPS when modpack have fewer mods, but when playing huge modpacks with 250+ mods(for example, [ATM3](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3)), the tick time will be 300+ ms, cause TPS drop to below 5. If I run same modpack on hotspot, the game can easily keep running at 20 TPS. I found a reddit post may describe same performance problem: [link](https://www.reddit.com/r/FeedTheBeastCrashes/comments/cz73mn/1122_forge_tps_issues_with_more_than_1_person_on/).

**Comment by DanHeidinga** [comment] 2020-01-22 16:06
FYI @andrewcraik @vijaysun-omr @dmitripivkine

**Comment by andrewcraik** [comment] 2020-01-22 17:43
Thanks for the heads up - will get someone to get a basic setup and try doing a few benchmarks to see where it looks like the time is going so we can route it to the right experts.

**Comment by BeverlyXu** [comment] 2020-01-28 21:21
@scikirbypoke We are looking into this issue. We have the minecraft installed with the modspacks (omnifactory and ATM3) you recommended, and was able to see the status via F3. Could you share more information on how to reproduce the problem? ie, did you see that on loading the game, or did you have to play for a period of time? What activities are more likely to cause the slow TPS? Did you play in a single, or multi player mode, or the problem shows up in both? Do we need to use a particular server? 

We are looking for minimum steps to reproduce the problem on our end. Could there be a saved "new world" that we can load directly to reproduce the problem? Thanks!

**Comment by scikirbypoke** [comment] 2020-01-29 03:54
Just create a new world in single player and play as creative mode, look around until all nearby chunks loaded, and check the tick time. I have tested many worlds and it seems any world type would have the problem, but more complex the world is the more tick time it use(compare to hotspot). To check the tick time faster, you can use [debugserverinfo](https://www.curseforge.com/minecraft/mc-mods/debugserverinfo) or [server tab info](https://www.curseforge.com/minecraft/mc-mods/server-tab-info/) mod.

**Comment by scikirbypoke** [comment] 2020-02-10 14:27
Since ATM3 has a long launch time (50 mins) on my Fx8350, so I switch to FTB Revelation to test tick time quicker. I launch the pack two times and entered same world, the only difference is jvm.
openj9:
![2020-02-10_20 29 55](https://user-images.githubusercontent.com/11038263/74157511-5c22c300-4c53-11ea-9ca5-2104bfdc4313.png)
hotspot:
![2020-02-10_20 48 02](https://user-images.githubusercontent.com/11038263/74157523-62b13a80-4c53-11ea-8f87-41e7b5e4e29d.png)
The world used at testing was just a newly created default world.

**Comment by BeverlyXu** [comment] 2020-02-13 17:11
We originally planned to reproduce the problem and debug in our own environment. But we are having difficulty recreating the problem. Now we want to make a few suggestions to see if they help the problem. 

Based on your description, the problem appeared **after** the initial loading, and started **after** a few activities. So it's most likely not a "startup" problem, but a problem during "throughput". And given that the problem only occurs while a large amount of MODs are loaded, we suspect that gc may become aggressive during the game. 

1. What is your heap size setting? Are you using the default? We would suggest to set a fixed heap size, something like -Xms4096M -Xmx4096M (or 1G or 2G). When the heap size is not set, OpenJ9 will only acquire a small amount of memory at startup (ideal for cloud environment), and grows the heap as the application runs. But this could bring overhead as the jvm acquires more memory. Having a fixed heap size will eliminate this factor. Is there a way to know how much memory these large MODs will take? We need to allocate memory accordingly. 

2. What is the garbage collection policy? Here is an article that has Minecraft specific jvm tuning suggestions https://steinborn.me/posts/tuning-minecraft-openj9/

3. If any of the above tuning option didn't work, please help us collect the verbose gc log, and we could look into the problem that way. https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/mm_gc_pd_verbosegc.html

**Comment by scikirbypoke** [comment] 2020-02-14 04:39
I read the jvm tuning guide and launched minecraft on openj9 with 
`-Xms4096M -Xmx4096M -Xmns2048M -Xmnx3276M -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3 -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc`
The tick time was much better than last test, but just barely sustained around 30ms. Once I try to look around, it raise beyond 50ms and FPS drop from 40 to 0. After that, I used `-Xms4096M -Xmx4096M` launch game on hotspot, and it easily sustained a stable 18ms tick time and 55 FPS.
I am going to collect the gc log and post it here.

**Comment by scikirbypoke** [comment] 2020-02-14 06:11
Got GC log from minecraft with tuned arguments.
[verbosegc.20200214.132941.10603.txt](https://github.com/eclipse/openj9/files/4202992/verbosegc.20200214.132941.10603.txt)

**Comment by dmitripivkine** [comment] 2020-02-14 14:10
> Got GC log from minecraft with tuned arguments.
> [verbosegc.20200214.132941.10603.txt](https://github.com/eclipse/openj9/files/4202992/verbosegc.20200214.132941.10603.txt)

@amicic Would you please take a look too?

**Comment by amicic** [comment] 2020-02-14 14:47
Pressure on the Tenure heap in the second half of the run is rather high causing frequent and long Global GCs. Just from Verbose GC it's not possible if these are real live data or there is potentially a leak somewhere - we need a couple of heap dumps at roughly 15 and 20 mins into the run. And of course we always need Verbose GC logs.

I'd recommend to simplify things and run next experiments with as minimum tuning as possible, except say fixed heap sizing: -Xms4096M -Xmx4096M. We can perhaps add some tuning once we figure Tenure pressure issue.

**Comment by scikirbypoke** [comment] 2020-02-15 02:19
Got two heap dumps, this time I could look around without encountering lags, but FPS always lesser than 25.
[Heap dump link](https://drive.google.com/file/d/1JCwNKgn2vMK0j5LJM-htg5eEjhs1eLql/view?usp=sharing)

**Comment by amicic** [comment] 2020-02-18 19:15
This run looked much better from GC point of view.

The biggest difference was larger Tenure size. The previous 'tuned' experiment had only 2G Tenure and 2G Nursery. With default heap ratio Tenure is 3G and Nursery is 1G. The Tenure pressure problem was completely gone.

There were only a few Global GCs, and most of them were explicit.  -Xdisableexplicitgc tuning might be valuable, but it's still hard to say if it will really be, since I can't tell the real reason why they are invoked.

Heap tuning (or any tuning) will obviously be affected by different workloads, in this case Modpack (and possibly some other factors during the game). While largish Nursery/ smallish Tenure tuning might have been reasonable for non-modpack workload, this one seems to cause  a creation of large amount of persistent data and needs bigger Tenure, while no more stressing allocation and local (Scavenge) GCs.

I could not observe any leaks either from Verbose GC logs nor from Heap Dumps. The two dumps, while 5 minutes apart are very similar, since at that stage the run was rather calm - there did not seem to be too much activity and variability.

The first half of the run seemed to be much more active and there were some Scavenge pauses in 100ms range, that are possible to cause game stuttering. Concurrent Scavenge (CS) tuning may help with it. However,  it might also cause a drop of average FPS by a few percent.

I don't see a reason for the other two tuning options (dynamic sizing and tenure age threshold).

Both previous and last run had a high number of Weak/Soft references, but suspiciously low number of them being cleared during global GCs (especially Weak ones). I browsed heap dumps a bit, I could not spot anything obviously wrong.

For low FPS problem, JIT experts should look further (CPU/method profiles and what not). For that time, as far as GC is concerned, I recommend to keep things simple as with the last runs.

**Comment by scikirbypoke** [comment] 2020-02-23 04:02
More tests on lowest video setting Omnifactory shows same initial memory allocation with maximum memory allocation has positive effect on both hotspot and openj9, but even after that openj9's tick time  is two times of hotspot's, and opej9's FPS is more unstable.
https://imgur.com/a/pIl46HD

**Comment by BeverlyXu** [comment] 2020-03-05 19:55
Could you try to collect the perf profile (https://perf.wiki.kernel.org/index.php/Tutorial) and verbose log please? Something like `-Xjit:perfTool,verbose={compilePerformance},vlog=LogVerbose`

**Comment by MechanosG** [comment] 2020-03-06 01:48
I seem to be having a similar problem.  I've been using OpenJ9 u212b04 for a while because newer versions would cause various problems with some mods.  Today I updated to u242b08 in order to get the ATM3 modpack to load, and load times/in-game performance was terrible.

I wasn't sure how much of this was ATM3 related, so I tested my current in-dev modpack with u242b08 and again, load times were really bad and in-game performance was unplayable.  With u212b04, I get 50-60 FPS nearly constantly and much faster load times, using the same launch arguments.  The only thing changed between tests was updating OpenJ9 from u212b04 to u242b08.

**Comment by scikirbypoke** [comment] 2020-03-06 12:20
Got [profile](https://drive.google.com/file/d/1tAtwfIGLRCmAGq3-lFFFRuorCbXNPs-J/view?usp=sharing) using `perf record -F 99 -p pid -a -- sleep 60`.

**Comment by BeverlyXu** [comment] 2020-03-16 19:10
The perf.data file generated by the perf tool is kernel dependent, i.e. i won't be able to load it or "zoom in" on my machine. The data is only useful when it is viewed on the machine that generates the perf.data file. We have an internal script that can process the data and format it into a readable flat text file on any machine. I'm working to get a license for the script so I can share it externally. 

In the meanwhile, could you send us the verbose log, using this option:
`-Xjit:verbose={compilePerformance},vlog=LogVerbose`

**Comment by scikirbypoke** [comment] 2020-03-17 02:59
I indeed got a verbose log, but I think I forgot to upload it here...
[verbose log](https://drive.google.com/file/d/1DJsoGOP0ijuSTwBOCYwl73ufckiR5IRg/view?usp=sharing)

**Comment by 1a2s3d4f1** [comment] 2020-03-23 00:39
openjdk version "11.0.6+10"
openj9 version "0.18.1"
system windows 7 
bellsoft-jre11.0.6+10-windows-amd64-full:
![2020-03-23_08 03 14](https://user-images.githubusercontent.com/40121560/77267985-65d22880-6cdf-11ea-9e19-792d9b9e6a8a.png)
OpenJDK11U-jdk_x64_windows_openj9_11.0.6_10_openj9-0.18.1:
![2020-03-23_08 14 32](https://user-images.githubusercontent.com/40121560/77268613-7daaac00-6ce1-11ea-8e41-7345e306834b.png)
verbose log:[LogVerbose.20200323.080504.zip](https://github.com/eclipse/openj9/files/4366681/LogVerbose.20200323.080504.zip)

**Comment by 1a2s3d4f1** [comment] 2020-03-23 01:53
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 7 amd64-64-
it Compressed References 20200122_442 (JIT enabled, AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

bellsoft-jre11.0.6+10-windows-amd64-full:
![2020-03-23_09 15 22](https://user-images.githubusercontent.com/40121560/77272371-062e4a00-6cec-11ea-9d6d-04d39ac9ccbc.png)
OpenJDK11U-jdk_x64_windows_openj9_11.0.6_10_openj9-0.18.1:
![2020-03-23_09 31 59](https://user-images.githubusercontent.com/40121560/77272390-121a0c00-6cec-11ea-90a9-35b12d4d4e48.png)
verbose log:
[LogVerbose.20200323.093447.5948.gz](https://github.com/eclipse/openj9/files/4366841/LogVerbose.20200323.093447.5948.gz)

**Comment by 1a2s3d4f1** [comment] 2020-03-24 17:17
[LogVerbose.20200323.093447.5948.gz](https://github.com/eclipse/openj9/files/4376733/LogVerbose.20200323.093447.5948.gz)
Player move cause tick time longer(36ms>42ms)

**Comment by pshipton** [comment] 2020-03-30 15:09
We're past Milestone 2 for the 0.20.0 release, moving this forward to the next release.
If a low risk fix does become available in the next couple of weeks, please raise it for consideration.

**Comment by BeverlyXu** [comment] 2020-04-03 21:24
I'm waiting for this pull request #9014  to be merged so I can release the tool to look at perf.data file from our community user.

**Comment by BeverlyXu** [comment] 2020-04-06 19:17
@scikirbypoke , would you please download the script from #9014 and send us the results? 

The script is being reviewed and tested before it can be merged, and I will need to add more error handling mechanism to make it more user friendly. 

But we don't want to let you wait for too long, as the main functionality of the script has been tested already.

**Comment by scikirbypoke** [comment] 2020-04-07 02:19
Tried with `perf record -F 99 -p 3668 -a -- sleep 60` then `perf script | ./perf-hottest sym`. The command line output of the script is at here: https://gist.github.com/scikirbypoke/869b70c7bb20bf24380bfe61ababc00c
Should I try to run perf with different arguments?

**Comment by mpirvu** [comment] 2020-04-13 17:08
Looking at the verbose log from comment https://github.com/eclipse/openj9/issues/8353#issuecomment-599852183 I see 4742 lines that start with
`#FAILURE:  Failure while commiting static final field assumption for class`
Because of this, many methods end up interpreted.

**Comment by vijaysun-omr** [comment] 2020-04-13 17:12
fyi @liqunl and @andrewcraik wrt the last comment about static final field assumptions

**Comment by liqunl** [comment] 2020-04-13 17:31
Looks like we didn't check if a class has static final field modified before folding its static final fields. Fixing.

**Comment by vijaysun-omr** [comment] 2020-04-13 18:19
Is there an -Xjit option that can be used to avoid the compilation failures mentioned above ? This may be a quick way to confirm that this is the source of the reported performance problem (as is suspected).

**Comment by liqunl** [comment] 2020-04-13 18:31
The option is `-Xjit:disableGuardedStaticFinalFieldFolding`, this will turn off all OSR-dependent static final field folding

**Comment by vijaysun-omr** [comment] 2020-04-13 20:46
@scikirbypoke please try adding `-Xjit:disableGuardedStaticFinalFieldFolding` to your JVM command line options if you get a chance to see how/if the performance characteristics improve.

**Comment by scikirbypoke** [comment] 2020-04-14 03:35
The `-Xjit:disableGuardedStaticFinalFieldFolding` option seems have positive effect to overall performance. The boot time became shorter, the TPS dropped to the level of hotspot's, but the FPS kept flipping between 30 and 60 and given an average 45 FPS. When I was using hotspot to enter same world, the FPS just float around 60.

**Comment by vijaysun-omr** [comment] 2020-04-14 14:59
Thank you for trying that option @scikirbypoke 

@liqunl please focus on delivery of the issue you mentioned related to static final fields.

@BeverlyXu please pursue the FPS issue referred to in the prior comment to see if that can be improved in some way.

**Comment by BeverlyXu** [comment] 2020-04-14 20:32
@scikirbypoke so it looks like TPS is in order and FPS is still not satisfactory -- fluctuates a lot and average is still lower than Hotspot's

Could you please keep the Xjit option of `disableGuardedStaticFinalFieldFolding`, and take the verbose log with `verbose={compilePerformance}` while running the `perf` tool? Please note to start measuring the performance after the initial loading, and during the period where you see the fluctuation. 

Please send us the verbose log and the parsed result of perf.data. This will help us understand where we spend most of our time. 

Thank you!

**Comment by scikirbypoke** [comment] 2020-04-15 02:59
verbose log: https://send.firefox.com/download/87d50c8e0061b446/#zUO7lcfebt-7Vxt-Y-JcMg
parsed result: https://gist.github.com/scikirbypoke/8d3c710589a3b89aeac28705996741bd
I couldn't reproduce the FPS flipping problem this time. For overall performance, hotspot now seems no better than openj9, but I am not sure if the problem has been complete fixed.
@1a2s3d4f1 @MechanosG should try `disableGuardedStaticFinalFieldFolding` option too.

**Comment by mpirvu** [comment] 2020-04-15 14:29
Compilation stats for the verbose log above:
```
        Samples MAX(ms) TOTAL(ms)       AVG(usec)       MIN(usec)
Total   27596   6611.2  313917.1        11375           146
cold    7286    27.1    10891.2         1495            146
warm    19747   4852.4  238977.8        12102           196
hot     67      6611.2  36903.1         550792          2738
pvhot   23      3960.8  17801.8         773990          14501
scorc   18      2950.0  9069.5          503863          7821
jni     455     51.9    273.8           602             169
MAXLINE=+ (hot) net/minecraftforge/client/model/pipeline/BlockInfo.updateLightMatrix()V @ 00007F44F1B818C0-00007F44F1B8F0C0 OrdinaryMethod 4.10% T Q_SZ=4 Q_SZI=0 QW=168 j9m=0000000007D880F0 bcsz=1041 OSR time=6611235us mem=[region=128512 system=131072]KB compThread=0 CpuLoad=506%(63%avg) JvmCpu=505%
numGCR   recompilations = 2645
coldupgr recompilations = 137
inv      recompilations = 100
sync compilations = 100
DLT compilations  = 61
numFailures       = 11
max_Q_SZ          = 592
```
Nothing worisome. The 11 compilation failures happen because the JIT exceeds its 256M of memory allowed for one compilation. They are retried at lower opt level however.
Some general remarks:
- The application is big. 27K compilations is on the large size
- Despite the heavy compilations the system has the resources to do it as there is still free CPU on the table
- ClassLoadPhase is detected throughout the run which means the that application is constanly loading new classes.
- There is a fair amount of synchronous compilations (100) due to invalidations, which may cause small blips in performance.

**Comment by 1a2s3d4f1** [comment] 2020-04-15 15:42
Openj9 tick time longger than Hotspot if loader some entities  

Already use `disableGuardedStaticFinalFieldFolding` option
[LogVerbose.20200415.231802.zip](https://github.com/eclipse/openj9/files/4482157/LogVerbose.20200415.231802.zip)

**Comment by BeverlyXu** [comment] 2020-04-16 15:53
@scikirbypoke Good to hear the workaround has helped! What was the main difference b/w your fluctuated run and the stable run?

@1a2s3d4f1 @MechanosG Please look at the tuning options suggested above and the workaround -Xjit options to see if it solves your problems. If you still have concern, please send the verbose logs and parse the perf.data. We'll be happy to take a look.

**Comment by scikirbypoke** [comment] 2020-04-17 03:35
The FPS fluctuating seems like a random incident and haven't happened again. I think the problem have been fixed.

**Comment by andrewcraik** [comment] 2020-04-17 17:33
Thankyou @scikirbypoke for helping us find the problem!

https://github.com/eclipse/openj9/pull/9246 has merged which, once in the build should remove the need for a workaround. Since the other fluctuation seems to have been addressed I am going to close this as fixed. Please reopen if there is anything we have not addressed.

**Closed by andrewcraik** 2020-04-17 17:33 UTC
Labels: arch:x86, comp:jit, perf, userRaised

**Comment by 1a2s3d4f1** [comment] 2020-04-18 09:43
openj9 0.20 have Performance problem if not use `disableGuardedStaticFinalFieldFolding` option

**Comment by 1a2s3d4f1** [comment] 2020-05-14 05:39
It is a performance problem of modded minecraft? (already add disableGuardedStaticFinalFieldFolding option)
install 2 mod
Hotspot: 24/25ms  Openj9: 30/29ms
[LogVerbose.20200514.124153.zip](https://github.com/eclipse/openj9/files/4626239/LogVerbose.20200514.124153.zip)
