### ISSUE TITLE
printerjob get font height  not work

### ISSUE THREAD

**Issue by annopnod** [eclipse/openj9#5697] opened 2019-05-09 10:37 UTC
i test printerjob to get font height  not work (output is 0 )
test at debian 9 and win7
OpenJDK 7  and 8
 
![01](https://user-images.githubusercontent.com/6957642/57447358-1b8bb880-7281-11e9-9fd2-c07572120d91.png)

![02](https://user-images.githubusercontent.com/6957642/57447359-1b8bb880-7281-11e9-8200-04c3e672cadd.png)

![03](https://user-images.githubusercontent.com/6957642/57447360-1b8bb880-7281-11e9-8f83-0191a24a6874.png)

**Comment by DanHeidinga** [comment] 2019-05-10 15:37
> OpenJDK 7 and 8

If the issue occurs with OpenJDK7 then it should be reported to the OpenJDK community and fixed upstream.

Please clarify whether the problem is OpenJ9-specific or not.

**Comment by DanHeidinga** [comment] 2019-05-16 06:02
Closing now.  We can reopen the issue if it's confirmed to be an OpenJ9-issue rather than an upstream OpenJDK issue.

**Closed by DanHeidinga** 2019-05-16 06:02 UTC
Labels: userRaised
