### ISSUE TITLE
Failure in SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#6715] opened 2019-08-09 15:19 UTC
Ran the test locally on Ubuntu Linux. Also fails on personal builds on local Jenkins farm.

To reproduce:
- Installed JDK:
```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11-201908081810)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-5dd23af84, JRE 11 Linux amd64-64-Bit Compressed References 20190808_302 (JIT enabled, AOT enabled)
OpenJ9   - 5dd23af84
OMR      - 6e99760b
JCL      - 965d0c0df3 based on jdk-11.0.4+11)
```
- follow the instructions in https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally. 
- run the test using `make -f ../functional/SyntheticGCWorkload/autoGen.mk _SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0`.

Optional info
-------------

- intermittent failure (no): 
- regression or new test:  Seems to be a new test

Failure output (captured from console output)
---------------------------------------------
```
run_workload() - Command: /home/pdbain/projects/triage/jdk-11.0.4+11/bin/java -Xcompressedrefs -Xverbosegclog:/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_original.xml -cp .:SyntheticGCWorkload.jar net.adoptopenjdk.casa.workload_sessions.Main config/config_1k_0.3.xml --log_file /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_stdout_original.txt -s
Start time: 2019-08-09T_06-56-52
Workload configuration: config/config_1k_0.3.xml
Options: -Xcompressedrefs -Xgc:concurrentSlack=macrofrag
Heap: 
run_workload() - Command: /home/pdbain/projects/triage/jdk-11.0.4+11/bin/java -Xcompressedrefs -Xgc:concurrentSlack=macrofrag -Xverbosegclog:/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_concurrentSlackAuto.xml -cp .:SyntheticGCWorkload.jar net.adoptopenjdk.casa.workload_sessions.Main config/config_1k_0.3.xml --log_file /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_stdout_concurrentSlackAuto.txt -s
test_verbose_files() - Command: /home/pdbain/projects/triage/jdk-11.0.4+11/bin/java -cp SyntheticGCWorkload.jar net.adoptopenjdk.casa.verbose_gc_parser.VerboseGCComparator /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_original.xml /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_concurrentSlackAuto.xml -e x,p -d 2,2 -p 0.15,0.15
Legend: 
. = Scavenge
, = Global
f = Failed flip
F = Failed tenure
p = Percolate collect
c = Concurrent aborted
| = Minute marker
x = Warning: aborted collection due to insufficient free space
s = Warning: scan cache overflow (storage acquired from heap)
X = Other warning
T = Total throughput
S = Concurrent slack (-1 = auto)
? = Unknown event
---------------------------------------------------------
/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_original.xml: 
........f......,.p,..,..,.fp,..,.,..p,...,..,..,..,..p,..,..p,....,...,...p,..,..,....,.....,....,...p,....,...,...,.......,.,.,.,,,.f,,|,.,,,.,,,..,,.,.,..,..,.,|.,.,..,.,.,.,..,.,.,|.,..,.,.,.,..,.,.,.|,..,.,.,.,.,.,.,..|,.,.,.,.,.,.,.,..,.|,.,.,.,.,.,.,..,.,.|,.,.,.,.,.,..,.,.,.|,.,.,.,.,.,.,..,,..|,.,.,.,.,.,..,,.f.,,,
.	,	x	f	F	p	S	T	
183	121	0	4	0	7	0	47.5GB
---------------------------------------------------------
/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15653584092891/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-09T_06-46-50_verbose_concurrentSlackAuto.xml: 
..............,..,.f.,..,.f.,.f..,..,..,.,.,.,..,..,..,.,...,...,....,...,..,.p,..p,...,.,..,.,..,.p,..,.,.,,.,,,,,,,,,,|,,.,,,,,p,,,,,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,.,,,,,,,,,,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,.,,,,,,,,,,,,,,,.,,,,,,,.,,,,,,,,,,,,..,,,..,|,..,,,,,,,,,,,,,,,.,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,.,,,,,,,,,,,,.,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,,,,,,|,
.	,	x	f	F	p	S	T	
89	444	0	3	0	4	-2	48.3GB
---------------------------------------------------------
Test results: 
Warning: aborted collection due to insufficient free space (x): before 0, after 0, ratio NaN <= 0.15 --> passed
Percolate collect (p): before 7, after 4, ratio 0.5714285714285714 > 0.15 --> failed
=========================================================
FAILED

SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0_FAILED

"/home/pdbain/projects/triage/jdk-11.0.4+11/bin/java" -Xshareclasses:destroyAll; "/home/pdbain/projects/triage/jdk-11.0.4+11/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /home/pdbain/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_pdbain" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0 Finish Time: Fri Aug  9 07:07:05 2019 Epoch Time (ms): 1565359626002


TEST TARGETS SUMMARY
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
FAILED test targets:
	SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0

TOTAL: 1   EXECUTED: 1   PASSED: 0   FAILED: 1   DISABLED: 0   SKIPPED: 0
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by smlambert** [comment] 2019-08-09 15:26
This is a newly-added test that needs to be 'tuned'.  Requesting some assistance from @LinHu2016 to ensure we are using the correct settings/inputs for this test.

**Comment by LinHu2016** [comment] 2019-08-09 15:53
this issue had been seen once before, the test is designed to run twice with the config-ed data model, first run should generate big fragmentation to cause 10-20 abort case and some percolate cases, but in some special systems, it does not generate fragmentation, so it could cause second run the worse result, we need to update the test to handle the case, 
but if it failed all of platforms or all the time, it might be the config file issue.

**Comment by pdbain-ibm** [comment] 2019-08-09 17:37
Failed 3/3 runs on my Linux system, and fails in my personal builds.

**Comment by LinHu2016** [comment] 2019-08-09 20:21
Just reviewed the test result, which @pdbain-ibm posted in issue description, realize global gcs in second run almost 4 times more than in first run.  it looks like the concurrent gc kick off issue, it might be related with recent new gc change(https://github.com/eclipse/openj9-omr/commit/aec40ce26d54d434f39de2f8cb93fe0cf60a082b), I am not familiar with this new change, will investigate the details on next Monday.

**Comment by LinHu2016** [comment] 2019-08-12 18:00
Try to isolate and narrow done the issue, @pdbain-ibm could you please rerun the test with "export EXTRA_OPTIONS=-Xgc:tenureBytesDeviationBoost=0" on your local? see if still can reproduce the failure. Thanks

**Comment by pdbain-ibm** [comment] 2019-08-12 19:32
I ran:
```
export EXTRA_OPTIONS=-Xgc:tenureBytesDeviationBoost=0
make -f ../functional/SyntheticGCWorkload/autoGen.mk _SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0
```
The test still failed.

**Comment by LinHu2016** [comment] 2019-08-12 19:39
@pdbain-ibm Could you please share failure output? Thanks

**Comment by pdbain-ibm** [comment] 2019-08-14 12:38
```
===============================================
Running test SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0 ...
===============================================
SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0 Start Time: Mon Aug 12 12:03:14 2019 Epoch Time (ms): 1565636594770
"/home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java" -Xshareclasses:destroyAll; "/home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done";

Attempting to destroy all caches in cacheDir /home/pdbain/javasharedresources/

JVMSHRC806I Compressed references persistent shared cache "sharedcc_pdbain" has been destroyed. Use option -Xnocompressedrefs if you want to destroy a non-compressed references cache.
JVMSHRC005I No shared class caches available
cache cleanup done
variation: -Xmx1g -Xms1g -Xdump:none -Xgcpolicy:gencon -Xnocompactgc -Xgcthreads16
JVM_OPTIONS: -Xcompressedrefs -Xmx1g -Xms1g -Xdump:none -Xgcpolicy:gencon -Xnocompactgc -Xgcthreads16 -Xgc:tenureBytesDeviationBoost=0
{ itercnt=1; \
mkdir -p "/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0"; \
cd "/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0"; \
mkdir -p "/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0"; \
cd /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/SyntheticGCWorkload; \
chmod a+x run_test.sh; \
./run_test.sh 1k 0.15,0.15 "/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0" "/home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java" -Xcompressedrefs -Xmx1g -Xms1g -Xdump:none -Xgcpolicy:gencon -Xnocompactgc -Xgcthreads16 -Xgc:tenureBytesDeviationBoost=0; \
if [ $? -eq 0 ] ; then echo ""; echo "SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0""_PASSED"; echo ""; cd /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/TestTargetResult";
Start time: 2019-08-12T_12-03-15
Workload configuration: config/config_1k_0.3.xml
Options: -Xcompressedrefs
Heap: 
run_workload() - Command: /home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java -Xcompressedrefs -Xverbosegclog:/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_original.xml -cp .:SyntheticGCWorkload.jar net.adoptopenjdk.casa.workload_sessions.Main config/config_1k_0.3.xml --log_file /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_stdout_original.txt -s
Start time: 2019-08-12T_12-13-16
Workload configuration: config/config_1k_0.3.xml
Options: -Xcompressedrefs -Xgc:concurrentSlack=macrofrag
Heap: 
run_workload() - Command: /home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java -Xcompressedrefs -Xgc:concurrentSlack=macrofrag -Xverbosegclog:/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_concurrentSlackAuto.xml -cp .:SyntheticGCWorkload.jar net.adoptopenjdk.casa.workload_sessions.Main config/config_1k_0.3.xml --log_file /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_stdout_concurrentSlackAuto.txt -s
test_verbose_files() - Command: /home/pdbain/projects/triage/openjdk-tests/TestConfig/../../jdk-11.0.4+11/bin/java -cp SyntheticGCWorkload.jar net.adoptopenjdk.casa.verbose_gc_parser.VerboseGCComparator /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_original.xml /home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_concurrentSlackAuto.xml -e x,p -d 2,2 -p 0.15,0.15
Legend: 
. = Scavenge
, = Global
f = Failed flip
F = Failed tenure
p = Percolate collect
c = Concurrent aborted
| = Minute marker
x = Warning: aborted collection due to insufficient free space
s = Warning: scan cache overflow (storage acquired from heap)
X = Other warning
T = Total throughput
S = Concurrent slack (-1 = auto)
? = Unknown event
---------------------------------------------------------
/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_original.xml: 
...............,....f.,..,..p,...,.p,,.X..,..,.,..,..p,...,.p,...p,...,..p,,....,...p,..,...,..p,,.p,...,..,..p,...p,.p,.,.,.,.,,.,,.,,,.,,|.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,p,,,,,,,,,,,,,,,|,,,,,,,,,,,,,.,,,,.,,,,,,.,,,,,,,,,,,,,,,,,,,,|,,,,,.,,,,,,,.,,,,.,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,.,,,,,|,,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,,,.,,,,,,,,.,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,
.	,	x	f	F	p	X	S	T	
98	547	0	1	0	14	1	0	49.6GB
---------------------------------------------------------
/home/pdbain/projects/triage/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15656365947785/SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0/config_1k_0.3.xml_2019-08-12T_12-03-15_verbose_concurrentSlackAuto.xml: 
........f.......,..,.p,.,..,.,..p,..,..p,.f..,..,..,..,..,.,..p,....,....,...,...,..,..,..,..,.p,...,..p,...,....,,.,,,.,.,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|p,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.f,,,,,,,,,,,,,,,,,.,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,,|,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,|,,,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,,,,,,,,,,,,,,,,,.,,,,,|,,,,,,,,,.,,,,,,,,,,,,,.,,,,,,.,,,,,,,,,,,,,,,.,.,,,,.|,.,,,,,,,,..,.,.,,,,,,,,,,,.,,,,,,,,,
.	,	x	f	F	p	X	S	T	
104	777	0	3	0	7	0	-2	49.5GB
---------------------------------------------------------
Test results: 
Warning: aborted collection due to insufficient free space (x): before 0, after 0, ratio NaN <= 0.15 --> passed
Percolate collect (p): before 14, after 7, ratio 0.5 > 0.15 --> failed
=========================================================
FAILED
```

**Comment by pdbain-ibm** [comment] 2019-08-14 12:40
You can reproduce the failure by following the instructions in https://github.com/eclipse/openj9/wiki/Reproducing-Test-Failures-Locally
The command to run the test in question is `make -f ../functional/SyntheticGCWorkload/autoGen.mk _SyntheticGCWorkload_concurrentSlackAuto_1k_J9_0`.

**Comment by LinHu2016** [comment] 2019-08-14 20:26
Base on the output of the run, looks like java options did not pass in the command, so workload was running under the default mode, which data model doesn't match heap env, then generate unpredictable test case.

pass to Test team for detail fixing

**Comment by LinHu2016** [comment] 2019-08-14 20:26
@renfeiw

**Comment by renfeiw** [comment] 2019-08-15 18:52
PR to fix the issue: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1283

**Comment by renfeiw** [comment] 2019-08-16 15:38
The pr is merged, this issue should be fixed now.

**Comment by llxia** [comment] 2019-08-19 19:39
Tests are running fine in the nightly build. https://ci.eclipse.org/openj9/view/Test_Functional_Nightly/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/112/tapResults/

Close this issue.

**Closed by llxia** 2019-08-19 19:39 UTC
Labels: test failure
