### ISSUE TITLE
Memory corruption detected when loading a class in groovy and Xshareclasses is enabled.

### ISSUE THREAD

**Issue by LukeButters** [eclipse/openj9#6549] opened 2019-07-23 05:31 UTC
Java -version output
--------------------

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

Summary of problem
------------------

Memory corruption when loading a class in groovy.

I am receiving this error:
```
04:55:50.700 0x22a3a00 omrport.359    *   ** ASSERTION FAILED ** at ../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))
```

The error seems to be triggered when `loadClass` is called on the groovy class loader when running: (as root if that matters)
```
/usr/lib/jvm/default-java/bin/java -classpath path-to-shadded-jar.jar -Xshareclasses:name=jetty -Xshareclasses:cacheDir=/tmp/jvmcaches/ com.funnelback.jetty.launch.Launch
```
The code run is:
```
    public static void main(String[] args) throws Exception {
        
        System.out.println("Do with groovy");
        try (GroovyClassLoader groovyClassLoader = new GroovyClassLoader(Launch.class.getClassLoader())) {
            System.out.println("Doing with groovy");
            // a jar file containing a single hello world printing main.
            groovyClassLoader.addClasspath("/tmp/hello/Hello.jar");
            
            System.out.println("g4");
            Class<?> clazz = groovyClassLoader.loadClass("foo.Hello", false, true);
            System.out.println("g5");
        } catch (Exception e) {
            System.out.println("g8");
            throw new RuntimeException(e);
        }
        System.out.println("g9 end");
    }
```

The dependencies from maven are:
```
    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.6</version>
            <type>pom</type>
        </dependency>
    </dependencies>
```
Output is:
```
/usr/lib/jvm/default-java/bin/java -classpath /home/luke/code/trunk/funnelback/web/server/funnelback-jetty-launcher.jar -Xshareclasses:name=jetty -Xshareclasses:cacheDir=/tmp/jvmcaches/ com.funnelback.jetty.launch.Launch
Do with groovy
Doing with groovy
g4
05:18:58.617 0x1aaca00 omrport.359    *   ** ASSERTION FAILED ** at ../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/07/23 15:18:58 - please wait.
JVMDUMP032I JVM requested System dump using '/usr/lib/jvm/core.20190723.151858.14762.0001.dmp' in response to an event
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.14788.

JVMDUMP010I System dump written to /usr/lib/jvm/core.20190723.151858.14762.0001.dmp
JVMDUMP032I JVM requested Java dump using '/usr/lib/jvm/javacore.20190723.151858.14762.0002.txt' in response to an event
JVMDUMP010I Java dump written to /usr/lib/jvm/javacore.20190723.151858.14762.0002.txt
JVMDUMP032I JVM requested Snap dump using '/usr/lib/jvm/Snap.20190723.151858.14762.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /usr/lib/jvm/Snap.20190723.151858.14762.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".
```
Diagnostic files
----------------
[javacore.20190723.151858.14762.0002.txt](https://github.com/eclipse/openj9/files/3420335/javacore.20190723.151858.14762.0002.txt)

[Snap.20190723.151858.14762.0003.trc.zip](https://github.com/eclipse/openj9/files/3420336/Snap.20190723.151858.14762.0003.trc.zip)

core dump:
https://drive.google.com/file/d/138FKS_NNKBQjALJtnu97MRXIgAzut3OV/view?usp=sharing

**Comment by jschmied** [comment] 2019-07-23 09:21
I have the same error when building anything with maven:
----------
1XECTHTYPE     Current thread history (J9VMThread:0x0000000000019A00)
3XEHSTTYPE     09:18:58:459667033 GMT omrport.359 - * ** ASSERTION FAILED ** at ../../omr/port/common/omrmemtag.c:145: ((memoryCorruptionDetected)) 
3XEHSTTYPE     09:18:58:459665933 GMT j9jcl.102 -  >JCL: SharedClassURLClasspathHelperImpl notifyClasspathChange: Entering 
----------
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x0000000000019A00, omrthread_t:0x0000026378DD61E0, java/lang/Thread:0x0000000600F855C8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x1BC8, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00000020)
3XMCPUTIME               CPU usage total: 0.375000000 secs, user: 0.078125000 secs, system: 0.296875000 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=102680 (0x19118)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.notifyClasspathChange2(Native Method)
4XESTACKTRACE                at com/ibm/oti/shared/SharedClassURLClasspathHelperImpl.setClasspath(SharedClassURLClasspathHelperImpl.java:353)
5XESTACKTRACE                   (entered lock: com/ibm/oti/shared/SharedClassURLClasspathHelperImpl@0x0000000600F85C00, entry count: 1)
4XESTACKTRACE                at com/ibm/oti/shared/provider/SharedClassProviderImpl.setURLClasspath(SharedClassProviderImpl.java:136)
4XESTACKTRACE                at jdk/internal/loader/URLClassPath.updateClasspathWithSharedClassesHelper(URLClassPath.java:252)
5XESTACKTRACE                   (entered lock: jdk/internal/loader/URLClassPath@0x0000000600F856A8, entry count: 1)
4XESTACKTRACE                at jdk/internal/loader/URLClassPath.getResource(URLClassPath.java:418)
4XESTACKTRACE                at java/net/URLClassLoader$ClassFinder.run(URLClassLoader.java:1091)
4XESTACKTRACE                at java/net/URLClassLoader$ClassFinder.run(URLClassLoader.java:1078)

**Comment by DanHeidinga** [comment] 2019-07-23 11:46
fyi @hangshao0

**Comment by hangshao0** [comment] 2019-07-23 15:20
The corruption is classloader->classPathEntries at this line:
https://github.com/eclipse/openj9/blob/8e63ec532c2539fdaa00207266045a7c24a8908c/runtime/jcl/common/shared.c#L1928

**Comment by hangshao0** [comment] 2019-07-23 19:24
The corrupted memory is 0x7fc02c18d300

> j9memtag 0x7fc02c18d300
J9MemTag at 0x7fc02c18d300 {
  Fields for J9MemTag:
        0x0: U32 eyeCatcher = 0xB7654321 (3076866849)
        0x4: U32 sumCheck = 0x834A2E02 (2202676738)
        0x8: U64 allocSize = 0x00007FC02C1FDCC0 (140463350734016)
        0x10: const U8* callSite = !j9x 0x00007FC029617B83
        0x18: struct OMRMemCategory* category = !omrmemcategory 0x00007FC03156BA60
}
> j9memtag 0x7fc02c18d2e0
J9MemTag at 0x7fc02c18d2e0 {
  Fields for J9MemTag:
        0x0: U32 eyeCatcher = 0xB1234567 (2971878759)
        0x4: U32 sumCheck = 0x850C29A4 (2232166820)
        0x8: U64 allocSize = 0x0000000000000000 (0)
        0x10: const U8* callSite = !j9x 0x00007FC029617B83
        0x18: struct OMRMemCategory* category = !omrmemcategory 0x00007FC03156BA60
}
> xs 0x00007FC029617B83
**0x00007fc029617b83 :  common/shared.c:244**

I find it in the GroovyClassLoader:

!j9classloader 0x7fc02c09e118
J9ClassLoader at 0x7fc02c09e118 {
  Fields for J9ClassLoader:
        0x0: struct J9Pool* sharedLibraries = !j9pool 0x0000000000000000
        0x8: struct J9HashTable* classHashTable = !j9hashtable 0x00007FC02C220F00
        0x10: struct J9HashTable* romClassOrphansHashTable = !j9hashtable 0x0000000000000000
        0x18: struct J9Object* classLoaderObject = !j9object 0x00000007FFEB2348 // groovy/lang/GroovyClassLoader
        **0x20: struct J9ClassPathEntry* classPathEntries = !j9classpathentry 0x00007FC02C18D300**
        **0x28: UDATA classPathEntryCount = 0x0000000000000000 (0)**
        0x30: struct J9ClassLoader* unloadLink = !j9classloader 0x0000000000000000
        0x38: struct J9ClassLoader* gcLinkNext = !j9classloader 0x0000000000000000
        0x40: struct J9ClassLoader* gcLinkPrevious = !j9classloader 0x0000000000000000
        0x48: UDATA gcFlags = 0x0000000000000000 (0)
        0x50: struct J9VMThread* gcThreadNotification = !j9vmthread 0x0000000000000000
        0x58: struct J9Pool* jniIDs = !j9pool 0x0000000000000000
        0x60: UDATA flags = 0x0000000000000008 (8)
        0x68: struct J9JNIRedirectionBlock* jniRedirectionBlocks = !j9jniredirectionblock 0x0000000000000000
        0x70: struct J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
        0x78: struct J9MemorySegment* classSegments = !j9memorysegment 0x0000000000000000
        0x80: struct J9RAMClassFreeListBlock* ramClassLargeBlockFreeList = !j9ramclassfreelistblock 0x0000000000000000
        0x88: struct J9RAMClassFreeListBlock* ramClassSmallBlockFreeList = !j9ramclassfreelistblock 0x0000000000000000
        0x90: struct J9RAMClassFreeListBlock* ramClassTinyBlockFreeList = !j9ramclassfreelistblock 0x0000000000000000
        0x98: UDATA* ramClassUDATABlockFreeList = !j9x 0x0000000000000000
        0xa0: struct J9HashTable* redefinedClasses = !j9hashtable 0x0000000000000000
        0xa8: struct J9NativeLibrary* librariesHead = !j9nativelibrary 0x0000000000000000
        0xb0: struct J9NativeLibrary* librariesTail = !j9nativelibrary 0x0000000000000000
        0xb8: volatile UDATA gcRememberedSet = 0x0000000000000000 (0)
        0xc0: struct J9HashTable* moduleHashTable = !j9hashtable 0x00007FC02C220FE0
        0xc8: struct J9HashTable* packageHashTable = !j9hashtable 0x00007FC02C1FCF70
        0xd0: struct J9HashTable* moduleExtraInfoHashTable = !j9hashtable 0x0000000000000000
        0xd8: struct J9HashTable* classLocationHashTable = !j9hashtable 0x0000000000000000
}

j9jcl.125      > JCL: com.ibm.oti.shared createCPEntries: Entering with helperID=4, **urlCount=0**

The GroovyClassLoader is initialized with urlCount = 0. In this case, we should not allocate memory for its class path entries at shared.c:244 at all.

**Comment by LukeButters** [comment] 2019-07-25 02:44
Would this be something that can be fixed in the LTS java 11?

**Comment by pshipton** [comment] 2019-07-25 03:34
Yes, once the fix is determined it will be fixed for Java 8, 11, 13 and later.

**Comment by jschmied** [comment] 2019-07-25 13:51
I this it's a regression in jdk-11.0.4+11_openj9-0.15.1 it was working before.

**Comment by hangshao0** [comment] 2019-07-25 16:39
The overwrite happens at: 
https://github.com/eclipse/openj9/blob/master/runtime/jcl/common/shared.c#L283

wrapBlockAndSetTags::headerTag is 000000001071D7A0, its size is 0, footerTag is 000000001071D7C0, its size is 0, call site: common/shared.c:244
newCacheItem is **278112000**
unwrapBlockAndCheckTags::headerTag is 000000001071D7A0 and its size is 0, footerTag is 000000001071D7C0 and its size is **278112000**

When urlCount is 0, The cpEntries returned by j9mem_allocate_memory() is actually a pointer to footerTag. It is not memory for cpEntries. We should not allocate memory if urlCount is 0.

**Comment by hangshao0** [comment] 2019-08-06 19:29
When a URLClassLoader is initialized with an empty url array. It calls into notifyClasspathChange3() through SharedClassURLClasspathHelperImpl(). There is no need to allocate memory and create class path entries for the empty array in this case.

**Comment by hangshao0** [comment] 2019-08-07 22:02
The workaround for 0.15.1 builds is to use sub-option `checkURLTimestamps` after `-Xshareclasses:`. e.g. `-Xshareclasses:checkURLTimestamps`

**Comment by LukeButters** [comment] 2019-08-08 00:33
is that workaround needed with the change you made in #6686 ?
How do I get a compiled version of openj9 with your change @hangshao0?

**Comment by hangshao0** [comment] 2019-08-08 14:48
> is that workaround needed with the change you made in #6686 ?

No. It is only needed for builds with out my fix.

> How do I get a compiled version of openj9 with your change

Once the change is merged and go through all our builds, it will be available at https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

**Closed** 2019-08-14 20:32 UTC
Labels: userRaised
