### ISSUE TITLE
Files with umlauts don't exist for J9

### ISSUE THREAD

**Issue by mipastgt** [eclipse/openj9#4466] opened 2019-01-26 17:42 UTC
I just stumbled over an issue with J9 on my Mac (10.13.4 HighSierra). I used the download OpenJDK11U-jdk_x64_mac_openj9_jdk-11.0.1_13_openj9-0.11.0_11.0.1_13.tar.gz from AdoptOpenJDK.
When testing one of my programs I realized that with J9 I could not open any files which contain german umlauts, e.g., a file named "tüst.txt" whereas a file named "test.txt" opens without problem. I have attached a little test program to show this. (You have to create the appropriate files on your local machine of course.) With the hotspot version both files exists. With J9 only the file without umlaut seems to exist.

[DotDirDemo.java.zip](https://github.com/eclipse/openj9/files/2799286/DotDirDemo.java.zip)

**Comment by JasonFengJ9** [comment] 2019-01-31 16:07
Looking at this.

**Comment by pshipton** [comment] 2019-02-05 15:57
Try `javac -encoding UTF8 DotDirDemo.java`

**Comment by pshipton** [comment] 2019-02-05 16:02
What is the output from `java -XshowSettings:properties` on the Mac?

**Comment by AidanHa** [comment] 2019-02-05 16:16
root@5ccc2c132fd6:~/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin# java -XshowSettings:properties -version  
Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    com.ibm.cpu.endian = little
    com.ibm.jcl.checkClassPath = 
    com.ibm.oti.configuration = scar
    com.ibm.oti.shared.enabled = false
    com.ibm.oti.vm.bootstrap.library.path = /root/bootjdk10/lib/compressedrefs
        /root/bootjdk10/lib
    com.ibm.oti.vm.library.version = 29
    com.ibm.system.agent.path = /root/bootjdk10/lib
    com.ibm.util.extralibs.properties = 
    com.ibm.vm.bitmode = 64
    file.encoding = UTF8
    file.encoding.pkg = sun.io
    file.separator = /
    ibm.signalhandling.rs = false
    ibm.signalhandling.sigchain = true
    ibm.signalhandling.sigint = true
    ibm.system.encoding = ANSI_X3.4-1968
    java.awt.fonts = 
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = 
    java.class.version = 54.0
    java.compiler = j9jit29
    java.fullversion = 10.0.2-adoptopenjdk+13
JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13
    java.home = /root/bootjdk10
    java.io.tmpdir = /tmp
    java.library.path = /root/bootjdk10/lib/compressedrefs
        /root/bootjdk10/lib
        /usr/lib64
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 10.0.2-adoptopenjdk+13
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 10
    java.util.prefs.PreferencesFactory = java.util.prefs.FileSystemPreferencesFactory
    java.vendor = Eclipse OpenJ9
    java.vendor.url = http://www.eclipse.org/openj9
    java.version = 10.0.2-adoptopenjdk
    java.version.date = 2018-07-17
    java.vm.info = JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13
    java.vm.name = Eclipse OpenJ9 VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 10
    java.vm.vendor = Eclipse OpenJ9
    java.vm.version = openj9-0.9.0
    jdk.extensions.name = Extensions for OpenJDK for Eclipse OpenJ9
    jdk.extensions.version = 10.0.0.1
    line.separator = \n 
    os.arch = amd64
    os.encoding = ANSI_X3.4-1968
    os.name = Linux
    os.version = 4.9.125-linuxkit
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.library.path = /root/bootjdk10/lib/compressedrefs
        /root/bootjdk10/lib
    sun.cpu.endian = little
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.launcher = SUN_STANDARD
    sun.java.launcher.pid = 62400
    sun.jnu.encoding = ANSI_X3.4-1968
    user.country = US
    user.dir = /root/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin
    user.home = /root
    user.language = en
    user.name = root
    user.timezone = 
    user.variant = 

openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Linux amd64-64-Bit Compressed References 20180813_102 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13)
root@5ccc2c132fd6:~/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin# 

And the command you mentioned above did not work

**Comment by pshipton** [comment] 2019-02-05 16:59
I'm not sure how you got the error in the picture. I got the following when I compiled on Linux, for which `-encoding UTF8` fixed it. Seems UTF8 is the default encoding on Mac according to the file.encoding property. You could always compile it on another platform.
```
/team/peter/DotDirDemo.java:6: error: unmappable character (0xC3) for encoding US-ASCII
                File file2 = new File("target/classes/t??st.txt");
```

**Comment by AidanHa** [comment] 2019-02-05 17:15
I was able to compile the example on MacOS. However I am not able to reproduce the error as both test.txt and tüst.txt are recognized.
![image](https://user-images.githubusercontent.com/33072072/52291125-aa65fd80-293f-11e9-8f84-7d63261e35d8.png)
I am using the same jdk that was used in this issue...

**Comment by JasonFengJ9** [comment] 2019-02-05 19:17
I wasn't able to reproduce this issue either.

@mipastgt do you mind to provide testcase `.class` file as well to rule out compilation difference?

**Comment by mipastgt** [comment] 2019-02-05 21:58
I have attached the output of the above mentioned command on my Mac as a text file.
[output.txt](https://github.com/eclipse/openj9/files/2834048/output.txt)

**Comment by mipastgt** [comment] 2019-02-05 22:11
And here is the requested class file.
[DotDirDemo.class.zip](https://github.com/eclipse/openj9/files/2834065/DotDirDemo.class.zip)

**Comment by mipastgt** [comment] 2019-02-05 22:12
And here is the requested class file. It was compiled with Eclipse against the J9 runtime.
[DotDirDemo.class.zip](https://github.com/eclipse/openj9/files/2834086/DotDirDemo.class.zip)

**Comment by mipastgt** [comment] 2019-02-05 22:17
And just for completeness, here are the test files too.
I just ran the test again. As soon as I switch the runtime to OpenJDK (from Oracle) everything
works, even with the same classfile without recompiling. With the J9 it doesn't.
[test_files.zip](https://github.com/eclipse/openj9/files/2834092/test_files.zip)

**Comment by pshipton** [comment] 2019-02-05 23:09
@mipastgt did you mean to close this issue?

**Comment by mipastgt** [comment] 2019-02-05 23:47
No, sorry. I must have hit a wrong button.

**Comment by mipastgt** [comment] 2019-02-06 10:09
Sorry, I missed that piece of code which just prints some version numbers to be sure that I am really running on the right platform. I've now packed everything in a separate Eclipse project and zipped it. See attachement. It also contains a file with the test results with two other VMs. The first of these is the AdoptJDK hotspot variant and the other one is the Oracle OpenJDK. The project JDK was the J9, but according to my tests it does not matter against which JDK the code is compiled. The only thing what matters is which runtime JDK is used to run the code.

In case this should be relevant. My machine is a MacBook Pro with 10.13.4 HighSierra and the new file system APFS. I also tried to put the test files on an USB-stick with FAT32 but that does not make a difference. I also tried re-compiling the code with several other JDKs (Azul, Bellsoft, ...) and all of them work correctly. It's only the J9 which consistently shows this strange behaviour.
[J9Eval.zip](https://github.com/eclipse/openj9/files/2835730/J9Eval.zip)

**Comment by JasonFengJ9** [comment] 2019-02-06 19:52
fyi @AidanHa

**Comment by AidanHa** [comment] 2019-02-06 20:17
Sorry, some issues came up with previous PRs that I have been working on. I will try to replicate the issue as soon as I can. Have you tried replicating it @JasonFengJ9 ?

**Comment by JasonFengJ9** [comment] 2019-02-06 23:46
Just tried, unfortunately the issue reported wasn't reproduced.

@AidanHa if you can't reproduce this issue either, the next step would be to identify the environment difference, or provide @mipastgt an instrumental patch or `JVM` to understand the problem, please reach out to @tajila or myself for help if needed.

**Comment by mipastgt** [comment] 2019-02-07 12:49
Concerning the environment:
I use Eclipse 2018-12 (4.10.0) which itself is running on Oracles OpenJDK 11.0.2.
My Mac is set to have german as its default locale and the default file encoding is UTF-8.

**Comment by mipastgt** [comment] 2019-02-07 13:37
I did some further tests and I consistently get the reported error when I run the program from within Eclipse. But I have now also tried to run it from the command line and there it works as it should. This must be a very strange interaction with Eclipse for which I do not have any explanation. I leave it up to you whether you think it is worth further investigation. I do not normally use the J9 so it is no real problem for me.
[results.txt](https://github.com/eclipse/openj9/files/2841007/results.txt)

**Comment by AidanHa** [comment] 2019-02-07 13:43
Thanks for the follow up @mipastgt. As you mentioned above, I was unsuccessful in reproducing the issue on the command line, but I will try to pinpoint the issue with the information you just gave.

**Comment by pshipton** [comment] 2019-02-07 14:15
@mipastgt can you please check the command line that Eclipse is using to launch the OpenJ9 test. Likely the answer is there, perhaps Eclipse is changing the default file encoding.

**Comment by mipastgt** [comment] 2019-02-07 14:41
This is the command line indicated by Eclipse:
`/Library/Java/JavaVirtualMachines/jdk-11.0.1-adopt-j9/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath <my home dir>/Projects/LocalEval/J9Eval/bin jdks.DotDirDemo`

**Comment by AidanHa** [comment] 2019-02-07 16:35
I am still unable to replicate this issue even WITH the Eclipse IDE:

Command Line:
/Users/Aidan.Ha@ibm.com/Downloads/jdk-11.0.2+9_openj9-0.12.1 2/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath /Users/Aidan.Ha@ibm.com/Downloads/J9Eval/bin jdks.DotDirDemo

![image](https://user-images.githubusercontent.com/33072072/52426521-22f9c500-2acc-11e9-95d3-8b53b530f08b.png)

I carefully made sure that both the environment and code (package) were the same. I tried running it both with the prebuilt JDK as well as using the jdk that I built on my local machine (both match the version given in the issue).

**Comment by mipastgt** [comment] 2019-02-07 16:48
But your output clearly shows that you are using the most recent 11.0.2+9 build whereas I am still using the older 11.0.1+13 release because the newer one was not yet available at the time when I made my initial tests. Before you invest any more time let me try it with the new version.

**Comment by AidanHa** [comment] 2019-02-07 16:55
@mipastgt My fault, I must've accidentally grabbed the wrong one from the website. I've ran it with JDK 11.0.1+13, and I have successfully replicated the Issue. So perhaps this was fixed in the most recent version?

Sorry about that.

**Comment by mipastgt** [comment] 2019-02-07 17:00
Success!!! I just installed the new version and  voila, it works.
I am glad we got that sorted out now. The previous version must have been broken somehow.

<img width="959" alt="bildschirmfoto 2019-02-07 um 17 56 19" src="https://user-images.githubusercontent.com/16735714/52428294-f3fe4600-2b01-11e9-8d3d-a60e3eb66283.png">

**Comment by AidanHa** [comment] 2019-02-07 18:57
Great! Should this issue be closed now?

**Comment by mipastgt** [comment] 2019-02-07 19:00
As far as I am concerned it can be closed.

**Closed** 2019-02-07 19:35 UTC
Labels: comp:vm, userRaised
