### ISSUE TITLE
AdoptOpenJDK11 with EclipseJ9 3x slower than HotSpot on AES & RSA encoding & decoding

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#3636] opened 2018-11-10 23:09 UTC
Hello,

I have identified that EclipseJ9 is x3 shower than HotSpot (using AdoptOpenJDK11 on Linux) for AES and RSA encoding and decoding.

Here's a sample code to reproduce the issue with 200000 iterations doing the following sequence:
1. AES 128 decoding
2. RSA 512 decoding
3. RSA 512 encoding
4. AES 128 encoding

Results on a physical machine Linux CentOS 7.4.1708 with 8 cores - Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (fam: 06, model: 55, stepping: 04), 32GB RAM :

HOTSPOT
$ time ./java -showversion /u/users/ple/TestCrypto.java
openjdk version "11" 2018-09-25 
OpenJDK Runtime Environment 18.9 (build 11+28) 
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode) 
server: numberOfRequests 200000 average duration 87 microseconds 

real    0m18.48s 
user    0m20.99s 
sys     0m0.44s 

OPENJ9
$ time ./java -showversion /u/users/ple/TestCrypto.java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux amd64-64-Bit Compressed References 20181020_70 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)
server: numberOfRequests 200000 average duration 256 microseconds

real    0m52.43s
user    0m59.70s
sys     0m1.29s

See attached file for the code code of the sample.

[TestCrypto.zip](https://github.com/eclipse/openj9/files/2568874/TestCrypto.zip)

Not sure, but got the feeling that AdoptOpenJDK11 with EclipseJ9 (latest version downloaded from AdoptOpenJDK site) isn't using opensll to accelerate encryption.

Any idea if that could be fixed in an update of ElipseJ9, at least in the GitHut some I could rebuild AdoptOpenJDK11 with this fix to check if we have other performance loss with J9 vs HotSpot with our app?

Kind regards,
Alexandre

**Comment by pshipton** [comment] 2018-11-12 14:04
@ashbm5

**Comment by pshipton** [comment] 2018-11-12 14:05
@vijaysun-omr

**Comment by pshipton** [comment] 2018-11-12 14:06
@avermeer you are correct, JDK11 is not using openssl acceleration yet, only jdk8. jdk11 support for openssl is expected in a future version https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/31

**Comment by DanHeidinga** [comment] 2018-11-12 14:13
@pshipton is ibmruntimes/openj9-openjdk-jdk11#31 expected to land in the `0.12.0` release?  If that's the case, we should open a tracking issue here and assign to the `0.12.0` milestone

**Comment by pshipton** [comment] 2018-11-12 14:47
> is ibmruntimes/openj9-openjdk-jdk11#31 expected to land in the 0.12.0 release?

@ashbm5 @enasser ?

**Comment by vijaysun-omr** [comment] 2018-11-14 00:37
v0.11.0 is a release of OpenJ9 that is used in both JDK11 and JDK8. 
The "what's new" page does mention the fact that OpenSSL support was only available on JDK8 but maybe you were considering that page to be about what is in JDK11 (perhaps thinking that v0.11.0 is somehow associated only with JDK11 ?).
I think @enasser will likely be the one to confirm if the JDK11 support will land in v0.12.0 of OpenJ9 but I think it is possible that it will. 
If v0.12.0 of OpenJ9 releases before JDK12 comes out then I expect it will be used in both JDK11 and JDK8.

**Comment by pshipton** [comment] 2018-11-14 04:05
> If v0.12.0 of OpenJ9 releases before JDK12 comes out then I expect it will be used in both JDK11 and JDK8.

Correct, 0.12.0 [1] is scheduled for January and will support jdk8 and jdk11. 
0.13.0 is scheduled for March to introduce Java 12 support.
List of scheduled releases https://www.eclipse.org/openj9/docs/openj9_support/

[1] https://projects.eclipse.org/projects/technology.openj9/releases/0.12.0/plan

**Comment by avermeer** [comment] 2018-11-14 09:51
Hello,

  I'd love to see an AdoptOpenJDK11 release based on 0.12.0 that fixes this OpenSSL acceleration issue, but the plan https://www.eclipse.org/openj9/docs/openj9_support/ explicitly mentions that 0.12.0 is not targeted for JDK11(LTS).
  Is  https://www.eclipse.org/openj9/docs/openj9_support/ table outdated, or is OpenSSL acceleration "dead" for AdoptOpenJDK11 ?

Kind regards,
Alexandre

**Comment by DanHeidinga** [comment] 2018-11-14 15:09
That page is incorrect.  I think I messed the table up when updating it for our 6 release a year policy.  The project intends to ship quarterly releases that line up with the OpenJDK updates and to have two additional releases (March & Sept) that target only the new JDK levels.

I'll get that page updated to indicate that 0.12.0 will include updates for JDK8 & JDK11

**Comment by avermeer** [comment] 2018-12-13 21:01
Hello,

Is there any hope that this performance issue on Java crypto APIs will be fixed in OpenJ9  upcoming 0.12.0 release? it's quite an hard blocker for our adoption of J9 vs HotSpot...

Kind regards,
Alexandre

**Comment by fjeremic** [comment] 2018-12-13 22:12
> Is there any hope that this performance issue on Java crypto APIs will be fixed in OpenJ9 upcoming 0.12.0 release? it's quite an hard blocker for our adoption of J9 vs HotSpot...

The fix has landed in ibmruntimes/openj9-openjdk-jdk11. I think it should be available now. @pshipton can you confirm?

**Comment by enasser** [comment] 2018-12-14 03:14
Yes @fjeremic Openssl support feature is merged. There were few build configuration issues while merging which is mostly fixed and the builds should be available soon. @pshipton please confirm.

**Comment by pshipton** [comment] 2018-12-14 03:52
@avermeer According to @sxa555 in Slack https://openj9.slack.com/messages/CBCEMDZE2, it seems the latest set of jdk11 nightly builds at AdoptOpenJDK.net should have openssl enabled and resolve this issue.

**Comment by pshipton** [comment] 2018-12-14 03:59
Sorry, the dates of the AdoptOpenJDK builds are misleading. The latest build shows Dec 13 but is a build from the 10th according to the dates of the files. Please check the next nightly builds.

**Comment by pshipton** [comment] 2018-12-14 12:19
The builds for Dec 14 have openssl enabled, except on macOS.

**Comment by avermeer** [comment] 2018-12-17 23:06
Hello,

I have bad news : we ran tests with the latest AdoptOpenJDK11 with OpenJ9 builds, and it shows this performance issue has not been fixed.
Let me give details below, please let me know if I was mistaken somewhere.

These tests are based on the same TestCrypto.java sample code which I shared while opening this ticket.

As a reminder, with October AdoptOpenJD11 with HotSpot we had:

Hotspot :
```
time ./java -showversion /u/users/ple/TestCrypto.java
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
server: numberOfRequests 200000 average duration 87 microseconds

real    0m20.01s
user    0m21.23s
sys     0m0.52s
```

With AdoptOpenJDK11 with OpenJ9 october release we had:

```
time ./java -showversion /u/users/ple/TestCrypto.java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux amd64-64-Bit Compressed References 20181020_70 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)
server: numberOfRequests 200000 average duration 260 microseconds

real    0m53.46s
user    0m59.91s
sys     0m1.42s
```

With latest AdoptOpenJDK11 with OpenJ9 nightly build, we have still have disapointing results versus HotSpot, whether or not native crypto is activated:

```
time ./java -showversion -Djdk.nativeCrypto=true /u/users/ple/TestCrypto.java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201812161931)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f9ab45bfe, JRE 11 Linux amd64-64-Bit Compressed References 20181216_61 (JIT enabled, AOT enabled)
OpenJ9   - f9ab45bfe
OMR      - 0d514697
JCL      - f6d23ec079 based on jdk-11.0.1+13)
server: numberOfRequests 200000 average duration 256 microseconds

real    0m52.73s
user    0m58.47s
sys     0m1.38s
```

```
time ./java -showversion -Djdk.nativeCrypto=false /u/users/ple/TestCrypto.java
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13-201812161931)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-f9ab45bfe, JRE 11 Linux amd64-64-Bit Compressed References 20181216_61 (JIT enabled, AOT enabled)
OpenJ9   - f9ab45bfe
OMR      - 0d514697
JCL      - f6d23ec079 based on jdk-11.0.1+13)
server: numberOfRequests 200000 average duration 263 microseconds

real    0m53.95s
user    1m0.90s
sys     0m1.55s
```


I wish you could tell me I'm wrong somewhere with these tests, but so far I still get HotSpot ~3x faster than OpenJ9.

Did I miss something?

Kind regards,
Alexandre

**Comment by pshipton** [comment] 2018-12-17 23:45
@enasser can you please take a look

**Comment by pshipton** [comment] 2018-12-18 00:15
I tried running TestCrypto with `-Djdk.nativeCryptoTrace=true` and got the following. 
```
Warning: Native crypto library load failed. Using Java crypto implementation
Warning: Native crypto library load failed. Using Java crypto implementation
```

There doesn't seem to be any debug option to tell us why it failed, but I tried loading the crypto library and got `Exception in thread "main" java.lang.UnsatisfiedLinkError: jncrypto (libssl.so.1.1: cannot open shared object file: No such file or directory)`
Indeed `libssl.so.1.1` is not included in the build.

```
ldd ./jdk-11.0.1+13/lib/libjncrypto.so
...
libssl.so.1.1 => not found
...
```

Checking the jdk8 libjncrypto.so, there is no reference to `libssl.so.1.1`. Seems something is wrong with the jdk11 build.

**Comment by pshipton** [comment] 2018-12-18 13:46
The fix https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/83 is merged. Will check the next Adopt build to confirm.

**Comment by pshipton** [comment] 2018-12-18 14:15
Built on xlinux myself to check. libssl.so is not longer a prereq of libjncrypto.so
Running TestCrypto with `-Djdk.nativeCryptoTrace=true` results in the following, now correct, behavior.
```
MessageDigest load - using Native crypto library.
CipherCore Load - using native crypto library.
```

Not sure time to run the test is improved. I got about the same results with and without `-Djdk.nativeCrypto=false`, but I'm using a cloud machine so results may vary.

**Comment by ashbm5** [comment] 2018-12-18 16:03
The reason for the slowdown when compared to hotspot is that the OpenSSL functionality that was added to OpenJ9 doesn't support RSA yet. As announced, the following algorithms use OpenSSL: AES/GCM, AES/CBC and SHA* hashing routines. 

You do notice a very small perf. gain when enabling OpenSSL support as compared to disabled OpenSSL due to the perf. increase of the AES/CBC algorithm in your benchmark. However, RSA/ECB is taking the vast majority of time in your benchmark and since it is not using OpenSSL it is significantly slower.

When benchmarking only RSA/ECB - I'm seeing 2-3x slower on OpenJ9, corresponding to your observations.

Given this, Having RSA also leverage OpenSSL looks like an important work item to work on next.

**Comment by enasser** [comment] 2018-12-18 18:03
As @ashbm5 explained above the current openssl support did not help to improve the performance of the scenario in test case TestCrypto. Both Openj9 JDK 8 and JDK 11 giving similar results with OpenSSL support while testing with TestCrypto. Need to include the corresponding algorithm with OpenSSL support in order to fix this performance gap.

**Comment by avermeer** [comment] 2018-12-18 18:19
Hello @enasser ,

Thank you (and the other involved developers) very much for your tenacious attempts to get this issue fixed.
And please apologies for this trivial question: would it be affordable to get this performance issue resolved in time for 0.12.0 release?

Kind regards,
Alexandre

**Comment by ashbm5** [comment] 2018-12-18 20:47
@avermeer - we will try our best but no promises.

**Comment by ashbm5** [comment] 2019-01-04 19:41
@avermeer is it essential for this RSA support to be rolled into 0.12 release or having the feature appear in one of the nightly builds a bit after 0.12 be satisfactory? is this for production use or prototyping/experimentation?

**Comment by pshipton** [comment] 2019-01-11 12:39
It seems this is not going to be resolved in the 0.12 release, moving to the next one.

**Comment by avermeer** [comment] 2019-01-11 13:05
Oh this is very sad that it's not going to be resolved in 0.12.0 release.
When would it resolved at best?

**Comment by ashbm5** [comment] 2019-01-11 15:23
Probably in the next two weeks it will be in the nightly build. I have confirmed that accelerating RSA w/ OpenSSL resolves the performance issue mentioned above using the test code posted.

**Comment by avermeer** [comment] 2019-01-11 15:56
@ashbm5, that would be outstanding, thanks!

**Comment by pshipton** [comment] 2019-01-11 16:04
The 0.12 release is scheduled to GA on Jan 23, we should try to squeeze it in if possible.

**Comment by pshipton** [comment] 2019-01-11 19:12
Set this back to the 0.12 milestone. Alon thinks jdk8 can have a PR opened on Monday, and jdk11 will follow, TBD how long it will take to port.

**Comment by vij-singh** [comment] 2019-01-15 15:24
@ashbm5 Alon are there any updates?

**Comment by pshipton** [comment] 2019-01-21 12:34
No, the code is not yet delivered.

**Comment by Siarhei-Yarkavy** [comment] 2019-01-22 08:04
I think it makes sense to wait with the release but deliver those important fixes.

**Comment by avermeer** [comment] 2019-01-22 08:50
Hello @Siarhei-Yarkavy,

If you mean delay the 0.12.0 release until this issue is fixed, then I agree.
As soon as there is something which I can test on nightly builds, I will happily test & provide feedbacks.

Kind regards,
Alexandre

**Comment by SueChaplain** [comment] 2019-01-24 12:16
I've added the doc:externals label as the addition of RSA support needs to be included in the user documentation. @vij-singh - please have someone open an issue at openj9-docs with the content we need: https://github.com/eclipse/openj9-docs/issues/new?template=new-documentation-change.md

I'll need to know whether it is enabled by default as per the other algorithms, and whether there will be a new -D system property as per the other algorithms.

**Comment by pshipton** [comment] 2019-01-24 13:10
Thanks @SueChaplain. I've created https://github.com/eclipse/openj9-docs/issues/201

**Comment by pshipton** [comment] 2019-01-24 21:26
Fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/100 and https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/103.

I won't close this until the jdk8 changes are delivered as well.

**Comment by pshipton** [comment] 2019-01-29 14:13
The RSA acceleration work is completed.

**Closed by pshipton** 2019-01-29 14:13 UTC
Labels: doc:externals, perf, userRaised

**Comment by avermeer** [comment] 2019-01-31 17:42
Hello,

We have verified on our side, and the performance issue related to this ticket is indeed fixed, this is outstanding => thank you very much for having kept this for the 11.0.2 OpenJ9 release, just in time !!

Kind regards,
Alexandre
