### ISSUE TITLE
JDK8 JIT Server : MathLoadTest_all_ConcurrentScavenge_0_FAILED Segmentation error vmState=0x00000000 at libj9gc29.so

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9221] opened 2020-04-11 23:20 UTC
Failure link
------------

From an internet build `Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/45`:
```
22:57:20  openjdk version "1.8.0_252-internal"
22:57:20  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_04_10_21_40-b00)
22:57:20  Eclipse OpenJ9 VM (build ibm_sdk-70d2e4b6b2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200410_46 (JIT enabled, AOT enabled)
22:57:20  OpenJ9   - 70d2e4b6b2
22:57:20  OMR      - f30df531c
22:57:20  JCL      - 61d22079a86 based on jdk8u252-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
MLT 23:23:17.487 -   103 ArbitraryJava[net.adoptopenjdk.test.autosimd.AutoSIMDTestLong testSums]  Weighting=1 
MLT 23:23:17.488 -   104 JUnit[net.adoptopenjdk.test.math.MathAPITest]  Weighting=1 
MLT 23:23:17.569 - Starting thread. Suite=0 thread=0
MLT 23:23:17.572 - Starting thread. Suite=0 thread=1
MLT 23:23:17.572 - Starting thread. Suite=0 thread=2
MLT stderr 00000000017AE000: J9_INVALID_OBJECT in thread load-2
MLT stderr 00000000017AE000:	O-Slot=00007FFABC157138
MLT stderr 00000000017AE000:	O-Slot value=FFFFFFFFFFFFFFFF
MLT stderr 00000000017AE000:	PC=00007FFAF428A8F7
MLT stderr 00000000017AE000:	framesWalked=2
MLT stderr 00000000017AE000:	arg0EA=00000000017B5588
MLT stderr 00000000017AE000:	walkSP=00000000017B5468
MLT stderr 00000000017AE000:	literals=0000000001971BC8
MLT stderr 00000000017AE000:	jitInfo=00007FFAEDCBB6F8
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
MLT stderr Handler1=00007FFB0FD0C780 Handler2=00007FFB0F8189F0 InaccessibleAddress=00007FFA959376D0
MLT stderr RDI=00007FFA94038B62 RSI=00007FFA959376D2 RAX=00007FFB07C710BB RBX=00007FFB146F8340
MLT stderr RCX=0000000001519DC8 RDX=00000000017AE000 R8=00007FFB07C32273 R9=00007FFA94038BAA
MLT stderr R10=00007FFA94038BA8 R11=00007FFA959376D0 R12=00007FFABC1570B0 R13=00007FFB07ED9840
MLT stderr R14=00007FFB10218AB8 R15=00007FFA94038B60
MLT stderr RIP=00007FFB07BE51E7 GS=0000 FS=0000 RSP=00007FFABC157018
MLT stderr EFlags=0000000000010216 CS=0033 RBP=00000000017AE000 ERR=0000000000000004
MLT stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FFA959376D0
MLT stderr xmm0 0000003000000020 (f: 32.000000, d: 1.018558e-312)
MLT stderr xmm1 ffff000000000000 (f: 0.000000, d: -nan)
MLT stderr xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr xmm3 00007ffa00000001 (f: 1.000000, d: 6.952083e-310)
MLT stderr xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr xmm7 0000000038c73bcc (f: 952581056.000000, d: 4.706376e-315)
MLT stderr xmm8 0000000036fac000 (f: 922402816.000000, d: 4.557275e-315)
MLT stderr xmm9 000000003c075284 (f: 1007112832.000000, d: 4.975799e-315)
MLT stderr xmm10 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
MLT stderr xmm11 3fefae147ae147ae (f: 2061584256.000000, d: 9.900000e-01)
MLT stderr xmm12 3fe311ac17eebc51 (f: 401521760.000000, d: 5.959073e-01)
MLT stderr xmm13 411f916000000000 (f: 0.000000, d: 5.172080e+05)
MLT stderr xmm14 3fefae147ae147ae (f: 2061584256.000000, d: 9.900000e-01)
MLT stderr xmm15 410930526ec940ad (f: 1858683008.000000, d: 2.063463e+05)
MLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so
MLT stderr Module_base_address=00007FFB079FB000
MLT stderr Target=2_90_20200410_46 (Linux 2.6.32-754.27.1.el6.x86_64)
MLT stderr CPU=amd64 (4 logical CPUs) (0x1f4100000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x00007FFB07BE51E7 [libj9gc29.so+0x1ea1e7])
MLT stderr (0x00007FFB07C145AA [libj9gc29.so+0x2195aa])
MLT stderr (0x00007FFB08152AC9 [libj9jit29.so+0x277ac9])
MLT stderr (0x00007FFB088024D4 [libj9jit29.so+0x9274d4])
MLT stderr (0x00007FFB0FD3CA9E [libj9vm29.so+0xc3a9e])
MLT stderr (0x00007FFB07A3A676 [libj9gc29.so+0x3f676])
MLT stderr (0x00007FFB07C14B2C [libj9gc29.so+0x219b2c])
MLT stderr (0x00007FFB07B7F97A [libj9gc29.so+0x18497a])
MLT stderr (0x00007FFB07B3CF3E [libj9gc29.so+0x141f3e])
MLT stderr (0x00007FFB0FD0DD47 [libj9vm29.so+0x94d47])
MLT stderr (0x00007FFB0FC8B938 [libj9vm29.so+0x12938])
MLT stderr (0x00007FFB0FC8BC1C [libj9vm29.so+0x12c1c])
MLT stderr (0x00007FFB0FC8BAE0 [libj9vm29.so+0x12ae0])
MLT stderr (0x00007FFB0FD47792 [libj9vm29.so+0xce792])
MLT stderr ---------------------------------------

MathLoadTest_all_ConcurrentScavenge_0_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-64_linux&TARGET=MathLoadTest_all_ConcurrentScavenge_0

**Comment by dmitripivkine** [comment] 2020-04-13 13:47
I will double check but it looks like another duplicate of https://github.com/eclipse/openj9/issues/8789, https://github.com/eclipse/openj9/issues/9123

**Comment by dmitripivkine** [comment] 2020-04-13 15:02
Unfortunately DDR failed to walk problematic java stack for thread 0x17AE000. However I can observe number of just unloaded classes around. If you need my help with deeper investigation please let me know.
I guess all problems such this relate to https://github.com/eclipse/openj9/issues/9212

**Comment by a7ehuo** [comment] 2020-05-07 19:59
Tried the build as below on `04/30` in Grinder, FR: `1/100`.

18:52:20  JITServer is ready to accept incoming requests
18:52:20  openjdk version "1.8.0_262-internal"
18:52:20  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_04_30_14_10-b00)
18:52:20  Eclipse OpenJ9 VM (build master-ef109f7c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200430_1436 (JIT enabled, AOT enabled)
18:52:20  OpenJ9   - ef109f7c2
18:52:20  OMR      - f2285166b
18:52:20  JCL      - ed7c83cea53 based on jdk8u262-b01)

**Comment by dmitry-ten** [comment] 2020-08-24 18:19
150 [runs](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/9804), 0 failures.
@mpirvu this issue was most likely fixed by other changes and can be closed.

**Comment by mpirvu** [comment] 2020-08-24 19:30
Closing based on the above comment

**Closed by mpirvu** 2020-08-24 19:30 UTC
Labels: comp:jitserver, segfault, test failure
