### ISSUE TITLE
JDK8 JITServer : ClassCastException: [I incompatible with java.lang.reflect.Method 

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9540] opened 2020-05-12 22:30 UTC
Failure link
------------

From an internal build `Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly_mathLoadTest/10`:
```
01:01:17  openjdk version "1.8.0_262-internal"
01:01:17  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_05_11_21_17-b00)
01:01:17  Eclipse OpenJ9 VM (build ibm_sdk-3abfb62305, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200511_77 (JIT enabled, AOT enabled)
01:01:17  OpenJ9   - 3abfb62305
01:01:17  OMR      - 295075ec1
01:01:17  JCL      - d0099f2c689 based on jdk8u262-b01)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test MathLoadTest_all_special_12 ...
===============================================

MLT 22:06:26.582 - Completed 66.9%. Number of tests started=3510 (+485)
MLT 22:06:39.705 - First failure detected by thread: load-2. Not creating dumps as no dump generation is requested for this load test
MLT 22:06:39.706 - Test failed
MLT   Failure num.  = 1
MLT   Test number   = 19
MLT   Test details  = 'JUnit[net.adoptopenjdk.test.bigdecimal.TestSuite019]'
MLT   Suite number  = 0
MLT   Thread number = 2
MLT >>> Captured test output >>>
MLT Test failed:
MLT java.lang.ClassCastException: [I incompatible with java.lang.reflect.Method
MLT 	at java.lang.Class.lookupCachedMethod(Class.java:3636)
MLT 	at java.lang.Class.getMethodHelper(Class.java:1239)
MLT 	at java.lang.Class.getMethod(Class.java:1191)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.getAnnotations(JUnit38ClassRunner.java:131)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.makeDescription(JUnit38ClassRunner.java:101)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.makeDescription(JUnit38ClassRunner.java:109)
MLT 	at org.junit.internal.runners.JUnit38ClassRunner.getDescription(JUnit38ClassRunner.java:95)
MLT 	at org.junit.runners.Suite.describeChild(Suite.java:123)
MLT 	at org.junit.runners.Suite.describeChild(Suite.java:27)
MLT 	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:352)
MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
MLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
MLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
MLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
MLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
MLT 	at java.lang.Thread.run(Thread.java:823)
MLT <<<
MLT 
MLT 22:06:43.428 - Test failed. Details recorded in execution log.
MLT 22:06:46.566 - Completed 76.5%. Number of tests started=4017 (+507) (with 2 failure(s))
MLT 22:06:51.631 - Test failed. Details recorded in execution log.
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/mathLoadTest&PLATFORM=x86-64_linux&TARGET=MathLoadTest_all_special_12

**Comment by pshipton** [comment] 2020-05-12 22:44
@mpirvu

**Comment by EmanElsaban** [comment] 2020-11-06 15:38
Ran 100 tests on Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11896/. Everything passed. It seems like the problem is fixed, probably due to other changes.

From console output:
java version:
```
18:04:54  set TEST_ROOT to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/..
18:04:54  set JDK_VERSION to 8
18:04:54  set JDK_IMPL to openj9
18:04:54  set JVM_VERSION to openjdk8-openj9
18:04:54  set JCL_VERSION to latest
18:04:54  set JAVA_HOME to /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
18:04:54  set SPEC to linux_x86-64_cmprssptrs
18:04:54  Running MathLoadTest_all_special_12 ...
18:04:54  There are 1 test targets in MathLoadTest_all_special_12
18:04:54  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
18:04:54  openjdk version "1.8.0_272"
18:04:54  OpenJDK Runtime Environment (build 1.8.0_272-202011041720-b10)
18:04:54  Eclipse OpenJ9 VM (build master-a236ce7ee, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201104_839 (JIT enabled, AOT enabled)
18:04:54  OpenJ9   - a236ce7ee
18:04:54  OMR      - e5f5e201d
18:04:54  JCL      - 289ae443 based on jdk8u272-b10)
```
FYI: @mpirvu

**Comment by EmanElsaban** [comment] 2020-11-12 14:12
I reran 200 tests on Grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11982/. Everything passed. 
From Console output:
java version:
```
07:28:55  set TEST_ROOT to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/..
07:28:55  set JDK_VERSION to 8
07:28:55  set JDK_IMPL to openj9
07:28:55  set JVM_VERSION to openjdk8-openj9
07:28:55  set JCL_VERSION to latest
07:28:55  set JAVA_HOME to /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
07:28:55  set SPEC to linux_x86-64_cmprssptrs
07:28:55  Running MathLoadTest_all_special_12 ...
07:28:55  There are 1 test targets in MathLoadTest_all_special_12
07:28:55  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
07:28:55  openjdk version "1.8.0_275-internal"
07:28:55  OpenJDK Runtime Environment (build 1.8.0_275-internal-202011091720-b01)
07:28:55  Eclipse OpenJ9 VM (build master-bd1f483c1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201109_844 (JIT enabled, AOT enabled)
07:28:55  OpenJ9   - bd1f483c1
07:28:55  OMR      - e1903b901
07:28:55  JCL      - 04fa7040 based on jdk8u275-b01)
```

In addition, I checked all builds for this test failure ```MathLoadTest_all_special_12``` dated back to 547(28-10-2020) on https://hyc-runtimes-jenkins.swg-devops.com/view/Nightly/job/Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly/ , it passed in all these tests. I also checked in jdk11 (https://hyc-runtimes-jenkins.swg-devops.com/view/Nightly/job/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/) back to build 544(28-10-2020), passed in all these tests as well.

The problem seems to be fixed by another change, I think it should be closed. @mpirvu

**Comment by mpirvu** [comment] 2020-11-12 14:17
Closing based on the last two comments.

**Closed** 2020-11-12 14:17 UTC
Labels: comp:jitserver, test failure
