### ISSUE TITLE
x86-6 Storage is not completely initialized

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7593] opened 2019-10-25 12:59 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_mac_Nightly/77
DaaLoadTest_daa3_0
```
DLT java.lang.InternalError: Storage is not completely initialized, 4 bytes left
DLT 	at java.base/java.lang.StringConcatHelper.newString(StringConcatHelper.java:401)
DLT 	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:298)
DLT 	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
DLT 	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
DLT 	at java.base/java.lang.invoke.FilterArgumentsHandle.invokeExact_thunkArchetype_X(FilterArgumentsHandle.java:85)
DLT 	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.addResult(JUnitAdaptor.java:120)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.testFinished(JUnitAdaptor.java:80)
DLT 	at org.junit.runner.notification.SynchronizedRunListener.testFinished(SynchronizedRunListener.java:56)
DLT 	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:190)
DLT 	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
DLT 	at org.junit.runner.notification.RunNotifier.fireTestFinished(RunNotifier.java:187)
DLT 	at org.junit.internal.runners.model.EachTestNotifier.fireTestFinished(EachTestNotifier.java:38)
DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:331)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
```

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=system&JenkinsFile=openjdk_x86-64_mac&TARGET=DaaLoadTest_daa3_0&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK13_x86-64_mac_Nightly/101/OpenJ9-JDK13-x86-64_mac-20191025-023354.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK13_x86-64_mac_Nightly/101/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by andrewcraik** [comment] 2019-10-25 13:24
@pshipton is this tagged JIT because it passes -Xint?

**Comment by pshipton** [comment] 2019-10-25 13:58
Right sorry, removing the tag.

**Comment by pshipton** [comment] 2019-10-31 12:53
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_mac_Nightly/83

**Comment by JasonFengJ9** [comment] 2019-11-03 15:38
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_windows_Nightly/86/tapResults/

**Comment by smlambert** [comment] 2019-11-03 15:49
The above failure is a different test target (MathLoadTest_all_0), but failing in the same way... 

'Rerun' link:
https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=system&JenkinsFile=openjdk_x86-64_windows&TARGET=MathLoadTest_all_0&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK13_x86-64_windows_Nightly/110/OpenJ9-JDK13-x86-64_windows-20191103-023356.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK13_x86-64_windows_Nightly/110/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by pshipton** [comment] 2019-11-04 16:19
@DanHeidinga can you pls take a look.

**Comment by DanHeidinga** [comment] 2019-11-04 16:39
This appears to be related to the String Concat using Indy feature.

The current stack trace shows mostly thunkArchetype methods (ie the JIT's JSR 292 implementation) - see
```
DLT 	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:298)
DLT 	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
```
with the final failing call in:
https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/2445b05329a2f5dc7eebd432361788307994da18/src/java.base/share/classes/java/lang/StringConcatHelper.java#L394-L403

@andrewcraik Can someone on the JIT team look at this as the "interesting" parts of the stack are all compiled 292 implementation?  The final call that throws the exception is only reading the data passed in from the compiled code.

**Comment by andrewcraik** [comment] 2019-11-04 18:09
We are a bit busy but I will put this on the list for when someone has time.

**Comment by hzongaro** [comment] 2019-11-05 15:57
> Can someone on the JIT team look at this

Andrew asked me to investigate the problem

**Comment by hzongaro** [comment] 2019-11-06 02:40
I saw 11/100 failures with MathLoadTest_all_0 on Windows in a grinder run; 0/100 failures with DaaLoadTest_all_0 on MacOS.

**Comment by hzongaro** [comment] 2019-11-11 22:01
Still working on narrowing down what's going on.  Here's an update.

I haven't been able to reproduce the failure when I tried to gather core and javacore files using `-Xdump:java+system:events=throw,filter=java/lang/InternalError,range=1..3`, so I've been a bit slowed trying to pinpoint the problematic code.

I can reproduce the problem on Windows with builds beginning going back to https://ci.eclipse.org/openj9/job/Build_JDK13_x86-64_windows_Nightly/89/:

- [Grinder run](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/3424/) with [nightly Windows build 101](https://ci.eclipse.org/openj9/job/Build_JDK13_x86-64_windows_Nightly/101/) fails 4/50

This [grinder run on Windows with `-Xjit:exclude={net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor*.testFinished*}`](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/3352/) passed 50/50, so I've gathered logs for `testFinished`.  I'm currently trying to narrow down optimizations on `testFinished` with `lastOptIndex` in hopes that will provide a clue to where things are going wrong.

**Comment by hzongaro** [comment] 2019-11-18 03:16
A little more information.  The error reported states

```
java.lang.InternalError: Storage is not completely initialized, 4 bytes left
```

The string concatenation that's involved in [`JUnitAdaptor$1.addResult`](https://github.com/AdoptOpenJDK/stf/blob/f7d33b5261489635dee9b7df24600dd10f7229d4/stf.load/src/stf.load/net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor.java#L114-L124) looks like this:

```
String resultLine = "platform=" + platform 
			+ " result=" + status 
			+ " class=" + description.getClassName() 
			+ " test=" + description.getMethodName() 
			+ messageText
			+ exceptionText; 
resultsText.append(resultLine + "\n");
```

The only one of those strings whose is length is four is the value of `status` - from the [call to  `addResult` in `testFinished`](https://github.com/AdoptOpenJDK/stf/blob/f7d33b5261489635dee9b7df24600dd10f7229d4/stf.load/src/stf.load/net/adoptopenjdk/loadTest/adaptors/JUnitAdaptor.java#L80), the value is `"pass"`.

I attempted replacing the value passed in with the string `"abcdefghjijklmnopqrstuvwxyz"`, along with some additional debugging code in `StringConcatHelper.newString` to include the value of the concatenated string in the error that is thrown.  The error that was reported with those changes was:

```
java.lang.InternalError: Storage is not completely initialized, 26 bytes left - UTF16 String is "platform=win_x86-64 result=abcdefghijklmnopqrstuvwxyz class=net.adoptopenjdk.test.bigdecimal.TestSuite023 test=testItem_0354"
```

So that seems to point to the problem being related to the steps involved in concatenating the value of `status` into the string.

**Comment by hzongaro** [comment] 2019-11-20 16:09
I managed to produce a core and javacore by adding calls to `com.ibm.jvm.Dump.SystemDump` and `com.ibm.jvm.Dump.JavaDump` into `StringConcatHelper.newString` at the point where it throws an `InternalError`.  From that I was able to work backwards through the paths in the CFG, and found that on one path a call to `java.lang.String.lengthInternal` is folded to an `iconst 4` (or `iconst 26`, in the modified version) by local value propagation when the object it's operating on should be `exceptionText`, which has length zero.

Eliding many intervening nodes, the code prior to that looks roughly like this:

```
#1256 = "pass"
#1261 = StringConcatHelper.stringOf(#1256)
#1256 = exceptionText
...
String.lengthInternal(#1256)
```

Now running with additional tracing enabled in local value propagation to resolve the problem.

**Comment by hzongaro** [comment] 2019-11-21 13:33
Going a bit further, the problem appears to be related to the inliner's reuse of the temporary variable that holds the string `"pass"` (or `"abcdefghijklmnopqrstuvwxyz"` in the modified version).  In the following nodes after inlining, `#1256` is marked as containing known object `obj2`, but is reused by the inliner to hold the value of `exceptionText`:

```
n10255n   astore  <temp slot 9>[#1256  Auto] (obj2)
n20n        aload  <string "abcdefghijklmnopqrstuvwxyz">[#370  Static] (obj2)

n4871n      aload  exceptionText<auto slot 7>[#869  Auto]

n9813n    astore  <temp slot 13>[#2651  Auto]
n4871n      ==>aload

n6604n      aload  <temp slot 13>[#2651  Auto]

n9802n    astore  <temp slot 22>[#2645  Auto]
n6604n      ==>aload

n6660n      aload  <temp slot 22>[#2645  Auto]

n6876n    astore  <temp slot 9>[#1256  Auto] (obj2) <<<<
n6660n      ==>aload
```

**Comment by hzongaro** [comment] 2019-11-23 03:42
*Latest updates*  I think the problem might be associated with reuse of `TR_CallTarget` instances for multiple calls.  Looking at a log file that is attempting to inline three calls to `DirectHandle.invokeExact_thunkArchetype_L`, each call has the same `TR_CallTarget` instance.  The call target instance has an associated `TR_PrexArgInfo` instance that carries some information that's specific to a call site, including whether the argument is a known object.  It appears that a known object identified as an argument at one call site is being used incorrectly at another call site.

Following are the details from the log file.  First are the three calls that are involved, along with the arguments that are of interest:

```
n6680n      aloadi  unknown field[#1180  Shadow] (obj6) [flags 0x80000607 0x0 ]               [0x00007FF68D7717C0] bci=[23,57,87] rc=4 vc=277 vn=- li=4 udi=- nc=1

n6663n      aload  argPlaceholder<parm 1 Ljava/lang/Object;>[#406  Parm] [flags 0x40000107 0x0 ]  [0x00007FF68D771270] bci=[23,53,87] rc=2 vc=277 vn=- li=2 udi=- nc=0

n6684n      acalli  java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;[#1229  final computed-virtual Method] [flags 0x20500 0x0 ] (sharedMemory )  [0x00007FF68D771900] bci=[23,57,87] rc=3 vc=277 vn=- li=3 udi=- nc=3 flg=0x20
n6773n        ==>lloadi
n6680n        ==>aloadi
n6663n        ==>aload

...

n6694n      aloadi  unknown field[#1180  Shadow] (obj6) [flags 0x80000607 0x0 ]               [0x00007FF68D771C20] bci=[23,57,87] rc=4 vc=277 vn=- li=4 udi=- nc=1

n6664n      aload  <parm 2 Ljava/lang/Object;>[#407  Parm] (obj2) [flags 0x40000107 0x0 ]     [0x00007FF68D7712C0] bci=[23,53,87] rc=2 vc=277 vn=- li=2 udi=- nc=0

n6698n      acalli  java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;[#1232  final computed-virtual Method] [flags 0x20500 0x0 ] (sharedMemory )  [0x00007FF68D771D60] bci=[23,57,87] rc=3 vc=277 vn=- li=3 udi=- nc=3 flg=0x20
n6778n        ==>lloadi
n6694n        ==>aloadi
n6664n        ==>aload

...

n6750n      aloadi  unknown field[#1180  Shadow] (obj6) [flags 0x80000607 0x0 ]               [0x00007FF68D772DA0] bci=[23,57,87] rc=4 vc=277 vn=- li=4 udi=- nc=1

n6668n      aload  <parm 6 Ljava/lang/Object;>[#411  Parm] [flags 0x40000107 0x0 ]            [0x00007FF68D771400] bci=[23,53,87] rc=2 vc=277 vn=- li=2 udi=- nc=0

n6754n      acalli  java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;[#1244  final computed-virtual Method] [flags 0x20500 0x0 ] (sharedMemory )  [0x00007FF68D772EE0] bci=[23,57,87] rc=3 vc=277 vn=- li=3 udi=- nc=3 flg=0x20
n6798n        ==>lloadi
n6750n        ==>aloadi
n6668n        ==>aload
```

Later comes the computation of the `TR_PrexArgInfo` from the first call.  Note that the first argument is identified as being known object `obj6`:

```
inlineFromGraph: found a call at parent 00007FF68D771950 child 00007FF68D771900, findAndUpdateCallsite returned callsite 00007FF68D1D31C0
PREX.inl: Populating prex argInfo for [00007FF68D771900] acalli java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;
PREX.inl:    Child 2 [00007FF68D771270] arg 0000000000000000 aload argPlaceholder<parm 1 Ljava/lang/Object;>
PREX.inl:    Child 1 [00007FF68D7717C0] arg 0000000000000000 aloadi unknown field
PREX.inl:      00007FF68D0AA600: 00007FF68D7717C0 is known object obj6 in inlined call [00007FF68D771900]
PREX.inl:      00007FF68D0AA620: is known object obj6
PREX.inl: Done populating prex argInfo for acalli 00007FF68D771900
```

Then while processing the `TR_PrexArgInfo` from the second call, we see the following.  Note that the second argument is identified as being known object `obj2`.  Note also that the `TR_PrexArgInfo` for the first argument has address `00007FF68D0AA620`, which is the same address that was assigned to it above.  It's also marked as being a known object, which n6694n does happen to refer to, but that object has not been determined in this computation - it's persisted from the processing of the first call.

```
inlineFromGraph: found a call at parent 00007FF68D771DB0 child 00007FF68D771D60, findAndUpdateCallsite returned callsite 00007FF68D1D31C0
PREX.inl: Populating prex argInfo for [00007FF68D771D60] acalli java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;
PREX.inl:    Child 2 [00007FF68D7712C0] arg 0000000000000000 aload <parm 2 Ljava/lang/Object;>
PREX.inl:      00007FF68D0AA750: is known object obj2
PREX.inl:    Child 1 [00007FF68D771C20] arg 00007FF68D0AA620 (known-object) aloadi unknown field
PREX.inl: Done populating prex argInfo for acalli 00007FF68D771D60
```

Finally, when the third call is processed, both entries for the arguments indicate they are known objects -- which n6750n does happen to be, but n6668n is not -- and the addresses for the argument entries are those that were set previously.

```
bool inlinecallTarget: calltarget 00007FF68D1D33B0 calltarget->mycallsite 00007FF68D1D31C0 calltarget->alreadyInlined = 0 inlinefromgraph = 1 currentNumberOfNodes = 1641
PREX.inl: Populating prex argInfo for [00007FF68D772EE0] acalli java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_L(Ljava/lang/Object;)Ljava/lang/Object;
PREX.inl:    Child 2 [00007FF68D771400] arg 00007FF68D0AA750 (known-object) aload <parm 6 Ljava/lang/Object;>
PREX.inl:    Child 1 [00007FF68D772DA0] arg 00007FF68D0AA620 (known-object) aloadi unknown field
PREX.inl: Done populating prex argInfo for acalli 00007FF68D772EE0
```

It might be that ordinarily a different call target instance would be created for each call site, but that doesn't happen for JSR 292 methods - I'm just speculating here.

I will follow up with Yi @cathyzhyi and Andrew @andrewcraik to see if either has any ideas why this is happening and suggestions about how to resolve the problem.

**Comment by pshipton** [comment] 2019-11-23 14:55
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_sanity.system_x86-64_mac_Nightly/97
DaaLoadTest_daa3_0

**Comment by andrewcraik** [comment] 2019-11-25 14:29
@hzongaro could you try a build with https://github.com/eclipse/omr/pull/4566 included? One way we know this information leak can happen is through the parm symbols which is something @liqunl has been working to fix.

**Comment by hzongaro** [comment] 2019-11-26 01:10
Thanks, Andrew @andrewcraik.  A grinder run of `MathLoadTest_all_0` with the changes for [OMR pull request #4566](https://github.com/eclipse/omr/pull/4566) passed 100/100, so that likely will resolve this problem.  Liqun @liqunl, FYI.

**Comment by pshipton** [comment] 2019-12-03 14:13
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.system_x86-64_windows_Nightly/114
MathLoadTest_all_0
```
MLT testFinished: testItem_0983(net.adoptopenjdk.test.bigdecimal.TestSuite051)
MLT testFailure: null: Storage is not completely initialized, 4 bytes left
MLT java.lang.InternalError: Storage is not completely initialized, 4 bytes left
MLT 	at java.base/java.lang.StringConcatHelper.newString(StringConcatHelper.java:401)
MLT 	at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_L(DirectHandle.java:298)
MLT 	at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FilterArgumentsWithCombinerHandle.invokeExact_thunkArchetype_X(FilterArgumentsWithCombinerHandle.java:99)
MLT 	at java.base/java.lang.invoke.FoldNonvoidHandle.invokeExact_thunkArchetype_X(FoldHandle.java:121)
MLT 	at java.base/java.lang.invoke.FilterArgumentsHandle.invokeExact_thunkArchetype_X(FilterArgumentsHandle.java:85)
MLT 	at java.base/java.lang.invoke.AsTypeHandle.invokeExact_thunkArchetype_X(AsTypeHandle.java:49)
MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.addResult(JUnitAdaptor.java:120)
MLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor$1.testFinished(JUnitAdaptor.java:80)
```

**Comment by andrewcraik** [comment] 2019-12-12 21:25
OMR 4566 merged yesterday and promoted today so this should now be fixed - I am going to close - please reopen if there are reproductions with the fixes delivered.

**Closed by andrewcraik** 2019-12-12 21:25 UTC
Labels: test failure
