### ISSUE TITLE
Build issue due to missing openj9_version_info.h

### ISSUE THREAD

**Issue by FireBurn** [eclipse/openj9#87] opened 2017-09-20 13:56 UTC
Error:

gmake[5]: Entering directory `/apps/was/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/util'
cc -DJAVA_SPEC_VERSION=9 -O3 -fno-strict-aliasing -g -MMD -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64  -fPIC  -DIPv6_FUNCTION_SUPPORT -DJ9HAMMER -m64 -Wimplicit -Wreturn-type -Werror -I. -I../include -I../oti -I../gc_include -I/apps/was/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/omr/gc/include -I../nls -I/apps/was/openj9-openjdk-jdk9/build/linux-x86_64-normal-server-release/vm/omr/include_core    -DUT_DIRECT_TRACE_REGISTRATION -DTR_HOST_X86 -DOPENJ9_BUILD -c -o openj9_version.o openj9_version.c
gmake[3]: warning: -jN forced in submake: disabling jobserver mode.
openj9_version.c:27:33: fatal error: openj9_version_info.h: No such file or directory
 #include "openj9_version_info.h"
gmake[5]: *** [openj9_version.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....

Workaround:

```
diff --git a/runtime/util/openj9_version.c b/runtime/util/openj9_version.c
index dee6a0d..ea50f93 100644
--- a/runtime/util/openj9_version.c
+++ b/runtime/util/openj9_version.c
@@ -22,20 +22,10 @@

 /*The file prints out required version information for Xinternalversion option */
 #include "openj9_version.h"
-#if defined(OPENJ9_BUILD)
-/*The file collects version information in OpenJ9 build */
-#include "openj9_version_info.h"
-#endif /* OPENJ9_BUILD */

 void
 j9print_internal_version(J9PortLibrary *portLib) {
        PORT_ACCESS_FROM_PORT(portLib);

-#if defined(OPENJ9_BUILD)
-       j9tty_err_printf(PORTLIB, "Eclipse OpenJ9 %s %s-bit Server VM (%s) from %s-%s JRE (%s), built on %s %s by %s with %s\n",
-               J9PRODUCT_NAME, J9TARGET_CPU_BITS, J9VERSION_STRING, J9TARGET_OS, J9TARGET_CPU_OSARCH,
-               J9VERSION_STRING, __DATE__, __TIME__, J9USERNAME, J9COMPILER_VERSION_STRING);
-#else /* OPENJ9_BUILD */
        j9tty_err_printf(PORTLIB, "internal version not supported\n");
-#endif /* OPENJ9_BUILD */
 }
```

This clearly isn't the fix, so not submitting a pull request

**Comment by DanHeidinga** [comment] 2017-09-20 14:08
See also https://github.com/ibmruntimes/openj9-openjdk-jdk9/issues/11

**Comment by JamesKingdon** [comment] 2017-09-21 14:26
Just ran into this. It seems openj9_version_info.h is generated by the configure step, but deleted by make clean. So if you run configure and follow the instruction to then make clean you hit the problem. For a temporary work-around, just run the configure step again. If you know you will need to do a make clean, do it before running configure.

**Comment by jdekonin** [comment] 2017-10-06 14:00
I haven't been able to reproduce this issue since integrating your work here Keith.  Thanks for removing this headache.

**Comment by keithc-ca** [comment] 2017-10-06 14:09
Closing: fixed via https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/46.

**Closed by keithc-ca** 2017-10-06 14:09 UTC
Labels: bug, comp:build
