### ISSUE TITLE
Attach dir auto detection broken?

### ISSUE THREAD

**Issue by CodingFabian** [eclipse/openj9#2781] opened 2018-09-06 12:29 UTC
When starting a process without any attach configuration it seems to try to write to a strange directly.
I was unable to find it until I enabled attach logging:

1536236641952 1869: 29 [Attach API initializer]: IPC Directory=f/.com_ibm_tools_attach
1536236641952 1869: 29 [Attach API initializer]: createDirectoryAndSemaphore /root/f/.com_ibm_tools_attach

The build is

```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-b13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180813_291 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - a05586ac based on jdk8u181-b13)
```

running the adoptopenjdk docker image adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u181-b13_openj9-0.9.0

env is
```
JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle
HOSTNAME=5ab71418d220
SHLVL=1
OLDPWD=/
HOME=/root
JAVA_VERSION=jdk8u181-b13_openj9-0.9.0
TERM=xterm
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root
JAVA_HOME=/opt/java/openjdk
```

whats going on here? is that a bug?

**Comment by CodingFabian** [comment] 2018-09-06 12:31
https://github.com/eclipse/openj9/blob/6849cd19d029fadd26f2fb164d54ecc00da6ec75/jcl/src/java.base/share/classes/com/ibm/tools/attach/target/CommonDirectory.java#L93

I assume this code is the one responsible. so the system temp dir is f?

**Comment by DanHeidinga** [comment] 2018-09-06 13:38
@pdbain-ibm Any insight on this?

**Comment by CodingFabian** [comment] 2018-09-06 14:06
BTW: creating /root/f or changing -Dcom.ibm.tools.attach.directory on attacher and attachee (those are words, right?) both makes it work.
So it seems to be "only" an issue in finding /tmp and mistakenly choosing /root/f.

I tried to search for "f" in the codebase, of course with so many hits that I consider the search unsuccessful. :)

**Comment by pdbain-ibm** [comment] 2018-09-06 14:12
@CodingFabian Thank you for your inquiry.  I will investigate.

syshelp.c:getTmpDir() looks for a directory specified by the "TMPDIR" environment variable.  If that is not specified, or it doesn't point to a directory with the correct permissions, it checks "/tmp".  If that isn't a directory with the correct permissions, it uses $PWD.

Questions:
- are you running as root?
- what are the permissions on /tmp?

**Comment by pdbain-ibm** [comment] 2018-09-06 14:45
> attacher and attachee (those are words, right?)

Close enough.  The proper terminology is 'attacher' and 'target'.

**Comment by CodingFabian** [comment] 2018-09-06 14:46
Yes. As root. Just directly in the mentioned docker image.

**Comment by pdbain-ibm** [comment] 2018-09-06 15:17
- Does attach API work if you specify `TMPDIR` as `/tmp` 
- What is the value of "java.io.tmpdir"?  You can get it by running with `-XshowSettings:properties`
- Tracepoints would tell us if the attribute check is failing.  You can enable them via `-Xtrace:maximal=omrport,output=traces`.
Could you also send me the result of `ls -laR /tmp`.

**Comment by CodingFabian** [comment] 2018-09-06 16:40
Permissions on temp
```
/ # ls -la /tmp
total 278
drwxrwxrwt    4 root     root             5 Sep  6 12:18 .
drwxr-xr-x   20 root     root            23 Sep  6 12:07 ..
```

setting TMPDIR has no effect, same as setting `java.io.tmpdir`
```
1536251740189 3975: 29 [Attach API initializer]: AttachHandler initialize
1536251740190 3975: 29 [Attach API initializer]: IPC Directory=f/.com_ibm_tools_attach
1536251740190 3975: 29 [Attach API initializer]: createDirectoryAndSemaphore /root/f/.com_ibm_tools_attach
```

properties:
```
java -Dcom.ibm.tools.attach.logging=yes -XshowSettings:properties EndlessApp &
~ # Property settings:
    awt.toolkit = sun.awt.X11.XToolkit
    com.ibm.cpu.endian = little
    com.ibm.jcl.checkClassPath =
    com.ibm.oti.configuration = scar
    com.ibm.oti.shared.enabled = false
    com.ibm.oti.vm.bootstrap.library.path = /opt/java/openjdk/jre/lib/amd64/compressedrefs
        /opt/java/openjdk/jre/lib/amd64
    com.ibm.oti.vm.library.version = 29
    com.ibm.system.agent.path = /opt/java/openjdk/jre/lib/amd64
    com.ibm.tools.attach.logging = yes
    com.ibm.util.extralibs.properties =
    com.ibm.vm.bitmode = 64
    com.ibm.zero.version = 2
    file.encoding = ANSI_X3.4-1968
    file.encoding.pkg = sun.io
    file.separator = /
    ibm.signalhandling.rs = false
    ibm.signalhandling.sigchain = true
    ibm.signalhandling.sigint = true
    ibm.system.encoding = ANSI_X3.4-1968
    java.awt.fonts =
    java.awt.graphicsenv = sun.awt.X11GraphicsEnvironment
    java.awt.printerjob = sun.print.PSPrinterJob
    java.class.path = .
    java.class.version = 52.0
    java.compiler = j9jit29
    java.endorsed.dirs = /opt/java/openjdk/jre/lib/endorsed
    java.ext.dirs = /opt/java/openjdk/jre/lib/ext
    java.fullversion = 1.8.0_181-b13
JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180813_291 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - a05586ac based on jdk8u181-b13
    java.home = /opt/java/openjdk/jre
    java.io.tmpdir = /tmp
    java.library.path = /opt/java/openjdk/jre/lib/amd64/compressedrefs
        /opt/java/openjdk/jre/lib/amd64
        /usr/lib64
        /usr/lib
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 1.8.0_181-b13
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.util.prefs.PreferencesFactory = java.util.prefs.FileSystemPreferencesFactory
    java.vendor = Eclipse OpenJ9
    java.vendor.url = http://www.eclipse.org/openj9
    java.version = 1.8.0_181
    java.vm.info = JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180813_291 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - a05586ac based on jdk8u181-b13
    java.vm.name = Eclipse OpenJ9 VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Eclipse OpenJ9
    java.vm.version = openj9-0.9.0
    jdk.extensions.name = Extensions for OpenJDK for Eclipse OpenJ9
    jdk.extensions.version = 8.0.0.2
    line.separator = \n
    os.arch = amd64
    os.encoding = ANSI_X3.4-1968
    os.name = Linux
    os.version = 4.4.0-79-generic
    path.separator = :
    sun.arch.data.model = 64
    sun.boot.class.path = /opt/java/openjdk/jre/lib/amd64/compressedrefs/jclSC180/vm.jar
        /opt/java/openjdk/jre/lib/se-service.jar
        /opt/java/openjdk/jre/lib/rt.jar
        /opt/java/openjdk/jre/lib/resources.jar
        /opt/java/openjdk/jre/lib/jsse.jar
        /opt/java/openjdk/jre/lib/charsets.jar
        /opt/java/openjdk/jre/lib/jce.jar
        /opt/java/openjdk/jre/lib/tools.jar
    sun.boot.library.path = /opt/java/openjdk/jre/lib/amd64/compressedrefs
        /opt/java/openjdk/jre/lib/amd64
    sun.cpu.endian = little
    sun.io.unicode.encoding = UnicodeLittle
    sun.java.command = EndlessApp
    sun.java.launcher = SUN_STANDARD
    sun.java.launcher.pid = 4357
    sun.jnu.encoding = ANSI_X3.4-1968
    user.country = US
    user.dir = /root
    user.home = /root
    user.language = en
    user.name = root
    user.timezone =
    user.variant =
```
`ls -laR /tmp` is empty in any case

`-Xtrace:maximal=omrport,output=traces` has an effect!
The directory is now named p0 not f
```
1536251930349 4469: 30 [Attach API initializer]: IPC Directory=p0/.com_ibm_tools_attach
1536251930349 4469: 30 [Attach API initializer]: createDirectoryAndSemaphore /root/p0/.com_ibm_tools_attach
```

I am attaching the traces file

**Comment by CodingFabian** [comment] 2018-09-06 16:56
you should be able to do all these experiments youself:
```
docker run --rm -it adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u181-b13_openj9-0.9.0 /bin/ash
```

**Comment by CodingFabian** [comment] 2018-09-06 16:56
My very scientific EndlessApp looks like this:
````
java
import java.lang.management.ManagementFactory;
import java.util.concurrent.TimeUnit;

public class EndlessApp {

  public static void main(String[] args) throws InterruptedException {
    System.out.println(ManagementFactory.getRuntimeMXBean().getName().split("@")[0]);
    while (true) {
      TimeUnit.SECONDS.sleep(10);
    }
  }

}

```

**Comment by pdbain-ibm** [comment] 2018-09-06 17:05
Yup.  Confirmed.  I'm on the case...

**Comment by pdbain-ibm** [comment] 2018-09-06 20:36
omrstr_convert() is mangling the path: it takes `/tmp` and turns it into bytes `c0 60 8 8c d3 7f`.
`locale` is not installed on the docker image.  Will investigate further tomorrow.

**Comment by pdbain-ibm** [comment] 2018-09-07 17:08
Following up on problem 1 with the maintainer. Testing a fix for problem 2 now.

**Comment by pdbain-ibm** [comment] 2018-09-07 17:34
@dinogun
would you please investigate 
https://github.com/eclipse/openj9/issues/2781#issuecomment-419491792?

**Comment by dinogun** [comment] 2018-09-10 07:15
@pdbain-ibm Thanks for letting me know, looking into this.

**Comment by pdbain-ibm** [comment] 2018-09-20 19:34
@dinogun Any progress on this?

**Comment by dinogun** [comment] 2018-10-23 17:20
Adding glibc-bin and libc-i18n packages helps to resolve this issue
```
1540314686563 10: 19 [Attach API initializer]: AttachHandler initialized
1540314686565 10: 19 [Attach API initializer]: Could not get system temporary directory. Trying java.io.tmpdir
1540314686565 10: 19 [Attach API initializer]: IPC Directory=/tmp/.com_ibm_tools_attach
1540314686566 10: 19 [Attach API initializer]: createDirectoryAndSemaphore /tmp/.com_ibm_tools_attach
1540314686567 10: 19 [Attach API initializer]: non-blocking locking file /tmp/.com_ibm_tools_attach/_master
1540314686569 10: 19 [Attach API initializer]: deleteStaleDirectories checking _master
1540314686570 10: 19 [Attach API initializer]: AttachHandler obtained master lock
1540314686608 10: 19 [Attach API initializer]: locking file /tmp/.com_ibm_tools_attach/_attachlock
1540314686612 10: 19 [Attach API initializer]: createAdvertisementFile /tmp/.com_ibm_tools_attach/10/attachInfo
1540314686613 10: 19 [Attach API initializer]: unlocking file /tmp/.com_ibm_tools_attach/_attachlock
1540314686614 10: 19 [Attach API initializer]: unlocking file /tmp/.com_ibm_tools_attach/_master
1540314686616 10: 21 [Attach API wait loop]: iteration 0 waitForNotification ignoreNotification entering
1540314686617 10: 21 [Attach API wait loop]: iteration 0 waitForNotification ignoreNotification entered
1540314686617 10: 21 [Attach API wait loop]: iteration 0 waitForNotification starting wait
```
However this increases the size of the image by about 27MB, looking to strip out unnecessary files to trim down the image. Should have an updated image tomorrow.

**Comment by DanHeidinga** [comment] 2018-10-30 01:37
> Should have an updated image tomorrow.

@dinogun Is the the updated image available?

**Comment by dinogun** [comment] 2018-11-02 05:31
It turns out the actual issue was with the `glibc` package itself. Moving to a newer `glibc` (2.28-r0) and the latest `Alpine` (3.8.1) actually resolves this issue without having to add any new packages.

I tested this with the latest Alpine image `adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u192-b12` and it works ok. Please confirm, thanks

**Comment by DanHeidinga** [comment] 2018-11-02 13:33
@pdbain-ibm Can you retest with the latest alpine image?

**Comment by pdbain-ibm** [comment] 2018-11-02 13:39
Will do...

**Comment by pdbain-ibm** [comment] 2018-11-02 14:44
Thanks @dinogun .  Tested and working.
@CodingFabian would you kindly retest and close this issue if you are satisfied?

**Comment by DanHeidinga** [comment] 2018-11-14 16:26
Closing as fixed.  Please comment if you still see the issue

**Comment by DanHeidinga** [comment] 2018-11-14 16:26
Closing as fixed.  Please comment if you still see the issue

**Closed by DanHeidinga** 2018-11-14 16:26 UTC
Labels: comp:vm, userRaised
