### ISSUE TITLE
OpenJ9 is incompatible with sbt's shell mode...

### ISSUE THREAD

**Issue by markehammons** [eclipse/openj9#40] opened 2017-09-17 09:07 UTC
[SBT](http://www.scala-sbt.org/) is a build tool for the scala programming language. When I try to run it in interactive mode with the command ```sbt``` using the openj9+openjdk jre obtained [here](https://adoptopenjdk.net/releases.html?variant=openjdk9-openj9), I get the following error:

```
java.lang.IllegalArgumentException: Signal already used by VM or OS: SIGCONT
   at jdk.internal.misc.Signal.handle(java.base@9-internal/Signal.java:173)
   at sun.misc.Signal.handle(jdk.unsupported@9-internal/Signal.java:157)
   at sbt.Signals0.withHandler(Signal.scala:79)
   at sbt.Signals$.withHandler(Signal.scala:11)
   at sbt.JLine.readLineDirect(LineReader.scala:34)
   at sbt.JLine.readLineWithHistory(LineReader.scala:27)
   at sbt.JLine.sbt$JLine$$unsynchronizedReadLine(LineReader.scala:19)
   at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
   at sbt.JLine$$anonfun$readLine$1.apply(LineReader.scala:16)
   at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:117)
   at sbt.JLine$$anonfun$withJLine$1.apply(LineReader.scala:115)
   at sbt.JLine$.withTerminal(LineReader.scala:89)
   at sbt.JLine$.withJLine(LineReader.scala:115)
   at sbt.JLine.readLine(LineReader.scala:16)
   at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:185)
   at sbt.BasicCommands$$anonfun$shell$1.apply(BasicCommands.scala:181)
   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
   at sbt.Command$$anonfun$command$1$$anonfun$apply$1.apply(Command.scala:30)
   at sbt.Command$.process(Command.scala:93)
   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
   at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
   at sbt.State$$anon$1.runCmd$1(State.scala:183)
   at sbt.State$$anon$1.process(State.scala:187)
   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
   at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
   at sbt.MainLoop$.next(MainLoop.scala:96)
   at sbt.MainLoop$.run(MainLoop.scala:89)
   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
   at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
   at sbt.Using.apply(Using.scala:24)
   at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
   at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
   at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
   at sbt.MainLoop$.runLogged(MainLoop.scala:22)
   at sbt.StandardMain$.runManaged(Main.scala:61)
   at sbt.xMain.run(Main.scala:35)
   at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
   at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
   at xsbt.boot.Launch$.run(Launch.scala:109)
   at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
   at xsbt.boot.Launch$.launch(Launch.scala:117)
   at xsbt.boot.Launch$.apply(Launch.scala:18)
   at xsbt.boot.Boot$.runImpl(Boot.scala:41)
   at xsbt.boot.Boot$.main(Boot.scala:17)
   at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException: Signal already used by VM or OS: SIGCONT
[error] Use 'last' for the full log.
```

My operating system is fedora 26, and the openj9 --version string is as follows:

```
openjdk 9-internal
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170915_6 (JIT enabled, AOT enabled)
J9VM - cea1ed7
JIT  - cea1ed7
OMR  - 617de12
OpenJDK  - 83f5cd0 based on )
```

**Comment by gireeshpunathil** [comment] 2017-09-18 04:41
Here is a simple recreate of the above issue - that works fine in openjdk and fails with openj9:

```java
import sun.misc.Signal;
import sun.misc.SignalHandler;

public class Foo {
  public static void main(String args[]) {
    SignalHandler sh = new SignalHandler() {
      public void handle(Signal sig) {
        System.out.println("signal " + sig + " received!");
      }
    };
    try {
      Signal.handle(new Signal("CONT"), sh);
    }
    catch(IllegalArgumentException e) {
      System.out.println(e.toString());
    }
  }
}
```
Please note the use of internal proprietary APIs (`sun.misc`)
/cc @DanHeidinga @pshipton

**Comment by andrewcraik** [comment] 2017-09-18 13:36
A similar message can be seen running Spark with OpenJ9 - in this case the message is not a fatal error and the application runs, but the VMs do not shutdown cleanly - they are killed by the controller app. Some interplay between the OpenJ9 signal handlers and the signal handlers being added by the Java code I suspect.

**Comment by babsingh** [comment] 2017-09-18 16:00
To resolve the IllegalArgumentException, [jvm.c:JVM_RegisterSignal](https://github.com/eclipse/openj9/blob/master/runtime/j9vm/jvm.c#L4163) needs to be implemented; it currently has a stub.

@andrewcraik `-Xrs` option may help VM shutdown cleanly for the signal handler issue.

**Comment by babsingh** [comment] 2017-09-18 18:26
Duplicate of Issue #54

**Comment by gireeshpunathil** [comment] 2017-09-19 01:57
@babsingh - I don't think so. This is the OP, and #54 is its derivative / follow-up.

**Comment by enasser** [comment] 2017-09-20 11:11
I have worked on couple of such issues in the past reported by open sources projects like Spark, Hive mostly while running java as a background process. 

This is basically a difference behavior between J9 and Hotspot while handling a signal which is already registered with JVM. 

Both J9 and Hotspot  did not register the signal if the same signal is already registered with JVM. The difference is in the way it respond while ignoring the signal. Hotspot returns SIG_IGN to silently ignore the SIGINT signal (or any other signal) where as IBM JDK throw the exception "java.lang.IllegalArgumentException: Signal already used by VM: INT".  

This appears to be a design decision taken during Java 5 or even before. The method sun.misc.Signal.handle() is an internal method and not supposed to be called directly by the application. Hence, this behavior difference was never an issue as the JDK internally handle it appropriately.  However applications like Spark, Hive use this JDK internal class directly which expose the behavior difference. 

The question is which behavior is more correct - whether an exception is thrown when the signal is already registered or just ignore it. We can argue either way. However, I feel it is better to ignore if it is already registered with JVM as it cannot anyway handle if application want to register the same signal handler.  Also, those projects which uses sun.misc.Signal.handle() need to remove the usage of such internal APIs.

**Comment by pshipton** [comment] 2017-09-20 12:29
Basically it happens on OpenJ9 because JVM_RegisterSignal() needs to be implemented. atm it always returns -1 which causes Signal.handle() to throw IllegalArgumentException.

**Comment by markehammons** [comment] 2017-09-22 07:34
I'm gonna try to fix it from the other side, by getting sbt to stop using the sun.misc class. That's something that needs to be done anyway.

**Comment by babsingh** [comment] 2017-11-20 21:55
@markehammons I have pushed a fix. Now, sbt's shell mode should work with Openj9.

![screen shot 2017-11-20 at 4 53 09 pm](https://user-images.githubusercontent.com/8634038/33043466-927d7654-ce13-11e7-8d14-a3bb5957f674.png)

@DanHeidinga this issue can be closed.

**Comment by DanHeidinga** [comment] 2017-11-21 05:05
Thanks @babsingh.

**Closed by DanHeidinga** 2017-11-21 05:05 UTC
Labels: bug

**Comment by madper** [comment] 2018-12-31 06:40
Hey!
I still meet the issue with [Ammonite](https://github.com/lihaoyi/Ammonite). While it works well with openjdk 11. The openj9 version I'm using is:
![screenshot from 2018-12-31 14-39-39](https://user-images.githubusercontent.com/451815/50555619-ed61ff00-0d09-11e9-9f9b-7ee0a84dfbab.png)
![screenshot from 2018-12-31 14-36-13](https://user-images.githubusercontent.com/451815/50555588-85131d80-0d09-11e9-9d1d-be72d65711f5.png)

Not quite sure if it worths a new issue.

**Comment by madper** [comment] 2019-01-04 05:39
@babsingh Ooops, my fault.  I see. Thanks a lot for the correction!  :-D
