### ISSUE TITLE
openjdk8-openj9-0.15.1 Segmentation fault

### ISSUE THREAD

**Issue by roded** [eclipse/openj9#8181] opened 2019-12-29 17:57 UTC
Java -version output
--------------------
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190717_368 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - f147086df1e based on jdk8u222-b10)

Summary of problem
------------------
Segmentation fault. We don't know how to reproduce the issue, but it reappears spontaneously.
The attached logs is all I have to share at the moment, upon another occurrence we'll attempt salvaging the full dumps. Perhaps, someone can anyone tell if this issue has already been resolved in a later OpenJ9 version?

Diagnostic files
----------------
```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
Handler1=00007FA678CE5FC0 Handler2=00007FA6785E0520 InaccessibleAddress=00007FA650880000
RDI=00000000F8DCF7A8 RSI=00000000FF3555B5 RAX=00000000008463D0 RBX=00007FA5D81441B0
RCX=00007FA650039C30 RDX=0000000000000060 R8=00007FA5D81441D8 R9=000000009FFA3203
R10=0000000000000000 R11=00007FA60A5D8448 R12=00000000FF3555B5 R13=0000000000000060
R14=00007FA5D81441D8 R15=0000000000000000
RIP=00007FA61C4FF14E GS=0000 FS=0000 RSP=00007FA60A5D8428
EFlags=0000000000010202 CS=0033 RBP=00007FA650039C10 ERR=0000000000000004
TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FA650880000
xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm2 8120e5d0195bf46f (f: 425456736.000000, d: -3.080081e-303)
xmm3 095ebfb64d8b6fb7 (f: 1300983680.000000, d: 1.525784e-263)
xmm4 b867386008e16f77 (f: 148991856.000000, d: -5.459046e-37)
xmm5 ab00ed2d30aba187 (f: 816554368.000000, d: -1.511464e-101)
xmm6 7a54425144ca72b7 (f: 1154118272.000000, d: 1.838718e+281)
xmm7 9bf65a191cba432c (f: 481968928.000000, d: -5.648301e-174)
xmm8 07c014d1ebe83afc (f: 3957865216.000000, d: 2.378131e-271)
xmm9 3ff433004ae9e666 (f: 1256842880.000000, d: 1.262451e+00)
xmm10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
xmm11 19feae9ffa222883 (f: 4196542720.000000, d: 1.805212e-183)
xmm12 af7eee1ea6c22cd4 (f: 2797743360.000000, d: -6.521436e-80)
xmm13 c2ef3ddbd63c7488 (f: 3594286336.000000, d: -2.748043e+14)
xmm14 b7ebe8582f1ef890 (f: 790558848.000000, d: -2.562908e-39)
xmm15 187b3bab78d49f07 (f: 2027200256.000000, d: 9.550357e-191)
Module=/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
Module_base_address=00007FA61C47B000
Target=2_90_20190717_368 (Linux 3.10.0-693.2.2.el7.x86_64)
CPU=amd64 (4 logical CPUs) (0xf6f87000 RAM)
----------- Stack Backtrace -----------
(0x00007FA61C4FF14E [libcrypto.so.1.1+0x8414e])
---------------------------------------
```

Java Core:
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "pool-41-thread-1" J9VMThread:0x00000000047A7200, omrthread_t:0x00007FA5E83E3338, java/lang/Thread:0x00000000FF341DB8, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x150, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x155, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x40400020)
3XMTHREADINFO2            (native stack address range from:0x00007FA60A59C000, to:0x00007FA60A5DC000, size:0x40000)
3XMCPUTIME               CPU usage total: 0.487340205 secs, current category="Application"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=65536 (0x10000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at jdk/crypto/jniprovider/NativeCrypto.CBCUpdate(Native Method)
4XESTACKTRACE                at com/sun/crypto/provider/NativeCipherBlockChaining.encrypt(NativeCipherBlockChaining.java:242)
4XESTACKTRACE                at com/sun/crypto/provider/NativeCipherBlockChaining.decrypt(NativeCipherBlockChaining.java:278)
4XESTACKTRACE                at com/sun/crypto/provider/CipherCore.update(CipherCore.java:849)
4XESTACKTRACE                at com/sun/crypto/provider/AESCipher.engineUpdate(AESCipher.java:410)
4XESTACKTRACE                at javax/crypto/Cipher.update(Cipher.java:1944)
4XESTACKTRACE                at sun/security/ssl/CipherBox.decrypt(CipherBox.java:469)
4XESTACKTRACE                at sun/security/ssl/InputRecord.decrypt(InputRecord.java:172)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.readRecord(SSLSocketImpl.java:1017)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000000FF355588, entry count: 1)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
5XESTACKTRACE                   (entered lock: java/lang/Object@0x00000000FF355598, entry count: 1)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
4XESTACKTRACE                at sun/security/ssl/SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
4XESTACKTRACE                at sun/net/www/protocol/https/HttpsClient.afterConnect(HttpsClient.java:559)
4XESTACKTRACE                at sun/net/www/protocol/https/AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
5XESTACKTRACE                   (entered lock: sun/net/www/protocol/https/DelegateHttpsURLConnection@0x00000000FF359A70, entry count: 2)
4XESTACKTRACE                at sun/net/www/protocol/http/HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
5XESTACKTRACE                   (entered lock: sun/net/www/protocol/https/DelegateHttpsURLConnection@0x00000000FF359A70, entry count: 1)
4XESTACKTRACE                at sun/net/www/protocol/https/HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
5XESTACKTRACE                   (entered lock: sun/net/www/protocol/https/HttpsURLConnectionImpl@0x00000000FF359B88, entry count: 1)
4XESTACKTRACE                at io/model9/backup/server/java/agentconn/UrlConnectionAgentCommunicator.httpPost(UrlConnectionAgentCommunicator.java:896)
4XESTACKTRACE                at io/model9/backup/server/java/agentconn/UrlConnectionAgentCommunicator.httpPost(UrlConnectionAgentCommunicator.java:863)
4XESTACKTRACE                at io/model9/backup/server/java/agentconn/UrlConnectionAgentCommunicator.getConnectionInputStream(UrlConnectionAgentCommunicator.java:1061)
4XESTACKTRACE                at io/model9/backup/server/java/agentconn/UrlConnectionAgentCommunicator.postDumpVolume(UrlConnectionAgentCommunicator.java:367)
4XESTACKTRACE                at io/model9/backup/server/java/agentconn/AgentCommunicator$postDumpVolume$10.call(Bytecode PC:58)
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/CallSiteArray.defaultCall(CallSiteArray.java:47(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/AbstractCallSite.call(AbstractCallSite.java:116(Compiled Code))
4XESTACKTRACE                at zosbackupserver/VolumeBackupRunService.$tt__volumeBackupRunService_getDumpInputStream(VolumeBackupRunService.groovy:99)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62(Compiled Code))
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:498(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/reflection/CachedMethod.invoke(CachedMethod.java:98(Compiled Code))
4XESTACKTRACE                at groovy/lang/MetaMethod.doMethodInvoke(MetaMethod.java:325(Compiled Code))
4XESTACKTRACE                at groovy/lang/MetaClassImpl.invokeMethod(MetaClassImpl.java:1225(Compiled Code))
4XESTACKTRACE                at groovy/lang/ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1125)
4XESTACKTRACE                at groovy/lang/MetaClassImpl.invokeMethod(MetaClassImpl.java:1034(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/InvokerHelper.invokePogoMethod(InvokerHelper.java:947(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/InvokerHelper.invokeMethod(InvokerHelper.java:930(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/InvokerHelper.invokeMethodSafe(InvokerHelper.java:92(Compiled Code))
4XESTACKTRACE                at zosbackupserver/VolumeBackupRunService$_getDumpInputStream_closure1.doCall(VolumeBackupRunService.groovy)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke0(Native Method)
4XESTACKTRACE                at sun/reflect/NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62(Compiled Code))
4XESTACKTRACE                at sun/reflect/DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43(Compiled Code))
4XESTACKTRACE                at java/lang/reflect/Method.invoke(Method.java:498(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/reflection/CachedMethod.invoke(CachedMethod.java:98(Compiled Code))
4XESTACKTRACE                at groovy/lang/MetaMethod.doMethodInvoke(MetaMethod.java:325(Compiled Code))
4XESTACKTRACE                at org/codehaus/groovy/runtime/metaclass/ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264(Compiled Code))
4XESTACKTRACE                at groovy/lang/MetaClassImpl.invokeMethod(MetaClassImpl.java:1034(Compiled Code))
4XESTACKTRACE                at groovy/lang/Closure.call(Closure.java:420(Compiled Code))
4XESTACKTRACE                at groovy/lang/Closure.call(Closure.java:436(Compiled Code))
4XESTACKTRACE                at grails/gorm/transactions/GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:94)
4XESTACKTRACE                at org/springframework/transaction/support/TransactionTemplate.execute(TransactionTemplate.java:133)
4XESTACKTRACE                at grails/gorm/transactions/GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:91)
4XESTACKTRACE                at zosbackupserver/VolumeBackupRunService.getDumpInputStream(VolumeBackupRunService.groovy)
4XESTACKTRACE                at zosbackupserver/VolumeBackupRunService$getDumpInputStream$6.callCurrent(Bytecode PC:37)
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/CallSiteArray.defaultCallCurrent(CallSiteArray.java:51(Compiled Code))
4XESTACKTRACE                at zosbackupserver/TapeDataSetImportRunService$getDumpInputStream$6.callCurrent(Bytecode PC:51)
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor.dumpResource(ParallelRunExecutor.groovy:95)
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor$dumpResource$3.callCurrent(Bytecode PC:43)
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/CallSiteArray.defaultCallCurrent(CallSiteArray.java:51(Compiled Code))
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor$dumpResource$3.callCurrent(Bytecode PC:50)
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor.dumpSelectedResource(ParallelRunExecutor.groovy:255)
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor$dumpSelectedResource$2.call(Bytecode PC:37)
4XESTACKTRACE                at org/codehaus/groovy/runtime/callsite/CallSiteArray.defaultCall(CallSiteArray.java:47(Compiled Code))
4XESTACKTRACE                at zosbackupserver/ParallelRunExecutor$dumpSelectedResource$2.call(Bytecode PC:51)
4XESTACKTRACE                at zosbackupserver/StripedDumpInitiatorCallable.call(StripedDumpInitiatorCallable.groovy:41)
4XESTACKTRACE                at zosbackupserver/StripedDumpInitiatorCallable.call(StripedDumpInitiatorCallable.groovy)
4XESTACKTRACE                at java/util/concurrent/FutureTask.run(FutureTask.java:266)
4XESTACKTRACE                at io/model9/backup/common/utilities/stripedexecutor/StripedExecutorService$SerialExecutor$1.run(StripedExecutorService.java:429)
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149(Compiled Code))
4XESTACKTRACE                at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:819)
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FA6785FC9D2 [libj9prt29.so+0x3a9d2])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA6785FCA4E [libj9prt29.so+0x3aa4e])
4XENATIVESTACK               (0x00007FA6785FCB44 [libj9prt29.so+0x3ab44])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA6785FC8AB [libj9prt29.so+0x3a8ab])
4XENATIVESTACK               (0x00007FA6785F8F32 [libj9prt29.so+0x36f32])
4XENATIVESTACK               (0x00007FA6785F9CD4 [libj9prt29.so+0x37cd4])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA6780A4FF6 [libj9dmp29.so+0x19ff6])
4XENATIVESTACK               (0x00007FA6780A518D [libj9dmp29.so+0x1a18d])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA6780A18DD [libj9dmp29.so+0x168dd])
4XENATIVESTACK               (0x00007FA67809D3BD [libj9dmp29.so+0x123bd])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA67809E1DE [libj9dmp29.so+0x131de])
4XENATIVESTACK               (0x00007FA6780A753C [libj9dmp29.so+0x1c53c])
4XENATIVESTACK               (0x00007FA67808FC8D [libj9dmp29.so+0x4c8d])
4XENATIVESTACK               (0x00007FA67808F2A5 [libj9dmp29.so+0x42a5])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA67809289B [libj9dmp29.so+0x789b])
4XENATIVESTACK               (0x00007FA678092A1C [libj9dmp29.so+0x7a1c])
4XENATIVESTACK               (0x00007FA6780A915B [libj9dmp29.so+0x1e15b])
4XENATIVESTACK               (0x00007FA678CE5BA2 [libj9vm29.so+0x9eba2])
4XENATIVESTACK               (0x00007FA6785E1283 [libj9prt29.so+0x1f283])
4XENATIVESTACK               (0x00007FA678CE5D98 [libj9vm29.so+0x9ed98])
4XENATIVESTACK               (0x00007FA6785E074A [libj9prt29.so+0x1e74a])
4XENATIVESTACK               (0x00007FA67AA15890 [libpthread.so.0+0x12890])
4XENATIVESTACK               (0x00007FA61C4FF14E [libcrypto.so.1.1+0x8414e])
```

**Comment by JasonFengJ9** [comment] 2019-12-29 21:32
This appears like https://github.com/eclipse/openj9/issues/4530, so it has been fixed (workaround) in later version. Alternatively `-Djdk.nativeDigest=false` can be specified in current JDK command line options.

**Comment by roded** [comment] 2019-12-30 09:22
[8181.tar.gz](https://github.com/eclipse/openj9/files/4009369/8181.tar.gz)

@JasonFengJ9, please see attached dump files. Does these help in telling if the issue is in fact the same as #4530?

**Comment by pshipton** [comment] 2019-12-30 13:46
@ashbm5 pls take a look.

**Comment by pshipton** [comment] 2019-12-30 13:53
As the crash appears related to the CBC algorithm and not MessageDigest, it won't be a duplicate of #4530. I'm not aware of any fixes for this. The workaround is https://www.eclipse.org/openj9/docs/djdknativecbc/

**Comment by ashbm5** [comment] 2020-01-06 15:54
@roded the attached tarball has a javacore file in it but I can't view it, corrupted? please attach the javacore itself to the issue.

**Comment by roded** [comment] 2020-01-08 12:53
@ashbm5, sorry about that, attached.
[javacore.20191125.011003.1.0002.txt](https://github.com/eclipse/openj9/files/4035328/javacore.20191125.011003.1.0002.txt)

**Comment by ashbm5** [comment] 2020-01-08 15:34
@roded if i view that file using vi on linux I'm still not seeing the javacore. Could you copy & paste the content of the file directly to this issue instead of attaching the file. Thanks

**Comment by roded** [comment] 2020-01-08 15:37
Attached is a javacore for what appears to be a second occurrence of the issue (please correct me if I'm wrong and this is an unrelated problem in which case another issue will be opened). We also have a snap, jitdump and core dumps we could share if requested.

[javacore.20200108.100100.1.0002.txt](https://github.com/eclipse/openj9/files/4036028/javacore.20200108.100100.1.0002.txt)

**Comment by roded** [comment] 2020-01-08 15:46
@ashbm5, I'm hitting the maximum comment limit of 64k when pasting it in. Are you experiencing the same issue with the javacore.20200108.100100.1.0002.txt dump I've just posted?

**Comment by pshipton** [comment] 2020-01-08 15:51
The attached javacores are readable for me. I'm not sure what "if i view that file using vi on linux I'm still not seeing the javacore" means.

**Comment by ashbm5** [comment] 2020-01-08 15:51
@roded to confirm, it's the same issue. could you also post the segfault associated with the new javacore?

**Comment by roded** [comment] 2020-01-08 15:53
Here's the segfault associated with the javacore.20200108.100100.1.0002.txt dump:

```
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000080
Handler1=00007FDBF1013000 Handler2=00007FDBF090D520 InaccessibleAddress=0000000000000000
RDI=00007FDBB81D1190 RSI=00000007FE770655 RAX=00007FDBB818FA40 RBX=0000000000000050
RCX=0000000000000050 RDX=00000007FE770838 R8=0000000000000050 R9=0000000000000050
R10=0000000001AF45E8 R11=00007FDBCC604210 R12=00000007FE770655 R13=0000000037363233
R14=00000007FE770838 R15=00007FDBCDB037DC
RIP=00007FDBCD0A4462 GS=0000 FS=0000 RSP=00007FDBCDB03770
EFlags=0000000000010202 CS=0033 RBP=00007FDBB81D1190 ERR=0000000000000000
TRAPNO=000000000000000D OLDMASK=0000000000000000 CR2=0000000000000000
xmm0 869094a601ec4282 (f: 32260738.000000, d: -4.676767e-277)
xmm1 69372f4af9ea9c5c (f: 4192902144.000000, d: 6.932332e+198)
xmm2 ef03f595ab60d7a1 (f: 2875250688.000000, d: -5.910339e+226)
xmm3 473e0acacd9e67ec (f: 3449710592.000000, d: 1.559878e+35)
xmm4 f3eb45a954d9262f (f: 1423517184.000000, d: -2.440761e+250)
xmm5 95746692c5e07e21 (f: 3319823872.000000, d: -2.541719e-205)
xmm6 69372f4af9ea9c5c (f: 4192902144.000000, d: 6.932332e+198)
xmm7 4030e3a26b870491 (f: 1804010624.000000, d: 1.688920e+01)
xmm8 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
xmm9 4030e3a2d50e77eb (f: 3574495232.000000, d: 1.688920e+01)
xmm10 3fe8d48ed61d7aab (f: 3592256256.000000, d: 7.759470e-01)
xmm11 3cdc000000000000 (f: 0.000000, d: 1.554312e-15)
xmm12 bc75900000000000 (f: 0.000000, d: -1.870249e-17)
xmm13 4030a2b23f3baa00 (f: 1060874752.000000, d: 1.663553e+01)
xmm14 3bddd332a0e20e2f (f: 2699169280.000000, d: 2.526275e-20)
xmm15 4030a2b23f3baa00 (f: 1060874752.000000, d: 1.663553e+01)
Module=/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
Module_base_address=00007FDBCCF38000 Symbol=EVP_DecryptUpdate
Symbol_address=00007FDBCD0A4400
Target=2_90_20190717_368 (Linux 3.10.0-1062.4.3.el7.x86_64)
CPU=amd64 (2 logical CPUs) (0x1e845c000 RAM)
----------- Stack Backtrace -----------
EVP_DecryptUpdate+0x62 (0x00007FDBCD0A4462 [libcrypto.so.1.1+0x16c462])
Java_jdk_crypto_jniprovider_NativeCrypto_CBCUpdate+0x88 (0x00007FDBCC604298 [libjncrypto.so+0x2298])
(0x00007FDBD50A8E3D [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/01/08 10:01:00 - please wait.
JVMDUMP032I JVM requested System dump using '/model9/diag/core.20200108.100100.1.0001.dmp' in response to an event
JVMDUMP010I System dump written to /model9/diag/core.20200108.100100.1.0001.dmp
JVMDUMP032I JVM requested Java dump using '/model9/diag/javacore.20200108.100100.1.0002.txt' in response to an event
JVMDUMP010I Java dump written to /model9/diag/javacore.20200108.100100.1.0002.txt
JVMDUMP032I JVM requested Snap dump using '/model9/diag/Snap.20200108.100100.1.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /model9/diag/Snap.20200108.100100.1.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/model9/diag/jitdump.20200108.100100.1.0004.dmp'
```

**Comment by ashbm5** [comment] 2020-01-08 16:03
Thanks. Looks like it's the same issue as previously mentioned. 

We're working on a potential fix - will let you know once it's available on the nightly build. For now, the command line option `-Djdk.nativeCBC=false` will prevent that crash.

By the way, I noticed

**Comment by roded** [comment] 2020-01-08 16:35
@ashbm5, should we assume that setting `-Djdk.nativeCBC=false` will incur a performance hit around SSL handshaking?

**Comment by ashbm5** [comment] 2020-01-08 16:50
@roded There will be performance degradation for TLS/SSL traffic encrypt/decrypt operation.

**Closed** 2020-01-14 15:47 UTC
Labels: userRaised
