### ISSUE TITLE
Console.readPassword() was failed on Linux s390x platform

### ISSUE THREAD

**Issue by takiguc** [eclipse/openj9#3581] opened 2018-11-07 12:15 UTC
Hello.

I ran following testcase on Linux s390x platform (SLES12, Ubuntu 18.04) with AdoptOpenJDK+OpenJ9 11.0.1
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Linux s390x-64-Bit Compressed References 20181020_68 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)
```
import java.io.Console;

public class ConsoleTestC {
   public static void main(String[] args) {
     Console console = System.console();
     char password[] = console.readPassword("password> ");
     System.out.println(password);
   }
}
```

Test instruction
1. Compile and run ConsoleTestC on terminal
$ java ConsoleTestC
password>
2. Type "abc", then "abc" is displayed
3. Type "ls", but nothing is displayed
4. Type "stty echo" to change back the setting

Following build did not have this issue:
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.10.0, JRE 11 Linux s390x-64-Bit Compressed References 20181003_43 (JIT enabled, AOT enabled)
OpenJ9   - e44c4716
OMR      - 32df9563
JCL      - eeda2c2d02 based on jdk-11+28)

OpenJDK has following 2 fixes for same kind of issue:
JDK11: JDK-8209637 [s390x] Interpreter doesn't call result handler after native calls
https://bugs.openjdk.java.net/browse/JDK-8209637
JDK12: JDK-8211163 UNIX version of Java_java_io_Console_echo does not return a clean boolean
https://bugs.openjdk.java.net/browse/JDK-8211163

I think if JDK-8211163 is ported, this issue will be fixed.

**Comment by DanHeidinga** [comment] 2018-11-07 15:01
OpenJ9 uses the OpenJDK class libraries so we'll pick up JDK-8211163 when its available in OpenJDK.  If you want this in JDK11 (and it sounds like you do), you should request OpenJDK backport the fix to the 11 LTS release.

For JDK-8209637, we'll take a look at correctly converting booleans when returning from native calls.  

@fengxue-IS / @tajila Can the two of you take a look at this?  Tobi, I know you've been involved in some of the byte conversion work and this is likely an extension of it to jni.

**Comment by tajila** [comment] 2018-11-07 16:16
Ill take a look at the boolean returns for JNI

**Comment by DanHeidinga** [comment] 2018-11-14 15:58
@tajila Can you add a link to your PR here?

@takiguc Are you able to test with a nightly build from https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9 once Tobi's PR has been merged to confirm that fixes your issue?

**Comment by tajila** [comment] 2018-11-14 16:17
Here is the PR, https://github.com/eclipse/openj9/pull/3648

**Comment by fjeremic** [comment] 2018-11-14 17:32
I couldn't reproduce on 11/05 or 11/14 builds:

```
> ll
total 137132
drwxrwxr-x 5 fjeremic fjeremic      4096 Nov  5 05:50 jdk8u192-b12-jre-11-05
drwxrwxr-x 9 fjeremic fjeremic      4096 Nov 14 06:36 jdk8u192-b12-jre-11-14
-rw-rw---- 1 fjeremic fjeremic  49529778 Nov 14 12:12 OpenJDK8U-jre_s390x_linux_openj9_2018-11-05-13-20.tar.gz
-rw-rw---- 1 fjeremic fjeremic  90714701 Nov 14 12:14 OpenJDK8U-jdk_s390x_linux_openj9_2018-11-14-14-10.tar.gz
-rw-rw-r-- 1 fjeremic fjeremic       239 Nov 14 12:27 ConsoleTestC.java
drwxr-xr-x 7 fjeremic fjeremic      4096 Nov 14 12:28 ..
-rw-r--r-- 1 fjeremic fjeremic       566 Nov 14 12:28 ConsoleTestC.class
drwxrwxr-x 4 fjeremic fjeremic      4096 Nov 14 12:29 .


> jdk8u192-b12-jre-11-05/bin/java ConsoleTestC
password>
abc

> jdk8u192-b12-jre-11-05/bin/java ConsoleTestC
password>
ls

> jdk8u192-b12-jre-11-14/bin/java ConsoleTestC
password>
abc

> jdk8u192-b12-jre-11-14/bin/java ConsoleTestC
password>
ls
```

**Comment by DanHeidinga** [comment] 2018-11-14 18:13
@fjeremic The OpenJDK bug indicates this only applies to 9+.

**Comment by fjeremic** [comment] 2018-11-14 20:16
> @fjeremic The OpenJDK bug indicates this only applies to 9+.

Ah, ok. I was going by the following comment:

> @takiguc Are you able to test with a nightly build from [adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9](https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9) once Tobi's PR has been merged to confirm that fixes your issue?

I guess "openjdk8" is the default variant from the URL. That link should switch to OpenJDK 11 (LTS), i.e.

https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

**Comment by DanHeidinga** [comment] 2019-04-22 18:00
This is working now:
```
# jdk-11.0.3+7/bin/java -showversion ConsoleTestC
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.14.0, JRE 11 Linux s390x-64-Bit Compressed References 20190417_218 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5cc996a803 based on jdk-11.0.3+7)
password> 
abc

# jdk-11.0.3+7/bin/java  ConsoleTestC
password> 
ls
```

**Closed by DanHeidinga** 2019-04-22 18:00 UTC
Labels: comp:vm, userRaised
