### ISSUE TITLE
jdk-15+36: sanity.perf naive-bayes ExceptionInInitializerError

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10591] opened 2020-09-14 13:36 UTC
Failure link
------------
https://ci.adoptopenjdk.net/job/Test_openjdk15_j9_sanity.perf_aarch64_linux/43/consoleFull

Failure output (captured from console output)
---------------------------------------------
```
14:48:23  ====== naive-bayes (apache-spark), iteration 0 started ======
14:48:23  Error during tear-down: null
14:48:23  java.lang.NullPointerException
14:48:23  	at org.renaissance.apache.spark.NaiveBayes.tearDownAfterAll(NaiveBayes.scala:93)
14:48:23  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:97)
14:48:23  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
14:48:23  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
14:48:23  	at org.renaissance.RenaissanceSuite$$$Lambda$125/0000000084665830.apply(Unknown Source)
14:48:23  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
14:48:23  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
14:48:23  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
14:48:23  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
14:48:23  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
14:48:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:48:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
14:48:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:48:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
14:48:23  	at org.renaissance.Launcher.main(Launcher.java:18)
14:48:23  Exception occurred in org.renaissance.apache.spark.NaiveBayes@9162eb02: null
14:48:23  java.lang.ExceptionInInitializerError
14:48:23  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:186)
14:48:23  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:175)
14:48:23  	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:76)
14:48:23  	at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:362)
14:48:23  	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$29.apply(SparkContext.scala:985)
14:48:23  	at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$29.apply(SparkContext.scala:985)
14:48:23  	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:177)
14:48:23  	at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:177)
14:48:23  	at scala.Option.map(Option.scala:146)
14:48:23  	at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:177)
14:48:23  	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:196)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
14:48:23  	at scala.Option.getOrElse(Option.scala:121)
14:48:23  	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
14:48:23  	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
14:48:23  	at scala.Option.getOrElse(Option.scala:121)
14:48:23  	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
14:48:23  	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
14:48:23  	at scala.Option.getOrElse(Option.scala:121)
14:48:23  	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
14:48:23  	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
14:48:23  	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
14:48:23  	at scala.Option.getOrElse(Option.scala:121)
14:48:23  	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
14:48:23  	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:65)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKeyWithClassTag$3.apply(PairRDDFunctions.scala:629)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKeyWithClassTag$3.apply(PairRDDFunctions.scala:629)
14:48:23  	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
14:48:23  	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
14:48:23  	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions.combineByKeyWithClassTag(PairRDDFunctions.scala:628)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKey$3.apply(PairRDDFunctions.scala:616)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$combineByKey$3.apply(PairRDDFunctions.scala:616)
14:48:23  	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
14:48:23  	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
14:48:23  	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
14:48:23  	at org.apache.spark.rdd.PairRDDFunctions.combineByKey(PairRDDFunctions.scala:615)
14:48:23  	at org.apache.spark.mllib.classification.NaiveBayes.run(NaiveBayes.scala:382)
14:48:23  	at org.renaissance.apache.spark.NaiveBayes.runIteration(NaiveBayes.scala:115)
14:48:23  	at org.renaissance.RenaissanceBenchmark.runIterationWithBeforeAndAfter(RenaissanceBenchmark.java:125)
14:48:23  	at org.renaissance.FixedIterationsPolicy.execute(FixedIterationsPolicy.java:48)
14:48:23  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:86)
14:48:23  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
14:48:23  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
14:48:23  	at org.renaissance.RenaissanceSuite$$$Lambda$125/0000000084665830.apply(Unknown Source)
14:48:23  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
14:48:23  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
14:48:23  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
14:48:23  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
14:48:23  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
14:48:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
14:48:23  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
14:48:23  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
14:48:23  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
14:48:23  	at org.renaissance.Launcher.main(Launcher.java:18)
14:48:23  Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
14:48:23  	at java.base/java.lang.String.substring(String.java:2663)
14:48:23  	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:48)
14:48:23  	... 59 more
14:48:23  The following benchmarks failed: naive-bayes
```

**Comment by DanHeidinga** [comment] 2020-09-14 14:04
We need a stop-ship decision on this failure found in the 0.22.0 M2 build

**Comment by tajila** [comment] 2020-09-14 14:29
@mikezhang1234567890 can you please investigate this issue

**Comment by mikezhang1234567890** [comment] 2020-09-14 14:53
Looking into it now.

**Comment by mikezhang1234567890** [comment] 2020-09-14 18:37
The issue seems to be build differences . Trying with a [build from the OpenJ9 Jenkins](https://ci.eclipse.org/openj9/job/Build_JDK15_x86-64_linux_Nightly/48/) does not have this error. The builds have the same SHAs for OpenJ9, OMR, and the openJDK repos:
```
mike@forms1:~/scratch/sparktest$ ./eclipse-jdk15/bin/java -version
openjdk version "15-internal" 2020-09-15
OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15x86-64linuxNightly)
Eclipse OpenJ9 VM (build master-6648d4de734, JRE 15 Linux amd64-64-Bit Compressed References 20200913_48 (JIT enabled, AOT enabled)
OpenJ9   - 6648d4de734
OMR      - 58b0c18383a
JCL      - ad829e12c8f based on jdk-15+36)
mike@forms1:~/scratch/sparktest$ ./adopt-jdk-15+36/bin/java -version
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36-202009132042)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-6648d4de7, JRE 15 Linux amd64-64-Bit Compressed References 20200913_36 (JIT enabled, AOT enabled)
OpenJ9   - 6648d4de7
OMR      - 58b0c1838
JCL      - ad829e12c8 based on jdk-15+36)
```

It could be because of different set up or the difference between internal and release builds.

**Comment by lumpfish** [comment] 2020-09-15 09:07
Looks like this test is also failing on jdk15 hotspot: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1932

**Comment by tajila** [comment] 2020-09-15 12:44
@llxia do you know who owns these tests?

**Comment by llxia** [comment] 2020-09-15 14:23
`renaissance-naive-bayes` test is from [renaissance-benchmarks](https://github.com/renaissance-benchmarks/renaissance).

**Comment by llxia** [comment] 2020-09-15 14:29
Tested in Grinder and got the same result as Mike:

- Passed using openj9 SDK from [Build_JDK15_x86-64_linux_Nightly/49](https://ci.eclipse.org/openj9/job/Build_JDK15_x86-64_linux_Nightly/49/): 
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1042/
- Failed using openj9 SDK from [Adopt](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-x64-openj9/37/): 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3885/

**Comment by DanHeidinga** [comment] 2020-09-16 15:21
Based on discussion in https://github.com/AdoptOpenJDK/TSC/issues/174#issuecomment-693426034, we agree this is not a stop-ship issue for the JDK15 release

**Comment by llxia** [comment] 2020-09-16 16:46
Reran using openj9 SDK from Build_JDK15_x86-64_linux_Nightly/49 at Adopt and the same machine test-godaddy-debian8-x64-3, the test passed https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3922/

**Comment by pshipton** [comment] 2020-09-23 20:24
I'll move this to the backlog since the test is questionable as it also fails on Hotspot.

**Comment by smlambert** [comment] 2020-10-13 02:44
Given this is occurring in both hotspot and openj9 builds at AdoptOpenJDK, and not reproducible against builds from OpenJ9, will close this and track under https://github.com/AdoptOpenJDK/openjdk-tests/issues/1932

**Closed by smlambert** 2020-10-13 02:44 UTC
Labels: test failure
