### ISSUE TITLE
java -version is every slow on centos7 

### ISSUE THREAD

**Issue by 15838028035** [eclipse/openj9#11148] opened 2020-11-11 03:33 UTC
Hi , when i run  java -version on linux   CentOS Linux release 7.6.1810 (Core),
 some times later , java version print.  It  is every  every  slow on centos7 

i config JAVA_HOME、path use linux export commond  in bash.profile .

 cloud you help me ?

**Comment by pshipton** [comment] 2020-11-11 03:40
I'm guessing it's related to the memory allocation, where the JVM is trying to find memory below 4GB. Please try the XL variant to see if it is also slow to startup. 
For example https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u272-b10_openj9-0.23.0/OpenJDK8U-jdk_x64_linux_openj9_linuxXL_8u272b10_openj9-0.23.0.tar.gz

**Comment by pshipton** [comment] 2020-11-11 03:53
How can I recreate the problem? What JVM -version are you using? For me on `CentOS Linux release 7.6.1810 (Core)`, the following JVM starts immediately.

```
jdk8u272-b10/bin/java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
Eclipse OpenJ9 VM (build openj9-0.23.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201022_822 (JIT enabled, AOT enabled)
OpenJ9   - 0394ef754
OMR      - 582366ae5
JCL      - 41f03341d5 based on jdk8u272-b10)
```

**Comment by 15838028035** [comment] 2020-11-11 10:09
![图片](https://user-images.githubusercontent.com/12193885/98798593-00d36a80-2449-11eb-824a-03320ffd1ef8.png)

**Comment by pshipton** [comment] 2020-11-11 13:49
Pls try the newer version in case the problem has been fixed. I know we did fix something related to memory allocation at some point.

**Comment by 15838028035** [comment] 2020-11-11 13:54
Okay! Thanks! 

发自我的iPhone

**Comment by pshipton** [comment] 2020-11-18 16:33
I'll close this assuming the problem is resolved, if there is still a problem please let us know.

**Closed by pshipton** 2020-11-18 16:33 UTC
Labels: userRaised
