### ISSUE TITLE
JIT crash vmState=0x00000000 x86 mauve -Xjit:count=0 -Xaggressive

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8866] opened 2020-03-15 20:25 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Personal/83
MauveMultiThreadLoadTest_special_22
variation: Mode688
JVM_OPTIONS: -Xcompressedrefs -Xcompressedrefs -Xjit:count=0 -Xgcpolicy:gencon -Xaggressive -Xconcurrentlevel0 
```
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=000000006E7B6292 ContextFlags=0010005f
LT  stderr Handler1=00007FFD64D5DDC0 Handler2=00007FFD6DBE8300 InaccessibleReadAddress=0000000000000018
LT  stderr RDI=000000005AE0F07B RSI=000000005AE0F080 RAX=0000000000000000 RBX=00000000016BB000
LT  stderr RCX=00000000FFF06400 RDX=000000005AE0F080 R8=000000006EC92EF0 R9=00000000016BB800
LT  stderr R10=0000000001178F90 R11=00000000FFFF0000 R12=00000000FFEAAFD0 R13=0000000000000010
LT  stderr R14=0000000000000000 R15=00000000FFEAAF80
LT  stderr RIP=000000006E7B6292 RSP=0000000001636EE0 RBP=000000000162BD00 GS=002B
LT  stderr FS=0053 ES=002B DS=002B
LT  stderr XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_special.system_x86-64_windows_Personal\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9jit29.dll
LT  stderr Module_base_address=000000006E630000 Offset_in_DLL=0000000000186292
LT  stderr Target=2_90_20200315_653 (Windows Server 2012 R2 6.3 build 9600)
LT  stderr CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr Java_java_lang_invoke_MutableCallSite_invalidate+0xf0a72 (0x000000006E7B6292 [j9jit29+0x186292])
LT  stderr (0x00000000FFF06400)
LT  stderr (0x00000000FFF06400)
LT  stderr (0x00000000FFEA9CC0)
LT  stderr (0x00000000FFEA9CE0)
LT  stderr Java_java_lang_invoke_MutableCallSite_invalidate+0x5cda30 (0x000000006EC93250 [j9jit29+0x663250])
LT  stderr (0x000000005AE0F080)
LT  stderr (0x0000000040000000)
LT  stderr (0x000000005AE0CC8C)
LT  stderr (0x000000005AE0CC8C)
LT  stderr (0x000000005AE0CC8C)
LT  stderr (0x00000000FFF05F60)
LT  stderr (0x00000000012AF598)
LT  stderr (0x0000000040000000)
LT  stderr (0x000000005AE0BC47)
LT  stderr ---------------------------------------
```

**Comment by DanHeidinga** [comment] 2020-03-16 03:28
fyi @andrewcraik

**Comment by andrewcraik** [comment] 2020-03-16 13:47
That backtrace is garbage given the offsets on the symbols. This looks a bit like something @liqunl and/or @dsouzai were looking at just based on the weird backtrace. That being said we need to get the core loaded in windbg to try and figureout where the crash really happened since the printed trace is not accurate.

**Comment by pshipton** [comment] 2020-03-16 13:47
Note we now have a debug image artifact on the JVM build that can be used to look at the core file and see where the crash occurred.
https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_windows_Personal/653/

**Comment by pshipton** [comment] 2020-03-16 14:16
Unfortunately this jdk8 debug image still contains .diz files. These are zipped up .pdb files and .map files that have to be unzipped before the debugger will find them. It's WIP to fix this, but should be resolved shortly in newer builds.

**Comment by pshipton** [comment] 2020-03-18 12:41
JVM and debug image https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_linux_Nightly/325/

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/1356
MauveMultiThreadLoadTest_special_22
```
LT  02:42:12.850 - Starting thread. Suite=0 thread=6
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=00007FB60E865E80 Handler2=00007FB60E1579F0 InaccessibleAddress=00000000FFC61CB0
LT  stderr RDI=00007FB5F2C30163 RSI=00007FB5F2C30168 RAX=0000000000000048 RBX=000000000229AE00
LT  stderr RCX=00000000FFC61B00 RDX=00007FB5F2C30168 R8=0000000002080730 R9=000000000229BB00
LT  stderr R10=0000000002051370 R11=0000000000000000 R12=00000007FFEB2858 R13=00000007FFEB3B18
LT  stderr R14=0000000000000001 R15=00000007FFEB3AC8
LT  stderr RIP=00007FB60737A2AA GS=0000 FS=0000 RSP=00000000020806E0
LT  stderr EFlags=0000000000010217 CS=0033 RBP=0000000002051300 ERR=0000000000000004
LT  stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00000000FFC61CB0
LT  stderr xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm1 62412f6c6974752f (f: 1769239808.000000, d: 1.979263e+165)
LT  stderr xmm2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm3 7463617274736241 (f: 1953718912.000000, d: 4.440325e+252)
LT  stderr xmm4 000000003ecccde7 (f: 1053609472.000000, d: 5.205522e-315)
LT  stderr xmm5 00000000390e7854 (f: 957249600.000000, d: 4.729442e-315)
LT  stderr xmm6 0000000001cd35d8 (f: 30225880.000000, d: 1.493357e-316)
LT  stderr xmm7 000000003e2a0984 (f: 1042942336.000000, d: 5.152820e-315)
LT  stderr xmm8 0000000001cd3558 (f: 30225752.000000, d: 1.493351e-316)
LT  stderr xmm9 0000000001cd3538 (f: 30225720.000000, d: 1.493349e-316)
LT  stderr xmm10 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
LT  stderr xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm12 000000003febe111 (f: 1072423168.000000, d: 5.298475e-315)
LT  stderr xmm13 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
LT  stderr xmm14 0000000047002000 (f: 1191190528.000000, d: 5.885263e-315)
LT  stderr xmm15 4103c9595c0aa61e (f: 1544201728.000000, d: 1.620912e+05)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_special.system_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9jit29.so
LT  stderr Module_base_address=00007FB606FFE000
LT  stderr Target=2_90_20200317_325 (Linux 4.4.0-140-generic)
LT  stderr CPU=amd64 (8 logical CPUs) (0x3eae99000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x00007FB60E186D62 [libj9prt29.so+0x49d62])
LT  stderr (0x00007FB60E158753 [libj9prt29.so+0x1b753])
LT  stderr (0x00007FB60E186DDE [libj9prt29.so+0x49dde])
LT  stderr (0x00007FB60E186ED4 [libj9prt29.so+0x49ed4])
LT  stderr (0x00007FB60E158753 [libj9prt29.so+0x1b753])
LT  stderr (0x00007FB60E186C3B [libj9prt29.so+0x49c3b])
LT  stderr (0x00007FB60E8659C4 [libj9vm29.so+0x929c4])
LT  stderr (0x00007FB60E158753 [libj9prt29.so+0x1b753])
LT  stderr (0x00007FB60E865C35 [libj9vm29.so+0x92c35])
LT  stderr (0x00007FB60E892A15 [libj9vm29.so+0xbfa15])
LT  stderr ---------------------------------------
```

**Comment by pshipton** [comment] 2020-03-18 13:02
Using the debug symbols for the previous crash, obtained the following stack trace from gdb.
```
frames for handling the crash, not relevant 
#10 0x00007fb60e865c35 in vmSignalHandler (portLibrary=0x7fb60ef9c340 <j9portLibrary>, gpType=24, gpInfo=<optimized out>, 
    userData=<optimized out>) at gphandle.c:841
#11 0x00007fb60e892a15 in swapStacksAndRunHandler () at stackswap.s:146
#12 0x0000000002051300 in ?? ()
#13 0x00007fb5d20c0980 in ?? ()
#14 0x00007fb5f2c301e0 in ?? ()
#15 0x000000000229ae00 in ?? ()
#16 0x00000000ffc61b00 in ?? ()
#17 0x00007fb5f2c30168 in ?? ()
#18 0x00007fb5f2c30163 in ?? ()
#19 0x00007fb5f2c30168 in ?? ()
#20 0x00007fb6080104f0 in ?? ()
#21 0x00007fb60e83820f in classHashGetName (nameLength=0x7fb5d20c0890, name=<synthetic pointer>, entry=0x18)
    at KeyHashTable.c:84
#22 classHashEqualFn (tableNode=0x18, queryNode=0x2080040, userData=0x7fb5d20c0980) at KeyHashTable.c:101
#23 0x62412f6c6974752f in ?? ()
#24 0x0000000000000000 in ?? ()
```

**Comment by pshipton** [comment] 2020-06-15 01:54
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_x86-64_windows_Personal_mauveLoadTest/5
MauveSingleInvocationLoadTest_special_22
```
LT  11:08:16.474 - Completed 80.1%. Number of tests started=2256
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FF87949C3C2 ContextFlags=0010005f
LT  stderr Handler1=00007FF87B2BFC80 Handler2=00007FF87CD68900 InaccessibleReadAddress=0000000000000019
LT  stderr RDI=00007FF8663CA9C3 RSI=00007FF8663CA9C8 RAX=0000000000000001 RBX=0000000001E32900
LT  stderr RCX=00000000FFBD6000 RDX=00007FF8663CA9C8 R8=0000000000000000 R9=0000000001E32C00
LT  stderr R10=000000000147E840 R11=00000000FFFF0000 R12=00000000FFFDEF28 R13=0000000000000010
LT  stderr R14=000000002553F848 R15=00000000FFFDEED8
LT  stderr RIP=00007FF87949C3C2 RSP=0000000001A9C650 RBP=0000000001A95000 GS=002B
LT  stderr FS=0053 ES=002B DS=002B
LT  stderr XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM8 3fdfd535dd2acfe8 (f: 3710570496.000000, d: 4.973883e-001)
LT  stderr XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
LT  stderr Module=C:\Users\jenkins\workspace\Test_openjdk8_j9_special.system_x86-64_windows_Personal_mauveLoadTest\openjdkbinary\j2sdk-image\jre\bin\compressedrefs\j9jit29.dll
LT  stderr Module_base_address=00007FF879310000 Offset_in_DLL=000000000018c3c2
LT  stderr Target=2_90_20200614_757 (Windows Server 2012 R2 6.3 build 9600)
LT  stderr CPU=amd64 (8 logical CPUs) (0x1ffb9c000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr Java_java_lang_invoke_MutableCallSite_invalidate+0xf2a32 (0x00007FF87949C3C2 [j9jit29+0x18c3c2])
LT  stderr (0x00000000FFBD6000)
LT  stderr (0x00000000FFBD6000)
LT  stderr (0x00000000FFFDDB88)
LT  stderr (0x00000000FFFDDBA8)
LT  stderr Java_java_lang_invoke_MutableCallSite_invalidate+0x5d98c0 (0x00007FF879983250 [j9jit29+0x673250])
LT  stderr (0x00007FF8663CA9C8)
LT  stderr (0x00007FF86631C754)
LT  stderr (0x00007FF86631C754)
LT  stderr (0x00000000FFBD5E60)
LT  stderr ---------------------------------------
```

**Comment by cathyzhyi** [comment] 2020-06-23 13:03
@nbhuiyan is helping to investigate.

**Comment by nbhuiyan** [comment] 2020-08-07 15:53
While I was able to reproduce this crash in June, it is no longer reproducible with the latest nightly builds. @andrewcraik

**Comment by andrewcraik** [comment] 2020-08-10 12:18
This was likely fixed by other changes around the time it was last observed. I am closing this, but please reopen if the issue recurs in testing since we believe it be fixed in later builds.

**Closed by andrewcraik** 2020-08-10 12:18 UTC
Labels: comp:jit, segfault, test failure
