### ISSUE TITLE
OOM running pull request testing on plinux

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#968] opened 2018-01-17 22:15 UTC
We've seen this a couple of times today. 

https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/328/console

```
15:40:02 package org.openj9.resources.annotationPackage
15:40:02 PASSED: test_elementFormDefault
15:40:02 PASSED: test_isAnnotationPresent
15:40:02 
15:40:02 ===============================================
15:40:02     JCL_TEST_Test-Annotation-Package
15:40:02     Tests run: 2, Failures: 0, Skips: 0
15:40:02 ===============================================
15:40:02 
15:40:02 org.openj9.test.java.lang.
15:40:03 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/01/17 20:40:03 - please wait.
15:40:03 JVMDUMP032I JVM requested System dump using '/home/jenkins/jenkins-agent/workspace/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/core.20180117.204003.20846.0001.dmp' in response to an event
```
It also occurred in testing for #962. 
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/326/console

Both of these occurred on ub16-ppcle-3

It didn't reoccur on restart, which occurred on ub16-ppcle-2
https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/329/console

**Comment by pshipton** [comment] 2018-01-17 22:20
Happened in the last nightly build https://ci.eclipse.org/openj9/view/Test/job/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/49/console 
on ub16-ppcle-4

**Comment by AdamBrousseau** [comment] 2018-01-17 22:26
Also [315](https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/315/consoleFull) on ub16-ppcle-3

**Comment by dmitripivkine** [comment] 2018-01-17 23:10
I have seen this before. This looks like an attempt of allocation of reference array with 2GB elements (intentional OOM). Test itself seems passed even with OOM thrown

**Comment by pshipton** [comment] 2018-01-17 23:14
Looking at the console output, in this case the OOM seems to have terminated the VM.

**Comment by pshipton** [comment] 2018-01-17 23:16
A working test should look like the following, and continue to run

```
org.openj9.test.java.lang.
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/01/17 15:36:20 - please wait.
JVMDUMP032I JVM requested System dump using '/tmp/bld_376274/openj9/test/TestConfig/core.20180117.153620.1943.0001.dmp' in response to an event
JVMDUMP010I System dump written to /tmp/bld_376274/openj9/test/TestConfig/core.20180117.153620.1943.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/tmp/bld_376274/openj9/test/TestConfig/heapdump.20180117.153620.1943.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /tmp/bld_376274/openj9/test/TestConfig/heapdump.20180117.153620.1943.0002.phd
JVMDUMP032I JVM requested Java dump using '/tmp/bld_376274/openj9/test/TestConfig/javacore.20180117.153620.1943.0003.txt' in response to an event
JVMDUMP010I Java dump written to /tmp/bld_376274/openj9/test/TestConfig/javacore.20180117.153620.1943.0003.txt
JVMDUMP032I JVM requested Snap dump using '/tmp/bld_376274/openj9/test/TestConfig/Snap.20180117.153620.1943.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /tmp/bld_376274/openj9/test/TestConfig/Snap.20180117.153620.1943.0004.trc
JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
[Support_Exec] [INFO] ***9-internal+0-adhoc.openj9.openjdk
JRE 9 IBM J9 2.9 Linux ppc64le-64 Compressed References 20180117_376274 (JIT enabled, AOT enabled)
OpenJ9   - b338003
OMR      - 3cda7d8***
org.openj9.test.java.lang.Test_System$TestSecurityManager
Exception in thread "no-op thread" org.openj9.test.java.lang.Test_ThreadGroup$1UncaughtException
	at org.openj9.test.java.lang.Test_ThreadGroup$14.uncaughtException(Test_ThreadGroup.java:1204) from jdk.internal.loader.ClassLoaders$AppClassLoader@76597532(file:/tmp/bld_376274/openj9/jvmtest/Java8andUp/GeneralTest.jar)
	at java.lang.Thread.uncaughtException(java.base@9-internal/Thread.java:1354) from jrt:/java.base
org.openj9.test.java.lang.Test_Throwable$TestException: test
PASSED: dummyReflectHelper
PASSED: testDefaultMethodInheritance
PASSED: testInterfaceMethodInheritance
...
```

**Comment by pshipton** [comment] 2018-01-17 23:32
Seems I looked at the wrong javacore file. The message from the matching console is as follows. There is a core and heapdump, but no javacore file. Seems like an unreported crash occurred either before or early in javacore creation.

```
01:43:37 JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/01/17 06:43:36 - please wait.
01:43:37 JVMDUMP032I JVM requested System dump using '/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/core.20180117.064336.20821.0001.dmp' in response to an event
01:46:06 JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.20889.
01:46:06 
01:46:06 JVMDUMP010I System dump written to /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/core.20180117.064336.20821.0001.dmp
01:46:06 JVMDUMP032I JVM requested Heap dump using '/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK9-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/heapdump.20180117.064336.20821.0002.phd' in response to an event
```

**Comment by pshipton** [comment] 2018-01-18 15:13
Note we don't have the ability to properly analyse the core files from OpenJ9 since there is no DDR support yet.

**Comment by TianyuZuo** [comment] 2018-02-13 16:18
This OOM message does not have relationship with JCL_TEST_Test-Annotation-Package because it was actually generated by 
18:29:55 ===============================================
18:29:55     JCL_TEST_Java-Lang
18:29:55     Tests run: 357, Failures: 0, Skips: 0
18:29:55 ===============================================
(link https://ci.eclipse.org/openj9/job/PullRequest-Sanity-linux_ppc-64_cmprssptrs_le/397/consoleFull)

The test `/test/Java8andUp/src/org/openj9/test/java/lang/Test_OutOfMemoryError.java` belongs to the JCL_TEST_Java-Lang test target. In the test, it is generating the OOM on purpose and testing the OOM behaviour. And the same test failure message also exists in jvm.28 builds. I think this is an expected behaviour. If there is cmd options to hide this output, we can add it into the test cmds.

**Comment by DanHeidinga** [comment] 2018-03-12 15:11
@TianyuZuo Any update on this?

**Comment by TianyuZuo** [comment] 2018-03-12 15:33
This should be fixed by https://github.com/eclipse/openj9/pull/1169

**Comment by DanHeidinga** [comment] 2018-03-13 01:57
Closing this.  Please reopen if the issue is seen again.

**Closed by DanHeidinga** 2018-03-13 01:57 UTC
Labels: test failure
