### ISSUE TITLE
MacOS signal handling: cmdLineTest_sigxfszHandlingTest_0 fails

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#3445] opened 2018-10-25 13:57 UTC
```
make -f ../functional/cmdLineTests/sigxfszHandlingTest/autoGen.mk _all
...
Testing: -XX:+HandleSIGXFSZ
Test start time: 2018/10/25 09:55:47 Eastern Standard Time
Running command: "/Users/pdbain/vm/openj9-openjdk-jdk11/build/macosx-x86_64-normal-server-release/images/jdk/bin/java" -Xcompressedrefs  -cp "/Users/pdbain/macprojects/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdline_options_testresources/cmdlinetestresources.jar" -XX:+HandleSIGXFSZ j9vm.test.sigxfsz.SignalXfszTest test.txt
Time spent starting: 6 milliseconds
Time spent executing: 3588 milliseconds
Test result: FAILED
Output from test:
 [OUT] Starting SignalXfszTest
 [OUT] File is written successfully
>> Failure condition was found: [Output match: File is written successfully]
```

**Comment by babsingh** [comment] 2018-10-25 15:06
This is a duplicate of https://github.com/eclipse/openj9/issues/3342.

Correct behavior of the above testcase: `Failed to write the file`.

fyi - @tajila

**Comment by pshipton** [comment] 2018-10-25 16:59
Closing since its a dup.

**Closed by pshipton** 2018-10-25 16:59 UTC
