### ISSUE TITLE
Too many open files error running Maven build of JRuby

### ISSUE THREAD

**Issue by headius** [eclipse/openj9#4717] opened 2019-02-13 04:57 UTC
The JRuby maven build does touch a lot of files, but under HotSpot JDK8, the build completes fine.

When run on OpenJ9 JDK8 I get the following result:

```
[INFO] --- maven-jar-plugin:3.0.0:jar (default-jar) @ jruby-stdlib ---
[INFO] Building jar: /Users/headius/projects/jruby/lib/target/jruby-stdlib-9.2.6.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JRuby 9.2.6.0 ...................................... SUCCESS [  0.297 s]
[INFO] JRuby Core ......................................... SUCCESS [ 35.767 s]
[INFO] JRuby Lib Setup 9.2.6.0 ............................ FAILURE [ 16.525 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 56.333 s
[INFO] Finished at: 2019-02-12T22:54:46-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.0:jar (default-jar) on project jruby-stdlib: Error assembling JAR: Problem creating jar: Execution exception: java.io.FileNotFoundException: /Users/headius/projects/jruby/lib/target/classes/META-INF/jruby.home/bin/rake-compiler.bat (Too many open files) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

With verbose maven logging on (`-X`) the following exceptions are at the root end of the exception chain:

```
Caused by: java.io.FileNotFoundException: /Users/headius/projects/jruby/lib/target/classes/META-INF/jruby.home/lib/ruby/stdlib/.jrubydir (Too many open files)
    at java.io.FileInputStream.open0 (Native Method)
    at java.io.FileInputStream.open (FileInputStream.java:195)
    at java.io.FileInputStream.<init> (FileInputStream.java:138)
    at org.codehaus.plexus.components.io.resources.PlexusIoFileResource$1.getContents (PlexusIoFileResource.java:99)
    at org.codehaus.plexus.components.io.resources.PlexusIoFileResource.getContents (PlexusIoFileResource.java:124)
    at org.codehaus.plexus.archiver.ArchiveEntry.getInputStream (ArchiveEntry.java:131)
    at org.codehaus.plexus.archiver.zip.AbstractZipArchiver$1.get (AbstractZipArchiver.java:498)
    at org.codehaus.plexus.archiver.zip.AbstractZipArchiver$2.get (AbstractZipArchiver.java:611)
    at org.apache.commons.compress.archivers.zip.ZipArchiveEntryRequest.getPayloadStream (ZipArchiveEntryRequest.java:62)
    at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry (ScatterZipOutputStream.java:95)
    at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$2.call (ParallelScatterZipCreator.java:175)
    at java.util.concurrent.FutureTask.run (FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
    at java.lang.Thread.run (Thread.java:813)
```

**Comment by headius** [comment] 2019-02-13 04:58
Oh to run the JRuby maven build, just clone it from https://github.com/jruby/jruby and run `mvn package` or `./mvnw package` if you don't have Maven 3.1 or higher in PATH.

**Comment by pshipton** [comment] 2019-02-13 05:25
What OpenJ9 build are you using? This sounds like a problem that was fixed after the 0.12 release of OpenJ9, and if you try a nightly build from adoptopenjdk.net it might work.

**Comment by pshipton** [comment] 2019-02-13 05:27
The fix I'm thinking of is #4442

**Comment by headius** [comment] 2019-02-14 19:28
This is a release of 8 from AdoptOpenJDK:

```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190205_147 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)
```

**Comment by DanHeidinga** [comment] 2019-02-14 19:37
The fix for #4442 didn't make it into the release.  Can you test with a nightly build from Adopt?

**Comment by headius** [comment] 2019-02-14 19:37
I just tried the latest 8 nightly and it still gives me the same error.

```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-201902140428-b08)
Eclipse OpenJ9 VM (build master-ca17a8398, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20190214_156 (JIT enabled, AOT enabled)
OpenJ9   - ca17a8398
OMR      - cbb8cd3f
JCL      - 0af09e1362 based on )
```

This also does *not* appear to break for @enebo on Linux, even with the release build.

**Comment by headius** [comment] 2019-02-14 20:14
Latest release on Linux succeeds building JRuby: https://travis-ci.org/jruby/jruby/builds/493418833

**Comment by pdbain-ibm** [comment] 2019-02-14 20:18
Could you please send the outputs of `ulimit -Sn` and `ulimit -Hn`?

**Comment by headius** [comment] 2019-02-14 20:39
```
[] ~/projects/jruby $ ulimit -Sn
256

[] ~/projects/jruby $ ulimit -Hn
unlimited
```

**Comment by pdbain-ibm** [comment] 2019-02-15 13:51
Thanks.  Working on this now.  For the record, could you add your OS version?

**Comment by pdbain-ibm** [comment] 2019-02-15 18:29
Hmmm.  Setting the soft limit == hard limit fails if the hard limit is -1, since it exceeds the OS limit. 
On MacOS the limit is `kern.maxfilesperproc: 24576` from `sysctlbyname()`, or possibly a property list on earlier versions. On Linux, it is `/proc/sys/fs/file-max`.

**Comment by pdbain-ibm** [comment] 2019-02-18 14:11
Opened OMR issue https://github.com/eclipse/omr/issues/3579.

**Comment by headius** [comment] 2019-02-22 17:38
Sorry for my absence. I'm on OS X 10.14.3. Sounds like you're on the right track though!

**Comment by pdbain-ibm** [comment] 2019-03-12 18:31
@headius would you kindly retest with the latest nightly MacOS build?

**Comment by headius** [comment] 2019-03-13 13:22
@pdbain-ibm Can do!

**Comment by headius** [comment] 2019-03-13 13:38
@pdbain-ibm The 2019-3-13 nightly appears to build JRuby successfully on MacOS!

Thanks everyone, this will make it a lot easier for me to use OpenJ9 day-to-day on JRuby work.

**Comment by pdbain-ibm** [comment] 2019-03-13 13:57
@headius would you kindly close this issue?
Many thanks for your assistance and your patience.

**Comment by fjeremic** [comment] 2019-03-13 14:12
> @headius would you kindly close this issue?
> Many thanks for your assistance and your patience.

No need for the churn, we can close on his behalf given the issue is fixed. Thanks for making OpenJ9 better everyone!

**Closed by fjeremic** 2019-03-13 14:12 UTC
Labels: userRaised

**Comment by headius** [comment] 2019-03-13 17:51
FWIW I usually don't close issues on projects I don't own, and I suspect there's many others that work the same way. We prefer users don't close JRuby issues until we've decided on a release milestone, etc (and btw it would be really nice to see real release milestones for issues like this, so I can make recommendations to folks about which release they can use).
