### ISSUE TITLE
Containerized JVM will not use more than 25GB heap without explicit configuration

### ISSUE THREAD

**Issue by psoohoo-turbonomic** [eclipse/openj9#10200] opened 2020-07-20 16:30 UTC
Java -version output
--------------------
```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.21.0, JRE 11 Linux amd64-64-Bit Compressed References 20200715_697 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 95bb504fbb based on jdk-11.0.8+10)
```

Summary of problem
------------------
When running an OpenJ9 JVM in a container that is given a memory limit of 40gb or higher, the JVM never auto-detects more than 25gb of usable max heap. According to the documentation for the "UseContainerSupport" flag, we were expecting to see the JVM use up to 75% of the available memory limit as heap.

More specifically:

- With no explicit -Xms or -Xmx or any other memory-sizing options set, the JVM would correctly auto-set the max heap to 75% of the memory limit — but only up to a point.
- That point seemed to be a hard limit of 25gb for max heap. After that point, it didn’t seem to matter how high I set the memory limit to, the JVM would never set the max heap higher than 25 gb. We would see JVM startup output verifying that the limit was recognized, but that the heap was still limited to 25gb, e.g.:
```
Operating System Metrics:
...
    Memory Limit: 40.00G
    Memory Soft Limit: Unlimited
    Memory & Swap Limit: 40.00G
    Kernel Memory Limit: Unlimited
    TCP Memory Limit: Unlimited
    Out Of Memory Killer Enabled: true
...
VM settings:
    Min. Heap Size: 16.00M
    Max. Heap Size (Estimated): 25.00G
    Using VM: Eclipse OpenJ9 VM
```
- When I explicitly set MaxRAMPercentage (to 75 in this case), the JVM will set the max heap according to the memory limit and would go beyond 25gb. Again, up until a certain point where the compressed refs boundary of 63.75gb was hit.

**Comment by pshipton** [comment] 2020-07-20 16:44
@amicic @dmitripivkine can you please take a look.

**Comment by dmitripivkine** [comment] 2020-07-22 19:45
@psoohoo-turbonomic Thank you to point to this issue.

I did review the code and discovered that it works as designed (but documentation is incomplete for container's case). So this is how it works now:
- Compressed Refs JVM can support bit shifts from 0 to 4 (with heaps up to 64GB)
- Using 4-bit shift has measurable performance negative impact for JVM
- JVM tries to get minimum shift possible (for maximum performance) attempting to apply 0, 3, 4 -bit shift sequentially (0,1,2,3,4 on Z platforms)
- OpenJ9 Compressed Refs JVM implementation required some reserve of free space below 4GB bar to put VM metadata (classes, threads etc.). We don't want to allow object heap to take too much space below 4GB bar. (Imagine for 3-bit shift (heap size limit up to 32GB) requested heap size of 29GB. It means best effort heap location is in range [3GB,32GB]. This takes 1GB space below 4GB bar for heap and can lead to native OOM low memory). Because of this reason limit of heap size for 3-bit shift is selected at 25GB.
- Default maximum heap size for container is selected as 75% of memory available
- Starting Java 11 default maximum heap size might be extended to 25% of RAM on machine if it is larger
- But: **default** maximum heap size can not exceed 25GB limit to prevent silent switching to 4-bit shift mode with possible performance penalties. Any explicit provisioning of maximum heap size would overwrite this 25GB limit.

@pshipton I believe the only action here we should fix documentation by mentioning this limit. I am not comfortable to add exception for container runs by silent overrun limit except somebody insisted strongly to do this. Do you agree?

**Comment by psoohoo-turbonomic** [comment] 2020-07-23 12:24
Thank you for the detailed explanation, @dmitripivkine. Can you quantify what the performance impact of the 4-bit shift might be? A rough guidelines would be good enough.

Also, from a performance point of view -- if we need more than 25gb heap, do you think we'd be better off using the uncompressed refs build?

Finally, and maybe this is for @pshipton -- is there a timeline for when you think the single JVM that supports both compressed and uncompressed refs might be available?

**Comment by pshipton** [comment] 2020-07-23 12:55
We are hoping to have a single JVM for the Oct release, but this isn't guaranteed. While it is working already, we are addressing the performance issues and it's hard to know if they can all be addressed by Oct.

**Comment by dmitripivkine** [comment] 2020-07-23 14:48
> Thank you for the detailed explanation, @dmitripivkine. Can you quantify what the performance impact of the 4-bit shift might be? A rough guidelines would be good enough.
 
The nature of performance impact is 4-bit shift requires start address for any object in the heap to be aligned to 16 bytes (shifts 0-3 use alignment to 8 bytes). As a result there are more unused reminders and less objects can be located in the heap. So GC must be executed more often. Also more importantly it has an impact of objects locality - CPU cache lines should be refreshed more often. In numbers (depends of application obviously) an impact can reach 3-5% of application throughput.

> Also, from a performance point of view -- if we need more than 25gb heap, do you think we'd be better off using the uncompressed refs build?

4-bit shift Compressed Refs JVM usually performs better than Full 64-bit (throughput comparing with 3-bit shift in average minus 3-5% for 4-bit vs. minus 8-10% for Full) but it can be used if heap size does not exceed 58-59GB realistically.

**Comment by psoohoo-turbonomic** [comment] 2020-07-24 13:43
> The nature of performance impact is 4-bit shift requires start address for any object in the heap to be aligned to 16 bytes (shifts 0-3 use alignment to 8 bytes). As a result there are more unused reminders and less objects can be located in the heap. So GC must be executed more often. Also more importantly it has an impact of objects locality - CPU cache lines should be refreshed more often. In numbers (depends of application obviously) an impact can reach 3-5% of application throughput.
> 
> > Also, from a performance point of view -- if we need more than 25gb heap, do you think we'd be better off using the uncompressed refs build?
> 
> 4-bit shift Compressed Refs JVM usually performs better than Full 64-bit (throughput comparing with 3-bit shift in average minus 3-5% for 4-bit vs. minus 8-10% for Full) but it can be used if heap size does not exceed 58-59GB realistically.

Thanks for the detailed reply, @dmitripivkine. This is very helpful to know! I wonder if there's a place in the docs that some performance guidance like this re: heap sizes and reference sizes could go? 

Patrick

**Comment by psoohoo-turbonomic** [comment] 2020-07-24 14:18
I'd also like to add another comment after thinking about it. It's understandable why it doesn't engage the 4-bit shift mode automatically, but from a user point of view it can be seen as non-intuitive behavior. Can I ask that you consider one of:

- if Max Heap is capped at 25gb, output something explaining why, as well as a hint of how to "fix" it. (e.g. "please set -Xmx or -MaxRAMPercentage...")
- DO switch to 4-bit shift, because in many cases that may be the desired behavior, but log a warning that it was turned on due to the memory limit setting.

In any case, having documentation about the behavior is probably the most important thing to do.

Thanks again for the quick follow up, guys!

**Comment by dmitripivkine** [comment] 2020-07-24 16:14
> * DO switch to 4-bit shift, because in many cases that may be the desired behavior, but log a warning that it was turned on due to the memory limit setting.

The problem I see with this approach is in general starting with Java 11 default value for -Xmx can be selected as large as 25% of machine RAM. We observed a number of cases when `-Xmx` is not specified explicitly and customers have no idea that running with huge heaps. If large heap is not necessary JVM would not expand it fully however 4-bit shift has to be selected regardless. And this a reason for hidden performance loss. Also there are platforms where memory allocation does not support real virtualization so physical memory would be allocated at JVM start time (zOS for instance). Yes, we can add number of exceptions to behave differently in various environments (containerized, non-Unix based etc.) but my vote would be against it. Any exception just reason for extra confusion. Current approach looks more reasonable - if you have special requirements please do specify JVM options explicitly. There should be clear instructions in documentation. I absolutely agree with this point.
Any way, all this JVM startup logic would be reviewed for coming new Compressed Refs/Full JVM Combo.
I believe we should have a public discussion regarding this and similar issues.

**Comment by psoohoo-turbonomic** [comment] 2020-07-24 19:32
> The problem I see with this approach is in general starting with Java 11 default value for -Xmx can be selected as large as 25% of machine RAM. We observed a number of cases when `-Xmx` is not specified explicitly and customers have no idea that running with huge heaps. If large heap is not necessary JVM would not expand it fully however 4-bit shift has to be selected regardless. And this a reason for hidden performance loss. Also there are platforms where memory allocation does not support real virtualization so physical memory would be allocated at JVM start time (zOS for instance). Yes, we can add number of exceptions to behave differently in various environments (containerized, non-Unix based etc.) but my vote would be against it. Any exception just reason for extra confusion. Current approach looks more reasonable - if you have special requirements please do specify JVM options explicitly. There should be clear instructions in documentation. I absolutely agree with this point.

Ahh, I had forgotten about the non-container cases. :) What you wrote sounds sensible, and the current behavior does sound like a good compromise. I think we agree that as long as it's mentioned in the documentation (and "googleable"), it's pretty easy to configure, especially once one knows how the max heap is being determined. An explicit mention of the 25gb cap would be useful for search purposes too.

Thanks again for the follow up, @dmitripivkine .

**Closed** 2020-09-02 15:39 UTC
Labels: comp:gc, doc:externals, userRaised
