### ISSUE TITLE
testJITServer_1 testServerGoesDown AssertionError

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8653] opened 2020-02-25 14:12 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/290
testJITServer_1
```
xception in thread "main" java.lang.NullPointerException
	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:345)
	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1084)
	at java.security.AccessController.doPrivileged(AccessController.java:770)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
	at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:260)
	at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:40)
	at org.testng.TestRunner.fireEvent(TestRunner.java:772)
	at org.testng.TestRunner.afterRun(TestRunner.java:741)
	at org.testng.TestRunner.run(TestRunner.java:509)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)
```
```
FAILED: testServerGoesDown
java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.fail(AssertJUnit.java:66)
	at jit.test.jitserver.JITServerTest.destroyAndCheckProcess(JITServerTest.java:122)
	at jit.test.jitserver.JITServerTest.testServerGoesDown(JITServerTest.java:208)
```

**Comment by pshipton** [comment] 2020-02-25 14:13
@mpirvu

**Comment by mpirvu** [comment] 2020-02-25 14:24
@ymanton since you added this new test, could you please look into it? Thanks

**Comment by ymanton** [comment] 2020-02-25 15:59
The client JVM, which is also running TestNG, hit the following exception after completing most of the test and moving on to generating some HTML log:

```
[2020-02-25T13:33:23.114Z] [JITServerTest] [INFO] Stopping client...
[2020-02-25T13:33:28.547Z] Expected a return value of 0 or 143, got 1 instead.
[2020-02-25T13:33:28.547Z] Dumping the contents of log file: /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15826326079491/testJITServer_1/testServerGoesDown.client.out
[2020-02-25T13:33:28.547Z] 
[2020-02-25T13:33:28.547Z] JITServer is currently a technology preview. Its use is not yet supported
[2020-02-25T13:33:28.547Z] JIT: env var TR_Options is set to verbose={compileEnd|JITServer|heartbeat},vlog=testServerGoesDown.client.jitverboselog.out
[2020-02-25T13:33:28.547Z] [IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk8_j9_sanity.functional_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
[2020-02-25T13:33:28.547Z] ...
[2020-02-25T13:33:28.547Z] ... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
[2020-02-25T13:33:28.547Z] ...
[2020-02-25T13:33:28.547Z] 
[2020-02-25T13:33:28.547Z] Exception in thread "main" java.lang.NullPointerException
[2020-02-25T13:33:28.547Z] 	at sun.misc.URLClassPath$FileLoader.getResource(URLClassPath.java)
[2020-02-25T13:33:28.547Z] 	at sun.misc.URLClassPath.getResource(URLClassPath.java:345)
[2020-02-25T13:33:28.547Z] 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1084)
[2020-02-25T13:33:28.547Z] 	at java.security.AccessController.doPrivileged(AccessController.java:770)
[2020-02-25T13:33:28.547Z] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
[2020-02-25T13:33:28.547Z] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
[2020-02-25T13:33:28.547Z] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
[2020-02-25T13:33:28.547Z] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[2020-02-25T13:33:28.547Z] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
[2020-02-25T13:33:28.547Z] 	at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:260)
[2020-02-25T13:33:28.547Z] 	at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:40)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestRunner.fireEvent(TestRunner.java:772)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestRunner.afterRun(TestRunner.java:741)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestRunner.run(TestRunner.java:509)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2020-02-25T13:33:28.547Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.runSuites(TestNG.java:1049)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.run(TestNG.java:1017)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.privateMain(TestNG.java:1354)
[2020-02-25T13:33:28.547Z] 	at org.testng.TestNG.main(TestNG.java:1323)
```

This looks to be either a bug in TestNG or a legitimate bug against the JVM or specifically the code generated by the JIT or JITServer. The test itself seems to be working as designed. I'll look a bit deeper.

**Comment by ymanton** [comment] 2020-02-27 16:01
I haven't been able to recreate this at all after many iterations. The JIT logs from the one failure above show that the method that throws the exception was compiled on the server:

```
#JITServer: Client sending compReq seqNo=235 to server for method sun/misc/URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; @ hot.
...
#JITServer: Client successfully loaded method sun/misc/URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; @ hot following compilation request. [metaData=00007FD0D887B078, startPC=00007FD0DA9BC694]
+ (hot) sun/misc/URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; @ 00007FD0DA9BC694-00007FD0DA9C0CAA OrdinaryMethod - Q_SZ=7 Q_SZI=7 QW=420 j9m=00007FD08C025F28 bcsz=164 OSR remote compThread=3 CpuLoad=568%(71%avg) JvmCpu=80%
```

The server log shows the corresponding activity:

```
#JITServer: compThreadID=3 found clientSessionData=00007FD03C39ECA0 for clientUID=6136771216714376899 seqNo=235
#JITServer: Server will process a list of 0 unloaded classes for clientUID 6136771216714376899
...
+ (hot) sun/misc/URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource; @ 00007FD02A600034-00007FD02A60464A OrdinaryMethod - Q_SZ=0 Q_SZI=0 QW=0 j9m=00007FD08C025F28 bcsz=164 OSR compThread=3 CpuLoad=70%(8%avg) JvmCpu=0%
#JITServer: compThreadID=3 has successfully compiled sun/misc/URLClassPath$FileLoader.getResource(Ljava/lang/String;Z)Lsun/misc/Resource;
```

The only notable thing is the **OSR** bit. I seem to recall that OSR was not working and therefore disabled under JITServer so I wouldn't expect this. @mpirvu is that correct?

**Comment by mpirvu** [comment] 2020-02-27 16:15
>  I seem to recall that OSR was not working 

JITServer can do OSR compilations. OSR was enabled quite a while ago.

**Comment by ymanton** [comment] 2020-02-27 19:52
OK, not much else to go on. I'll let this issue sit for a while until it can be reproduced.

**Comment by harryyu1994** [comment] 2020-03-17 16:14
@mpirvu 25/25 grinder passed with latest. (Original failure rate is around 3/5). We can close this one.

**Comment by mpirvu** [comment] 2020-03-17 17:09
Supposedly fixed by https://github.com/eclipse/openj9/pull/8811

**Closed by mpirvu** 2020-03-17 17:09 UTC
Labels: comp:jitserver, test failure
