### ISSUE TITLE
JTReg test fail - Linux PPC64LE : java/lang/String/Exceptions.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4122] opened 2018-12-19 20:49 UTC
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/String/Exceptions.java intermittently fails on Linux PPC64LE.
When it fails it coredumps with errors like this ...

```
XML output with verification to /home/jenkins/workspace/SXA-Grinder/jvmtest/openjdk_regression/work
[2018-12-18 17:10:29,572] Agent[0]: stderr: Unhandled exception
[2018-12-18 17:10:29,572] Agent[0]: stderr: Type=Segmentation error vmState=0x00000000
[2018-12-18 17:10:29,572] Agent[0]: stderr: J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
[2018-12-18 17:10:29,573] Agent[0]: stderr: Handler1=00003FFF7913B9B0 Handler2=00003FFF78FBD700
[2018-12-18 17:10:29,573] Agent[0]: stderr: R0=000000000000006F R1=00003FFF594BB430 R2=0000000000000000 R3=000000000000000A
[2018-12-18 17:10:29,573] Agent[0]: stderr: R4=0000000000000001 R5=0000000000000000 R6=0000000000000001 R7=0000000000000001
[2018-12-18 17:10:29,573] Agent[0]: stderr: R8=00003FFF73FF2B10 R9=000000000000000E R10=0000000000525400 R11=0000000000520EA8
[2018-12-18 17:10:29,573] Agent[0]: stderr: R12=0000000028004422 R13=00003FFF594C6900 R14=0000000000525350 R15=000000000051F300
[2018-12-18 17:10:29,574] Agent[0]: stderr: R16=00003FFF59950038 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=0000000000000000
[2018-12-18 17:10:29,574] Agent[0]: stderr: R20=00003FFF594BB6E0 R21=0000000000000000 R22=00000000FFD4A2F0 R23=0000000000000000
[2018-12-18 17:10:29,574] Agent[0]: stderr: R24=00000000FFD4A4B0 R25=00000000FFD6BB30 R26=0000000000000001 R27=00000000E063DC88
[2018-12-18 17:10:29,574] Agent[0]: stderr: R28=0000000000000001 R29=0000000000000000 R30=0000000000000001 R31=0000000000000001
[2018-12-18 17:10:29,575] Agent[0]: stderr: NIP=00003FFF5B571B28 MSR=800000000280F033 ORIG_GPR3=00003FFF7921E7D8 CTR=00003FFF5B571A6C
[2018-12-18 17:10:29,575] Agent[0]: stderr: LINK=00003FFF5B571B0C XER=0000000000000000 CCR=0000000048004424 SOFTE=0000000000000001
[2018-12-18 17:10:29,575] Agent[0]: stderr: TRAP=0000000000000300 DAR=000000000000000A dsisr=0000000042000000 RESULT=0000000000000000
[2018-12-18 17:10:29,575] Agent[0]: stderr: FPR0 0000000000525440 (f: 5395520.000000, d: 2.665741e-317)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR1 4051c39ec8349899 (f: 3358890240.000000, d: 7.105657e+01)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR3 3c50000000000000 (f: 0.000000, d: 3.469447e-18)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR4 402a56ef8ec92280 (f: 2395546112.000000, d: 1.316980e+01)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR5 3fe9d18be0000000 (f: 3758096384.000000, d: 8.068294e-01)
[2018-12-18 17:10:29,576] Agent[0]: stderr: FPR6 4119d18000000000 (f: 0.000000, d: 4.230080e+05)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR7 3d2ef35793c76730 (f: 2479318784.000000, d: 5.497923e-14)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR8 006100760061006a (f: 6357098.000000, d: 7.566052e-307)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR9 006e0061006c002e (f: 7077934.000000, d: 1.335110e-306)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR10 3ff3d4a96f20bf31 (f: 1864417024.000000, d: 1.239419e+00)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR11 bedd6fb245f1d1f7 (f: 1173475840.000000, d: -7.018164e-06)
[2018-12-18 17:10:29,577] Agent[0]: stderr: FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,578] Agent[0]: stderr: FPR13 4029e909dd6ce7ac (f: 3714902016.000000, d: 1.295515e+01)
[2018-12-18 17:10:29,578] Agent[0]: stderr: FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,578] Agent[0]: stderr: FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,578] Agent[0]: stderr: FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,578] Agent[0]: stderr: FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,580] Agent[0]: stderr: FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,580] Agent[0]: stderr: FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,581] Agent[0]: stderr: FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,582] Agent[0]: stderr: FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,582] Agent[0]: stderr: FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,582] Agent[0]: stderr: FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,582] Agent[0]: stderr: FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,584] Agent[0]: stderr: FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,585] Agent[0]: stderr: FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,585] Agent[0]: stderr: FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,585] Agent[0]: stderr: FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,585] Agent[0]: stderr: FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,585] Agent[0]: stderr: FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,586] Agent[0]: stderr: FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
[2018-12-18 17:10:29,586] Agent[0]: stderr: 
[2018-12-18 17:10:29,586] Agent[0]: stderr: Compiled_method=java/lang/String.decompressedArrayCopy([BI[CII)V
[2018-12-18 17:10:29,586] Agent[0]: stderr: Target=2_90_20181116_21 (Linux 4.4.0-140-generic)
[2018-12-18 17:10:29,586] Agent[0]: stderr: CPU=ppc64le (4 logical CPUs) (0x1fe3b0000 RAM)
[2018-12-18 17:10:29,587] Agent[0]: stderr: ----------- Stack Backtrace -----------
[2018-12-18 17:10:29,587] Agent[0]: stderr: (0x00003FFF5B571B28 [<unknown>+0x0])
[2018-12-18 17:10:29,587] Agent[0]: stderr: (0x00003FFF7916E28C [libj9vm29.so+0xde28c])
[2018-12-18 17:10:29,587] Agent[0]: stderr: (0x00003FFF79124C2C [libj9vm29.so+0x94c2c])
[2018-12-18 17:10:29,587] Agent[0]: stderr: (0x00003FFF79125F18 [libj9vm29.so+0x95f18])
[2018-12-18 17:10:29,588] Agent[0]: stderr: (0x00003FFF782ADB68 [libjclse11_29.so+0x6db68])
[2018-12-18 17:10:29,588] Agent[0]: stderr: JVM_InvokeMethod+0x40 (0x00003FFF792DA2C0 [libjvm.so+0x2a2c0])
[2018-12-18 17:10:29,588] Agent[0]: stderr: JVM_InvokeMethod+0x34 (0x00003FFF79C36604 [libjvm.so+0x6604])
[2018-12-18 17:10:29,588] Agent[0]: stderr: Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00003FFF595CC9E4 [libjava.so+0xc9e4])
[2018-12-18 17:10:29,588] Agent[0]: stderr: (0x00003FFF5B344AA4 [<unknown>+0x0])
[2018-12-18 17:10:29,589] Agent[0]: stderr: (0x00003FFF79120244 [libj9vm29.so+0x90244])
[2018-12-18 17:10:29,589] Agent[0]: stderr: (0x00003FFF7918F8C0 [libj9vm29.so+0xff8c0])
[2018-12-18 17:10:29,589] Agent[0]: stderr: (0x00003FFF78FBEC54 [libj9prt29.so+0x2ec54])
[2018-12-18 17:10:29,589] Agent[0]: stderr: (0x00003FFF7918ADD4 [libj9vm29.so+0xfadd4])
[2018-12-18 17:10:29,589] Agent[0]: stderr: (0x00003FFF79060CC8 [libj9thr29.so+0x10cc8])
[2018-12-18 17:10:29,590] Agent[0]: stderr: (0x00003FFF79EB8070 [libpthread.so.0+0x8070])
[2018-12-18 17:10:29,590] Agent[0]: stderr: clone+0x98 (0x00003FFF79D93A70 [libc.so.6+0x123a70])
[2018-12-18 17:10:29,590] Agent[0]: stderr: ---------------------------------------
```

A 26% failure rate was observed with job https://ci.adoptopenjdk.net/view/work in progress/job/SXA-Grinder/10. The coredump files generated have been obtained and are available here - https://ibm.box.com/s/wpmr1klbml2p2z4slctyw9ai7kgrcpb3.

No such problem observed on other platforms.

**Comment by DanHeidinga** [comment] 2018-12-20 14:43
@gita-omr FYI linux ppc jit crash

**Comment by gita-omr** [comment] 2018-12-20 17:49
@DanHeidinga , the link to the Grinder job above is not working.

**Comment by DanHeidinga** [comment] 2018-12-20 18:01
@gita-omr where you able to download the cores and the test source?  That should be sufficient to start investigating.

@ben-walsh Can you update the description with the correct grinder link?

**Comment by gita-omr** [comment] 2018-12-20 18:08
We definitely need the test case in order to narrow down JIT component.

**Comment by gita-omr** [comment] 2018-12-20 18:45
@ben-walsh please see comment above.

**Comment by gita-omr** [comment] 2018-12-20 18:49
@DanHeidinga @ben-walsh : looking at the core files is not always productive. What we usually do-  we try to narrow down JIT component by using JIT options, in exactly the same environment the test case was running in. We of course can try other ways, but since the defect is really urgent, we would appreciate as much info as possible.

**Comment by ben-walsh** [comment] 2018-12-20 20:44
The link to the job is correct but it's the spaces in the URL causing the problem, so use https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/10.
I've kicked off a rebuild with "-Xint" value for JVM_OPTIONS - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/16.

**Comment by gita-omr** [comment] 2018-12-20 20:58
Great, thanks! It that does not fail, I think next thing to try would be -Xjit:limit={java/lang/String.decompressedArrayCopy([BI[CII)V} 
@R-santhir

**Comment by gita-omr** [comment] 2018-12-21 14:13
@ben-walsh also started builds:
with tracing the method:
[https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/18/](url)
with verbose:
[https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/25/](url)

**Comment by gita-omr** [comment] 2018-12-21 16:00
Fails each time with this build:
[https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder/27/](url)

**Comment by R-Santhir** [comment] 2018-12-28 17:07
Having taken a look at the tracefile, it would be helpful to have a core from the run that generated the tracefile. @ben-walsh can you please kick off a run that will save generated cores with the following options:

`-Xjit:limit={java/lang/String.decompressedArrayCopy([BI[CII)V},{java/lang/String.decompressedArrayCopy([BI[CII)V}(traceFull,count=1),log=test.trc,verbose`

The grinder's do not seem to save cores by default.

I also tried to locally reproduce the failure with @smlambert 's help, but was not able to due to a known issue. I will keep trying in parallel with some suggestions @smlambert made.

**Comment by R-Santhir** [comment] 2019-01-06 20:56
Here's a summary of my investigation so far, as mentioned by Gita the failure occurs even with **noopt** :

The cause of the failure is the following store:
`sthx    [gr3, gr0], gr2`

At the point of failure, gr0 is 0 and gr3 is a small value, so a store is done to what is essentially a NULL address, which I believe is what the test itself is trying to do. The problem is that what was originally a NULL check and a call to a JIT helper was turned into a only a store.

```
n28n      NULLCHK on n14n [#30]                                                               [    0x7fffb8e864a0] bci=[-1,29,339] rc=0 vc=0 vn=- li=- udi=- nc=1
n27n        call  com/ibm/jit/JITHelpers.putCharInArrayByIndex(Ljava/lang/Object;IC)V[#633  final virtual Method -520] [flags 0x20500 0x0 ] ()  [    0x7fffb8e86450] bci=[-1,29,339] rc=1 vc=0 vn=- li=- udi=- nc=4 flg=0x20
n14n          ==>aload
```

This is done by unsafeFastPath:
```
<optimization id=2 name=unsafeFastPath method=java/lang/String.decompressedArrayCopy([BI[CII)V>
Performing 2: unsafeFastPath
[     1] O^O UNSAFE FAST PATH:  Found unsafe/JITHelpers calls, turning node [00007FFFB8E86360] into a load/store
[     2] O^O UNSAFE FAST PATH:  Found unsafe/JITHelpers calls, turning node [00007FFFB8E86450] into a load/store
<trees
```

So there are two things that are happening here that I need some clarification on, firstly unsafeFastPath is happening even with no-opt, and the NULL check is being removed on what is definitely a NULL address. If @andrewcraik could provide some explanation on why this is happening and how this should be remedied that would be much appreciated.

I've attached the tracefile I used for investigation.

[test.trc.139794.21063.20190105.154423.139794.txt](https://github.com/eclipse/openj9/files/2730850/test.trc.139794.21063.20190105.154423.139794.txt)

**Comment by ben-walsh** [comment] 2019-01-07 14:22
@R-Santhir

Correct, the job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder does not save any generated cores nor any files from the workspace. The job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-Grinder which did, has been recreated as https://ci.adoptopenjdk.net/view/work in progress/job/SXA-BenWalsh-Grinder, following an unintentional removal while I was away.

Per https://github.com/eclipse/openj9/issues/4122#issuecomment-450393013, I have kicked off a rebuild with the requested JVM opts - https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-BenWalsh-Grinder/4.

**Comment by andrewcraik** [comment] 2019-01-07 14:53
@R-Santhir in response to the two issues above - unsafeFastPath is supposed to happen even at noOpt because it is an ilgen opt - noOpt does not mean no optimization it means minimal optimization. So the decompressed array copy will be copying the contents of one array to another and it should not be possible for the array being passed in to be null - hence why the NULLCHK is ripped out. Can you provide details of the test itself and how we got a null array in the first place since that shouldn't be possible if the Java is implemented correctly.

**Comment by R-Santhir** [comment] 2019-01-07 15:19
Thanks for the explanation @andrewcraik. Here's the failing method:

`        private static void getChars() {
        System.out.println("getChars.(int srcBegin, int srcEnd, char dst[], "
                           + " int dstBegin");
        tryCatch("  null", NullPointerException.class, new Runnable() {
                public void run() {
                    "foo".getChars(1, 2, null, 1);
                }});
    }`

I believe that getChars is producing the decompressedArrayCopy, which would explain the failure.

**Comment by andrewcraik** [comment] 2019-01-07 15:52
@liqunl looks like we are not preserving a NULLCHK when doing the transform at https://github.com/eclipse/openj9/blob/43d93bde6571c89e8d2e95fa0072e0382507ecb4/runtime/compiler/optimizer/UnsafeFastPath.cpp#L686
Now I suspect we should keep the NULLCHK - looks a bit like one you fixed recently, but we need to check the perf implications.

**Comment by liqunl** [comment] 2019-01-08 16:02
This is not caused or exposed by any recent change. The fast path for jit helpers was added as part of String compression. This bug has existed since then. 

UnsafeFastPath was initially an opt to only optimize calls to Unsafe APIs made from several recognized methods where the Object passed to Unsafe is always valid, so we don't generate NULLCHK for the load/store. The original NULLCHK is on the Unsafe object, not on the argument of the call. Thus, there shouldn't be any problem removing that NULLCHK.

Currently, we use the same transformation to optimize jit helpers, which does not emit a NULLCHK. 

There's another bug I found by reading the code. The fast path doesn't check for endianness. If we were to check that in UnsafeFastPath, the opt would be too different from what we have now.

Since the jit helpers are basically doing something very similar to Unsafe, I think we should use Unsafe to implement these jit helpers, and let the jit helpers be inlined such that the Unsafe calls can be fast pathed. The jit helpers can do an explicit null check. Maintaining variations of an opt is defect prone.

**Comment by liqunl** [comment] 2019-01-08 16:13
Since the jit helpers are only used for String, I'm proposing overloading the jit helpers to take `char[]` or `byte[]` as argument. The following are examples for get APIs, same for put APIs.
```
public static final long CHAR_ARRAY_BASE_OFFSET = unsafe.arrayBaseOffset(char[].class);
public static final long BYTE_ARRAY_BASE_OFFSET = unsafe.arrayBaseOffset(byte[].class);

public char getCharFromArrayByIndex(char[] obj, int index) {
	return obj[index];
}

public char getCharFromArrayByIndex(byte[] obj, int index) {
	// Explicit null check
	obj.getClass();
	if (IS_PLATFORM_LITTLE_ENDIAN) {
		return unsafe.getChar(obj, BYTE_ARRAY_BASE_OFFSET + (long)index << 2);
	}
	else {
		return Character.reverseBytes(unsafe.getChar(obj, BYTE_ARRAY_BASE_OFFSET + (long)index << 2));
	}
}

public byte getByteFromArrayByIndex(byte[] obj, int index) {
	return obj[index];
}

public byte getByteFromArrayByIndex(char[] obj, int index) {
	// Explicit null check
	obj.getClass();
	if (IS_PLATFORM_LITTLE_ENDIAN) {
		return unsafe.getByte(obj, CHAR_ARRAY_BASE_OFFSET + index);
	}
	else {
		// Flip the last bit of index to get the right index of the desired byte
		return return unsafe.getByte(obj, CHAR_ARRAY_BASE_OFFSET + index^1);
	}
}
```
With this implementation, we can just inline the jit helpers and let the Unsafe opt handle Unsafe calls instead of special case jit helpers.

**Comment by liqunl** [comment] 2019-01-08 16:13
@andrewcraik @fjeremic Please give your thoughts to comments above.

**Comment by R-Santhir** [comment] 2019-01-08 16:21
@gita-omr requested the command line arguments to build and run the failing test:

```jdk-11.0.1+13/bin/javac openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/String/Exceptions.java```

```jdk-11.0.1+13/bin/java openjdk-tests/openjdk_regression/openjdk-jdk/test/jdk/java/lang/String/Exceptions```

**Comment by andrewcraik** [comment] 2019-01-08 17:50
We do not want to rely on the inliner handling the Unsafes and I don't want the inliner to have to inline these JITHelpers because that will introduce massive scope for performance problems. It would be easier to just fix the helper and that could be done just by exposing the endianness in the J9VMInternals if it isn't already there. As a result, I would rather the current helper is fixed with the appropriate recognition.

**Comment by andrewcraik** [comment] 2019-01-08 18:03
I believe that @fjeremic already looked at endianness when building this implementation so I would be surprised if it was fundamentally broken. I'll leave him to comment on that. For this bug can we just get an appropriate NULLCHK to be generated for the argument so that NPE is thrown and we can carry on? Adding a getClass or something the Java code and a NULLCHK in the trees?

**Comment by liqunl** [comment] 2019-01-08 19:19
@andrewcraik If we want to optimize the jit helpers without inlining them, the explicit null check should be added to the jit helpers's callers. Unfortunately, there are a lot of them. I don't think we want to add explicit null check in all methods. We may better add explicit null checks in public APIs. For this one, it's `String.getChars`.
We can also generate a null check in the trees, but that is likely to have a performance impact.

**Comment by liqunl** [comment] 2019-01-08 19:34
@andrewcraik Looking at the implementation of `String.getChars` more closely, I found another problem. The condition to throw StringIndexOutOfBoundsException is incomplete. The condition for `index` is missing. Missing of a check in the caller should not be the reason that the internal API should do the check. Thus, I think the null check and other checks are the job of public APIs. 
[Conditions needed in the doc](https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/String.java#L1827)
[Conditions in the code](https://github.com/eclipse/openj9/blob/master/jcl/src/java.base/share/classes/java/lang/String.java#L1833)

**Comment by liqunl** [comment] 2019-01-08 19:38
@andrewcraik It'll take time to find out because some public APIs has implicit checks. Most public APIs have the right checks. For this issue, I think we should blame the implementation of `getChars` for the missing NPE.

**Comment by andrewcraik** [comment] 2019-01-08 19:40
yup so we can add the getClass or whatever for the getChars to have the right check and a follow-up of any others that are missing can be done IMO.

**Comment by liqunl** [comment] 2019-01-09 14:42
For getChars that takes a char array, the following if statement will give us the missing checks.
```
public void getChars(int start, int end, char[] data, int index) {
        if (0 <= start && start <= end && end <= lengthInternal() && 0 <= index && end - start <= data.length - index) {
```
But I don't know what kind of checks we should do for getChars that takes a byte array. Is `index` in byte or in char? @fjeremic @andrewcraik 
```
void getChars(int start, int end, byte[] data, int index) {
```

**Comment by andrewcraik** [comment] 2019-01-09 15:13
so looking at the implementation the start and end are in terms of characters - all indexes, offsets etc are in terms of chars - how that maps to the byte array depends on the compression of the string. I think the bound checks are fine - we should just add a data.getClass() to do the NULLCHK. You should do a functional test with a null array and bad bounds to see if the Oracle implementation throws the out of bounds exception or the NullPointerException (I suspect they may throw the bad bounds). The result of that test will determine if the getClass is done before or after the if checking the boundaries.

**Closed** 2019-01-17 14:06 UTC
Labels: comp:jit, test excluded, test failure

**Comment by gita-omr** [comment] 2019-02-01 15:01
@smlambert just wanted to mention that we need to re-enable the test case since this ended up being a legitimate problem.

**Comment by ben-walsh** [comment] 2019-02-04 10:40
PR to re-enable relevant test - https://github.com/AdoptOpenJDK/openjdk-tests/pull/846
