### ISSUE TITLE
DaaLoadTest_daa1_CS_5m_0 crash vmState=0x00020002

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#11846] opened 2021-02-01 20:07 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_ppc64_aix_xl_Nightly/55
DaaLoadTest_daa1_CS_5m_0
```
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00020002
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
DLT stderr Handler1=09001000A1252520 Handler2=09001000A121B838
DLT stderr R0=0A00000000000000 R1=00000100223F1D50 R2=09001000A12A5248 R3=00000100101793F0
DLT stderr R4=0000000000000018 R5=0004000000000000 R6=0000000000000009 R7=0000000000000032
DLT stderr R8=0000000000000125 R9=0000000000000125 R10=0000000000000003 R11=0000000000000000
DLT stderr R12=0000000000000000 R13=00000100223FA800 R14=0000000000000000 R15=0000000000000000
DLT stderr R16=0000000000000000 R17=0000000000000000 R18=0000000000000000 R19=0000000000000000
DLT stderr R20=0000000000000001 R21=0000000000000001 R22=0073000000000000 R23=0000000000000070
DLT stderr R24=0000000000000060 R25=0000000000000002 R26=00000100106928B0 R27=0000000000000001
DLT stderr R28=0000000000000000 R29=00000100106927D0 R30=00000100223F8CB8 R31=00000100223F1F30
DLT stderr IAR=0900000013F7AB14 LR=0900000013F7ABC0 MSR=A00000000000D032 CTR=0900000013FB6B00
DLT stderr CR=2400024800000000 FPSCR=8202000000000000 XER=0000000082020000
DLT stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
DLT stderr FPR2 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
DLT stderr FPR3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR5 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
DLT stderr FPR6 4070b1f20d4afc0c (f: 223018000.000000, d: 2.671216e+02)
DLT stderr FPR7 408f400000000000 (f: 0.000000, d: 1.000000e+03)
DLT stderr FPR8 4112d6ec00000000 (f: 0.000000, d: 3.086670e+05)
DLT stderr FPR9 4530000000000000 (f: 0.000000, d: 1.934281e+25)
DLT stderr FPR10 408f400000000000 (f: 0.000000, d: 1.000000e+03)
DLT stderr FPR11 43300000000003e8 (f: 1000.000000, d: 4.503600e+15)
DLT stderr FPR12 4530000000000000 (f: 0.000000, d: 1.934281e+25)
DLT stderr FPR13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.system_ppc64_aix_xl_Nightly_testList_1/openjdkbinary/j2sdk-image/jre/lib/ppc64/default/libj9gc29.so
DLT stderr Module_base_address=0900000013EA9000
DLT stderr Target=2_90_20210131_56 (AIX 7.1)
DLT stderr CPU=ppc64 (16 logical CPUs) (0x200000000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr scanClearable__14MM_RootScannerFP18MM_EnvironmentBase+0x248 (0x0900000013F6B00C [libj9gc29.so+0xc200c])
DLT stderr workerCompleteGC__18MM_MarkingDelegateFP18MM_EnvironmentBase+0x1a0 (0x0900000013F62A04 [libj9gc29.so+0xb9a04])
DLT stderr markLiveObjectsComplete__16MM_MarkingSchemeFP18MM_EnvironmentBase+0x10 (0x0900000013F5AD74 [libj9gc29.so+0xb1d74])
DLT stderr run__19MM_ParallelMarkTaskFP18MM_EnvironmentBase+0x6c (0x090000001408B8D0 [libj9gc29.so+0x1e28d0])
DLT stderr workerEntryPoint__21MM_ParallelDispatcherFP18MM_EnvironmentBase+0x22c (0x090000001401B330 [libj9gc29.so+0x172330])
DLT stderr dispatcher_thread_proc2__FP14OMRPortLibraryPv+0x27c (0x090000001401A480 [libj9gc29.so+0x171480])
DLT stderr omrsig_protect+0x488 (0x090000001291FCCC [libj9prt29.so+0x59ccc])
DLT stderr dispatcher_thread_proc+0x4c (0x090000001401B0B0 [libj9gc29.so+0x1720b0])
DLT stderr thread_wrapper+0x524 (0x09000000128A6968 [libj9thr29.so+0x4968])
DLT stderr _pthread_body+0xf0 (0x0900000000570E14 [libpthreads.a+0x3e14])
```

**Comment by pshipton** [comment] 2021-02-01 20:07
@dmitripivkine

**Comment by dmitripivkine** [comment] 2021-02-02 18:58
this is crash stack:
```
mainSynchSignalHandler(??, ??, ??) at 0x9000000129227b0
scanOwnableSynchronizerObjects__27MM_MarkingSchemeRootClearerFP18MM_EnvironmentBase(??, ??) at 0x900000013f7ab14
scanClearable__14MM_RootScannerFP18MM_EnvironmentBase(??, ??) at 0x900000013f6b008
workerCompleteGC__18MM_MarkingDelegateFP18MM_EnvironmentBase(??, ??) at 0x900000013f62a00
markLiveObjectsComplete__16MM_MarkingSchemeFP18MM_EnvironmentBase(??, ??) at 0x900000013f5ad70
run__19MM_ParallelMarkTaskFP18MM_EnvironmentBase(??, ??) at 0x90000001408b8cc
workerEntryPoint__21MM_ParallelDispatcherFP18MM_EnvironmentBase(??, ??) at 0x90000001401b32c
dispatcher_thread_proc2__FP14OMRPortLibraryPv(??, ??) at 0x90000001401a47c
omrsig_protect(??, ??, ??, ??, ??, ??, ??) at 0x90000001291fcc8
dispatcher_thread_proc(??) at 0x90000001401b0ac
thread_wrapper(??) at 0x9000000128a6964
```

The problem occur in `scanOwnableSynchronizerObjects()`, this is duplicate of https://github.com/eclipse/openj9/issues/10489

**Closed by dmitripivkine** 2021-02-02 18:58 UTC
Labels: comp:gc, segfault, test failure
