### ISSUE TITLE
JDK11 : jdk/internal/loader/ClassLoaderValue/ClassLoaderValueTest.java - Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10712] opened 2020-09-26 16:26 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/182/consoleFull
```
01:29:04  openjdk version "11.0.9-internal" 2020-10-20
01:29:04  OpenJDK Runtime Environment (build 11.0.9-internal+0-adhoc.****.BuildJDK11x86-64linuxNightly)
01:29:04  Eclipse OpenJ9 VM (build master-d6380006236, JRE 11 Linux amd64-64-Bit Compressed References 20200924_510 (JIT enabled, AOT enabled)
01:29:04  OpenJ9   - d6380006236
01:29:04  OMR      - 79c250b8851
01:29:04  JCL      - 77c6759fc47 based on jdk-11.0.9+8)
```
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
02:44:12  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
02:04:25  --------------------------------------------------
02:04:25  TEST: jdk/internal/loader/ClassLoaderValue/ClassLoaderValueTest.java
02:04:25  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image
02:04:25  
02:04:25  stderr:
02:04:25  Unhandled exception
02:04:25  Type=Segmentation error vmState=0x00000000
02:04:25  Unhandled exception
02:04:25  Type=Segmentation error vmState=0x00000000
02:04:25  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
02:04:25  Handler1=00007F96B9BCB950 Handler2=00007F96B9935920 InaccessibleAddress=0000000000000010
02:04:25  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
02:04:25  Handler1=00007F96B9BCB950 Handler2=00007F96B9935920 InaccessibleAddress=0000000000000010
02:04:25  RDI=0000000000366A00 RSI=000000000000000C RAX=00007F96B4025B30 RBX=0000000000000000
02:04:25  RCX=0000000000000000 RDX=000000000000000C R8=0000000000000000 R9=0000000000000498
02:04:25  R10=000000000016FF00 R11=00007F96B9BC9CB0 R12=00007F9661707396 R13=0000000000000000
02:04:25  R14=0000000000366A00 R15=00007F9679854A30
02:04:25  RDI=0000000000362E00 RSI=000000000000000C RAX=00007F96B4025B30 RBX=0000000000000000
02:04:25  RCX=0000000000000000 RDX=000000000000000C R8=0000000000000000 R9=0000000000000498
02:04:25  R10=000000000016FF00 R11=00007F96B9BC9CB0 R12=00007F9661707396 R13=0000000000000000
02:04:25  R14=0000000000362E00 R15=00007F96798D6A30
02:04:25  RIP=00007F96B9C13B77 GS=0000 FS=0000 RSP=00007F96798546B0
02:04:25  EFlags=0000000000010246 CS=0033 RBP=00007F96B9CF0C18 ERR=0000000000000004
02:04:25  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000010
02:04:25  RIP=00007F96B9C13B77 GS=0000 FS=0000 RSP=00007F96798D66B0
02:04:25  EFlags=0000000000010246 CS=0033 RBP=00007F96B9CF0C18 ERR=0000000000000004
02:04:25  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000010
02:04:25  xmm0 0000000000290ef0 (f: 2690800.000000, d: 1.329432e-317)
02:04:25  xmm1 00000000e020a318 (f: 3760235264.000000, d: 1.857803e-314)
02:04:25  xmm2 00007f9679854a60 (f: 2038778496.000000, d: 6.930963e-310)
02:04:25  xmm3 00007f9679854a60 (f: 2038778496.000000, d: 6.930963e-310)
02:04:25  xmm4 00007f9679854a60 (f: 2038778496.000000, d: 6.930963e-310)
02:04:25  xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm6 000000004187e2a8 (f: 1099424384.000000, d: 5.431878e-315)
02:04:25  xmm7 000000003cc5d56a (f: 1019598208.000000, d: 5.037484e-315)
02:04:25  xmm8 696d6f74612f746e (f: 1630499968.000000, d: 7.041037e+199)
02:04:25  xmm9 3b6e61656c6f6f42 (f: 1819242368.000000, d: 2.010410e-22)
02:04:25  xmm10 000000003e8c05e2 (f: 1049363968.000000, d: 5.184547e-315)
02:04:25  xmm11 000000003c075284 (f: 1007112832.000000, d: 4.975799e-315)
02:04:25  xmm12 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
02:04:25  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm0 0000000000290e10 (f: 2690576.000000, d: 1.329321e-317)
02:04:25  xmm1 00000000e020a318 (f: 3760235264.000000, d: 1.857803e-314)
02:04:25  xmm2 00007f96798d6a60 (f: 2039310976.000000, d: 6.930963e-310)
02:04:25  xmm3 00007f96798d6a60 (f: 2039310976.000000, d: 6.930963e-310)
02:04:25  xmm4 00007f96798d6a60 (f: 2039310976.000000, d: 6.930963e-310)
02:04:25  xmm5 00000000395a743c (f: 962229312.000000, d: 4.754044e-315)
02:04:25  xmm6 0000000041823ebf (f: 1099054720.000000, d: 5.430052e-315)
02:04:25  xmm7 00000000be61c060 (f: 3194077184.000000, d: 1.578084e-314)
02:04:25  xmm8 696d6f74612f746e (f: 1630499968.000000, d: 7.041037e+199)
02:04:25  xmm9 3b6e61656c6f6f42 (f: 1819242368.000000, d: 2.010410e-22)
02:04:25  xmm10 000000003e8c05e2 (f: 1049363968.000000, d: 5.184547e-315)
02:04:25  xmm11 000000003c075284 (f: 1007112832.000000, d: 4.975799e-315)
02:04:25  xmm12 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
02:04:25  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
02:04:25  Module_base_address=00007F96B9B97000
02:04:25  Target=2_90_20200924_510 (Linux 4.4.0-169-generic)
02:04:25  CPU=amd64 (4 logical CPUs) (0x5e2f07000 RAM)
02:04:25  ----------- Stack Backtrace -----------
02:04:25  (0x00007F96B9C13B77 [libj9vm29.so+0x7cb77])
02:04:25  (0x00007F96B9C13080 [libj9vm29.so+0x7c080])
02:04:25  (0x00007F96B9C69732 [libj9vm29.so+0xd2732])
02:04:25  ---------------------------------------
02:04:25  JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/25 03:03:52 - please wait.
02:04:25  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
02:04:25  Module_base_address=00007F96B9B97000
02:04:25  Target=2_90_20200924_510 (Linux 4.4.0-169-generic)
02:04:25  CPU=amd64 (4 logical CPUs) (0x5e2f07000 RAM)
02:04:25  ----------- Stack Backtrace -----------
02:04:25  (0x00007F96B9C13B77 [libj9vm29.so+0x7cb77])
02:04:25  (0x00007F96B9C13080 [libj9vm29.so+0x7c080])
02:04:25  (0x00007F96B9C69732 [libj9vm29.so+0xd2732])
02:04:25  ---------------------------------------
02:04:25  JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/25 03:03:52 - please wait.
02:04:25  Unhandled exception
02:04:25  Type=Segmentation error vmState=0x00000000
02:04:25  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
02:04:25  Handler1=00007F96B9BCB950 Handler2=00007F96B9935920 InaccessibleAddress=0000000000000010
02:04:25  RDI=000000000035B600 RSI=000000000000000C RAX=00007F96B4025B30 RBX=0000000000000000
02:04:25  RCX=0000000000000000 RDX=000000000000000C R8=0000000000000000 R9=0000000000000498
02:04:25  R10=000000000016FF00 R11=00007F96B9BC9CB0 R12=00007F9661707396 R13=0000000000000000
02:04:25  R14=000000000035B600 R15=00007F9679791A30
02:04:25  RIP=00007F96B9C13B77 GS=0000 FS=0000 RSP=00007F96797916B0
02:04:25  EFlags=0000000000010246 CS=0033 RBP=00007F96B9CF0C18 ERR=0000000000000004
02:04:25  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=0000000000000010
02:04:25  xmm0 0000000000290ef0 (f: 2690800.000000, d: 1.329432e-317)
02:04:25  xmm1 00000000e020a318 (f: 3760235264.000000, d: 1.857803e-314)
02:04:25  xmm2 00007f9679791a60 (f: 2037979776.000000, d: 6.930963e-310)
02:04:25  xmm3 00007f9679791a60 (f: 2037979776.000000, d: 6.930963e-310)
02:04:25  xmm4 00007f9679791a60 (f: 2037979776.000000, d: 6.930963e-310)
02:04:25  xmm5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm8 696d6f74612f746e (f: 1630499968.000000, d: 7.041037e+199)
02:04:25  xmm9 3b6e61656c6f6f42 (f: 1819242368.000000, d: 2.010410e-22)
02:04:25  xmm10 000000003e8c05e2 (f: 1049363968.000000, d: 5.184547e-315)
02:04:25  xmm11 000000003c075284 (f: 1007112832.000000, d: 4.975799e-315)
02:04:25  xmm12 0000000040400000 (f: 1077936128.000000, d: 5.325712e-315)
02:04:25  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
02:04:25  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
02:04:25  Module_base_address=00007F96B9B97000
02:04:25  Target=2_90_20200924_510 (Linux 4.4.0-169-generic)
02:04:25  CPU=amd64 (4 logical CPUs) (0x5e2f07000 RAM)
02:04:25  ----------- Stack Backtrace -----------
02:04:25  (0x00007F96B9C13B77 [libj9vm29.so+0x7cb77])
02:04:25  (0x00007F96B9C13080 [libj9vm29.so+0x7c080])
02:04:25  (0x00007F96B9C69732 [libj9vm29.so+0xd2732])
02:04:25  ---------------------------------------
02:04:25  JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/25 03:03:52 - please wait.
02:04:25  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/core.20200925.030352.18884.0001.dmp' in response to an event
02:04:25  JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.23601.
02:04:25  
02:04:25  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/core.20200925.030352.18884.0001.dmp
02:04:25  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/javacore.20200925.030352.18884.0004.txt' in response to an event
02:04:25  JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/core.20200925.030352.18884.0002.dmp' in response to an event
02:04:25  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/javacore.20200925.030352.18884.0004.txt
02:04:25  JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.23659.
02:04:25  
02:04:25  JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/core.20200925.030352.18884.0002.dmp
02:04:25  JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/javacore.20200925.030352.18884.0006.txt' in response to an event
02:04:25  JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/Snap.20200925.030352.18884.0005.trc' in response to an event
02:04:25  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/Snap.20200925.030352.18884.0005.trc
02:04:25  JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/jitdump.20200925.030352.18884.0007.dmp' in response to an event
02:04:25  JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/javacore.20200925.030352.18884.0006.txt
02:04:25  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work/scratch/1/jitdump.20200925.030352.18884.0007.dmp
02:04:25  JVMDUMP013I Processed dump event "gpf", detail "".
02:04:25  
02:04:25  TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details
02:04:25  --------------------------------------------------
02:06:03  Test results: passed: 723; error: 1
02:06:13  Report written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/jvmtest/openjdk/report/html/report.html
02:06:13  Results written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_Nightly/openjdk-tests/TKG/test_output_16010125183871/jdk_lang_j9_0/work
02:06:13  Error: Some tests failed or other problems occurred.
02:06:13  
02:06:13  jdk_lang_j9_0_FAILED
```

**Comment by DanHeidinga** [comment] 2020-09-28 13:14
@JasonFengJ9 this looks like a duplicate of https://github.com/eclipse/openj9/issues/10707

**Closed by DanHeidinga** 2020-09-28 13:14 UTC
Labels: test failure
