### ISSUE TITLE
openjdk plinux/AIX abort creating jitdump

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10706] opened 2020-09-25 20:03 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/157
jdk/test/sun/misc/CopyMemory.java
ub18-ppcle-1
```
23:16:56  elapsed time (seconds): 82.721
23:16:56  configuration:
23:16:56  Boot Layer
23:16:56    class path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdkbinary/j2sdk-image/lib/tools.jar
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/junit.jar
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar
23:16:56  
23:16:56  Test Layer
23:16:56    class path: /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/classes/2/sun/misc
23:16:56                /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc
23:16:56  
23:16:56  rerun:
23:16:56  cd /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/scratch/2 && \
23:16:56  DISPLAY=:0 \
23:16:56  HOME=/home/jenkins \
23:16:56  LANG=en_CA.UTF-8 \
23:16:56  PATH=/bin:/usr/bin:/usr/sbin \
23:16:56      /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdkbinary/j2sdk-image/bin/java \
23:16:56          -Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache -XX:-JITServerTechPreviewMessage' \
23:16:56          -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache -J-XX:-JITServerTechPreviewMessage' \
23:16:56          -Dtest.compiler.opts= \
23:16:56          -Dtest.java.opts= \
23:16:56          -Dtest.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdkbinary/j2sdk-image \
23:16:56          -Dcompile.jdk=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdkbinary/j2sdk-image \
23:16:56          -Dtest.timeout.factor=8.0 \
23:16:56          -Dtest.root=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test \
23:16:56          -Dtest.name=sun/misc/CopyMemory.java \
23:16:56          -Dtest.file=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc/CopyMemory.java \
23:16:56          -Dtest.src=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc \
23:16:56          -Dtest.src.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc \
23:16:56          -Dtest.classes=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/classes/2/sun/misc \
23:16:56          -Dtest.class.path=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/classes/2/sun/misc \
23:16:56          -Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/classes/2/sun/misc:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc \
23:16:56          -classpath /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/classes/2/sun/misc:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/openjdk/openjdk-jdk/jdk/test/sun/misc:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdkbinary/j2sdk-image/lib/tools.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/javatest.jar:/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/jvmtest/openjdk/jtreg/lib/jtreg.jar \
23:16:56          CopyMemory
23:16:56  stderr:
23:16:56  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_160100355359/jdk_lang_j9_0/work/scratch/2/jitdump.20200924.231501.8568.0004.dmp
23:16:56  JVMDUMP013I Processed dump event "abort", detail "".
```

**Comment by andrewcraik** [comment] 2020-09-25 20:49
@gita-omr this is on P so could someone have an initial look for a backtrace etc to see if it is an opt problem or a codegen problem?

**Comment by pshipton** [comment] 2020-09-25 20:51
There is another one from a different test.
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/57
test/jdk/java/util/Iterator/IteratorDefaults.java
cent7-ppcle-3
```
01:48:00  stderr:
01:48:00  JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_16010109773743/jdk_util_j9_0/work/scratch/2/Snap.20200925.024519.3293.0003.trc
01:48:00  JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_16010109773743/jdk_util_j9_0/work/scratch/2/jitdump.20200925.024519.3293.0004.dmp' in response to an event
01:48:00  #JITDUMP:  vmThread=000000000001EF00 Crashed while printing out current IL.
01:48:00  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_16010109773743/jdk_util_j9_0/work/scratch/2/jitdump.20200925.024519.3293.0004.dmp
01:48:00  JVMDUMP013I Processed dump event "abort", detail "".
```

**Comment by gita-omr** [comment] 2020-09-28 17:34
Yes, we'll take a look.

**Comment by pshipton** [comment] 2020-09-30 13:12
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/161/
java/util/HashSet/Serialization.java
cent7-ppcle-2
```
00:33:56  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_16014383593773/jdk_util_j9_0/work/scratch/1/jitdump.20200930.013110.25236.0004.dmp
00:33:56  JVMDUMP013I Processed dump event "abort", detail "".
```

**Comment by pshipton** [comment] 2020-10-08 04:40
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/181
jdk/test/sun/misc/CopyMemory.java
aix71-p8-9

**Comment by pshipton** [comment] 2020-10-09 12:14
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/169/
java/util/HashSet/Serialization.java
cent7-ppcle-1

**Comment by pshipton** [comment] 2020-10-15 13:24
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/175
java/util/HashSet/Serialization.java
cent7-ppcle-6

**Comment by gita-omr** [comment] 2020-10-23 18:01
Ok, let me take a look at the latest one.

**Comment by gita-omr** [comment] 2020-10-23 19:56
The console output has this:

        Serialization
[2020-10-15T05:25:23.366Z] stderr:
[2020-10-15T05:25:23.366Z] JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_ppc64le_linux_xl_Nightly/openjdk-tests/TKG/test_output_16027368557735/jdk_util_j9_0/work/scratch/1/jitdump.20201015.022205.15995.0004.dmp
[2020-10-15T05:25:23.366Z] JVMDUMP013I Processed dump event "abort", detail "".
[2020-10-15T05:25:23.366Z] 
[2020-10-15T05:25:23.366Z] TEST RESULT: Error. Agent communication error: java.io.EOFException; check console log for any additional details

But I can't find any other output in the Artifacts...

**Comment by gita-omr** [comment] 2020-10-23 21:18
All failures above have the same message, but Serialization.java seems to be most frequent. So we started grinder here:

https://ci.eclipse.org/openj9/job/Grinder/1118/

**Comment by gita-omr** [comment] 2020-10-25 21:44
Might be an environment issue. We ran on another machine and it passed 100/100.

**Comment by gita-omr** [comment] 2020-10-26 18:34
Also did not fail after 100 iterations on Adopt: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4309/

**Comment by gita-omr** [comment] 2020-10-28 23:15
https://github.com/eclipse/openj9/issues/10985#issuecomment-716912871  might solve the issue. Started 100 iterations with direct IP address here:  https://ci.eclipse.org/openj9/view/Test/job/Grinder/1123/

**Comment by pshipton** [comment] 2020-11-05 04:57
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/207/console
jdk/test/sun/misc/CopyMemory.java
aix71-p8-9

**Comment by pshipton** [comment] 2020-11-09 01:22
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/21
sun/misc/CopyMemory.java
aix71-p8-9

**Comment by gita-omr** [comment] 2020-11-18 15:53
Just fyi: we are looking at this one as well.  @mnalam-p

**Comment by gita-omr** [comment] 2020-11-19 00:13
100 iterations passed: https://ci.eclipse.org/openj9/job/Grinder/1186/

**Comment by gita-omr** [comment] 2020-11-19 15:21
500 iterations passed:https://ci.eclipse.org/openj9/job/Grinder/1192

**Comment by mnalam-p** [comment] 2020-11-19 19:09
20 iteration on local testing passed (on ppc64le)

**Comment by pshipton** [comment] 2020-11-30 14:41
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/228
jdk/test/sun/misc/CopyMemory.java
```
22:41:09  stderr:
22:41:09  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_16065343105630/jdk_lang_j9_0/work/scratch/jitdump.20201127.223959.22151418.0004.dmp
22:41:09  JVMDUMP013I Processed dump event "abort", detail "".
```

**Comment by pshipton** [comment] 2020-12-01 15:19
FYI This was set as a blocker due to the initial frequency of failure, and because the JVM should not unexpectedly abort without explanation of the problem.

**Comment by gita-omr** [comment] 2020-12-04 15:24
We are still trying to reproduce.

**Comment by rmnattas** [comment] 2020-12-07 16:56
One thing about this issue that it happens from different tests (we say it from CopyMemory.java, Serialization.java and IteratorDefaults.java) which could indicate that its something else happening causing this crash.
The last available artifacts that we're not old to get auto-delete were 3 all in `jdk/test/sun/misc/CopyMemory.java`[2] so I can't fully confirm what I found is the common thing in all these errors.

But, the second to last stderr line points to a jitdump... the jitdump for all the 3 cases are for the method `OldFloatingDecimalForTest.dtoa(IJI)V`, I know this method because it was the one failing when a spill happens in the middle of the fixedSeqMemAccess that I fixed last week (Issue: eclipse/openj9#11163, PR: eclipse/omr#5678).

Looking at `agent.trace` in the artifacts for all these 3 cases I see that its true.. a spill happened in the middle of the fixedSeqMemAccess for all of them [1]. And looking back at the Eclipse CI fail for the original spill issue ([LINK](https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/214/testReport/junit/sun_misc_FloatingDecimal_TestFloatingDecimal/java/TestFloatingDecimal/)) its also failing with:
```
Agent communication error: java.io.EOFException; check console log for any additional details    
```


Given that no other failure in these runs occurred but this spill is definitely causing an assert to fail, and that the only failure error we see is the same as the one we saw in the spill issue (`Agent communication error: java.io.EOFException`). 
**I think this is a dup for eclipse/openj9#11163** but for some reason it didn't console log like it... but the failing assert is got printed in the `agent.trace` file[1]

@zl-wang @gita-omr 


[1]
```
[2020-11-27 22:39:59,712]: POOL: Reusing Agent[4]
[2020-11-27 22:39:59,926] Agent[3]: stderr: Assertion failed at /home/jenkins/workspace/Build_JDK8_ppc64_aix_Nightly/build/aix-ppc64-normal-server-release/vm/compiler/../omr/compiler/p/codegen/OMRConstantD
ataSnippet.hpp:131: instr4->getBinaryEncoding() == instr1->getBinaryEncoding() + 16
[2020-11-27 22:39:59,926] Agent[3]: stderr: VMState: 0x0005ff0a
[2020-11-27 22:39:59,926] Agent[3]: stderr:     Instruction a000000701ee590 [lfd] (generated from node a000000300ee240 [dconst]): Unexpected ConstantDataSnippet load sequence
[2020-11-27 22:39:59,926] Agent[3]: stderr: compiling OldFloatingDecimalForTest.dtoa(IJI)V at level: scorching
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x16c
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0xce8
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x244
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x54
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x11c
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x5e8
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x2b4
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x484
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x2138
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x1034
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x20fc
[2020-11-27 22:39:59,926] Agent[3]: stderr: omrsig_protect+0x614
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x870
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x998
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x83c
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x4e0
[2020-11-27 22:39:59,926] Agent[3]: stderr: omrsig_protect+0x614
[2020-11-27 22:39:59,926] Agent[3]: stderr: +0x5b8
[2020-11-27 22:39:59,926] Agent[3]: stderr: thread_wrapper+0x73c
[2020-11-27 22:39:59,927] Agent[3]: stderr: _pthread_body+0x128
[2020-11-27 22:39:59,927] Agent[3]: stderr: +0x0
[2020-11-27 22:39:59,927] Agent[3]: stderr: 
[2020-11-27 22:39:59,927] Agent[3]: stderr: 
[2020-11-27 22:39:59,927] Agent[3]: stderr: Instruction context:
[2020-11-27 22:39:59,927] Agent[3]: stderr: 
[2020-11-27 22:39:59,927] Agent[3]: stderr: ...
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb7c 0001398c [0xa000000701ee280] 3f400000                0        lis     gr26, 0x0000000000000000
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb80 00013990 [0xa000000701ee310] 3c600000                0        lis     gr3, 0x0000000000000000
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb84 00013994 [0xa000000701ee3a0] 635a0000                0        ori     gr26, gr26, 0
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb88 00013998 [0xa000000701ee440] 7b43000e                0        rldimi  gr3, gr26, 0x0000000000000020, 0xFFFFFFFF00000000
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb8c 0001399c [0xa000000702fa280] eb4e0748                0        ld      gr26, [gr14, 1864]              ; spilled for dconst # #SPILL8          # SymRef  <#SPILL8_4663 0xa000000702f8e70>[#4663  Auto +1864] [flags 0x80000000 0x0 ]
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb90 000139a0 [0xa000000701ee590] c8030000                0        lfd     fp0, [gr3, 0]
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb94 000139a4 [0xa000000701ee860] 38600020                0        li      gr3, 0x0000000000000020
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb98 000139a8 [0xa000000701ee8f0] 7c6307b4                0        extsw   gr3, gr3
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdb9c 000139ac [0xa000000701ee980] 7c0315ae                0        stfdx   [gr3, gr2], fp0         # SymRef  <generic int shadow>[#1984  Shadow] [flags 0x603 0x0 ]
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdba0 000139b0 [0xa000000701eeb60] 38640138                0        addi    gr3, gr4, 312
[2020-11-27 22:39:59,927] Agent[3]: stderr: 0x100109bdba4 000139b4 [0xa000000701eec00] 7c6307b4                0        extsw   gr3, gr3

```





[2]
> https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/207/console
> jdk/test/sun/misc/CopyMemory.java
> aix71-p8-9

> https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_OpenJDK8/21
> sun/misc/CopyMemory.java
> aix71-p8-9

> https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/228
> jdk/test/sun/misc/CopyMemory.java
> aix71-p8-9
> 
> ```
> 22:41:09  stderr:
> 22:41:09  JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64_aix_Nightly/openjdk-tests/TKG/test_output_16065343105630/jdk_lang_j9_0/work/scratch/jitdump.20201127.223959.22151418.0004.dmp
> 22:41:09  JVMDUMP013I Processed dump event "abort", detail "".
> ```

**Comment by gita-omr** [comment] 2020-12-07 17:20
Wow! That’s great! I think we can definitely assume it’s a duplicate of #11163

**Comment by pshipton** [comment] 2020-12-08 02:00
In that case, unless somebody has an objection we can go ahead and close this since #11163 has been fixed. I'll reopen it if the problem is seen again.

**Comment by gita-omr** [comment] 2020-12-08 16:44
I have no objections.

**Closed** 2020-12-08 17:55 UTC
Labels: arch:power, blocker, comp:jit, test failure
