### ISSUE TITLE
JTReg Test Failure: java/lang/reflect/PublicMethods/PublicMethodsTest.java

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#7897] opened 2019-11-28 10:00 UTC
Failure link
------------
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/e34da885d49e5ac71b82d013e1335b260431fad6/test/jdk/java/lang/reflect/PublicMethods/PublicMethodsTest.java#L1 and https://github.com/ibmruntimes/openj9-openjdk-jdk13/blob/90dbac740d239d3d47ed2277fcd8418ae024b1dd/test/jdk/java/lang/reflect/PublicMethods/PublicMethodsTest.java#L1 consistantly fail for JDK11/13-openj9 (hotspot unaffected)
- test category, openjdk
- OS/architecture, openjdk_x86-64_linux, openjdk_x86-64_windows, openjdk_x86-64_mac

Optional info
-------------
- Part of the excluded https://github.com/AdoptOpenJDK/openjdk-tests/issues/585
- I suspect it to be Hotspot specific since the test is comparing class and interface details across implementations without any checks. 

Failure output (captured from console output)
---------------------------------------------
```
JDK11
16:29:56  openjdk version "11.0.6" 2020-01-14
16:29:56  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+4-201911260313)
16:29:56  Eclipse OpenJ9 VM AdoptOpenJDK (build master-9966b13c4, JRE 11 Linux amd64-64-Bit Compressed References 20191126_376 (JIT enabled, AOT enabled)
16:29:56  OpenJ9   - 9966b13c4
16:29:56  OMR      - bad5f71b7
16:29:56  JCL      - e34da885d4 based on jdk-11.0.6+4)

JDK13
16:30:20  openjdk version "13.0.1" 2019-10-15
16:30:20  OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9-201911260504)
16:30:20  Eclipse OpenJ9 VM AdoptOpenJDK (build master-9966b13c4, JRE 13 Linux amd64-64-Bit Compressed References 20191126_106 (JIT enabled, AOT enabled)
16:30:20  OpenJ9   - 9966b13c4
16:30:20  OMR      - bad5f71b7
16:30:20  JCL      - 90dbac740d based on jdk-13.0.1+9)

16:32:12  STDOUT:
16:32:12  interface I { void m(); }
16:32:12  interface J { void m(); }
16:32:12  interface K extends I, J {  }
16:32:12  abstract class C {  }
16:32:12  abstract class D extends C implements I {  }
16:32:12  abstract class E extends D implements J, K {  }
16:32:12  
16:32:12  expected: E.gM: I.m
16:32:12    actual: E.gM: J.m
16:32:12  
16:32:12  
16:32:12  STDERR:
16:32:12  java.lang.RuntimeException: There were 1 differences.
16:32:12  	at PublicMethodsTest.main(PublicMethodsTest.java:81)
16:32:12  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:32:12  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:32:12  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:32:12  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:32:12  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
16:32:12  	at java.base/java.lang.Thread.run(Thread.java:832)
16:32:12  
16:32:12  JavaTest Message: Test threw exception: java.lang.RuntimeException
16:32:12  JavaTest Message: shutting down test
```
Rerun JDK13-openj9 job: https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=openjdk&JenkinsFile=openjdk_x86-64_linux&CUSTOM_TARGET=test/jdk/java/lang/reflect/PublicMethods/PublicMethodsTest.java&TARGET=jdk_custom_0

**Comment by ChengJin01** [comment] 2019-12-02 18:56
I'll look at the issue to see what happened to OpenJ9.

**Comment by ChengJin01** [comment] 2019-12-02 23:03
I created a simple test based on the failing test output as follows:
[getMethodTest.java.txt](https://github.com/eclipse/openj9/files/3913670/getMethodTest.java.txt)
```
interface I { void m(); }
interface J { void m(); }
interface K extends I, J {  }
abstract class C {  }
abstract class D extends C implements I {  }
abstract class E extends D implements J, K {  }

public class getMethodTest {
    public static void main(String[] args) {
      try {
		Method testMethod = E.class.getMethod("m");
		System.out.println("testMethod.class = " + testMethod.toString());
	} catch (NoSuchMethodException e) {
 ...
}
```
And reproduced the issue with the latest build from AdoptOpenJDK:
```
# jdk_11.0.5_10_hotspot/bin/java  -cp .   getMethodTest
testMethod.class = public abstract void I.m()

# jdk_11.0.5_10_openj9/bin/java  -cp .   getMethodTest
testMethod.class = public abstract void J.m()  <------
```
Given that `Class.java` is implemented independently on OpenJ9, need to check whether there is something incorrect in `Class.getMethod()` against the Spec.

**Comment by M-Davies** [comment] 2019-12-03 10:41
@ChengJin01 I couldn't see any difference between the Hotspot and OpenJ9 implementations for `Class.getMethod()` and `Class.getMethodHelper()`. It's possible they still differ from each other underneath the hood however as they call a lot of smaller functions.

**Comment by M-Davies** [comment] 2019-12-03 13:47
I did find some small difference in the child functions but am doubtful that these would make any difference to the test.

- `Class.getMethod() -> getMethodHelper() -> getDeclaredMethodImpl() -> filterMethods()`in the test checks if the current method name == classname (if it is, it removes it from the returned array). `filterMethods()` does not appear to exist in OpenJ9

- `Class.getMethod() -> getMethodHelper() -> getDeclaredMethodImpl() -> getDeclaredMethodsImpl() -> writeFieldValue()` writes a field value according to a given offset value. OpenJ9 has an extra line in this method https://github.com/eclipse/openj9/blob/37b5263ba841f18c6091f4e7caa9abf67f3c8d9b/jcl/src/java.base/share/classes/java/lang/Class.java#L345 which the test does not have.

**Comment by ChengJin01** [comment] 2019-12-03 18:22
@M-Davies , the code logic changed in `getMethodHelper()` last year to deal with specific methods after removing `j.l.Class.getClassDepth()`. Now the thing we need to figure out is whether or not it covered all aspects against the Java Spec.

**Comment by ChengJin01** [comment] 2019-12-03 22:44
I created 3 test cases separately based on the simple test above:
```
(1)
interface I { void m(); }
interface J { void m(); }
abstract class E implements I,J {} <---- I in front of J

# jdk_11.0.5_10_hotspot/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void I.m()

# jdk_11.0.5_10_openj9/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void I.m()

(2)
interface I { void m(); }
interface J { void m(); }
abstract class E implements J,I {} <---- J in front of I

# jdk_11.0.5_10_hotspot/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void J.m()

# jdk_11.0.5_10_openj9/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void J.m()

(3)
interface I { void m(); }
interface J { void m(); }
abstract class C {  }
abstract class D extends C implements I {} <---- I is implemented by D
abstract class E extends D implements J {} <---- J is implemented by E

# jdk_11.0.5_10_hotspot/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void I.m()

# jdk_11.0.5_10_openj9/bin/java  -cp .   getMethodTest
testMethod.classMethod = public abstract void J.m()
```
Against the API Spec:
```
3. Within each such subset only the most specific methods are selected. 
   Let method M be a method from a set of methods with same VM signature 
   (return type, name, parameter types). 
   M is most specific if there is no such method N != M from the same set, 
   such that N is more specific than M. N is more specific than M if:
    a. N is declared by a class and M is declared by an interface; or
    b. N and M are both declared by classes or both by interfaces 
       and N's declaring type is the same as or a subtype of M's declaring type 
    (clearly, if M's and N's declaring types are the same type, then M and N are the same method).
```
For test case (1) and (2), the most specific method was chosen according to the order of interfaces in the declaration as both methods are declared in interfaces, which is correct as both `I.m` and `J.m` are equal in terms of signature and return type.

For test case (3), apparently Hotspot chose `Class D` for `m()` while OpenJ9 chose `interface J` for `m()`. Now the problem is, whether this behaviour can be explained by the Spec above at `3.a`
```
a. N is declared by a class and M is declared by an interface;
```
To be specific, the more specific method N should come from the super-class rather than the interface if N and M are equal in both signature and return type. If so, we should first search the corresponding super-class for the requested method; if doesn't exist, then get back to check the interface.

FYI: @JasonFengJ9

**Comment by ChengJin01** [comment] 2019-12-05 04:02
I made a fix for this issue on Java 11 & 13 which proved to work good on the failing tests above:
```
# jdk11_openj9/bin/java -version
openjdk version "11.0.6-internal" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6-internal+0-adhoc.root.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build jcl_class_getmethod-47b1c87, JRE 11 Linux amd64-64-Bit Compressed References 20191204_000000 (JIT enabled, AOT enabled)
OpenJ9   - 47b1c87
OMR      - 3d58b80
JCL      - 9f9c073 based on jdk-11.0.6+4)

# jdk11_openj9/bin/java -cp .  getMethodTest
testMethod.classMethod = public abstract void I.m()

.../jdk11_PublicMethods# ../jdk11_openj9/bin/java   -cp .  PublicMethodsTest
# (test passed without exception)


# jdk13_openj9/bin/java  -version
openjdk version "13.0.1-internal" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1-internal+0-adhoc.root.openj9-openjdk-jdk13)
Eclipse OpenJ9 VM (build jcl_class_getmethod-47b1c87, JRE 13 Linux amd64-64-Bit Compressed References 20191204_000000 (JIT enabled, AOT enabled)
OpenJ9   - 47b1c87
OMR      - 3d58b80
JCL      - 9c25deb based on jdk-13.0.1+9)

# jdk13_openj9/bin/java -cp .  getMethodTest
testMethod.classMethod = public abstract void I.m()

.../jdk13_PublicMethods# ../jdk13_openj9/bin/java   -cp .  PublicMethodsTest
# (test passed without exception)
```
Will launch personal builds to see whether everything goes well before creating a PR.

**Closed** 2020-09-03 13:59 UTC
Labels: test failure
