### ISSUE TITLE
Many git fetch problems on zlinux machines

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#8827] opened 2020-03-11 14:09 UTC
Like https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.functional_s390x_linux_Nightly/32
I notice `ERROR: Reference path does not exist: $HOME/openjdk_cache`

See the #jenkins channel for all the failures. I tried to restart but many failed again.

**Comment by pshipton** [comment] 2020-03-11 14:10
@jdekonin @AdamBrousseau

**Comment by pshipton** [comment] 2020-03-11 14:11
Also like https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_s390x_linux_Nightly/1369
```
08:25:46  get functional test material...
08:25:46  git clone --depth 1 -b master https://github.com/eclipse/openj9.git
08:32:59  error: RPC failed; curl 56 SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
08:32:59  fatal: The remote end hung up unexpectedly
```

**Comment by AdamBrousseau** [comment] 2020-03-11 14:45
Indeed the ref repos aren't there. Looking at the [update job](https://ci.eclipse.org/openj9/view/Infrastructure/job/Update-Reference-Repos), looks like it hasn't been running because the cron schedule was removed by [this change](https://github.com/eclipse/openj9/commit/f7795600acf895f1fc26a9d0d31406291f9e48ca). Likely intended to be manually configured, the issue is leaving the properties section (for build discarder) but having no trigger, will overwrite the manual config and remove any triggers. For properties you can only configure one way or the other, can't mix. I'll open a PR to fix that.
In terms of poor network perf, we can try rebooting them. Not sure what else can be done other than raising the issue with Marist.

**Comment by AdamBrousseau** [comment] 2020-03-11 16:37
Job running now to update all the repos
https://ci.eclipse.org/openj9/view/Infrastructure/job/Update-Reference-Repos/504
PR #8829 will need to be merged and the schedule will need to be turned back on.

**Comment by pshipton** [comment] 2020-03-11 18:34
Let me know when the schedule is added, and then I will close.

**Comment by AdamBrousseau** [comment] 2020-03-11 19:08
Added for noon on Suday

**Closed** 2020-03-11 20:36 UTC
Labels: comp:infra
