### ISSUE TITLE
JDK8 DaaLoadTest_all_ConcurrentScavenge_0_FAILED : Segmentation error vmState=0x00020002

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10587] opened 2020-09-14 01:37 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/486/tapResults/
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
00:08:31  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=ppc64le_linux&TARGET=DaaLoadTest_all_ConcurrentScavenge_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test DaaLoadTest_all_ConcurrentScavenge_0 ...
===============================================

DLT 23:57:13.831 -   47 JUnit[net.openj9.test.arithmetics.TestArithmeticOperations]  Weighting=1 
DLT 23:57:13.866 - Starting thread. Suite=0 thread=0
DLT 23:57:13.868 - Starting thread. Suite=0 thread=1
DLT 23:57:13.868 - Starting thread. Suite=0 thread=2
DLT 23:57:13.868 - Starting thread. Suite=0 thread=3
DLT 23:57:13.869 - Starting thread. Suite=0 thread=4
DLT 23:57:13.869 - Starting thread. Suite=0 thread=5
DLT 23:57:13.869 - Starting thread. Suite=0 thread=6
DLT 23:57:13.870 - Starting thread. Suite=0 thread=7
DLT 23:57:13.870 - Starting thread. Suite=0 thread=8
DLT 23:57:13.870 - Starting thread. Suite=0 thread=9
DLT 23:57:13.871 - Starting thread. Suite=0 thread=10
DLT 23:57:13.871 - Starting thread. Suite=0 thread=11
DLT 23:57:13.871 - Starting thread. Suite=0 thread=12
DLT 23:57:13.871 - Starting thread. Suite=0 thread=13
DLT stderr Unhandled exception
DLT stderr Type=Segmentation error vmState=0x00020002
DLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
DLT stderr Handler1=00003FFF81F0AC50 Handler2=00003FFF81D635C0
DLT stderr R0=00003FFF80795650 R1=00003FFF4AD5BDF0 R2=00003FFF808F5700 R3=00003FFF7C05ABE0
DLT stderr R4=0000000080D81F38 R5=00000000B65A2ED2 R6=0000000081030000 R7=00003FFF7C03D680
DLT stderr R8=000000000000000C R9=00003FFF7C014650 R10=00003FFF7C059270 R11=00000000000001FF
DLT stderr R12=00003FFF8075FD40 R13=00003FFF4AD66900 R14=0000000000000000 R15=0000000000000000
DLT stderr R16=00003FFF4AD20000 R17=0000000000040000 R18=00003FFF82C84390 R19=00003FFF4AD5F900
DLT stderr R20=00003FFF7C191EC0 R21=00003FFF7C192328 R22=00003FFF4AD5F260 R23=00003FFF4AD5BF30
DLT stderr R24=00003FFF4AD5BE58 R25=0000000000000001 R26=00003FFF7C0D1660 R27=00003FFF7C0D1740
DLT stderr R28=0000000000000090 R29=0000000000000003 R30=00003FFEF4001AC8 R31=00000000B65A2ED2
DLT stderr NIP=00003FFF80795618 MSR=800000010280F033 ORIG_GPR3=00000000000081C8 CTR=00003FFF8075FD40
DLT stderr LINK=00003FFF80795650 XER=0000000000000000 CCR=0000000044244248 SOFTE=0000000000000001
DLT stderr TRAP=0000000000000300 DAR=00000000B65A2EDE dsisr=0000000040000000 RESULT=0000000000000000
DLT stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR1 4053827f20000000 (f: 536870912.000000, d: 7.803901e+01)
DLT stderr FPR2 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
DLT stderr FPR3 bf3d4a1000000000 (f: 0.000000, d: -4.469194e-04)
DLT stderr FPR4 3f499a0000000000 (f: 0.000000, d: 7.812977e-04)
DLT stderr FPR5 bf94724ea0000000 (f: 2684354560.000000, d: -1.996730e-02)
DLT stderr FPR6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR8 808d1650807e02d0 (f: 2155741952.000000, d: -5.177687e-306)
DLT stderr FPR9 808d167000000000 (f: 0.000000, d: -5.177773e-306)
DLT stderr FPR10 bfd1e45000000000 (f: 0.000000, d: -2.795601e-01)
DLT stderr FPR11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR13 bfb7440000000000 (f: 0.000000, d: -9.088135e-02)
DLT stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
DLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
DLT stderr Module_base_address=00003FFF805D0000
DLT stderr Target=2_90_20200912_511 (Linux 4.4.0-173-generic)
DLT stderr CPU=ppc64le (16 logical CPUs) (0x1fe090000 RAM)
DLT stderr ----------- Stack Backtrace -----------
DLT stderr (0x00003FFF80795618 [libj9gc29.so+0x1c5618])
DLT stderr (0x00003FFF80795650 [libj9gc29.so+0x1c5650])
DLT stderr (0x00003FFF8061293C [libj9gc29.so+0x4293c])
DLT stderr (0x00003FFF80790638 [libj9gc29.so+0x1c0638])
DLT stderr (0x00003FFF8074645C [libj9gc29.so+0x17645c])
DLT stderr (0x00003FFF80848E00 [libj9gc29.so+0x278e00])
DLT stderr (0x00003FFF807555B4 [libj9gc29.so+0x1855b4])
DLT stderr (0x00003FFF80754D18 [libj9gc29.so+0x184d18])
DLT stderr (0x00003FFF81D649C8 [libj9prt29.so+0x349c8])
DLT stderr (0x00003FFF80754490 [libj9gc29.so+0x184490])
DLT stderr (0x00003FFF81E31248 [libj9thr29.so+0x11248])
DLT stderr (0x00003FFF82C58040 [libpthread.so.0+0x8040])
DLT stderr clone+0x98 (0x00003FFF82B33BB0 [libc.so.6+0x123bb0])
DLT stderr ---------------------------------------
DLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2020/09/12 23:57:14 - please wait.
DLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/core.20200912.235714.7189.0001.dmp' in response to an event
DLT stderr JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.7239.
DLT stderr 
DLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/core.20200912.235714.7189.0001.dmp
DLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/javacore.20200912.235714.7189.0002.txt' in response to an event
STF 23:57:15.588 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/javacore.20200912.235714.7189.0002.txt
STF 23:57:15.588 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/core.20200912.235714.7189.0001.dmp
DLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/javacore.20200912.235714.7189.0002.txt
DLT stderr core file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/core.20200912.235714.7189.0001.dmp
DLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/javacore.20200912.235714.7189.0002.txt
DLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/Snap.20200912.235714.7189.0003.trc' in response to an event
STF 23:57:17.426 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/Snap.20200912.235714.7189.0003.trc
DLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/Snap.20200912.235714.7189.0003.trc
DLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/Snap.20200912.235714.7189.0003.trc
DLT stderr JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/jitdump.20200912.235714.7189.0004.dmp' in response to an event
DLT stderr JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/results/jitdump.20200912.235714.7189.0004.dmp
DLT stderr JVMDUMP013I Processed dump event "gpf", detail "".
STF 23:57:17.528 - **FAILED** Process DLT ended with exit code (255) and not the expected exit code/s (0)
STF 23:57:17.528 - Monitoring Report Summary:
STF 23:57:17.528 -   o Process DLT has crashed unexpectedly
STF 23:57:17.528 - Killing processes: DLT
STF 23:57:17.528 -   o Process DLT is not running
**FAILED** at step 1 (Run daa load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/../TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/execute.pl line 94.
STF 23:57:17.539 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 23:57:17.539 - 
STF 23:57:17.539 - ====================   T E A R D O W N   ====================
STF 23:57:17.539 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/openjdk-tests/TKG/../TKG/test_output_15999661304023/DaaLoadTest_all_ConcurrentScavenge_0/20200912-235710-DaaLoadTest/tearDown.pl
STF 23:57:17.598 - TEARDOWN stage completed
STF 23:57:17.602 - 
STF 23:57:17.603 - =====================   R E S U L T S   =====================
STF 23:57:17.603 - Stage results:
STF 23:57:17.603 -   setUp:     pass
STF 23:57:17.603 -   execute:  *fail*
STF 23:57:17.603 -   teardown:  pass
STF 23:57:17.603 - 
STF 23:57:17.603 - Overall result: **FAILED**

DaaLoadTest_all_ConcurrentScavenge_0_FAILED
```

**Comment by dmitripivkine** [comment] 2020-09-14 19:13
this is a duplicate of https://github.com/eclipse/openj9/issues/10489 (corruption in Ownable Synchronizer List)
```
#13 <signal handler called>
#14 0x00003fff80795618 in MM_MarkingSchemeRootClearer::scanOwnableSynchronizerObjects(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#15 0x00003fff8061293c in MM_RootScanner::scanClearable(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#16 0x00003fff80790638 in MM_MarkingDelegate::workerCompleteGC(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#17 0x00003fff8074645c in MM_MarkingScheme::markLiveObjectsComplete(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#18 0x00003fff80848e00 in MM_ParallelMarkTask::run(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#19 0x00003fff807555b4 in MM_ParallelDispatcher::workerEntryPoint(MM_EnvironmentBase*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#20 0x00003fff80754d18 in dispatcher_thread_proc2(OMRPortLibrary*, void*) ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#21 0x00003fff81d649c8 in omrsig_protect ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9prt29.so
#22 0x00003fff80754490 in dispatcher_thread_proc ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9gc29.so
#23 0x00003fff81e31248 in thread_wrapper ()
   from /team/Dmitri/10587/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9thr29.so
#24 0x00003fff82c58040 in ?? ()
#25 0x00003fff82b33bb0 in ?? ()
```

**Closed by dmitripivkine** 2020-09-14 19:13 UTC
Labels: comp:gc, test failure
