### ISSUE TITLE
JIT failure when JVMTI field watches are added

### ISSUE THREAD

**Issue by urisimchoni** [eclipse/openj9#1572] opened 2018-03-29 09:37 UTC
When running an application with a JVMTI agent, and the agent installs field access/modification watches, methods using those fields fail to JIT-compile.

This seems to happen at the second JIT attempt, i.e. if there are methods A and B, both of which involve watched fields, and A is called first, then only B's JIT fails.

A bare-bones sample of the issue is in https://github.com/urisimchoni/jitfaildemo

An excerpt from the sample with some comments:
```java
public class Hello {
    public static void main(String[] args) {
        AManyFields amf = new AManyFields();
        //native call to the agent - it installs watches over the fields of the class of amf
        MyAgent.analyzeObj(amf);
        BManyFields bmf = new BManyFields();
        //native call to the agent - it installs watches over the fields of the class of bmf
        MyAgent.analyzeObj(bmf);

        int sum=0;
        sum+=amf.getSum();
        sum+=bmf.getSum();
        System.out.printf("Sum is %d\n",sum);
    }
}
```

Running this with `-Xjit:count=0,verbose={compileStart|compileEnd}` emits the following:
```
 (no-opt) Compiling AManyFields.getSum()I  OrdinaryMethod j9m=00000000022CA7B0 t=2831 compThread=0 memLimit=262144 KB freePhysicalMemory=10853 MB
+ (no-opt) AManyFields.getSum()I @ 00007FCBA80FA010-00007FCBA80FA117 OrdinaryMethod - Q_SZ=0 Q_SZI=0 QW=6 j9m=00000000022CA7B0 bcsz=14 sync OSR compThread=0 CpuLoad=115%(28%avg) JvmCpu=99%
 (no-opt) Compiling BManyFields.getSum()I  OrdinaryMethod j9m=00000000022CACA8 t=2831 compThread=0 memLimit=262144 KB freePhysicalMemory=10853 MB
! BManyFields.getSum()I time=79us Compilation Exception <TRANSLATION FAILURE: out of scratch memory>
```

Removing the watch from agent code causes JIT to succeed.

This issue seems to be correlated with a JVM crash we're investigating, related to a Java EE application and a JVMTI agent. While we haven't been able to reproduce the crash with a simple app and a simple agent, we do see that in the full app and agent, we get those JIT errors, and if we remove functionality from the agent so as to avoid the crash, those errors also disappear.

**Comment by urisimchoni** [comment] 2018-03-29 17:18
Forgot to add version info so here it is: it happens with Java 8, both with IBM's JDK and own-built OpenJ9 and OpenJDK.

The IBM version info:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 8.0.5.10 - pxa6480sr5fp10-20180214_01(SR5 FP10))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180208_378436 (JIT enabled, AOT enabled)
OpenJ9   - 39bb844
OMR      - c04ccb2
IBM      - 2321a81)
JCL - 20180209_01 based on Oracle jdk8u161-b12

The OpenJDK version:
openjdk version "1.8.0_162-internal-debug"
OpenJDK Runtime Environment (build 1.8.0_162-internal-debug-_2018_03_27_19_22-b00)
Eclipse OpenJ9 VM (build master-9c05da6, JRE 1.8.0 Linux amd64-64 Compressed References 20180327_000000 (JIT enabled, AOT enabled)
OpenJ9   - 9c05da6
OMR      - 03270bf
JCL      - 8599c6f based on jdk8u162-b12)

**Comment by JamesKingdon** [comment] 2018-03-31 01:28
Hi, many thanks for opening the issue and providing a test-case. I was able to reproduce the problem easily by following your instructions.

The compilation of the second getSum() method fails very early:

```
<compile
        method="BManyFields.getSum()I"
        hotness="warm"
        isProfilingCompile=0>

=======>BManyFields.getSum()I
<ilgen
        method="BManyFields.getSum()I">
   <request> {OrdinaryMethod(<NULL>)} </request>

        +------------- Byte Code Index
        |  +-------------------- OpCode
        |  |                        +------------- First Field
        |  |                        |     +------------- Branch Target
        |  |                        |     |      +------- Const Pool Index
        |  |                        |     |      |    +------------- Constant
        |  |                        |     |      |    |
        V  V                        V     V      V    V

        0, JBiconst0            
        1, JBistore1            
        2, JBiload1             
        3, JBaload0getfield      
        4, JBgetfield                            4
        7, JBgetfield                            5
       10, JBiadd               
       11, JBistore1            
       12, JBiload1             
       13, JBreturn1            

Compilation Failed Because: offset == J9JIT_RESOLVE_FAIL_COMPILE
</compile>
```

**Comment by JamesKingdon** [comment] 2018-03-31 01:42
There are 4 places in `j9method.cpp` where we can generate that failure code, and I'm not sure which one is the cause, but just picking on the first example, we do
`offset = jitCTResolveInstanceFieldRefWithMethod(_fe->vmThread(), ramMethod(), cpIndex, isStore, &fieldShape);`
followed by
```
if (offset == J9JIT_RESOLVE_FAIL_COMPILE)
      {
      comp->failCompilation<TR::CompilationException>("offset == J9JIT_RESOLVE_FAIL_COMPILE");
      }
```

**Comment by JamesKingdon** [comment] 2018-03-31 20:09
Got a bit further, the fail code is being set in `jvmtiHookCheckForDataBreakpoint` in jvmtiHook.c at
```
						} else {
							if (data->resolvedField == romField) {
								data->result = J9_JIT_RESOLVE_FAIL_COMPILE;
								printf("jvmtiHookCheckForDataBreakpoint: FAIL at 2\n");
								break;
							}
						}

```

**Comment by JamesKingdon** [comment] 2018-03-31 20:13
@DanHeidinga I'm not familiar with this code - who would be a good person to look at it?

**Comment by DanHeidinga** [comment] 2018-04-02 01:56
@gacholio Can you comment on the behaviour of `jvmtiHookCheckForDataBreakpoint` and why we're deliberately failing compiles when the fields are watched?

**Comment by JamesKingdon** [comment] 2018-04-02 11:01
When you put it like that, it seems quite likely that we can't support watched fields from jitted code. But then the question would be why does one method get JIT compiled and one not.

**Comment by andrewcraik** [comment] 2018-04-02 12:36
The JIT will fail the compilations because the watch is not supported by the JIT and I don't think these are directly correlated with the error - this is how I would expect the JIT to behave. We can check with @gacholio on what compensation logic runs when the watch is set for methods that have already been compiled, but I imagine that we would need to stop running JIT'd code that might reference the problem field.

Note that runnint with `count=0` is an unusual configuration in that most of the Java code will not have run and most references will not be resolved. A more natural configuration is at least `count=1,disableAsyncCompilation` which means after a method is run one the method will be compiled on the application thread (`count=0` implies `disableAsyncCompilation`).

Perhaps some more background on the real issue you are trying to debug might allow us to make suggestions to help your investigation?

**Comment by JamesKingdon** [comment] 2018-04-02 13:15
One thing of interest; I modified the testcase to print from the callbacks and I don't get any output for either of the objects, even when running Xint.

**Comment by urisimchoni** [comment] 2018-04-02 13:21
Re: callbacks don't print - that's because field access events are not enabled, e.g.:
`jvmti->SetEventNotificationMode(JVMTI_ENABLE, JVMTI_EVENT_FIELD_ACCESS, NULL);`

**Comment by JamesKingdon** [comment] 2018-04-02 13:41
Ah, that works better :)

**Comment by JamesKingdon** [comment] 2018-04-02 13:52
Hmm, ok, and with that I can see that something is going wrong. Running with -Xint or without count=0 I get both the expected callbacks. In the case where count=0 is set (globally) the first method gets JIT compiled and we only get one callback. I haven't put any diagnostic in to differentiate between the callback invocations, but it seems likely that the method that gets JIT compiled is the one that doesn't make the callback. Looks like there might be a race condition for avoiding JIT compiling a watched method and/or compensating for an already compiled method that has a watched field.

However, as per Andrew's comment, a missing callback probably isn't related to the crash you're investigating.

**Comment by JamesKingdon** [comment] 2018-04-03 19:12
Hi Uri, I think probably we need someone from the interpreter side to look into one of your core files and see what's going on. Do you have a service contract for WebSphere? It might be easier to get the right eyes on the problem via a conventional PMR.

**Comment by JamesKingdon** [comment] 2018-04-04 12:09
I think it's worth keeping this issue to explore why we have the inconsistent behaviour across the two methods and the missing callback invocation. I'm pretty sure something isn't working quite right there.

**Comment by DanHeidinga** [comment] 2018-04-04 13:39
@urisimchoni If you have a core file that you can share, I'd like to have someone on my team take a look.  We don't like it when the JVM crashes =)

**Comment by gacholio** [comment] 2018-04-04 17:30
@urisimchoni You are correct - when a field watch is added, all compiled methods are discarded because we don't keep sufficient data to know which fields are used in which compilations (which may have fully or partially inlined other methods).

The "out of scratch memory" message is misleading - it's no doubt printed as a result of the compile-time resolution of the watched field failing.

**Comment by DanHeidinga** [comment] 2018-04-09 17:08
@urisimchoni Thanks for sending me the core file.  We've been able to identify the root cause (missing syncObject) and are working through the right way to fix this.  GAC has opened #1637 and described the root issue there.

Closing this now as we'll track the fix in the more specific #1637.

**Closed by DanHeidinga** 2018-04-09 17:08 UTC
Labels: comp:jit, userRaised

**Comment by DanHeidinga** [comment] 2018-04-09 17:33
Sorry @JamesKingdon, I missed that comment.  Can you open a new issue for that specific part of this investigation?

**Comment by gacholio** [comment] 2018-04-09 17:49
There is no failure here (other than the crash, of course).  The only thing to possibly address is the message in the verbose log, which I'm sure will never be done.  Being able to run code with watched fields would be an enhancement, which again I find unlikely to ever be done, given the frequency of use of this facility.

**Comment by JamesKingdon** [comment] 2018-04-09 17:54
@gacholio The test-case shows inconsistent behaviour. The first of two methods gets compiled by the JIT and fails to invoke the callback, despite both methods having watches set.

**Comment by andrewcraik** [comment] 2018-04-09 18:01
@JamesKingdon I know the VM is allowed to delay having a JVMTI event hookup for some quantum of time after the event is enabled. The count=0 case is an odd one because the method could be compiled before the agent is attached and before the method ran. I don't know if the code in question ran before the agent had completed init and if the event had been fully enabled, etc. At non-zero counts I would expect completely consistent behavior.

**Comment by JamesKingdon** [comment] 2018-04-09 18:44
However, you are right that it is somehow related to the use of count=0, the expected behaviour returns with count=1.

Does this put it in the realm of too obscure to merit further investigation?

**Comment by andrewcraik** [comment] 2018-04-09 19:17
I'm not sure I'd say doesn't merit further investigation, but the urgency of that investigation is much lower. I am curious about what runtest is doing so I may speak to you offline with a result posted here.

**Comment by DanHeidinga** [comment] 2018-04-09 19:17
> Does this put it in the realm of too obscure to merit further investigation?

I doubt anyone is going to track down the `count=0` issue given the root cause of the crash has been identified and the other issues that would affect more users.

**Comment by urisimchoni** [comment] 2018-04-10 03:51
Thanks all and sorry to have "barked on the wrong tree". Hopefully the core dump will lead in the right direction.

**Comment by DanHeidinga** [comment] 2018-04-10 12:58
Thanks so much for reporting the issue!  You've provided great context and a core that made it easy to identify a decompilation bug.  A big help anyone running with the debugger / jvmti watches. 

Much appreciated!
