### ISSUE TITLE
JTReg Test Failure: java/util/concurrent/ArrayBlockingQueue/WhiteBox.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#6776] opened 2019-08-20 09:21 UTC
Failure link
------------
- Build: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/197
- Test Category: openjdk
- Test Suite: jdk_util
- OS/Architecture: x64_macosx and x64_macosx_xl
- OpenJDK Version: 13+30
- Public Build SHAs:
- OpenJ9 - `81195db9c`
- OMR - `6e99760b`
- JCL - `2337332cb3`

Optional info
-------------
- Intermittent failure: No
- Regression or new test: Regression
- Last Passing SHAs: Same as above (?) link: https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk13_j9_sanity.openjdk_x86-64_mac_xl/19/
- Past issue on JDK11 Mac: https://github.com/eclipse/openj9/issues/5988

Failure output (captured from console output)
---------------------------------------------
```
09:51:43  [2019-08-20 09:51:43,588] Agent[1]: stderr: Unhandled exception
09:51:43  [2019-08-20 09:51:43,588] Agent[1]: stderr: Type=Segmentation error vmState=0x00040000
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000000
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: Handler1=000000000CEF1C10 Handler2=000000000D1276C0
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: RDI=000000000000002D RSI=0000000000000020 RAX=01EED70B08FFE145 RBX=D9B200308B3FAB97
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: RCX=616A0010003B6863 RDX=616A0010003B6863 R8=0000000000000001 R9=000000000D0ED838
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: R10=0000000000000000 R11=00007FA69502F700 R12=00007FA694C15D30 R13=01EF56B19F1D5E82
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: R14=00007FA694D097E0 R15=00007FA694C15D38
09:51:43  [2019-08-20 09:51:43,589] Agent[1]: stderr: RIP=000000000EE9E820 GS=0000 FS=0000 RSP=0000700007BCFB90
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: RFlags=0000000000010206 CS=002B RBP=0000700007BCFC00 ERR=0EA4A57000000000
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: TRAPNO=000000000000000D CPU=A570000000000000 FAULTVADDR=000000000EA4A570
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: XMM0 00000000005b3400 (f: 5977088.000000, d: 2.953074e-317)
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: XMM1 000000000004cc00 (f: 314368.000000, d: 1.553184e-318)
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: XMM2 000000000004cc00 (f: 314368.000000, d: 1.553184e-318)
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: XMM3 3f53e7a7d4000000 (f: 3556769792.000000, d: 1.214899e-03)
09:51:43  [2019-08-20 09:51:43,590] Agent[1]: stderr: XMM4 bea8be276726e6d2 (f: 1730602752.000000, d: -7.373926e-07)
09:51:43  [2019-08-20 09:51:43,591] Agent[1]: stderr: XMM5 3fd2294200000000 (f: 0.000000, d: 2.837682e-01)
09:51:43  [2019-08-20 09:51:43,591] Agent[1]: stderr: XMM6 3f53e7a7d4000000 (f: 3556769792.000000, d: 1.214899e-03)
09:51:43  [2019-08-20 09:51:43,591] Agent[1]: stderr: XMM7 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
09:51:43  [2019-08-20 09:51:43,591] Agent[1]: stderr: XMM8 01000a0000001e00 (f: 7680.000000, d: 7.308923e-304)
09:51:43  [2019-08-20 09:51:43,591] Agent[1]: stderr: XMM9 0000000000000004 (f: 4.000000, d: 1.976263e-323)
09:51:43  [2019-08-20 09:51:43,592] Agent[1]: stderr: XMM10 0000000000000006 (f: 6.000000, d: 2.964394e-323)
09:51:43  [2019-08-20 09:51:43,592] Agent[1]: stderr: XMM11 0000000000000008 (f: 8.000000, d: 3.952525e-323)
09:51:43  [2019-08-20 09:51:43,592] Agent[1]: stderr: XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:51:43  [2019-08-20 09:51:43,592] Agent[1]: stderr: XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:51:43  [2019-08-20 09:51:43,592] Agent[1]: stderr: XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: Module=/Users/jenkins/workspace/Grinder_Advanced/openjdkbinary/j2sdk-image/lib/default/libjclse29.dylib
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: Module_base_address=000000000EE85000 Symbol=getSegmentSizes
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: Symbol_address=000000000EE9E740
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: Target=2_90_20190813_40 (Mac OS X 10.13.6)
09:51:43  [2019-08-20 09:51:43,593] Agent[1]: stderr: CPU=amd64 (4 logical CPUs) (0x200000000 RAM)
09:51:43  [2019-08-20 09:51:43,594] Agent[1]: stderr: ----------- Stack Backtrace -----------
09:51:43  [2019-08-20 09:51:43,594] Agent[1]: stderr: ---------------------------------------
09:51:43  [2019-08-20 09:51:43,594] Agent[1]: stderr: JVMDUMP039I Processing dump event "gpf", detail "" at 2019/08/20 09:51:43 - please wait.
09:51:43  [2019-08-20 09:51:43,594] Agent[1]: stderr: JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/core.20190820.095143.89318.0001.dmp' in response to an event
09:51:49  [2019-08-20 09:51:49,399] Agent[1]: stderr: JVMDUMP012E Error in System dump: The core file created by child process with pid = 89326 was not found. Expected to find core file with name "/cores/core.89326"
09:51:49  [2019-08-20 09:51:49,400] Agent[1]: stderr: JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/javacore.20190820.095143.89318.0002.txt' in response to an event
09:51:50  [2019-08-20 09:51:49,744] Agent[1]: stderr: JVMDUMP012E Error in Java dump: /Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/javacore.20190820.095143.89318.0002.txt
09:51:50  [2019-08-20 09:51:49,744] Agent[1]: stderr: JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/Snap.20190820.095143.89318.0003.trc' in response to an event
09:51:50  [2019-08-20 09:51:49,847] Agent[1]: stderr: JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/Snap.20190820.095143.89318.0003.trc
09:51:50  [2019-08-20 09:51:49,848] Agent[1]: stderr: JVMDUMP007I JVM Requesting JIT dump using '/Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/jitdump.20190820.095143.89318.0004.dmp'
09:51:50  [2019-08-20 09:51:49,848] Agent[1]: stderr: JVMDUMP010I JIT dump written to /Users/jenkins/workspace/Grinder_Advanced/openjdk-tests/TestConfig/test_output_15662910516620/jdk_custom_0/work/scratch/0/jitdump.20190820.095143.89318.0004.dmp
09:51:50  [2019-08-20 09:51:49,849] Agent[1]: stderr: JVMDUMP013I Processed dump event "gpf", detail "".
```

**Comment by pshipton** [comment] 2019-08-20 12:30
@DanHeidinga fyi, a regression

**Comment by DanHeidinga** [comment] 2019-08-20 12:45
@ChengJin01 Can you take a look at this?

**Comment by DanHeidinga** [comment] 2019-08-20 12:54
It's not clear this is a regression so much as an intermittent issue - see the history in #5988 

I'm going to close this as a duplicate of #5988.  FYI @theresa-m

**Closed by DanHeidinga** 2019-08-20 12:54 UTC
Labels: test failure
