### ISSUE TITLE
Changed behaviour in DDR gccheck threadstacks

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/openj9#3472] opened 2018-10-29 19:31 UTC
When I worked on core provided in https://github.com/eclipse/openj9/issues/3467 I noticed change of behaviour in DDR: with latest it returns an error
```
> !gccheck threadstacks
Starting GC Check
Checking THREAD STACKS...Problem running command:
Array index out of range: 7
```
This behaviour has been introduced in iBuild 400030. Previous behaviour was an exception:
```
> !gccheck threadstacks
Starting GC Check
Checking THREAD STACKS...Error executing DDR command !gccheck threadstacks : null
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
    at java.lang.reflect.Method.invoke(Method.java:508)
    at com.ibm.jvm.dtfjview.CombinedContext.executeDDRInteractiveCommand(CombinedContext.java:260)
    at com.ibm.jvm.dtfjview.CombinedContext.execute(CombinedContext.java:170)
    at com.ibm.jvm.dtfjview.Session.execute(Session.java:819)
    at com.ibm.jvm.dtfjview.Session.execute(Session.java:773)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.executeJdmpviewCommand(ToolsRegistry.java:183)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:107)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.execute(ToolsRegistry.java:88)
    at com.ibm.jvm.dtfjview.tools.ToolsRegistry.recordAndExecute(ToolsRegistry.java:72)
    at com.ibm.jvm.dtfjview.Session.runInteractive(Session.java:747)
    at com.ibm.jvm.dtfjview.Session.run(Session.java:671)
    at com.ibm.jvm.dtfjview.DTFJView.launch(DTFJView.java:52)
    at com.ibm.jvm.dtfjview.DTFJView.main(DTFJView.java:46)
Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/MethodMetaDataConstants.J9TR_SHRINK_WRAP
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData$MethodMetaData_29_V0.getJitRegisterSaveDescription(MethodMetaData.java:570)
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData$MethodMetaData_29_V0.jitAddSpilledRegisters(MethodMetaData.java:435)
    at com.ibm.j9ddr.vm29.j9.stackwalker.MethodMetaData.jitAddSpilledRegisters(MethodMetaData.java:147)
    at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker$JITStackWalker_29_V0.jitWalkStackFrames(JITStackWalker.java:271)
    at com.ibm.j9ddr.vm29.j9.stackwalker.JITStackWalker.jitWalkStackFrames(JITStackWalker.java:102)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:484)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker$StackWalker_29_V0.walkStackFrames(StackWalker.java:165)
    at com.ibm.j9ddr.vm29.j9.stackwalker.StackWalker.walkStackFrames(StackWalker.java:96)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckVMThreadStacks.check(CheckVMThreadStacks.java:66)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.Check.run(Check.java:55)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.CheckCycle.run(CheckCycle.java:469)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.gccheck.GCCheckRunner.run(GCCheckRunner.java:60)
    at com.ibm.j9ddr.vm29.tools.ddrinteractive.commands.GCCheckCommand.run(GCCheckCommand.java:47)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.tryCommand(Context.java:229)
    at com.ibm.j9ddr.tools.ddrinteractive.Context.execute(Context.java:202)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.execute(DDRInteractive.java:385)
    at com.ibm.j9ddr.command.CommandReader.processLine(CommandReader.java:79)
    at com.ibm.j9ddr.tools.ddrinteractive.DDRInteractive.processLine(DDRInteractive.java:360)
    ... 16 more
>
```

**Comment by dmitripivkine** [comment] 2018-10-29 19:32
@pshipton @dnakamura FYI

**Comment by dnakamura** [comment] 2018-10-29 19:53
Given that the exception occurs during a stack walk, and the backtrace mentions `Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/MethodMetaDataConstants.J9TR_SHRINK_WRAP` I would hazard a guess that https://github.com/eclipse/openj9/commit/19913fe106de400428e77e15f8f8aa9facc2d5f1 is the more likely cause of the change
@fjeremic

**Comment by fjeremic** [comment] 2018-10-30 21:32
> Given that the exception occurs during a stack walk, and the backtrace mentions `Caused by: java.lang.NoSuchFieldError: com/ibm/j9ddr/vm29/structure/MethodMetaDataConstants.J9TR_SHRINK_WRAP` I would hazard a guess that [19913fe](https://github.com/eclipse/openj9/commit/19913fe106de400428e77e15f8f8aa9facc2d5f1) is the more likely cause of the change
> @fjeremic

I don't see a reference to `J9TR_SHRINK_WRAP` in the entire codebase. Not sure what `MethodMetaDataConstants` is either so I'm not sure how they relate. Having said that it's almost certainly related to #3291.

**Comment by llxia** [comment] 2018-10-31 22:52
Regarding cmdLineTester_GCCheck, afaik the reason for it not being in the openj9 repo is due to caffeine.jar. The version of caffeine.jar that is used in the test is very old and the new version of caffeine.jar has a completed different structure. To add this test into openj9 repo, we may need to update exisiting test to use the new caffeine.jar.

**Comment by pshipton** [comment] 2018-10-31 23:32
@llxia @smlambert I think we should make it a priority to get a gccheck test running on openj9. Either using the new caffeine.jar or something else. I suspect any app/benchmark would be sufficient as we likely just need something that runs for a little while so gc and jit activity can occur. Let me know if you'd like another issue opened.
@dmitripivkine fyi

**Comment by pshipton** [comment] 2018-10-31 23:37
The same holds true for any other DDR tests that are not yet running on openj9. IBM internal testing is not sufficient as the openj9 DDR implementation works differently. A working DDR is required to diagnose certain types of problems.

**Comment by smlambert** [comment] 2018-10-31 23:56
Agree with all that you have said, and encourage the dev team to dig in.  :)

Lan was polite in saying the phrase "we may need to update existing test".  As I am less polite, the 'we' in that sentence is the Runtimes team.  Good to know that cmdlinetester_GCCheck is considered a great DDR test, also good to understand that DDR works differently in openj9.  

Let's work together to test this 'new feature' properly.

**Comment by pshipton** [comment] 2018-11-01 00:01
@DanHeidinga ^

**Comment by DanHeidinga** [comment] 2018-11-01 14:58
> As I am less polite, the 'we' in that sentence is the Runtimes team.

I hope that "we" is the OpenJ9 community

**Comment by keithc-ca** [comment] 2018-11-01 15:16
FYI, I believe the `NoSuchFieldError` suggests that an older JDK (before `J9TR_SHRINK_WRAP` was removed) was used to examine a newer core file, which is an unsupported scenario.

**Comment by smlambert** [comment] 2018-11-01 15:18
Corrected my statement above... yes of course openj9 team (vs. runtimes team).

**Comment by pshipton** [comment] 2018-11-01 16:55
For the record, @llxia (thanks Lan!) pointed out that the test is running internally on openj9 builds. It's passing on x86, so the test isn't sufficient to catch the problem discovered here.

**Comment by pshipton** [comment] 2018-11-02 20:59
Re-opening since #3518 was reverted.

**Comment by keithc-ca** [comment] 2018-11-06 17:20
Fixed via https://github.com/eclipse/openj9/pull/3554.

**Closed by keithc-ca** 2018-11-06 17:20 UTC
Labels: comp:vm
