### ISSUE TITLE
JITServer: zLinux performance regression

### ISSUE THREAD

**Issue by dchopra001** [eclipse/openj9#9068] opened 2020-04-01 14:51 UTC
When running the AcmeAir benchmark on zLinux, the throughput regresses by 12% when using JITServer to perform compilations. This issue will be used to track the investigation.

**Comment by dchopra001** [comment] 2020-04-01 14:57
A typical iteration of the benchmark is executed as follows:
1. Launch JITServer
2. Launch AcmeAir
3. Run JMeter for 300s to "warm up" (this run will do the bulk of the compilations)
4. Run JMeter for another 300s (any profiles are collected during this round)

AcmeAir is not shutdown in between steps 3 and 4. The reason being that we don't want to spend time loading AOT methods when collecting a profile. The goal of collecting the profile is to compare the performance of the compiled methods (starting once most of the compilations have been completed).

For short, I'll refer to step 3 as the "cold" run, and step 4 as the "warm" run.

**Comment by dchopra001** [comment] 2020-04-01 15:01
To try and narrow the problem down, I first tried to restrict the optimization levels. The results summary is below:

```
-Xjit:initialOptLevel=noOpt,inhibitRecompilation , regression = 3.58%
-Xjit:initialOptLevel=cold,inhibitRecompilation , regression = 9.43%
-Xjit:initialOptLevel=warm,inhibitRecompilation , regression = 11.60%
```

It's clear that most of the regression can be accounted for when restricting optLevel to cold. So I will restrict all future runs to this optLevel and will try to further narrow the problem down.

**Comment by dchopra001** [comment] 2020-04-01 15:09
To make sure that the variance between each iteration is not too high, I ran the benchmark three times with the following JVM options to make sure the data can be reliable:
```
"-XX:+UseJITServer -XX:+UseContainerSupport"
```

1. cold: 10423.4/s, warm: 11634.8/s
2. cold: 10308.5/s, warm: 11560.2/s
3. cold: 10548.2/s, warm: 11668.0/s

Based on the above, the variance is 0.5%..

**Comment by dchopra001** [comment] 2020-04-09 11:53
While looking at profiles, I noticed a big difference in the samples collected for `'java/util/HashMap.get(Ljava/lang/Object;`. Runs with JITServer enabled showed around ~27000 ticks, while runs without JITServer showed ~900 ticks. After reproducing this a few times, I found that the first optimization where the resulting trees diverge is during `basicBlockExtension`. It seems like block frequencies are consistently different and that results in different transformations being executed. One reason block frequencies could be different is because JITServer caches the block frequencies from the client. While this should not make much of a difference when the frequency numbers are large, for small frequency counts (like our case) this can be important.

While discussing these results with @andrewcraik, he suggested collecting logs with `traceBlockFrequencyGeneration` to gain a better understanding of why this might be happening. 

Before moving forward with looking deeper into basicBlockExtension, I decided to perform some more runs to make sure the problem is indeed with this optimization, and clear any doubts before moving forward.

So I did baseline and JITServer enabled runs of AcmeAir with the following options to collect logs and perf info:
```
"-XX:+UseContainerSupport -Xjit:initialOptLevel=cold,inhibitRecompilation,disableTreeSimplification,{'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}\(traceFull,traceCG,log=traceLocal.log,traceBasicBlockExtension,traceBlockFrequencyGeneration,traceNewBlockOrdering\),perfTool"
```

Here are the results:
<img width="208" alt="Screen Shot 2020-04-09 at 7 28 10 AM" src="https://user-images.githubusercontent.com/11260919/78890492-c11c4e80-7a33-11ea-8a7c-89e900c8c586.png">

The average for the base case is `9967.53`, and the variance is 0.032%.
The average for the JITServer case is `9260.72` and the variance is 0.837%.

Based on the average throughput, the regression between the base case and JITServer is 7.091%. 

Additionally, here is the corresponding sample count inside this method for each of the above runs:
<img width="224" alt="Screen Shot 2020-04-09 at 7 34 00 AM" src="https://user-images.githubusercontent.com/11260919/78890981-9bdc1000-7a34-11ea-8151-f90a566eab2c.png">

**Some notes about the above:**

1. To make sure basicBlockExtension is indeed the problem, we need another set of runs like the ones above, but with basicBlockExtension disabled. I'll also need to check to make sure that the compilations looks similar after. Also, the amount of samples collected in both sets of runs must also be much closer. The drawback of disabling basicBlockExtension is that performance in general may be severely reduced. This can be a problem because if throughput reduces significantly, then it can "hide" the actual problem.

2. I also collected trace logs for each of the runs in the tables above. I compared the logs to see what is different between the two logs after basicBlockExtension finishes. Something worth noting is that the optimizations done from one run to another are not always the same. This means that in some runs, the compilations diverged differently as compared to how they diverged in other runs. On top of that, in runs 4 and 7, there was no difference in how basicBlockExtension was performed during the JITServer compile and the base case compile. The post optimization trees, and instruction selection also looked almost identical. However, the samples collected inside the methods are vastly different. Since we see a large amount of samples in `HashMap.get` in the JITServer enabled run, this could imply that perhaps another method is not able to successfully inline this method for remote compiles, and hence we see a lot more samples inside it. One way to verify this theory can be by sequentially limiting the optimizations done on this method until the compiled bodies are consistently similar. If after achieving that, there is still a huge discrepancy in sample count, then it would mean that the problem is not with this method specifically.

**Comment by andrewcraik** [comment] 2020-04-09 12:51
I want to make clear that the issue here is not basicBlockExtension itself - the optimization has no functional problem and is doing the correct thing based on block frequency. The issue is that block frequencies are different enough that we see the opt making different decisions. Please do not characterize this as a basicBlockExtension problem - it is a question of the profiling data at present. The frequencies will also impact other optimizations so the focus here should be on the frequencies and not on an optimization. Once the frequencies are more similar then we should expect the opts to behave in a similar way.

**Comment by andrewcraik** [comment] 2020-04-09 12:52
Why are you running with disableTreeSimplification? That enables a number of optimizations by cleaning up the trees. I would avoid disabling opts unless necessary...

**Comment by dchopra001** [comment] 2020-04-09 12:55
> I want to make clear that the issue here is not basicBlockExtension itself - the optimization has no functional problem and is doing the correct thing based on block frequency

Yes, I don't think there is a problem with the opt itself either. Hence why I am doing more experiments to try and further narrow the problem down. Apologies for the mischaracterization!

**Comment by andrewcraik** [comment] 2020-04-09 13:19
Sounds good - it will be interesting to understand the differences in the profiling between the two configurations. I look forward to seeing the results of your experiments :)

**Comment by dchopra001** [comment] 2020-04-09 17:22
> Why are you running with disableTreeSimplification? That enables a number of optimizations by cleaning up the trees. I would avoid disabling opts unless necessary...

So this was done a while ago when I was investigating the discrepancy in sample count for the following method:
 `java/lang/String.charAtInternal(I[C)C_cold`

The difference in sample count was more than 2X (~50k for JITServer and 22k for local compiles).

Running with `disableTreeSimplification` reduced the sample count gap down to ~10% (~50k for JITServer and 42k for local compiles). However, running with this option still yielded an overall throughput regression. So in order to remove one variable, I decided to stick with this option moving forward for all runs.

In hindsight this may not have been a good decision. I imagine subsequent profiles can be altered because of the absence of this optimization. After my current batch of runs finish, I'll revisit this option and either try to reduce its scope or eliminate it entirely (or at the very least do some due diligence to make sure the profiles don't look severely different with this opt disabled). I'll document the results here.

**Comment by dchopra001** [comment] 2020-04-13 14:54
> To make sure basicBlockExtension is indeed the problem, we need another set of runs like the ones above, but with basicBlockExtension disabled. I'll also need to check to make sure that the compilations looks similar after. Also, the amount of samples collected in both sets of runs must also be much closer

I tried the above approach. Here are the exact options I used:
```
-Xjit:initialOptLevel=cold,inhibitRecompilation,disableTreeSimplification,{'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}\(traceFull,traceCG,log=/home/root/jitServerData/traceLocal.log,disableBasicBlockExtension\),perfTool
```

The throughput data is below:
<img width="208" alt="Screen Shot 2020-04-13 at 10 40 47 AM" src="https://user-images.githubusercontent.com/11260919/79129476-44f77300-7d73-11ea-8588-0f23d312b4aa.png">


The average throughput was 9940.13/s for local JIT and 9075.53/s for Remote JIT (difference of  ~8.70%). Without disabling BBE, the regression was about 7.091%. Overall there isn't a huge loss in performance from our previous runs. So the data from this run should be useful.

Next are the number of samples in each method for Local vs JITServer:
<img width="219" alt="Screen Shot 2020-04-13 at 10 44 48 AM" src="https://user-images.githubusercontent.com/11260919/79129794-d535b800-7d73-11ea-8ebd-96963f04c293.png">

So the average ticks in local compiles is 4127.6 and 89564.2 for JITServer. Compared to the previous result (https://github.com/eclipse/openj9/issues/9068#issuecomment-611487541), these numbers are 4.13 and 3.34 times higher, respectively. 

Since the sample count for both of the runs increased by a similar amount, this implies that disabling BBE had a similar impact in both cases. Moreover, the regression is still there. In the runs without `disableBasicBlockExtension`, there was a ~27x difference in sample count. In these runs, there is a ~22x difference.

Just to make sure, I also took a look at the Post Optimization Trees for all the trace logs generated, and the trees look nearly identical (no structural differences). 

**Conclusion for this experiment**
What the above results prove is that the problem is not related to `basicBlockExtension` or related to the profiling data being different. If that was the case, then we would have seen similar sample counts for both of the methods once basic block extension was disabled(as the “bad optimization” has been removed) . However we did not see such a thing.



I think it’s possible that this `HashMap.get method` isn’t getting inlined by other methods when we use a JITServer to do our compilations. That theory would explain why we are seeing so many samples in profiles where JITServer was used and almost no samples for profiles where a local JIT was used.

For the **next experiment** I am going to keep the same options as above, and run with dontInline={'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}

**Comment by dchopra001** [comment] 2020-04-13 15:07
Results for dontInline={'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'} are below:
Options:
```
-Xjit:initialOptLevel=cold,inhibitRecompilation,disableTreeSimplification,{'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}\(traceFull,traceCG,log=/home/root/jitServerData/traceLocal.log,disableBasicBlockExtension\),perfTool,dontInline={'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}
```

Here’s the throughput data:
<img width="209" alt="Screen Shot 2020-04-13 at 11 00 23 AM" src="https://user-images.githubusercontent.com/11260919/79131088-02836580-7d76-11ea-8f20-29e7ac7567d6.png">

There is a 6.23% difference now, which is the closest we have seen so far.

And here’s the number of samples recorded in the HashMap.get method:
<img width="218" alt="Screen Shot 2020-04-13 at 11 01 33 AM" src="https://user-images.githubusercontent.com/11260919/79131197-32cb0400-7d76-11ea-921c-406f0cc6b05e.png">


The samples are now a lot closer, and we seem to be spending less time in the method in the JITServer version now (not sure why). However the sample counts are now significantly higher. 

Apart from the higher sample count for this method, the profiles and trace files also look similar.

The above results seem to imply that JITServer may not be inlining this method as aggressively as a local JIT does. However before I go further down this path, I'm going to do a few more experiments to try and remove `disableTreeSimplification` from the option set.

**Comment by dchopra001** [comment] 2020-04-14 14:48
Below are the results of running without `disableTreeSimplification`:

`-Xjit` option:
```
-Xjit:initialOptLevel=cold,inhibitRecompilation,{'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}\(traceFull,traceCG,log=/home/root/jitServerData/traceLocal.log\),perfTool"
```

Here's the throughput data:
<img width="212" alt="Screen Shot 2020-04-14 at 10 30 45 AM" src="https://user-images.githubusercontent.com/11260919/79236584-22c92800-7e3b-11ea-9488-99b6ef8b41f4.png">

The average is 10064.74 and 9242.9 for the Local and JITServer runs, respectively. So on average the regression has now become 8.17%. So it seems like the slightly higher throughput has also revealed a higher perf gap.

Meanwhile, here's the sample count data:
<img width="222" alt="Screen Shot 2020-04-14 at 10 36 15 AM" src="https://user-images.githubusercontent.com/11260919/79237150-d4685900-7e3b-11ea-9ad5-82f126e0b26f.png">

The averages are 1040.4 for local and 27922.6 for JITServer. This data is similar to what I had observed with `disableTreeSimplification`. So this confirms that `disableTreeSimplification` was not causing any side effects on the data in this scenario.

**Disabling inlining**
Moving on, I added back the `dontInline` option to the above option set to try and close the sample count gap:
```
-Xjit:initialOptLevel=cold,inhibitRecompilation,{'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}\(traceFull,traceCG,log=/home/root/jitServerData/traceLocal.log\),perfTool,dontInline={'java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;'}"
```

Here's the throughput data:
<img width="211" alt="Screen Shot 2020-04-14 at 10 43 03 AM" src="https://user-images.githubusercontent.com/11260919/79237988-ce26ac80-7e3c-11ea-88aa-88829d0d574b.png">

The average is 9950.3 and 9154.2 for Local and JITServer, respectively. So there is an average regression of 8%. This is close to the previous data. 

Looking at the ticks recorded in the method now, we see some very similar numbers:
<img width="220" alt="Screen Shot 2020-04-14 at 10 45 28 AM" src="https://user-images.githubusercontent.com/11260919/79238257-2c538f80-7e3d-11ea-86cc-e232312cb506.png">

Compared to before, we are seeing much closer numbers. So I think this confirms that JITServer compiles are not inlining this method as aggressively as local JIT compiles. There isn't much of a difference in throughput. However that could be because this problem of inlining is prevalent for many other methods, and so we won't see a difference in throughput until the broader problem has been addressed.

**Comment by dchopra001** [comment] 2020-04-23 11:13
For this latest set of experiments, @andrewcraik recommended looking at the logs of a few methods where the difference in sample counts is the largest. The goal is to try and make sure the frequency count and profiling information is consistent across the two compiles (JITServer vs local compiles). 

For all of these runs, I augmented the check here: 

https://github.com/eclipse/openj9/blob/6fbf525428bc0578d75f4c40549430cb089b2791/runtime/compiler/control/CompilationThread.cpp#L8220-L8228 

to 

```
                     if (!vm->isAOT_DEPRECATED_DO_NOT_USE()
#if defined(JITSERVER_SUPPORT)
                                    && !that->_methodBeingCompiled->isOutOfProcessCompReq()
#endif
```

The reason for this being that in an earlier investigation I found that methods were often not being inlined for JITServer compiles because the byte code cutoff size was set to the smallest possible value (200). To prevent this, and hence to make sure that inlining was as similar as possible between the two runs, I added in this check. This check is also enabled in all future runs below.

The first method I looked at is `java/util/HashMap.hash(Ljava/lang/Object;)I`. This method has one of the highest sample counts in the local compilation profile, and also has a significant difference in sample count between Local vs JITServer compile.

For local compilations, this method has ~72,000 ticks, while for JITServer compilations, this method has ~32,000 ticks. That’s a difference of approximately 55%.

Looking at the inlining data, I see the following sub-opt for inlining in every single run:

 ```
 [     1] O^O INLINER: Inlining qwerty java/util/jar/Attributes$Name.hashCode()I into java/util/HashMap.hash(Ljava/lang/Object;)I with a virtual guard kind=ProfiledGuard type=VftTest partialInline=0
 ```

This sub-opt is not always performed for JITServer though. The frequency count for the tree where this call exists is 9983 (for both JITServer and local compiles). So I don’t think that is the issue here.

After adding in some tracing, I found that the change I had made above was not sufficient. `getDumbInlinerBytecodeSizeCutoff` was still returning 200 (the minimum possible value). This would in turn cause `maxCallSize` to be too small here:
https://github.com/eclipse/omr/blob/68e48bcad2c7ca65ddadeafdc0a5725e1dedf717/compiler/optimizer/Inliner.cpp#L1208-L1213

This would only happen in JITServer runs.

As per @mpirvu’s suggestion, I added the `-Xjit:disableAdaptiveDumbInliner` option to the command line, causing us to take the else path in the code above. With this change, the method was now being inlined 100% of the time for JITServer compiles as well.

The ticks in Local compiles were now about ~31,000. Meanwhile, the ticks in JITServer compiles were ~17,000. So while the magnitude of the ticks was smaller, there was still a 2X difference.

So I'm not sure if continuing to look at this method will be worth it.

**Comment by dchopra001** [comment] 2020-04-23 11:19
Taking a closer look at one of the profiles, I also found a few methods where the difference in sample counts was huge (the magnitude of the sample counts wasn't necessarily always large). Here's the table of those methods below:
![Screen Shot 2020-04-23 at 7 13 25 AM](https://user-images.githubusercontent.com/11260919/80093214-15462900-8532-11ea-8c18-1277ec3f024c.png)

I have already looked at `java/util/HashMap.get(Ljava/lang/Object;)Ljava/lang/Object;` earlier in the investigation. The theory for the large gap there was that perhaps this method wasn't being inlined enough in the JITServer compilations. An entry like `java/lang/Object.<init>()V` might further support this theory. The HeapByteBuffer and ArrayList methods in this table also seem like methods that get inlined a lot for local compilations (hence the extremely low sample count), and don't get inlined as much in the JITServer compiles.

**Comment by andrewcraik** [comment] 2020-04-23 12:51
right so first question is - have you looked at the number of methods compiled at each optimization levels in the JITServer vs local scenarios? That would be one source of this kind of difference. Can you share verbose={compilePerformance,inlining} logs for local compilation and JITServer runs along with the list of method with the biggest delta? We can then check:
a) the methods at each opt level
b) those with massiv esample differences (per above) where was it inlined in the two sets of logs and at what opt levels
We can then figure out what the next thing to look at is.

**Comment by mpirvu** [comment] 2020-04-23 14:38
> have you looked at the number of methods compiled at each optimization levels in the JITServer vs local scenarios?

In these experiments all compilations are performed at cold opt level since the gap is large enough to be analyzed.

**Comment by dchopra001** [comment] 2020-04-23 15:31
>  Can you share verbose={compilePerformance,inlining} logs for local compilation and JITServer runs along with the list of method with the biggest delta?

I'm collecting those right now.

As a side note, I did take a quick look at logs for methods like `Object.<init>` to make sure there wasn't anything in there that was causing an issue. The logs look almost identical.

**Comment by dchopra001** [comment] 2020-04-24 13:20
When specifying `verbose={compilePerformance,inlining}`, I am able to collect a verbose log for a local run that has inlining information (starts with `#INL`).

However, the same options don't yield a similar result for JITServer runs. I'm not sure why. @mpirvu would you happen to know why the same options aren't working for JITServer vlog?

I have attached examples for reference here.
[vlogLocal.txt](https://github.com/eclipse/openj9/files/4529058/vlogLocal.txt)
[vlogRemote.txt](https://github.com/eclipse/openj9/files/4529061/vlogRemote.txt)

**Comment by mpirvu** [comment] 2020-04-24 14:04
The log is produced at the client which does not do the compilation. The INL lines are printed during the compilation (thus at the server) and they are not to the client.
You may try to use vlog options at the server directly.

**Comment by dchopra001** [comment] 2020-04-27 14:44
**Update:**
There was some conflicting data I ran into late week and so I needed to recalibrate and do a larger batch of runs to make sure the information is reliable. 

My Friday night runs are missing data due to disk space issues. I'll be re-running them today to get the missing data and will provide an overall summary after.

**Comment by dchopra001** [comment] 2020-04-28 12:50
Okay, so with `-Xjit:disableAdaptiveDumbInliner` I noticed that the initial difference I reported about `java/lang/Object.<init>()V` was no longer there. I did 10 runs this time to make sure that this was the case. 

Here is the data below:
![Screen Shot 2020-04-28 at 8 08 43 AM](https://user-images.githubusercontent.com/11260919/80485495-85382300-8927-11ea-801f-06a11147a0ba.png)
![Screen Shot 2020-04-28 at 8 09 41 AM](https://user-images.githubusercontent.com/11260919/80485548-a13bc480-8927-11ea-8553-aac6bf2784ae.png)

Here are the exact command line options passed to the Local AcmeAir run:
```
ENV JVM_ARGS="-XX:+UseContainerSupport -Xjit:initialOptLevel=cold,inhibitRecompilation,perfTool,verbose={compilePerformance,inlining},vlog=/home/root/jitServerData/vlogLocal,disableAdaptiveDumbInliner"
```
Here's the options for the JITServer run:
```
ENV JVM_ARGS="-XX:+UseJITServer -XX:JITServerAddress=jitserver_server -XX:+UseContainerSupport -Xjit:initialOptLevel=cold,inhibitRecompilation,perfTool,disableAdaptiveDumbInliner"
```

And here's the options specified to the JITServer itself:
```
ENTRYPOINT ["/opt/ibm/java/jre/bin/jitserver", "-Xjit:verbose={compilePerformance,inlining},vlog=/home/root/jitServerData/vlogRemote"]
```

Here are the top methods that saw JITServer record a significantly higher sample count than local compiles (I ignored the runs where the size difference in the sample count was less than 1000 and tried including data where the sample count was large enough):

![Screen Shot 2020-04-28 at 8 41 26 AM](https://user-images.githubusercontent.com/11260919/80488324-23c68300-892c-11ea-854f-c407e068ee75.png)


The above table is from the first runs (For JITServer and Local compiles) perf report, where the difference in overall throughput was 8.79%.

Here are the corresponding verbose logs for those runs:
[vlogLocal.txt](https://github.com/eclipse/openj9/files/4545791/vlogLocal.txt)
[vlogRemote.txt](https://github.com/eclipse/openj9/files/4545795/vlogRemote.txt)

I also did similar runs to the above but _without_ `-Xjit:disableAdaptiveDumbInliner`. I'll post data related to that shortly.

@andrewcraik Please let me know if you would like to see information related to the other runs as well.

**Comment by dchopra001** [comment] 2020-04-28 13:36
For completeness, I did runs _without_ `-Xjit:disableAdaptiveDumbInliner` to make sure what I was seeing before was reproducible. 

Here is the throughput summary:
![Screen Shot 2020-04-28 at 8 56 51 AM](https://user-images.githubusercontent.com/11260919/80489730-43f74180-892e-11ea-9356-90403bcc367d.png)

And here is the sample count information for `Object.<init`>:
![Screen Shot 2020-04-28 at 8 58 15 AM](https://user-images.githubusercontent.com/11260919/80490126-e6172980-892e-11ea-9bd6-e8a4ddf79e3a.png)

So in this table we see a much more pronounced difference between the two runs. And it's quite consistently reproducible as well. 

The command line options are the same as the one described in https://github.com/eclipse/openj9/issues/9068#issuecomment-620585957, but without the `disableAdaptiveDumbInliner` option.

Here are the top few methods with the largest differences for Run 1 (for both JITServer and Local):

![Screen Shot 2020-04-28 at 9 30 27 AM](https://user-images.githubusercontent.com/11260919/80493075-eb767300-8932-11ea-9f87-bae195308c30.png)

In this table `Object.<init>` is near the top of the list. We also see some similar methods to my previous comment (ex. `ArrayList.*`, `HeapByteBuffer.put*`)

And here are the corresponding vlogs:
[vlogLocal.20200427.145801.12.txt](https://github.com/eclipse/openj9/files/4546063/vlogLocal.20200427.145801.12.txt)

[vlogRemote.20200427.165410.1.txt](https://github.com/eclipse/openj9/files/4546068/vlogRemote.20200427.165410.1.txt)

**Comment by mpirvu** [comment] 2020-04-28 14:29
To summarize your experiments: disabling the adaptiveDumbInliner eliminated the difference in number of ticks for `Object.<init>` (and possibly other methods), but did not affect throughput gap.
I would keep adaptiveDumbInliner disabled for the rest of the runs to eliminate one variable and continue to analyze the remaining methods that show a large discrepancy of ticks. For instance HashMap.put seems like a good candidate. The vlog will show where it was inlined for local compilations. Choose to investigate a method where HashMap.put is not inlined for remote compilations but inlined for local ones.

**Comment by dchopra001** [comment] 2020-04-28 14:43
I see 210 occurrences of `bcsz=13 java\/util\/HashMap.put(Ljava\/lang\/Object;Ljava\/lang\/Object;)Ljava\/lang\/Object;` in the local verbose log and 248 occurrences in the JITServer verbose log.

That's not what I was expecting (i.e the method being inlined more in the JITServer runs). I'll try to dig deeper to identify the methods where it was inlined in both cases. Perhaps the difference there will reveal something.

**Comment by dchopra001** [comment] 2020-09-08 15:29
With the large number of changes that have gone in related to JITServer on Z performance over the last few months (with the last one being https://github.com/eclipse/omr/pull/5518 on September 3rd), I am no longer seeing the same type of performance regression for JITServer.

Here is the throughput data comparing a JITServer client vs OpenJ9 baseline client. There are no restrictions on CPU and memory.

![Screen Shot 2020-09-08 at 11 24 46 AM](https://user-images.githubusercontent.com/11260919/92496256-ea4d3080-f1c5-11ea-96f7-d220b6dd9f39.png)

The steady state throughput average (over 5 runs) for OpenJ9 baseline is 27832.8428.
The steady state throughput average (over 5 runs) for JITServer Client is 27372.227.

The JITServer client lags the baseline case by 1.65%. I believe this is acceptable for JITServer.

**Comment by mpirvu** [comment] 2020-09-08 15:35
> The JITServer client lags the baseline case by 1.65%. I believe this is acceptable for JITServer.

This is really great news! This puts Z on par with X and P platforms.

**Comment by mpirvu** [comment] 2020-09-08 15:36
Could you also please measure the CPU consumed by the client and compare it to non-JITServer?
Thanks

**Comment by dchopra001** [comment] 2020-09-08 15:41
Below is data for JITServer vs Baseline for memory footprint. In both cases the AcmeAir client was run with `--cpus=1 --cpuset-cpus=1`. The JITServer was also run with `--cpus=1 --cpuset-cpus=1`.

![Screen Shot 2020-09-08 at 11 36 24 AM](https://user-images.githubusercontent.com/11260919/92497645-9b07ff80-f1c7-11ea-9566-7dc0f6b3b1f7.png)

Here is the throughput for the above run:
![Screen Shot 2020-09-08 at 11 39 38 AM](https://user-images.githubusercontent.com/11260919/92497941-fdf99680-f1c7-11ea-996c-40955df7c5f0.png)

As is evident, with limited resources the memory usage doesn't have spikes for AcmeAir client using JITServer, and we are able to reach a similar level of throughput.

**Comment by dchopra001** [comment] 2020-09-08 15:52
Finally, here is a plot showing the throughput benefits of using JITServer when the AcmeAir client is restricted to `--cpus=1 --cpuset-cpus=1 --memory=200m`. The JITServer has no restrictions for these runs.

![Screen Shot 2020-09-08 at 11 50 41 AM](https://user-images.githubusercontent.com/11260919/92499188-93e1f100-f1c9-11ea-9b66-eb1d74330b89.png)

Again, the benefit for using JITServer is clear here as the JITServer based client's throughput is 6x higher.

**Comment by dchopra001** [comment] 2020-09-08 15:52
> Could you also please measure the CPU consumed by the client and compare it to non-JITServer?

Okay. Will do this next.

**Comment by dchopra001** [comment] 2020-09-08 20:23
Here's the `TR_PrintCompTime` output at the end of an AcmeAir Client run **without** JITServer (warm run):
JIT: env var TR_PrintCompTime is set to 1
Time spent in compilation thread =0 ms
Time spent in compilation thread =7788 ms
Time spent in compilation thread =8033 ms
Time spent in compilation thread =8850 ms
Time spent in compilation thread =10978 ms
Time spent in compilation thread =13311 ms
Time spent in compilation thread =10347 ms
Time spent in compilation thread =7896 ms

This sums to 67203ms.

Here's the same output but for a client **with** JITServer enabled:
JIT: env var TR_PrintCompTime is set to 1
Time spent in compilation thread =585 ms
Time spent in compilation thread =0 ms
Time spent in compilation thread =982 ms
Time spent in compilation thread =971 ms
Time spent in compilation thread =706 ms
Time spent in compilation thread =1449 ms
Time spent in compilation thread =647 ms
Time spent in compilation thread =630 ms

This totals 5970ms. 

So there's significant improvement in time spent in compilation thread when using JITServer. 

Attaching the results files in this comment.
[CPUUsage.zip](https://github.com/eclipse/openj9/files/5190876/CPUUsage.zip)

**Comment by dchopra001** [comment] 2020-09-08 20:26
I'm also attaching a zip file that includes verbose logs from cold and warm runs when using JITServer (along with the output of the runs). This shows that most methods are either compiled remotely (or AOT loaded in a warm run). So we are indeed using the JITServer when these runs are being executed.
[vlogsRun.zip](https://github.com/eclipse/openj9/files/5190889/vlogsRun.zip)

**Comment by dchopra001** [comment] 2020-09-08 20:42
Note: the above data posted today is based on a build using the following commits:
https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/182efd2724169a1c67f04707ace98106a13dfd45
https://github.com/eclipse/openj9/commit/8001edab752ae4a1d15f59a04f0af99d913f3472
https://github.com/eclipse/omr/commit/5f5f8a142854c9a1b2aa62135b0c6a16dfccbc1f

**Comment by dchopra001** [comment] 2020-09-28 16:33
Since performance is no longer an issue for JITServer on Z, I am closing this issue.

**Closed** 2020-09-28 16:34 UTC
Labels: arch:z, comp:jitserver, perf
