### ISSUE TITLE
Test-sanity.system Mauve gnu.testlet.java.text.CollationElementIterator

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5379] opened 2019-04-05 14:40 UTC
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_390-64_cmprssptrs/305
MauveSingleThreadLoadTest_OpenJ9_0
MauveMultiThreadLoadTest_OpenJ9_0
```
LT  PASS: gnu.testlet.java.text.CollationElementIterator.jdk11: NULLORDER (number 0)
LT  first = {5373952, 82, 0, 0}
LT  PASS: gnu.testlet.java.text.CollationElementIterator.jdk11: first initial test (number 0)
LT  next (2) = {5439488, 83, 0, 0}
LT  PASS: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 2 initial test (number 0)
LT  PASS: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 2 initial test (number 0)
LT  next (3) = {5505024, 84, 0, 0}
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 3 initial test (number 0)
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 3 initial test (number 0)
LT  next (4) = {5570560, 85, 0, 0}
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 4 initial test (number 0)
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 4 initial test (number 0)
LT  next (5) = {5701632, 87, 0, 0}
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 5 initial test (number 0)
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 5 initial test (number 0)
LT  next (6) = {5767168, 88, 0, 0}
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 6 initial test (number 0)
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 6 initial test (number 0)
LT  next (7) = {5832704, 89, 0, 0}
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: next() 7 initial test (number 0)
LT  FAIL: gnu.testlet.java.text.CollationElementIterator.jdk11: no primary difference 7 initial test (number 0)
```

**Comment by pshipton** [comment] 2019-04-05 14:40
@fjeremic

**Comment by fjeremic** [comment] 2019-04-05 14:42
@NigelYiboYu could you please take a look at this one?

**Comment by pshipton** [comment] 2019-04-05 14:50
@fjeremic @NigelYiboYu sorry, I was a little hasty thinking this was a z problem. That is just the fastest platform to test on. 

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86-64_cmprssptrs/217

**Comment by pshipton** [comment] 2019-04-05 14:51
and good to check with @Mesbah-Alam, did the Mauve test change again?

**Comment by fjeremic** [comment] 2019-04-05 14:59
Anything that points to the JIT either? It seems as if the presumption was that this is a JIT bug.

**Comment by NigelYiboYu** [comment] 2019-04-05 15:00
The above x86 test failed in the same test `10:43:05  LT    Test details  = 'Mauve[gnu.testlet.java.text.CollationElementIterator.jdk11]'`

**Comment by pshipton** [comment] 2019-04-05 15:09
> Anything that points to the JIT either? It seems as if the presumption was that this is a JIT bug.

Agreed, checking that in https://github.com/eclipse/openj9/issues/5379#issuecomment-480304987.
Although if the tests didn't change, it will be a JIT bug.

**Comment by pshipton** [comment] 2019-04-05 15:21
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-aix_ppc-64_cmprssptrs/258

**Comment by pshipton** [comment] 2019-04-05 15:36
This build.
```
OpenJ9: 2b707c2
OMR: 54908f0
OpenJDK8: 2b68f66 - openj9-openjdk-jdk8
```

Last "good" build.
```
OpenJ9: 8212220
OMR: c363b21
OpenJDK8: 2b68f66 - openj9-openjdk-jdk8
```

Changes:
https://github.com/eclipse/openj9/compare/8212220...2b707c2
https://github.com/eclipse/openj9-omr/compare/c363b21...54908f0

**Comment by pshipton** [comment] 2019-04-05 15:38
@andrewcraik

**Comment by andrewcraik** [comment] 2019-04-05 15:54
@hzongaro the EA changes landed in this build so maybe they are related - could you have a look?

**Comment by pshipton** [comment] 2019-04-05 16:02
This test material changed (not interesting), but there should be system test material as well, which I haven't yet figured out. 
https://github.com/AdoptOpenJDK/openjdk-tests/compare/1d006fe...0880a4d

**Comment by pshipton** [comment] 2019-04-05 16:03
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-win_x86/214
MauveSingleThreadLoadTest_OpenJ9_0

**Comment by hzongaro** [comment] 2019-04-05 20:06
> @hzongaro the EA changes landed in this build so maybe they are related - could you have a look?
@andrewcraik Will do

**Comment by pshipton** [comment] 2019-04-05 20:26
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-win_x86-64_cmprssptrs/218
MauveSingleThreadLoadTest_OpenJ9_0

**Comment by pshipton** [comment] 2019-04-05 20:30
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_390-64_cmprssptrs/227
MauveSingleThreadLoadTest_OpenJ9_0

**Comment by pshipton** [comment] 2019-04-06 03:49
This continues to fail, I'm not going to keep copying the failures here.

**Comment by pshipton** [comment] 2019-04-07 12:08
There are a lot of test failures (11 last night). Please back out the problematic change if it can't be immediately fixed.

**Comment by hzongaro** [comment] 2019-04-08 16:06
I just wanted to update the current status of this - still trying to get things set up to reproduce the failure.  Once I have that, I'll figure out which change is responsible for these failures.

**Comment by hzongaro** [comment] 2019-04-09 03:58
Gah!  Finally reproduced the failure.  Now trying to isolate where things go wrong.

**Comment by hzongaro** [comment] 2019-04-09 16:02
It looks like the Escape Analysis changes Andrew mention in [his comment](https://github.com/eclipse/openj9/issues/5379#issuecomment-480327886) above are related to this failure.  The affected test seems to pass reliably with that change reverted and fail reliably with it in place, so I will submit a pull request to revert it for now.

**Closed** 2019-04-09 20:44 UTC
Labels: comp:jit, prio:high, test failure
