### ISSUE TITLE
Memory leak at the JITServer

### ISSUE THREAD

**Issue by harryyu1994** [eclipse/openj9#5645] opened 2019-04-30 20:39 UTC
Test setup:
- 4 Acmeair JITaaS Client and 1 JITaaS server:

JITaaS server footprint:
- starts with 12MB
- during rampup, gets up to 900MB
- at steady state, drops down to 180MB

After I shut down the 4 Acmeair JITaaS clients, JITaaS server's footprint stays at 180MB.
The server most likely did not clean up the cached items associated with the clients.

**Comment by dmitry-ten** [comment] 2019-05-01 15:57
I'll investigate.

**Comment by dmitry-ten** [comment] 2019-05-02 15:18
Apparently, this leak has been present for a very long time. Tried out a build from November 11, and it still shows up, even after running `java -Xjit:count=0 -version` once.
However, I don't think it's because the server doesn't clean up cached items. When the client terminates normally, it cleans them up. And even if it didn't, it wouldn't account for even 50% of the delta between the starting and ending memory footprint.
I did find a case when caches don't get cleaned up, however. If the client terminates early, caches will not be cleared. Not sure how to deal with this case. Maybe since we normally create only 1 connection per client now, we can clear caches whenever connection gets destroyed.

**Comment by harryyu1994** [comment] 2019-05-02 18:27
I thought the server has a timer on each client and if it doesn't hear back from the client in a period of time it will clean up the data associated with that client.

What we have now is 1 connection per compilation thread and not per client. So we probably can't clear caches immediately after the connections close down.

**Comment by dmitry-ten** [comment] 2019-05-02 19:14
There is a timeout parameter passed to the stream, but it's never used.
I guess we need to implement timeout handling on both server and client.
I think I'll do that first, because that will solve one potential memory leak, while I still don't know where the original leak comes from.

**Comment by mpirvu** [comment] 2019-11-20 10:45
Running 10 acmeair experiments in succession (thus 20 JVM clients in total) the RSS at the server grew from 44596 KB  to 570556 KB. Virtual size grew at a smaller rate 5.6G-->6G
`30421 mpirvu    20   0 5615996  44596  18684 S   0.4  0.3   0:02.73 java`
to
`30421 mpirvu    20   0 6008420 570556  26428 S   0.3  3.5   8:12.60 java`
I have yet to determine if this is a true memory leak.

**Comment by mpirvu** [comment] 2019-11-20 11:08
After one more acmeair run the memory stats are:
`30421 mpirvu    20   0 6011504 617876  26428 S   0.3  3.8   9:02.62 java`
so virtual and physical memory grew again by 3M and 47MB respectively.
The vlog for the server shows that client disconnects nicely and its session data should have been deleted:
```
#JITServer: compThreadID=1 has failed to compile
#JITServer: Stream connection terminated by JITClient on stream 00007F0A05961078 while compThreadID=1 was reading the compilation request: Connection terminated at JITClient's request
#JITServer: compThreadID=0 has failed to compile
#JITServer: compThreadID=1 did an early abort
#JITServer: Stream connection terminated by JITClient on stream 00007F090B3E8E88 while compThreadID=0 was reading the compilation request: Connection terminated at JITClient's request
#JITServer: compThreadID=0 did an early abort
#JITServer: Stream connection terminated by JITClient on stream 00007F090B3E1340 while compThreadID=2 was reading the compilation request: Connection terminated at JITClient's request
#JITServer: compThreadID=2 did an early abort
#JITServer: Server received request for stream 00007F090B3E1340
#JITServer: Stream client session terminated by JITClient on compThreadID=0: JITClient session 12931123646865995588 terminated at JITClient's request
#JITServer: Message to delete Client (12931123646865995588) received. Data for client deleted
#JITServer: compThreadID=0 did an early abort
```

**Comment by mpirvu** [comment] 2019-11-20 13:38
After yet another run there is a 67MB increase in virtual memory and 45MB in RSS:
`30421 mpirvu    20   0 6079096 663172  26428 S   0.3  4.1  10:11.41 java`

This deserves an investigation

**Comment by mpirvu** [comment] 2019-11-20 14:07
Javacore at the server shows 61MB of persistent memory, 14KB of code cache (I wonder why not 0) and 0MB of data cache. We must be consuming heap memory allocated with malloc.

**Comment by mpirvu** [comment] 2019-11-21 16:29
A started a more systematic set of experiments where I start/stop liberty repeatedly (no load applied)
```
RSS    VirtualSize (KB)
34.1   1286   ==> JITServer just started
70.1   1377   ==> After first liberty start/stop sequence
78.5   1387   ==> After second liberty start/stop sequence
97.0   1379
...
After another 100 runs
501.1  1690
```
Looking at the javacores I see that the only component that increases is persistent memory at about 1M per run. After 105 runs I have 128MB of persistent memory being utilized

**Comment by mpirvu** [comment] 2019-11-21 16:39
Another observation is that the code cache grows, though very little ==> 14K after 105 runs. Could it be that we do some cold allocations that are not cleaned up?

**Comment by mpirvu** [comment] 2019-11-23 22:26
In theory, tracking persistent memory can be done by enabling this env var: `TR_PrintPersistentMem`
```
   static char * printPersistentMem = feGetEnv("TR_PrintPersistentMem");
   if (printPersistentMem)
      {
      if (trPersistentMemory)
         trPersistentMemory->printMemStats();
      }
```
Then, at shutdown the JVM will print a long table of allocations for each data type that is tracked. The tracking is done in this piece of code:
```
void * allocatePersistentMemory(size_t const size, ObjectType const ot = UnknownType) throw()
      {
      _totalPersistentAllocations[ot] += size;
      void * persistentMemory = _persistentAllocator.get().allocate(size, std::nothrow);
      return persistentMemory;
      }
```
This approach has three problems:
1) Only allocations are tracked, deallocations are not. This is not useful if a particular data type is allocated and deallocated a lot.
2) Some data types are not tracked and they appear in the "unknown" bucket. In fact the unknown bucket will show most of the allocations.
3) When using C++ STL, the allocations do not go through the routine shown above, but they go directly to the persistent allocator defined in `/runtime/compiler/env/PersistentAllocator.cpp`

Problem (1) above can be solved in the following way:
- Add a new field to the `Block` structure which defines the header of an allocation block. This new field can be used to store the data type.
- Pass the data type to the allocator by using the `hint` parameter of the `allocate()` function.
At this point when deallocating an object we can substract from the appropriate bucket.

However, our biggest problem is (3) because JITServer does many allocations using STL. To address this I used a different approach:
1) In the allocator I am obtaining the stack trace and save it into a hashtable where the address of the allocated block is the key
2) In the deallocator I am deleting from my hashtable
3) At shutdown I am traversing the hashtable and print all the addresses that have allocated but not deallocated together with their stack traces. This way I can tell where the culprit allocation originated from

**Comment by mpirvu** [comment] 2019-11-24 02:21
Using the technique described above I discovered a few inefficiencies in the code related to for loops of the form:
`for (auto it : collection)`
The iterator over the collection is actually a copy of an element from the collection. If the element is simple (like a pointer) then there is no problem, but if the element is a complex data structure like `ClassInfo` then the constructor of that element is going to be invoked and it's going to spend a lot of time creating objects. Moreover, if we want to erase something from that element, we may delete from the copy of the element not from the element itself which is plain wrong. The solution is to use a reference like this: `for (auto& it : collection)`

**Comment by mpirvu** [comment] 2019-11-24 02:25
I also observed that some runtime assumptions that are created during compilation are created at the server using persistent memory. We need to collect and pass these runtime assumptions to the client and then deallocate the memory used for them. A few relevant stack traces related to leaked allocations:

We leak something in OMR:compilation constructor: It's the sentinel for the runtimeAsumptions created during compilation
```
OMR::Compilation::Compilation(int, OMR_VMThread*, TR_FrontEnd*, TR_ResolvedMethod*, TR::IlGenRequest&, TR::Options&, TR::Region&, TR_Memory*, TR_OptimizationPlan*)
J9::Compilation::Compilation(int, J9VMThread*, TR_FrontEnd*, TR_ResolvedMethod*, TR::IlGenRequest&, TR::Options&, TR::Region&, TR_Memory*, TR_OptimizationPlan*, TR_RelocationRuntime*)
TR::CompilationInfoPerThreadBase::wrappedCompile(J9PortLibrary*, void*)
/home/mpirvu/FullVM/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/lib/amd64/compressedrefs/libj9prt29.so(+0x1fdb3) [0x7f7a678a9db3]
TR::CompilationInfoPerThreadBase::compile(J9VMThread*, TR_MethodToBeCompiled*, J9::J9SegmentProvider&)
```

```
TR_RedefinedClassRPicSite::make(TR_FrontEnd*, TR_PersistentMemory*, unsigned long, unsigned char*, unsigned int, OMR::RuntimeAssumption**)
J9::CodeGenerator::jitAddPicToPatchOnClassRedefinition(void*, void*, bool)
TR::X86CallSnippet::emitSnippetBody()
J9::Snippet::emitSnippet()
OMR::CodeGenerator::emitSnippets()
```
```
TR_PatchJNICallSite::make(TR_FrontEnd*, TR_PersistentMemory*, unsigned long, unsigned char*, OMR::RuntimeAssumption**)
J9::CodeGenerator::registerAssumptions()
OMR::CodeGenPhase::performProcessRelocationsPhase(TR::CodeGenerator*, TR::CodeGenPhase*)
OMR::CodeGenPhase::performAll()
OMR::CodeGenerator::generateCode()
```

**Comment by mpirvu** [comment] 2019-11-24 02:26
We also leak memory in whatever the idiom recognition allocates with persistent memory:
```
TR_Memory::allocateMemory(unsigned long, TR_AllocationKind, TR_MemoryBase::ObjectType)
createIdiomArrayAddressIndexTreeInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
createIdiomArrayAddressInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
createIdiomArrayStoreInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, int, TR::DataType, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
makeCopyingTROxGraph(TR::Compilation*, int, int)
```
```
TR_Memory::allocateMemory(unsigned long, TR_AllocationKind, TR_MemoryBase::ObjectType)
createIdiomArrayAddressInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
createIdiomArrayStoreInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, int, TR::DataType, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
makeCopyingTROxGraph(TR::Compilation*, int, int)
TR_CISCGraph::makePreparedCISCGraphs(TR::Compilation*)
```
```
TR_MemoryBase::jitPersistentAlloc(unsigned long, TR_MemoryBase::ObjectType)
TR_PCISCGraph::addNode(TR_CISCNode*, TR::Block*, TR::TreeTop*, TR::Node*)
createIdiomArrayAddressInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
makeMemCpyByteToCharGraph(TR::Compilation*, int)
TR_CISCGraph::makePreparedCISCGraphs(TR::Compilation*)
```
TR_MemoryBase::jitPersistentAlloc(unsigned long, TR_MemoryBase::ObjectType)
TR_PCISCNode::addParent(TR_CISCNode*)
createIdiomIOP2VarInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
createIdiomDecVarInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
createIdiomDecVarInLoop(TR_PCISCGraph*, int, int, TR_PCISCNode*, TR_PCISCNode*, TR_PCISCNode*)
```

**Comment by mpirvu** [comment] 2019-11-25 20:38
Another memory leak happens due to this code:
```

            uintptrj_t methodStart = TR::Compiler->mtd.bytecodeStart(method);
            TR_IPBCDataCallGraph *entry = new TR_IPBCDataCallGraph(methodStart + bcIndex);
            CallSiteProfileInfo *csInfo = entry->getCGData();
            csInfo->_weight[0] = count;
            // TODO: we should probably add some class as well
            if (methodInfoPresentInPersistent)
               clientData->cacheIProfilerInfo(method, bcIndex, entry);
            else
               compInfoPT->cacheIProfilerInfo(method, bcIndex, entry); ==> entries for this must be allocated using heap memory

```
The error is that we allocate an entry with persistent memory but then attach it to the per compilation cache which is not destroyed explicitly.

**Comment by mpirvu** [comment] 2019-11-28 17:33
By instrumenting the code I found another memory leak, this time when using system heap memory not persistent memory. The stack trace associated with it is something like this:
```
operator new(unsigned long)
Unknown
std::__detail::_Hash_node<std::pair<TR_ResolvedMethodKey const, TR_ResolvedMethodCacheEntry>, true>* std::__detail::_Hashtable_alloc<TR::typed_allocator<std::__detail::_Hash_node<std::pair<TR_ResolvedMethodKey const, TR_ResolvedMethodCacheEntry>, true>, TR::Region&> >::_M_allocate_node<std::pair<TR_ResolvedMethodKey const, TR_ResolvedMethodCacheEntry> >(std::pair<TR_ResolvedMethodKey const, TR_ResolvedMethodCacheEntry>&&)
TR::CompilationInfoPerThreadRemote::cacheResolvedMethod(TR_ResolvedMethodKey, TR_OpaqueMethodBlock*, unsigned int, std::tuple<TR_ResolvedJ9JITServerMethodInfoStruct, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&)
TR_ResolvedJ9JITServerMethod::getResolvedSpecialMethod(TR::Compilation*, int, bool*)
J9::SymbolReferenceTable::findOrCreateSpecialMethodSymbol(TR::ResolvedMethodSymbol*, int)
TR_J9ByteCodeIlGenerator::genInvokeSpecial(int)
```
I have many examples, but they all have `TR::CompilationInfoPerThreadRemote::cacheResolvedMethod` in common.
I looked at the implementation and it looks fine. I think that the problem is related to how memory is allocated for std::string.The "value" stored in `resolvedMethodInfoMap` is of type:
```
struct
TR_ResolvedMethodCacheEntry
   {
   TR_OpaqueMethodBlock *method;
   uint32_t vTableSlot;
   TR_ResolvedJ9JITServerMethodInfo methodInfo;
   };
```
`TR_ResolvedJ9JITServerMethodInfo` contains 3 std strings: 
`using TR_ResolvedJ9JITServerMethodInfo = std::tuple<TR_ResolvedJ9JITServerMethodInfoStruct, std::string, std::string, std::string>;
`
I think that while the std::string itself is allocated using scratch memory, the backing array of characters is allocated using system heap memory. Since we don't call the destructors when clearing these per-compilation caches, such memory leaks.

**Comment by mpirvu** [comment] 2019-12-02 22:02
Fix for this latest problem will be provided in #7937

**Comment by mpirvu** [comment] 2019-12-02 22:07
After all the fixes, I repeated the experiment from https://github.com/eclipse/openj9/issues/5645#issuecomment-557164118
After 3 Liberty start-ups the memory stats were:
RSS=78,356 KB  VSZ=1,313,804 KB
After another 100 Liberty start-ups the memory stats were:
RSS=82,164 KB  VSZ=1,316,888 KB.
The extra memory is due to 3 persistent memory segments which could very well be due to fragmentation (the JIT never completely frees persistent memory, but keeps it in its internal freed block lists).

**Closed** 2019-12-03 13:24 UTC
Labels: comp:jitserver
