### ISSUE TITLE
Open source wildfly-14.0.0.Beta1-SNAPSHOT fails to build with OpenJ9 and test fails with OpenJDK hotspot

### ISSUE THREAD

**Issue by suman-mitra** [eclipse/openj9#2215] opened 2018-06-18 05:30 UTC
wildfly-14.0.0.Beta1-SNAPSHOT build failed with  OpenJDK_OpenJ9 and tests failed with OpenJDK_hotspot

1. With OpenJDK_OpenJ9 nightly build (OpenJDK8-OPENJ9_x64_Linux_20180613) failed while Building due failure in below integration test

 org.jboss.as.test.integration.ee.concurrent.DefaultContextServiceServletTestCase

2. With OpenJDK8 Hotspot nightly build (OpenJDK8_x64_Linux_20180614) , it was able to build, but while executing tests below tests failed

org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase
org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase
org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase
org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase
org.jboss.as.test.clustering.cluster.web.persistence.DatabasePersistenceWebFailoverTestCase

**Comment by suman-mitra** [comment] 2018-06-18 05:31
1. With OpenJDK8-OPENJ9_x64_Linux_20180613, failed while building

   testcase :- org.jboss.as.test.integration.ee.concurrent.DefaultContextServiceServletTestCase

^[[31m13:02:20,979 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /war-example/simple: javax.servlet.ServletException: java.lang.ClassNotFoundException: org.wildfly.extension.undertow.security.AccountImpl$AccountPrincipal
        at org.jboss.as.test.integration.ee.concurrent.DefaultContextServiceTestServlet.doGet(DefaultContextServiceTestServlet.java:74)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
        at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction$$Lambda$346.000000005C0F91B0.call(Unknown Source)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$347.000000005C01DC80.call(Unknown Source)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction$$Lambda$347.000000005C01DC80.call(Unknown Source)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
        at java.lang.Thread.run(Thread.java:812)

**Comment by suman-mitra** [comment] 2018-06-18 05:32
2.  With OpenJDK8 Hotspot (OpenJDK8_x64_Linux_20180614) , below 5 tests failed :-
org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase
org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase
org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase
org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase
org.jboss.as.test.clustering.cluster.web.persistence.DatabasePersistenceWebFailoverTestCase

**Comment by suman-mitra** [comment] 2018-06-18 05:38
-------------------------------------------------------------------------------
Test set: org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 16.401 s <<< FAILURE! - in org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase
testSingletonService(org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase)  Time elapsed: 16.397 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertFalse(Assert.java:64)
        at org.junit.Assert.assertFalse(Assert.java:74)
        at org.jboss.as.test.clustering.cluster.singleton.SingletonPolicyServiceTestCase.testSingletonService(SingletonPolicyServiceTestCase.java:147)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)

**Comment by suman-mitra** [comment] 2018-06-18 05:38
-------------------------------------------------------------------------------
Test set: org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.82 s <<< FAILURE! - in org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase
test(org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase)  Time elapsed: 0.766 s  <<< ERROR!
java.lang.NullPointerException
        at org.jboss.as.test.clustering.cluster.web.authentication.FormAuthenticationWebFailoverTestCase.test(FormAuthenticationWebFailoverTestCase.java:135)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:129)

**Comment by suman-mitra** [comment] 2018-06-18 05:39
Test set: org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.569 s <<< FAILURE! - in org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase
test(org.jboss.as.test.clustering.cluster.web.expiration.CoarseSessionExpirationTestCase)  Time elapsed: 0.569 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.jboss.as.test.clustering.cluster.web.expiration.SessionExpirationTestCase.test(SessionExpirationTestCase.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:142)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:129)

**Comment by suman-mitra** [comment] 2018-06-18 05:39
-------------------------------------------------------------------------------
Test set: org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.579 s <<< FAILURE! - in org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase
test(org.jboss.as.test.clustering.cluster.web.expiration.FineSessionExpirationTestCase)  Time elapsed: 0.57 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.jboss.as.test.clustering.cluster.web.expiration.SessionExpirationTestCase.test(SessionExpirationTestCase.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)

**Comment by suman-mitra** [comment] 2018-06-18 05:40
-------------------------------------------------------------------------------
Test set: org.jboss.as.test.clustering.cluster.web.persistence.DatabasePersistenceWebFailoverTestCase
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 27.151 s <<< FAILURE! - in org.jboss.as.test.clustering.cluster.web.persistence.DatabasePersistenceWebFailoverTestCase
test(org.jboss.as.test.clustering.cluster.web.persistence.DatabasePersistenceWebFailoverTestCase)  Time elapsed: 20.323 s  <<< FAILURE!
java.lang.AssertionError: expected:<200> but was:<500>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.jboss.as.test.clustering.ClusterHttpClientUtil.establishTopology(ClusterHttpClientUtil.java:69)
        at org.jboss.as.test.clustering.ClusterHttpClientUtil.establishTopology(ClusterHttpClientUtil.java:58)
        at org.jboss.as.test.clustering.ClusterHttpClientUtil.establishTopology(ClusterHttpClientUtil.java:52)
        at org.jboss.as.test.clustering.cluster.web.AbstractWebFailoverTestCase.establishTopology(AbstractWebFailoverTestCase.java:360)
        at org.jboss.as.test.clustering.cluster.web.AbstractWebFailoverTestCase.testFailover(AbstractWebFailoverTestCase.java:120)
        at org.jboss.as.test.clustering.cluster.web.AbstractWebFailoverTestCase.testGracefulUndeployFailover(AbstractWebFailoverTestCase.java:112)
        at org.jboss.as.test.clustering.cluster.web.AbstractWebFailoverTestCase.test(AbstractWebFailoverTestCase.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:379)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:60)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:96)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:85)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:143)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:114)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:67)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:53)

**Comment by DanHeidinga** [comment] 2018-06-18 15:56
@suman-mitra If you use \`\`\` before and after long stacktraces they are easier to read.

**Comment by DanHeidinga** [comment] 2018-06-18 15:58
> java.lang.ClassNotFoundException: org.wildfly.extension.undertow.security.AccountImpl$AccountPrincipal

The first issue looks like a missing class.  Is there something else in the logs related to this class?  Is the configuration correct (missing jar, etc)?

For the test failures, can you provide links to the test source?  Without knowing why the assertion failed there isn't much to look at.

**Comment by suman-mitra** [comment] 2018-06-18 17:14
@DanHeidinga , yes the first issue looks like a missing class. But this is seen only when we build wildfly using OpenJ9 nightly build. And the same issue is not seen when we run using OpenJDK Hotspot nightly build. Infact , with OpenJDK Hotspot build wildfly is built without any failure.

Apologies, for not sharing the steps to recreate.  Please find them below 

1. git clone https://github.com/wildfly/wildfly.git
2. cd wildfly
3. ./build.sh   ----> Here it fails (with ClassNotFoundException) to build with OpenJ9 build, passes with OpenJDK Hotspot  build.
4. ./mvnw install -DallTests --> It runs all the tests and 5 of the tests fail with Assertion failure with OpenJDK hotspot build.

The above can also be run from 
https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/thirdparty_containers/wildfly

**Comment by DanHeidinga** [comment] 2018-06-22 04:48
Are you able to generate java / system cores from the failure?  Try an option like `-Xdump:java+system:events=throw+systhrow,filter=java/lang/ClassNotFoundException,msg_filter=org.wildfly.extension.undertow.security.AccountImpl$AccountPrincipal`

**Comment by suman-mitra** [comment] 2018-06-23 11:06
I'm unable to upload the dumps since there is a restriction on file size. It doesn't allow to upload anything more than 10 MB.  For now I'm uploading the javacore files. Do let me know how to pass on the dump files ...Thanks !!

[javacore.zip](https://github.com/eclipse/openj9/files/2129858/javacore.zip)

**Comment by pshipton** [comment] 2018-06-25 18:16
@suman-mitra There is no requirement for diagnostic files to be transferred in the open. You can use any file sharing mechanism such as box, or an IBM internal share.

**Comment by suman-mitra** [comment] 2018-06-26 05:54
I've sent a box link with the dumps uploaded there

**Comment by sshamaia** [comment] 2018-07-27 10:46
The build issue is fixed with  using the JVM command line option
-Dcom.ibm.enableClassCaching=false
and build succeeds.

Running all tests results in failure in
WildFly Test Suite: Integration - Basic
org.jboss.as.test.integration.ejb.transaction.bmt.timeout.StatelessTimeoutTestCase fails.
The exception is attached
[kafka_error.log](https://github.com/eclipse/openj9/files/2235499/kafka_error.log)

**Comment by pshipton** [comment] 2018-07-27 11:42
While this is great news, I don't understand. com.ibm.enableClassCaching isn't a property that OpenJ9 recognizes. Is there any typo with the name? Or is this a system property that wildfly uses?

**Comment by sshamaia** [comment] 2018-07-27 12:35
Am  not sure how this worked , but i have confirmed that removing this option causes the build failure.
I got this option while looking for similar issues and referring from https://issues.jboss.org/browse/WFLY-5588
But am not clear how this is resolving this issue though .. Is there any tracing i can enable to check if this option is getting used in wildfly

**Comment by pshipton** [comment] 2018-07-27 12:48
I just didn't search widely enough. I found the property in the extensions code. It controls the OpenJ9 added Last User Defined Class Loader optimization in ObjectInputStream.

**Closed** 2020-01-20 20:23 UTC
Labels: svtRaised, userRaised
