### ISSUE TITLE
Arm64 linux nightly builds fail to compile BUILD_JIGSAW_TOOLS

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8565] opened 2020-02-12 16:44 UTC
Nightly builds of arm64 linux (XL) on jdk11 have been failing for a few days now, couldn't see another issue on this but may be known as this is a WIP item.

Most recent build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/77/console

Last passing build:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+1-202002051925)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-81782de72, JRE 11 Linux aarch64-64-Bit 20200205_70 (JIT enabled, AOT enabled)
OpenJ9   - 81782de72
OMR      - d77a173dd
JCL      - 058070839f based on jdk-11.0.7+1)
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/70/console

Output:
```
Compiling 4 files for BUILD_JIGSAW_TOOLS
Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000001
Handler1=00004000196CB6A4 Handler2=000040001983F5A0
R0=000040001C0B2A00 R1=000040001C14F230 R2=00004000195CCC70 R3=000040001A41D5D8
R4=000000000000007B R5=0000000000000000 R6=00004000195CC6A0 R7=0000400078098A98
R8=00004000468B1244 R9=000040001C0B2A98 R10=000000000000A80F R11=4A2F74696A2F6D62
R12=69467463656A626F R13=00000003E8000000 R14=0010ECF53BA3A505 R15=0000847D1DA46BA2
R16=00004000197A0018 R17=00004000191C8368 R18=0000000000000000 R19=000040001C0B2A00
R20=000040001C0B26C8 R21=000040001C142C00 R22=0000000000000045 R23=000000003DD8B445
R24=00004000197A0ED8 R25=00004000464B61D8 R26=00004000195CCE70 R27=00004000196B82A0
R28=000040001C0B2A00 R29=0000000000000000 R30=000040001A1D134C R31=00004000195CCBD0
PC=00004000468B12DC SP=00004000195CCBD0 PSTATE=0000000020000000
V0 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
V1 40574b3568cfceac (f: 1758449280.000000, d: 9.317513e+01)
V2 3ff67f79221879fc (f: 572029440.000000, d: 1.406121e+00)
V3 4030fce35ec42420 (f: 1589912576.000000, d: 1.698784e+01)
V4 3d78293cd06cc908 (f: 3496790272.000000, d: 1.373399e-12)
V5 3fe6c1f480000000 (f: 2147483648.000000, d: 7.111762e-01)
V6 bed0000000000000 (f: 0.000000, d: -3.814697e-06)
V7 3c7654f9006a8474 (f: 6980724.000000, d: 1.936986e-17)
V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V16 3c80327c8035423a (f: 2150973952.000000, d: 2.809768e-17)
V17 3fd5d03e1bd5e814 (f: 467003424.000000, d: 3.408351e-01)
V18 3d2ef35793c76730 (f: 2479318784.000000, d: 5.497923e-14)
V19 4031542457337bc0 (f: 1462991872.000000, d: 1.732868e+01)
V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V31 0000000000000000 (f: 0.000000, d: 0.000000e+00)

Compiled_method=jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;
Target=2_90_20200212_77 (Linux 4.14.0-115.10.1.el7a.aarch64)
CPU=aarch64 (4 logical CPUs) (0x1d9710000 RAM)
----------- Stack Backtrace -----------
(0x000040001985CC48 [libj9prt29.so+0x3cc48])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/02/12 15:53:11 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/core.20200212.155311.25139.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/core.20200212.155311.25139.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/javacore.20200212.155311.25139.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/javacore.20200212.155311.25139.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/Snap.20200212.155311.25139.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/Snap.20200212.155311.25139.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/jitdump.20200212.155311.25139.0004.dmp'
JVMDUMP010I JIT dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/make/jitdump.20200212.155311.25139.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done] Error 1
ExplodedImageOptimize.gmk:40: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done' failed
make/Main.gmk:351: recipe for target 'exploded-image-optimize' failed
gmake[2]: *** [exploded-image-optimize] Error 1

ERROR: Build failed for targets 'product-images legacy-jre-image test-image' in configuration 'linux-aarch64-normal-server-release' (exit code 2) 
Stopping sjavac server
```

**Comment by 0xdaryl** [comment] 2020-02-12 16:56
@knn-k FYI

**Comment by knn-k** [comment] 2020-02-13 01:19
No aarch64-specific changes have been applied to OpenJ9 and OMR repositories recently.  I wonder what causes the crash.

**Comment by knn-k** [comment] 2020-02-13 14:32
I cannot reproduce the crash in my build environments, neither native aarch64 Linux nor cross-build on x86-64 Linux.

**Comment by adam-thorpe** [comment] 2020-02-13 15:05
@sxa555 could this be related to the gcc 7.5 changes? All of those have been sorted as far as I'm aware but this cropped up around then

**Comment by knn-k** [comment] 2020-02-14 02:13
This build at ci.eclipse.org went successful.
https://ci.eclipse.org/openj9/job/Build_JDK11_aarch64_linux_xl_Personal/115/

**Comment by pshipton** [comment] 2020-02-14 03:53
I don't know what compiler aarch64 uses, we didn't try to move it to gcc 7.5

**Comment by knn-k** [comment] 2020-02-18 03:40
Builds #80 and #83 went successful.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/83/console
#81 failed at "Compiling 4 files for BUILD_JIGSAW_TOOLS".

**Comment by M-Davies** [comment] 2020-04-08 08:32
Seen again on a jdk11/aarch64 build
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/264/console
```
Compiling 4 files for BUILD_JIGSAW_TOOLS
Unhandled exception
Type=Illegal instruction vmState=0x00000000
J9Generic_Signal_Number=00000048 Signal_Number=00000004 Error_Value=00000000 Signal_Code=00000001
Handler1=00004000355CE268 Handler2=0000400035749B28
R0=0000000000434F00 R1=0000000000465430 R2=00004000354CCC80 R3=00004000363DD6B8
R4=00000000000007CD R5=0000000000000000 R6=00004000354CC6A0 R7=0000400074098FE8
R8=00004000428B1224 R9=0000000000434F98 R10=000000000000A80F R11=4A2F74696A2F6D62
R12=69467463656A626F R13=00000003E8000000 R14=0007C62837B09C48 R15=000102452163A494
R16=00004000356B0018 R17=00004000350C8368 R18=0000000000000000 R19=0000000000434F00
R20=0000000000434C78 R21=0000000000458D00 R22=0000000000000045 R23=000000003DD8B445
R24=0000400036640290 R25=00000000FFC03FE0 R26=00004000354CCE80 R27=00004000355BAAC8
R28=0000000000434F00 R29=0000000000000000 R30=0000400036169A38 R31=00004000354CCBE0
PC=00004000428B12B4 SP=00004000354CCBE0 PSTATE=0000000020000000
V0 0000000042ba5bfb (f: 1119509504.000000, d: 5.531112e-315)
V1 000000003e3ab283 (f: 1044034176.000000, d: 5.158214e-315)
V2 000000003a52c3a3 (f: 978502592.000000, d: 4.834445e-315)
V3 00000000be9d6d20 (f: 3197988096.000000, d: 1.580016e-314)
V4 000000003d5324be (f: 1028859072.000000, d: 5.083239e-315)
V5 00000000396d7337 (f: 963474240.000000, d: 4.760195e-315)
V6 0000000041c80000 (f: 1103626240.000000, d: 5.452638e-315)
V7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V16 000040003616979c (f: 907450240.000000, d: 3.476723e-310)
V17 0000400035c62680 (f: 902178432.000000, d: 3.476722e-310)
V18 0000400035c1b658 (f: 901887552.000000, d: 3.476722e-310)
V19 0000400035c624a0 (f: 902177920.000000, d: 3.476722e-310)
V20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
V31 0000000000000000 (f: 0.000000, d: 0.000000e+00)

Compiled_method=jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;
Target=2_90_20200407_264 (Linux 4.14.0-115.10.1.el7a.aarch64)
CPU=aarch64 (4 logical CPUs) (0x1d9660000 RAM)
----------- Stack Backtrace -----------
(0x0000400035767548 [libj9prt29.so+0x37548])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2020/04/08 00:02:28 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/core.20200408.000228.8457.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/core.20200408.000228.8457.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/javacore.20200408.000228.8457.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/javacore.20200408.000228.8457.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/Snap.20200408.000228.8457.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/Snap.20200408.000228.8457.0003.trc
JVMDUMP007I JVM Requesting JIT dump using '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/jitdump.20200408.000228.8457.0004.dmp'
JVMDUMP010I JIT dump written to /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/make/jitdump.20200408.000228.8457.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
ExplodedImageOptimize.gmk:40: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done' failed
gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done] Error 1
make/Main.gmk:351: recipe for target 'exploded-image-optimize' failed
gmake[2]: *** [exploded-image-optimize] Error 1
```
on `build-linaro-centos76-armv8-2`

**Comment by knn-k** [comment] 2020-04-08 08:55
Illegal instruction in `jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;` again.
Is there a core file available?

**Comment by knn-k** [comment] 2020-04-08 09:23
Another question: Which JDK do you use as the boot-jdk for the configure option in these builds?

**Comment by M-Davies** [comment] 2020-04-08 10:52
@knn-k Boot jdk is in the console output 
```
configure: Found potential Boot JDK using configure arguments
checking for Boot JDK... /usr/lib/jvm/jdk-10.0.2+13
checking Boot JDK version... openjdk version "10.0.2" 2018-07-17 OpenJDK Runtime Environment AdoptOpenJDK (build 10.0.2+13) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 10.0.2+13, mixed mode) 
```

**Comment by knn-k** [comment] 2020-04-08 10:58
Thank you for the information.  The boot JDK is Hotspot JDK 10, and it has nothing to do with the crash.

I am running the `Compiling 4 files for BUILD_JIGSAW_TOOLS` part of the build repeatedly in my local machine, but I haven't seen the crash yet after 15 trials.

**Comment by M-Davies** [comment] 2020-04-08 10:59
> Illegal instruction in `jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;` again.
> Is there a core file available?

Ref https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1586343408050600?thread_ts=1586343264.050400&cid=C09NW3L2J, the core files are saved on builds but you need access to the machine to obtain them. You can request access to a specific machine at  https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/

**Comment by knn-k** [comment] 2020-04-08 11:25
What is the name of the host of the last failing build?

**Comment by knn-k** [comment] 2020-04-08 11:28
I would also like to see the contents of this failure-logs:
>* All command lines available in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/make-support/failure-logs.

**Comment by M-Davies** [comment] 2020-04-08 11:39
> What is the name of the host of the last failing build?

Do you mean the last build that failed before this one? If so, you can see the history of all the builds at https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/. The results are on the left (ticks and crosses).

If you mean the host machine (as in, the machine it failed on), you can see it in the console output https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/264/consoleFull
`Running on build-linaro-centos76-armv8-2`

> I would also like to see the contents of this failure-logs:
> 
> > * All command lines available in /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/make-support/failure-logs.

You would likely need to ask for access to the particular machine to see the logs for that.

**Comment by sxa** [comment] 2020-04-08 11:41
@knn-k Core dump from last night and the`failure-logs` directory you mentioned in your last comment are now in the home directory on the other machine I gave you access to - hope that helps :-)

**Comment by knn-k** [comment] 2020-04-08 11:46
@sxa Thank you.  I found the files.

**Comment by knn-k** [comment] 2020-04-08 12:07
https://github.com/eclipse/openj9/issues/8565#issuecomment-610827195 says Illegal instruction at PC=00004000428B12B4.  But I don't see nothing illegal around the address in the core file.  The instruction sequence looks like code generated by the JIT. 
```
   0x4000428b12a4:      mov     x0, x19
   0x4000428b12a8:      add     x9, x19, #0x98
   0x4000428b12ac:      mov     x10, #0xa80f                    // #43023
   0x4000428b12b0:      dmb     ish
   0x4000428b12b4:      ldxr    x11, [x9]
   0x4000428b12b8:      tst     x11, x10
   0x4000428b12bc:      b.ne    0x4000428b1354  // b.any
```

**Comment by sxa** [comment] 2020-04-08 14:35
Hold off on this for now - I've cleared out the workspace as I'm concerned it may be corrupt in some way and a newer rebuild on the machine appears to be ok ... Will run it a couple of times to verify and let you know if it fails again ...

**Comment by sxa** [comment] 2020-04-08 16:19
@knn-k Can you check out the contents of `cores.openj9.268.tar.xz` in your homedir which contains the dumps from https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/268/console - they should DEFINITELY be in sync as it's a new build I've executed on the machine.

**Comment by knn-k** [comment] 2020-04-08 23:45
The same observation as above.  It looks like the JITed method `jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;`, and I can see no illegal instruction at the reported address.

From https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/268/console :
```
Compiling 4 files for BUILD_JIGSAW_TOOLS
Unhandled exception
Type=Illegal instruction vmState=0x00000000
(... skipped ...)
PC=00004000368B105C SP=0000400029E8CBE0 PSTATE=0000000020000000
(... skipped ...)
Compiled_method=jdk/internal/reflect/Reflection.getCallerClass()Ljava/lang/Class;
```

Disassembling the memory region around 0x4000368B105C in the core file:
```
   0x4000368b1040:      mov     x9, #0x6                        // #6
   0x4000368b1044:      str     x9, [x19, #40]
   0x4000368b1048:      str     x10, [x19, #48]
   0x4000368b104c:      mov     x0, x19
   0x4000368b1050:      add     x9, x19, #0x98
   0x4000368b1054:      mov     x10, #0xa80f                    // #43023
   0x4000368b1058:      dmb     ish
   0x4000368b105c:      ldxr    x11, [x9] <- PC points here
   0x4000368b1060:      tst     x11, x10
   0x4000368b1064:      b.ne    0x4000368b10fc  // b.any
   0x4000368b1068:      and     x11, x11, #0xffffffffffffffdf
   0x4000368b106c:      stxr    w11, x11, [x9]
   0x4000368b1070:      cbnz    x11, 0x4000368b105c
```

**Comment by knn-k** [comment] 2020-04-09 03:27
The JIT compiler was not using the standard encoding for the `ldxr` instruction.
https://github.com/eclipse/omr/pull/5040 addresses it.

The instruction is used in the code for acquire/releaseVMaccess and monitorEnter/Exit.  I don't know why it crashes with "Illegal instruction" intermittently in a specific Java method.

**Comment by sxa** [comment] 2020-04-09 13:24
This is happening on the Linaro arm64 build machine but not hte packet one. For the purposes of this GA I'm going to disable [build-linaro-centos76-armv8-2](https://ci.adoptopenjdk.net/computer/build-linaro-centos76-armv8-2) until next week's GA is passed. I'm guessing the Linaro systems have a different version of the aarch64 instruction set that doesn't have certain instructions that we produce.

**Comment by pshipton** [comment] 2020-04-09 13:27
Ideally the fix https://github.com/eclipse/omr/pull/5040 will become part of the release?

**Comment by pshipton** [comment] 2020-04-09 13:28
I see the fix https://github.com/eclipse/openj9-omr/pull/59 already delivered to the release stream.

**Comment by pshipton** [comment] 2020-04-09 13:28
and https://github.com/eclipse/omr/pull/5040 is promoted for the head stream.

**Comment by sxa** [comment] 2020-04-09 13:33
@pshipton The builds I've been doing this morning have shown the same failure - has something changed in those references in the last 3-4 hours which will have changed things?

**Comment by pshipton** [comment] 2020-04-09 14:00
yes, eclipse/omr#5040 just promoted around 9:15am ET.

**Comment by sxa** [comment] 2020-04-09 15:44
That's fine - I'm only worried about nightlies from the default branch for now, and the [first build I've done](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9-linuxXL/150/consoleFull) since that merge looks good - I'll run a few more just to be sure then i can close this - thanks all

**Comment by sxa** [comment] 2020-04-09 17:26
Yep happy this is fixed now - please close

**Closed** 2020-04-09 17:52 UTC
Labels: arch:aarch64, bug
