### ISSUE TITLE
JTReg jdk11-m2 Failure: TestIBMJlmRemoteMemoryAuth_0

### ISSUE THREAD

**Issue by M-Davies** [eclipse/openj9#9047] opened 2020-03-31 14:31 UTC
Failure link
------------
- test category, sanity.system
- OS/architecture, aarch_64
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0-m2, JRE 11 Linux aarch64-64-Bit 20200330_133 (JIT enabled, AOT enabled)
OpenJ9   - c93e4dabc
OMR      - 1b6abd044
JCL      - 644e9abfc0 based on jdk-11.0.7+9)
```
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/73

Optional info
-------------

- intermittent failure (yes):   
- Part of the jdk11-m2 triage https://github.com/AdoptOpenJDK/openjdk-tests/issues/1705

Failure output (captured from console output)
---------------------------------------------
```
STF 17:03:51.047 - +------ Step 9 - Wait for processes to complete
STF 17:03:51.047 - | Wait for processes to meet expectations
STF 17:03:51.047 - |   Processes: [LT2, CL2]
STF 17:03:51.047 - |
STF 17:03:51.047 - Monitoring processes: CL2 LT2
CL2 j> 2020/03/30 17:03:51.616 ServerURL=service:jmx:rmi:///jndi/rmi://localhost:1234/jmxrmi
CL2 j> 2020/03/30 17:03:57.385 Monitored VM not ready at Mar 30, 2020, 5:03:57 PM (attempt 0).
CL2 j> 2020/03/30 17:03:57.387 Wait 5 secs and trying again...
CL2 j> 2020/03/30 17:03:59.454 Connection established!
CL2 j> 2020/03/30 17:03:59.643 Starting to write data
CL2 stderr Exception in thread "main" java.lang.AssertionError: UnmarshalException: 
CL2 stderr Error unmarshaling return header; nested exception is: 
CL2 stderr 	javax.net.ssl.SSLException: Tag mismatch!
CL2 stderr 	at org.junit.Assert.fail(Assert.java:88)
CL2 stderr 	at net.openj9.test.jlm.resources.MemoryData.writeData(MemoryData.java:177)
CL2 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.getStatsViaServer(MemoryProfiler.java:260)
CL2 stderr 	at net.openj9.test.jlm.remote.MemoryProfiler.main(MemoryProfiler.java:121)
STF 17:04:21.108 - **FAILED** Process CL2 ended with exit code (1) and not the expected exit code/s (0)
STF 17:04:21.108 - Monitoring Report Summary:
STF 17:04:21.109 -   o Process CL2 ended with exit code (1) and not the expected exit code/s (0)
STF 17:04:21.109 -   o Process LT2 is still running as expected
STF 17:04:21.110 - Killing processes: CL2 LT2
STF 17:04:32.112 -   o Process LT2 killed
STF 17:04:32.113 -   o Process CL2 is not running
**FAILED** at step 9 (Wait for processes to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_sanity.system_aarch64_linux_xl/openjdk-tests/TKG/../TKG/test_output_15855859707042/TestIBMJlmRemoteMemoryAuth_0/20200330-165812-TestIBMJlmRemoteMemoryAuth/execute.pl line 321.
STF 17:04:32.474 - **FAILED** execute script failed. Expected return value=0 Actual=1
```

**Comment by pshipton** [comment] 2020-03-31 15:29
@knn-k

**Comment by knn-k** [comment] 2020-03-31 23:42
It is likely it is the same as #9046.

**Comment by knn-k** [comment] 2020-04-03 04:45
I ran this test 10 times manually on cent7-aarch64-1, and saw no failures.

**Comment by M-Davies** [comment] 2020-04-03 09:11
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/2725 grinder got aborted early but theres still over 50% failures in there. 

It was on `test-packet-armv8-ubuntu-16-04` which is also might be causing another test to fail intermittently https://github.com/eclipse/openj9/issues/9048

**Comment by knn-k** [comment] 2020-04-07 12:20
Where can I find the following OpenJ9 binary used in the grinder test?
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+9-202004012325)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-bd765361f, JRE 11 Linux aarch64-64-Bit 20200401_136 (JIT enabled, AOT enabled)
OpenJ9   - bd765361f
OMR      - 0ecff81ea
JCL      - 34c3dd7d55 based on jdk-11.0.7+9)
```

**Comment by M-Davies** [comment] 2020-04-07 13:20
The grinder just downloaded the latest nightly build from Adopt at the time. 

Looks like its a tag from 01/04/2020 which should be still available at https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9. Looks like it's this one https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-04-01-14-28/OpenJDK11U-testimage_aarch64_linux_openj9_2020-04-01-08-39.tar.gz

**Comment by knn-k** [comment] 2020-04-07 13:41
Thanks.
The link above is a testimage.  I downloaded https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-04-01-14-28/OpenJDK11U-jdk_aarch64_linux_openj9_2020-04-01-14-28.tar.gz instead.

**Comment by knn-k** [comment] 2020-04-10 07:13
Assuming it is the same failure with SSLException as that in #9046, see my comment https://github.com/eclipse/openj9/issues/9046#issuecomment-611909993 .

**Comment by andrew-m-leonard** [comment] 2020-05-18 08:18
Repeat of this: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.system_aarch64_linux/145/tapResults/

**Comment by knn-k** [comment] 2020-05-18 08:31
Those crashes in libj9jit29.so are caused by `getJittedBodyInfoFromPC()` returning a NULL.
It is a known problem as #9574.

**Comment by knn-k** [comment] 2020-06-18 02:11
I am closing this as a duplicate of #9046.

**Closed by knn-k** 2020-06-18 02:11 UTC
Labels: arch:aarch64, duplicate, test failure
