### ISSUE TITLE
Assertion failed : Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1)

### ISSUE THREAD

**Issue by zelix0** [eclipse/openj9#8838] opened 2020-03-12 07:08 UTC
Java -version output
--------------------

openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.18.1, JRE 11 Windows 8.1 amd64-64-Bit Compressed References 20200122_442 (JIT enabled , AOT enabled)
OpenJ9   - 51a5857d2
OMR      - 7a1b0239a
JCL      - da35e0c380 based on jdk-11.0.6+10)

**Summary of problem**
------------------

Error when running Zelix KlassMaster 13.0.3 on WIndows 8.1. Error does not occur when using HotSpot JVM with 
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode).

Assertion failed at C:\cygwin64\tmp\openjdk-jdk11u-windows-x64-openj9\workspace\build\src\build\windows-x86_64-normal-server-release
\vm\compiler\optimizer\InterpreterEmulator.cpp:208: 0
VMState: 0x000501ff
        unexpected bytecode in thunk archetype 00007FF79620A980 at bcIndex 40 JBlload2 (33)

compiling com/zelix/vy.a(CSII)V at level: warm

Unhandled exception
Type=Segmentation error vmState=0x000501ff
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=0000000075D96759 ContextFlags=0010005f

Diagnostic files
----------------
[ConsoleOutput1.txt](https://github.com/eclipse/openj9/files/4322731/ConsoleOutput1.txt)

[jitdump.20200312.085100.8472.0004.zip](https://github.com/eclipse/openj9/files/4322723/jitdump.20200312.085100.8472.0004.zip)
[Snap.20200312.085100.8472.0003.zip](https://github.com/eclipse/openj9/files/4322724/Snap.20200312.085100.8472.0003.zip)
[javacore.20200312.085100.8472.0002.zip](https://github.com/eclipse/openj9/files/4322725/javacore.20200312.085100.8472.0002.zip)

**Comment by pshipton** [comment] 2020-03-12 12:50
This should be completely fixed by #8598. In advance of the 0.20.0 release in April, it can be verified by using a Nightly build from AdoptOpenJDK.net.

**Comment by zelix0** [comment] 2020-03-13 04:58
> it can be verified by using a Nightly build from AdoptOpenJDK.net.
**Retested with openjdk version "11.0.7" 2020-04-14**
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+6-202003120047) Eclipse OpenJ9 VM AdoptOpenJDK (build master-c209fa52b, JRE 11 Windows 8.1 amd64-64-Bit Compressed References 20200311_496 (JIT enabled, AOT enabled)
OpenJ9   - c209fa52b
OMR      - b03105e81
JCL      - 7d1badbc1c based on jdk-11.0.7+6)

**Now getting the following NullPointerException when using J9 JVM but not HotSpot JVM.**

Caused by: java.lang.NullPointerException
        at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
        at java.base/java.util.TimSort.sort(TimSort.java:220)
        at java.base/java.util.Arrays.sort(Arrays.java:1546)
        at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
        at java.base/java.util.Collections.sort(Collections.java:179)
        at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_V(DirectHandle.java:175)
        at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
        at java.base/java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
        at com.zelix.ml.a(ml.java:215)
        at java.base/java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_V(VirtualHandle.java:85)
        at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
        at java.base/java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
        at com.zelix.jg.a(jg.java:48)
        at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_V(DirectHandle.java:177)
        at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
        at java.base/java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
        at com.zelix.lm.a(lm.java:1795)
        at java.base/java.lang.invoke.VirtualHandle.invokeExact_thunkArchetype_V(VirtualHandle.java:85)
        at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
        at java.base/java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
        at com.zelix.al.a(al.java:699)
        at java.base/java.lang.invoke.DirectHandle.invokeExact_thunkArchetype_V(DirectHandle.java:177)
        at java.base/java.lang.invoke.BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(BruteArgumentMoverHandle.java:404)
        at java.base/java.lang.invoke.MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:64)
        at com.zelix.al.a(al.java:1186)
        at com.zelix.al$$Lambda$72/0000000000000000.accept(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)

**Comment by DanHeidinga** [comment] 2020-03-13 13:45
fyi @andrewcraik @cathyzhyi

**Comment by cathyzhyi** [comment] 2020-03-24 01:47
assigned to @cathyzhyi

**Comment by pshipton** [comment] 2020-03-30 15:07
We're past Milestone 2 for the 0.20.0 release, moving this forward to the next release.

**Comment by cathyzhyi** [comment] 2020-04-13 22:02
@zelix0 Hi, how reproducible is the problem? could you try adding `-Xjit:java+system:events=throw,filter=java/lang/NullPointerException#*java/util/TimSort.countRunAndMakeAscending*,range=1..1` to collect the javacore and core files so that I can take a look?

**Comment by zelix0** [comment] 2020-04-14 02:10
Using jdk-11.0.7+9 x64 on Windows 8.1 I am getting the following "unrecognized option" error.  

<JIT: unrecognized option --> 'java+system:events=throw,filter=java/lang/NullPointerException#*java/util/TimSort.countRunAndMakeAscending*,range=1..1'>
<**JIT: fatal error, invalid command line**>
Assertion failed at J:\jenkins\tmp\workspace\build\src\build\windows-x86_64-normal-server-release\vm\compiler\control\CompilationController.cpp:101: rc != 0
        TlsFree failed with GetLastError = 87

If I didn't use the suggested command line option I got 5 crashes out of 5 runs.  Twice I got an "Unhandled exception Type=Segmentation error vmState=0x00000000".  Three times I got a "NullPointerException at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)"

I have attached the dump files from one of the Segmentation errors.  However, the core dumps are about 3GB so they are not included.

[DumpFiles.zip](https://github.com/eclipse/openj9/files/4472704/DumpFiles.zip)

**Comment by cathyzhyi** [comment] 2020-04-14 15:39
@zelix0 Thanks a lot for trying to collect the data. I will take a look at the dump files collected.

**Comment by cathyzhyi** [comment] 2020-04-20 15:23
@zelix0 Hey, the backtrace of the javacore files are off because openjdk doesn't package the pdf file for windows sdks. Also, it seems there are multiple problems here, NPE and crashes in the compilation. Is it possible that I can run the test locally on my end? Thanks!

**Comment by zelix0** [comment] 2020-04-20 22:19
> can run the test locally on my end? 

I e-mailed a download link to a test case to your Gmail address about 4 weeks ago.  I am not sure whether it allowed you to reproduce the problem.  Just in case I have pasted a link to the same test case below.

https://www.zelix.com/temp/5s5s3xaspe1r/ZKM14.0.0debug0.zip

If you extract ZKM14.0.0debug0.zip you will get ReadMe.txt, ZKM.jar, script0.txt and miscellaneous other files to do with licensing etc.  As explained in the ReadMe.txt, you run the test case with the following command.

java -showversion -Xmx2048m -jar ZKM.jar -v script0.txt

Unfortunately, the test case is not a small and simple one. When I try to simplify it, the problem goes away.  I assume that it needs to be complex so that the J9 JIT will optimize.

**Comment by andrewcraik** [comment] 2020-05-19 14:31
@cathyzhyi updates?

**Comment by cathyzhyi** [comment] 2020-05-20 18:46
> @cathyzhyi updates?

I am able to reproduce the failures. There seems to be different failures but the root cause might be the same. The one I am focusing on now is a crash with 
```
limit={java/lang/invoke/AsTypeHandle.invokeExact_thunkArchetype_X*},ifexcluded(noopt),disableinlining,count=0
```
However, there are too many `AsTypeHandle.invokeExact_thunkArchetype_X` compiled so I didn't proceed with the tracing logs.
From the coredumps, I've manually reconstructed the stack frames and verified the invalid argument is `Ljava/util/Comparator; ` which is last argument to `java/util/TimSort.countRunAndMakeAscending([Ljava/lang/Object;IILjava/util/Comparator;)I` The invalid object can be traced back several frames to `com/zelix/zt.a`.
```
0x7574a8: 0x00007ff1f1a74433 {java/util/TimSort.countRunAndMakeAscending} +735
0x7574d8: 0x00007ff1f1a29df5 {java/util/TimSort.sort} +321
0x757508: 0x00007ff1f170a41e {java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X} +138
0x757548: 0x00007ff1f1a299b5 {java/util/Arrays.sort} +193
0x757588: 0x00007ff1f1a29645 {java/util/ArrayList.sort} +81
0x7575c8: 0x00007ff1f1a294a4 {java/util/Collections.sort} +80
0x7575e8: 0x00007ff1f18947a9 {java/lang/invoke/DirectHandle.invokeExact_thunkArchetype_V} +117
0x757608: 0x00007ff1f17358fc {java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X} +168
0x757618: 0x00007ff1f172727e {java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X} +170
0x757648: 0x00007ff1f234f658 {java/lang/invoke/MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X} +132
0x7576a8: 0x00007ff1f233ad19 {com/zelix/zt.a} +3685 com/zelix/zt.a(ZLjava/util/List;Lcom/zelix/nd;ILcom/zelix/zh;CSLcom/zelix/qa;)V
```
Still trying to dig more.

**Comment by cathyzhyi** [comment] 2020-05-21 15:56
so the invalid `Ljava/util/Comparator;` object is read by a `StaticFieldGetterHandle` from the static field of `om/zelix/_2.j (Ljava/util/Comparator;)`

**Comment by zelix0** [comment] 2020-05-23 07:41
Just to be sure, have re-run the test case using the OpenJ9 VM **with the -Xint option** and then using the **HotSpot version** of the AdoptOpenJDK.  The test case ran to completion with no problems in both scenarios.  Problems only occur if the OpenJ9 VM is used **without** the -Xint option.

**Comment by cathyzhyi** [comment] 2020-06-02 01:07
> Just to be sure, have re-run the test case using the OpenJ9 VM **with the -Xint option** and then using the **HotSpot version** of the AdoptOpenJDK. The test case ran to completion with no problems in both scenarios. Problems only occur if the OpenJ9 VM is used **without** the -Xint option.

Yes, we've noticed that as well. The test passes with -Xint which means all methods are interpreted. However, I've also noticed the failure seems to be timing sensitive so the problem might not necessarily in the compiler.

**Comment by zelix0** [comment] 2020-06-02 02:33
> the failure seems to be timing sensitive so the problem might not necessarily in the compiler

If the problem was some kind of application problem then wouldn't you expect to also have a least occasional crashes in the HotSpot version of the AdoptOpenJDK and the Oracle JVM? None has ever been reported.

Looking at it from another direction, have you ever had the test case complete without a crash when using the OpenJ9 VM without using the -Xint option?

For what it is worth, I have a sneaking suspicion that the problem has something to do with how the J9 compiler is processing/optimizing(/caching?) MutableCallSites. Could it be introducing a timing issue here?

**Comment by cathyzhyi** [comment] 2020-06-02 14:31
@zelix0 sry, I didn't make myself clear. I didn't mean the problem is in the application. I meant the problem might not be in `Just-In-Time compiler` but in the Runtime. My point was, even the test pass with `-Xint` when all the methods are interpreted doesn't mean the problem is in the compiler it might still be problem in the interpreter. Like you said it might be related to how OpenJ9 processes the MutableCallsites which is part of the Runtime not related to the `Just-In-Time` compiler.

**Comment by cathyzhyi** [comment] 2020-06-02 16:24
The failure still happens with all the methods are compiled at `noopt` level. The fact that it happens when all the `AsTypeHandle` thunks are compiled at `warm` and other methods at `noopt`  is actually a red herring. The failure seems to be very sensitive to timing. @liqunl @DanHeidinga Do you have some suggestions on what to look for next?  I think it's more likely something wrong with JSR292 infrastructure and not related to how the methods are compiled. Is there any options that I can try to narrow down the issue?

**Comment by DanHeidinga** [comment] 2020-06-03 01:43
> so the invalid `Ljava/util/Comparator;` object is read by a `StaticFieldGetterHandle` from the static field of `com/zelix/_2.j (Ljava/util/Comparator;)`.

Does that static field contain the invalid object?  Or is it being corrupted by the `StaticFieldGetterHandle` ?

If it's invalid in the static field, we need to find where the object came from - ie: who wrote it into the field - to narrow down what needs to be looked at

**Comment by cathyzhyi** [comment] 2020-06-08 19:35
I searched all the `StaticFieldSetterHandle` s and bytecodes and can't find any writes to that static field. I do notice that many of the other static fields in that class are invalid as well:
```
k ( +32) ([Ljava/lang/Object;) - 20002 Private
h ( +40) (Lcom/zelix/o;) - 20002 Private
j = 0x00000000f52513c0 (Ljava/util/Comparator;) - 4002000a Private Static  : Obj - {com/zelix/bp} +8
i ( +48) (Z) - 80002 Private
l = 0x0000000081660c50 (J) - 3c001a Private Static Final
m = 0x0000000081660c68 ([Ljava/lang/String;) - 2001a Private Static Final  : Ptr
n = 0x0000000081660c80 ([Ljava/lang/String;) - 2001a Private Static Final  : Obj - {java/util/HashMap}
o = 0x000075f8636c4cce (Ljava/util/Map;) - 2001a Private Static Final  :
```

**Comment by cathyzhyi** [comment] 2020-06-08 20:01
@zelix0 Hey, could you share some information on at the high level how does the application work? Also, how are the static fields of `com/zelix/_2` might be written? Could it be possible they are written by native code or by Unsafe APIs?

**Comment by DanHeidinga** [comment] 2020-06-08 20:05
@cathyzhyi Can you dump the `J9Class` in `jdmpview`?  It makes me wonder if the class has been initialized correctly or if it's been replaced (redefined)

**Comment by cathyzhyi** [comment] 2020-06-08 20:31
I think the class seems to be fine. 
> !j9class 0x00000000005a8200
J9Class at 0x5a8200 {
  Fields for J9Class:
        0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
        0x8: struct J9ROMClass* romClass = !j9romclass 0x00007F0A2C034AC8
        0x10: void** superclasses = !j9x 0x00000000005A8038
        0x18: UDATA classDepthAndFlags = 0x00000000000E0004 (917508)
        0x20: U32 classDepthWithFlags = 0x00000000 (0)
        0x24: U32 classFlags = 0x00000000 (0)
        0x28: struct J9ClassLoader* classLoader = !j9classloader 0x00007F0AA40C8968
        0x30: struct J9Object* classObject = !j9object 0x00000000812C52F0 // java/lang/Class
        0x38: volatile UDATA initializeStatus = 0x0000000000000001 (1)
        0x40: struct J9Method* ramMethods = !j9method 0x00000000005A8528 // com/zelix/_2.c(JI)Ljava/util/Comparator;
        0x48: UDATA* ramStatics = !j9x 0x00000000005A6D20
        0x50: struct J9Class* arrayClass = !j9class 0x00000000005A8D00 // [Lcom/zelix/_2;
        0x58: UDATA totalInstanceSize = 0x000000000000001C (28)
        0x60: struct J9ITable* lastITable = !j9itable 0x00000000005A7FE0
        0x68: UDATA* instanceDescription = !j9x 0x000000000000003D
        0x70: UDATA* instanceLeafDescription = !j9x 0x0000000000000001
        0x78: UDATA instanceHotFieldDescription = 0x0000000000000000 (0)
        0x80: UDATA selfReferencingField1 = 0x000000000000000C (12)
        0x88: UDATA selfReferencingField2 = 0x0000000000000000 (0)
        0x90: struct J9Method* initializerCache = !j9method 0x0000000000000000
        0x98: UDATA romableAotITable = 0x00007F0AA330DFC0 (139683664289728)
        0xa0: UDATA packageID = 0x00007F0AA45B7691 (139683683858065)
        0xa8: struct J9Module* module = !j9module 0x0000000000000000
        0xb0: struct J9Class* subclassTraversalLink = !j9class 0x0000000000551C00 // com/zelix/z7
        0xb8: struct J9Class* subclassTraversalReverseLink = !j9class 0x00000000005BD500 // com/zelix/_q
        0xc0: void** iTable = !j9x 0x00000000005A7FE0
        0xc8: UDATA castClassCache = 0x00000000005C0101 (6029569)
        0xd0: void** jniIDs = !j9x 0x00007F0A10003F00
        0xd8: UDATA lockOffset = 0x0000000000000004 (4)
        0xe0: U32 paddingForGLRCounters = 0x00000000 (0)
        0xe4: U16 reservedCounter = 0x0000 (0)
        0xe6: U16 cancelCounter = 0x0000 (0)
        0xe8: UDATA newInstanceCount = 0x00000000000007D0 (2000)
        0xf0: IDATA backfillOffset = 0x000000000000001C (28)
        0xf8: struct J9Class* replacedClass = !j9class 0x0000000000000000
        0x100: UDATA finalizeLinkOffset = 0x0000000000000000 (0)
        0x108: struct J9Class* nextClassInSegment = !j9class 0x0000000000000000
        0x110: UDATA* ramConstantPool = !j9x 0x00000000005A7730
        0x118: struct J9Object** callSites = !j9x 0x00000000005A8908
        0x120: struct J9Object** methodTypes = !j9x 0x0000000000000000
        0x128: struct J9Object** varHandleMethodTypes = !j9x 0x0000000000000000
0x130: struct J9VMCustomSpinOptions* customSpinOption = !j9vmcustomspinoptions 0x0000000000000000
        0x138: void** staticSplitMethodTable = !j9x 0x0000000000000000
        0x140: void** specialSplitMethodTable = !j9x 0x0000000000000000
        0x148: struct J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
        0x150: struct J9Class* gcLink = !j9class 0x0000000000000000
        0x158: struct J9Class* hostClass = !j9class 0x00000000005A8200 // com/zelix/_2
        0x160: struct J9Class* nestHost = !j9class 0x0000000000000000
        0x168: struct J9FlattenedClassCache* flattenedClassCache = !j9flattenedclasscache 0x0000000000000000

**Comment by DanHeidinga** [comment] 2020-06-09 01:33
```
0x38: volatile UDATA initializeStatus = 0x0000000000000001 (1)
```
shows the class was correctly initialized.

And no evidence the class has been redefined (`arrayClass` points to the right array class, `replacedClass` is null).

That negates my theories

**Comment by zelix0** [comment] 2020-06-09 05:51
> Could it be possible they are written by native code or by Unsafe APIs?

There is no native code or use of any unsafe APIs.

> how are the static fields of com/zelix/_2 might be written? 

At a high level, the static field java.util.Comparator j in com.zelix._2 is set by the method java.util.Comparator c(long, int).  That method c(long, int) first tests whether the Comparator field is null.  If it is null then it constructs a Comparator object (com.zelix.ja) and sets the field before returning the com.zelix.ja instance. Its the Singleton pattern.

However, the setting and getting of the field Comparator j and the construction of the Comparator are all done via invokedynamic calls. All the relevant bootstrap methods for the invokedynamics are in the class com/zelix/aae.  The bootstap method in com/zelix/aae returns a MutableCallSite that has a resolver method in com/zelix/aae as its target.  When the resolver method is first called it does a somewhat complicated lookup using the two longs that it is passed on the stack and the name associated with the invokedynamic's CONSTANT_Dynamic_info.  It then changes the MutableCallSite's target to be the ultimate, final MethodHandle resulting from its lookup.  The final target MethodHandle may reference a field, method, constructor etc. and may make use of the other parameters on the stack.

So there are a number of perhaps unusual features.  1) The bootstrap method is in another class and that bootstrap classes is called from many different classes.  2) The MutableCallSite that is returned has its target set twice. 3) For one particular bootstrap method, the 1st target is always the same but the ultimate, final target of the MutableCallSites that it returns differ depending upon the long parameters that are passed and the name associated with the CONSTANT_Dynamic_info.

I hope this helps.

**Comment by cathyzhyi** [comment] 2020-06-09 20:28
@zelix0 Thanks a lot for the detailed explanation! It's very helpful.

**Comment by zelix0** [comment] 2020-06-12 08:16
>  How many other use cases might affected?

By way of background, the utility that we distribute is used by our users to modify the bytecode of their Java applications.  Depending upon the setting that the user specifies, this can result in the user's application consistently triggering this J9 problem in a fashion similar to the testcase.  

For what it is worth, many thousands of users have downloaded our utility but there is no way of knowing how many of those users have used the relevant settings when processing their applications.  Further, if our users have indeed used the relevant settings when processing their applications then there is no way of knowing how many users there are of our user's processed applications.

Sorry I could not be more helpful. Otherwise, our experience has been that if our utility can produce bytecode that triggers crashes in a JVM then it is only a matter of time before a new release of major Java application triggers the same crash on that JVM.

**Comment by cathyzhyi** [comment] 2020-06-13 18:01
I tried to break on  `java/lang/invoke/StaticFieldSetterHandle.invokeExact_thunkArchetype_V(Ljava/lang/Object;)V`whenever detecting the setter is writing to `com/zelix/_2.j`. The static field is always set with a valid `{com/zelix/ja}` object.  However, the object address, more specifically the last valid address written to the field, becomes invalid at the time of crashing. The invalid address always points to the middle of another object. This makes me suspect GC happened and the address was replaced by another object. However, I don't know why this can happen. Could it be possible that this static field is not added to the root set for GC? @DanHeidinga Do you have any thoughts on this? 

Another observation is that this failure is very timing sensitive. Whenever I do either of the following the failure goes away or becomes a different failure:
- setting watchpoint in gdb on the static field `com/zelix/_2.j` directly
- turning off `unsafeFastPath` for the `StaticFieldSetterHandle` thunk which essentially makes writing to the static field slower

**Comment by DanHeidinga** [comment] 2020-06-15 04:41
> Could it be possible that this static field is not added to the root set for GC?

That's unlikely as the Class has been found (ie: the class object has been found).

If you switch to the optthruput gc policy which is a simpler policy with no barriers, does the issue still occur?  I'm wondering if we're missing a barrier in this code path?

**Comment by cathyzhyi** [comment] 2020-06-15 13:44
> > Could it be possible that this static field is not added to the root set for GC?
> 
> That's unlikely as the Class has been found (ie: the class object has been found).
> 
> If you switch to the optthruput gc policy which is a simpler policy with no barriers, does the issue still occur? I'm wondering if we're missing a barrier in this code path?

Thanks @DanHeidinga! I think that's the problem!

**Comment by cathyzhyi** [comment] 2020-06-15 16:02
Using `-Xgcpolicy:optthruput` makes the failure stop but seems adding write barrier for the `Unsafe.putObject` doesn't work. Continue investigating.

**Comment by DanHeidinga** [comment] 2020-06-15 17:08
Is this a write a final field?  Is the `reportFinalFieldModified` being called in this case?  Is the object refetched after the final write hook is executed?

**Comment by cathyzhyi** [comment] 2020-06-16 00:27
> Is this a write a final field? Is the `reportFinalFieldModified` being called in this case? Is the object refetched after the final write hook is executed?

Hey Dan @DanHeidinga, Thanks a lot for the help! I think I've found the root cause. The format of our write barrier is also not correct so even when we generate the write barrier the failure still happens. Now I am working on the fix.

**Closed** 2020-06-18 19:25 UTC
Labels: comp:jit, userRaised
