### ISSUE TITLE
ReentrantLock/CancelledLockLoops crash vmState=0x00020011

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9499] opened 2020-05-08 17:50 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/50
java/util/concurrent/locks/ReentrantLock/CancelledLockLoops.java
ub16-ppcle-1
```
22:59:37  Unhandled exception
22:59:37  Type=Segmentation error vmState=0x00020011
22:59:37  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
22:59:37  Handler1=00003FFF8C5B8720 Handler2=00003FFF8C417280
22:59:37  R0=00003FFF872A8F48 R1=00003FFF7595AD50 R2=00003FFF87E6F600 R3=00003FFF85F56120
22:59:37  R4=00003FFF7595AE00 R5=00003FFF880B5E70 R6=00003FFF880B5E70 R7=00003FFF3009C220
22:59:37  R8=00003FFF88407C18 R9=0000000200001E28 R10=0000000000000000 R11=000000000000270F
22:59:37  R12=00003FFF8D30D1D0 R13=00003FFF75966900 R14=0000000000000007 R15=0000000000000004
22:59:37  R16=00003FFF88049000 R17=00003FFF7595B51F R18=0000000000000006 R19=0000000000020019
22:59:37  R20=0000000000000000 R21=00003FFF8C781E30 R22=0005A51A2A9264F6 R23=00003FFF872A8DD4
22:59:37  R24=00003FFF88012DA8 R25=00003FFF87EADBE0 R26=00003FFF85F56120 R27=00003FFF85F56318
22:59:37  R28=0000000000000000 R29=00003FFF85F56230 R30=00003FFF7595AE00 R31=00003FFF68070260
22:59:37  NIP=00003FFF87287454 MSR=800000000280F033 ORIG_GPR3=00003FFF8C4E69F4 CTR=00003FFF8D30D1D0
22:59:37  LINK=00003FFF872A8F48 XER=0000000020000000 CCR=0000000028004224 SOFTE=0000000000000001
22:59:37  TRAP=0000000000000300 DAR=0000000200001E50 dsisr=0000000040000000 RESULT=0000000000000000
22:59:37  FPR0 00003fff8c780a08 (f: 2356677120.000000, d: 3.476582e-310)
22:59:37  FPR1 4048aff840000000 (f: 1073741824.000000, d: 4.937476e+01)
22:59:37  FPR2 3fe34413509f79fb (f: 1352628736.000000, d: 6.020600e-01)
22:59:37  FPR3 bf3d4a1000000000 (f: 0.000000, d: -4.469194e-04)
22:59:37  FPR4 3f499a0000000000 (f: 0.000000, d: 7.812977e-04)
22:59:37  FPR5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR6 616a5f65756c675f (f: 1970038656.000000, d: 1.853879e+161)
22:59:37  FPR7 6167656c6544676e (f: 1698981760.000000, d: 1.644647e+161)
22:59:37  FPR8 bf721456e0000000 (f: 3758096384.000000, d: -4.413928e-03)
22:59:37  FPR9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR11 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
22:59:37  FPR12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR13 4041a00000000000 (f: 0.000000, d: 3.525000e+01)
22:59:37  FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:59:37  Module=/home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9jit29.so
22:59:37  Module_base_address=00003FFF87110000
22:59:37  Target=2_90_20200507_383 (Linux 4.4.0-173-generic)
22:59:37  CPU=ppc64le (4 logical CPUs) (0x1fe390000 RAM)
22:59:37  ----------- Stack Backtrace -----------
22:59:37  (0x00003FFF87287454 [libj9jit29.so+0x177454])
22:59:37  (0x00003FFF7595ADA0 [<unknown>+0x0])
22:59:37  (0x00003FFF872A8F48 [libj9jit29.so+0x198f48])
22:59:37  (0x00003FFF8C4A1840 [libj9hookable29.so+0x1840])
22:59:37  (0x00003FFF8702E294 [libj9gc29.so+0x25e294])
22:59:37  (0x00003FFF86FA15B8 [libj9gc29.so+0x1d15b8])
22:59:37  (0x00003FFF86FA1838 [libj9gc29.so+0x1d1838])
22:59:37  (0x00003FFF86FB154C [libj9gc29.so+0x1e154c])
22:59:37  (0x00003FFF87012B8C [libj9gc29.so+0x242b8c])
22:59:37  (0x00003FFF86F3AFDC [libj9gc29.so+0x16afdc])
22:59:37  (0x00003FFF87018F60 [libj9gc29.so+0x248f60])
22:59:37  (0x00003FFF8701B7A8 [libj9gc29.so+0x24b7a8])
22:59:37  (0x00003FFF8701BE3C [libj9gc29.so+0x24be3c])
22:59:37  (0x00003FFF86F4D624 [libj9gc29.so+0x17d624])
22:59:37  (0x00003FFF86FA9FDC [libj9gc29.so+0x1d9fdc])
22:59:37  (0x00003FFF86E29EEC [libj9gc29.so+0x59eec])
22:59:37  (0x00003FFF87B9C8E8 [libj9jit29.so+0xa8c8e8])
22:59:37  (0x00003FFF87BB6F50 [libj9jit29.so+0xaa6f50])
22:59:37  (0x00003FFF8C59C5D4 [libj9vm29.so+0x8c5d4])
22:59:37  (0x00003FFF8C60CBF0 [libj9vm29.so+0xfcbf0])
22:59:37  (0x00003FFF8C418688 [libj9prt29.so+0x28688])
22:59:37  (0x00003FFF8C608284 [libj9vm29.so+0xf8284])
22:59:37  (0x00003FFF8C4E1248 [libj9thr29.so+0x11248])
22:59:37  (0x00003FFF8D308040 [libpthread.so.0+0x8040])
22:59:37  clone+0x98 (0x00003FFF8D1E3BB0 [libc.so.6+0x123bb0])
```

**Comment by pshipton** [comment] 2020-05-08 17:54
5x grinder https://ci.eclipse.org/openj9/job/Grinder/876

**Comment by dmitripivkine** [comment] 2020-05-08 17:54
Duplicate of https://github.com/eclipse/openj9/issues/8652

**Closed** 2020-05-08 17:55 UTC
Labels: comp:jit, segfault, test failure

**Comment by pshipton** [comment] 2020-05-12 15:45
@dmitripivkine there is another crash vmState=0x00020011. Is it another dup?
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8/3
java/util/Iterator/IteratorDefaults.java
```
01:10:29  Type=Segmentation error vmState=0x00020011
01:10:29  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
01:10:29  Handler1=00003FFFB6008720 Handler2=00003FFFB5E67280
01:10:29  R0=00003FFFB4BC9064 R1=00003FFF64859EF0 R2=00003FFFB578F600 R3=00003FFFAF756120
01:10:29  R4=00003FFF64859FA0 R5=00003FFFB00EF180 R6=00003FFFB00EF180 R7=00003FFF64E98370
01:10:29  R8=00003FFFB00D2DC8 R9=0000000000000000 R10=0000000000000000 R11=00003FFF6485A0B0
01:10:29  R12=00003FFFB4BC8EF0 R13=00003FFF64866900 R14=0000000000000007 R15=0000000000000004
01:10:29  R16=00003FFFB00497C0 R17=00003FFF6485A6BF R18=0000000000000006 R19=0000000000020019
01:10:29  R20=0000000000000000 R21=00003FFFB61D1E30 R22=0005A56C7A5D8062 R23=00003FFFB4BC8EF0
01:10:29  R24=00003FFFB0012D18 R25=00003FFFB57CDC00 R26=00003FFFAF756120 R27=00003FFFAF756318
01:10:29  R28=0000000000000000 R29=00003FFFAF756230 R30=00003FFF64859FA0 R31=00003FFF9C1E5CD0
01:10:29  NIP=00003FFFB4BA7538 MSR=800000010280F033 ORIG_GPR3=00000000000081C8 CTR=00003FFFB4BC8EF0
01:10:29  LINK=00003FFFB4BC9064 XER=0000000000000000 CCR=0000000028004284 SOFTE=0000000000000001
01:10:29  TRAP=0000000000000300 DAR=0000000000000000 dsisr=0000000040000000 RESULT=0000000000000000
01:10:29  FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR1 404bd735e0000000 (f: 3758096384.000000, d: 5.568133e+01)
01:10:29  FPR2 3f847ae147ae147b (f: 1202590848.000000, d: 1.000000e-02)
01:10:29  FPR3 3fee666660000000 (f: 1610612736.000000, d: 9.500000e-01)
01:10:29  FPR4 3f499a0000000000 (f: 0.000000, d: 7.812977e-04)
01:10:29  FPR5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR6 3f8e805fc0000000 (f: 3221225472.000000, d: 1.489329e-02)
01:10:29  FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR8 bfbf3de320000000 (f: 536870912.000000, d: -1.220381e-01)
01:10:29  FPR9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR11 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
01:10:29  FPR12 4008000000000000 (f: 0.000000, d: 3.000000e+00)
01:10:29  FPR13 bfb7440000000000 (f: 0.000000, d: -9.088135e-02)
01:10:29  FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
01:10:29  Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.openjdk_ppc64le_linux_OpenJDK8/openjdkbinary/j2sdk-image/jre/lib/ppc64le/compressedrefs/libj9jit29.so
01:10:29  Module_base_address=00003FFFB4A30000
01:10:29  Target=2_90_20200511_39 (Linux 4.4.0-173-generic)
01:10:29  CPU=ppc64le (16 logical CPUs) (0x1fe090000 RAM)
01:10:29  ----------- Stack Backtrace -----------
01:10:29  (0x00003FFFB4BA7538 [libj9jit29.so+0x177538])
01:10:29  (0x00003FFF64859F30 [<unknown>+0x0])
01:10:29  (0x00003FFFB4BC9064 [libj9jit29.so+0x199064])
01:10:29  (0x00003FFFB5EF1840 [libj9hookable29.so+0x1840])
01:10:29  (0x00003FFFB494E294 [libj9gc29.so+0x25e294])
01:10:29  (0x00003FFFB48C15B8 [libj9gc29.so+0x1d15b8])
01:10:29  (0x00003FFFB48C1838 [libj9gc29.so+0x1d1838])
01:10:29  (0x00003FFFB48D154C [libj9gc29.so+0x1e154c])
01:10:29  (0x00003FFFB4932B8C [libj9gc29.so+0x242b8c])
01:10:29  (0x00003FFFB485AFDC [libj9gc29.so+0x16afdc])
01:10:29  (0x00003FFFB4938F60 [libj9gc29.so+0x248f60])
01:10:29  (0x00003FFFB493B7A8 [libj9gc29.so+0x24b7a8])
01:10:29  (0x00003FFFB493BE3C [libj9gc29.so+0x24be3c])
01:10:29  (0x00003FFFB486D624 [libj9gc29.so+0x17d624])
01:10:29  (0x00003FFFB48C9FDC [libj9gc29.so+0x1d9fdc])
01:10:29  (0x00003FFFB4749EEC [libj9gc29.so+0x59eec])
01:10:29  (0x00003FFFB54BD558 [libj9jit29.so+0xa8d558])
01:10:29  (0x00003FFFB54D7BD0 [libj9jit29.so+0xaa7bd0])
01:10:29  (0x00003FFFB5FF12CC [libj9vm29.so+0x912cc])
01:10:29  (0x00003FFFB5FF25F8 [libj9vm29.so+0x925f8])
01:10:29  (0x00003FFFB446FF04 [libjclse29.so+0x6ff04])
01:10:29  JVM_InvokeMethod+0x40 (0x00003FFFB6190BF0 [libjvm.so+0x20bf0])
01:10:29  JVM_InvokeMethod+0x34 (0x00003FFFB6AD5FE4 [libjvm.so+0x5fe4])
01:10:29  Java_sun_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00003FFF9CFFBF84 [libjava.so+0xbf84])
01:10:29  (0x00003FFF9FD7A750 [<unknown>+0x0])
01:10:29  (0x00003FFFB5FF12CC [libj9vm29.so+0x912cc])
01:10:29  (0x00003FFFB5FF25F8 [libj9vm29.so+0x925f8])
01:10:29  (0x00003FFFB446FF04 [libjclse29.so+0x6ff04])
01:10:29  JVM_InvokeMethod+0x40 (0x00003FFFB6190BF0 [libjvm.so+0x20bf0])
01:10:29  JVM_InvokeMethod+0x34 (0x00003FFFB6AD5FE4 [libjvm.so+0x5fe4])
01:10:29  Java_sun_reflect_NativeMethodAccessorImpl_invoke0+0x24 (0x00003FFF9CFFBF84 [libjava.so+0xbf84])
01:10:29  (0x00003FFF9FD7A750 [<unknown>+0x0])
01:10:29  (0x00003FFFB5FEC5D4 [libj9vm29.so+0x8c5d4])
01:10:29  (0x00003FFFB605CBF0 [libj9vm29.so+0xfcbf0])
01:10:29  (0x00003FFFB5E68688 [libj9prt29.so+0x28688])
01:10:29  (0x00003FFFB6058284 [libj9vm29.so+0xf8284])
01:10:29  (0x00003FFFB5F31248 [libj9thr29.so+0x11248])
01:10:29  (0x00003FFFB6D58040 [libpthread.so.0+0x8040])
```

**Comment by dmitripivkine** [comment] 2020-05-12 16:16
yes, this crash looks like a duplicate of https://github.com/eclipse/openj9/issues/8652
