### ISSUE TITLE
Issue when resolving the callee for a TR::call node

### ISSUE THREAD

**Issue by vesuppi** [eclipse/openj9#5304] opened 2019-03-29 15:14 UTC
Hi, 

I have a some code that runs during the escape analysis phase in the JIT, which tries to print the name of the callee of a call node. I can get `TR_ResolvedMethod*` without a problem, but the pointer I obtained doesn't seem to be valid. Any method call on this pointer would segfault. My program looks like this:

```c++
  TR::TreeTop *treeTop;
  for (treeTop = comp()->getStartTree(); treeTop; treeTop = treeTop->getNextTreeTop())
  {
    TR::Node* N = getRealNode(treeTop->getNode());

    if (N->getOpCodeValue() == TR::call &&
        !N->getSymbolReference()->isUnresolved()) {
      TR_ResolvedMethod *callee = N->getSymbol()->castToResolvedMethodSymbol()->getResolvedMethod();
      if (callee) {
        // all method invocation on this pointer fails such as isStatic(), nameChars() etc.
        callee->isStatic();
      }
  }

TR::Node* getRealNode(TR::Node* N) {
  auto oc = N->getOpCodeValue();
  if (oc == TR::treetop
      || oc == TR::PassThrough
      || oc == TR::compressedRefs
      || N->getOpCode().isResolveOrNullCheck()
      ) {
    return N->getChild(0);
  }
  else {
    return N;
  }
}
```
Is this a known issue or did I miss anything? Thanks!

**Comment by pshipton** [comment] 2019-03-29 16:50
@andrewcraik

**Comment by andrewcraik** [comment] 2019-03-29 17:02
So the issue is that `castToResolvedMethodSymbol`, outside of a debug build, is just a straight C++ pointer type cast (see OMR compiler/il/symbol/OMRSymbol_inlines.hpp). There is a `isResolvedMethod` query and a `getResolvedMethodSymbol` which will do the check and return non-null if the type is wrong. Not the best API, but use one of those and check for NULL before proceeding and you should then have the behavior you want.

Note that checking a SymbolReference for unresolved is quite different from checking the properties of the symbol it is talking about.

**Comment by andrewcraik** [comment] 2019-03-29 17:03
Feel free to reopen if further discussion is required - I have closed this just to indicate the question raised has been answered and there is no lurking compiler bug.

**Closed by andrewcraik** 2019-03-29 17:02 UTC
Labels: comp:jit, userRaised

**Comment by vesuppi** [comment] 2019-03-29 17:55
> So the issue is that `castToResolvedMethodSymbol`, outside of a debug build, is just a straight C++ pointer type cast (see OMR compiler/il/symbol/OMRSymbol_inlines.hpp). There is a `isResolvedMethod` query and a `getResolvedMethodSymbol` which will do the check and return non-null if the type is right. Not the best API, but use one of those and you should then have the behavior you want.
> 
> Note that checking a SymbolReference for unresolved is quite different from checking the properties of the symbol it is talking about.

@andrewcraik 
I see. Thanks a lot. But I thought with the guard `!N->getSymbolReference()->isUnresolved()` all the unresolved symbols should be filtered out, and `castToResolvedMethodSymbol()` should be fine?

**Comment by andrewcraik** [comment] 2019-03-29 17:57
No the resolution of a symref is different from the symbol - symref resolution corresponds to constant pool resolution the symbol resolution is separate - have a look in the optimizer at other places querying getResolvedMethodSymbol or we can discuss on the OpenJ9 slack :)

**Comment by vesuppi** [comment] 2019-03-29 18:08
Oh oh okay, so basically if the corresponding constant pool entry exists the symbol reference can be resolved, but that's just means a name (a string) can be found. But symbol resolution corresponds to the specific in-memory data structure that represents this name?

Btw, I copied the code from `Walker.cpp` which has multiple occurances of such code:

https://github.com/eclipse/openj9/blob/f659113421b9e88fd42bf709fb3a435426dfab94/runtime/compiler/ilgen/Walker.cpp#L3929-L3930
