### ISSUE TITLE
SE80_GIT testvmcheck_1 - testLoadingClasses AssertionError: Child exited with non-zero stats expected:<0> but was:<1>

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10294] opened 2020-07-30 13:00 UTC
Failure link
------------

From an internal build `ibuild 452660`:
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pwa6480sr7-20200728_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200729_452660 (JIT enabled, AOT enabled)
OpenJ9   - ce556f8
OMR      - 21f4c44
IBM      - 2c50f8c)
JCL - 20200720_01 based on Oracle jdk8u261-b13
```

Optional info
-------------

- intermittent failure (yes): 

Failure output (captured from console output)
---------------------------------------------

```
{ itercnt=1; \
        mkdir -p "c:\\temp\\bld_452660\\testvmcheck_1"; \
        cd "c:\\temp\\bld_452660\\testvmcheck_1"; \
        "w:\\builds\\bld_452660/sdk/wa6480\\bin\\java"  -Xjit-Xgcpolicy:gencon -Xnocompressedrefs  \
        -cp "w:\\builds\\bld_452660/jvmtest/test/SE80\\TestConfig\\resources;w:\\builds\\bld_452660/jvmtest/test/SE80\\TKG\\lib\\testng.jar;

w:\\builds\\bld_452660/jvmtest/test/SE80\\TKG\\lib\\jcommander.jar;w:\\builds\\bld_452660/jvmtest/test/SE80\\functional\\Java8andUp\\General
Test.jar" \
        org.testng.TestNG -d "c:\\temp\\bld_452660\\testvmcheck_1" "w:\\builds\\bld_452660/jvmtest/test/SE80\\functional\\Java8andUp\\testng
.xml" \
        -testnames testvmcheck \
        -groups level.extended \
        -excludegroups d.*.win_x86-64,d.*.arch.x86,d.*.os.win,d.*.bits.64,d.*.generic-all; \
        if [ $? -eq 0 ] ; then echo ""; echo "testvmcheck_1""_PASSED"; echo ""; cd w:\\builds\\bld_452660/jvmtest/test/SE80;  else perl "-Iw

:\\builds\\bld_452660/../../javatest/HEAD_382595/test\\lib\\perl" -mResultStore::Uploader -e "ResultStore::Uploader::upload('.',452660,65235
6239,'vmfarm.ottawa.ibm.com:31','results-652356239')"; echo ""; echo "testvmcheck_1""_FAILED"; echo ""; fi; } 2>&1  tee -a "c:\\temp\\bld_4
52660\\TestTargetResult";

[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is w:\\builds\\bld_452660/jvmtest/test/SE80\\TestConfig\\resources\\excludes\\
current_exclude_8.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...Exception in thread "Thread-300" java.lang.AssertionError: TEST_STATUS=TEST_FAILED : com.oracle.net.Sdp
        at org.testng.Assert.fail(Assert.java:96)
        at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile$StreamDumper.run(TestLoadingClassesFromJarfile.java:252)
FAILED: testLoadingClasses
java.lang.AssertionError: Child exited with non-zero stats expected:<0> but was:<1>
        at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
        at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
        at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
        at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.createAndRunNewClassloadingTester(TestLoadingClassesFromJarfile.java:204)  
        at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.loadClassesFromJarfile(TestLoadingClassesFromJarfile.java:115
        at org.openj9.test.vmcheck.TestLoadingClassesFromJarfile.testLoadingClasses(TestLoadingClassesFromJarfile.java:80)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.testng.TestNG.privateMain(TestNG.java:1354)
        at org.testng.TestNG.main(TestNG.java:1323)===============================================
    testvmcheck
    Tests run: 1, Failures: 1, Skips: 0
```

**Comment by pshipton** [comment] 2020-07-30 15:27
This looks like a regression so I'm adding it to the next milestone.

**Comment by JasonFengJ9** [comment] 2020-08-12 12:04
Now this failure is seen across platforms in `ibuild 453452`.

**Comment by DanHeidinga** [comment] 2020-08-24 19:23
This hasn't gotten any investigation so I'm moving it out of the jdk15 (0.22) release.

**Comment by pshipton** [comment] 2020-09-25 17:45
@tajila this should get some investigation when someone has time.

**Comment by tajila** [comment] 2020-09-25 18:12
@JasonFengJ9 Can you please take a look at this

**Comment by JasonFengJ9** [comment] 2020-09-25 18:17
@tajila sure, will look into it.

**Closed** 2020-09-28 16:48 UTC
Labels: comp:vm, test failure
