### ISSUE TITLE
Test-sanity.system-JDK8-linux_x86-64_cmprssptrs LambdaLoadTest_ConcurrentScavenge_0 crash assert OOM

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#3491] opened 2018-10-31 03:04 UTC
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/122
```
LT  23:10:03.009 - Starting thread. Suite=0 thread=0
LT  23:10:03.010 - Starting thread. Suite=0 thread=1
LT  23:10:23.083 - Completed 22.0%. Number of tests started=44
LT  23:10:43.050 - Completed 22.0%. Number of tests started=44 (+0)
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=00007F664F2BBA60 Handler2=00007F664E6A9280 InaccessibleAddress=000000000000001A
LT  stderr RDI=00007F664802C620 RSI=00007F66487B8E18 RAX=00007F664802C4D0 RBX=0000000000000000
LT  stderr RCX=00007F66340A46D0 RDX=00007F66340A4890 R8=00007F66340A46E0 R9=00007F66340A46F0
LT  stderr R10=00000000E1980114 R11=0000000000000000 R12=00007F66340A46D0 R13=00007F664803A7A0
LT  stderr R14=00007F66340A46E0 R15=0000000000000000
LT  stderr RIP=00007F664C629F94 GS=0000 FS=0000 RSP=00007F66340A4630
LT  stderr EFlags=0000000000010246 CS=0033 RBP=00007F66340A4890 ERR=0000000000000004
LT  stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=000000000000001A
LT  stderr xmm0 e198e08ce198e08c (f: 3784892672.000000, d: -1.399002e+162)
LT  stderr xmm1 29450c20b853d46c (f: 3092501504.000000, d: 7.001475e-110)
LT  stderr xmm2 000e1781000e1781 (f: 923521.000000, d: 1.959708e-308)
LT  stderr xmm3 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr xmm4 007f007f007f007f (f: 8323199.000000, d: 2.759264e-306)
LT  stderr xmm5 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm7 006b007800690061 (f: 6881377.000000, d: 1.201621e-306)
LT  stderr xmm8 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
LT  stderr xmm9 3fb29305acb7410c (f: 2897690880.000000, d: 7.255588e-02)
LT  stderr xmm10 3d792505ce60559e (f: 3462419968.000000, d: 1.429306e-12)
LT  stderr xmm11 4031f303697e963f (f: 1769903616.000000, d: 1.794927e+01)
LT  stderr xmm12 bca8000000000000 (f: 0.000000, d: -1.665335e-16)
LT  stderr xmm13 3fb29305acb74100 (f: 2897690880.000000, d: 7.255588e-02)
LT  stderr xmm14 403205966f2b4d80 (f: 1865108864.000000, d: 1.802183e+01)
LT  stderr xmm15 3c5d1939471d9418 (f: 1193120768.000000, d: 6.309738e-18)
LT  stderr Module=/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so
LT  stderr Module_base_address=00007F664C42E000
LT  stderr Target=2_90_20181030_598 (Linux 4.4.0-134-generic)
LT  stderr CPU=amd64 (4 logical CPUs) (0x1f2ae3000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr Corruption in Evacuate at 00000000F828C520: calculated object size 34398413316 larger then available 64436960, Forwarded Header at 00007F6634C749E0
LT  stderr 23:10:43.010 0x259d200    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1290: ((false))
LT  stderr (0x00007F664C629F94 [libj9gc29.so+0x1fbf94])
LT  stderr (0x00007F664C5B4601 [libj9gc29.so+0x186601])
LT  stderr (0x00007F664C5FFF76 [libj9gc29.so+0x1d1f76])
LT  stderr (0x00007F664D26CCFB [libj9jit29.so+0x77acfb])
```

**Comment by pshipton** [comment] 2018-10-31 03:05
@0dvictor @amicic

**Comment by pshipton** [comment] 2018-10-31 11:54
More in the overnight builds last night
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/70
`LT  stderr JVMDUMP039I Processing dump event "abort", detail "" at 2018/10/31 06:19:37 - please wait.`
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/123
`LT  stderr 08:00:25.807 0xcbbe00    j9mm.108    *   ** ASSERTION FAILED ** at Scavenger.cpp:3416: (!(true || (_extensions->objectModel.isDeadObject(objectPtr))))`
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/126
`LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/10/31 09:59:52 - please wait.`

**Comment by pshipton** [comment] 2018-11-01 11:09
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/71
`DLT 06:16:36.788 - First failure detected by thread: load-0. Running test: ArbitraryJava[net.openj9.test.decimals.DecimalTestRunner invokeTest]. Creating java dumps.`
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/127/
```
LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/11/01 07:46:15 - please wait.
LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/11/01 07:46:15 - please wait.
```

**Comment by pshipton** [comment] 2018-11-01 13:05
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/125
```
LT  stderr Corruption in Evacuate at 00000000FD882C28: calculated object size 4302809396 larger then available 41407448, Forwarded Header at 00007FAF7A8F79E0
LT  stderr 12:45:30.749 0x824200    j9mm.141    *   ** ASSERTION FAILED ** at Scavenger.cpp:1290: ((false))
```

**Comment by dmitripivkine** [comment] 2018-11-01 16:34
@DanHeidinga FYI

**Comment by dmitripivkine** [comment] 2018-11-01 18:48
Failed an attempt to find object at `0xFD882C28` but it has been collected. Now this address points inside `!j9object 0xFD882C00`. The original address `0xFD882C28` has been taken from reference array
```
> !j9object 0xF2903598
!J9IndexableObject 0x00000000F2903598 {
    struct J9Class* clazz = !j9arrayclass 0x779200   // [L
    Object flags = 0x00000010;
    U_32 size = 0x00020000;
      [0] = !fj9object 0x0 = !j9object 0x0
      [1] = !fj9object 0xfffffffff19adfd0 = !j9object 0xf19adfd0
      [2] = !fj9object 0xfffffffffd882c28 = !j9object 0xfd882c28 <-----
      [3] = !fj9object 0x0 = !j9object 0x0
      [4] = !fj9object 0xfffffffffd940018 = !j9object 0xfd940018
      [5] = !fj9object 0x0 = !j9object 0x0
      [6] = !fj9object 0x0 = !j9object 0x0
      [7] = !fj9object 0x0 = !j9object 0x0
      [8] = !fj9object 0xfffffffffc320e38 = !j9object 0xfc320e38
      [9] = !fj9object 0xfffffffff19ae058 = !j9object 0xf19ae058
      [10] = !fj9object 0xfffffffff2840d98 = !j9object 0xf2840d98
      [11] = !fj9object 0x0 = !j9object 0x0
      [12] = !fj9object 0xfffffffff19ae088 = !j9object 0xf19ae088
      [13] = !fj9object 0x0 = !j9object 0x0
      [14] = !fj9object 0x0 = !j9object 0x0
      [15] = !fj9object 0x0 = !j9object 0x0
To print entire range: !j9indexableobject 0x00000000F2903598 0 131072
```
This array is a hash table:
```
> !j9object 0xFE36CC18
!J9Object 0x00000000FE36CC18 {
      struct J9Class* clazz = !j9class 0x776100   // java/util/HashMap
      Object flags = 0x00000080;
      I lockword = 0x00000000 (offset=0) (java/lang/Object) <hidden>
      Ljava/util/Set; keySet = !fj9object 0x0 (offset=4) (java/util/AbstractMap)
      Ljava/util/Collection; values = !fj9object 0x0 (offset=8) (java/util/AbstractMap)
      [Ljava/util/HashMap$Node; table = !fj9object 0xf2903598 (offset=12) (java/util/HashMap) <---
      Ljava/util/Set; entrySet = !fj9object 0x0 (offset=16) (java/util/HashMap)
      I size = 0x0000D610 (offset=20) (java/util/HashMap)
      I modCount = 0x0000D610 (offset=24) (java/util/HashMap)
      I threshold = 0x00018000 (offset=28) (java/util/HashMap)
      F loadFactor = 0x3F400000 (offset=32) (java/util/HashMap)
}
```
This hash table is referenced here:
```
> !j9object 0xFC013698
!J9Object 0x00000000FC013698 {
      struct J9Class* clazz = !j9class 0xC42600   // java/util/stream/ReduceOps$3ReducingSink
      Object flags = 0x00000080;
      I lockword = 0x00000000 (offset=0) (java/lang/Object) <hidden>
      Ljava/lang/Object; state = !fj9object 0xfe36cc18 (offset=4) (java/util/stream/ReduceOps$Box) <-----
      Ljava/util/function/Supplier; val$supplier = !fj9object 0xe1f4aae0 (offset=8) (java/util/stream/ReduceOps$3ReducingSink)
      Ljava/util/function/BiConsumer; val$accumulator = !fj9object 0xfc21df28 (offset=12) (java/util/stream/ReduceOps$3ReducingSink)
      Ljava/util/function/BinaryOperator; val$combiner = !fj9object 0xf13504b0 (offset=16) (java/util/stream/ReduceOps$3ReducingSink)
}
```

**Comment by pshipton** [comment] 2018-11-02 11:19
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/72/
```
LT  06:15:19.803 - First failure detected by thread: load-1. Running test: JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]. Creating java dumps.
```

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/129/
`LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/11/02 09:53:22 - please wait.`

**Comment by andrewcraik** [comment] 2018-11-02 12:28
@yanluo7 and @0dvictor will have a look at the JIT aspect on x86.

**Comment by pshipton** [comment] 2018-11-05 16:52
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/132
`LT  stderr JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2018/11/05 07:29:32 - please wait.`

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/72/
`LT  stderr JVMDUMP039I Processing dump event "abort", detail "" at 2018/11/05 07:31:04 - please wait.`

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/129/
`LT  stderr Corruption in Evacuate at 00000000F80FCD08: calculated object size 16313544413194223620 larger then available 66073336, Forwarded Header at 00007F000D7519E0`

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/75
```
JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]. Creating java dumps.
...
LT  11:05:51.187 - Test failed
LT    Failure num.  = 1
LT    Test number   = 12
LT    Test details  = 'JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  testStarted : testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFailure: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations): null
LT  java.lang.NullPointerException
LT  	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1118)
LT  	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1128)
LT  	at java.base/java.util.stream.Collectors$$Lambda$381.000000006C0072E0.accept(Unknown Source)
LT  	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
LT  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
LT  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
LT  	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
LT  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
LT  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
LT  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
LT  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
LT  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
LT  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
LT  	at java.base/java.util.stream.ReduceOps$ReduceTask.onCompletion(ReduceOps.java:958)
LT  	at java.base/java.util.concurrent.CountedCompleter.tryComplete(CountedCompleter.java:592)
LT  	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:328)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations$$Lambda$370.00000000880A9920.run(Unknown Source)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testCommonWord(TestParallelStreamOperations.java:244)
```

**Comment by pshipton** [comment] 2018-11-06 13:30
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/76
```
LT  07:07:45.744 - Test failed
LT    Failure num.  = 1
LT    Test number   = 12
LT    Test details  = 'JUnit[net.adoptopenjdk.test.streams.TestParallelStreamOperations]'
LT    Suite number  = 0
LT    Thread number = 0
LT  >>> Captured test output >>>
LT  testStarted : testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanMediumWords(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testAnyWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFinished: testRanContainLetter(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testStarted : testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations)
LT  testFailure: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations): java.lang.NullPointerException
LT  java.util.concurrent.ExecutionException: java.lang.NullPointerException
LT  	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
LT  	at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations$$Lambda$359.00000000D808BD30.run(Unknown Source)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testCommonWord(TestParallelStreamOperations.java:244)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/73/
```
LT  testFailure: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations): null
LT  java.lang.NullPointerException
LT  	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1118)
LT  	at java.base/java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1128)
LT  	at java.base/java.util.stream.Collectors$$Lambda$368.000000000C012200.accept(Unknown Source)
LT  	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
LT  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
LT  	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
LT  	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
LT  	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
LT  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
LT  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
LT  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
LT  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
LT  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.lambda$testCommonWord$27(TestParallelStreamOperations.java:312)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations$$Lambda$356.0000000038097100.run(Unknown Source)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testCommonWord(TestParallelStreamOperations.java:244)
LT  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/133
```
LT  testFailure: testCommonWord(net.adoptopenjdk.test.streams.TestParallelStreamOperations): java.lang.OutOfMemoryError
LT  java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError
LT  	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.lambda$testCommonWord$27(TestParallelStreamOperations.java:300)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations$$Lambda$63.000000009404F150.run(Unknown Source)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.runTest(TestParallelStreamOperations.java:343)
LT  	at net.adoptopenjdk.test.streams.TestParallelStreamOperations.testCommonWord(TestParallelStreamOperations.java:244)
LT  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/130
```
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=00007FB90F2BCB90 Handler2=00007FB90E6AAA20 InaccessibleAddress=000000000000001A
LT  stderr RDI=00007FB90802C620 RSI=00007FB908786138 RAX=00007FB90802C4D0 RBX=0000000000000000
LT  stderr RCX=00007FB8F6C9F6D0 RDX=00007FB8F6C9F890 R8=00007FB8F6C9F6E0 R9=00007FB8F6C9F6F0
LT  stderr R10=00000000E3A801AD R11=0000000000000000 R12=00007FB8F6C9F6D0 R13=00007FB90803A7A0
LT  stderr R14=00007FB8F6C9F6E0 R15=0000000000000000
LT  stderr RIP=00007FB90C629074 GS=0000 FS=0000 RSP=00007FB8F6C9F630
LT  stderr EFlags=0000000000010246 CS=0033 RBP=00007FB8F6C9F890 ERR=0000000000000004
LT  stderr TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=000000000000001A
LT  stderr xmm0 e3a8e205e3a8e205 (f: 3819495936.000000, d: -1.202011e+172)
LT  stderr xmm1 ed1c4d44f68c94c1 (f: 4136408320.000000, d: -3.902577e+217)
LT  stderr xmm2 000e1781000e1781 (f: 923521.000000, d: 1.959708e-308)
LT  stderr xmm3 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr xmm4 007f007f007f007f (f: 8323199.000000, d: 2.759264e-306)
LT  stderr xmm5 ffffffffffffffff (f: 4294967296.000000, d: -nan)
LT  stderr xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr xmm7 007a0071006f0063 (f: 7274595.000000, d: 2.314230e-306)
LT  stderr xmm8 3bbcc86800000000 (f: 0.000000, d: 6.095003e-21)
LT  stderr xmm9 3fc97f52b5ce75b3 (f: 3050206720.000000, d: 1.991981e-01)
LT  stderr xmm10 3d78348bef38e149 (f: 4013482240.000000, d: 1.375910e-12)
LT  stderr xmm11 40318722fc9f18ab (f: 4238285056.000000, d: 1.752788e+01)
LT  stderr xmm12 3cd9800000000000 (f: 0.000000, d: 1.415534e-15)
LT  stderr xmm13 bfc97f52b5ce7580 (f: 3050206720.000000, d: -1.991981e-01)
LT  stderr xmm14 4031542457337bc0 (f: 1462991872.000000, d: 1.732868e+01)
LT  stderr xmm15 3c6d878a31553a8d (f: 827669120.000000, d: 1.280636e-17)
LT  stderr Module=/home/jenkins/workspace/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/openjdkbinary/j2sdk-image/jre/lib/amd64/compressedrefs/libj9gc29.so
LT  stderr Module_base_address=00007FB90C42D000
LT  stderr Target=2_90_20181106_615 (Linux 4.4.0-134-generic)
LT  stderr CPU=amd64 (4 logical CPUs) (0x1f2ae3000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x00007FB90C629074 [libj9gc29.so+0x1fc074])
LT  stderr (0x00007FB90C5B36E1 [libj9gc29.so+0x1866e1])
LT  stderr (0x00007FB90C5FF056 [libj9gc29.so+0x1d2056])
LT  stderr (0x00007FB90D26CF0B [libj9jit29.so+0x77bf0b])
```

**Comment by DanHeidinga** [comment] 2018-11-06 13:51
> @yanluo7 and @0dvictor will have a look at the JIT aspect on x86.

@yanluo7 & @0dvictor Can you provide the current status on this?  It's hitting every nightly build right now

**Comment by yanluo7** [comment] 2018-11-07 18:41
Been trying to narrow down the methods w/ travis grinder. Hitting an issue where the grinder/test script unable to parse `-Xjit:"..."` option, tried with single, double, and no quotes all failed. Working w/ infra to sort this out.

**Comment by pshipton** [comment] 2018-11-08 11:35
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/135
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/132
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/75

**Comment by pshipton** [comment] 2018-11-12 14:12
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/81
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/78
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/138

**Comment by DanHeidinga** [comment] 2018-11-12 14:56
@yanluo7 Can you add the `-Xjit` option to the `IBM_JAVA_OPTIONS` environment variable?  That may work around the grinder script having to parse it.

Given the regularity of the failures, do you need the grinder or can it be tested on a local machine?  Feel free to ping me via Slack if you need help finding a machine to test this on

**Comment by smlambert** [comment] 2018-11-12 17:33
Assume this issue is related: https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/188

**Comment by smlambert** [comment] 2018-11-12 17:48
Running internal Grinder/#700 (based off @yanluo7 Grinders which look like tanked with a machine issue).

**Comment by pshipton** [comment] 2018-11-13 15:51
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/139
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/79
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/136

**Comment by yanluo7** [comment] 2018-11-13 21:04
With help from Mesbah, found a workaround re. parsing of -Xjit argument -- needed to escape the `"` characters. As earlier analysis indicated that the underlying object array of a HashMap object contains bad object pointer, so narrowing down among HashMap.* methods. So far if one method- HashMap.resize is compiled with oplevel cold or noopt, the failure disappears. Getting a log to see...

**Comment by pshipton** [comment] 2018-11-14 15:37
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/83
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/137
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/140
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/80

**Comment by pshipton** [comment] 2018-11-15 14:21
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/81
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/84
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/138
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/141

**Comment by pshipton** [comment] 2018-11-21 13:47
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64/146

**Comment by DanHeidinga** [comment] 2018-11-22 14:58
@yanluo7 How is this progressing?  The last update indicated a workaround for the grinder issue - has that unblocked the rest of the investigation?

**Comment by yanluo7** [comment] 2018-11-22 15:00
With some struggle and help from infra team Mesbah I'm now able to build the system test and run lambda test locally on bowlcut or poisonivy. Looking at 2 core files reproduced locally, both are due to assertion during mark when an object encountered is already forwarded: 
e.g. ```Encountered object 00000000FCEB59B0 forwarded to 00000000FD27B100 (header 00007F0AAE1F9920) while Concurrent Scavenger/Marking not in progress```
In both cases, the forwarded object is an array of String objects. Searching the heap for the forwarded array didn't return any hits.

Tried running with `gconresolve rtresolve`, but the problem failed to reproduce with these 2 options.
Also adding `alwaysCallWritebarrier` caused a different crash in the interpreter where we try to do a virtual dispatch and the receiver is some garbage value; the `alwaysCallWritebarrier` maybe not the real issue as it's possible alwaysCallWritebarrier might not work under CS. 
I'm trying to generate builds where we always call the GC rdbar helper from the jitted code, and disable array copy optimization as the problems seen seem to be related to arrays.

**Comment by pshipton** [comment] 2018-11-23 12:02
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK8-linux_x86-64_cmprssptrs/145

**Comment by yanluo7** [comment] 2018-11-23 20:44
Rebuilt a JIT that always calls the readbar helper in readbarEvluator and disabled reference array copy support, but the problem is still there -- with similar symptom as a previous reported case: GC encountered a forwarded pointer, the forwarded obejct is an `HashMap$Node`, which belongs to a large reference array in tenure.
In another attempt, I simply excluded all methods from `j/u/HashMap` and `j/u/Arraylist`, but the problem still remained. I'm attempting to narrow down using a limitfile.

**Comment by yanluo7** [comment] 2018-11-26 19:54
I'm trying to narrow down the methods using a limit file. Total number of compiled methods up to the point of assert/crash is around 1800. Currently narrowing down to about 1000...

**Comment by pshipton** [comment] 2018-11-27 12:57
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64_cmprssptrs/95
https://ci.eclipse.org/openj9/job/Test-sanity.system-JDK11-linux_x86-64/92

**Comment by yanluo7** [comment] 2018-11-27 23:42
Continuing to narrow down the methods, down to about 30 currently...Hopefully this can lead to a handful of methods to focus on.

**Comment by yanluo7** [comment] 2018-11-28 18:59
Limit file debug continues, currently down to about 17 methods...

**Comment by yanluo7** [comment] 2018-11-29 23:14
Currently down to about 3-4 methods, I'm trying to make sure the offending method is one of those methods. as more methods get excluded both the test runtime and the indeterminacy increase substantially.

**Comment by yanluo7** [comment] 2018-12-07 21:15
The fix for the aforementioned 2 problems is merged in pr 3293. These bugs are not CS specific and affect every platform and gencon. It should fix some existing CS problems including one reported by Jimmy on Power running SPECjbb2015. However, with this fix I can still see lambda test failing, and if I disabled the wrtbar versioning opt, the failure goes away. Andrew and I believe this opt is somewhat flawed and under CS the concurrent GC can more readily expose it. We are designing a fix for that.

**Comment by DanHeidinga** [comment] 2018-12-13 20:36
> We are designing a fix for that.

@yanluo7 Any update on this fix?

**Comment by yanluo7** [comment] 2018-12-17 16:23
Working on a fix to limit wrtbar versioning in loop versioner to be less agressive, it's being PR'd.

**Comment by yanluo7** [comment] 2019-01-02 19:41
https://github.com/eclipse/omr/pull/3336 has been merged.

**Comment by pshipton** [comment] 2019-01-08 05:00
@yanluo7 does the merge of eclipse/omr#3336 resolve this problem? i.e. should we revert AdoptOpenJDK/openjdk-tests#752 and start running the test again?

**Comment by DanHeidinga** [comment] 2019-01-10 20:36
@yanluo7 Are you able to respond to @pshipton's comments above?

**Comment by smlambert** [comment] 2019-01-11 01:01
20x grinder: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/153/

**Comment by smlambert** [comment] 2019-01-11 03:04
20x with -Xjit appended via EXTRA_OPTIONS: https://ci.eclipse.org/openj9/view/Test/job/Test-Grinder/156/

**Comment by pshipton** [comment] 2019-01-11 12:33
@smlambert please re-enable the test, and we can closet this issue. I believe it originally failed every time or at least very frequently. 

I'd remove the the "test excluded" label from this issue once the test is enabled. Not sure if you have been doing this for other issues, but for tracking it seems better if only issues have actively have an excluded test have the label.

**Comment by smlambert** [comment] 2019-01-11 14:21
Yes, I have been removing the 'test excluded' label, so that we can use that as a mechanism for checking whats done... if an issue is closed and still has a test excluded label, then we need to act (with the exception of permanently excluded tests, which currently I mark with the test excluded + invalid labels).

**Comment by smlambert** [comment] 2019-01-11 15:13
Re-included: https://github.com/AdoptOpenJDK/openjdk-tests/pull/794

**Closed** 2019-01-11 15:14 UTC
Labels: comp:jit, test failure
