### ISSUE TITLE
80 VM_Extended.testDTFJ - AssertionFailedError : root frame of call stack must not be null

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10228] opened 2020-07-23 12:10 UTC
Failure link
------------

From an internal build `ibuild 452093`:
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20200707_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200722_452093 (JIT enabled, AOT enabled)
OpenJ9   - a63efb3
OMR      - c680503
IBM      - 78612de)
JCL - 20200706_01 based on Oracle jdk8u261-b13
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
JUnit.summary:
  [summary] Processed 137 test cases
     [echo] Test failure : com.ibm.dtfj.tck.tests.javaruntime.TestJavaRuntimeThreads
     [echo] Test case    : testWalkAllThreads
     [echo] Failure type : junit.framework.AssertionFailedError
     [echo] junit.framework.AssertionFailedError: [thread: Dedicated GC Main] root frame of call stack must not be null
     [echo] 	at com.ibm.dtfj.tck.tests.javaruntime.TestJavaRuntimeThreads.testWalkAllThreads(TestJavaRuntimeThreads.java:110)
     [echo] 	at com.ibm.dtfj.tck.harness.AbstractTCKTestcase.runTest(AbstractTCKTestcase.java:54)

BUILD FAILED
/bluebird/builds/bld_452093/jvmtest/VM/dtfj_tck/tck.xml:377: One or more TCK runs failed a junit test
```

**Comment by pshipton** [comment] 2020-07-23 13:29
@theresa-m this is an internal problem, but caused by your rename change. The TestJavaRuntimeThreads test contains the following at least, which needs to be updated.

		excludedThreads.add("gc slave");
		excludedThreads.add("gc slave thread");

		excludedThreads.add("dedicated gc master");
		excludedThreads.add("dedicated gc master thread");

**Comment by pshipton** [comment] 2020-07-23 13:29
The code is in the rtctest repo.

**Comment by theresa-m** [comment] 2020-07-23 15:54
Thanks. I will create a pr.

**Comment by pshipton** [comment] 2020-07-23 17:50
PR is merged, problem should be fixed now.

**Closed by pshipton** 2020-07-23 17:50 UTC
Labels: comp:test, test failure
