### ISSUE TITLE
Java 11 getModule returning null for some classes

### ISSUE THREAD

**Issue by andrewcraik** [eclipse/openj9#8993] opened 2020-03-26 14:59 UTC
Java -version output
--------------------

```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+8-202003231120)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-51420720e, JRE 11 Linux amd64-64-Bit Compressed References 20200323_542 (JIT enabled, AOT enabled)
OpenJ9   - 51420720e
OMR      - 24a81ac88
JCL      - d1ca0ebebe based on jdk-11.0.7+8)
```

Summary of problem
------------------
The JVM is failing to set the module on some `java.lang.Class` objects. The function `getModule()` in `java.lang.Class` should not return null, but there are classes with a null module. I found this by writing a JVMTI agent which uses the VMDeath handle to process all loaded classes in the course of calling `getResource` on some of these classes I get an internal NPE from `getResource` due to a null module.

Diagnostic files
----------------
Some source code to generate an agent to provoke the problem:

```
JNIEXPORT
void JNICALL
VMDeath(jvmtiEnv *jvmti, JNIEnv* env)
{
    jvmtiError err;
    printf("\nStart Shutdown Processing\n");
    jint classCount = 0;
    jclass *clazzItr;
    if (jvmti->GetLoadedClasses(&classCount, &clazzItr) != 0)
       return;
    // call getModule using JNI on clazzItr here - some will have a null result which should not happen
}

JNIEXPORT jint JNICALL
Agent_OnLoad(JavaVM *vm, char *options, void *reserved) {
    jvmtiEnv *jvmti;
    //Get JVMTI environment
    jint result = vm->GetEnv((void**)&jvmti, JVMTI_VERSION_1_2);
    if(result != 0){
        return JNI_FALSE;
    }
    jvmti->SetEventNotificationMode(JVMTI_ENABLE, JVMTI_EVENT_VM_DEATH, NULL);
    jvmtiEventCallbacks callbacks;
    (void)memset(&callbacks, 0, sizeof(callbacks));
    callbacks.VMDeath = &VMDeath;
    jvmti->SetEventCallbacks(&callbacks, (jint)sizeof(callbacks));
    printf("\nSizeAgent Loaded\n");
    return JNI_OK;
}
```

**Comment by JasonFengJ9** [comment] 2020-03-26 15:21
`Java -version` appears a bit confusing which is `Java 8` without modularity support.

**Comment by DanHeidinga** [comment] 2020-03-26 17:35
Assuming the wrong `java -version` was pasted, I think Andrew's highlighted a real issue.

Code that should be setting the java.base module walks all the loaded classes in the `vm->systemClassLoader` which does a walk of the Class Segments processing those with the matching classloader: https://github.com/eclipse/openj9/blob/c80af2e8aba83e2adeacd3741aeaf9275a81a946/runtime/j9vm/java11vmi.c#L806-L812

VM Anonymous classes - those loaded by Unsafe.defineAnonymousClass - will have a different loader in their memory segments and will be missed by that `allClassesNextDo` walk.

**Comment by JasonFengJ9** [comment] 2020-03-26 21:32
Attempting a testcase to reproduce the issue.

**Comment by DanHeidinga** [comment] 2020-03-27 04:50
@JasonFengJ9 Generate a core just after `java.base` has been defined and assigned to all the classes.  Then check if there are any classes in the InternalAnonymousClassloader that don't have their module set yet

**Comment by JasonFengJ9** [comment] 2020-03-27 11:55
@DanHeidinga I added code iterating the classes loaded by `InternalAnonymousClassloader` (assuming `vm->anonClassLoader`) as following:
https://github.com/eclipse/openj9/blob/8f1432c3a7afb8ca49debb0a3b8fab652bde31f7/runtime/j9vm/java11vmi.c#L813-L815
```
	Assert_SC_notNull(vm->anonClassLoader);
	J9ClassWalkState classWalkStateAnon = {0};
	J9Class* clazzAnon = vmFuncs->allClassesStartDo(&classWalkStateAnon, vm, vm->anonClassLoader);
	printf("Looking for clazzAnon within vm->anonClassLoader \n");
	while (NULL != clazzAnon) {
		printf("found a clazzAnon %p \n", clazzAnon);
		j9object_t moduleObjectAnon = J9VMJAVALANGCLASS_MODULE(currentThread, clazzAnon->classObject);
		Assert_SC_notNull(moduleObjectAnon);
		J9Module *moduleAnon = J9OBJECT_ADDRESS_LOAD(vmThread, moduleObjectAnon, vm->modulePointerOffset);
		Assert_SC_notNull(moduleAnon);
		clazzAnon = vmFuncs->allClassesNextDo(&classWalkStateAnon);
	}
	vmFuncs->allClassesEndDo(&classWalkStateAnon);
```
Run a few simple apps, _Looking for clazzAnon within vm->anonClassLoader_ was in the output but not _found a clazzAnon_.
This indicates that there was no class loaded by `vm->anonClassLoader` right after module `java.base` is created.

On the other hand, I didn't have luck to build a testcase reproducing the issue. 
`JVMTI_EVENT_VM_DEATH` notifies the agent of the termination of the `VM`. No events will occur after the `VMDeath` event. At that time, some modules might have been unloaded and freed though the module object within classes won't be cleared (causing `null` module reference), and just become invalid (i.e., invalid modules can cause crash if they are accessed somehow).
Capturing a Java stacktrace when the `null` module reference is returned could provide some hints.

**Comment by DanHeidinga** [comment] 2020-03-27 19:00
Is the `javaVM->anonClassCount ` non-zero at that point?

**Comment by JasonFengJ9** [comment] 2020-03-27 19:22
> Is the javaVM->anonClassCount non-zero at that point?

Modified `printf` above to `printf("Looking for clazzAnon within vm->anonClassLoader (%p) vm->anonClassCount (%lu) \n", vm->anonClassLoader, vm->anonClassCount);` which gives following output:
```
Looking for clazzAnon within vm->anonClassLoader (0x7fae65869248) vm->anonClassCount (0) 
```
So this also indicates that there is no classes loaded by `anonClassLoader` right after module `java.base` is created unless some classes loaded later weren't set properly with module object even after `java.base` creation.

**Comment by DanHeidinga** [comment] 2020-03-27 19:29
I still think we have a hole here but will need some time to contrive the test case to demonstrate it.  

@andrewcraik Can you confirm the java -version output?

**Comment by andrewcraik** [comment] 2020-03-27 19:35
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-202003241739-b06)
Eclipse OpenJ9 VM (build master-398fa6730, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200324_576 (JIT enabled, AOT enabled)
OpenJ9   - 398fa6730
OMR      - dc5747bc9
JCL      - 61ecedabf89 based on jdk8u252-b06)

**Comment by DanHeidinga** [comment] 2020-03-27 19:50
@andrewcraik That's a JDK 8 build - it doesn't have modules :)

**Comment by andrewcraik** [comment] 2020-03-27 20:02
@DanHeidinga sorry was experimenting with both 8 and 11 - 11 version posted

**Comment by JasonFengJ9** [comment] 2020-03-30 12:57
@andrewcraik just got couple of questions for followup investigation,  does `RI` (`JDK11` hotspot) return `null` module for the same testcase assuming it runs on `RI` as well? In addition, is there a stacktrace available by any chance when the `NPE` occurred?

**Comment by andrewcraik** [comment] 2020-03-30 13:37
@JasonFengJ9 `JDK11` hotspot does NOT return `null` running the same test. The exception I got was
```
Exception in thread "DestroyJavaVM helper thread" java.lang.NullPointerException
        at java.base/java.lang.Class.useModularSearch(Class.java:1917)
        at java.base/java.lang.Class.getResource(Class.java:1848)
```
The code in Class.java does not handle a null module return at Class.java 1917 and getModule does not suggest it can ever validly return null so I believe the correct thing is for all classes to a non-null module. Note in the above case my JVMTI agent was calling getResource on a class returned from the JVMTI load event but getModule called directly returned null in my testing.

**Comment by JasonFengJ9** [comment] 2020-03-30 14:00
Thanks @andrewcraik for the explanation, you are right that `java.lang.Class.getModule()` returns a non-null module.

Just to confirm that the `NPE` was thrown at following line of `if (thisModule.isNamed()) {`, correct?
```
private boolean useModularSearch(String absoluteResName, Module thisModule, Class<?> callerClass) {
	boolean visible = false;

L1916	if (thisModule.isNamed()) {.  ---> NPE here?
L1917		final Module callerModule = callerClass.getModule();
		visible = (thisModule == callerModule);
```
My `Java 11 pConfig` has `Class.java:1917` at `final Module callerModule = callerClass.getModule();` somehow.

**Comment by andrewcraik** [comment] 2020-03-30 14:55
yes I believe it was the `thisModule.isNamed()`

**Comment by JasonFengJ9** [comment] 2020-04-01 01:09
Build a testcase to get following stacktrace:
```
1XMCURTHDINFO  Current thread
3XMTHREADINFO      "main" J9VMThread:0x00000000192DCA00, omrthread_t:0x00007F823A805C50, java/lang/Thread:0x00000007FFF03FE0, state:R, prio=5
3XMJAVALTHREAD            (java/lang/Thread getId:0x1, isDaemon:false)
3XMTHREADINFO1            (native thread ID:0x9264A2, native priority:0x5, native policy:UNKNOWN, vmstate:R, vm thread flags:0x00001020)
3XMTHREADINFO2            (native stack address range from:0x000070000925B000, to:0x00007000092DB000, size:0x80000)
3XMCPUTIME               CPU usage total: 0.214851000 secs, current category="System-JVM"
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=674520 (0xA4AD8)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/lang/Class.useModularSearch(Class.java:1917)
4XESTACKTRACE                at java/lang/Class.getResource(Class.java:1848)
3XMTHREADINFO3           No native callstack available for this thread
```
The `NPE` was thrown at https://github.com/eclipse/openj9/blob/e3fd4465c807cdca6628ef2a11af875ecfc2b18f/jcl/src/java.base/share/classes/java/lang/Class.java#L2022 
The `null callerClass` is from https://github.com/eclipse/openj9/blob/e3fd4465c807cdca6628ef2a11af875ecfc2b18f/jcl/src/java.base/share/classes/java/lang/Class.java#L1947

The `NPE` was due to `null callerClass` which is returned from `System.getCallerClass()`.
The test scenario is to invoke `jobject resThread = (*env)->CallObjectMethod(env, clzThreadClass, midClassGetResource, (*env)->NewStringUTF(env, "Thread.class"));` within a JVMTI (such as `VMInit` or `VMDeath`) callback method.
```
<0000000009521A00> INL native method frame: bp = 000000000960F900, sp = 000000000960F8E0, pc = 0000000000000003, cp = 0000000000000000, arg0EA = 000000000960F908, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/Class.getStackClass(I)Ljava/lang/Class; (000000000954E348) . ---> the depth here is 2
<0000000009521A00> Bytecode frame: bp = 000000000960F920, sp = 000000000960F910, pc = 000000003388472D, cp = 000000000956FD60, arg0EA = 000000000960F920, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/System.getCallerClass()Ljava/lang/Class; (0000000009570FC0) 
<0000000009521A00> Bytecode frame: bp = 000000000960F950, sp = 000000000960F928, pc = 0000000033840850, cp = 000000000954B310, arg0EA = 000000000960F988, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/Class.getResource(Ljava/lang/String;)Ljava/net/URL; (000000000954E0C8)
<0000000009521A00> JNI call-in frame: bp = 000000000960F9B0, sp = 000000000960F990, pc = 00000000062BD208, cp = 0000000000000000, arg0EA = 000000000960F9B0, flags = 0000000000030000
<0000000009521A00> 	New ELS = 0000000000000000
<0000000009521A00> JNI native method frame: bp = 000000000960F9F0, sp = 000000000960F9B8, pc = 0000000000000007, cp = 0000000000000000, arg0EA = 000000000960FA00, flags = 0000000000000003
<0000000009521A00> JNI native method frame: bp = 000000000960FAA8, sp = 000000000960FA08, pc = 0000000000000007, cp = 0000000000000000, arg0EA = 000000000960FAA8, flags = 0000000000010010
<0000000009521A00> <end of stack>
```

On the other hand, invoking `jobject resThread = (*env)->CallObjectMethod(env, clzThreadClass, midClassGetResource, (*env)->NewStringUTF(env, "Thread.class"));` within a JNI method directly from Java can get a valid result while `System.getCallerClass()` retrieved expected class object.
```
<0000000009521A00> INL native method frame: bp = 000000000960F8A8, sp = 000000000960F888, pc = 0000000000000003, cp = 0000000000000000, arg0EA = 000000000960F8B0, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/Class.getStackClass(I)Ljava/lang/Class; (000000000954E348)
<0000000009521A00> Bytecode frame: bp = 000000000960F8C8, sp = 000000000960F8B8, pc = 000000003388472D, cp = 000000000956FD60, arg0EA = 000000000960F8C8, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/System.getCallerClass()Ljava/lang/Class; (0000000009570FC0)
<0000000009521A00> Bytecode frame: bp = 000000000960F8F8, sp = 000000000960F8D0, pc = 0000000033840850, cp = 000000000954B310, arg0EA = 000000000960F930, flags = 0000000000000000
<0000000009521A00> 	Method: java/lang/Class.getResource(Ljava/lang/String;)Ljava/net/URL; (000000000954E0C8)
<0000000009521A00> JNI call-in frame: bp = 000000000960F958, sp = 000000000960F938, pc = 00000000062BD208, cp = 0000000000000000, arg0EA = 000000000960F958, flags = 0000000000030000
<0000000009521A00> 	New ELS = 000070000BF85A88
<0000000009521A00> JNI native method frame: bp = 000000000960F998, sp = 000000000960F960, pc = 0000000000000007, cp = 0000000000000000, arg0EA = 000000000960F9A0, flags = 0000000000000003
<0000000009521A00> 	Method: test/jni/TestSimpleJNI.hello()[Ljava/lang/Class; (0000000009695928)
<0000000009521A00> *** END STACK WALK (rc = 0) ***
```

`Class.getStackClass(depth)` calls `inlVMGetStackClass()` which uses `walkStackFrames()` with `cInterpGetStackClassJEP176Iterator`.
Still looking into how `walkStackFrames` missed the class object in question.

**Comment by JasonFengJ9** [comment] 2020-04-01 20:06
@andrewcraik could you help run a test build (link below) against the testcase, and advise the result?

`OpenJ9-JDK11-x86-64_linux-20200401-150444.tar.gz`
https://ibm.box.com/s/fd3yz6grvyx4nbohepgu1j6izjsw4di9

**Comment by andrewcraik** [comment] 2020-04-07 18:04
The test worked with the supplied JVM - sorry for the delay. Your change seems to fix it.

**Comment by JasonFengJ9** [comment] 2020-04-07 18:10
Thanks for running the test @andrewcraik !

Am going to submit a PR.

**Closed** 2020-04-08 14:42 UTC
Labels: comp:vm, userRaised

**Comment by DanHeidinga** [comment] 2020-04-08 14:56
I extracted #9183 to address setting the module in vm anon classes as I believe there is still an issue there
