### ISSUE TITLE
JDK16 UnsupportedOperationException: ByteBuffer not supported

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11390] opened 2020-12-07 21:53 UTC
Failure link
------------

From an internal build `Test_openjdknext_j9_sanity.openjdk_s390x_linux_Nightly/325`:
```
21:55:49  openjdk version "16-internal" 2021-03-16
21:55:49  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:55:49  Eclipse OpenJ9 VM (build master-c757b511544, JRE 16 Linux s390x-64-Bit Compressed References 20201206_405 (JIT enabled, AOT enabled)
21:55:49  OpenJ9   - c757b511544
21:55:49  OMR      - c3c479f9d59
21:55:49  JCL      - ac04db2e394 based on jdk-16+27)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
22:52:08  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=16&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=s390x_linux&TARGET=jdk11_tier1_cipher_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
22:50:05  ===============================================
22:50:05  Running test jdk11_tier1_cipher_0 ...
22:50:05  ===============================================

22:50:19  STDERR:
22:50:19  java.lang.UnsupportedOperationException: ByteBuffer not supported
22:50:19  	at java.base/com.sun.crypto.provider.FeedbackCipher.encryptFinal(FeedbackCipher.java:261)
22:50:19  	at java.base/com.sun.crypto.provider.CipherCore.gcmDoFinal(CipherCore.java:1313)
22:50:19  	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:671)
22:50:19  	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
22:50:19  	at Encrypt.combination_13(Encrypt.java:607)
22:50:19  	at Encrypt.execute(Encrypt.java:227)
22:50:19  	at Encrypt.doTest(Encrypt.java:156)
22:50:19  	at Encrypt.main(Encrypt.java:140)
22:50:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
22:50:19  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
22:50:19  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
22:50:19  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
22:50:19  	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
22:50:19  	at java.base/java.lang.Thread.run(Thread.java:853)
22:50:19  
22:50:19  JavaTest Message: Test threw exception: java.lang.UnsupportedOperationException
22:50:19  JavaTest Message: shutting down test
22:50:19  
22:50:19  STDOUT:
22:50:19  Test transformation = AES/GCM/NoPadding, textLength = 0, AADLength = 0
22:50:19  
22:50:19  TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.UnsupportedOperationException: ByteBuffer not supported
```

**Comment by pshipton** [comment] 2020-12-08 01:29
@JasonFengJ9 I assume this isn't an intermittent problem and occurs across platforms?

Not sure if this is a temporary bug in OpenJDK, or a problem introduced by the openssl support. We can re-run the test with `-Djdk.nativeCrypto=false` to see if it still fails.

**Comment by pshipton** [comment] 2020-12-08 01:32
It would be nice to know what test case is being run.

**Comment by pshipton** [comment] 2020-12-08 01:37
Seems all of these:
com/sun/crypto/provider/Cipher/AEAD/Encrypt.java.Encrypt
com/sun/crypto/provider/Cipher/AEAD/GCMBufferTest.java.GCMBufferTest
com/sun/crypto/provider/Cipher/AEAD/OverlapByteBuffer.java.OverlapByteBuffer
com/sun/crypto/provider/Cipher/AEAD/SameBuffer.java.SameBuffer

**Comment by pshipton** [comment] 2020-12-08 01:55
https://ci.eclipse.org/openj9/view/Test/job/Grinder/1261 passed com/sun/crypto/provider/Cipher/AEAD/GCMBufferTest.java with `-Djdk.nativeCrypto=false`. I'll try the entire jdk11_tier1_cipher_0 suite.

**Comment by JasonFengJ9** [comment] 2020-12-08 02:04
Similarly with https://github.com/eclipse/openj9/issues/11391#issuecomment-740309497, this occurred across platform and is a regression between following two builds.
Good build:
```
21:51:12  openjdk version "16-internal" 2021-03-16
21:51:12  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:51:12  Eclipse OpenJ9 VM (build master-9f11871a18a, JRE 16 Linux s390x-64-Bit Compressed References 20201202_402 (JIT enabled, AOT enabled)
21:51:12  OpenJ9   - 9f11871a18a
21:51:12  OMR      - a58cd2f5687
21:51:12  JCL      - f7021059fd3 based on jdk-16+26)
```

Bad build:
```
21:54:32  openjdk version "16-internal" 2021-03-16
21:54:32  OpenJDK Runtime Environment (build 16-internal+0-adhoc.jenkins.BuildJDKnexts390xlinuxNightly)
21:54:32  Eclipse OpenJ9 VM (build master-c757b511544, JRE 16 Linux s390x-64-Bit Compressed References 20201205_404 (JIT enabled, AOT enabled)
21:54:32  OpenJ9   - c757b511544
21:54:32  OMR      - c3c479f9d59
21:54:32  JCL      - a40d4ba969a based on jdk-16+27)
```

**Comment by pshipton** [comment] 2020-12-08 02:55
https://github.com/ibmruntimes/openj9-openjdk-jdk/compare/f7021059fd3...a40d4ba969a
I expect openssl support isn't compatible with `8253821: Improve ByteBuffer performance with GCM`
@ashbm5

**Comment by ashbm5** [comment] 2020-12-08 14:54
@samasri please have a look, looks like some updates from OpenJDK broke openssl support

**Comment by samasri** [comment] 2020-12-11 18:28
The issue is happening because a new function `AESCipher.engineDoFinal` that accepts ByteBuffer input was added to override the default behaviour but there is no implementation that deals with ByteBuffer input.

The progam execution is as follows:
* [Cipher.doFinal(ByteBuffer src, ByteBuffer dst)](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e39441f285acebb657aa388043a894770/src/java.base/share/classes/javax/crypto/Cipher.java#L2483-L2501) is called from the Encrypt.java test.
* Then, [AESCipher.engineDoFinal(ByteBuffer,ByteBuffer)](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e394/src/java.base/share/classes/com/sun/crypto/provider/AESCipher.java#L667-L676) is called. This is the overridden function. Otherwise, the default [CipherSpi.engineDoFinal](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e39441f285acebb657aa388043a894770/src/java.base/share/classes/javax/crypto/CipherSpi.java#L732-L736) would've been called.
* After that, [CipherCore.gcmDoFinal(ByteBuffer,ByteBuffer)](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e39441f285acebb657aa388043a894770/src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java#L1297-L1315) is called.
* The above function calls [cipher.encryptFinal(ByteBuffer, ByteBuffer)](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e39441f285acebb657aa388043a894770/src/java.base/share/classes/com/sun/crypto/provider/CipherCore.java#L1313). `cipher` is an instance of a class that does not have an implementation `encryptFinal(ByteBuffer,ByteBuffer)`. Hence, java goes to the default implementation in the parent class: [FeedbackCipher.encryptFinal(ByteBuffer,ByteBuffer)](https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/ac04db2e39441f285acebb657aa388043a894770/src/java.base/share/classes/com/sun/crypto/provider/FeedbackCipher.java#L259-L262) throws an exception.

To fix this, I will be writing a function `encryptFinal(ByteByffer src, ByteBuffer dst)` in the right class (the one which `cipher` is an instance of) to unpack the ByteBuffers to arrays and then use the native implementation if its enabled.

**Comment by samasri** [comment] 2020-12-18 21:49
I implemented the necessary functions in `NativeGaloisCounterMode`. Now the `Encrypt`, `OverlapByteBuffer`, and `SameBuffer` tests are passing. Currently, the JDK passes the same tests like the good JDK (described in [Jason's comment](https://github.com/eclipse/openj9/issues/11390#issuecomment-740311645)). However, both JDKs (the good one and the current one) are still failing these tests: `GCMBufferTest`, `GCMIncrementByte4`, and `GCMIncrementDirect4`. Note that I am only running the tests in AES and AEAD directories for now since these are the ones that look like they have GCM tests. I will later do full unit tests when the AEAD and AES tests are all passing.

So for now, I will be working on fixing those bugs while making sure the fixes do not affect performance.

**Comment by samasri** [comment] 2021-01-05 20:55
After applying the two commits in [this branch](https://github.com/samasri/openj9-openjdk-jdk/commits/fix-11390), all the tests are passing now.

jdk11_tier1_cipher_0  test results with JDK built using the mentioned commits: https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdknext_j9_sanity.openjdk_x86-64_linux_Nightly/386/

I will be testing it for performance (to make sure the changes didn't decrease performance) and then open a PR for it.

**Comment by pshipton** [comment] 2021-02-08 23:24
Created https://github.com/AdoptOpenJDK/openjdk-tests/pull/2249 to exclude the failing tests until they can be fixed.

**Comment by pshipton** [comment] 2021-02-11 20:50
The fixes are merged.

**Closed by pshipton** 2021-02-11 20:50 UTC
Labels: blocker, comp:openssl, jdk16, test failure
