### ISSUE TITLE
Netbeans 10 crashes during loading modules macos JDK11

### ISSUE THREAD

**Issue by kirill-zhukov** [eclipse/openj9#4557] opened 2019-02-02 17:13 UTC
Netbeans 10 incubater so release version crashes during startup on loading modules. Netbeans 8.2 has the same problems though expected that it should not work with JDK11. Used JDK11.02 from https://adoptopenjdk.net. Netbeans throws class loader exception. So there's I guess definitely a compatibility issue.

**Comment by DanHeidinga** [comment] 2019-02-03 00:42
Thanks @kirill-zhukov for opening this issue.  Can you provide the `java -version` output from the Adopt build and the stacktrace from the exception?

**Comment by JasonFengJ9** [comment] 2019-02-03 13:50
Will have a look.

**Comment by JasonFengJ9** [comment] 2019-02-03 15:35
Somehow I can't reproduce it. Downloaded [Apache NetBeans 10.0](https://www-eu.apache.org/dist/incubator/netbeans/incubating-netbeans/incubating-10.0/incubating-netbeans-10.0-bin.zip), and [OpenJ9 JDK11](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_mac_openj9_11.0.2_9_openj9-0.12.0.tar.gz), and run `./bin/netbeans --jdkhome /path/to/jdk`. Netbeans seems startup ok, here is a screenshot from the `Netbeans -> about`.
<img width="548" alt="openj9-jdk11-netbeans" src="https://user-images.githubusercontent.com/17935151/52178604-b49cc600-279e-11e9-8c4c-6ccf635d6bdf.png">
@kirill-zhukov Is there any other steps involved?

**Comment by DanHeidinga** [comment] 2019-04-22 15:34
Closing this as we haven't been able to reproduce it.  @kirill-zhukov If it occurs again with a recent OpenJ9 build please let us know.

**Closed by DanHeidinga** 2019-04-22 15:34 UTC
Labels: userRaised

**Comment by joaomfrebelo** [comment] 2020-01-31 22:17
My NB10 and NB11.2 did work for a time with adoptOpnejdk and opneJ9 in Java projects, when i started with php projects the netbean crashes on startup when is starting to open the opened project that was opened in last time that netbeans was closed. With adoptOpenJDK Hotspot or Oracle Hotsopot works well, moving again to openJ9 continue crashes, move again to Hotspot and did well again.

**Comment by pshipton** [comment] 2020-02-01 00:09
@joaomfrebelo Better to open a new Issue I think. Pls follow the "Report a user problem" template and provide the details requested.
