### ISSUE TITLE
TestSoftMxCallBackExtend_1 - OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10189] opened 2020-07-17 13:14 UTC
Failure link
------------
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_0/49
https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_extended.functional_ppc64_aix_Nightly_testList_1/48
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/50
```
23:59:08  openjdk version "1.8.0_262-internal"
23:59:08  OpenJDK Runtime Environment (build 1.8.0_262-internal-****_2020_07_16_21_40-b00)
23:59:08  Eclipse OpenJ9 VM (build master-8afb12cfa08, JRE 1.8.0 Linux s390x-64-Bit Compressed References 20200716_457 (JIT enabled, AOT enabled)
23:59:08  OpenJ9   - 8afb12cfa08
23:59:08  OMR      - 24cd6ede529
23:59:08  JCL      - 670667fed42 based on jdk8u262-b10)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test TestSoftMxCallBackExtend_1 ...
===============================================
TestSoftMxCallBackExtend_1 Start Time: Fri Jul 17 04:34:27 2020 Epoch Time (ms): 1594960467417
variation: Mode601
JVM_OPTIONS:  -Xcompressedrefs -Xjit -Xgcpolicy:optthruput 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk8_j9_extended.functional_s390x_linux_Nightly_testList_1/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_8.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:294649856
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:320864256
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:347078656
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:373293056
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:399507456
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:425721856
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:451936256
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:478150656
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:504365056
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:530579456
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:536870912
SoftMxTest: Softmx OOM Callback triggered, adjusted softmx up to avoid OOM:536870912
FAILED: testExpandHeapUntilOOM
java.lang.OutOfMemoryError: Java heap space
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:610)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.TestNG.privateMain(TestNG.java:1354)
	at org.testng.TestNG.main(TestNG.java:1323)


===============================================
    testSoftMxCallback
    Tests run: 1, Failures: 1, Skips: 0
===============================================


===============================================
GeneralTest suite
Total tests run: 1, Failures: 1, Skips: 0
===============================================


TestSoftMxCallBackExtend_1_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
01:06:42  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=s390x_linux&TARGET=TestSoftMxCallBackExtend_1

**Comment by pshipton** [comment] 2020-07-20 16:18
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly_testList_0/52

**Comment by pshipton** [comment] 2020-07-20 16:28
@jason-hall @amicic Do you think this is caused by https://github.com/eclipse/omr/pull/5327 ?

**Comment by jason-hall** [comment] 2020-07-20 16:41
optthruput out of memory? Probably is

**Comment by pshipton** [comment] 2020-07-21 18:07
eclipse/omr#5327 is integrated so I'll close this. It should be reopened if the problem is seen again.

**Closed by pshipton** 2020-07-21 18:07 UTC
Labels: test failure
