### ISSUE TITLE
j9mm.141    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ScavengerDelegate.cpp:356: ((false))

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7682] opened 2019-11-03 15:56 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/190/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
DLT stderr Bad scan type for object pointer 00000000FF903298
DLT stderr 03:08:34.002 0xfa65d00    j9mm.141    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ScavengerDelegate.cpp:356: ((false))
DLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2019/11/02 23:08:34 - please wait.
DLT stderr JVMDUMP032I JVM requested System dump using '/Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/core.20191102.230834.21544.0001.dmp' in response to an event
DLT stderr JVMDUMP010I System dump written to /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/core.20191102.230834.21544.0001.dmp
DLT stderr JVMDUMP032I JVM requested Java dump using '/Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/javacore.20191102.230834.21544.0002.txt' in response to an event
DLT stderr JVMDUMP010I Java dump written to /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/javacore.20191102.230834.21544.0002.txt
DLT stderr JVMDUMP032I JVM requested Snap dump using '/Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/Snap.20191102.230834.21544.0003.trc' in response to an event
DLT stderr JVMDUMP010I Snap dump written to /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/Snap.20191102.230834.21544.0003.trc
DLT stderr JVMDUMP013I Processed dump event "traceassert", detail "".
STF 23:08:38.456 - Found dump at: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/javacore.20191102.230834.21544.0002.txt
STF 23:08:38.456 - Found dump at: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/core.20191102.230834.21544.0001.dmp
STF 23:08:38.457 - Found dump at: /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/Snap.20191102.230834.21544.0003.trc
STF 23:08:38.457 - **FAILED** Process DLT ended with exit code (255) and not the expected exit code/s (0)
DLT stderr javacore file generated - /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/javacore.20191102.230834.21544.0002.txt
DLT stderr core file generated - /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/core.20191102.230834.21544.0001.dmp
DLT stderr Snap file generated - /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/results/Snap.20191102.230834.21544.0003.trc
STF 23:08:38.457 - Monitoring Report Summary:
STF 23:08:38.457 -   o Process DLT has crashed unexpectedly
STF 23:08:38.457 - Killing processes: DLT
STF 23:08:38.457 -   o Process DLT is not running
**FAILED** at step 1 (Run daa load test). Expected return value=0 Actual=1 at /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/execute.pl line 93.
STF 23:08:38.769 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 23:08:38.769 - 
STF 23:08:38.769 - ====================   T E A R D O W N   ====================
STF 23:08:38.769 - Running teardown: perl /Users/jenkins/workspace/Test_openjdk8_j9_sanity.system_x86-64_mac_Nightly/openjdk-tests/TestConfig/../TestConfig/test_output_15727504672414/DaaLoadTest_daa1_0/20191102-230749-DaaLoadTest/tearDown.pl
STF 23:08:38.823 - TEARDOWN stage completed
STF 23:08:38.826 - 
STF 23:08:38.826 - =====================   R E S U L T S   =====================
STF 23:08:38.826 - Stage results:
STF 23:08:38.826 -   setUp:     pass
STF 23:08:38.826 -   execute:  *fail*
STF 23:08:38.826 -   teardown:  pass
STF 23:08:38.826 - 
STF 23:08:38.826 - Overall result: **FAILED**

DaaLoadTest_daa1_0_FAILED
```

**Comment by pshipton** [comment] 2019-11-04 12:15
@dmitripivkine can you pls take a look.

**Comment by dmitripivkine** [comment] 2019-11-04 15:52
```
Checking THREAD STACKS...  <gc check (1): from debugger: THREAD STACKS: slot fd0d700(fd23838) -> ff903298: class pointer not in a class segment>

<fd0d700> For pinning array U8(0x03) num internal pointer stack slots U8(0x01)
<fd0d700> Before object slot walk &address : 0x000000000FD23838 address : 0x00000000FF903298 bp 0x000000000FD23968 offset of first internal ptr I16(0xFEC0)
<fd0d700> After object slot walk for pinning array with &address : 0x000000000FD23838 old address 0x00000000FF903298 new address 0x00000000FF903298 displacement IDATA(0x0000000000000000)
```
This is duplicate of https://github.com/eclipse/openj9/issues/7300

**Comment by dmitripivkine** [comment] 2019-11-04 15:56
Close as far as it is a duplicate

**Closed by dmitripivkine** 2019-11-04 15:56 UTC
Labels: comp:gc, test failure
