### ISSUE TITLE
JBoss cached LUDCL failure

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#7332] opened 2019-10-03 03:33 UTC
As reported in "DefaultContextServiceServletTestCase#testServletin WildFly test suite fails on Openj9 OpenJDK8" https://issues.jboss.org/browse/JBEAP-17634 , OpenJ9 is causing a ClassNotFoundException due to having the wrong classloader cached as the LUDCL.

```
Caused by: java.lang.ClassNotFoundException: org.wildfly.extension.undertow.security.AccountImpl$AccountPrincipal
        at java.lang.Class.forNameImpl(Native Method)
        at java.lang.Class.forName(Class.java:403)
        at java.io.ClassCache$FutureValue.get(ClassCache.java:190)
        at java.io.ClassCache.get(ClassCache.java:161)
        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:791)
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1974)
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1857)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2148)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:518)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:456)
        at java.util.HashSet.readObject(HashSet.java:341)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2284)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:518)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:456)
        at org.jboss.as.security.deployment.SecurityContextHandleFactory.readSetupContextHandle(SecurityContextHandleFactory.java:75)
        at org.jboss.as.ee.concurrent.ConcurrentContext$ChainedSetupContextHandle.readObject(ConcurrentContext.java:251)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2284)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2393)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2317)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2175)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:518)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:456)
        at org.jboss.as.test.integration.ee.concurrent.DefaultContextServiceTestServlet.doGet(DefaultContextServiceTestServlet.java:71)
        ... 49 more
```

Related issue on Wildfly: https://issues.jboss.org/browse/WFLY-5588
Similar issue reported with Wildfly: https://github.com/eclipse/openj9/issues/2215

OpenJ9 doc on option to enable / disable https://github.com/eclipse/openj9-docs/blob/master/docs/dcomibmenableclasscaching.md

This issue is to determine next steps:
* can the ludcl cache be made correct?
* should it be disabled by default in the meantime?

**Comment by DanHeidinga** [comment] 2019-10-03 03:36
@vijaysun-omr how much is the `-Dcom.ibm.enableClassCaching=[true|false]` cache worth performance wise?  Would you be concerned if it was disabled while we investigate the root issue?

**Comment by vijaysun-omr** [comment] 2019-10-03 12:01
I believe LUDCL paths were optimized for ORB serialization code. In some of the microbenchmark scenarios, the improvements were quite significant but I don't know of the impact in a real application/benchmark. In any case, I'm fine with temporarily disabling the LUDCL optimization while the issue is investigated and fixed properly.

**Comment by theresa-m** [comment] 2019-10-04 18:24
Prs to disable LUDCL:
JDK8 master: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/330
JDK8 v0.17.0: TODO
JDK11 master: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/213
JDK11 v0.17.0: TODO
JDK13 master: TODO
JDK13: v0.17.0: TODO
JDK next master: TODO
JDK next v0.17.0: TODO

**Comment by pshipton** [comment] 2019-10-04 18:47
We'll need to open an issue at https://github.com/eclipse/openj9-docs/issues for this change in behavior.

**Comment by theresa-m** [comment] 2019-10-04 18:51
The docs indicate that disabled is the default.. which will be true once the prs are merged.

https://github.com/eclipse/openj9-docs/blob/master/docs/dcomibmenableclasscaching.md

**Comment by pshipton** [comment] 2019-10-04 19:08
Regardless of the docs being wrong, this is a change in behavior and should be documented, likely in a release note. We still need a doc issue for the change.

**Comment by DanHeidinga** [comment] 2019-10-05 02:31
I've merged the disable LUDCL PRs into all the extensions repos and into the `0.17.0` release branches.

**Comment by zl-wang** [comment] 2019-10-07 21:14
The class cache is worth of significant performance impact (in 10-20% range) for SPEC benchmarking.

**Comment by vijaysun-omr** [comment] 2019-10-07 21:15
I don't think this is the one that gives SPEC performance. This was an optimization added for ORB serialization I think.

**Comment by vijaysun-omr** [comment] 2019-10-08 01:40
@zl-wang  this is a temporary disabling of the functionality until the underlying problem is found and fixed.

**Comment by pshipton** [comment] 2019-10-09 13:36
The feature has been disabled by default in the 0.17 release, further work to fix the feature will occur in a future release.

**Comment by DanHeidinga** [comment] 2019-10-09 17:52
Note, the OpenJ9 0.17 release milestone 2 builds for JDK8 and 11 are now available and contain this fix. Please give them a try and report any problems. The expected GA date is around Oct 18th.

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u232-b07_openj9-0.17.0-m2
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.5+9_openj9-0.17.0-m2

**Comment by theresa-m** [comment] 2019-10-24 14:51
The ludcl optimization assumes that during the time ludcl is cached user code is not touched. However there are several places in `java.io.ObjectInputStream` where serialization read methods are invoked, and these methods may be implemented by a user.
Wildfly exposed that flaw with a readObject method that switches classloaders when called https://github.com/wildfly/wildfly/blob/3f2e4701fbc5d281405c67a37c7795d367ecc091/ee/src/main/java/org/jboss/as/ee/concurrent/ConcurrentContext.java#L201

I've opened a pr that will refresh the ludcl cache if a method invoked: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/341

I will work on getting some perf numbers for this.

**Comment by theresa-m** [comment] 2019-10-30 20:11
performance testing results: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/341#issuecomment-548091121

**Closed** 2019-11-08 16:04 UTC
Labels: comp:vm, doc:externals
