### ISSUE TITLE
Access Violation calling j9port_startup_library

### ISSUE THREAD

**Issue by rweijnen** [eclipse/openj9#1564] opened 2018-03-28 14:27 UTC
I have build openj9 for Windows per instructions and running the following code from Visual Studio 2017 I get an Access Violation on calling `j9port_startup_library`:

```
	J9PortLibraryVersion portver;
	J9PORT_SET_VERSION(&portver, J9PORT_CAPABILITY_MASK);

	J9PortLibrary *portlib;
	int32_t rc = j9port_allocate_library(&portver, &portlib);
	if (rc != 0)
	{
		printf("j9port_allocate_library failed with: %d\n", rc);
		return 1;
	}

	portlib->omrPortLibrary = omrPortLibrary;
	rc = j9port_create_library(portlib, &portver, sizeof(J9PortLibrary));
	if (rc != 0)
	{
		return 1;
	}

	rc = j9port_startup_library(portlib);
	if (rc != 0)
	{
		printf("j9port_startup_library failed with %d\n", rc);
		return 1;
	}
```
Exception thrown at 0x00007FFF0FC9430A (j9thr29.dll) in sample.exe: 0xC0000005: Access violation reading location 0x0000000000000000

I am not sure this is required but I also tried to init OMR:
```
	if (omrthread_init_library() != 0) {
		return 1;
	}
	omrthread_t attachedThread = NULL;
	if (0 != omrthread_attach_ex(&attachedThread, J9THREAD_ATTR_DEFAULT)) {
		printf("failed to attach.\n");
	}

	OMRPortLibrary omrPortLibrary;
	if (0 != omrport_init_library(&omrPortLibrary, sizeof(OMRPortLibrary))) {
		printf("omrport_init_library failed\n");
		
		return 1;
	}
```

**Comment by pshipton** [comment] 2018-03-28 14:37
Note if you want to create a working build, use VS 2010 for Java 8 and VS 2013 for Java 9. I expect we'll look at getting VS 2017 working at some point down the road.

**Comment by rweijnen** [comment] 2018-03-28 16:21
I build openj9 with visual studio 2010 but I am using the header and lib files with visual studio 2017. I assumed that would work?

**Comment by pshipton** [comment] 2018-03-28 16:27
Apparently not. This isn't a configuration OpenJ9 would support.

**Comment by rweijnen** [comment] 2018-03-28 16:46
I will check with visual studio 2010

**Comment by pshipton** [comment] 2018-03-28 19:15
Given "I build openj9 with visual studio 2010 but I am using the header and lib files with visual studio 2017" I'm closing this.

**Comment by rweijnen** [comment] 2018-03-28 20:27
I just rebuild the project with Visual Studio 2010 and it gives me the exact same error

**Comment by pshipton** [comment] 2018-03-28 20:42
Not sure, I assume its a machine setup problem. What exactly are you doing, running "java" or something else?

Although AdoptOpenJDK.net doesn't have Java 8 Windows builds working yet because of a machine setup problem (missing wdbgexts.h) https://github.com/AdoptOpenJDK/openjdk-build/issues/243) , internal to IBM Window's is built and tested multiple times a day without issue.

```
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-j9build_2018_03_28_17_33-b00)
Eclipse OpenJ9 VM (build ibm_sdk-532157df0c, JRE 1.8.0 Windows 10 amd64-64 Compressed References 20180328_382584 (JIT enabled, AOT enabled)
OpenJ9   - 532157df0c
OMR      - 30c4f205
JCL      - 8599c6f68e based on jdk8u162-b12)
```

**Comment by pshipton** [comment] 2018-03-28 21:01
If you are looking for an example of starting up the port library outside of running "java", see JNI_CreateJavaVM() in runtime/j9vm/jvm.c

**Comment by rweijnen** [comment] 2018-03-28 21:05
That is indeed what I'm trying to do, so I'll have a look at that code (thanks).
java -version runs fine btw 
```
c:\Temp\openj9-openjdk-jdk8\build\windows-x86_64-normal-server-release\images\j2re-image>.\bin\java.exe -version
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-me_2018_03_27_21_50-b00)
Eclipse OpenJ9 VM (build master-d5b6fa8e, JRE 1.8.0 Windows 10 amd64-64 Compressed References 20180327_000000 (JIT enabled, AOT enabled)
OpenJ9   - d5b6fa8e
OMR      - a05605ea
JCL      - 8599c6f68e based on jdk8u162-b12)
```

**Comment by pshipton** [comment] 2018-03-28 21:07
Also see runtime/makelib/cmain.c and the port library tests in runtime/tests/port, which might be easier.

**Comment by rweijnen** [comment] 2018-03-28 21:14
Yes I tried a 2 tests from tests/port/j9portTest.c and they also give me an access violation (for example j9port_test4).

**Comment by rweijnen** [comment] 2018-03-28 21:21
When running outside the debugger I see this output:
```
** ASSERTION FAILED ** j9prt.504 at common/j9port.c:404 Assert_PRT_true((omrthread_self() != ((void *)0)))

** ASSERTION FAILED ** omrport.0 at ../../omr/port/common/omrport.c:515 Assert_PRT_true((omrthread_self() != ((void *)0)))
```

**Comment by pshipton** [comment] 2018-03-28 22:10
@smlambert @llxia is pltest running on OpenJ9? I can't find it. 

We do run this internally to IBM and it passes. Its not exactly the same source as OpenJ9, but close enough that it shouldn't make any difference to these tests. It likely needs to be in the same directory as the rest of the OpenJ9 shared libraries.
`wa6480\jre\bin\compressedrefs\pltest`

**Comment by llxia** [comment] 2018-03-29 01:51
pltest is disabled in OpenJ9

https://github.com/eclipse/openj9/blob/2954f9d4159fe9333811c6aa08c3759885bb4f0d/test/TestConfig/scripts/testKitGen/makeGenTool/mkgen.pl#L115

**Comment by smlambert** [comment] 2018-03-29 01:57
Native tests were disabled, awaiting the work item to compile native libraries as part of the CCM build, which you may recall, was recently reassigned (under duress).

![jenkinsmoveplansept25](https://user-images.githubusercontent.com/2836948/38065770-fa1917b8-32d2-11e8-8a50-5f64d10e0cb1.jpg)

**Comment by rweijnen** [comment] 2018-03-30 23:01
I rebuild the project on Windows 7 x64 with Visual Studio 2010.
Then I ran the exact code from this issue and Visual Studio shows me that we crash in 
```
omrthread.c

static omrthread_monitor_t

monitor_allocate(omrthread_t self, intptr_t policy, intptr_t policyData)

{

   omrthread_monitor_t newMonitor;
	
   omrthread_library_t lib = self->library;
```

self is nil and therefore an ACCESS_VIOLATION is thrown
![screenshot](https://user-images.githubusercontent.com/7575747/38156500-a0b647ce-347e-11e8-854a-f7a884bb78f2.png)

**Comment by jilleb** [comment] 2018-03-31 08:12
@pshipton, reopen issue?

**Comment by rweijnen** [comment] 2018-04-01 17:33
Yes @pshipton can you please re-open this issue (or would you prefer me to open a new one)?

**Comment by jilleb** [comment] 2018-04-05 12:54
I am able to reproduce this issue on VS2010 and Windows 7 x64.

**Comment by rweijnen** [comment] 2018-04-16 20:17
Any updates on this issue?

**Comment by pshipton** [comment] 2018-04-16 23:43
Looking at the examples, you have to initialize the thread library, but not explicitly the omr port library. I created a working example. I compiled and ran it on Linux but it should work the same on Windows.

Instead of calling j9port_allocate_library() / j9port_create_library() / j9port_startup_library() you could call j9port_init_library() instead, which is the second example below.

```
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

#include <j9comp.h>
#include <j9port.h>

int main(int argc, char **argv) {
    omrthread_t attachedThread = NULL;
    J9PortLibraryVersion portver;
    J9PortLibrary *portlib;
    int32_t rc;
    intptr_t fd;

    rc = omrthread_init_library();
    if (rc != 0) {
        printf("omrthread_init_library failed with: %d\n", rc);
        return 1;
    }

    rc = omrthread_attach_ex(&attachedThread, J9THREAD_ATTR_DEFAULT);
    if (rc != 0) {
        printf("omrthread_attach_ex failed with: %d\n", rc);
        return 1;
    }

    J9PORT_SET_VERSION(&portver, J9PORT_CAPABILITY_MASK);
    rc = j9port_allocate_library(&portver, &portlib);
    if (rc != 0) {
        printf("j9port_allocate_library failed with: %d\n", rc);
        return 1;
    }

    rc = j9port_create_library(portlib, &portver, sizeof(J9PortLibrary));
    if (rc != 0) {
        printf("j9port_create_library failed with: %d\n", rc);
        return 1;
    }

    rc = j9port_startup_library(portlib);
    if (rc != 0) {
        printf("j9port_startup_library failed with: %d\n", rc);
        return 1;
    }

    OMRPORT_ACCESS_FROM_J9PORT(portlib);
    PORT_ACCESS_FROM_PORT(portlib);

    j9tty_printf(PORTLIB, "Port library created\n");

    fd = omrfile_open("test1.txt", EsOpenCreate | EsOpenRead | EsOpenWrite, 777); 
    printf("omrfile_open fd = %" PRIdPTR "\n", fd);

#define OUTPUT "port library is working\n"
    omrfile_write(fd, OUTPUT, sizeof(OUTPUT) - 1);
    omrfile_close(fd);

    return 0;
}
```

```
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

#include <j9comp.h>
#include <j9port.h>

int main(int argc, char **argv) {
    omrthread_t attachedThread = NULL;
    J9PortLibraryVersion portver;
    J9PortLibrary *portlib;
    int32_t rc;
    intptr_t fd;

    rc = omrthread_init_library();
    if (rc != 0) {
        printf("omrthread_init_library failed with: %d\n", rc);
        return 1;
    }

    rc = omrthread_attach_ex(&attachedThread, J9THREAD_ATTR_DEFAULT);
    if (rc != 0) {
        printf("omrthread_attach_ex failed with: %d\n", rc);
        return 1;
    }

    J9PORT_SET_VERSION(&portver, J9PORT_CAPABILITY_MASK);
    rc = j9port_allocate_library(&portver, &portlib);
    if (rc != 0) {
        printf("j9port_allocate_library failed with: %d\n", rc);
        return 1;
    }

    rc = j9port_create_library(portlib, &portver, sizeof(J9PortLibrary));
    if (rc != 0) {
        printf("j9port_create_library failed with: %d\n", rc);
        return 1;
    }

    rc = j9port_startup_library(portlib);
    if (rc != 0) {
        printf("j9port_startup_library failed with: %d\n", rc);
        return 1;
    }

    OMRPORT_ACCESS_FROM_J9PORT(portlib);
    PORT_ACCESS_FROM_PORT(portlib);

    j9tty_printf(PORTLIB, "Port library created\n");

    fd = omrfile_open("test1.txt", EsOpenCreate | EsOpenRead | EsOpenWrite, 777); 
    printf("omrfile_open fd = %" PRIdPTR "\n", fd);

#define OUTPUT "port library is working\n"
    omrfile_write(fd, OUTPUT, sizeof(OUTPUT) - 1);
    omrfile_close(fd);

    return 0;
}
```

**Comment by rweijnen** [comment] 2018-04-17 12:27
Both your examples crash equally well on Windows with Visual Studio 2010 with the same Access Violation as with my original example.

**Comment by jilleb** [comment] 2018-04-17 13:38
Can confirm, still failing on W7x64/VS2010.

**Comment by pshipton** [comment] 2018-04-18 17:13
I ran an openj9 build on Windows 7 VS2010. This produced pltest.exe in openj9-openjdk-jdk8\build\windows-x86_64-normal-server-release\vm. I started pltest.exe (no parameters, cd was the location of pltest) and it ran and passed all the tests `ALL TESTS COMPLETED AND PASSED`. Next I'll try the standalone example I created earlier.

**Comment by rweijnen** [comment] 2018-04-18 18:18
Just tested `pltest.exe` here and also works fine (`ALL TESTS COMPLETED AND PASSED`), curious to your result of the sample code. Thanks for taking the effort.

**Comment by pshipton** [comment] 2018-04-18 18:43
I had to make some minor changes to compile on Windows, but it works. I used the same compile/link options as for pltest.

```
cl -DJAVA_SPEC_VERSION=8 /Ox -D_AMD64_=1 -DWIN64 -D_WIN64 -DWIN32 -D_WIN32 -DJ9HAMMER -Fdmain.pdb -D_CRT_SECURE_NO_WARNINGS -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_WIN95 -D_WIN32_WINDOWS=0x0500 /D_WIN32_DCOM -D_WIN32_IE=0x0500 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -D_MT -D_WINSOCKAPI_ -Zm400 -W3 -Zi -MD -D_DLL -WX -I. -I../include -I../oti -I../port/common -I../nls -I../omr/include_core    -DUT_DIRECT_TRACE_REGISTRATION -DTR_HOST_X86 -c main.c

link /INCREMENTAL:NO /NOLOGO /LARGEADDRESSAWARE /debug  /opt:icf /opt:ref  -out:../prttest.exe -subsystem:console \
 -machine:AMD64 wsetargv.obj /NODEFAULTLIB:MSVCRTD main.obj prttest.res ../lib/j9prt.lib ../lib/j9thr.lib    kernel32.lib wsock32.lib advapi32.lib
link /INCREMENTAL:NO /NOLOGO /LARGEADDRESSAWARE /debug  /opt:icf /opt:ref  -out:../prttest.exe -subsystem:console \
 -machine:AMD64 wsetargv.obj /NODEFAULTLIB:MSVCRTD main.obj ../lib/j9prt.lib ../lib/j9thr.lib    kernel32.lib wsock32.lib advapi32.lib
```



```
#include <stdlib.h>
#include <string.h>

#include <j9comp.h>
#include <j9port.h>

int main(int argc, char **argv) {
    omrthread_t attachedThread = NULL;
    J9PortLibraryVersion portver;
    J9PortLibrary portlib;
    intptr_t rc;
    intptr_t fd;

    rc = omrthread_init_library();
    if (rc != 0) {
        printf("omrthread_init_library failed with: %lld\n", rc);
        return 1;
    }

    rc = omrthread_attach_ex(&attachedThread, J9THREAD_ATTR_DEFAULT);
    if (rc != 0) {
        printf("omrthread_attach_ex failed with: %lld\n", rc);
        return 1;
    }

    J9PORT_SET_VERSION(&portver, J9PORT_CAPABILITY_MASK);
    rc = j9port_init_library(&portlib, &portver, sizeof(portlib));
    if (rc != 0) {
        printf("j9port_init_library failed with: %lld\n", rc);
        return 1;
    }

	{
		OMRPORT_ACCESS_FROM_J9PORT(&portlib);
		PORT_ACCESS_FROM_PORT(&portlib);

		j9tty_printf(PORTLIB, "Port library created\n");

		fd = omrfile_open("test1.txt", EsOpenCreate | EsOpenRead | EsOpenWrite, 777); 
		printf("omrfile_open fd = %lld\n", fd);

#define OUTPUT "port library is working\n"
		omrfile_write(fd, OUTPUT, sizeof(OUTPUT) - 1);
		omrfile_close(fd);
	}

    return 0;
}
```

**Comment by pshipton** [comment] 2018-04-18 19:01
It still works when I trim down the compile line to `cl /Ox -DWIN64 -DWIN32 -DJ9HAMMER -Fdmain.pdb -nologo -Zm400 -W3 -Zi -MD -WX -I. -I../include -I../oti -I../port/common -I../nls -I../omr/include_core -c main.c`

**Comment by pshipton** [comment] 2018-04-27 15:06
Closing as I assume this is resolved now since there haven't been any further comments.

**Closed by pshipton** 2018-04-27 15:06 UTC
Labels: comp:vm, question, userRaised
