### ISSUE TITLE
cmdLineTester_SCHelperCompatabilityTests_unix_1 failure on openj9 openjdk-jdk8

### ISSUE THREAD

**Issue by vsebe** [eclipse/openj9#597] opened 2017-11-15 20:01 UTC
```
Running test cmdLineTester_SCHelperCompatabilityTests_unix_1 ...
===============================================
test with Mode610
{ mkdir -p "/tmp/bld_370249/test/TestConfig/test_output_1510768124/cmdLineTester_SCHelperCompatabilityTests_unix_1"; \
	cd "/tmp/bld_370249/test/TestConfig/test_output_1510768124/cmdLineTester_SCHelperCompatabilityTests_unix_1"; \
	cp "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/HelperCompatabilityTests.jar" .; \
	"/tmp/bld_370249/j2sdk-image/jre/bin/../../bin/jar" xf HelperCompatabilityTests.jar; \
	 \
	"/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -DJAVA_EXE='"/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon ' -DJDK_HOME="/tmp/bld_370249/j2sdk-image/jre/bin/../.." -DCPDL=":" -DPROPS_DIR="/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/props_unix" -DSCMODE=204 \
	-jar "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdline_options_tester/cmdlinetester.jar" \
	-config "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/HelperCompatabilityTests_SE80.xml" \
	-xids all,SE80 -xlist "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/exclude.xml" \
	-nonZeroExitWhenError \
	-outputLimit 300; \
	if [ $? -eq 0 ] ; then echo "cmdLineTester_SCHelperCompatabilityTests_unix_1""_PASSED"; else echo "cmdLineTester_SCHelperCompatabilityTests_unix_1""_FAILED"; fi; } 2>&1 | tee -a TestTargetResult
Parsing exclude list...
  add excludes for [all]
  add excludes for [SE80]
DONE in 0 ms.
*** Starting test suite: Shared Classes HelperCompatabilityTests Suite - Windows Configuration ***

...

Testing: HelperCompatabilityTest 9
Test start time: 2017/11/15 13:17:57 Eastern Standard Time
Running command: "/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses -Xbootclasspath/a:./Utils:. URLClassPathHelperURLHelperStaleEntryCompatabilityTest -testfile "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/props_unix/Test8.props" -javacdir /tmp/bld_370249/j2sdk-image/jre/bin/../../bin
Time spent starting: 1 milliseconds
Time spent executing: 2939 milliseconds
Test result: FAILED
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /tmp/bld_370249/j2sdk-image/jre/bin/../../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] added manifest
 [OUT] adding: B.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: C.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: D.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: E.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: F.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: X.class(in = 298) (out= 234)(deflated 21%)
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] 
 [OUT] ** urlsString: ./AlphabetJar/Alphabet.jar;
 [OUT] 
 [OUT] Failure finding class: D on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F on path: ./AlphabetJar/Alphabet.jar; which is index: 0 result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

...

Testing: HelperCompatabilityTest 11
Test start time: 2017/11/15 13:18:00 Eastern Standard Time
Running command: "/tmp/bld_370249/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xjit -Xgcpolicy:gencon  -Xshareclasses -Xbootclasspath/a:./Utils:. URLHelperURLClassPathHelperStaleEntryCompatabilityTest -testfile "/tmp/bld_370249/test/TestConfig/../../jvmtest/cmdLineTests/shareClassTests/SCHelperCompatabilityTests/props_unix/Test10.props" -javacdir /tmp/bld_370249/j2sdk-image/jre/bin/../../bin
Time spent starting: 1 milliseconds
Time spent executing: 2902 milliseconds
Test result: FAILED
 [OUT] 
 [OUT]  Incorrect usage
 [OUT] 
 [OUT]  Please specifiy -testfile <filename> -javacdir <path to javac>
 [OUT] 
 [OUT] ** urlsString: ./AlphabetJar/Alphabet.jar;./Pets;:./Vowels;:
 [OUT] 
 [OUT] ** Running: /bin/sh ./batchfiles/StaleClassPathTest5.sh /tmp/bld_370249/j2sdk-image/jre/bin/../../bin
 [OUT] Here is the standard output of the command:
 [OUT] 
 [OUT] added manifest
 [OUT] adding: B.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: C.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: D.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: E.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: F.class(in = 298) (out= 233)(deflated 21%)
 [OUT] adding: X.class(in = 298) (out= 234)(deflated 21%)
 [OUT] Here is the standard error of the command (if any):
 [OUT] 
 [OUT] 
 [OUT] Failure finding class: A result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: E result: false expecting: true
 [OUT] 
 [OUT] Failure finding class: F result: false expecting: true
 [OUT] 
 [OUT] TEST FAILED
>> Success condition was not found: [Output match: TEST PASSED]
>> Failure condition was not found: [Output match: Error:]
>> Failure condition was not found: [Output match: Unhandled Exception]
>> Failure condition was not found: [Output match: Exception:]

---TEST RESULTS---
Number of PASSED tests: 31 out of 33
Number of FAILED tests: 2 out of 33

---SUMMARY OF FAILED TESTS---
HelperCompatabilityTest 9
HelperCompatabilityTest 11
-----------------------------

cmdLineTester_SCHelperCompatabilityTests_unix_1_FAILED
```

Tested openj9 openjdk-jdk8 on linux_x86-64_cmprssptrs:
j2sdk-image/jre/bin/java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-openj9_2017_11_15_12_33-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20171115_370249 (JIT enabled, AOT enabled)
OpenJ9 - 10706ea
OMR - 99498e1
OpenJDK - e9942fd based on jdk8u152-b03)

attn @llxia

**Comment by hangshao0** [comment] 2017-11-15 21:26
Test issue, similar to #470

**Comment by pshipton** [comment] 2017-11-28 23:10
Duplicate of #469

**Closed by pshipton** 2017-11-28 23:10 UTC
Labels: jdk8
