### ISSUE TITLE
threadMXBeanTimersTest_3 crashed in JDK11

### ISSUE THREAD

**Issue by llxia** [eclipse/openj9#2821] opened 2018-09-10 21:14 UTC
Java Version:
```
00:07:26.367 "/home/jenkins/workspace/TestBuild_Sandbox/openjdkbinary/j2sdk-image/bin/java" -version
00:07:26.367 openjdk version "11-internal" 2018-09-25
00:07:26.367 OpenJDK Runtime Environment (build 11-internal+0-adhoc.j9build.Build-JDK11-linux390-64cmprssptrs)
00:07:26.367 Eclipse OpenJ9 VM (build nativetest-025d2d99, JRE 11 Linux s390x-64-Bit Compressed References 20180908_15 (JIT enabled, AOT enabled)
00:07:26.367 OpenJ9   - 025d2d99
00:07:26.367 OMR      - 30a0046f
00:07:26.367 JCL      - 98f20388ae6 based on jdk-11+28)
```

Output:
```
===============================================
Running test threadMXBeanTimersTest_3 ...
===============================================
threadMXBeanTimersTest_3 Start Time: Sat Sep  8 22:57:48 2018 Epoch Time (ms): 1536461868997
test with Mode610
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_SE110.txt
...
... TestNG 6.14.2 by C?dric Beust (cedric@beust.com)
...

Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=007d9b48 Signal_Code=00000001
Handler1=000003FF8D62E790 Handler2=000003FF8D226DA0 InaccessibleAddress=0000000000000000
gpr0=00000000000008E9 gpr1=0000000086E39A98 gpr2=0000000086D3F450 gpr3=00000000015DE481
gpr4=000003FF8C40D542 gpr5=000000000040F548 gpr6=000000000000084C gpr7=0000000000300A00
gpr8=00000000015DE481 gpr9=0000000086D06BF8 gpr10=00000000015E8A0B gpr11=000003FF200009F8
gpr12=000003FF8E09B000 gpr13=0000000000404800 gpr14=000003FF6DAAB8B4 gpr15=000003FF8CFFE480
psw=0000000000000000 mask=0705200180000000 fpc=0008000000000000 bea=000003FF6DAAB8B2
fpr0 0000000000000018 (f: 24.000000, d: 1.185758e-322)
fpr1 0000000086d06bf8 (f: 2261806080.000000, d: 1.117481e-314)
fpr2 000000000040f168 (f: 4256104.000000, d: 2.102795e-317)
fpr3 3f98412530c8c014 (f: 818462720.000000, d: 2.368601e-02)
fpr4 000003ff30009810 (f: 805345280.000000, d: 2.171200e-311)
fpr5 3d7546fc71d6f863 (f: 1909913728.000000, d: 1.209474e-12)
fpr6 0000000000380400 (f: 3671040.000000, d: 1.813735e-317)
fpr7 bc39500000000000 (f: 0.000000, d: -1.372193e-18)
fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
fpr9 000003ff883ab960 (f: 2285549824.000000, d: 2.171931e-311)
fpr10 000003ff8cfc0000 (f: 2365325312.000000, d: 2.171970e-311)
fpr11 000003ffdb27f5ad (f: 3676829184.000000, d: 2.172618e-311)
fpr12 0000000000000011 (f: 17.000000, d: 8.399116e-323)
fpr13 000003fff4e7d838 (f: 4108834816.000000, d: 2.172832e-311)
fpr14 00000000000fb5f8 (f: 1029624.000000, d: 5.087018e-318)
fpr15 000003ff886fec70 (f: 2289036288.000000, d: 2.171933e-311)
Target=2_90_20180908_15 (Linux 4.4.0-116-generic)
CPU=s390x (4 logical CPUs) (0x1e9a20000 RAM)
----------- Stack Backtrace -----------
(0x0000000000000000 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2018/09/08 22:57:51 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/core.20180908.225751.4161.0001.dmp' in response to an event
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=007d9b48 Signal_Code=00000001
Handler1=000003FF8D62E790 Handler2=000003FF8D226DA0 InaccessibleAddress=0000000000000000
gpr0=00000000000008E9 gpr1=0000000086E39A98 gpr2=0000000086D22438 gpr3=0000000001AA668F
gpr4=0000000001AB0AFD gpr5=0000000000408FB8 gpr6=0000000000000861 gpr7=0000000000300A00
gpr8=0000000001AA668F gpr9=0000000086D09C28 gpr10=0000000001AB0AFD gpr11=000003FF180009F8
gpr12=000003FF8E09B000 gpr13=0000000000409200 gpr14=000003FF6DAAB8B4 gpr15=000003FF8CEFE480
psw=0000000000000000 mask=0705100180000000 fpc=0008000000000000 bea=000003FF6DAAB8B2
fpr0 0000000000000018 (f: 24.000000, d: 1.185758e-322)
fpr1 0000000086d09c28 (f: 2261818368.000000, d: 1.117487e-314)
fpr2 0000000000408b70 (f: 4230000.000000, d: 2.089898e-317)
fpr3 3fa95482fec8b940 (f: 4274567424.000000, d: 4.947290e-02)
fpr4 000003ff88899928 (f: 2290718976.000000, d: 2.171933e-311)
fpr5 3d735a19523c4e3b (f: 1379683840.000000, d: 1.100031e-12)
fpr6 0000000000380400 (f: 3671040.000000, d: 1.813735e-317)
fpr7 bc35400000000000 (f: 0.000000, d: -1.151965e-18)
fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
fpr9 000003ff883ab960 (f: 2285549824.000000, d: 2.171931e-311)
fpr10 000003ff8cec0000 (f: 2364276736.000000, d: 2.171970e-311)
fpr11 000003ffdb27f5ad (f: 3676829184.000000, d: 2.172618e-311)
fpr12 0000000000000011 (f: 17.000000, d: 8.399116e-323)
fpr13 000003fff4e7d838 (f: 4108834816.000000, d: 2.172832e-311)
fpr14 00000000000fb5f8 (f: 1029624.000000, d: 5.087018e-318)
fpr15 000003ff886fec70 (f: 2289036288.000000, d: 2.171933e-311)
Target=2_90_20180908_15 (Linux 4.4.0-116-generic)
CPU=s390x (4 logical CPUs) (0x1e9a20000 RAM)
----------- Stack Backtrace -----------
(0x0000000000000000 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2018/09/08 22:57:51 - please wait.
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 Signal_Number=0000000b Error_Value=007d9b48 Signal_Code=00000001
Handler1=000003FF8D62E790 Handler2=000003FF8D226DA0 InaccessibleAddress=0000000000000000
gpr0=00000000000008E9 gpr1=0000000086E39A98 gpr2=0000000086D23438 gpr3=00000000017A05AA
gpr4=00000000017AA734 gpr5=0000000000406A98 gpr6=0000000000000862 gpr7=0000000000300A00
gpr8=00000000017A05AA gpr9=0000000086D094F8 gpr10=00000000017AA734 gpr11=000003FF140009F8
gpr12=000003FF8E09B000 gpr13=0000000000406D00 gpr14=000003FF6DAAB8B4 gpr15=000003FF8CF7E480
psw=0000000000000000 mask=0705100180000000 fpc=0008000000000000 bea=000003FF6DAAB8B2
fpr0 000003ff8cf7e468 (f: 2365056000.000000, d: 2.171970e-311)
fpr1 0000000086d094f8 (f: 2261816576.000000, d: 1.117486e-314)
fpr2 000003ff6daac728 (f: 1839908608.000000, d: 2.171711e-311)
fpr3 3fa76c58e632b251 (f: 3862082048.000000, d: 4.574850e-02)
fpr4 000003ff88899430 (f: 2290717696.000000, d: 2.171933e-311)
fpr5 3d735a9f98a21341 (f: 2560758528.000000, d: 1.100147e-12)
fpr6 0000000000380400 (f: 3671040.000000, d: 1.813735e-317)
fpr7 bc35400000000000 (f: 0.000000, d: -1.151965e-18)
fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
fpr9 000003ff883ab960 (f: 2285549824.000000, d: 2.171931e-311)
fpr10 000003ff8cf40000 (f: 2364801024.000000, d: 2.171970e-311)
fpr11 000003ffdb27f5ad (f: 3676829184.000000, d: 2.172618e-311)
fpr12 0000000000000011 (f: 17.000000, d: 8.399116e-323)
fpr13 000003fff4e7d838 (f: 4108834816.000000, d: 2.172832e-311)
fpr14 00000000000fb5f8 (f: 1029624.000000, d: 5.087018e-318)
fpr15 000003ff886fec70 (f: 2289036288.000000, d: 2.171933e-311)
Target=2_90_20180908_15 (Linux 4.4.0-116-generic)
CPU=s390x (4 logical CPUs) (0x1e9a20000 RAM)
----------- Stack Backtrace -----------
(0x0000000000000000 [<unknown>+0x0])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2018/09/08 22:57:51 - please wait.
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.4188.

JVMDUMP010I System dump written to /home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/core.20180908.225751.4161.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/javacore.20180908.225751.4161.0004.txt' in response to an event
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/core.20180908.225751.4161.0002.dmp' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/javacore.20180908.225751.4161.0004.txt
JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.4190.

JVMDUMP010I System dump written to /home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/core.20180908.225751.4161.0002.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/javacore.20180908.225751.4161.0006.txt' in response to an event
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/Snap.20180908.225751.4161.0005.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/Snap.20180908.225751.4161.0005.trc
JVMDUMP007I JVM Requesting JIT dump using '/home/jenkins/workspace/TestBuild_Sandbox/openjdk-tests/functional/Java8andUp/jitdump.20180908.225751.4161.0007.dmp'
JVMDUMP013I Processed dump event "gpf", detail "".

threadMXBeanTimersTest_3_FAILED
```

Link: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox/492/

**Comment by irinarada** [comment] 2018-09-17 16:09
@fjeremic - can someone look at this as soon as possible? https://github.com/eclipse/openj9/issues/2821

**Comment by fjeremic** [comment] 2018-09-17 16:11
> @fjeremic - can someone look at this as soon as possible? #2821

@dchopra001 can you please take a look at this one?

**Comment by dchopra001** [comment] 2018-09-17 18:55
This issue is no longer reproducible.

1. I discussed with Lan, and he did not see this failure in recent builds:
https://ci.eclipse.org/openj9/view/Test/job/Test-extended.functional-JDK11-linux_390-64_cmprssptrs/18/tapResults/

2. Just to be sure, I launched grinders on this test to try and reproduce the issue. After 160 runs, I have 0 reproductions of this issue:
10x:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/328/
40x:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/329/
50x:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/331/
60x:
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/332/

Based on the above information, I don't think this is an issue anymore. So we can close this.

**Comment by dchopra001** [comment] 2018-09-17 19:36
This failure looks different from the original reported failure. The first looked to be in jitted code, while this one looks to have crashed in the VM module. It's hard to say for sure if it's the same issue (though I wouldn't rule it out). If we still think this is the same issue, then it looks like this could be a common problem across all platforms.

**Comment by irinarada** [comment] 2018-09-17 20:45
@andrewcraik , @zl-wang - either ppc or common issue... can we have someone look at it.

**Comment by irinarada** [comment] 2018-09-17 20:51
@IBMJimmyk - would you please look at this.

**Comment by IBMJimmyk** [comment] 2018-09-18 20:48
I was able to reproduce the crash in my personal workspace. Failure rate seems to be around 1 in 20 but the test is fairly quick to run. However, I am having problem with my test environment that prevents the generation of a corefile so I still need to get that sorted out.

**Comment by IBMJimmyk** [comment] 2018-09-19 15:16
I got a corefile. It looks like this one was crashing inside growSlotIterator.

0x000072120e08cfe8 {libj9vm29.so}{growSlotIterator} [0x7211d3fab000]
0x000072120d5ae7f0 {libj9jit29.so}{jitWalkStackFrames} [0x7211d3fab110]
0x000072120e0d2918 {libj9vm29.so}{walkStackFrames} [0x7211d3fab190]
0x000072120e08d6e4 {libj9vm29.so}{internalGrowJavaStack} [0x7211d3fab260]
0x000072120e08e168 {libj9vm29.so}{growJavaStack} [0x7211d3fab5e0]
0x000072120dff9cf4 {libj9vm29.so}{bytecodeLoop} [0x7211d3fab610]
0x000072120e0c03ac {libj9vm29.so}{c_cInterpreter} [0x7211d3faba80]

Crash occurs just after entering growSlotIterator. It tries to load from $r5 but $r5 is 0x0.

**Comment by IBMJimmyk** [comment] 2018-09-19 23:41
This is likely a duplicate. See this comment:
https://github.com/eclipse/openj9/issues/2917#issuecomment-422992665

This test has a low failure rate (maybe around 1 in 20). I'll need to run it a bunch of times to make sure I fixed the problem.

**Closed** 2018-09-21 12:13 UTC
Labels: jdk11, test failure
