### ISSUE TITLE
Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs CondyPrimitive_1

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2958] opened 2018-09-20 11:13 UTC
https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/18/tapResults/

```
===============================================
Running test CondyPrimitive_1 ...
===============================================
CondyPrimitive_1 Start Time: Thu Sep 20 02:51:58 2018 Epoch Time (ms): 1537429918570
test with '-Xjit:count=1,disableA
```

all testing stops

Similar failure on ppc le also mentioned in #2917

**Comment by pshipton** [comment] 2018-09-20 11:15
@irinarada

**Comment by aviansie-ben** [comment] 2018-09-20 13:20
Looking at the full plaintext log of the run (https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/18/consoleText) seems to indicate that testing continues as normal after the following failure in CondyPrimitive_1:

```
===============================================
Running test CondyPrimitive_1 ...
===============================================
CondyPrimitive_1 Start Time: Thu Sep 20 02:51:58 2018 Epoch Time (ms): 1537429918570
test with '-Xjit:count=1,disableAsyncCompilation,rtResolve'
{ "/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdkbinary/j2sdk-image/bin/java"  -Xcompressedrefs '-Xjit:count=1,disableAsyncCompilation,rtResolve'  \
		-cp "/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources:/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/testng.jar:/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/lib/jcommander.jar:/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java11andUp/GeneralTest.jar" \
		org.testng.TestNG -d "/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1537429475873/CondyPrimitive_1" "/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/Java11andUp/testng.xml" -testnames PrimitiveCondyTest \
		-groups level.sanity \
		-excludegroups d.*.aix_ppc-64_cmprssptrs,d.*.arch.ppc,d.*.os.aix,d.*.bits.64,d.*.generic-all; \
		if [ $? -eq 0 ] ; then echo ""; echo "CondyPrimitive_1""_PASSED"; echo ""; else echo ""; echo "CondyPrimitive_1""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_1537429475873/TestTargetResult";
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/TestConfig/resources/excludes/latest_exclude_11.txt
...
... TestNG 6.14.2 by C�dric Beust (cedric@beust.com)
...

0000000030008200: Object neither in heap nor stack-allocated in thread main
0000000030008200:	O-Slot=0000000110048300
0000000030008200:	O-Slot value=3EB0000000000000
0000000030008200:	PC=0000000110954434
0000000030008200:	framesWalked=7
0000000030008200:	arg0EA=00000000300E51F8
0000000030008200:	walkSP=00000000300E4FB8
0000000030008200:	literals=0000000000000000
0000000030008200:	jitInfo=0000000121232D98
0000000030008200:	method=0000000030172A18 (java/util/zip/ZipFile$1.getEntry(Ljava/util/zip/ZipFile;Ljava/lang/String;Ljava/util/function/Function;)Ljava/util/jar/JarEntry;) (JIT)
0000000030008200:	stack=00000000300E0038-00000000300E5F90
07:52:06.589 0x30147200    j9mm.479    *   ** ASSERTION FAILED ** at ../../../../gc_glue_java/ScavengerRootScanner.hpp:105: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, *slotPtr, stackLocation, walkState).validate(_env)))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/09/20 02:52:06 - please wait.
JVMDUMP032I JVM requested System dump using '/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/core.20180920.025206.17760378.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/core.20180920.025206.17760378.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/javacore.20180920.025206.17760378.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/javacore.20180920.025206.17760378.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/Snap.20180920.025206.17760378.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/u0020236/workspace/Test-sanity.functional-JDK11-aix_ppc-64_cmprssptrs/openjdk-tests/functional/Java11andUp/Snap.20180920.025206.17760378.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".

CondyPrimitive_1_FAILED

CondyPrimitive_1 Finish Time: Thu Sep 20 02:52:19 2018 Epoch Time (ms): 1537429939850
```

Not sure why the test results don't reflect this, but the test failure itself seems like a duplicate of #2934.

**Closed** 2018-09-21 12:13 UTC
Labels: comp:jit, jdk11, test failure
