### ISSUE TITLE
java.lang.InternalError: Failed to load default.policy with AdoptOpenJDK 11.0.2 with OpenJ9 used thru Windows UNC 

### ISSUE THREAD

**Issue by avermeer** [eclipse/openj9#4927] opened 2019-02-28 17:22 UTC
Hello,

I have a particular setup for our pool of Windows automated test replay machines where we install Java on a single Windows machine, and I use this Java Runtime with UNC path from other Windows machines.

With this setup, we have detected a regression with AdoptOpenJDK 11.0.2 with OpenJ9 versus AdoptOpenJDK 8 update 202 (both Windows x64): whenever we try to execute Java code with a Java policy, we get this kind of exception:

`Exception in thread "main" java.lang.InternalError: Failed to load default.policy`

I have narrowed the issue with a minimal sample code taken from a Java Tutorial at: https://docs.oracle.com/javase/tutorial/security/tour2/step1.html

To reproduce the issue:

1. Install AdoptOpenJDK 11.0.2 with OpenJ9 Windows x64 on a Windows machine.
   In current example, my machine's host name is "Jupiter"
   I have installed AdoptOpenJDK 11.0.2 with OpenJ9 Windows x64 at path
   `e:\nosave\Java\jdk-11.0.2+9_openj9-0.12.1`

2. Also Install AdoptOpenJDK 8 update 202 with OpenJ9 Windows x64 on same Windows machine
   I have installed AdoptOpenJDK 11.0.2 with OpenJ9 Windows x64 at path
   `e:\nosave\Java\jdk-8.0.202.08-openj9`
 
3. Make sure that the directories where the two AdoptOpenJDK version are installed are accessible from the other Windows machine.
   I have shared the `e:\` directory of my "Jupiter" machine with "HOME" share name
   
4. Connect to the "other" Windows machine, open a command prompt, compile the GetProps.java from https://docs.oracle.com/javase/tutorial/displayCode.html?code=https://docs.oracle.com/javase/tutorial/security/tour2/examples/GetProps.java 

5. Reproduce the issue by typing: `   \\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\bin\java -version`   You get:
```
   openjdk version "11.0.2" 2019-01-15
   OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
   Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.1, JRE 11 Windows Server 2012 R2 amd64-64-Bit Compressed References 20190204_123 (JIT enabled, AOT enabled)
   OpenJ9   - 90dd8cb40
   OMR      - d2f4534b
   JCL      - 289c70b684 based on jdk-11.0.2+9)
```

   then type:
`   \\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\bin\java -Djava.security.manager  GetProps`
   you get:
```
About to get os.name property value
Exception in thread "main" java.lang.InternalError: Failed to load default.policy
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:553)
        at java.base/sun.security.provider.PolicyFile$3.run(PolicyFile.java:358)
        at java.base/sun.security.provider.PolicyFile$3.run(PolicyFile.java:355)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
        at java.base/sun.security.provider.PolicyFile.initPolicyFile(PolicyFile.java:355)
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:345)
        at java.base/sun.security.provider.PolicyFile.<init>(PolicyFile.java:298)
        at java.base/java.security.Policy.loadPolicyProvider(Policy.java:207)
        at java.base/java.security.Policy.getPolicyNoCheck(Policy.java:178)
        at java.base/java.security.ProtectionDomain.implies(ProtectionDomain.java:321)
        at java.base/java.security.ProtectionDomain.impliesWithAltFilePerm(ProtectionDomain.java:353)
        at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:236)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
        at java.base/java.lang.System.getProperty(System.java:450)
        at GetProps.main(GetProps.java:13)
Caused by: java.io.FileNotFoundException: \home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\lib\security\default.policy (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/sun.security.util.PolicyUtil.getInputStream(PolicyUtil.java:60)
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:511)
        ... 16 more
```
which is the unexpected failure.

6. From same command prompt, to show that this issue doesn't take place with AdoptOpenJDK 8 update 202, type:

`\\Jupiter\home\nosave\Java\jdk-8.0.202.08-openj9\bin\java -version`

you get:
```
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Windows Server 2012 R2 amd64-64-Bit Compressed References 20190205_265 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)
```

then type:
`\\Jupiter\home\nosave\Java\jdk-8.0.202.08-openj9\bin\java -Djava.security.manager  GetProps`
you get:
```
About to get os.name property value
  The name of your operating system is: Windows Server 2012 R2
About to get java.version property value
  The version of the JVM you are running is: 1.8.0_202
About to get user.home property value
Caught exception java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "user.home" "read")
```

which is the expected behavior as documented here: https://docs.oracle.com/javase/tutorial/security/tour2/step2.html

I am aware of one by-pass, which consists in mapping the UNC path to a drive letter.

However, this is a regression from AdoptOpenJDK 8 to AdoptOpenJDK 11 and the use of drive letter mapping is inconvenient for many of other use cases.

It looks like with AdoptOpenJDK 11, something is truncating the \\Jupiter from the path of the java command when default.policy file is searched.

Would it be possible to have an analysis and a fix for this issue?

Kind regards,
Alexandre Vermeerbergen

**Comment by DanHeidinga** [comment] 2019-02-28 17:36
@hangshao0 Can you take a look at this?

**Comment by hangshao0** [comment] 2019-02-28 20:56
Does this fail with OpenJDK Java 11 ? @avermeer

**Comment by avermeer** [comment] 2019-02-28 21:05
Hello @hangshao0,

I tried with AdoptOpenJDK 8 with HotSpot and it does not fails.

Kind regards,
Alexandre

**Comment by hangshao0** [comment] 2019-02-28 21:15
What about OpenJDK JDK11 (OpenJDK 11 + HotSpot)  ? @avermeer

**Comment by avermeer** [comment] 2019-02-28 21:20
Hi @hangshao0,

With AdoptOpenJDK 11 with HotSpot it fails.

However, it's the regression from AdoptOpenJDK 8 OpenJ9 to AdoptOpenJDK11 OpenJ9 with bothers me. 

I am not looking for a fix on the HotSpot version.

Kind regards,
Alexandre

**Comment by hangshao0** [comment] 2019-02-28 22:14
This is caused by OpenJDK11 changing the implementation here:

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/share/classes/sun/security/provider/PolicyFile.java#L355-L360

This piece of code is not in OpenJDK8.

**Comment by avermeer** [comment] 2019-02-28 22:17
Alright, but this is not failing on Linux, and it is not failing when Java path is mapped to a Windows drive letter, so can't we say it's a bug?

And if so, how can it be fixed?

Kind regards,
Alexandre

**Comment by hangshao0** [comment] 2019-02-28 22:38
It might be related to the implementation of https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/windows/classes/sun/nio/fs/WindowsFileSystem.java. 

JCL won't call into WindowsFileSystem.java on Linux. 

I am interested in knowing what is the value of property "java.home" ?

**Comment by avermeer** [comment] 2019-02-28 23:07
Hi @hangshao0 ,

I ran `\\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\bin\java GetProps`

(variant without the default security manager), which gives the following result:

```
About to get os.name property value
  The name of your operating system is: Windows Server 2012 R2
About to get java.version property value
  The version of the JVM you are running is: 11.0.2
About to get user.home property value
  Your user home directory is: C:\Users\AVE
About to get java.home property value
  Your JRE installation directory is: \\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1

```
This last path `\\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1` is the value of system property java.home, per the source of GetProps.java.

Clearly this later path is not truncated, so it doesn't seem that the issue's cause is there...

Kind regards,
Alexandre

**Comment by hangshao0** [comment] 2019-02-28 23:11
Thanks. I just want to make sure that J9 JVM does not truncate the path, it is JCL that removes 
`\\Jupiter`

**Comment by avermeer** [comment] 2019-03-07 17:17
Hello @hangshao0,

What are the next steps to get this issue fixed ?

Kind regards, 
Alexandre

**Comment by hangshao0** [comment] 2019-03-07 18:40
Java.home is correct, but `\\Jupiter` is missing here:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/share/classes/sun/security/provider/PolicyFile.java#L283-L285 

Something is wrong with Path.of().toUri().toURL() on Windows. Those implementations are all in the OpenJDK code. So it is a OpenJDK defect, but it is possible to change the OpenJDK code.

**Comment by hangshao0** [comment] 2019-03-07 19:32
Can you run with "-Djava.security.debug=policy" ? What do you see in the output ? @avermeer

**Comment by hangshao0** [comment] 2019-03-07 22:22
> Something is wrong with Path.of().toUri().toURL() on Windows.

Actually it is URL.getFile(). The OpenJDK code eventually calls into this method that removes the host name `\\Jupiter`
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/share/classes/sun/security/util/PolicyUtil.java#L58

I have a simple test case:
```
Path p = Path.of("\\\\Jupiter","lib", "security","default.policy");
URL url = p.toUri().toURL();
System.out.println("URL is: "+ url); 
System.out.println("url.getFile() is: "+ url.getFile());
```

I see the output is:
```
URL is: file://Jupiter/lib/security/default.policy
url.getFile() is: /lib/security/default.policy
```

**Comment by pshipton** [comment] 2019-03-07 22:33
Not sure there is anything wrong with URL.getFile(). Jupiter should be the host name. What is url.getHost()?

**Comment by hangshao0** [comment] 2019-03-07 22:58
url.getHost() returns Jupiter

The host is removed from uriPath by this code on Windows:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/windows/classes/sun/nio/fs/WindowsUriSupport.java#L51-L52

URL.getFile() returns field `file`, but host is not part of `file`: 
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/share/classes/java/net/URL.java#L440

**Comment by hangshao0** [comment] 2019-03-08 20:04
This is a defect of the OpenJDK code. Passing this to you. @andrew-m-leonard

**Comment by avermeer** [comment] 2019-03-17 16:37
Hello @hangshao0,

Adding `-Djava.security.debug=policy` option leads to the print of the proper path of the policy file, but it still fails:

\\Jupiter\home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\bin\java -Djava.security.manager -Djava.security.debug=policy  GetProps
About to get os.name property value
policy: reading file://Jupiter/home/nosave/Java/jdk-11.0.2+9_openj9-0.12.1/lib/security/default.policy
Exception in thread "main" java.lang.InternalError: Failed to load default.policy
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:553)
        at java.base/sun.security.provider.PolicyFile$3.run(PolicyFile.java:358)
        at java.base/sun.security.provider.PolicyFile$3.run(PolicyFile.java:355)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:647)
        at java.base/sun.security.provider.PolicyFile.initPolicyFile(PolicyFile.java:355)
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:345)
        at java.base/sun.security.provider.PolicyFile.<init>(PolicyFile.java:298)
        at java.base/java.security.Policy.loadPolicyProvider(Policy.java:207)
        at java.base/java.security.Policy.getPolicyNoCheck(Policy.java:178)
        at java.base/java.security.ProtectionDomain.implies(ProtectionDomain.java:321)
        at java.base/java.security.ProtectionDomain.impliesWithAltFilePerm(ProtectionDomain.java:353)
        at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:236)
        at java.base/java.security.AccessController.checkPermission(AccessController.java:373)
        at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
        at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
        at java.base/java.lang.System.getProperty(System.java:450)
        at GetProps.main(GetProps.java:13)
Caused by: java.io.FileNotFoundException: \home\nosave\Java\jdk-11.0.2+9_openj9-0.12.1\lib\security\default.policy (The system cannot find the path specified)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at java.base/sun.security.util.PolicyUtil.getInputStream(PolicyUtil.java:60)
        at java.base/sun.security.provider.PolicyFile.init(PolicyFile.java:511)
        ... 16 more

Also worth noting that using -Djava.security.policy=someURL option as document here https://docs.oracle.com/javase/7/docs/technotes/guides/security/PolicyFiles.html is not a working by-pass for this issue.

@andrew-m-leonard : what are the next steps to get this issue fixed?

Kind regards,
Alexandre Vermeerbergen

**Comment by andrew-m-leonard** [comment] 2019-03-18 09:22
@hangshao0 Hi, I can get an OpenJDK "bug" opened, but I need explanation as to what the bug is please? and a simple testcase?
I'm not sure I totally follow the above logic...?
Is there a problem with URL.getFile() ? however @pshipton thinks not?
@avermeer

**Comment by andrew-m-leonard** [comment] 2019-03-18 10:09
@hangshao0 @pshipton I've reviewed the OpenJDK code and it all looks good to me. This output is correct:
```
URL is: file://Jupiter/lib/security/default.policy
url.getFile() is: /lib/security/default.policy
```
protocol = "file"
host = "Jupiter"
file or path = "/lib/security/default.policy"

**Comment by pshipton** [comment] 2019-03-18 13:14
@andrew-m-leonard I don't think there is anything wrong with URL itself. The following code changed between jdk8 and jdk11, causing the test case in the description to fail.

https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/400c27cffa4ab06b19a2ad7e95e1b543e3ac52cc/src/java.base/share/classes/sun/security/provider/PolicyFile.java#L283-L285

**Comment by andrew-m-leonard** [comment] 2019-03-18 14:05
@pshipton I think that line is fine, digging a bit deeper I think the problem is here:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/b44d19c4cbca42541aef5132f21870c1b924a68c/src/java.base/share/classes/sun/security/util/PolicyUtil.java#L57
Which tries to optimize for "file"... however I don't think it will work for a "remote" file as it ignores the url.getHost() bit...!
The jdk8 default policy initialization is done differently so I think doesn't go down this path, it looks like to have a static default policy defined, whereas jdk11 tries to load the given file stream, comment from jdk8:
"if none of these could be loaded, use a builtin static policy
     *      equivalent to the default lib/security/java.policy file."
However, if I read the above code correctly I cannot see how ANY "remote" "file:/host/path.." policy will load!! What do you think Peter?

**Comment by pshipton** [comment] 2019-03-18 15:02
@andrew-m-leonard Seems like a question for the OpenJDK community. Something that "worked" with jdk8 fails to start up with jdk11.

**Comment by hangshao0** [comment] 2019-03-18 15:03
> I need explanation as to what the bug is please? and a simple testcase?

The test case is in the description. Or do you have another simple test case ? @avermeer 
The problem here is that the issue shows up when user change JDK from Java 8 to Java 11 on Windows. It is not there on Linux. The behavior is not consistent.

**Comment by avermeer** [comment] 2019-03-18 15:37
Hello @hangshao0 ,

I do not have another simple test case, except that instructions of my initial test case can be sightly simplified if you use the same Windows machine to install AdopOpenJDK 11 and access your own Windows machine using an UNC path => this also reproduces the issue!

Kind regards,
Alexandre

**Comment by avermeer** [comment] 2019-03-29 21:07
Hello,

I'm afraid I do not understand what are the next step to get this issue fixed.
A question to OpenJDK community was mentioned by @pshipton.
Is it possible to get a URL to the related thread for the follow-up of current incident?

Kind regards,
Alexandre

**Comment by DanHeidinga** [comment] 2019-03-29 21:13
@andrew-m-leonard Can you link to the OpenJDK discussion for issues with the PolicyUtil code?

**Comment by avermeer** [comment] 2019-03-29 21:31
Finally I ran a search on OpenJDK issues, looks like this one is precisely related to current incident:
https://bugs.openjdk.java.net/browse/JDK-8218618

However the issue is marker as fixed only in Java 13, is there any hope to get it back ported to current Java 11 LTS ?

Kind regards,
Alexandre

**Comment by avermeer** [comment] 2019-03-30 06:31
Hello,

I found another reference of this issue in the public version of  JBS (Java Bug System), with other linked incidents, at this place: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8218618. It is worth noting that the fix is not only in Java 13, but was also back-ported to Java 12.

What would be the most efficient way to get this fix in next version of AdoptOpenJDK**11** with **OpenJ9** ?

**Notes:**

- I mentioned  **OpenJ9**, since this is the VM type I'm willing to use
- Although there is a fix for Java 12 & 13, I also insist on Java version **11**, as it is the minimum version I want to support for my applications, given the LTS - Long Term Support nature of this version 
- I do not have a JBS account, so I cannot interact myself with OpenJDK community to ask for this fix back-port.

Kind regards,
Alexanddre

**Comment by pshipton** [comment] 2019-04-01 13:11
@lumpfish @andrew-m-leonard can you please take a look at backporting the fix into the jdk11 extensions.

**Comment by pshipton** [comment] 2019-04-01 15:15
@adamfarley mentioned he is looking at this.

**Comment by pshipton** [comment] 2019-04-01 18:23
Already linked above, but fyi the jdk11 tracking issue https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/148

**Comment by pshipton** [comment] 2019-04-04 20:20
The backport PR is https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/151

**Comment by adamfarley** [comment] 2019-04-05 09:27
A backport bug has been raised in the OpenJDK community: https://bugs.openjdk.java.net/browse/JDK-8221990

I've also notified the security-dev mailing list and asked for reviews.

**Comment by pshipton** [comment] 2019-04-05 14:01
@adamfarley at what point in this process can we merge ibmruntimes/openj9-openjdk-jdk11#151? I don't expect the OpenJDK community to accept the change in time for the April 16th release, but we do want this change in the OpenJDK + OpenJ9 equivalent.

**Comment by adamfarley** [comment] 2019-04-05 14:14
We've already had a response from a Reviewer in the updates project (that contains 11u) saying he doesn't see any potential issues, so I've straight-up asked him to sponsor the change.

If this doesn't get approved in time, the PR can be merged at the last minute, so at least OpenJ9 OpenJDK11 will contain the change.

As for "readiness status", the PR is fit to be merged whenever we want to merge it.

**Comment by pshipton** [comment] 2019-04-05 14:55
@adamfarley I'd be happy to merge it before the OpenJDK + OpenJ9 Milestone 1 build on April 9. Note the PR is still marked WIP.

**Comment by andrew-m-leonard** [comment] 2019-04-08 08:40
@adamfarley we probably need to officially request the original jdk13 bug fix for backport according to the process documented here: http://openjdk.java.net/projects/jdk-updates/approval.html
or specifically documented by Admam Haley for jdk11u here:  https://wiki.openjdk.java.net/display/JDKUpdates/JDK11u    section "Fix Approvals"

**Comment by adamfarley** [comment] 2019-04-08 10:37
Done. As for the PR, I'm getting approval for that now.

**Comment by pshipton** [comment] 2019-04-08 13:00
Thanks Adam.

**Closed by pshipton** 2019-04-08 13:00 UTC
Labels: userRaised

**Comment by avermeer** [comment] 2019-04-08 13:05
Great news!
I will try the nightly build in 2 or 3 days and will provide feedback on this fix.

**Comment by pshipton** [comment] 2019-04-08 13:14
@avermeer note we are producing a Milestone 1 build for the OpenJ9 0.14 release, as a preview of the release content. Assuming you plan to use the 0.14 release and not a nightly build, it would be a good idea to try out the M1 build. It should be available sometime in the next couple of days.

**Comment by avermeer** [comment] 2019-04-08 13:16
@pshipton yes I plan to use the 0.14 release, and your proposal for me to try the fix with M1 build sounds very good.

Question: will there be an announce for M1 build availability? 
and where will it be accessible if not on "AdoptOpenJDK" nightly builds page?

**Comment by pshipton** [comment] 2019-04-08 13:31
@avermeer Previously it has been announced on Slack. As an example, here is the 0.13 announcement https://openj9.slack.com/archives/C8312LCV9/p1551969207014100

**Comment by pshipton** [comment] 2019-04-16 19:30
@avermeer https://openj9.slack.com/archives/C8312LCV9/p1555442998007800
