### ISSUE TITLE
libjncrypto.dylib references /usr/local/lib/libcrypto.1.1.dylib

### ISSUE THREAD

**Issue by breun** [eclipse/openj9#4410] opened 2019-01-23 19:47 UTC
I'm the package maintainer for AdoptOpenJDK packages in MacPorts and I'm trying to package AdoptOpenJDK 8u202 with OpenJ9 for Mac from https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#x64_mac. Upon package installation MacPorts checks all libraries and gives me this error:

```
Could not open /usr/local/lib/libcrypto.1.1.dylib: Error opening or reading file (referenced from /Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home/jre/lib/libjncrypto.dylib)
DEBUG: Marking /Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home/jre/lib/libjncrypto.dylib as broken
```

It indeed seems `Contents/Home/jre/lib/libjncrypto.dylib` is referencing `/usr/local/lib/libcrypto.1.1.dylib`:

```
$ otool -L /Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home/jre/lib/libcrypto.1.1.dylib
/Library/Java/JavaVirtualMachines/openjdk8-openj9/Contents/Home/jre/lib/libcrypto.1.1.dylib:
	/usr/local/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

`/usr/local/lib/libcrypto.1.1.dylib` is not available on my system, and I guess not on most other people's machines either.

**Comment by pshipton** [comment] 2019-01-23 20:23
This is a duplicate of https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/98

**Comment by DanHeidinga** [comment] 2019-01-24 15:23
@breun Thanks for reporting this.

**Comment by pshipton** [comment] 2019-01-28 00:11
Fixed in the head stream by ibmruntimes/openj9-openjdk-jdk8#244 and ibmruntimes/openj9-openjdk-jdk11#102.

In the 0.12 release branch jdk8 still pending, and ibmruntimes/openj9-openjdk-jdk11#105.

**Closed** 2019-01-28 04:38 UTC
Labels: userRaised
