### ISSUE TITLE
CHTable warning messages are indicative of a latent bug

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#3471] opened 2018-10-29 19:11 UTC
The JITaaS server sometimes emits warning messages when applying the set of CHTable modifications received from the client.
` fprintf(stderr, "CHTable WARNING: classInfo for subclass %p of %p is null, ignoring\n", flat->_subClasses[i], flat->_classId);`
This happens when a subclass in the list of subclasses for a superclass is not found in the CHTable in its own right. This should never happen and needs to be corrected.

**Comment by dmitry-ten** [comment] 2018-11-01 20:11
I found the cause of the bug.
Consider the following scenario:
**Setup**: 
- classes A and B are loaded and their classInfo is the PersistentCHTable. B is a subclass of A. 
- 1 client, 1 server, 2 compilations on 2 threads.
**Events**:
1. *Thread 1* modifies classInfo of A. 
2. *Thread 1* sends CH table commit to the server. {Commit: modified A}
3. Class B is unloaded, thus A is marked as dirty, B is marked for removal.
4. *Thread 2* sends CH table commit to the server. {Commit: modified A, removed B}
5. *(Server) Thread 2* receives CH table commit. classInfo of B is removed, B is also removed from the list of subclasses of A.
6. *(Server) Thread 1* receives CH table commit. When update of A is performed, all subclasses are set again. This results in an attempt to access classInfo of B, but it's already been deleted.

**Comment by dmitry-ten** [comment] 2018-11-01 20:32
FYI @mpirvu

**Comment by mpirvu** [comment] 2018-11-01 20:32
Thanks Dmitry for tracking this down!
So the problem appears due to message reordering. There is a similar issue with messages that we send for class unloading and my proposal at the time was to use sequence IDs to play the messages in order. I will copy that issue from the internal repo to the public one.

**Comment by mpirvu** [comment] 2018-11-01 20:36
I was creating another issue the other day (but didn't have time to finish it) proposing to send CHTable updates together with compilation requests to reduce the number of messages. Doing so we could use one just one sequence number for class unloading and CHTable updates.

**Comment by mpirvu** [comment] 2018-11-01 20:45
Similar issue regarding class unloading updates: https://github.com/eclipse/openj9/issues/3520

**Closed** 2018-12-05 17:36 UTC
Labels: bug, jitaas
