### ISSUE TITLE
JDK15 gcNotificationTest_Balanced_1_FAILED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10246] opened 2020-07-24 19:54 UTC
Failure link
------------

From an internal build `Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/12`:
```
02:32:57  openjdk version "15-internal" 2020-09-15
02:32:57  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64lelinuxNightly)
02:32:57  Eclipse OpenJ9 VM (build master-f60babb2cfa, JRE 15 Linux ppc64le-64-Bit Compressed References 20200723_24 (JIT enabled, AOT enabled)
02:32:57  OpenJ9   - f60babb2cfa
02:32:57  OMR      - 025d6b2b62b
02:32:57  JCL      - 3604912533c based on jdk-15+32)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
===============================================
Running test gcNotificationTest_Balanced_1 ...
===============================================
gcNotificationTest_Balanced_1 Start Time: Fri Jul 24 01:27:34 2020 Epoch Time (ms): 1595579254024
variation: Mode551 -XX:+HeapManagementMXBeanCompatibility -Xmx512m
JVM_OPTIONS:  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -XX:+HeapManagementMXBeanCompatibility -Xmx512m 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_15.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

JVMDUMP039I Processing dump event "abort", detail "" at 2020/07/24 01:27:43 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/core.20200724.012743.22127.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/core.20200724.012743.22127.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/javacore.20200724.012743.22127.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/javacore.20200724.012743.22127.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/Snap.20200724.012743.22127.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/Snap.20200724.012743.22127.0003.trc
JVMDUMP032I JVM requested JIT dump using '/home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/jitdump.20200724.012743.22127.0004.dmp' in response to an event
JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955732245521/gcNotificationTest_Balanced_1/jitdump.20200724.012743.22127.0004.dmp
JVMDUMP013I Processed dump event "abort", detail "".

gcNotificationTest_Balanced_1_FAILED
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
04:28:04  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=ppc64le_linux&TARGET=gcNotificationTest_Balanced_1

**Comment by JasonFengJ9** [comment] 2020-07-24 19:58
Similar failure at JDK 16:

```
===============================================
Running test gcNotificationTest_Balanced_1 ...
===============================================
gcNotificationTest_Balanced_1 Start Time: Fri Jul 24 01:11:56 2020 Epoch Time (ms): 1595578316091
variation: Mode551 -XX:+HeapManagementMXBeanCompatibility -Xmx512m
JVM_OPTIONS:  -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced -XX:+HeapManagementMXBeanCompatibility -Xmx512m 
[IncludeExcludeTestAnnotationTransformer] [INFO] exclude file is /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/../TestConfig/resources/excludes/latest_exclude_16.txt
...
... TestNG 6.14.2 by Cédric Beust (cedric@beust.com)
...

08:12:06.342 0x143700    j9mm.107    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:4939: ((false && (isLiveObject(referenceObj))))
JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/07/24 01:12:06 - please wait.
JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/core.20200724.011206.22368.0001.dmp' in response to an event
JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/core.20200724.011206.22368.0001.dmp
JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/javacore.20200724.011206.22368.0002.txt' in response to an event
JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/javacore.20200724.011206.22368.0002.txt
JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/Snap.20200724.011206.22368.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdkNext_j9_extended.functional_ppc64le_linux_Nightly_testList_0/openjdk-tests/TKG/test_output_15955770766150/gcNotificationTest_Balanced_1/Snap.20200724.011206.22368.0003.trc
JVMDUMP013I Processed dump event "traceassert", detail "".

gcNotificationTest_Balanced_1_FAILED
```

**Comment by dmitripivkine** [comment] 2020-07-24 20:26
looking... @amicic FYI

**Comment by dmitripivkine** [comment] 2020-07-27 16:30
this is duplicate of https://github.com/eclipse/openj9/issues/10249

**Closed by dmitripivkine** 2020-07-27 16:30 UTC
Labels: comp:gc, jdk15, test failure
