### ISSUE TITLE
JDK11 JIT Server : ASSERTION FAILED ** at CopyForwardScheme.cpp:3649

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9170] opened 2020-04-07 22:47 UTC
Failure link
------------

From an internal build `Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/242`:
```
00:02:18  openjdk version "11.0.7-internal" 2020-04-14
00:02:18  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
00:02:18  Eclipse OpenJ9 VM (build ibm_sdk-934063f45c, JRE 11 Linux amd64-64-Bit Compressed References 20200406_42 (JIT enabled, AOT enabled)
00:02:18  OpenJ9   - 934063f45c
00:02:18  OMR      - b7eb64f76
00:02:18  JCL      - ea4a5a16094 based on jdk-11.0.7+9)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
DLT 21:07:48.164 -   18 ArbitraryJava[net.openj9.test.PDMoveShifts.ShiftTestRunner invokeTest]  Weighting=1 
DLT 21:07:48.291 - Starting thread. Suite=0 thread=0
DLT 21:07:48.294 - Starting thread. Suite=0 thread=1
DLT 21:08:08.335 - Completed 7.2%. Number of tests started=136
DLT stderr 0000000000ADAC00: J9_INVALID_OBJECT in thread load-1
DLT stderr 0000000000ADAC00:	O-Slot=00007FBAF897F468
DLT stderr 0000000000ADAC00:	O-Slot value=FFFFFFFFFFFFFFFF
DLT stderr 0000000000ADAC00:	PC=00007FBAFBE038E7
DLT stderr 0000000000ADAC00:	framesWalked=8
DLT stderr 0000000000ADAC00:	arg0EA=0000000000AE2100
DLT stderr 0000000000ADAC00:	walkSP=0000000000AE2010
DLT stderr 0000000000ADAC00:	literals=000000000086FA48
DLT stderr 0000000000ADAC00:	jitInfo=00007FBAF90EE1B8
DLT stderr 0000000000ADAC00:	method=0000000000AD66D8 (jdk/internal/reflect/GeneratedConstructorAccessor22.newInstance([Ljava/lang/Object;)Ljava/lang/Object;) (JIT)
DLT stderr 0000000000ADAC00:	stack=0000000000ADB788-0000000000AE27A0
DLT stderr 04:08:24.600 0x7b0300    j9mm.479    *   ** ASSERTION FAILED ** at CopyForwardScheme.cpp:3649: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, *slotPtr, stackLocation, walkState).validate(_env)))
DLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/04/06 21:08:24 - please wait.
DLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/core.20200406.210824.4626.0001.dmp' in response to an event
DLT stderr JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.4713.
DLT stderr 
DLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/core.20200406.210824.4626.0001.dmp
DLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/javacore.20200406.210824.4626.0002.txt' in response to an event
DLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/javacore.20200406.210824.4626.0002.txt
DLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/Snap.20200406.210824.4626.0003.trc' in response to an event
STF 21:08:29.049 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/javacore.20200406.210824.4626.0002.txt
STF 21:08:29.050 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/core.20200406.210824.4626.0001.dmp
STF 21:08:29.050 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/Snap.20200406.210824.4626.0003.trc
DLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/javacore.20200406.210824.4626.0002.txt
DLT stderr core file generated - /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/core.20200406.210824.4626.0001.dmp
DLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/Snap.20200406.210824.4626.0003.trc
DLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/results/Snap.20200406.210824.4626.0003.trc
DLT stderr JVMDUMP013I Processed dump event "traceassert", detail "".
STF 21:08:29.473 - **FAILED** Process DLT ended with exit code (255) and not the expected exit code/s (0)
STF 21:08:29.473 - Monitoring Report Summary:
STF 21:08:29.473 -   o Process DLT has crashed unexpectedly
STF 21:08:29.474 - Killing processes: DLT
STF 21:08:29.474 -   o Process DLT is not running
**FAILED** at step 1 (Run daa load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/../TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/execute.pl line 97.
STF 21:08:29.656 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 21:08:29.656 - 
STF 21:08:29.656 - ====================   T E A R D O W N   ====================
STF 21:08:29.656 - Running teardown: perl /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/../TKG/test_output_15862323211420/DaaLoadTest_daa1_special_14/20200406-210742-DaaLoadTest/tearDown.pl
STF 21:08:29.733 - TEARDOWN stage completed
STF 21:08:29.739 - 
STF 21:08:29.739 - =====================   R E S U L T S   =====================
STF 21:08:29.739 - Stage results:
STF 21:08:29.739 -   setUp:     pass
STF 21:08:29.739 -   execute:  *fail*
STF 21:08:29.739 -   teardown:  pass
STF 21:08:29.739 - 
STF 21:08:29.739 - Overall result: **FAILED**

DaaLoadTest_daa1_special_14_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system/daaLoadTest&PLATFORM=x86-64_linux&TARGET=DaaLoadTest_daa1_special_14

**Comment by pshipton** [comment] 2020-04-08 00:01
@mpirvu

**Comment by dmitripivkine** [comment] 2020-04-08 16:06
most likely a duplicate of https://github.com/eclipse/openj9/issues/8789 and (or) https://github.com/eclipse/openj9/issues/9123

**Comment by dmitripivkine** [comment] 2020-04-08 19:46
> most likely a duplicate of #8789 and (or) #9123
> Also this is `-Xgcpolicy:balanced` so the problem (as we expected) is not a Concurrent Scavenge specific.

yes, looks like it is the same problem:
```
> !j9method 0xAD66D8
J9Method at 0xad66d8 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00007FBA94060880
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x0000000000AD65C0 (flags = 0x0)
	0x10: void* methodRunAddress = !j9x 0x0000000000000006
	0x18: void* extra = !j9x 0x0000000000000685
}
Signature: jdk/internal/reflect/GeneratedConstructorAccessor22.newInstance([Ljava/lang/Object;)Ljava/lang/Object; !bytecodes 0x0000000000AD66D8
ROM Method: !j9rommethod 0x00007FBA9406086C
Next Method: !j9method 0x0000000000AD66F8
> !j9constantpool 0x0000000000AD65C0
J9ConstantPool at 0xad65c0 {
  Fields for J9ConstantPool:
	0x0: struct J9Class* ramClass = !j9class 0x0000000000AD6400 // jdk/internal/reflect/GeneratedConstructorAccessor22
	0x8: struct J9ROMConstantPoolItem* romConstantPool = !j9romconstantpoolitem 0x00007FBA940607B0
}
> !j9class 0x0000000000AD6400
J9Class at 0xad6400 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
	0x8: struct J9ROMClass* romClass = !j9romclass 0x00007FBA94060700
	0x10: void** superclasses = !j9x 0x0000000000AD66F8
	0x18: UDATA classDepthAndFlags = 0x00000000080E0003 (135135235) <--- unloaded
	0x20: U32 classDepthWithFlags = 0x00000000 (0)
	0x24: U32 classFlags = 0x00002000 (8192)
	0x28: struct J9ClassLoader* classLoader = !j9classloader 0x00007FBB180F2018
	0x30: struct J9Object* classObject = !j9object 0xFFFFFFFFFFFFFFFF<FAULT>
	0x38: volatile UDATA initializeStatus = 0x0000000000000001 (1)
	0x40: struct J9Method* ramMethods = !j9method 0x0000000000AD66B8 // jdk/internal/reflect/GeneratedConstructorAccessor22.<init>()V
	0x48: UDATA* ramStatics = !j9x 0x0000000000000000
	0x50: struct J9Class* arrayClass = !j9class 0x0000000000000000
	0x58: UDATA totalInstanceSize = 0x0000000000000004 (4)
	0x60: struct J9ITable* lastITable = !j9itable 0x00000000006FA288
	0x68: UDATA* instanceDescription = !j9x 0x0000000000000001
	0x70: UDATA* instanceLeafDescription = !j9x 0x0000000000000001
	0x78: UDATA instanceHotFieldDescription = 0x0000000000000000 (0)
	0x80: UDATA selfReferencingField1 = 0x0000000000000000 (0)
	0x88: UDATA selfReferencingField2 = 0x0000000000000000 (0)
	0x90: struct J9Method* initializerCache = !j9method 0x0000000000AD66B8 // jdk/internal/reflect/GeneratedConstructorAccessor22.<init>()V
	0x98: UDATA romableAotITable = 0x00007FBB1773CD80 (140441529077120)
	0xa0: UDATA packageID = 0x00007FBA94060701 (140439324067585)
	0xa8: struct J9Module* module = !j9module 0x0000000000000000
	0xb0: struct J9Class* subclassTraversalLink = !j9class 0x0000000000AD6400 // jdk/internal/reflect/GeneratedConstructorAccessor22
	0xb8: struct J9Class* subclassTraversalReverseLink = !j9class 0x0000000000AD6400 // jdk/internal/reflect/GeneratedConstructorAccessor22
	0xc0: void** iTable = !j9x 0x00000000006FA288
	0xc8: UDATA castClassCache = 0x0000000000706C00 (7367680)
	0xd0: void** jniIDs = !j9x 0x0000000000000000
	0xd8: UDATA lockOffset = 0x0000000000000004 (4)
	0xe0: U32 paddingForGLRCounters = 0x00000000 (0)
	0xe4: U16 reservedCounter = 0x0000 (0)
	0xe6: U16 cancelCounter = 0x0000 (0)
	0xe8: UDATA newInstanceCount = 0x00000000000003E8 (1000)
	0xf0: IDATA backfillOffset = 0x0000000000000008 (8)
	0xf8: struct J9Class* replacedClass = !j9class 0x0000000000000000
	0x100: UDATA finalizeLinkOffset = 0x0000000000000000 (0)
	0x108: struct J9Class* nextClassInSegment = !j9class 0x0000000000000000
	0x110: UDATA* ramConstantPool = !j9x 0x0000000000AD65C0
	0x118: struct J9Object** callSites = !j9x 0x0000000000000000
	0x120: struct J9Object** methodTypes = !j9x 0x0000000000000000
	0x128: struct J9Object** varHandleMethodTypes = !j9x 0x0000000000000000
	0x130: struct J9VMCustomSpinOptions* customSpinOption = !j9vmcustomspinoptions 0x0000000000000000
	0x138: void** staticSplitMethodTable = !j9x 0x0000000000000000
	0x140: void** specialSplitMethodTable = !j9x 0x0000000000000000
	0x148: struct J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
	0x150: struct J9Class* gcLink = !j9class 0x0000000000000000
	0x158: struct J9Class* hostClass = !j9class 0x0000000000AD6400 // jdk/internal/reflect/GeneratedConstructorAccessor22
	0x160: struct J9Class* nestHost = !j9class 0x0000000000000000
	0x168: struct J9FlattenedClassCache* flattenedClassCache = !j9flattenedclasscache 0x0000000000000000
}
Class name: jdk/internal/reflect/GeneratedConstructorAccessor22
To view static fields, use !j9statics 0x0000000000AD6400
To view instance shape, use !j9classshape 0x0000000000AD6400
>```

**Comment by a7ehuo** [comment] 2020-05-07 20:00
Tried the build as below on `04/30` in Grinder, FR: `21/100`.
```
18:52:20  JITServer is ready to accept incoming requests
18:52:20  openjdk version "1.8.0_262-internal"
18:52:20  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_04_30_14_10-b00)
18:52:20  Eclipse OpenJ9 VM (build master-ef109f7c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200430_1436 (JIT enabled, AOT enabled)
18:52:20  OpenJ9   - ef109f7c2
18:52:20  OMR      - f2285166b
18:52:20  JCL      - ed7c83cea53 based on jdk8u262-b01)
```

**Comment by a7ehuo** [comment] 2020-05-13 21:34
With `DaaLoadTest_daa1_special_14`, I was able to reproduce a crash [1] in `markClassesInInlineRanges()` after limiting the compilation to one method as below: 
```
+ (warm) org/junit/runners/BlockJUnit4ClassRunner$1.runReflectiveCall()Ljava/lang/Object; @ 00007FC96E073CC0-00007FC96E0743BD OrdinaryMethod - Q_SZ=209 Q_SZI=203 QW=1664 j9m=0000000000432258 bcsz=8 remote compThreadID=4 CpuLoad=718%(89%avg) JvmCpu=342%
```

Looks like the inlinedMethod inside the metaData is corrupted. @mpirvu found that the `createClassUnloadPicSite` is skipped at the server [2]. Working on a fix next. 

[1]
```
~~~~~~~~~~~~~~~
#12 <signal handler called>
#13 0x00007f4d76efc017 in markClassesInInlineRanges (methodMetaData=0x7f4d59c0a2f8, walkState=0x7f4d599507d0)
    at /root/home/ahuo/src/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-release/vm/compiler/../compiler/runtime/MethodMetaData.c:629
#14 0x00007f4d77755884 in jitWalkStackFrames (walkState=0x7f4d599507d0) at jswalk.c:239
#15 0x00007f4d7e42274e in walkStackFrames (currentThread=0x120c00, walkState=0x7f4d599507d0) at swalk.c:335
#16 0x00007f4d7c0e3776 in GC_VMThreadStackSlotIterator::scanSlots (vmThread=<optimized out>, 
    walkThread=walkThread@entry=0x3d8600, userData=userData@entry=0x7f4d59950ae0, 
    oSlotIterator=oSlotIterator@entry=0x7f4d7c0d7cb0 <stackSlotIterator(J9JavaVM*, J9Object**, void*, J9StackWalkState*, void--Type <RET> for more, q to quit, c to continue without paging--
 const*)>, includeStackFrameClassReferences=<optimized out>, trackVisibleFrameDepth=<optimized out>)
    at VMThreadStackSlotIterator.cpp:114
#17 0x00007f4d7c0d758d in MM_RootScanner::scanOneThread (this=0x7f4d59950b30, env=0x7f4d08001cc8, walkThread=0x3d8600, 
    localData=0x7f4d59950ae0) at RootScanner.cpp:519
#18 0x00007f4d7c0d649f in MM_RootScanner::scanThreads (this=this@entry=0x7f4d59950b30, env=env@entry=0x7f4d08001cc8)
    at RootScanner.cpp:488
#19 0x00007f4d7c1b00d2 in MM_GlobalMarkingSchemeRootMarker::scanRoots (env=0x7f4d08001cc8, this=0x7f4d59950b30)
    at GlobalMarkingScheme.cpp:1088
#20 MM_GlobalMarkingScheme::markLiveObjectsRoots (this=0x7f4d780776b0, env=env@entry=0x7f4d08001cc8)
    at GlobalMarkingScheme.cpp:1396
#21 0x00007f4d7c1b1f94 in MM_ParallelGlobalMarkTask::run (this=0x7f4d59ad6a80, envBase=0x7f4d08001cc8)
    at GlobalMarkingScheme.cpp:129
#22 0x00007f4d7c1e2b9b in MM_ParallelDispatcher::slaveEntryPoint (this=0x7f4d7804bc50, env=0x7f4d08001cc8)
    at ParallelDispatcher.cpp:170
```

```
(gdb) print inlinedMethod
$2 = (J9Method *) 0x1456c8 <= corrupted 

> !j9method 0x1456c8
J9Method at 0x1456c8 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x0000000000000006
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x00000000000007C0 (flags = 0xF)
	0x10: void* methodRunAddress = !j9x 0x00007F4CE00120C8
	0x18: void* extra = !j9x 0x00000000001455B0
}
Signature: <FAULT>
ROM Method: !j9rommethod 0xFFFFFFFFFFFFFFF2
Next Method: !j9method 0x00000000001456E8

> !j9constantpool 0x00000000000007C0 
J9ConstantPool at 0x7c0 {
  Fields for J9ConstantPool:
	0x0: struct J9Class* ramClass = <FAULT>
	0x8: struct J9ROMConstantPoolItem* romConstantPool = <FAULT>
}
```

[2]
https://github.com/eclipse/openj9/blob/f3e03dbfd72777811ff9857360fcdf4ec009cee4/runtime/compiler/runtime/MetaData.cpp#L1251-L1276

**Comment by dmitripivkine** [comment] 2020-09-25 19:03
This problem has been solved and item can be closed

**Closed by dmitripivkine** 2020-09-25 19:03 UTC
Labels: comp:jitserver, test failure
