### ISSUE TITLE
JDK15 Windows : DaaLoadTest_daa1_special_14 j9mm.316    *   ** ASSERTION FAILED ** at GlobalMarkingScheme.cpp:870: ((uintptr_t)0x99669966 == (clazz)->eyecatcher)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10250] opened 2020-07-24 20:35 UTC
Failure link
------------

From an internal build `Test_openjdk15_j9_special.system_x86-64_windows_Nightly_daaLoadTest/3`:
```
01:04:51  openjdk version "15-internal" 2020-09-15
01:04:51  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15x86-64windowsNightly)
01:04:51  Eclipse OpenJ9 VM (build master-f60babb2cfa, JRE 15 Windows Server 2016 amd64-64-Bit Compressed References 20200723_24 (JIT enabled, AOT enabled)
01:04:51  OpenJ9   - f60babb2cfa
01:04:51  OMR      - 025d6b2b62b
01:04:51  JCL      - 3604912533c based on jdk-15+32)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
=============================================== 
Running test DaaLoadTest_daa1_special_14 ... 
===============================================

DLT 01:13:19.571 - Starting thread. Suite=0 thread=1
DLT 01:13:39.631 - Completed 9.3%. Number of tests started=177
DLT stderr 05:13:54.322 0x154100    j9mm.316    *   ** ASSERTION FAILED ** at GlobalMarkingScheme.cpp:870: ((uintptr_t)0x99669966 == (clazz)->eyecatcher)
DLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/07/24 01:13:54 - please wait.
DLT stderr JVMDUMP032I JVM requested System dump using 'C:\Users\jenkins\workspace\Test_openjdk15_j9_special.system_x86-64_windows_Nightly_daaLoadTest\openjdk-tests\TKG\test_output_15955675655229\DaaLoadTest_daa1_special_14\20200724-011309-DaaLoadTest\results\core.20200724.011354.8992.0001.dmp' in response to an event
STF 01:13:54.696 - Found dump at: C:\Users\jenkins\workspace\Test_openjdk15_j9_special.system_x86-64_windows_Nightly_daaLoadTest\openjdk-tests\TKG\test_output_15955675655229\DaaLoadTest_daa1_special_14\20200724-011309-DaaLoadTest\results\core.20200724.011354.8992.0001.dmp
DLT stderr core file generated - C:\Users\jenkins\workspace\Test_openjdk15_j9_special.system_x86-64_windows_Nightly_daaLoadTest\openjdk-tests\TKG\test_output_15955675655229\DaaLoadTest_daa1_special_14\20200724-011309-DaaLoadTest\results\core.20200724.011354.8992.0001.dmp
DLT stderr 92.0001.dmp

DaaLoadTest_daa1_special_14_FAILED
```
For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
04:14:16  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=system/daaLoadTest&PLATFORM=x86-64_windows&TARGET=DaaLoadTest_daa1_special_14

**Comment by dmitripivkine** [comment] 2020-07-27 16:03
this is a duplicate of https://github.com/eclipse/openj9/issues/10249

**Closed by dmitripivkine** 2020-07-27 16:03 UTC
Labels: comp:gc, comp:vm, jdk15, test failure
