### ISSUE TITLE
OpenJ9 and JRebel Segmentation error

### ISSUE THREAD

**Issue by snoobvn** [eclipse/openj9#1542] opened 2018-03-26 21:06 UTC
It works fine with OpenJDK (nightly build) but not with OpenJDK with OpenJ9
Build: OpenJDK9-OPENJ9_x64_Win_20182203
Here is the full log: https://gist.github.com/snoobvn/0c1488f59baaf33ab4635a0c4addf56f
core.20180327.035809.4116.0001.dmp is a 1GB file so I can't post it here
[javacore.20180327.035809.4116.0002.txt](https://github.com/eclipse/openj9/files/1849537/javacore.20180327.035809.4116.0002.txt)

**Comment by pshipton** [comment] 2018-03-26 21:14
@dmitripivkine is there anything that can be done here without DDR?

**Comment by pshipton** [comment] 2018-03-26 21:47
There was discussion about this problem on Slack in #newcomers. Seems JRebel may not be detecting OpenJ9 correctly, and incorrectly treating it as Hotspot.

**Comment by dmitripivkine** [comment] 2018-03-26 22:15
Well, we can try to reproduce it in some less hostile environment... Looks like it is a startup time, so I guess kind of data mismatch.

**Comment by Maldivia** [comment] 2018-03-26 23:12
This is a JRebel issue, we're doing some (nasty) stuff during very early VM startup, that in this case causes classes to try to be loaded too early.

**Comment by pshipton** [comment] 2018-03-27 00:39
> This is a JRebel issue...

Closing

**Closed by pshipton** 2018-03-27 00:39 UTC
Labels: userRaised
