### ISSUE TITLE
Compiler crash in Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl

### ISSUE THREAD

**Issue by austin0** [eclipse/openj9#10195] opened 2020-07-20 14:29 UTC
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/161/console
https://trss.adoptopenjdk.net/output/test?id=5f1512677eaab3443cafc357
https://trss.adoptopenjdk.net/output/test?id=5f1512677eaab3443cafc358
------------

Compiler crashed while running `jdk_lang_j9_0` and `jdk_util_j9_0`.

First occurrence (jdk_lang_j9_0):
```
01:25:51  --------------------------------------------------
01:25:51  TEST: java/lang/invoke/condy/CondyReturnPrimitiveTest.java
01:25:51  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/openjdkbinary/j2sdk-image
01:25:51  
01:25:51  ACTION: build -- Error. compiler crashed (exit code 4)
01:25:51  REASON: User specified action: run build jdk.experimental.bytecode.BasicClassBuilder 
01:25:51  TIME:   6.51 seconds
```

JTReg error:
```
01:25:51  An exception has occurred in the compiler (11.0.8). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
01:25:51  java.lang.NullPointerException
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Infer$GraphSolver.solve(Infer.java:1670)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:475)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.InferenceContext.solve(InferenceContext.java:482)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:218)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:605)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1563)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1733)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1802)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1776)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve$10.doLookup(Resolve.java:2654)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3293)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3543)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2651)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Resolve.resolveInternalMethod(Resolve.java:2733)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.lookupMethod(Lower.java:788)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.makeCall(Lower.java:1851)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.visitEnumDef(Lower.java:2363)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.visitClassDef(Lower.java:2169)
01:25:51  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:774)
01:25:51  	at jdk.compiler/com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.translate(Lower.java:2064)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.translate(Lower.java:2083)
01:25:51  	at jdk.compiler/com.sun.tools.javac.comp.Lower.translateTopLevelClass(Lower.java:3678)
01:25:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1579)
01:25:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1432)
01:25:51  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
01:25:51  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
01:25:51  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
01:25:51  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
01:25:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:25:51  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:25:51  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:25:51  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:25:51  	at com.sun.javatest.regtest.agent.RegressionCompileCommand.run(RegressionCompileCommand.java:189)
01:25:51  	at com.sun.javatest.regtest.agent.CompileActionHelper.runCompile(CompileActionHelper.java:92)
01:25:51  	at com.sun.javatest.regtest.agent.AgentServer.doCompile(AgentServer.java:262)
01:25:51  	at com.sun.javatest.regtest.agent.AgentServer.run(AgentServer.java:229)
01:25:51  	at com.sun.javatest.regtest.agent.AgentServer.main(AgentServer.java:69)
01:25:51  
01:25:51  TEST RESULT: Error. compiler crashed (exit code 4)
01:25:51  --------------------------------------------------
```

Optional info
-------------

- intermittent failure (yes|no): yes
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) : 
Last Passing OpenJ9: 45adb18eb1fe8eb68dcc6630ca70855d6ad12b32
Last Passing Build: https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/158/

Failure output
---------------------------------------------
https://ci.adoptopenjdk.net/job/Test_openjdk11_j9_sanity.openjdk_aarch64_linux_xl/161/artifact/openjdk_test_output.tar.gz

**Comment by 0xdaryl** [comment] 2020-07-20 14:39
This is a duplicate of #10126.

**Closed by 0xdaryl** 2020-07-20 14:39 UTC
Labels: test failure
