### ISSUE TITLE
FVT_Serviceability.trace.trigger.system_dump Segmentation error vmState=0x0002000f

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7713] opened 2019-11-07 13:22 UTC
Failure link
------------

```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pwa6480sr6-20191024_01(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 Windows 10 amd64-64-Bit 20191106_432144 (JIT enabled, AOT enabled)
OpenJ9   - a971152
OMR      - 02e4821
IBM      - ae1a7e3)
JCL - 20191016_01 based on Oracle jdk8u231-b10
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
j> 23:41:39 20191106 23:41:39 Execution Timer INFO: Execution Timer started
j> 23:41:39 20191106 23:41:39 Thread Control Engine INFO: Starting JobSet Primary
j> 23:42:04 Unhandled exception
j> 23:42:04 Type=Segmentation error vmState=0x0002000f
j> 23:42:04 Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FF8EB6EAAFF ContextFlags=0010001f
j> 23:42:04 Handler1=00007FF8EB8BB000 Handler2=00007FF8F271D8C0 InaccessibleReadAddress=0000000000000018
j> 23:42:04 RDI=0000000000000000 RSI=00000000073EC808 RAX=00000000008182F8 RBX=0000000000000000
j> 23:42:04 RCX=00000000008D0220 RDX=00000000073EC808 R8=00000000008D0220 R9=000000000A6EE358
j> 23:42:04 R10=000000000A6EE8C0 R11=000000000000BAA0 R12=000000000A6EE358 R13=000000000A6EE340
j> 23:42:04 R14=00000000008D0190 R15=0000000016C40188
j> 23:42:04 RIP=00007FF8EB6EAAFF RSP=000000000A6EE290 RBP=0000000000000000 GS=002B
j> 23:42:04 FS=0053 ES=002B DS=002B
j> 23:42:04 XMM0 43e0000000000000 (f: 0.000000, d: 9.223372e+018)
j> 23:42:04 XMM1 bf50486695138968 (f: 2501085440.000000, d: -9.938242e-004)
j> 23:42:04 XMM2 3f504d012e159826 (f: 773167168.000000, d: 9.949218e-004)
j> 23:42:04 XMM3 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-001)
j> 23:42:04 XMM4 402a56ef6a000000 (f: 1778384896.000000, d: 1.316980e+001)
j> 23:42:04 XMM5 3f504cffb9ad0b58 (f: 3115125504.000000, d: 9.949205e-004)
j> 23:42:04 XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+000)
j> 23:42:04 Module=W:\builds\bld_432144\sdk\wa6480\jre\bin\default\j9gc29.dll
j> 23:42:04 Module_base_address=00007FF8EB530000 Offset_in_DLL=00000000001baaff
j> 23:42:04 Target=2_90_20191106_432144 (Windows 10 10.0 build 14393)
j> 23:42:04 CPU=amd64 (6 logical CPUs) (0x1fff8d000 RAM)
j> 23:42:04 ----------- Stack Backtrace -----------
j> 23:42:06 GC_ObjectModelDelegate::calculateObjectDetailsForCopy+0x2f (objectmodeldelegate.cpp:62, 0x00007FF8EB6EAAFF [j9gc29+0x1baaff])
j> 23:42:06 MM_Scavenger::copyAndForwardThreadSlot+0x1d8 (scavenger.cpp:2810, 0x00007FF8EB688638 [j9gc29+0x158638])
j> 23:42:06 MM_ScavengerRootScanner::doStackSlot+0x13a (scavengerrootscanner.hpp:105, 0x00007FF8EB68B17A [j9gc29+0x15b17a])
j> 23:42:06 vmThreadStackDoOSlotIterator+0x2a (vmthreadstackslotiterator.cpp:54, 0x00007FF8EB54584A [j9gc29+0x1584a])
j> 23:42:06 walkJITFrameSlotsForInternalPointers+0xe2 (methodmetadata.c:1355, 0x00007FF8E90B4752 [j9jit29+0x154752])
j> 23:42:06 jitWalkFrame+0x442 (jswalk.c:578, 0x00007FF8E95C75F2 [j9jit29+0x6675f2])
j> 23:42:06 jitWalkStackFrames+0x285 (jswalk.c:249, 0x00007FF8E95C7E85 [j9jit29+0x667e85])
j> 23:42:06 walkStackFrames+0x297 (swalk.c:335, 0x00007FF8EB8EA8E7 [j9vm29+0xaa8e7])
j> 23:42:06 GC_VMThreadStackSlotIterator::scanSlots+0xa5 (vmthreadstackslotiterator.cpp:115, 0x00007FF8EB545925 [j9gc29+0x15925])
j> 23:42:06 MM_RootScanner::scanOneThread+0x10e (rootscanner.cpp:529, 0x00007FF8EB54365E [j9gc29+0x1365e])
j> 23:42:06 MM_RootScanner::scanThreads+0xb3 (rootscanner.cpp:496, 0x00007FF8EB5433B3 [j9gc29+0x133b3])
j> 23:42:06 MM_RootScanner::scanRoots+0x7e (rootscanner.cpp:929, 0x00007FF8EB54451E [j9gc29+0x1451e])
j> 23:42:06 MM_Scavenger::workThreadGarbageCollect+0x1fb (scavenger.cpp:2207, 0x00007FF8EB68A6CB [j9gc29+0x15a6cb])
j> 23:42:06 MM_Dispatcher::run+0x62 (dispatcher.cpp:97, 0x00007FF8EB626A42 [j9gc29+0xf6a42])
j> 23:42:06 MM_Scavenger::scavenge+0xa0 (scavenger.cpp:483, 0x00007FF8EB662C40 [j9gc29+0x132c40])
j> 23:42:06 MM_Scavenger::masterThreadGarbageCollect+0x217 (scavenger.cpp:3842, 0x00007FF8EB66EF57 [j9gc29+0x13ef57])
j> 23:42:06 MM_Scavenger::internalGarbageCollect+0xec5 (scavenger.cpp:4378, 0x00007FF8EB670195 [j9gc29+0x140195])
j> 23:42:06 MM_Collector::garbageCollect+0x321 (collector.cpp:496, 0x00007FF8EB632231 [j9gc29+0x102231])
j> 23:42:06 MM_MemorySubSpaceSemiSpace::allocationRequestFailed+0x59c (memorysubspacesemispace.cpp:137, 0x00007FF8EB6D5FDC [j9gc29+0x1a5fdc])
j> 23:42:06 MM_MemorySubSpaceGeneric::allocateTLH+0x208 (memorysubspacegeneric.cpp:379, 0x00007FF8EB6D45D8 [j9gc29+0x1a45d8])
j> 23:42:06 MM_TLHAllocationSupport::refresh+0x36c (tlhallocationsupport.cpp:236, 0x00007FF8EB64701C [j9gc29+0x11701c])
j> 23:42:06 MM_TLHAllocationSupport::allocateFromTLH+0x10f (tlhallocationsupport.cpp:305, 0x00007FF8EB6471FF [j9gc29+0x1171ff])
j> 23:42:06 MM_TLHAllocationInterface::allocateObject+0x216 (tlhallocationinterface.cpp:191, 0x00007FF8EB642176 [j9gc29+0x112176])
j> 23:42:06 OMR_GC_AllocateObject+0x254 (omrgcalloc.cpp:39, 0x00007FF8EB65F624 [j9gc29+0x12f624])
j> 23:42:06 J9AllocateObject+0x2e9 (mgcalloc.cpp:380, 0x00007FF8EB550DE9 [j9gc29+0x20de9])
j> 23:42:06 old_slow_jitNewObject+0x270 (cnathelp.cpp:516, 0x00007FF8E95C9110 [j9jit29+0x669110])
j> 23:42:06 jitNewObject+0x88 (xnathelp.asm:225, 0x00007FF8E95B6BB8 [j9jit29+0x656bb8])
j> 23:42:06 ---------------------------------------
j> 23:42:06 JVMDUMP039I Processing dump event "gpf", detail "" at 2019/11/06 23:42:05 - please wait.
j> 23:42:06 JVMDUMP032I JVM requested System dump using 'C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\dumps\coredump-0002.dmp' in response to an event
j> 23:42:08 JVMDUMP010I System dump written to C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\dumps\coredump-0002.dmp
j> 23:42:08 JVMDUMP027W The requested heapdump has not been produced because another component is holding the VM exclusive lock.
j> 23:42:08 JVMDUMP032I JVM requested Java dump using 'C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\javacore.20191106.234205.9992.0004.txt' in response to an event
p> 20191106-23:42:08 Dump C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340/javacore.20191106.234205.9992.0004.txt spotted.
p> 20191106-23:42:11 Dump C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340/Snap.20191106.234205.9992.0005.trc spotted.
j> 23:42:11 JVMDUMP010I Java dump written to C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\javacore.20191106.234205.9992.0004.txt
j> 23:42:11 JVMDUMP032I JVM requested Snap dump using 'C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\Snap.20191106.234205.9992.0005.trc' in response to an event
j> 23:42:11 JVMDUMP010I Snap dump written to C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\Snap.20191106.234205.9992.0005.trc
j> 23:42:11 JVMDUMP007I JVM Requesting JIT dump using 'C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\jitdump.20191106.234205.9992.0006.dmp'
j> 23:42:11 JVMDUMP010I JIT dump written to C:\temp\bld_432144\trace.property.trigger.system_dump\620516786\WIN10X64VM6-trace-m112-20191106-234033\ptrig_coredump\JLTF-mauve-mode112-20191106-2340\jitdump.20191106.234205.9992.0006.dmp
j> 23:42:11 JVMDUMP013I Processed dump event "gpf", detail "".
p> 20191106-23:42:11 Java Process completed. Total java component duration 69 seconds. Leaving process polling loop
```

The result file is at /team/triage/issue7713.

**Comment by pshipton** [comment] 2019-11-07 15:23
@dmitripivkine another dup of https://github.com/eclipse/openj9/issues/7300 ?

**Comment by dmitripivkine** [comment] 2019-11-07 16:00
yes, this is a duplicate of #7300 

```
Checking THREAD STACKS...  <gc check (1): from debugger: THREAD STACKS: slot 79b1500(16c40188) -> 7ff5feecb2a8: corrupt data exception>

<79b1500> For pinning array U8(0x03) num internal pointer stack slots U8(0x00)
<79b1500> Before object slot walk &address : 0x0000000016C40188 address : 0x00007FF5FEECB2A8 bp 0x0000000016C401D8 offset of first internal ptr I16(0xFFA8)
<79b1500> After object slot walk for pinning array with &address : 0x0000000016C40188 old address 0x00007FF5FEECB2A8 new address 0x00007FF5FEECB2A8 displacement IDATA(0x0000000000000000)
```

**Closed by dmitripivkine** 2019-11-07 16:00 UTC
Labels: comp:gc, test failure
