### ISSUE TITLE
JTReg Test Failure: CompactStringBuffer.testCompactStringBufferForLatinA

### ISSUE THREAD

**Issue by adamfarley** [eclipse/openj9#6671] opened 2019-08-05 15:19 UTC
Failure link
------------

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/13/consoleText

Optional info
-------------

- intermittent failure: no
- regression or new test:  regression
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :
Unknown

Notes: Only seen on zLinux, and occurs on this line of the test, seemingly 100% of the time.
assertEquals(new StringBuffer(ORIGIN).indexOf("A", 0), 0);

Assumed to be an OpenJ9 issue as OpenJ9 implements its own StringBuilder class.

Failure output
--------------

[2019-07-31T22:54:36.169Z] test CompactStringBuffer.testCompactStringBufferForLatinA(): failure
[2019-07-31T22:54:36.169Z] java.lang.AssertionError: expected [0] but found [-1]
[2019-07-31T22:54:36.169Z] 	at org.testng.Assert.fail(Assert.java:94)
[2019-07-31T22:54:36.169Z] 	at org.testng.Assert.failNotEquals(Assert.java:496)
[2019-07-31T22:54:36.169Z] 	at org.testng.Assert.assertEquals(Assert.java:125)
[2019-07-31T22:54:36.169Z] 	at org.testng.Assert.assertEquals(Assert.java:372)
[2019-07-31T22:54:36.169Z] 	at org.testng.Assert.assertEquals(Assert.java:382)
[2019-07-31T22:54:36.169Z] 	at CompactStringBuffer.testCompactStringBufferForLatinA(CompactStringBuffer.java:62)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-07-31T22:54:36.169Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
[2019-07-31T22:54:36.169Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
[2019-07-31T22:54:36.169Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:773)
[2019-07-31T22:54:36.169Z] 	at org.testng.TestRunner.run(TestRunner.java:623)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
[2019-07-31T22:54:36.169Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
[2019-07-31T22:54:36.169Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
[2019-07-31T22:54:36.169Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
[2019-07-31T22:54:36.169Z] 	at org.testng.TestNG.run(TestNG.java:1018)
[2019-07-31T22:54:36.169Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
[2019-07-31T22:54:36.169Z] 	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2019-07-31T22:54:36.169Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2019-07-31T22:54:36.169Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2019-07-31T22:54:36.169Z] 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
[2019-07-31T22:54:36.169Z] 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by smlambert** [comment] 2019-08-06 16:31
Excluded via https://github.com/AdoptOpenJDK/openjdk-tests/pull/1248

**Comment by pshipton** [comment] 2019-08-20 13:52
@DanHeidinga @fjeremic fyi, regression indicated

**Comment by andrew-m-leonard** [comment] 2019-08-27 09:23
Affects StringBuilder as well: 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_s390x_linux/40/testReport/junit/java_lang_StringBuilder_CompactStringBuilder/java/CompactStringBuilder/
21:03:20  test CompactStringBuilder.testCompactStringBuilderForLatinA(): failure
21:03:20  java.lang.AssertionError: expected [0] but found [-1]
21:03:20  	at org.testng.Assert.fail(Assert.java:94)
21:03:20  	at org.testng.Assert.failNotEquals(Assert.java:496)
21:03:20  	at org.testng.Assert.assertEquals(Assert.java:125)
21:03:20  	at org.testng.Assert.assertEquals(Assert.java:372)
21:03:20  	at org.testng.Assert.assertEquals(Assert.java:382)
21:03:20  	at CompactStringBuilder.testCompactStringBuilderForLatinA(CompactStringBuilder.java:62)

**Comment by andrew-m-leonard** [comment] 2019-08-27 09:27
Exclude PR: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1300

**Comment by adamfarley** [comment] 2019-08-28 08:45
@fjeremic - Thanks for clarifying. Is there a way to determine which versions of Java a J9 jcl class applies to without reading the source code for that class? Reading j9 jcl classes is discouraged for OpenJDK jcl contributors due to the risk of contamination, you see.

**Comment by fjeremic** [comment] 2019-08-30 13:50
Just a short update:

I have a fix for this issue and I've written a semi-exhaustive set of tests to make sure it is caught much earlier in the development process. This is a JIT Z codegen bug. Unfortunately we're dealing with a miscellaneous hang issue in the Runtime Assumption Table (RAT) that is exposed via these tests. We cannot deliver the tests and the fix until this issue is resolved.

I'm going to give us a few more days to work on it before delivering the fix by itself and the tests as a follow-up.

**Comment by fjeremic** [comment] 2019-08-30 13:50
Also noteworthy that I've verified #6778 is a duplicate of this issue and will be fixed at the same time.

**Closed** 2019-09-30 14:49 UTC
Labels: arch:z, test excluded, test failure

**Comment by adamfarley** [comment] 2019-09-30 16:12
If this is now closed, the associated tests will now be unexcluded.
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1376
