### ISSUE TITLE
sanity.external: thorntail_microprofile_tck fails with openj9 jdk8

### ISSUE THREAD

**Issue by smlambert** [eclipse/openj9#6435] opened 2019-07-11 18:02 UTC
This microprofile tck is failing with jdk8 openj9 (and passes with hotspot).  

Note: While the output at the failure link contains a bunch of additional failures, those refer to failing to upload artifacts and are not relevant (as they also appear in the successful hotspot run).  Also see: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1161

Failure link
------------
https://ci.adoptopenjdk.net/view/Test_external/job/Test_openjdk8_j9_sanity.external_thorntail-mp-tck_x86-64_linux/99/

- test level: sanity
- test group (functionality, system, etc): external
- test target name:  thorntail_microprofile_tck
- OS/architecture: x86-64_linux
- OpenJDK version: jdk8u222-b08
- java -version output: 
openjdk version "1.8.0_222"
 OpenJDK Runtime Environment (build 1.8.0_222-201907110356-b08)
Eclipse OpenJ9 VM (build master-dbc3c1755, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190711_364 (JIT enabled, AOT enabled)
OpenJ9   - dbc3c1755
OMR      - 4c15abd8
JCL      - cf4961987f based on jdk8u222-b08)

Optional info
-------------
- intermittent failure: no
- regression: no

Failure output
--------------
06:10:14  [INFO] Results:
06:10:14  [INFO] 
06:10:14  [ERROR] Failures: 
06:10:14  [ERROR]   DelegateHealthSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment ...
06:10:14  [ERROR]   EnforceQualifierTest>Arquillian.arquillianBeforeClass:96 » Deployment Found 1 ...
06:10:14  [ERROR]   HealthCheckResponseAttributesTest>Arquillian.arquillianBeforeClass:96 » Deployment
06:10:14  [ERROR]   MultipleLivenessFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment Fo...
06:10:14  [ERROR]   MultipleProceduresFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment ...
06:10:14  [ERROR]   MultipleReadinessFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment F...
06:10:14  [ERROR]   NoProcedureSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment Fou...
06:10:14  [ERROR]   OnlySuccessfulProcedureTest>Arquillian.arquillianBeforeClass:96 » Deployment F...
06:10:14  [ERROR]   SingleHealthFailedTest>Arquillian.arquillianBeforeClass:96 » Deployment Found ...
06:10:14  [ERROR]   SingleHealthSuccessfulTest>Arquillian.arquillianBeforeClass:96 » Deployment Fo...
06:10:14  [INFO] 
06:10:14  [ERROR] Tests run: 32, Failures: 10, Errors: 0, Skipped: 22
06:10:14  [INFO] 
06:10:14  [INFO] ------------------------------------------------------------------------
06:10:14  [INFO] Reactor Summary for MicroProfile TCK: Parent 2.4.1.Final-SNAPSHOT:
06:10:14  [INFO] 
06:10:14  [INFO] MicroProfile TCK: Parent ........................... SUCCESS [  7.520 s]
06:10:14  [INFO] MicroProfile TCK: Health ........................... FAILURE [ 25.715 s]
06:10:14  [INFO] MicroProfile TCK: Config ........................... SKIPPED
06:10:14  [INFO] MicroProfile TCK: JWT .............................. SKIPPED
06:10:14  [INFO] MicroProfile TCK: Metrics .......................... SKIPPED
06:10:14  [INFO] MicroProfile TCK: Fault Tolerance .................. SKIPPED
06:10:14  [INFO] MicroProfile TCK: RestClient ....................... SKIPPED
06:10:14  [INFO] MicroProfile TCK: OpenAPI .......................... SKIPPED
06:10:14  [INFO] MicroProfile TCK: OpenTracing ...................... SKIPPED
06:10:14  [INFO] ------------------------------------------------------------------------
06:10:14  [INFO] BUILD FAILURE
06:10:14  [INFO] ------------------------------------------------------------------------
06:10:14  [INFO] Total time:  56.203 s
06:10:14  [INFO] Finished at: 2019-07-11T04:10:13Z
06:10:14  [INFO] ------------------------------------------------------------------------

**Comment by pshipton** [comment] 2019-09-27 22:29
I don't see anybody working on this, moving to the next release.

**Comment by DanHeidinga** [comment] 2019-10-17 14:17
@ChengJin01 Can you take a look at this?  I'd like to see all `AQA`-related tests passing for the 0.18.0 release and that requires someone to dig to the bottom of this.

I'd start by confirming the test still fails with the most recent OpenJ9 builds as it may have been resolved in the mean time?

**Comment by ChengJin01** [comment] 2019-10-17 14:51
Will investigate to see what happened there.

**Comment by ChengJin01** [comment] 2019-10-17 17:40
The failure in `MicroProfile TCK: Health` was caused by the error in downloading the pom.xml from `https://repo.gradle.org/gradle/libs-releases-local/`
```
...
02:48:11  WARNING: Failed downloading io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom 
from https://repo.gradle.org/gradle/libs-releases-local/. Reason: 
02:48:17  1/ [ERROR] Non-resolvable import POM: 
Failed to resolve POM for io.thorntail:bom:2.5.1.Final-SNAPSHOT 
due to Could not transfer artifact io.thorntail:bom:pom:2.5.1.Final-SNAPSHOT 
from/to gradle  (https://repo.gradle.org/gradle/libs-releases-local): 
Error transferring file: Server returned HTTP response code: 
409 for URL: https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom
from https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom 
@ io.thorntail.testsuite:thorntail-microprofile-tck-health:2.5.1.Final-SNAPSHOT, /thorntail/testsuite/microprofile-tcks/health/pom.xml
02:48:17  
02:48:17  	at org.wildfly.swarm.arquillian.adapter.WildFlySwarmContainer.deploy(WildFlySwarmContainer.java:95)
02:48:17  	at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
```
To be specific, it failed to download `https://repo.gradle.org/gradle/libs-releases-local/io/thorntail/bom/2.5.1.Final-SNAPSHOT/bom-2.5.1.Final-SNAPSHOT.pom` from `https://repo.gradle.org/gradle/libs-releases-local`

Looking at the link at `https://repo.gradle.org/gradle/libs-releases-local`
```
Index of libs-releases-local/

Name  Last modified      Size

org/   14-Apr-2013 08:38    - <--- the "io" dir doesn't exist

Artifactory Online Server at repo.gradle.org Port 443
```

As explained previously by @sophia-guo  at https://github.com/AdoptOpenJDK/openjdk-tests/issues/1161
```
Actually openj9 has never been passed the test. 
Thorntail-mp-tck test build has been updated to run tests taken 
from the MicroProfile TCKs instead of any other MicroProfile test. #1117 
The passing build https://ci.adoptopenjdk.net/job
/openjdk8_j9_external_sanity_thorntail-mp-tck_x86-64_linux/40 
was running the original Thorntail's own Mircorprofile tests.
```

So the problem has nothing to with OpenJ9 but a configure/setting related issue with Gradle or thorntail at
https://github.com/thorntail/thorntail/blob/master/testsuite/microprofile-tcks/health/pom.xml
```
<artifactId>thorntail-microprofile-tck-health</artifactId>
   <name>MicroProfile TCK: Health</name>

   <dependencies>

      <dependency>
         <groupId>org.eclipse.microprofile.health</groupId>
         <artifactId>microprofile-health-tck</artifactId>
      </dependency>
...
     <dependency>
         <groupId>io.thorntail</groupId> <------------------
         <artifactId>microprofile-health</artifactId>
      </dependency>
```

**Comment by ChengJin01** [comment] 2019-10-17 17:44
In addition, @sophia-guo already verified on hotspot previously at https://github.com/AdoptOpenJDK/openjdk-tests/issues/1161#issuecomment-498686604 and ended up with the same downloading failure.

**Comment by ChengJin01** [comment] 2019-10-17 17:45
duplicate issue was opened at https://github.com/AdoptOpenJDK/openjdk-tests/issues/1386

**Comment by DanHeidinga** [comment] 2019-10-17 17:50
Thanks @ChengJin01.  

Closing this as it's tracked upstream at Adopt and doesn't indicate an issue in OpenJ9

**Closed by DanHeidinga** 2019-10-17 17:50 UTC
Labels: AQA, arch:x86, test failure
