### ISSUE TITLE
GPF when lombok is used

### ISSUE THREAD

**Issue by sudhirtumati** [eclipse/openj9#6933] opened 2019-08-31 14:46 UTC
Java -version output
--------------------

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Windows 10 amd64-64-Bit Compressed References 20190718_139 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 06c2cc3322 based on jdk-12.0.2+10)

Summary of problem
------------------

Not able to compile code when lombok annotations are present

Diagnostic files
----------------
[diagnostic-files.zip](https://github.com/eclipse/openj9/files/3562548/diagnostic-files.zip)
[Core dump](https://drive.google.com/open?id=12UF7_czJIIAt2W5GXGPfz-hM9j6FHLLn)

**Comment by GaborSzabo7** [comment] 2019-10-09 21:11
Hi @sudhirtumati 

I found a similiar issue. Is it completely same or should I open a new bug?
https://stackoverflow.com/questions/58274481/maven-compile-failure-using-openj9-with-lombok

**Comment by DanHeidinga** [comment] 2019-10-10 03:08
FYI @andrewcraik - can you get someone to take a look at this?  The StackOverflow link is a crash in the jit dll on v0.16.0 and has a test case to reproduce it.

**Comment by andrewcraik** [comment] 2019-12-12 21:27
@liqunl can you take a look at this failure?

**Comment by liqunl** [comment] 2019-12-12 22:48
@sudhirtumati @GaborSzabo7 Could you kindly provide instructions on how to set up the machine to run the test and reproduce the issue?

**Comment by GaborSzabo7** [comment] 2019-12-13 14:33
@liqunl I installed Eclipse OpenJ9 VM AdoptOpenJDK in my machine and after that I created a very simple Spring Boot application. If you installed Eclipse OpenJ9 VM AdoptOpenJDK then I can give simple Spring Boot application to reproduce the issue.

**Comment by liqunl** [comment] 2019-12-17 19:08
The problem is that an reference field contains a bad value
```
> !j9object 0x00000007FFA0B290
!J9Object 0x00000007FFA0B290 {
        struct J9Class* clazz = !j9class 0x1DBB600 // java/lang/reflect/Field
        Object flags = 0x00000000;
        I lockword = 0x00000000 (offset = 0) (java/lang/Object) <hidden>
        Z override = 0x00000000 (offset = 8) (java/lang/reflect/AccessibleObject)
        Ljava/lang/Object; accessCheckCache = !fj9object 0x1 (offset = 4) (java/lang/reflect/AccessibleObject)
```
`accessCheckCache` has value `1`. The only place that sets the value for this field is `AccessibleObject.slowVerifyAccess`.

I ran the test with `-Xint`, the crash occurs in libj9vm29.so. From the core dump I found an object with the same problem. FYI @DanHeidinga

**Comment by DanHeidinga** [comment] 2019-12-17 19:21
@liqunl Can you dump the core file on the internal network at /team/triage/6933?  It'll help speed the investigation if we can start from your setup

**Comment by liqunl** [comment] 2019-12-17 19:40
@DanHeidinga I don't have permission to create a folder at `/team/triage`, please find the core dump at `/team/triage/liqunl/openj9-6933`

**Comment by andrewcraik** [comment] 2020-01-09 22:31
@DanHeidinga this seems to be one you were looking at / having someone how works on the VM take a look at - do you know what the status is given this is tagged for 0.18? Do you need anything else from the JIT side?

**Comment by pshipton** [comment] 2020-01-10 20:14
The investigation on this hasn't completed and it's getting to be too late to add more fixes, moving out to the next release.

**Comment by pshipton** [comment] 2020-02-24 16:23
@DanHeidinga is there somebody who can take a look at this one?

**Comment by DanHeidinga** [comment] 2020-02-24 19:52
@fengxue-IS Can you take a look at this?

**Comment by fengxue-IS** [comment] 2020-02-24 19:57
looking into this

**Comment by pshipton** [comment] 2020-03-04 16:26
Moving forward since I don't see any fix in hand and it's becoming too late to update the 0.19 release. Note the branch for the 0.20 release occurs on March 8.

**Comment by pshipton** [comment] 2020-03-18 21:03
@fengxue-IS any updates on this?

**Comment by pshipton** [comment] 2020-03-30 15:11
We're past Milestone 2 for the 0.20.0 release, moving this forward to the next release.

**Comment by babsingh** [comment] 2020-04-16 20:45
You can easily reproduce the issue through `javac`; instead of the above maven application. I derived the below steps by running the maven application in debug mode (`-X`).

### Easy steps
1. Get https://projectlombok.org/downloads/lombok.jar
2. Create `HelloWorld.java`
```
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, Lombak");
    }
}
```
3. Get [OpenJ9 JDK14 from AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14%2B36.1_openj9-0.19.0/OpenJDK14U-jdk_x64_linux_openj9_14_36_openj9-0.19.0.tar.gz)
4. `javac -cp lombok-1.18.12.jar HelloWorld.java` should reproduce the reported failure

### Failure and Debug Details

1. The `SIGSEGV` happens because https://projectlombok.org/ (https://github.com/rzwitserloot/lombok) installs a custom annotation processor, `Processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor`
2. Get debug info during `javac` with `-verbose`: `javac -cp lombok-1.18.12.jar -verbose HelloWorld.java`
3. Another note ... the failure does not happen with OpenJ9 JDK8 ... it only happens with OpenJ9 JDK13 and JDK 14. 

### Potential Temporary Fix

Disabling annotation processors with `-proc:none` resolves the `javac` failure. But, this may also disable Lombok features.

### [BAD] JDK14 failure happens in Round 1 of annotation processing (`javac -verbose`)

```
Round 1:
	input files: {HelloWorld}
	annotations: []
	last round: false
Unhandled exception
Type=Segmentation error vmState=0x00000000
```

### [GOOD] JDK8 behavior (`javac -verbose`)

```
Round 1:
	input files: {HelloWorld}
	annotations: []
	last round: false
Processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor matches [] and returns false.
[loading ZipFileIndexFileObject[/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-slowdebug/images/j2sdk-image/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Object.class)]]
[loading ZipFileIndexFileObject[/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-slowdebug/images/j2sdk-image/lib/ct.sym(META-INF/sym/rt.jar/java/lang/String.class)]]
Round 2:
	input files: {}
	annotations: []
	last round: false
Processor lombok.launch.AnnotationProcessorHider$AnnotationProcessor matches [] and returns false.
[loading ZipFileIndexFileObject[/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-slowdebug/images/j2sdk-image/lib/ct.sym(META-INF/sym/rt.jar/java/lang/Object.class)]]
[loading ZipFileIndexFileObject[/root/openj9-openjdk-jdk8/build/linux-x86_64-normal-server-slowdebug/images/j2sdk-image/lib/ct.sym(META-INF/sym/rt.jar/java/lang/String.class)]]
Round 3:
```

fyi @fengxue-IS

**Comment by DanHeidinga** [comment] 2020-04-22 04:47
@fengxue-IS are you able to modify the Lombok jar?  It may be sufficient to recompile `lombok.launch.AnnotationProcessor.java` with the lombak jar on the javac classpath.

If you can, try modifying this method to make it a no-op and confirm the issue still occurs:
https://github.com/rzwitserloot/lombok/blob/20cce2049de56d5a71c6dcc376d6f4088d4552bc/src/launch/lombok/launch/AnnotationProcessor.java#L83

If it doesn't, then it would be good to log the values used in the Unsafe call to see if they make sense or if anything is wrong in the data being used.

**Comment by fengxue-IS** [comment] 2020-04-22 15:58
I traced the source of this issue to https://github.com/rzwitserloot/lombok/blob/master/src/utils/lombok/permit/Permit.java#L68

Where call to `setAccessible()` run the code:
`UNSAFE.putBoolean(accessor, ACCESSIBLE_OVERRIDE_FIELD_OFFSET, true);`

The problem with this is that the `ACCESSIBLE_OVERRIDE_FIELD_OFFSET` is suppose to represent the field offset of `override` variable, which is not accessible starting from Java 12

lombok used a hacky way which is to use Fake.class to guess the actual class shape.
```
static class Fake {
	boolean override;
}

// The below seems very risky, but for all AccessibleObjects in java today it does work, and starting with JDK12, making the field accessible is no longer possible.
try {
	return UNSAFE.objectFieldOffset(Fake.class.getDeclaredField("override"));
} catch (Throwable t) {
	throw saved;
}
```

The produced offset so happens that it maps to `accessCheckCache` field in OpenJ9.

**Comment by DanHeidinga** [comment] 2020-04-22 18:38
@fengxue-IS if you update the Fake class to be:
```java
static class Fake {
	boolean override;
	Object accessCheckCache;
}
```
does the problem go away?  I suspect it will as it appears to be caused by the difference in how JDKs lay out fields.  

If that resolves the issue, then we should get a PR opened at Lombok with this fix.  There was a recent article indicating Hotspot is changing their field layout algorithms as well so having the object field may be safer even on newer Hotspots

**Comment by fengxue-IS** [comment] 2020-04-22 20:56
@DanHeidinga I've recompiled lombok.jar with the changes you suggested and the javac test passed successfully with updated jar. I will open a PR against the lombok project with this fix.

**Comment by fengxue-IS** [comment] 2020-04-22 22:48
Created PR against Lombok https://github.com/rzwitserloot/lombok/pull/2437

**Comment by DanHeidinga** [comment] 2020-04-23 13:50
Thanks @fengxue-IS. And also thanks to @sudhirtumati, @GaborSzabo7, ghunteranderson & @babsingh for reporting this and helping to track it down.

 I'm going to close this as this Jack has opened a PR to address this in Lombok.

**Closed by DanHeidinga** 2020-04-23 13:50 UTC
Labels: arch:x86, comp:vm, os:windows, segfault, userRaised
