### ISSUE TITLE
JDK11 JIT Server : jdk_lang_j9_0 various Segmentation error

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9169] opened 2020-04-07 22:40 UTC
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/41`:
```
3:04:08  openjdk version "11.0.7-internal" 2020-04-14
23:04:08  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
23:04:08  Eclipse OpenJ9 VM (build ibm_sdk-934063f45c, JRE 11 Linux amd64-64-Bit Compressed References 20200406_42 (JIT enabled, AOT enabled)
23:04:08  OpenJ9   - 934063f45c
23:04:08  OMR      - b7eb64f76
23:04:08  JCL      - ea4a5a16094 based on jdk-11.0.7+9)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:06:41  ===============================================
23:06:41  Running test jdk_lang_j9_0 ...
23:06:41  ===============================================

23:19:48  Unhandled exception
23:19:48  Type=Segmentation error vmState=0x0005ff03
23:19:48  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000002
23:19:48  Handler1=00007F0E6D8B62A0 Handler2=00007F0E6D1A79F0 InaccessibleAddress=00007F0E6C0C4333
23:19:48  RDI=00007F0DA4DFA000 RSI=00007F0DA509A000 RAX=00007F0E6C0C4320 RBX=00007F0DA509A000
23:19:48  RCX=00000000FFFFFE41 RDX=0000000000000080 R8=00007F0E6BBE9E6C R9=00007F0E6BBE2903
23:19:48  R10=0000000000000043 R11=0000000000000003 R12=00007F0DA4DFF8C0 R13=FFFFFFFFFFFFFFFF
23:19:48  R14=00007F0E6BBE2903 R15=0000000000000000
23:19:48  RIP=00007F0E6B6E13B4 GS=0000 FS=0000 RSP=00007F0E5181B280
23:19:48  EFlags=0000000000010202 CS=0033 RBP=0000000000000F6C ERR=0000000000000004
23:19:48  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007F0E6C0C4333
23:19:48  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm2 6161616161616161 (f: 1633771904.000000, d: 1.221764e+161)
23:19:48  xmm3 00000000ff000000 (f: 4278190080.000000, d: 2.113707e-314)
23:19:48  xmm4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm5 ffff0000000000ff (f: 255.000000, d: -nan)
23:19:48  xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm8 00000000ff000000 (f: 4278190080.000000, d: 2.113707e-314)
23:19:48  xmm9 0e0915042c4e040a (f: 743310336.000000, d: 4.701942e-241)
23:19:48  xmm10 0d4e0017000b2d48 (f: 732488.000000, d: 1.373030e-244)
23:19:48  xmm11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
23:19:48  Module_base_address=00007F0E6B211000
23:19:48  
23:19:48  Unhandled exception in signal handler. Protected function: writeCrashDataToConsole (0x0)
23:19:48  
23:19:48  ----------- Stack Backtrace -----------
23:19:48  (0x00007F0E6B6E13B4 [libj9jit29.so+0x4d03b4])
23:19:48  (0x00007F0E6B6E140E [libj9jit29.so+0x4d040e])
23:19:48  (0x00007F0E6B6E140E [libj9jit29.so+0x4d040e])
23:19:48  (0x00007F0E6B31617C [libj9jit29.so+0x10517c])
23:19:48  (0x00007F0E6B6DB2BE [libj9jit29.so+0x4ca2be])
23:19:48  (0x00007F0E6B6D98C2 [libj9jit29.so+0x4c88c2])
23:19:48  (0x00007F0E6B6D6F03 [libj9jit29.so+0x4c5f03])
23:19:48  (0x00007F0E6B6EC761 [libj9jit29.so+0x4db761])
23:19:48  (0x00007F0E6B361217 [libj9jit29.so+0x150217])
23:19:48  (0x00007F0E6B362161 [libj9jit29.so+0x151161])
23:19:48  (0x00007F0E6D1A8753 [libj9prt29.so+0x1b753])
23:19:48  (0x00007F0E6B363E55 [libj9jit29.so+0x152e55])
23:19:48  (0x00007F0E6B4E3495 [libj9jit29.so+0x2d2495])
23:19:48  (0x00007F0E6B35FDEB [libj9jit29.so+0x14edeb])
23:19:48  (0x00007F0E6B3602E2 [libj9jit29.so+0x14f2e2])
23:19:48  (0x00007F0E6B36038A [libj9jit29.so+0x14f38a])
23:19:48  (0x00007F0E6D1A8753 [libj9prt29.so+0x1b753])
23:19:48  (0x00007F0E6B3607E4 [libj9jit29.so+0x14f7e4])
23:19:48  (0x00007F0E6D616326 [libj9thr29.so+0xe326])
23:19:48  (0x00007F0E6E5C76BA [libpthread.so.0+0x76ba])
23:19:48  clone+0x6d (0x00007F0E6E2FD41D [libc.so.6+0x10741d])
23:19:48  ---------------------------------------

23:19:48  Unhandled exception
23:19:48  Type=Segmentation error vmState=0x000500af
23:19:48  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
23:19:48  Handler1=00007F0E6D8B62A0 Handler2=00007F0E6D1A79F0 InaccessibleAddress=00007FEDAFF8C7A0
23:19:48  RDI=00007FEDAFF8C760 RSI=00007F0DD03FA250 RAX=00007FEDAFF8C760 RBX=00007FEDAFF8C760
23:19:48  RCX=0000000000000000 RDX=00007FEDAFF8C761 R8=00007F0E6BBE4B07 R9=00007F0E6BC1CE60
23:19:48  R10=00007F0D7EE9B0F0 R11=0000000000000010 R12=00007F0D7EDFA000 R13=00007F0DD03FA248
23:19:48  R14=00007F0D7EE5E7A0 R15=00007F0D7EE85170
23:19:48  RIP=00007F0E6B475CB4 GS=0000 FS=0000 RSP=00007F0E516171B0
23:19:48  EFlags=0000000000010202 CS=0033 RBP=00007F0DD03FA250 ERR=0000000000000004
23:19:48  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007FEDAFF8C7A0
23:19:48  xmm0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:19:48  xmm2 00007f0d7ee8ffa0 (f: 2129198976.000000, d: 6.901897e-310)
23:19:48  xmm3 00007f0d7ee900e0 (f: 2129199360.000000, d: 6.901897e-310)
23:19:48  xmm4 00007f0d7ee8fc80 (f: 2129198208.000000, d: 6.901897e-310)
23:19:48  xmm5 00007f0d7ee90180 (f: 2129199488.000000, d: 6.901897e-310)
23:19:48  xmm6 00007f0d7ee90220 (f: 2129199616.000000, d: 6.901897e-310)
23:19:48  xmm7 00007f0d7ee902c0 (f: 2129199872.000000, d: 6.901897e-310)
23:19:48  xmm8 00007f0d7ee90360 (f: 2129200000.000000, d: 6.901897e-310)
23:19:48  xmm9 00007f0d7ee90400 (f: 2129200128.000000, d: 6.901897e-310)
23:19:48  xmm10 00007f0d7ee904a0 (f: 2129200256.000000, d: 6.901897e-310)
23:19:48  xmm11 00007f0d7ee90540 (f: 2129200384.000000, d: 6.901897e-310)
23:19:48  xmm12 00007f0d7ee905e0 (f: 2129200640.000000, d: 6.901897e-310)
23:19:48  xmm13 00007f0d7ee8ffa0 (f: 2129198976.000000, d: 6.901897e-310)
23:19:48  xmm14 00007f0d7ee90040 (f: 2129199104.000000, d: 6.901897e-310)
23:19:48  xmm15 00007f0d7ee900e0 (f: 2129199360.000000, d: 6.901897e-310)
23:19:48  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
23:19:48  Module_base_address=00007F0E6B211000
23:19:48  
23:19:48  Unhandled exception in signal handler. Protected function: writeCrashDataToConsole (0x0)

23:20:49  Unhandled exception
23:20:49  Type=Segmentation error vmState=0x0005ffff
23:20:49  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
23:20:49  Handler1=00007FDAE470B2A0 Handler2=00007FDADFDA59F0 InaccessibleAddress=00007F0DB4E01680
23:20:49  RDI=00007F0DB4E01640 RSI=0000000000000002 RAX=00007F0DB4E01640 RBX=00007F0DB4E01640
23:20:49  RCX=00007F0DB4E01680 RDX=0000000000000001 R8=0000000000000000 R9=0000000000000000
23:20:49  R10=0000000000000009 R11=00007FDADE77798F R12=00007FDAC4B7AA68 R13=00007FDADE77798F
23:20:49  R14=00007FDAD4C914A0 R15=00007FDADE77917B
23:20:49  RIP=00007FDADE073D40 GS=0000 FS=0000 RSP=00007FDAC4B7A280
23:20:49  EFlags=0000000000010206 CS=0033 RBP=00007FDA5E009CD0 ERR=0000000000000004
23:20:49  TRAPNO=000000000000000E OLDMASK=0000000000000000 CR2=00007F0DB4E01680
23:20:49  xmm0 0000003500000035 (f: 53.000000, d: 1.124658e-312)
23:20:49  xmm1 2525252525252525 (f: 623191360.000000, d: 9.532824e-130)
23:20:49  xmm2 0bb8000000000000 (f: 0.000000, d: 3.273519e-252)
23:20:49  xmm3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:20:49  xmm4 00000000000000ff (f: 255.000000, d: 1.259867e-321)
23:20:49  xmm5 0000000000cb7b18 (f: 13335320.000000, d: 6.588523e-317)
23:20:49  xmm6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:20:49  xmm7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:20:49  xmm8 00007f0db89f8208 (f: 3097461248.000000, d: 6.901944e-310)
23:20:49  xmm9 ffffffffffffffff (f: 4294967296.000000, d: -nan)
23:20:49  xmm10 0000000304004059 (f: 67125336.000000, d: 6.399152e-314)
23:20:49  xmm11 000000003f000000 (f: 1056964608.000000, d: 5.222099e-315)
23:20:49  xmm12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:20:49  xmm13 0000000400810000 (f: 8454144.000000, d: 8.492160e-314)
23:20:49  xmm14 000003da00000001 (f: 1.000000, d: 2.092288e-311)
23:20:49  xmm15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
23:20:49  Module=/home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9jit29.so
23:20:49  Module_base_address=00007FDADDE0F000
23:20:49  
23:20:49  Method_being_compiled=java/util/HashMap.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object;
23:20:49  Target=2_90_20200406_42 (Linux 4.4.0-174-generic)
23:20:49  CPU=amd64 (4 logical CPUs) (0xf6f3a000 RAM)
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_linux&TARGET=jdk_lang_j9_0

**Comment by pshipton** [comment] 2020-04-08 00:00
@mpirvu

**Comment by harryyu1994** [comment] 2020-04-16 18:45
Looking into this one.

**Comment by harryyu1994** [comment] 2020-04-16 18:47
Grinder 3x launched: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7128/

**Comment by dmitry-ten** [comment] 2020-04-17 21:21
Oh, I should've mentioned that I'm also working on this issue in #9023, sorry.
Some of the segfaults in this test are caused by JitProfiler enabled in remote compilations,
and some seem to be GC related.

**Comment by dmitry-ten** [comment] 2020-04-17 21:26
Although I'm testing with JDK8, not 11, but it's probably the same crash.

**Comment by harryyu1994** [comment] 2020-04-18 01:13
No worries, thanks for letting me know

**Comment by a7ehuo** [comment] 2020-04-23 14:50
I was just trying to verify if some of the JITServer issues might be fixed by the recent JITServer changes. This test still failed with JITServer (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7193/). However it also failed with non-JITServer, very intermittently, FR 1/20 (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7207/)

**Comment by dmitripivkine** [comment] 2020-04-23 16:09
> However it also failed with non-JITServer, very intermittently, FR 1/20 (https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7207/)

Crashed vmState 0x8000C is J9VMSTATE_ATTACHEDDATA_UPDATE

**Comment by a7ehuo** [comment] 2020-05-05 20:34
With the latest code, `jdk_lang_j9_0` still fails with JITServer in the nightly build `Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/68` [1]. But this time, it looks like related to the test itself. What happened here is that `InheritIO.sh` expects `stderr.txt` to contain only `'exit value: 0'` [2]. However with JITServer, `stderr.txt` now contains two lines now:
```
JITServer is currently a technology preview. Its use is not yet supported
exit value: 0
```

[1]
```
21:47:31  --------------------------------------------------
21:47:31  TEST: java/lang/ProcessBuilder/InheritIO/InheritIO.sh
21:47:31  TEST JDK: /home/jenkins/workspace/Test_openjdk11_j9_sanity.openjdk_x86-64_linux_jit_Nightly/openjdkbinary/j2sdk-image
21:47:31  
21:47:31  ACTION: shell -- Failed. Execution failed: exit code 1
21:47:31  REASON: User specified action: run shell InheritIO.sh 
21:47:31  TIME:   2.044 seconds
21:47:31  messages:
21:47:31  command: shell InheritIO.sh
21:47:31  reason: User specified action: run shell InheritIO.sh 
21:47:31  elapsed time (seconds): 2.044
21:47:31  STDOUT:
21:47:31  FAIL: unexpected 'JITServer is currently a technology preview. Its use is not yet supported
21:47:31  exit value: 0' in stderr
```

[2]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/302b1b522afcd0857c82ef9cdb070719d69ad2d4/test/jdk/java/lang/ProcessBuilder/InheritIO/InheritIO.sh#L76-L81

```bash
    ERR_EXPECTED='exit value: 0'
    ERR_RECEIVED=`cat stderr.txt`
    if [ "x${ERR_RECEIVED}" != "x${ERR_EXPECTED}" ]; then
        echo "FAIL: unexpected '${ERR_RECEIVED}' in stderr"
        exit 1
    fi
```

**Comment by dmitry-ten** [comment] 2020-08-24 18:20
50 [runs](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/9805/), 0 failures.
@mpirvu  this issue can be closed. All the above commits seem to have fixed it.

**Comment by mpirvu** [comment] 2020-08-24 19:32
Closing based on the above comment

**Closed by mpirvu** 2020-08-24 19:32 UTC
Labels: comp:jitserver, segfault, test failure
