### ISSUE TITLE
JDK13: java/util/concurrent/tck/JSR166TestCase.java.JSR166TestCase fails on pLinux

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#7011] opened 2019-09-09 14:11 UTC
This looks like a JIT bug, as if I run the test grinder with "-Xint" the test passes.

Failure link
------------
Failing grinder job:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/407/console

- openjdk
- jdk_custom
- java/util/concurrent/tck/JSR166TestCase.java
- openjdk_ppc64le_linux only
- public build SHAs (i.e. java -version output), in Grinder provides JDK_VERSION/JDK_IMPL info and helps identify point at which regression introduced: 

14:58:40  openjdk version "13" 2019-09-17
14:58:40  OpenJDK Runtime Environment AdoptOpenJDK (build 13+33-201909070410)
14:58:40  Eclipse OpenJ9 VM AdoptOpenJDK (build master-92ad03eb7, JRE 13 Linux ppc64le-64-Bit Compressed References 20190907_67 (JIT enabled, AOT enabled)
14:58:40  OpenJ9   - 92ad03eb7
14:58:40  OMR      - 7e9584ea
14:58:40  JCL      - 9beb413b36 based on jdk-13+33)

Failure output (captured from console output)
---------------------------------------------
13:48:22  JavaTest Message: JUnit Failure: testAccumulateAndGetMT(DoubleAccumulatorTest): expected:<1.999998E12> but was:<1.999997979144E12>
13:48:22  junit.framework.AssertionFailedError: expected:<1.999998E12> but was:<1.999997979144E12>
13:48:22  	at junit.framework.Assert.fail(Assert.java:50)
13:48:22  	at junit.framework.Assert.failNotEquals(Assert.java:287)
13:48:22  	at junit.framework.Assert.assertEquals(Assert.java:67)
13:48:22  	at junit.framework.Assert.assertEquals(Assert.java:74)
13:48:22  	at DoubleAccumulatorTest.testAccumulateAndGetMT(DoubleAccumulatorTest.java:175)

```
16:01:07  To rebuild the failed test in a jenkins job, copy the following link and fill out the <Jenkins URL> and <FAILED test target>:
16:01:07  <Jenkins URL>/parambuild/?JDK_VERSION=13&JDK_IMPL=openj9&BUILD_LIST=openjdk&Jenkinsfile=openjdk_ppc64le_linux&CUSTOM_TARGET=java/util/concurrent/tck/JSR166TestCase.java&TARGET=<FAILED test target>
```

**Comment by andrew-m-leonard** [comment] 2019-09-09 14:12
Note, this failure has only just been found as the testcase JSR166TestCase was un-excluded a few days ago...

**Comment by pshipton** [comment] 2019-09-09 22:25
@gita-omr @zl-wang can someone please take a look.

**Comment by AlenBadel** [comment] 2019-09-10 18:13
Taking a look at this.

**Comment by gita-omr** [comment] 2019-09-11 15:34
Wow, was able to assign to @AlenBadel due to the comment! @AlenBadel please update with the latest progress.

**Comment by pshipton** [comment] 2019-09-13 20:11
@AlenBadel @gita-omr @zl-wang 
Given the previous comment indicates this is a regression, it should be fixed before we release pLinux. We don't want to hold up the 0.16 release for other platforms, so we'll plan to tag the final release on the weekend (Sep 14) and not include plinux in the 0.16 release which is scheduled to go live Tues Sep 17. Once we can fix this, we have the option to create a new release (0.16.1), depending on the timing. The 0.17 release is coming quickly, to GA around Oct 18.
Let us know if there is any new information about this problem.

**Comment by gita-omr** [comment] 2019-09-13 20:22
I was actually suspecting it's a test case problem. Multiple threads are accumulating double values into the same DoubleAccumulator which causes reassociation and therefore shows different result in last few digits.

**Comment by andrew-m-leonard** [comment] 2019-09-16 10:30
I've had a look at the testcase and the underlying DoubleAccumulator code, and the intention of the testcase seems good to me, ie.utilising the "atomic" DoubleAccumulator across a bunch of threads to add up a set of double numbers....
I've delved into the DoubleAccumulator class library code, and it is complicated beyond belief, I suspect you need a top PHD in Mathematics to understand what it is doing.....!! So with that in mind however, I am not surprised the JIT may have an issue optimizing it, but equally given it's complexity I wouldn't also rule out the JCL code just being wrong....!

**Comment by andrew-m-leonard** [comment] 2019-09-16 10:41
One addition, the DoubleAccumulator implementation does make use of @jdk.internal.vm.annotation.Contended

**Comment by gita-omr** [comment] 2019-09-16 11:57
This test was un-excluded only recently. Does it mean we never seen it passing?

**Comment by pshipton** [comment] 2019-09-16 12:42
My concern is this comment

> For reference this seems to have been exposed during the 08/27 Build, as the test didn't assert with the prior 08/21 Build.

**Comment by gita-omr** [comment] 2019-09-16 13:10
Me too. We will post an update soon.

**Comment by AlenBadel** [comment] 2019-09-16 14:46
The test case itself `JSR166TestCase.java` runs `testAccumulateAndGetMT` multiple times, using different "suites". 
The failure itself is intermittent, but since `testAccumulateAndGetMT()` fails with multiple "suites" we almost always see it. Nevertheless, the failure is almost always the same. 

I've been running it manually elusively running JSR166TestCase with `ForkJoinTaskTest.suite());`

I was able to reproduce this while compiling only two methods. 
 1 )
` method="java/util/concurrent/atomic/DoubleAccumulator.accumulate(D)V" `
2) 
`method="DoubleAccumulatorTest$$Lambda$39/0000000000000000.applyAsDouble(DD)D"  `

Specially, it was reproducible using ` -Xjit:optLevel=noOpt,lastOptIndex=0,limit={<method 1>, <method 2>}`

I'm taking a look at how we compile these two methods from 08/21 and comparing them to just reccently.

**Comment by andrew-m-leonard** [comment] 2019-09-16 19:08
Interesting the same test case JSR166TestCase has just failed on zLinux, but it looks a different issue, a timeout....
https://ci.adoptopenjdk.net/job/Test_openjdk13_j9_sanity.openjdk_s390x_linux/41/consoleFull
@pshipton @AlenBadel

**Comment by gita-omr** [comment] 2019-09-16 22:11
@AlenBadel will provide more detailed update. I just wanted to mention that we don't think it's incorrect test case anymore. After a more careful look, the test case just trying to stress out the DoubleAccumulator (which is supposed to be thread safe) under multiple threads as much as possible. 

This leaves us with two possibilities: (1) atomicity issue (eg JIT or VM made the class thread unsafe)  (2) reassociation of double operations. We are leaning towards (1). I suspect compiling the two methods in  https://github.com/eclipse/openj9/issues/7011#issuecomment-531810450 makes the accumulation much faster and exposes the problem (the first method calls the second one).

**Comment by raguks** [comment] 2019-09-18 14:55
@gita-omr @AlenBadel do you have any update on this one?

**Comment by gita-omr** [comment] 2019-09-18 15:12
We are suspecting it fails with 0.15 (which makes it a non-regression). Confirming now. Also trying to figure out which causes this apparent data race condition.

**Comment by gita-omr** [comment] 2019-09-18 18:16
Confirmed it fails with 0.15:  https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder_Advanced/1516/ 

Still debugging but it might take a while since it's a very tricky concurrency issue.

**Comment by pshipton** [comment] 2019-09-18 18:35
Since it's not a regression, moving to the next release. We'll go ahead and build plinux for the 0.16 release.

**Comment by gita-omr** [comment] 2019-09-24 15:02
A quick update: we are actively debugging this failure. Good news is that it seems to be not a concurrency/synchronization  but most likely some other codegen issue. Floating point re-association was eliminated as well.

**Comment by AlenBadel** [comment] 2019-09-27 17:01
Just to follow up on https://github.com/eclipse/openj9/issues/7011#issuecomment-531810450 Initially I thought the problem was only reproducible when being invoked by `ForkJoinTaskTest`. 
I created a small micro test case based off of `testAccumulateAndGetMT`, and using the same options above I was able to reproduce the issue. 

`testAccumulateAndGetMT` essentially uses a cyclic barrier `Phaser` to launch several threads that accumulate values one to a million. The test waits for all threads to finish their work before the accumulated sum is compared to the expected value.

Next to tackle and confirm validity of the concurrency properties of this problem. Since the resulting accumulation output is always less than the expected result I thought that perhpahs the spawned threads were not finished accumulating before the accumulated value is read. The test uses `Phaser.arriveAndAwaitAdvance()` as the barrier before `DoubleAccumulator.get()` is called to read the accumulated value. To verify correctness, I changed the test case so that the initial thread is forced to busy-wait while polling `Phaser.getUnarrivedParties()` which identifies how many other threads were still running. This ensures only one thread is alive before the accumulated value is read. The test still failed, which presented the conviction that Phaser was doing it's job; not allowing the accumulated value to be read before all tasks were finished accumulation. The accumulated result has definitely been corrupted somewhere. 

I was able to reproduce this issue reliability in SMT1 mode (Forces programs to use one hardware thread) and by modifying `testAccumulateAndGetMT` to accumulate iteratively over one software thread. So we've ruled concurrency and re-association.

Modifying the test case to just simply accumulate 0, and then 1 exposed the issue. Digging a bit deeper, it looks like lambda method `applyAsDouble` has been giving the wrong output. For an input of 0 and 1 instead of adding them and the output resulting being 1, we were getting some garbage exponentially close to zero. 

`DoubleAccumulator.accumulate` invokes `Lambda.applyAsDouble`. Before the call is made to `applyAsDouble`, `DoubleAccumulator.accumulate` sets up the arguments to be used. The floating point registers fp0, and fp1 are loaded their respective values of 0, and 1 from the stack. `DoubleAccumulator.accumulate` then proceeds to call `applyAsDouble` via the `interfaceCallHelper`, but the value of `fp0` becomes corrupted somewhere in the `interfaceCallHelper` routine. 

Looking further `interfaceCallHelper` ultimately reaches the helper [jitGetExceptionTableFromPC](https://github.com/eclipse/openj9/blob/master/runtime/codert_vm/jswalk.c#L1483). This helper allocates memory using `j9mem_allocate_memory` which changes `fp0`. The issue was intermittent because we don't always allocate memory during this call.

The solution is to preserve floating point argument registers (fp0-fp7) before a call to the `jitAddPicToPatchOnClassUnload` helper which calls `jitGetExceptionTableFromPC` later on. the registers are then restored coming back from `jitAddPicToPatchOnClassUnload`.

I will also be checking all other JIT Helpers, to ensure if they allocate memory that all argument registers are preserved.

**Comment by gita-omr** [comment] 2019-09-27 17:07
Thanks @AlenBadel for the great job!

@pshipton @DanHeidinga, do you think we should aim for 0.17? Looks like @AlenBadel  fixed pretty severe issue.

**Comment by DanHeidinga** [comment] 2019-09-27 17:11
How risky is the fix?  If the fix isn't too risky, I would prefer to include it as this fixes an incorrect calculation / bad data situation.

**Comment by gita-omr** [comment] 2019-09-27 17:18
I would say not very risky. I believe we already save GPRs so just do similar thing for FPRs.

I agree, incorrect FP result is concerning.

**Comment by AlenBadel** [comment] 2019-09-27 17:20
> How risky is the fix? If the fix isn't too risky, I would prefer to include it as this fixes an incorrect calculation / bad data situation.

Not risky at all. The registers are preserved on the stack inside `jitAddPicToPatchOnClassUnload` before the call to `jitAddPicToPatchOnClassUnload`. We're not expanding the size of the routine's stack or anything.

**Comment by pshipton** [comment] 2019-09-27 22:41
Ideally this should be resolved the first week of Oct (by Oct 4), and get into the Milestone 2 build for 0.17.

**Comment by smlambert** [comment] 2019-09-30 13:45
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1369

**Comment by AlenBadel** [comment] 2019-09-30 22:06
I've taken a long look and I believe the only JIT Helper used within PicBuilder on Power is `jitAddPicToPatchOnClassUnload` all others are VM Helpers. 
VM Helpers are also assumed to be safe, as they preserve all volatile registers (GPR3-10 + FP0-FP7) on entry, and restore them as they exit. @gacholio Please correct me if I'm wrong.

In regards to my previous https://github.com/eclipse/openj9/issues/7011#issuecomment-536026668, we actually need to increase the stack before the call to `TOC_jitAddPicToPatchOnClassUnload`. All the floating point argument registers FP0-FP7 can't fit in the already allocated space. I'll need to grow the stack by 64Bytes (8Bytes * 8 Floating Point Registers) to a total of 128Bytes. (It takes 128 Bytes to store GPR3-10 and FPR0-FP7)

Usually the GPRs are backed up at the beginning of a routine. See
https://github.com/eclipse/openj9/blob/master/runtime/compiler/p/runtime/PicBuilder.spp#L2759

There is some complexity expanding the stack at this location. This is most likely due to some unforeseen branching or paths inside picbuilder. I believe it's due to bad "stack math" being assumed somewhere. There may exist one or more paths that assume the stack to be 64bytes rather than 128bytes, even though the stack size can be changed inside of `interfaceCallHelper` and `_interfaceCompeteSlot2`. The two mentioned routines also assume GPRs to be in memory, so storing the GPRs somewhere closer to the C-Helper call isn't an option. 

Instead, I've gone ahead and simply incremented the java stack pointer inside `__picRegistrationbefore` to store the FPRs.  The FPRs are restored after the C-Helper call, and the java stack pointer is decremented back.

**Comment by AlenBadel** [comment] 2019-09-30 22:09
@smlambert I assume I need to re-include this test once my fix is in.

**Comment by gita-omr** [comment] 2019-09-30 22:30
Jenkins test sanity aix,plinux jdk8,jdk11,jdk13

**Comment by gita-omr** [comment] 2019-09-30 22:34
I agree with https://github.com/eclipse/openj9/issues/7011#issuecomment-536772416. I think this is the safest fix.

**Comment by smlambert** [comment] 2019-09-30 23:19
@AlenBadel yes, once this fix is in, it should get removed from the excludes files:

https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk12-openj9.txt#L311
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk13-openj9.txt#L306

**Comment by AlenBadel** [comment] 2019-10-01 16:15
@smlambert 

It looks like it's been disabled on JDK12 for a long time. Is there interest to enable this on JDK12 on all platforms? 
Was disabling the JSR166 test on S390 a mistake? The line references this issue, and this is a power issue.

**Comment by AlenBadel** [comment] 2019-10-01 17:32
Commit https://github.com/eclipse/openj9/pull/7290

**Comment by smlambert** [comment] 2019-10-01 17:38
Yes, https://github.com/eclipse/openj9/issues/7011#issuecomment-537112118 its interesting, for the purpose of this issue and your PR, we will reinclude for jdk13, as the jdk12 points at a separate issue (which states it should be always excluded, which we should revisit, based on the jdk13 runs and results).

**Comment by adam-thorpe** [comment] 2019-10-02 14:35
@AlenBadel yes I've just realised I made a mistake in excluding it on s390x, it should've been power, however the test fails on both as stated above (but for different reasons, s390x seems to be resolved now). I will update the list to state power not zlinux and then the test can be reincluded when needed.

**Comment by AlenBadel** [comment] 2019-10-03 16:55
Merged
https://github.com/eclipse/openj9/pull/7290

@andrew-m-leonard Could you please confirm and resolve this?

**Comment by pshipton** [comment] 2019-10-04 02:46
I'll tentative close it now, and if there is a problem we can reopen.

**Closed by pshipton** 2019-10-04 02:46 UTC
Labels: arch:power, comp:jit, test excluded, test failure

**Comment by andrew-m-leonard** [comment] 2019-10-04 09:00
I can confirm it is now passing on pLinux
