### ISSUE TITLE
JDK15 SyntheticGCWorkload_DoubleMap_J9_0_FAILED : j9mm.316    *   ** ASSERTION FAILED ** at GlobalMarkingScheme.cpp:870: ((uintptr_t)0x99669966 == (clazz)->eyecatcher)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10354] opened 2020-08-07 14:21 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_extended.functional_ppc64le_linux_Nightly/10/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```

=============================================== 
Running test SyntheticGCWorkload_DoubleMap_J9_0 ... 
===============================================

06:41:21.283 0x148600    j9mm.316    *   ** ASSERTION FAILED ** at GlobalMarkingScheme.cpp:870: ((uintptr_t)0x99669966 == (clazz)->eyecatcher)

SyntheticGCWorkload_DoubleMap_J9_0_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
03:39:48  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=ppc64le_linux&TARGET=SyntheticGCWorkload_DoubleMap_J9_0

**Comment by JasonFengJ9** [comment] 2020-08-07 14:21
fyi @dmitripivkine

**Comment by dmitripivkine** [comment] 2020-08-07 15:43
duplicate of https://github.com/eclipse/openj9/issues/10249

**Closed by dmitripivkine** 2020-08-07 15:43 UTC
Labels: comp:gc, test failure
