### ISSUE TITLE
unable to generate thread dump / javacore on macOS

### ISSUE THREAD

**Issue by yusuke** [eclipse/openj9#3468] opened 2018-10-29 02:10 UTC
build: OpenJDK11-jdk_x64_mac_openj9_11.0.1_13.tar.gz

Steps to reproduce:
1. run a Java application using OpenJDK11-jdk_x64_mac_openj9_11.0.1_13
2. trigger $ kill -9 PID
3. nothing happens

**Comment by DanHeidinga** [comment] 2018-10-29 03:18
@babsingh can you take a look at this?

**Comment by pdbain-ibm** [comment] 2018-10-29 12:18
@yusuke 

Thank you for your report.  I would like to reproduce your situation.

Would you please confirm the Java version and MacOS version?
I am running High Sierra (10.13.6) and Java version (downloaded from AdoptOpenJDK)
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.1+13)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.11.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20181020_7 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9dc
OMR      - ea548a66
JCL      - f62696f378 based on jdk-11.0.1+13)
```

Have you tested with a simple application such as the one attached?
[looper.java.txt](https://github.com/eclipse/openj9/files/2525167/looper.java.txt)

Are you using and VM arguments?

I tested both `kill` and `kill -9` on the above application and both worked. 

If you wish, you can contact me directly on the openj9.slack.com Slack channel.

**Comment by pdbain-ibm** [comment] 2018-10-29 12:45
I tested with `kill -QUIT` and it generated a javacore, but it generates the dump in `Contents/Home/bin` due to known issue https://github.com/eclipse/openj9/issues/3343.
@babsingh Looking at the git log, I don't think the MacOS build on AdoptOpenJDK contains the fix for same, correct?
@yusuke could you please check the `bin` for javacores/system cores?

Thank you

**Comment by babsingh** [comment] 2018-10-29 13:55
I also saw similar results as Peter. I sent `kill -3` (generate core files), `kill -9`, `SIGINT`, `SIGTERM` and `SIGHUP`. All signals worked as expected. I am running MacOS Sierra (10.13.4).

> generates the dump in Contents/Home/bin due to known issue #3343

Based upon SDK's OpenJ9 SHA (**090ff9dc**), #3381 changes are not included in the below SDK.

**Downloaded** [OpenJDK11-jdk_x64_mac_openj9_11.0.1_13](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_x64_mac_openj9_11.0.1_13.tar.gz).

**Micro-test:**
```
import sun.misc.Signal;

public class QuickTest extends Thread {

        private static Object monitor = new Object();

        public static void main(String args[]) {
                Runtime.getRuntime().addShutdownHook(new QuickTest());
                System.out.println("Press CTRL-C to exit");

                synchronized (monitor) {
                        try {
                                monitor.wait();
                        } catch (Exception e) {
                                System.out.println("Main thread interrupted");
                        }
                        System.out.println("Terminating main thread correctly");
                }
        }

        public void run() {
                System.out.println("OK... exiting");
                synchronized (monitor) {
                        monitor.notify();
                }
        }

}
```

**Comment by babsingh** [comment] 2018-10-31 13:56
@yusuke we would like to replicate your issue.  the app may be hung ... making it unresponsive to signals. can you provide us the instructions to run the Java app for reproducing the issue?

**Comment by yusuke** [comment] 2018-11-15 02:57
It worked from Terminal.app.
But somehow I still don't get java core when I'm running from IntelliJ IDEA.

 https://youtu.be/H8mX2Ta6TYQ

**Comment by babsingh** [comment] 2018-11-16 21:49
**Tried to use OpenJ9 in IntelliJ IDEA.**
- Verified @yusuke's observation: `kill -3` **SIGQUIT** doesn't generate javacores when OpenJ9 is run within IntelliJ IDEA. But, `kill -3` generates javacores when OpenJ9 is run from a terminal outside IntelliJ IDEA.
-  After debugging OpenJ9 within IntelliJ IDEA, I found that ...
   - The signal handler is being successfully registered for `SIGQUIT`. But, the OpenJ9 process doesn't receive the `SIGQUIT` signal raised via `kill -3 <PID>`. 
   - Inside IntelliJ IDEA, the OpenJ9 process successfully receives and handles other signals such as `SIGINT`, `SIGHUP`, `SIGTERM`, `SIGABRT`, `SIGUSR1`, `SIGKILL` etc.
   - It seems like `SIGQUIT` is somehow blocked for the OpenJ9 process within IntelliJ IDEA. In case of Hotspot, `SIGQUIT` successfully reaches Hotspot and the javacore output is produced.
   - More investigation will be required to resolve the **SIGQUIT** issue. **Guess:** IntelliJ IDEA's initialization or setup may have caused a conflict with OpenJ9's SIGQUIT handling or vice-versa.

**Workarounds to generate a `javacore` within IntelliJ IDEA:**
1. `kill -6 <PID>` **SIGABRT** works within IntelliJ IDEA. **SIGABRT** will generate a javacore, snap trace, core dump and jit dump. But, **SIGABRT** will also terminate the OpenJ9 process. A user may not want the OpenJ9 process to terminate. In this case, the below `-Xdump` option can be used.
2. JVM option `-Xdump` can be used to generate javacores. A cmdline example is shown below. [-Xdump usage](https://www.eclipse.org/openj9/docs/xdump/). Multiple trigger [events=<...>](https://www.eclipse.org/openj9/docs/xdump/#dump-events) are available. In IntelliJ IDEA, `-Xdump:...` can be specified in `Open edit Run/Debug configurations dialog -> Edit Configurations -> VM options: <JVM_OPTIONS>`.
```
<JAVA_HOME>/bin/java -Xdump:java:events=catch,filter=java/lang/OutOfMemory* Application
```

**Comment by babsingh** [comment] 2018-11-21 18:39
I was able to reproduce this issue on Linux. IntelliJ IDEA is run using Hotspot. Hotspot blocks `SIGQUIT`. So, any sub-process (fork or exec) within IntelliJ IDEA will have `SIGQUIT` blocked.

On Linux, it is easy to investigate this issue:
- [Reference to find blocked signals for a process on Linux](https://unix.stackexchange.com/questions/85364/how-can-i-check-what-signals-a-process-is-listening-to)
- [Reference to unblock signals for a process](https://stackoverflow.com/questions/42982014/cant-set-signal-handler-for-sigquit-in-child-process-started-from-java)

Only Unix platforms will be affected by this issue. Created an OMR PR with the fix: https://github.com/eclipse/omr/pull/3225.

**Comment by charliegracie** [comment] 2018-11-21 20:35
@babsingh isn't this one of the things that `jsig` is supposed to be handling? If HotSpot blocks the signal, which I believe it does, how does this work when launching a Java process on another HotSpot JVM? Is your belief that they are unblocking the signal? I would have expected jsig to perform this task.

**Comment by babsingh** [comment] 2018-11-21 23:33
`jsig` enables signal chaining. It is used with native applications that invoke the JVM and register an application signal handler. Signal chaining will invoke the application signal handler + the JVM signal handler. [JSIG Documentation](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/j9_native_signals.html).

In this case, `jsig` doesn't apply because a native application is not involved.

Hotspot VM process forks an OpenJ9 VM process or another Hotspot VM process or a native application. In all scenarios, the forked process has `SIGQUIT` blocked : `grep Sig /proc/<PID>/status`. The forked process won't receive the `SIGQUIT` signal when raised via `kill -3 <PID>`, and the `SIGQUIT` handler won't be invoked.

In case of Hotspot VM process forking another Hotspot VM process, `SIGQUIT` is blocked for the forked Hotspot VM process in `/proc/<PID>/status` (inherited from the parent process). But, the forked Hotspot VM process still handles `SIGQUIT`. **Guess:** The forked Hotspot VM process is dynamically unblocking `SIGQUIT` during initialization similar to eclipse/omr#3225. Unblocking a signal in such manner doesn't update `/proc/<PID>/status`.

> Is your belief that they are unblocking the signal in the child? 

YES, I believe that the forked Hotspot VM process unblocks `SIGQUIT` for itself during initialization.

**Comment by DanHeidinga** [comment] 2018-11-22 04:32
> Unblocking a signal in such manner doesn't update /proc/<PID>/status.

WIth eclipse/omr#3225 is /proc/<PID>/status updated for the forked process?

**Comment by babsingh** [comment] 2018-11-22 14:00
With eclipse/omr#3225, `SIGQUIT` is unblocked for OpenJ9 but `/proc/<PID>/status` isn't updated. `/proc/<PID>/status` still shows `SIGQUIT` is blocked.

**Comment by DanHeidinga** [comment] 2018-11-22 14:07
So with this change our behaviour and the `/proc` settings are consistent with RI?  Sounds good to me!

**Comment by babsingh** [comment] 2018-12-06 17:02
I tried the latest OpenJ9 JDK11 macOS x64 SDK at [AdoptOpenJDK](https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9) - [jdk_x64_mac_openj9_2018-12-06-13-30.tar.gz](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2018-12-06-13-30/OpenJDK11U-jdk_x64_mac_openj9_2018-12-06-13-30.tar.gz) 
to verify the eclipse/omr#3225 fix. OpenJ9 successfully generates javacores (`kill -3 <PID>`) when run within IntelliJ IDEA. @pshipton @DanHeidinga this issue can be closed.

**Comment by DanHeidinga** [comment] 2018-12-06 17:08
Thanks @babsingh!  Closing this now but @yusuke please comment if you see the issue with the updated builds.

**Closed by DanHeidinga** 2018-12-06 17:08 UTC
Labels: comp:vm, userRaised
