### ISSUE TITLE
Add a description on the Docker Hub page

### ISSUE THREAD

**Issue by philippgille** [eclipse/openj9#1115] opened 2018-02-06 12:50 UTC
The Docker Hub page of your public Docker image looks like it got zero attention, which make it seem like you guys don't care about people who want to run their application on OpenJ9 in a Docker container.

As this number increases with the popularity of Docker, you might want to improve the Docker Hub page.

According to #38 it's https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9/ and this is how it currently looks:

![grafik](https://user-images.githubusercontent.com/170670/35860236-9f489ca2-0b43-11e8-8314-3205e8e49989.png)

Now compare that to some of the popular Docker images on Docker Hub. Most of them contain the following:
- A description about what the Docker image contains / what the application/runtime does
- A list of tags and according links to the Dockerfile in GitHub
- An example how to start a container with `docker run`
- An example of a Dockerfile that builds upon the Docker image
- Links to further information (tutorials, references, website, support, ...)

As an example check out the official OpenJDK Docker Image page on Docker Hub: https://hub.docker.com/_/openjdk/

Related to #38

**Comment by pshipton** [comment] 2018-02-06 13:17
@dinogun fyi. Is this issue better opened at AdoptOpenJDK?

**Comment by dinogun** [comment] 2018-02-07 17:07
@philippgille Thanks for reporting this. I have opened an issue at AdoptOpenJDK [here](https://github.com/AdoptOpenJDK/openjdk-docker/issues/13). Some of the info is available at this [blog](https://blog.adoptopenjdk.net/2017/12/adopt-openjdk-docker-images-now-available) and on the [ibmjava](https://hub.docker.com/r/library/ibmjava/) dockerhub page.

**Comment by DanHeidinga** [comment] 2018-02-07 21:17
Closing this as the issue is tracked at Adopt now.

**Closed by DanHeidinga** 2018-02-07 21:17 UTC
Labels: userRaised
