### ISSUE TITLE
i improve printerjob can print preview

### ISSUE THREAD

**Issue by annopnod** [eclipse/openj9#5550] opened 2019-04-18 02:26 UTC
PrinterJob.java

public void printpreview(ImagePrinter f) throws PrinterException, IOException {
        int index = 0;
        boolean haspage = true;
        int w = (int) this.job.defaultPage().getWidth();
        int h = (int) this.job.defaultPage().getHeight();

        while (haspage) {

            BufferedImage image = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d = image.createGraphics();
            haspage = this.painter.print(g2d, this.job.defaultPage(), index) == Printable.PAGE_EXISTS;
            if (haspage) {
                f.WritePaper(image);
            }
            image.flush();
            image = null;
            System.gc();
            index++;

        }

    }

public class ImagePrinter {

    RandomAccessFile raf;

    public ImagePrinter(File f) {
        try {
            this.raf = new RandomAccessFile(f, "rw");
            
        } catch (Exception ex) {

        }

    }

    public void Close() {
        try {
            this.raf.close();
            System.gc();
        } catch (IOException ex) {

        }
    }

    public int GetPaperCount() throws IOException {
        int accumulator = 0;

        this.raf.seek(0);
      
        while (this.raf.getFilePointer() < this.raf.length()) {
            int length = this.raf.readInt();
            this.raf.seek(this.raf.getFilePointer() + length);
            accumulator++;
        }

        return accumulator;
    }

    public BufferedImage ReadPaper(int i) throws IOException {
        int accumulator = 0;
        this.raf.seek(0);

        while (this.raf.getFilePointer() < this.raf.length()) {
            if (i == accumulator) {
                int length = this.raf.readInt();
                byte[] bytesdata = new byte[length];
                this.raf.readFully(bytesdata);
                return ImageIO.read(new ByteArrayInputStream(bytesdata));
            } else {
                int length = this.raf.readInt();
                this.raf.seek(this.raf.getFilePointer() + length);
                accumulator++;
            }
        }

        return null;
    }

    public void WritePaper(BufferedImage image) throws IOException {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ImageIO.write(image, "png", baos);
        baos.flush();
        byte[] b = baos.toByteArray();
        this.raf.writeInt(b.length);
        this.raf.write(b);
        baos.close();

    }

}

**Comment by DanHeidinga** [comment] 2019-04-18 02:40
HI @annopnod I'm not clear on what the issue being reported is.  Can you add more detail on what the problem is?  Thanks.

**Comment by annopnod** [comment] 2019-04-18 04:30
PrinterJob.java oracle can not print preview to BufferedImage
i improve printerjob can  print preview to BufferedImage
i improve ImagePrinter.java is virtual printer export  to BufferedImage
can drawimage using  jlabel imageicon on jscrollpane

**Comment by annopnod** [comment] 2019-04-18 04:31
PrinterJob.java oracle can not print preview to BufferedImage
i improve PrinterJob.java can print preview to BufferedImage
i create class ImagePrinter.java is virtual printer export to BufferedImage
can drawimage using jlabel imageicon on jscrollpane

**Comment by pdbain-ibm** [comment] 2019-04-18 12:09
@annopnod This appears to be a change to OpenJDK, specifically java.desktop/share/classes/java/awt/print/PrinterJob.java.  Am I correct?

**Comment by annopnod** [comment] 2019-04-19 01:19
yes

**Comment by DanHeidinga** [comment] 2019-04-22 13:51
@annopnod This change is to base OpenJDK class library code.  The best place to get this change made is upstream at the OpenJDK project.

OpenJ9 works to consume the OpenJDK class libraries with as few changes as possible.  We prefer to see non-vm specific changes be made in OpenJDK directly and we'll consume them after that.

Have you suggested this change at the OpenJDK project? A link to the mailing list discussions there would help connect the two discussions.

**Comment by DanHeidinga** [comment] 2019-05-01 15:32
I'll close this now as we've noted it should be raised to OpenJDK.

**Closed by DanHeidinga** 2019-05-01 15:32 UTC
Labels: userRaised
