### ISSUE TITLE
Segmentation error on openj9-0.13.0, JRE 12 Windows 10 amd64

### ISSUE THREAD

**Issue by Azquelt** [eclipse/openj9#5581] opened 2019-04-23 14:51 UTC
Java -version output
--------------------

openjdk version "12" 2019-03-19
OpenJDK Runtime Environment AdoptOpenJDK (build 12+33)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.13.0, JRE 12 Windows 10 amd64-64-Bit Compressed References 20190320_32 (JIT enabled, AOT enabled)
OpenJ9   - caeb51f87
OMR      - 33a33ff2
JCL      - 419f571019 based on jdk-12+33)

Summary of problem
------------------

While testing OpenLiberty, the vm running the application server crashed with a Segmentation error.

log output: (includes the last few lines of application log)
```
[AUDIT   ] CWWKZ0001I: Application ftTimeout started in 4.695 seconds.
[WARNING ] reaper.stall 
                                                                                                               000002.058481
                                                                                                               000000.009260
Unhandled exception
Type=Segmentation error vmState=0x000501ff
Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00000000630F12A1 ContextFlags=0010005f
Handler1=0000000063037AA0 Handler2=00007FFBCDB3ECF0 InaccessibleReadAddress=0000000000000000
RDI=000000D336DF8040 RSI=00000000007E8400 RAX=0000000000000000 RBX=000001E6200E98C0
RCX=0000000000000000 RDX=00007FF4D95412D0 R8=00000000636B7EF0 R9=000000D336DF79A0
R10=00007FF4D94E9EE0 R11=00007FF4D94E9EE0 R12=00007FF4D95411B8 R13=00007FF4D95410E0
R14=00000000007EAD00 R15=00007FF4D9541000
RIP=00000000630F12A1 RSP=000000D336DF7B00 RBP=000000D336DF7C28 GS=002B
FS=0053 ES=002B DS=002B
XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM6 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM7 000000003e68f5c3 (f: 1047066048.000000, d: 5.173194e-315)
XMM8 000000003f266666 (f: 1059481216.000000, d: 5.234533e-315)
XMM9 000000003dcccccd (f: 1036831936.000000, d: 5.122630e-315)
XMM10 000000003f800000 (f: 1065353216.000000, d: 5.263544e-315)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\jvms\OpenJDK12U-jdk_x64_windows_openj9_12_33_openj9-0.13.0\bin\compressedrefs\j9jit29.dll
Module_base_address=0000000062FB0000 Offset_in_DLL=00000000001412a1

Method_being_compiled=org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;
Target=2_90_20190320_32 (Windows 10 10.0 build 10240)
CPU=amd64 (2 logical CPUs) (0x1fff79000 RAM)
----------- Stack Backtrace -----------
Java_java_lang_invoke_MutableCallSite_invalidate+0x7dfe1 (0x00000000630F12A1 [j9jit29+0x1412a1])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7dccb (0x00000000630F0F8B [j9jit29+0x140f8b])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7eeb1 (0x00000000630F2171 [j9jit29+0x142171])
Java_java_lang_invoke_MutableCallSite_invalidate+0x362754 (0x00000000633D5A14 [j9jit29+0x425a14])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5deb4 (0x00000000630D1174 [j9jit29+0x121174])
Java_java_lang_invoke_MutableCallSite_invalidate+0x362231 (0x00000000633D54F1 [j9jit29+0x4254f1])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5da33 (0x00000000630D0CF3 [j9jit29+0x120cf3])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3febb9 (0x0000000063471E79 [j9jit29+0x4c1e79])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3fb595 (0x000000006346E855 [j9jit29+0x4be855])
Java_java_lang_invoke_MutableCallSite_invalidate+0x26339a (0x00000000632D665A [j9jit29+0x32665a])
(0x00000000630256BC [j9jit29+0x756bc])
(0x0000000063028384 [j9jit29+0x78384])
j9port_isCompatible+0x1ca26 (0x00007FFBCDB3F736 [j9prt29+0x1f736])
j9port_isCompatible+0x1e124 (0x00007FFBCDB40E34 [j9prt29+0x20e34])
(0x0000000063024E79 [j9jit29+0x74e79])
(0x000000006302A578 [j9jit29+0x7a578])
(0x0000000063029F58 [j9jit29+0x79f58])
(0x000000006303782F [j9jit29+0x8782f])
j9port_isCompatible+0x1e15f (0x00007FFBCDB40E6F [j9prt29+0x20e6f])
(0x000000006303744D [j9jit29+0x8744d])
omrthread_get_category+0xa42 (0x00007FFBD4E24452 [J9THR29+0x4452])
_o_ceil+0x4e (0x00007FFBDDE7C4CE [ucrtbase+0x1c4ce])
BaseThreadInitThunk+0x14 (0x00007FFBDE8E3DC4 [KERNEL32+0x13dc4])
RtlUserThreadStart+0x21 (0x00007FFBE1273691 [ntdll+0x73691])
---------------------------------------
JVMDUMP039I Processing dump event "gpf", detail "" at 2019/04/18 06:07:54 - please wait.
JVMDUMP032I JVM requested System dump using 'C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\core.20190418.060754.5164.0001.dmp' in response to an event
JVMDUMP010I System dump written to C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\core.20190418.060754.5164.0001.dmp
JVMDUMP032I JVM requested Java dump using 'C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\javacore.20190418.060754.5164.0002.txt' in response to an event
JVMDUMP010I Java dump written to C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\javacore.20190418.060754.5164.0002.txt
JVMDUMP032I JVM requested Snap dump using 'C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\Snap.20190418.060754.5164.0003.trc' in response to an event
JVMDUMP010I Snap dump written to C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\Snap.20190418.060754.5164.0003.trc
JVMDUMP007I JVM Requesting JIT dump using 'C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\jitdump.20190418.060754.5164.0004.dmp'
JVMDUMP010I JIT dump written to C:\jazz-build-engines\jazz112.hursley.ibm.com\EBC.PROD.WASRTC\build\dev\image\output\wlp\usr\servers\FaultTolerance20TCKServer\jitdump.20190418.060754.5164.0004.dmp
JVMDUMP013I Processed dump event "gpf", detail "".
```

Diagnostic files
----------------

[javacore.20190418.060754.5164.0002.clean.txt](https://github.com/eclipse/openj9/files/3108086/javacore.20190418.060754.5164.0002.clean.txt)

Core dump can be provided privately if required.

**Comment by fjeremic** [comment] 2019-04-23 14:55
This is a JIT problem. @andrewcraik @cathyzhyi @0xdaryl FYI, we'll likely need some help to take a look. For starters @Azquelt are you able to reproduce the problem?

The issue seems to be during the compilation of the:

```
org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;
```

method. Are you able to open up the core file with WinDbg or any other post-mortem disassembler on Windows and get us the backtrace of the crashing thread? This will give us insight into where in the JIT we crashed.

**Comment by Azquelt** [comment] 2019-04-23 15:45
I'm not familiar with debugging on windows. Does this contain what you need?

[backtraces.txt](https://github.com/eclipse/openj9/files/3108359/backtraces.txt)

Otherwise, some pointers on how to gather what you need would be helpful.

I was seeing the problem occur reliably on one of our build machines, I haven't tried to reproduce it on my workstation.

**Comment by fjeremic** [comment] 2019-04-23 16:35
Unfortunately no, the thread in question does not appear to be there. It seems we can get the info we need from the VM state:

```
> bin/java -Xjit:vmstate=0x000501ff -version
vmState [0x501ff]: {J9VMSTATE_JIT_CODEGEN} {inlining}
```

Judging by the backtrace we have there from the stdout it could be some JSR 292 related issue. I suggest we try to reproduce using the following JIT option on the JVM command-line:

```
-Xjit:{org/eclipse/microprofile/config/ConfigProvider.getConfig(Ljava/lang/ClassLoader;)Lorg/eclipse/microprofile/config/Config;}(tracefull,traceInlining,traceCG,log=getConfig.trace)
```

The trace file will be generated in the `$PWD`, or you can modify the above command to specify a custom path by modifying the `log=` portion, for example `log=/some/path/filename.trace`. We will need a reproduction of the issue with the above option on the command line.

Was there by any chance a `jitdump.*` file generated along with the javacore and core dump? If this file is not empty it will also be very useful.

**Comment by Azquelt** [comment] 2019-04-23 16:40
Here's the jitdump: 
[jitdump.20190418.060754.5164.0004.dmp.txt](https://github.com/eclipse/openj9/files/3108677/jitdump.20190418.060754.5164.0004.dmp.txt)

I can see if I can reproduce the problem with that argument tomorrow.

**Comment by fjeremic** [comment] 2019-04-23 16:58
Thanks. The jitdump did not reproduce the issue but gives us insight into what was going on in the method. This may be an OSR problem. @andrewcraik @cathyzhyi FYI!

**Comment by cathyzhyi** [comment] 2019-04-24 12:55
The stacktrace are likely to be bogus. The method `Java_java_lang_invoke_MutableCallSite_invalidate` is a JNI call and shouldn't appear in stacktrace from a compilation thread. 
```Java_java_lang_invoke_MutableCallSite_invalidate+0x7dfe1 (0x00000000630F12A1 [j9jit29+0x1412a1])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7dccb (0x00000000630F0F8B [j9jit29+0x140f8b])
Java_java_lang_invoke_MutableCallSite_invalidate+0x7eeb1 (0x00000000630F2171 [j9jit29+0x142171])
Java_java_lang_invoke_MutableCallSite_invalidate+0x362754 (0x00000000633D5A14 [j9jit29+0x425a14])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5deb4 (0x00000000630D1174 [j9jit29+0x121174])
Java_java_lang_invoke_MutableCallSite_invalidate+0x362231 (0x00000000633D54F1 [j9jit29+0x4254f1])
Java_java_lang_invoke_MutableCallSite_invalidate+0x5da33 (0x00000000630D0CF3 [j9jit29+0x120cf3])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3febb9 (0x0000000063471E79 [j9jit29+0x4c1e79])
Java_java_lang_invoke_MutableCallSite_invalidate+0x3fb595 (0x000000006346E855 [j9jit29+0x4be855])
Java_java_lang_invoke_MutableCallSite_invalidate+0x26339a (0x00000000632D665A [j9jit29+0x32665a])
```

can't really tell what's wrong here. tracelog as suggested in  https://github.com/eclipse/openj9/issues/5581#issuecomment-485879836 would be helpful.

**Comment by DanHeidinga** [comment] 2019-05-01 15:31
@Azquelt Have you been able to reproduce the problem using the -Xjit option Fillip suggested?

**Comment by Azquelt** [comment] 2019-05-01 16:17
Not yet. I've run several more test runs with the `-Xjit` option but have not been able to reproduce the option since.

Today I did come across a defect where we saw a saw a similar problem in a build using linux 11.0.2+9_openj9-0.12.1. I'll see if I can get a backtrace from that core dump.

Otherwise, I'm still trying to reproduce the issue. I will report back if I manage to see it happen again.

**Comment by pshipton** [comment] 2019-05-01 17:38
In theory, problems with the 0.12 or 0.13 release could be fixed in the 0.14 release. Ideally this release should be used now that it is released.

**Comment by DanHeidinga** [comment] 2019-05-28 13:32
@Azquelt Have you been able to reproduce the issue with a newer release (ie: 0.14.0)?  Or with the `-Xjit` option?

**Comment by Azquelt** [comment] 2019-05-28 15:03
No, I haven't. I'm happy to close this for now and re-open if I'm able to reproduce with better logs in the future?

**Comment by DanHeidinga** [comment] 2019-05-28 15:28
Sounds good.  Thanks @Azquelt

**Closed by DanHeidinga** 2019-05-28 15:28 UTC
Labels: comp:jit, comp:jit:x, userRaised

**Comment by Azquelt** [comment] 2019-08-21 13:57
I had this reoccur with the `-Xjit` option enabled, but both of the log files just say 
```
<!--
MULTIPLE LOG FILES MAY EXIST
Please check for ADDITIONAL log files named:  getConfig.trace.1  getConfig.trace.2  getConfig.trace.3  getConfig.trace.4  getConfig.trace.5  getConfig.trace.6
-->
```
I've uploaded the mostly empty trace files and the jitdump in case there's something I'm missing there.
[traceAndJitdump.zip](https://github.com/eclipse/openj9/files/3525656/traceAndJitdump.zip)

This is occurring on openj9-0.12.1 - I can't easily reproduce on a newer version because this happens very occasionally and our automated builds run against the earliest version that we support.

**Comment by tevans78** [comment] 2019-09-27 09:20
@DanHeidinga did you get a chance to look at the new dump from Andrew? If this is a reoccurrance of the same problem, please could you reopen this issue? Thank you.
