### ISSUE TITLE
JEP 318: Epsilon: An Arbitrarily Low-Overhead Garbage Collector

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/openj9#1370] opened 2018-03-07 04:42 UTC
http://openjdk.java.net/jeps/318

This is an "Epic" to contain requirements for supporting this JEP on OpenJ9.

**Comment by DanHeidinga** [comment] 2018-03-07 14:36
Discussed this idea with @charliegracie and it should be relatively straightforward to create a "zero gc" policy based off `optthruput`.  

Likely by extending one of the classes (TODO: remember which one) and adding a flag to determine whether or not to GC on allocation failure.

**Comment by ashu-mehra** [comment] 2018-03-07 18:18
@Param-S and I were discussing something similar few weeks back and that it could be useful in OpenWhisk (serverless) kind of environment where the JVM does not run long enough to exhaust heap. We won't need to worry about GC cycle at all; JVM would just handle allocation.
Any idea if that's the scenario this JEP is also targeting, or there are other use cases?

@Param-S - fyi

**Comment by DanHeidinga** [comment] 2018-03-07 18:44
@ashu-mehra Possibly provided the Whisk container has sufficient memory to live through the request(s).  My understanding of OpenWhisk is that the container is reused for subsequent requests and killed every ~15 minutes.  

The use of this kind of GC in that environment would require tuning of the max heap to live through multiple requests.

**Comment by DanHeidinga** [comment] 2018-04-09 13:37
@dmitripivkine Can someone on the GC team take a look at this?  It's (tentatively?) targeted to JDK11 but would be nice to support all the way back to 8.

**Comment by dmitripivkine** [comment] 2018-04-12 14:32
@LinHu2016 Would you please start work on this?

**Comment by LinHu2016** [comment] 2018-04-12 15:12
sure

**Comment by LinHu2016** [comment] 2018-04-16 15:55
not sure if we need to support finalization for "no-gc collector"

**Comment by dmitripivkine** [comment] 2018-04-16 16:28
I believe we should not touch finalization code for primary implementation. There are number of possible improvements (including finalization) we can do in future if necessary

**Comment by LinHu2016** [comment] 2018-05-01 17:47
first step:
- add new gcpolicy:noop ( or match oracle naming -- "gcpolicy:epsilon", any another suggestion?, should we support -XX:+UseNoGC and -XX:+UseEpsilonGC for compatibility?)
- initialize heap ,collector ,classmanager base on Optthruput with the configuration for no-op
  ( noScavenge, noConcurrentMark, noConcurrentSweep, noLOA, noSplitAddressOrderedList, disable processLargeAllocateStats/estimateFragmentation, disable system gc...., for now the ParallelGlobalCollector, markingScheme, SweepScheme, CompactScheme have been initialized for minimizing subspace and memorypool change, in future might use "empty colletor" for saving footprint)
 - disable garbage collection on allocation failure in MemorySubSpaceFlat, instead expend heap
 - disable dumps on OOM exception by default, can be enabled with the java options
 - update verbose gc and MXBeans for new gcpolicy
 - no finalization
- test plan: try to reuse openjdk test/hotspot/jtreg/gc/epsilon, some tests need to be updated to work with OpenJ9
- no extra work for supporting in Java 8

**Comment by pshipton** [comment] 2018-05-01 18:29
I suggest -gcpolocy:nogc instead of -gcpolicy:noop. +1 for supporting -XX:+UseNoGC for compatibility. -1 for supporting options using epsilon as this seems like a transient name that wouldn't necessarily be supported in the future.

**Comment by dmitripivkine** [comment] 2018-05-01 19:41
I agree with Pete: -gcpolocy:nogc and -XX:+UseNoGC looks better
We do have "expand heap on failure" feature (currently is used in Gencon). I believe it should be used for optthruput. We don't need GC Slave threads to be created.
I am not sure about finalization - this is a part of Java Spec and might be useful even in noGC case (for example release native memory from DBB).

**Comment by LinHu2016** [comment] 2018-05-03 21:00
first step: Updated

    - add new gcpolicy:nogc and support -XX:+UseNoGCfor compatibility
    - initialize heap ,collector ,classmanager base on Optthruput with the configuration for no-op
    ( noScavenge, noConcurrentMark, noConcurrentSweep, noLOA, noSplitAddressOrderedList, disable processLargeAllocateStats/estimateFragmentation, disable system gc...., for now the ParallelGlobalCollector, markingScheme, SweepScheme, CompactScheme have been initialized for minimizing subspace and memorypool change, in future might use "empty collector" for saving footprint)
    - disable garbage collection on allocation failure in MemorySubSpaceFlat, instead trigger  expending heap
    - disable dumps on OOM exception by default, can be enabled with the java options -Xdump
    - update verbose gc and JMX for new gcpolicy
    - enable reportGCStart and reportGCEnd for gcpolicy:nogc in order to report heap memory statistics for verbose gc and JMX
    - no finalization
    - test plan: try to reuse openjdk test/hotspot/jtreg/gc/epsilon, some tests need to be updated to work with OpenJ9
    - update _GIT SPECjbb2005_xxxx tests for performance testing 
    - no extra work for supporting in Java 8

**Comment by LinHu2016** [comment] 2018-05-17 15:37
the result of performance test: SPECjbb2005 warehouses=3 measurement =90 seconds
with -Xmx20G  -Xgcpolicy:optthruput / -Xgcpolicy:gencon / -Xgcpolicy:nogc

                                                                             | optthruput    | gencon          | nogc
___________________________________________________________________________________________
SPECjbb2005Score   (wh3)                               | 24464           | 26237            | 27319
                                                                             | 89.55%         | 96.04%         | 100.00%
Pause time   (mean) ms                                      | 32                  | 5.94              | 0.26
Pause time   (max) ms                                        | 55.1               | 52.6               | 0.79
Pause time   (total) ms                                       | 7577              | 5809              | 5.42
Proportion of garbage collection pauses (%)   | 6.93%            | 5.19%            | 0.01%
Max Heap   Size(expanded)                               | 269MB          | 153MB           | 14,434MB
GC count                                                             | 237                | 946(s)/32(g) | 21

**Comment by LinHu2016** [comment] 2018-05-17 15:51
![screen shot 2018-05-17 at 11 49 25 am](https://user-images.githubusercontent.com/18031118/40188718-953e5778-59c8-11e8-86d1-69b77c1d58da.png)

**Comment by LinHu2016** [comment] 2018-05-17 15:52
![screen shot 2018-05-07 at 10 54 38 am](https://user-images.githubusercontent.com/18031118/40188785-bf205bfe-59c8-11e8-951d-c2a732f9c83a.png)

**Comment by LinHu2016** [comment] 2018-05-17 15:53
![screen shot 2018-05-07 at 10 50 38 am](https://user-images.githubusercontent.com/18031118/40188835-dce9afdc-59c8-11e8-81ef-a26eb17e1456.png)

**Comment by dmitripivkine** [comment] 2018-05-29 15:58
After discussion we decided that -Xgcpolicy:nogc **should** generate set of dumps on OOM by default.
This is a default behaviour for JVM and this is customer responsibility to setup application properly to avoid OOM.

**Comment by DanHeidinga** [comment] 2018-05-29 17:25
> -Xgcpolicy:nogc should generate set of dumps on OOM by default.

Agreed.  In a scenario tuned to run with the `nogc` policy, an OOM should generate dumps to allow the user to figure out the cause.

**Comment by pshipton** [comment] 2018-06-05 14:30
Well, I was just about to ask @dmitripivkine @LinHu2016 if there more work to do, or we can close this Issue.

@fjeremic do we need to keep it open for potential future JIT work, or should we create another issue for that?

**Comment by fjeremic** [comment] 2018-06-05 14:32
> @fjeremic do we need to keep it open for potential future JIT work, or should we create another issue for that?

I would say create another issue or leave things as is since we already took note of it here. I see this as an opportunity for future improvement however we would need to justify investment into this area which means this GC policy has to see some traction first from users.

**Comment by dmitripivkine** [comment] 2018-06-05 15:06
I believe we do have good starting point and can close this issue. JIT support and GC further improvements can be done under another issues.

**Comment by pshipton** [comment] 2018-06-05 15:17
Seems the consensus is to close.

**Comment by pshipton** [comment] 2018-06-05 15:59
Perhaps a little hasty. I should have confirmed, did the appropriate testing for the new gc policy get added?

**Comment by LinHu2016** [comment] 2018-06-07 15:19
@pshipton testing plan has not completed, currently we are using openjdk hotspot jtreg epsilon tests for verifying JEP318 functions and SPECjbb2005 for performance test, but there are some limitations to use epsilon tests.
 1, some epsilon tests have the dependence on new JAVA 9 API (for pid), could not run on Java 8
 2, epsilon tests are not in openjdk main branch(it targets to Java 11)
 3, some tests need to be updated to run with OpenJ9 due to some incompatible jvm options between hotspot and OpenJ9.

**Comment by pshipton** [comment] 2018-09-05 18:55
@LinHu2016 where are we for the testing? I'd like to assign this to a milestone and close it off. The 0.11.0 milestone closes Oct 8, which I'm guessing is too early. I'll tentatively assign this to the 0.12.0 milestone which closes in Jan.

**Comment by LinHu2016** [comment] 2018-09-05 21:02
@pshipton original plan for testing is that trying to reuse openjdk test/hotspot/jtreg/gc/epsilon.
There are 12 of15 tests can be reuse without major code change, but some of tests have dependence on new JAVA 9 APIs, which would not work for Java 829, so I am going to write new pack tests for gcpolicy:nogc.

**Comment by pshipton** [comment] 2018-09-05 21:09
@LinHu2016 do you have a timeline for completing the work? Can it be completed by early January?

**Comment by LinHu2016** [comment] 2018-09-06 14:45
plan to complete it in October.

**Comment by pshipton** [comment] 2018-09-07 15:51
ok. I'll leave it in the Jan 0.12.0 milestone for now, since the Oct 0.11.0 milestone work needs to be completed by Oct 8. If it happens to be finished in time we can change the milestone.

**Comment by pshipton** [comment] 2018-12-03 22:59
@LinHu2016 is there still some testing to complete? I was under the impression it's not quite done yet.

**Comment by LinHu2016** [comment] 2018-12-04 15:24
@pshipton the tests for nogc are done(https://github.com/eclipse/openj9/pull/3355), now they are part of extended tests, I will promote them to sanity test after waiting another week if there is no any issue on all of platforms

**Comment by smlambert** [comment] 2018-12-04 15:55
We are in the process of moving tests in the other direction (move more sanity tests to extended), to ensure sanity set stays small / runs fast.  

Is there a specific request to move the nogc tests to sanity, or can we leave them where they are?

**Comment by pshipton** [comment] 2018-12-04 16:02
@LinHu2016 see Shelley's comment https://github.com/eclipse/openj9/issues/1370#issuecomment-444150978

Separately from the above, is there any reason to keep this Issue open or can it now be closed?

**Comment by LinHu2016** [comment] 2018-12-04 16:49
@smlambert keep the tests in extended level are fine, move to sanity just for catching regression earlier. BTW the most of tests only take under 10 secs, but 2 of them for each platform due to generate dumps might take a couple mins.

**Comment by LinHu2016** [comment] 2018-12-04 16:50
@pshipton  yes, I will close this issue.

**Closed** 2018-12-04 20:05 UTC
Labels: Epic, JEP, comp:gc, doc:externals, jdk11
