### ISSUE TITLE
JDK11: java.net/nio openjdk tests fail on MacOS 10.14

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#6035] opened 2019-06-06 10:14 UTC
Failure link
------------

Internal link: https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac_Nightly/23/

- test category (functionality, system, etc): sanity.openjdk
- test suite name: 
java/net/Inet6Address/B6206527.java.B6206527
java/net/InetAddress/CheckJNI.java.CheckJNI
java/net/MulticastSocket/Promiscuous.java.Promiscuous
java/net/MulticastSocket/SetOutgoingIf.java.SetOutgoingIf
java/net/Socket/LinkLocal.java.LinkLocal
java/net/ipv6tests/B6521014.java.B6521014
java/nio/channels/DatagramChannel/MulticastSendReceiveTests.java.MulticastSendReceiveTests
- OS/architecture (i.e. Ubuntu 16.04 x64): MacOS 10.14
- OpenJDK version (i.e. 8u202-b08): jdk-11.0.4+4
- public build SHAs (i.e. -version output): 
02:49:36  openjdk version "11.0.4-internal" 2019-07-16
02:49:36  OpenJDK Runtime Environment (build 11.0.4-internal+0-adhoc.jenkins.BuildJDK11x86-64macNightly)
02:49:36  Eclipse OpenJ9 VM (build ibm_sdk-8db5207bd0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190526_43 (JIT enabled, AOT enabled)
02:49:36  OpenJ9   - 8db5207bd0
02:49:36  OMR      - 0437c698
02:49:36  JCL      - 8354ce2194e based on jdk-11.0.4+4)

Optional info
-------------

- intermittent failure (yes|no): no
- regression or new test:  been failing for ages....!
- if regression, what are the last passing / first failing public SHAs (OpenJ9, OMR, JCL) :

Failure output
--------------
Various:
java.net.NoRouteToHostException: No route to host (Host unreachable)
java.io.IOException: No route to host
java.net.BindException: Can't assign requested address (Bind failed)

Maybe an issue with Mac 10.14, or maybe a common setup issue on hyc-runtimes on all their 10.14 boxes. These tests run fine on the 10.13 boxes.

**Comment by pshipton** [comment] 2019-06-07 18:55
@andrew-m-leonard does the same problem happen with Hotspot? This seems unlikely to have anything to do with OpenJ9, and more to do with the OpenJDK extensions.

**Comment by andrew-m-leonard** [comment] 2019-06-10 08:22
not sure, I can't run Hotspot at hyc-runtimes... so I will create an issue to try this on someones Macbook with Hotspot

**Comment by smlambert** [comment] 2019-06-10 16:09
Not sure why you think you can not run hotspot at hyc-runtimes...

Current job settings:
<img width="436" alt="Screen Shot 2019-06-10 at 12 05 11 PM" src="https://user-images.githubusercontent.com/2836948/59209069-7a8e6700-8b78-11e9-8096-76e01889b197.png">

Settings changed to run against nightly hotspot build:
<img width="501" alt="Screen Shot 2019-06-10 at 12 05 36 PM" src="https://user-images.githubusercontent.com/2836948/59209119-972a9f00-8b78-11e9-93bd-b4b5d7c7cdcd.png">

**Comment by andrew-m-leonard** [comment] 2019-06-11 08:01
@smlambert thanks, the reason being because I couldn't work out how! you've answered that and i've learned something :-) thanks

**Comment by andrew-m-leonard** [comment] 2019-06-24 13:21
I've run these tests against Hotspot on the hyc-runtimes osx 10.14 machines and it fails the same. I think it is a infrastructure setup issue. @pshipton

**Comment by pshipton** [comment] 2019-06-24 13:47
@smlambert fyi the previous comment wrt the AQA labe.

**Comment by pshipton** [comment] 2019-09-27 22:28
Given this seems to be an infrastructure, not sure it needs to be tied to any OpenJ9 milestone.

**Comment by DanHeidinga** [comment] 2019-10-17 14:08
@andrew-m-leonard Are you (or someone on your team) looking at why this passes on OSX 10.13 and fails at 10.14?

I'd like to get the `AQA` test failures resolved for 0.18.0 and this hopefully low hanging fruit to resolve

**Comment by adam-thorpe** [comment] 2019-10-18 13:09
Tested at hyc
osx1014vm3 (Mac 10.14) vs osxrt3 (Mac 10.11)
- java/net/InetAddress/CheckJNI.java
- java/net/MulticastSocket/Promiscuous.java
- java/net/MulticastSocket/SetOutgoingIf.java
- java/net/Socket/LinkLocal.java
- java/nio/channels/DatagramChannel/Promiscuous.java

**Comment by adam-thorpe** [comment] 2019-10-21 14:23
jdk_net suite passes on an adopt 10.14 machine. https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/856/

**Comment by adam-thorpe** [comment] 2019-10-21 15:08
All 5 of the above tests also fail on hotspot, so this does not seem to be a j9 issue @DanHeidinga.

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2808/
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2810/

**Comment by DanHeidinga** [comment] 2019-10-21 16:09
Thanks @adam-thorpe.  From an OpenJ9 perspective, we can close this issue.

This should be reported on the OpenJDK mailing lists to highlight the issues with the tests.  Ideally with a patch to fix the issue.

Creating an issue at Adopt in one of the test repos to coordinate the investigation would be a good starting point while root cause is being determined.  I'll leave that in your hands @adam-thorpe 

Closing this as it's a not an OpenJ9 issue.

**Closed by DanHeidinga** 2019-10-21 16:09 UTC
Labels: AQA, test failure
