### ISSUE TITLE
AArch64 DDR Unrecognised command: !printallcallsites !findallcallsites

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#9251] opened 2020-04-15 12:36 UTC
https://ci.eclipse.org/openj9/view/Test/job/Grinder/787 - compressedrefs
https://ci.eclipse.org/openj9/view/Test/job/Grinder/789 - XL
AArch64 sanity.functional 0.20.0 branches
cmdLineTester_callsitedbgddrext_openj9_0
`*0 : PID: 84060 : No JRE`
`Unrecognised command: !printallcallsites`
`Unrecognised command: !findallcallsites`

```
OpenJ9: 05fa2d3
OMR: d4365f3
OpenJDK11: fe3ef26 - openj9-openjdk-jdk11
```

**Comment by pshipton** [comment] 2020-04-15 16:23
@knn-k

**Comment by pshipton** [comment] 2020-04-15 16:30
The core could be truncated, but it seems there is lots of space on the machine and I don't think that is what's happening.

The problem is easy to reproduce on cent7-aarch64-1
`java -Xdump:system:events=vmstop -version`
`jdmpview -core <core>`
`*0 : PID: 84925 : No JRE`

The test was working last weekend. It may be related to the gcc 7.5 switch.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Release/3/
```
OpenJ9: 496f48f
OMR: 4bf9435
OpenJDK11: 8a94684 - openj9-openjdk-jdk11
```

https://github.com/eclipse/openj9/compare/496f48f...05fa2d3
https://github.com/eclipse/openj9-omr/compare/4bf9435...d4365f3
https://github.com/ibmruntimes/openj9-openjdk-jdk11/compare/8a94684...fe3ef26

This is a blocking problem because we can't support AArch64 without DDR.

**Comment by pshipton** [comment] 2020-04-15 16:35
It's working fine with the older JVM built last weekend.
`*0 : PID: 85268 : JRE 11 Linux aarch64-64 (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11aarch64linuxRelease)`

**Comment by pshipton** [comment] 2020-04-15 16:52
I ran `jdmpview -J-Xint -core <core>` to disable the JIT, but the problem still occurs.
`*0 : PID: 84925 : No JRE`

**Comment by keithc-ca** [comment] 2020-04-15 18:00
There doesn't appear to be anything wrong with the core file (`openjdk-tests/TKG/test_output_15869240247365/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp`) captured in https://ci.eclipse.org/openj9/view/Test/job/Grinder/787: using jdmpview from a local Linux x86 build it finds the JRE just fine:
```
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Warning: native libraries are not available for aarch64.dmp
For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) : 

Source : file:///home/keithc/space/openj9/jdmpview/aarch64.dmp
	*0 : PID: 40219 : JRE 11 Linux aarch64-64 (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11aarch64linuxRelease)
```

**Comment by pshipton** [comment] 2020-04-15 18:20
Not a blocking problem then, but something we'll need to fix if possible or document as a limitation if not.

**Comment by pshipton** [comment] 2020-04-15 22:41
The problem seems to be a combination of
- the core file produced by the 0.20.0 test JVM has a different memory layout than other (older) Aarch64 JVMs we looked at
- AArch64 doesn't read some of the memory segments properly. It's not caused by any recent change, and occurs with -Xint. The Milestone 2 JVM has the same problem reading the core. The latest JVM can read core files produced by other (older) AArch64 JVMs where the memory layout is different.
- other platforms, xlinux, osx, can read the Aarch64 core file

**Comment by Akira1Saitoh** [comment] 2020-04-16 00:33
The latest aarch64 VM can read the core file `(openjdk-tests/TKG/test_output_15869240247365/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp)` **on my local machine** (Jetson nano).

```
jetson@jetson:~/work/openj9/work/tests$ ../../jdk/bin/java -version                                                                        openjdk version "11.0.7-internal" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11aarch64linuxRelease)
Eclipse OpenJ9 VM (build v0.20.0-release-05fa2d361, JRE 11 Linux aarch64-64-Bit Compressed References 20200415_8 (JIT enabled, AOT enabled)
OpenJ9   - 05fa2d361
OMR      - d4365f371
JCL      - fe3ef26da9f based on jdk-11.0.7+10)

jetson@jetson:~/work/openj9/work/tests$ ../../jdk/bin/jdmpview -core ./openjdk-tests/TKG/test_output_15869240247365/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp
DTFJView version 4.29.5, using DTFJ version 1.12.29003
Loading image from DTFJ...

Warning : native libraries are not available for ./openjdk-tests/TKG/test_output_15869240247365/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp
For a list of commands, type "help"; for how to use "help", type "help help"
Available contexts (* = currently selected context) :

Source : file:///home/jetson/work/openj9/work/tests/./openjdk-tests/TKG/test_output_15869240247365/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp
        *0 : PID: 40219 : JRE 11 Linux aarch64-64 (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11aarch64linuxRelease)
```

But the same VM cannot read the same core file on `cent7-aarch64-1`.

**Comment by pshipton** [comment] 2020-04-16 00:49
@Akira1Saitoh What is the cpu difference between the machines?

**Comment by Akira1Saitoh** [comment] 2020-04-16 00:54
Jetson nano has only 4 cores. `cent7-aarch64-1` has 96 cores.

**Comment by Akira1Saitoh** [comment] 2020-04-16 01:00
Another difference between those machines is that jetson nano has 4GB memory and `cent7-aarch64-1` has 128GB.

**Comment by knn-k** [comment] 2020-06-18 02:16
This failure is not seen on sanity.functional tests on cent7-aarch64-1.
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.functional_aarch64_linux_Personal_testList_0/

Can this be closed now?

**Comment by 0xdaryl** [comment] 2020-06-18 22:43
We have not been able to reproduce this problem since it was first seen.  Even then, the core file was only unreadable only on the machine it was produced on and not when it was transferred elsewhere.   Not a blocking issue, nor has it been recently.  Recommend closing as @knn-k suggests.

**Closed** 2020-06-25 19:09 UTC
Labels: arch:aarch64, test failure
