### ISSUE TITLE
Investigate JVM signal handling functions

### ISSUE THREAD

**Issue by mgaudet** [eclipse/openj9#54] opened 2017-09-18 17:04 UTC
The implementations of all 3 Signal JVM functions:

* `JVM_RegisterSignal`
* `JVM_FindSignal`
* `JVM_RaiseSignal`

Are questionable. All three need to be validated and completed.

**Comment by DanHeidinga** [comment] 2017-09-18 17:23
The implementations of all 3 Signal JVM functions:
* JVM_RegisterSignal
* JVM_FindSignal
* JVM_RaiseSignal

Are questionable.  All three need to be validated and completed.  My vague understanding is that J9 relies on patches to the JCL code to work around the need for these 3 functions.

**Comment by mgaudet** [comment] 2017-09-18 17:29
I'll re-title this as "Investigate JVM signal handling", as this came from me looking at https://github.com/eclipse/openj9/issues/40

**Comment by mstoodle** [comment] 2017-09-20 16:04
I marked as "enhancement" but if "bug" becomes more appropriate we should update it :)

**Comment by pshipton** [comment] 2017-11-20 22:12
@babsingh is this resolved by #283?

**Comment by babsingh** [comment] 2017-11-20 22:35
@pshipton no. more changes will be required to complete this. currently, the following scenario is not covered.

```
public class SigIntTest extends Thread {

        private static Object monitor = new Object();

        public static void main(String args[]) {
                Runtime.getRuntime().addShutdownHook(new SigIntTest());
                System.out.println("Press CTRL-C to exit - Sends SIGINT signal");

                synchronized (monitor) {
                        try {
                                monitor.wait();
                        } catch (InterruptedException e) {
                                System.out.println("Main thread interrupted");
                        }
                        System.out.println("Terminating main thread correctly");
                }
        }

        public void run() {
                System.out.println("OK ... exiting");
                synchronized (monitor) {
                        monitor.notify();
                }
        }

}
```

**Current behavior:**
```
Press CTRL-C to exit
^C
```

**Expected behavior:**
```
Press CTRL-C to exit
^COK... exiting
Terminating main thread correctly
```

**Comment by DanHeidinga** [comment] 2018-05-01 14:14
Current approach is https://github.com/eclipse/omr/issues/2332

**Comment by pshipton** [comment] 2018-05-03 03:16
The initial changes are delivered to enable signal handling on Windows, Linux, and AIX. There will be more internal changes but the functionality should be working as of now.

Linux/AIX eclipse/omr#2494 #1603 #1642
Windows #1816 not the full functionality but enough for CTRL-C to work

**Comment by babsingh** [comment] 2018-05-03 20:59
Adding @ibm-rtvs

**Comment by pshipton** [comment] 2018-05-04 20:03
The nightly builds from May 4th https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9 should have the shutdown hook updates.

**Comment by SueChaplain** [comment] 2018-05-16 10:05
@pshipton is there more testing to do here or can we remove this issue from the release notes in 0.9.0 please?

**Comment by pshipton** [comment] 2018-05-19 04:54
#1832 is merged.

**Comment by pshipton** [comment] 2018-05-24 18:52
Re #1984, it seems signals are not working as well as hoped.

**Comment by pshipton** [comment] 2018-06-01 23:39
Another fix here https://github.com/eclipse/omr/pull/2611

**Comment by thjaeckle** [comment] 2018-06-05 16:41
Oh noo, the fix won't be in 0.9.0?

**Comment by pshipton** [comment] 2018-06-05 18:33
> Oh noo, the fix won't be in 0.9.0?

The eclipse/omr#2611 fix is delivered and included in 0.9.0. I temporarily used this Issue in the 0.9.0 milestone because I couldn't add the omr issue directly, and was too lazy to create another issue in OpenJ9 to track it. Now that its been merged, any remaining work on signals is deferred until the next release. See the details in the release notes #1759

**Comment by pshipton** [comment] 2018-06-05 18:35
Oops, release notes are here #1996

**Comment by pshipton** [comment] 2018-09-05 16:09
I don't think this is going to be ready for the 0.10.0 release, deferring.

**Comment by babsingh** [comment] 2018-09-05 16:50
@pshipton what's the deadline for OpenJ9 0.10.0 release?

signal handling works on win32 and win64amd. these platforms will be fully supported once https://github.com/eclipse/omr/pull/2908 (signal chaining changes) are merged.

Unix variants (Linux, zOS and AIX) support all signals that are currently used by the JVM. `J9*AsyncHandlerRecord->flags` has 32-bits. Currently, 8-bits are unused. So, we can easily extend support for eight other signals. After the 32-bits are used, then a 64-bit data structure would need to be used for flags. This will require a lot of effort since all the API signatures and implementations across all platforms would need to be updated.

The new OMR signal APIs still need to be implemented for ztpf. Based upon previous discussions, ztpf implementation is not needed to close this PR.

Also, I will soon add signal handling tests in OpenJ9.

**Comment by pshipton** [comment] 2018-09-05 17:45
The deadline is about Sep 14.

**Comment by SueChaplain** [comment] 2018-10-03 10:13
@pshipton The OMR change eclipse/omr#2908 is merged. Presumably there is something else that needs merging to prevents us declaring that signal handling is fixed in 0.10.0? Think it was just Windows that was remaining? Thanks

**Comment by babsingh** [comment] 2018-10-03 12:33
@SueChaplain @pshipton Peter is correct. Windows has fewer signals. Current implementation supports all signals on Windows. Updated doc:

```
Currently, shutdown signals (SIGINT, SIGHUP and SIGTERM) and SIGCONT are fully supported on Unix platforms (pLinux, zLinux, xLinux, AIX and zOS). Support for other POSIX signals is pending. See SunMiscSignalTest.java for the list of signals that need to be supported.
```

**Comment by SueChaplain** [comment] 2018-10-03 12:52
@babsingh Thanks. I've updated the release notes for 0.10.0 accordingly.

**Comment by pdbain-ibm** [comment] 2018-10-03 19:29
Typo above: "using sun.misc.Signal or **dk**.internal.misc.Signal."  should be **jdk**?

**Comment by pshipton** [comment] 2018-10-03 20:38
@pdbain-ibm that line was removed so the typo is gone.
https://github.com/eclipse/openj9/pull/2766

**Comment by SueChaplain** [comment] 2019-03-26 16:30
@pshipton - I think I've lost track of what's remaining here. Can you confirm and let me know the release target please.

**Comment by pshipton** [comment] 2019-03-26 17:41
@SueChaplain there is no real target to complete this work. I'll put it into the 0.15 milestone so we don't loose track of it, but don't be surprised if it moves out further. The release notes should stay as-is.

**Comment by babsingh** [comment] 2019-05-28 19:45
This issue can be closed after https://github.com/eclipse/omr/pull/3921 and https://github.com/eclipse/openj9/pull/5923 are merged. Performing final cross-platform testing.

fyi - @DanHeidinga @pshipton

**Comment by pshipton** [comment] 2019-06-20 12:30
@babsingh please create the doc issue to update the release notes, and then we can close this.

**Comment by pshipton** [comment] 2019-06-25 22:02
There is a docs issue https://github.com/eclipse/openj9-docs/issues/296, this can be closed.

**Closed by pshipton** 2019-06-25 22:02 UTC
Labels: comp:vm, doc:externals, enhancement
