### ISSUE TITLE
ValueTypes: Warnings for ValueBased Classes (JEP 390)

### ISSUE THREAD

**Issue by tajila** [eclipse/openj9#10620] opened 2020-09-16 19:11 UTC
See https://openjdk.java.net/jeps/390

ValueTypes: Warnings for ValueBased Classes (JEP 390)

A new annotation `@ValueBased` will be introduced and applied to classes that may become inline-types in the future. Inline-types disallow synchronization on instances. 

To facilitate migration of `@ValueBased` classes to inline-types, the RI will add an option to fail, warn, or emit a JFR event when a monitor enter occurs on an instance of a `@ValueBased` class. This option will not be turned on by default.

For more info on value based classes see: https://docs.oracle.com/javase/8/docs/api/java/lang/doc-files/ValueBased.html
The `@ValueBased` annotation may be applied to the following classes:
- The primitive wrapper classes in java.lang: Byte, Short, Integer, Long, Float, Double, Boolean, and Character
- The "optional" classes in java.util: Optional, OptionalInt, OptionalLong, and OptionalDouble
- Many classes in the java.time API: Instant, LocalDate, LocalTime, LocalDateTime, ZonedDateTime, ZoneId, OffsetTime, OffsetDateTime, ZoneOffset, Duration, Period, Year, YearMonth, and MonthDay; and, in java.time.chrono, MinguoDate, HijrahDate, JapaneseDate, and ThaiBuddhistDate
- The value-based classes in the jdk.incubator.foreign module
- and more

Openj9 can implement a similar option to warn or fail when a monitor enter occurs on an instance of a `@ValueBased` class. An exception `VirtualMachineError` can be thrown on monitor enter in the case of fail. And a warning message can be printed if the warn is specified. 

Overview:
--------------------
1) @ValueBased will be detected when building the romClass just like @Contended, etc.
    - I believe the full name is jdk.internal.ValueBased (will need to confirm this)

2) A flag will be added to the ramClass J9ClassIsValueBased

3) Add J9VM flags to denote whether an exception will be thrown or an error message will be outputted.
    - J9_EXTENDED_RUNTIME2_VALUE_BASED_WARNING
    - J9_EXTENDED_RUNTIME2_VALUE_BASED_EXCEPTION
 Also add an internalVMFunction helper `BOOLEAN areValueBasedMonitorChecksEnabled()` (this will be called by the JIT). It will return true if either flag is set.

4) Update the locking code (monitorEnter, jitmonitor in cnathelp, etc. see https://github.com/eclipse/openj9/pull/10072 to figure out all the places to change) to detect a mask `(J9ClassIsValueType | J9ClassIsValueBased)` instead of just `J9ClassIsValueType`

5) In the exception path determine which kind of failure it is and throw the appropriate exception

6) Add cmdline option `-XX:addValueBasedClassChecks=[exception|warn]` (name is subject to change)
  This will set the flags in section 3) at VM startup.

**Comment by tajila** [comment] 2020-09-16 19:12
JEP is currently in draft phase. More details to come

**Comment by tajila** [comment] 2020-09-16 19:12
FYI @hangshao0

**Comment by tajila** [comment] 2020-10-14 15:21
@hangshao0 please take a look at this, this will be required for JDK16

**Comment by tajila** [comment] 2020-10-14 15:21
FYI @andrewcraik

**Comment by hangshao0** [comment] 2020-10-14 15:43
> please take a look at this, this will be required for JDK16

Yes, I will look at this.

**Comment by andrewcraik** [comment] 2020-10-14 17:29
Any particular reason to put the flag in the RAM class rather than the ROM class? It will take an extra de-ref to get the flag and check it if it is in the RAM class which will likely increase the overhead...

**Comment by tajila** [comment] 2020-10-14 17:34
> Any particular reason to put the flag in the RAM class rather than the ROM class? It will take an extra de-ref to get the flag and check it if it is in the RAM class which will likely increase the overhead...

The ROMclass is an extra hop assuming you are starting from the object.

```
J9Class *ramClass = J9OBJECT_U32_LOAD(..., (j9object_t)javaObject, offsetof(J9Object, clazz))
J9RomClass *romClass = clazz->romClass
```

**Comment by andrewcraik** [comment] 2020-10-14 19:38
Ok my bad - had that the wrong way around then - as long as we can get direct form the pointer in the object header that is the main. This can probably be done with a trees change in the lowering to avoid platform work.

**Comment by hangshao0** [comment] 2020-10-26 20:03
> Also add an internalVMFunction helper BOOLEAN areValueBasedMonitorChecksEnabled() (this will be called by the JIT). It will return true if either flag is set.

Does JIT need to distinguish between `-XX:addValueBasedClassChecks=exception` and `-XX:addValueBasedClassChecks=warn` ? Behaviors are different between exception and warning.

**Comment by tajila** [comment] 2020-10-26 20:55
I believe the JIT currently test the `ramClass->classFlags` for `J9ClassIsValueType` during monitorEnter. If it is set it calls a VM runtimehelper. If we the JIT does the same with the mask `(J9ClassIsValueType | J9ClassIsValueBased)` then only the VM code needs to know whether it is a "warn" or and "exception"

**Comment by DanHeidinga** [comment] 2020-12-01 14:39
FYI - this has been proposed to target JDK16 and will likely be confirmed for that release.  I know we already had it targeted there but it seems the official targeting is coming soon

**Comment by tajila** [comment] 2020-12-01 15:28
@hangshao0 The @valuebased annotation will likely land in the head repo next week

**Comment by hangshao0** [comment] 2020-12-01 21:26
Noticed in the updated JEP that the new CML options used by RI will be:

`-XX:DiagnoseSyncOnValuedBasedClasses=1` (for error)
`-XX:DiagnoseSyncOnValuedBasedClasses=2` (for warning)

**Comment by hangshao0** [comment] 2020-12-16 23:01
https://github.com/ibmruntimes/openj9-openjdk-jdk16 is created and the @valuebased annotation change has made its way to openj9 branch there. FYI @a7ehuo

**Comment by hangshao0** [comment] 2021-01-21 19:45
FYI @a7ehuo, see
https://github.com/eclipse/openj9/pull/11695#discussion_r561909801
https://github.com/eclipse/openj9/pull/11695#discussion_r562144476

Tobi mentioned that we need the behavior of this JEP even in `J9VM_OPT_VALHALLA_VALUE_TYPES` enabled builds.

**Comment by tajila** [comment] 2021-01-21 20:11
@a7ehuo Please correct me if I'm wrong but the JIT will always call the helper if either `J9ClassIsValueBased` or `J9ClassIsValueType` is set?

**Comment by a7ehuo** [comment] 2021-01-21 20:46
> JIT will always call the helper if either J9ClassIsValueBased or J9ClassIsValueType is set?

Based on https://github.com/eclipse/openj9/pull/11358#discussion_r538767994, as long as either value type or value based is enabled[1], JIT always checks `J9_CLASS_DISALLOWS_LOCKING_FLAGS`  and call the VM helper if either of `J9ClassIsValueBased` or `J9ClassIsValueType` is set. 

Meanwhile, my latest unit test still shows the issue mentioned in https://github.com/eclipse/openj9/pull/11358#discussion_r538913598 the warning/exception message for value based is displayed as value type because they're currently mutually exclusive. 

[1]
https://github.com/eclipse/openj9/blob/339a3a6c0c2bfeab644ab8db8c67b6f91c3aa947/runtime/compiler/x/codegen/J9TreeEvaluator.cpp#L4574-L4577

**Comment by tajila** [comment] 2021-01-21 20:52
> my latest unit test still shows the issue mentioned in #11358 (comment)

Okay, Hang is going to modify the exception code to do a runtime check between the two. Once this is done your test should work.

**Comment by hangshao0** [comment] 2021-01-29 22:17
> Hang is going to modify the exception code to do a runtime check between the two

https://github.com/eclipse/openj9/pull/11766 is merged.

**Closed** 2021-01-29 22:27 UTC
Labels: JEP, comp:vm, project:valhalla

**Comment by hangshao0** [comment] 2021-01-29 22:35
I notice https://openjdk.java.net/jeps/390 is updated today. They had a typo in the option name in that page. They changed `-XX:DiagnoseSyncOnValuedBasedClasses=1/2` to `-XX:DiagnoseSyncOnValueBasedClasses=1/2`.

**Comment by tajila** [comment] 2021-01-31 23:26
> I notice https://openjdk.java.net/jeps/390 is updated today. They had a typo in the option name on that page. They changed -XX:DiagnoseSyncOnValuedBasedClasses=1/2 to -XX:DiagnoseSyncOnValueBasedClasses=1/2 today.

ah okay, can you please update that

**Comment by hangshao0** [comment] 2021-02-01 16:06
> ah okay, can you please update that

The PR https://github.com/eclipse/openj9/pull/11830 to update that has already been merged by Peter.
