### ISSUE TITLE
openjdk11_j9_sanity.system_s390x_linux_xl LambdaLoadTest_ConcurrentScavenge_0 Segmentation error at Module=/lib/s390x-linux-gnu/libc.so.6

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8478] opened 2020-02-01 20:35 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_sanity.system_s390x_linux_xl_Nightly/61/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  08:14:50.423 -   13 JUnit[net.adoptopenjdk.test.streams.TestStreamOperations]  Weighting=1 
LT  08:14:50.468 - Starting thread. Suite=0 thread=0
LT  08:14:50.469 - Starting thread. Suite=0 thread=1
LT  08:14:50.598 - Thread completed. Suite=0 thread=0
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00000000
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=000003FFB10417A0 Handler2=000003FFB0C28098 InaccessibleAddress=FE0003FFA6EA2000
LT  stderr gpr0=000003FFAC14E900 gpr1=FE0003FFA992AA98 gpr2=FE0003FFA992AA98 gpr3=01FFFFFFFFFFF000
LT  stderr gpr4=FE0003FFA6EA1D98 gpr5=01FFFFFFFFFFF000 gpr6=000000000000000F gpr7=000003FFB03FDD00
LT  stderr gpr8=000003FFB03FDA38 gpr9=000003FFB03FDA40 gpr10=000003FFB03FDD00 gpr11=000003FFA992AA90
LT  stderr gpr12=000003FFA98F9D08 gpr13=000003FFA992AA90 gpr14=000003FFAB17B92E gpr15=000003FFB03FD998
LT  stderr psw=000003FFB1C91394 mask=0705200180000000 fpc=00080000 bea=000003FFB1C912B0
LT  stderr fpr0 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
LT  stderr fpr1 4030db74bdbf4976 (f: 3183429888.000000, d: 1.685725e+01)
LT  stderr fpr2 40571d5e450dcf2c (f: 1158532864.000000, d: 9.245888e+01)
LT  stderr fpr3 3fcc616f534e5fcb (f: 1397645312.000000, d: 2.217235e-01)
LT  stderr fpr4 3fe9a2e9c88772cf (f: 3364320000.000000, d: 8.011369e-01)
LT  stderr fpr5 3d772fc771c8d850 (f: 1908988032.000000, d: 1.318008e-12)
LT  stderr fpr6 4030db74bdbf4976 (f: 3183429888.000000, d: 1.685725e+01)
LT  stderr fpr7 bc6f800000000000 (f: 0.000000, d: -1.366095e-17)
LT  stderr fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
LT  stderr fpr9 000003ffac0b4000 (f: 2886418432.000000, d: 2.172228e-311)
LT  stderr fpr10 000003ffb03c0000 (f: 2956722176.000000, d: 2.172263e-311)
LT  stderr fpr11 000003fff48ff279 (f: 4103074304.000000, d: 2.172829e-311)
LT  stderr fpr12 000003ffac2130b8 (f: 2887856384.000000, d: 2.172228e-311)
LT  stderr fpr13 000003ffdd07cfd8 (f: 3708276736.000000, d: 2.172634e-311)
LT  stderr fpr14 0000000000000022 (f: 34.000000, d: 1.679823e-322)
LT  stderr fpr15 000003fff9a7eff8 (f: 4188532736.000000, d: 2.172871e-311)
LT  stderr Module=/lib/s390x-linux-gnu/libc.so.6
LT  stderr Module_base_address=000003FFB1C00000
LT  stderr Target=2_90_20200131_62 (Linux 4.4.0-170-generic)
LT  stderr CPU=s390x (4 logical CPUs) (0x1f723a000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x000003FFB1C91394 [libc.so.6+0x91394])
LT  stderr (0x000003FFAB17B92E [libj9gc29.so+0x17b92e])
LT  stderr (0x000003FFAB1B7002 [libj9gc29.so+0x1b7002])
LT  stderr (0x000003FFAB2162E6 [libj9gc29.so+0x2162e6])
LT  stderr (0x000003FFABD37462 [libj9jit29.so+0xa37462])
LT  stderr ---------------------------------------
LT  stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2020/01/31 08:15:00 - please wait.
LT  stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_sanity.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15804579708035/LambdaLoadTest_ConcurrentScavenge_0/20200131-081448-LambdaLoadTest/results/core.20200131.081500.12914.0001.dmp' in response to an event
```

To rebuild the failed tests in <Jenkins URL>=https://ci.adoptopenjdk.net/job/Grinder, use the following links:
04:17:48  https://ci.adoptopenjdk.net/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=s390x_linux_xl&TARGET=LambdaLoadTest_ConcurrentScavenge_0

**Comment by pshipton** [comment] 2020-02-03 15:43
@amicic @dmitripivkine fyi. It didn't crash directly in the GC, but GC appears involved.

**Comment by dmitripivkine** [comment] 2020-02-03 17:07
I have seen similar failure before. Most likely crashed in Barrier code. I will try to find previous item as well as look to the core file

**Comment by dmitripivkine** [comment] 2020-02-03 17:19
I have seen similar failure https://github.com/eclipse/openj9/issues/8344 but after brief investigation I decided it is a duplicate of https://github.com/eclipse/openj9/issues/8020 fix of each has not been promoted at the moment (Initialization of Concurrent Mark at the time of Concurrent Scavenger running). Seems it was not correct. We are going to look to this.

**Comment by dmitripivkine** [comment] 2020-02-03 17:27
@RSalman Would you please take a look?

**Comment by dmitripivkine** [comment] 2020-02-03 20:22
There is suspicious that seems both crashes (this and https://github.com/eclipse/openj9/issues/8344) copy of large array by multiple threads occur. Investigating.

**Comment by amicic** [comment] 2020-02-05 14:33
This test and MathLoadTest have been run  600 times at various zLinux machines but the problem has not been reproduced, yet.

The theory of a problem in copying large arrays still holds, but not much progress in understanding why.

**Comment by amicic** [comment] 2020-02-05 18:04
Finally 1 failure in 300 grinder jobs: https://ci.eclipse.org/openj9/view/Test/job/Grinder/635/,
but also 500 more in IBM internal machines with no luck.

Average reproducibility is roughly 1/1000.

Current working theory is that we are missing 'volatile' when accessing the word that controls/synchronizes multiple concurrent threads copying a large object.

Working on improving the reproducibility and adding extra instrumentation and diagnosticcs in the code

**Comment by amicic** [comment] 2020-02-06 02:38
I modified the source code so that large arrays chunks are 32x smaller than normal, what increased the probability of the race in suspected code. Then I was able to get 7/800 failure rate.

With added volatile, the failure rate goes back to 0/500.

```
class MM_ForwardedHeader
....
	MMINLINE uintptr_t
	readClassSlot(omrobjectptr_t destinationObjectPtr)
	{
		uintptr_t value = 0;
		if (compressObjectReferences()) {
			value = *(volatile uint32_t*)destinationObjectPtr;
		} else {
			value = *(volatile uintptr_t*)destinationObjectPtr;
		}
		return value;
	}
```

**Closed** 2020-02-10 15:10 UTC
Labels: comp:gc, segfault, test failure
