### ISSUE TITLE
JDK8 JIT Server : MathLoadTest_bigdecimal_ConcurrentScavenge_0 j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ConcurrentMarkingDelegate.cpp:61

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9123] opened 2020-04-03 22:02 UTC
Failure link
------------

From an internal build `Test_openjdk8_j9_sanity.system_x86-64_linux_jit_Nightly/37`:
```
23:34:12  openjdk version "1.8.0_252-internal"
23:34:12  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_04_02_21_44-b00)
23:34:12  Eclipse OpenJ9 VM (build ibm_sdk-4bf0a40282, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200402_38 (JIT enabled, AOT enabled)
23:34:12  OpenJ9   - 4bf0a40282
23:34:12  OMR      - e6f71e920
23:34:12  JCL      - 4f7bf238294 based on jdk8u252-b08)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
MLT 21:58:38.591 -   63 JUnit[net.adoptopenjdk.test.bigdecimal.TestSuite063]  Weighting=1 
MLT 21:58:38.643 - Starting thread. Suite=0 thread=0
MLT 21:58:38.647 - Starting thread. Suite=0 thread=1
MLT 21:58:38.648 - Starting thread. Suite=0 thread=2
MLT stderr 0000000001955000: J9_INVALID_OBJECT in thread load-2
MLT stderr 0000000001955000:	O-Slot=00007F64D28B95B8
MLT stderr 0000000001955000:	O-Slot value=FFFFFFFFFFFFFFFF
MLT stderr 0000000001955000:	PC=00007F65298AE4A4
MLT stderr 0000000001955000:	framesWalked=1
MLT stderr 0000000001955000:	arg0EA=000000000196A6A8
MLT stderr 0000000001955000:	walkSP=000000000196A5E8
MLT stderr 0000000001955000:	literals=0000000000000000
MLT stderr 0000000001955000:	jitInfo=00007F65286C7EB8
MLT stderr 0000000001955000:	method=00000000016D17C8 (.newInstance([Ljava/lang/Object;)Ljava/lang/Object;) (JIT)
MLT stderr 0000000001955000:	stack=0000000001963C40-000000000196AC40
MLT stderr 04:58:45.904 0x1955000    j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/ConcurrentMarkingDelegate.cpp:61: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(data->env)))
MLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/04/02 21:58:45 - please wait.

MathLoadTest_bigdecimal_ConcurrentScavenge_0_FAILED
```

To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-64_linux&TARGET=MathLoadTest_bigdecimal_ConcurrentScavenge_0

**Comment by dmitripivkine** [comment] 2020-04-03 22:33
@JasonFengJ9 It would be convenient if you will include link to failed build directly, not just mentioning it. It might simplify access to preserved artifacts

**Comment by dmitripivkine** [comment] 2020-04-03 22:40
@a7ehuo  Looks like it is a duplicate of https://github.com/eclipse/openj9/issues/8789
I will take a look for details but reassign it to JIT.
There is the problem in JIT frame any way

**Comment by JasonFengJ9** [comment] 2020-04-03 23:46
Slacked the internal link to @dmitripivkine 
Generally we don't post a link that is not accessible to everybody.

**Comment by dmitripivkine** [comment] 2020-04-06 18:36
Looks like very similar failure as https://github.com/eclipse/openj9/issues/8789.
I did not debug it on low level to track how we got `O-Slot value=FFFFFFFFFFFFFFFF` but because it is `.newInstance()` method I would suspect unloaded class around. Unfortunately I can not check previous Global GC activities (it is out of scope of snap traces already). However I can see number of unloaded classes around including `sun/reflect/GeneratedConstructorAccessor*` type (for example `!j9class 0x016AC200`). `-Xcheck:gc` reports about few of them discovered instances in the heap, but because this is post-crash dump we can not recognize is there alive object uses unloaded class (an error case) or this is a dead object (not a problem, unloaded class is required to walk dark matter)

**Comment by dmitripivkine** [comment] 2020-04-07 16:32
Just for record - problem occur because class `!j9class 0x16D1500` is unloaded:
```
> !j9method 0x16d17c8  <--- method from assertion
J9Method at 0x16d17c8 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00007F64B8034860
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x00000000016D16B0 (flags = 0x0)
	0x10: void* methodRunAddress = !j9x 0x0000000000000006
	0x18: void* extra = !j9x 0x00000000000000A7
}
Signature: .newInstance([Ljava/lang/Object;)Ljava/lang/Object; !bytecodes 0x00000000016D17C8
ROM Method: !j9rommethod 0x00007F64B803484C
Next Method: !j9method 0x00000000016D17E8
> !j9constantpool 0x00000000016D16B0
J9ConstantPool at 0x16d16b0 {
  Fields for J9ConstantPool:
	0x0: struct J9Class* ramClass = !j9class 0x00000000016D1500 //
	0x8: struct J9ROMConstantPoolItem* romConstantPool = !j9romconstantpoolitem 0x00007F64B8034790
}
> !j9class 0x00000000016D1500
J9Class at 0x16d1500 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
	0x8: struct J9ROMClass* romClass = !j9romclass 0x00007F64B80346F0
	0x10: void** superclasses = !j9x 0x00000000016D17E8
	0x18: UDATA classDepthAndFlags = 0x00000000080E0003 (135135235) <--- flag 0x0000000008000000 means class is unloaded
	0x20: U32 classDepthWithFlags = 0x00000000 (0)
	0x24: U32 classFlags = 0x00002000 (8192)
	0x28: struct J9ClassLoader* classLoader = !j9classloader 0x00007F654008D498
	0x30: struct J9Object* classObject = !j9object 0xFFFFFFFFFFFFFFFF<FAULT>
	0x38: volatile UDATA initializeStatus = 0x0000000000000001 (1)
	0x40: struct J9Method* ramMethods = !j9method 0x00000000016D17A8 // .<FAULT>
	0x48: UDATA* ramStatics = !j9x 0x0000000000000000
	0x50: struct J9Class* arrayClass = !j9class 0x0000000000000000
	0x58: UDATA totalInstanceSize = 0x0000000000000004 (4)
	0x60: struct J9ITable* lastITable = !j9itable 0x000000000161ECA0
	0x68: UDATA* instanceDescription = !j9x 0x0000000000000001
	0x70: UDATA* instanceLeafDescription = !j9x 0x0000000000000001
	0x78: UDATA instanceHotFieldDescription = 0x0000000000000000 (0)
	0x80: UDATA selfReferencingField1 = 0x0000000000000000 (0)
	0x88: UDATA selfReferencingField2 = 0x0000000000000000 (0)
	0x90: struct J9Method* initializerCache = !j9method 0x00000000016D17A8 // .<FAULT>
	0x98: UDATA romableAotITable = 0x00007F653DD93860 (140072806070368)
	0xa0: UDATA packageID = 0x00007F64B80346F1 (140070560679665)
	0xa8: struct J9Module* module = !j9module 0x0000000000000000
	0xb0: struct J9Class* subclassTraversalLink = !j9class 0x00000000016D1500 //
	0xb8: struct J9Class* subclassTraversalReverseLink = !j9class 0x00000000016D1500 //
	0xc0: void** iTable = !j9x 0x000000000161ECA0
	0xc8: UDATA castClassCache = 0x0000000001624600 (23217664)
	0xd0: void** jniIDs = !j9x 0x0000000000000000
	0xd8: UDATA lockOffset = 0x0000000000000004 (4)
	0xe0: U32 paddingForGLRCounters = 0x00000000 (0)
	0xe4: U16 reservedCounter = 0x0000 (0)
	0xe6: U16 cancelCounter = 0x0000 (0)
	0xe8: UDATA newInstanceCount = 0x00000000000003E8 (1000)
	0xf0: IDATA backfillOffset = 0x0000000000000008 (8)
	0xf8: struct J9Class* replacedClass = !j9class 0x0000000000000000
	0x100: UDATA finalizeLinkOffset = 0x0000000000000000 (0)
	0x108: struct J9Class* nextClassInSegment = !j9class 0x0000000000000000
	0x110: UDATA* ramConstantPool = !j9x 0x00000000016D16B0
	0x118: struct J9Object** callSites = !j9x 0x0000000000000000
	0x120: struct J9Object** methodTypes = !j9x 0x0000000000000000
	0x128: struct J9Object** varHandleMethodTypes = !j9x 0x0000000000000000
	0x130: struct J9VMCustomSpinOptions* customSpinOption = !j9vmcustomspinoptions 0x0000000000000000
	0x138: void** staticSplitMethodTable = !j9x 0x0000000000000000
	0x140: void** specialSplitMethodTable = !j9x 0x0000000000000000
	0x148: struct J9JITExceptionTable* jitMetaDataList = !j9jitexceptiontable 0x0000000000000000
	0x150: struct J9Class* gcLink = !j9class 0x00000000016D1A00 // <FAULT>
	0x158: struct J9Class* hostClass = !j9class 0x00000000016D1500 //
	0x160: struct J9FlattenedClassCache* flattenedClassCache = !j9flattenedclasscache 0x0000000000000000
}
Class name:
To view static fields, use !j9statics 0x00000000016D1500
To view instance shape, use !j9classshape 0x00000000016D1500
>```

**Comment by dmitripivkine** [comment] 2020-04-07 18:30
There is no theory how class unloading management (in Global GC) can be impacted by Concurrent Scavenger (in Local GC). It is possible that there is no such logical impact but factors like timing.

I can observe a quite large time interval between Class Unloading event in previous Global GC and failed attempt to use this class. So (except case thread was dormant for seconds) it does not look as a race (like "load class" - "GC" - "create object instance")

There are two possibilities for this kind of failure:
- class was not expected to be unloaded
If it is a case we need to know what actions are taken to prevent class unloading. Is there difference in behaviour for JIT Server?
- unloaded class was used by mistake
In this case the question is what was missed at class unloading event handling on JIT side.

**Comment by JasonFengJ9** [comment] 2020-04-29 00:34
Another occurrence at `Test_openjdk11_j9_sanity.system_x86-64_linux_jit_Nightly/62`.

**Comment by dmitripivkine** [comment] 2020-04-30 17:29
> Another occurrence at `Test_openjdk11_j9_sanity.system_x86-64_linux_jit_Nightly/62`.

```
02:23:15.563038000  0x479800 j9mm.481             Exception  * J9_INVALID_OBJECT in thread load-0
02:23:15.563051000  0x479800 j9mm.482             Exception  * O-Slot=0x7f8fe295d508
02:23:15.563064000  0x479800 j9mm.483             Exception  * O-Slot value=0xffffffffffffffff
02:23:15.563076000  0x479800 j9mm.484             Exception  * PC=0x7f90231256f1
02:23:15.563087000  0x479800 j9mm.485             Exception  * framesWalked=1
02:23:15.563099000  0x479800 j9mm.486             Exception  * arg0EA=0x496728
02:23:15.563110000  0x479800 j9mm.487             Exception  * walkSP=0x496640
02:23:15.563122000  0x479800 j9mm.488             Exception  * literals=0x0
02:23:15.563134000  0x479800 j9mm.489             Exception  * jitInfo=0x7f9020622c78
02:23:15.563147000  0x479800 j9mm.490             Exception  * method=0x476fd8 (.) (JIT) <--- j9method
02:23:15.563160000  0x479800 j9mm.493             Exception  * stack=0x48fc78-0x496cc0
02:23:15.563161000  0x479800 j9mm.491             Exit       *<StackSlotValidator::reportStackSlot
02:23:15.563163000  0x479800 j9mm.479             Assert     * ** ASSERTION FAILED ** at ../../gc_glue_java/ConcurrentMarkingDelegate.cpp:61: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(data->env)))

> !j9method 0x476fd8
J9Method at 0x476fd8 {
  Fields for J9Method:
	0x0: U8* bytecodes = !j9x 0x00007F8FBC0368E0
	0x8: struct J9ConstantPool* constantPool = !j9constantpool 0x0000000000476EC0 (flags = 0x0)
	0x10: void* methodRunAddress = !j9x 0x0000000000000006
	0x18: void* extra = !j9x 0x000000000000009D
}
Signature: <FAULT>
ROM Method: !j9rommethod 0x00007F8FBC0368CC
Next Method: !j9method 0x0000000000476FF8
> !j9constantpool 0x0000000000476EC0
J9ConstantPool at 0x476ec0 {
  Fields for J9ConstantPool:
	0x0: struct J9Class* ramClass = !j9class 0x0000000000476D00 // <FAULT> <--- j9class
	0x8: struct J9ROMConstantPoolItem* romConstantPool = !j9romconstantpoolitem 0x00007F8FBC036810
}
> !j9class 0x0000000000476D00
J9Class at 0x476d00 {
  Fields for J9Class:
	0x0: UDATA eyecatcher = 0x0000000099669966 (2573637990)
	0x8: struct J9ROMClass* romClass = !j9romclass 0x00007F8FBC036760
	0x10: void** superclasses = !j9x 0x0000000000476FF8
	0x18: UDATA classDepthAndFlags = 0x00000000080E0003 (135135235) <--- unloaded
	0x20: U32 classDepthWithFlags = 0x00000000 (0)
	0x24: U32 classFlags = 0x00002000 (8192)
```

**Comment by a7ehuo** [comment] 2020-05-07 19:58
Tried the build as below on `04/30` in Grinder, FR: `1/100`. 
```
18:52:20  JITServer is ready to accept incoming requests
18:52:20  openjdk version "1.8.0_262-internal"
18:52:20  OpenJDK Runtime Environment (build 1.8.0_262-internal-jenkins_2020_04_30_14_10-b00)
18:52:20  Eclipse OpenJ9 VM (build master-ef109f7c2, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200430_1436 (JIT enabled, AOT enabled)
18:52:20  OpenJ9   - ef109f7c2
18:52:20  OMR      - f2285166b
18:52:20  JCL      - ed7c83cea53 based on jdk8u262-b01)
```

**Comment by adamfarley** [comment] 2020-08-06 12:11
Could the below error be related to this? Or #9424.

0000000000198200: Invalid class pointer in thread MainThread
0000000000198200:	O-Slot=00000000001E6858
0000000000198200:	O-Slot value=00000000FFFFB578
0000000000198200:	PC=0000FFFF964A43A8
0000000000198200:	framesWalked=1
0000000000198200:	arg0EA=00000000001E6A40
0000000000198200:	walkSP=00000000001E65D8
0000000000198200:	literals=0000000000000000
0000000000198200:	jitInfo=0000FFFF5D0547F8
0000000000198200:	method=00000000002E4A30 (org/testng/Assert.assertEquals(Ljava/util/Collection;Ljava/util/Collection;Ljava/lang/String;)V) (JIT)
0000000000198200:	stack=00000000001E1CB8-00000000001E7570
21:43:59.866 0x18b900    j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/MarkingSchemeRootMarker.cpp:48: ((MM_StackSlotValidator(0, object, stackLocation, walkState).validate(_env)))

URL: https://trss.adoptopenjdk.net/output/test?id=5f2b3c660bec7975ae1130ad

**Comment by mpirvu** [comment] 2020-08-06 12:37
@adamfarley The error here was found during a test using JITServer and it is looked at as a possible JITServer fault. The error in the link mentioned above has the same symptom, but the test does not use JITServer, hence it's possible that the root cause is the same and JITServer just makes it appear more often.

**Comment by dmitripivkine** [comment] 2020-09-25 19:01
This problem has been solved and item can be closed

**Closed by dmitripivkine** 2020-09-25 19:01 UTC
Labels: comp:jitserver, test failure
