### ISSUE TITLE
openjdk9-openj9 jdk_lang test failures

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#1430] opened 2018-03-13 17:19 UTC
Test results from the openjdk regression test group run against the nightly openjdk9-openj9 build at AdoptOpenJDK: Test results: passed: 575; failed: 128; error: 6
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/artifact/jvmtest/openjdk_regression/work/java/lang/

java/lang/ref/EarlyTimeout.java
java/lang/Appendable/Basic.java
java/lang/Class/GenericStringTest.java
java/lang/Class/GetModuleTest.java
java/lang/Class/forName/NonJavaNames.sh
java/lang/Class/forName/arrayClass/ExceedMaxDim.java
java/lang/Class/forName/modules/TestDriver.java
java/lang/Class/getResource/ResourcesTest.java
java/lang/ClassLoader/EndorsedDirs.java
java/lang/ClassLoader/ExtDirs.java
java/lang/ClassLoader/LibraryPathProperty.java
java/lang/ClassLoader/forNameLeak/ClassForNameLeak.java
java/lang/ModuleLayer/BasicLayerTest.java
java/lang/ModuleTests/AddExportsTest.java
java/lang/ModuleTests/addXXX/Driver.java
java/lang/ProcessBuilder/Basic.java
java/lang/SecurityManager/modules/CustomSecurityManager.sh
java/lang/StackTraceElement/ModuleFrames.java
java/lang/StackTraceElement/PublicConstructor.java
java/lang/StackTraceElement/SerialTest.java
java/lang/StackWalker/Basic.java
java/lang/StackWalker/DumpStackTest.java
java/lang/StackWalker/LocalsAndOperands.java
java/lang/StackWalker/ReflectionFrames.java
java/lang/StackWalker/EmbeddedStackWalkTest.java
java/lang/StackWalker/SecurityExceptions.java
java/lang/StackWalker/StackWalkTest.java
java/lang/StackWalker/VerifyStackTrace.java
java/lang/String/CaseInsensitiveComparator.java
java/lang/String/CompactString/VMOptionsTest.java
java/lang/String/EqualsIgnoreCase.java
java/lang/StringBuffer/CompactStringBuffer.java
java/lang/StringBuffer/CompactStringBufferSerialization.java
java/lang/StringBuffer/Exceptions.java
java/lang/StringBuffer/TestSynchronization.java
java/lang/StringBuilder/CompactStringBuilder.java
java/lang/StringBuilder/CompactStringBuilderSerialization.java
java/lang/StringBuilder/Exceptions.java
java/lang/System/Logger/custom/CustomLoggerTest.java
java/lang/System/Logger/default/DefaultLoggerTest.java
java/lang/System/LoggerFinder/BaseLoggerFinderTest/BaseLoggerFinderTest.java
java/lang/System/LoggerFinder/DefaultLoggerFinderTest/DefaultLoggerFinderTest.java
java/lang/System/LoggerFinder/internal/BaseDefaultLoggerFinderTest/BaseDefaultLoggerFinderTest.java
java/lang/System/LoggerFinder/internal/BaseLoggerBridgeTest/BaseLoggerBridgeTest.java
java/lang/System/LoggerFinder/internal/LoggerBridgeTest/LoggerBridgeTest.java
java/lang/System/LoggerFinder/internal/LoggerFinderLoaderTest/LoggerFinderLoaderTest.java
java/lang/System/LoggerFinder/internal/backend/LoggerFinderBackendTest.java
java/lang/System/LoggerFinder/jdk/DefaultLoggerBridgeTest/DefaultLoggerBridgeTest.java
java/lang/System/SecurityRace.java
java/lang/System/Versions.java
java/lang/Thread/UncaughtExceptions.sh
java/lang/ThreadGroup/SetMaxPriority.java
java/lang/Throwable/SuppressedExceptions.java
java/lang/annotation/AnnotationsInheritanceOrderRedefinitionTest.java
java/lang/annotation/loaderLeak/Main.java
java/lang/annotation/typeAnnotations/TestConstructorParameterTypeAnnotations.java
java/lang/invoke/7157574/Test7157574.java
java/lang/invoke/8147078/Test8147078.java
java/lang/invoke/8177146/TestMethodHandleBind.java
java/lang/invoke/AccessControlTest.java
java/lang/invoke/ArrayConstructorTest.java
java/lang/invoke/CustomizedLambdaFormTest.java
java/lang/invoke/DropLookupModeTest.java
java/lang/invoke/ExplicitCastArgumentsTest.java
java/lang/invoke/FindAccessTest.java
java/lang/invoke/LFCaching/LFMultiThreadCachingTest.java
java/lang/invoke/LFCaching/LFSingleThreadCachingTest.java
java/lang/invoke/LambdaFormTest.java
java/lang/invoke/LoopCombinatorTest.java
java/lang/invoke/MethodHandles/TestCatchException.java
java/lang/invoke/MethodHandlesTest.java
java/lang/invoke/PrivateInvokeTest.java
java/lang/invoke/ProtectedMemberDifferentPackage/Test.java
java/lang/invoke/RevealDirectTest.java
java/lang/invoke/RicochetTest.java
java/lang/invoke/SpreadCollectTest.java
java/lang/invoke/TryFinallyTest.java
java/lang/invoke/VarHandles/VarHandleTestAccessBoolean.java
java/lang/invoke/VarHandles/VarHandleTestAccessByte.java
java/lang/invoke/VarHandles/VarHandleTestAccessChar.java
java/lang/invoke/VarHandles/VarHandleTestAccessInt.java
java/lang/invoke/VarHandles/VarHandleTestAccessLong.java
java/lang/invoke/VarHandles/VarHandleTestAccessModeMethodNames.java
java/lang/invoke/VarHandles/VarHandleTestAccessShort.java
java/lang/invoke/VarHandles/VarHandleTestAccessString.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsChar.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsInt.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsLong.java
java/lang/invoke/VarHandles/VarHandleTestByteArrayAsShort.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessBoolean.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessByte.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessChar.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessDouble.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessFloat.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessInt.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessLong.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessShort.java
java/lang/invoke/VarHandles/VarHandleTestMethodHandleAccessString.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeBoolean.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeByte.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeChar.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeDouble.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeFloat.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeInt.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeLong.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeShort.java
java/lang/invoke/VarHandles/VarHandleTestMethodTypeString.java
java/lang/invoke/VarHandles/VarHandleTestReflection.java
java/lang/invoke/VarHandles/accessibility/TestFieldLookupAccessibility.java
java/lang/invoke/VarargsArrayTest.java
java/lang/invoke/lambda/InheritedMethodTest.java
java/lang/invoke/lambda/LambdaStackTrace.java
java/lang/invoke/lambda/LogGeneratedClassesTest.java
java/lang/invoke/modules/Driver.java
java/lang/ref/CleanerTest.java
java/lang/ref/FinalizerHistogramTest.java
java/lang/ref/NullQueue.java
java/lang/ref/OOMEInReferenceHandler.java
java/lang/ref/ReachabilityFenceTest.java
java/lang/reflect/AccessibleObject/CanAccessTest.java
java/lang/reflect/AccessibleObject/ModuleSetAccessibleTest.java
java/lang/reflect/AccessibleObject/TrySetAccessibleTest.java
java/lang/reflect/DefaultMethodMembers/FilterNotMostSpecific.java
java/lang/reflect/Parameter/InnerClassToString.java
java/lang/reflect/Proxy/ProxyForMethodHandle.java
java/lang/reflect/Proxy/ProxyLayerTest.java
java/lang/reflect/Proxy/ProxyModuleMapping.java
java/lang/reflect/PublicMethods/PublicMethodsTest.java
jdk/internal/misc/Unsafe/CopySwap.java
jdk/internal/misc/VM/GetNanoTimeAdjustment.java
jdk/internal/misc/VM/RuntimeArguments.java
jdk/internal/reflect/CallerSensitive/CheckCSMs.java
jdk/internal/reflect/constantPool/ConstantPoolTest.java
sun/misc/SunMiscSignalTest.java
sun/reflect/ReflectionFactory/ReflectionFactoryTest.java
vm/verifier/VerifyProtectedConstructor.java

**Comment by sophia-guo** [comment] 2018-03-16 15:00
s390 specifc:
java/lang/ClassLoader/Assert.java
java/lang/String/CaseConvertSameInstance.java

https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_s390x_linux/3/artifact/jvmtest/openjdk_regression/work/java/lang/

CaseConvertSameInstance.jtr
Assert.jtr

**Comment by JasonFengJ9** [comment] 2018-03-23 14:26
Will look at this.

**Comment by JasonFengJ9** [comment] 2018-03-23 21:30
Here is a `java/lang/Class/GenericStringTest.java` failure as per
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/31/testReport/junit/java_lang_Class_GenericStringTest/java/GenericStringTest/
```
Unexpected Class.toGenericString output; expected 'java.lang.String[]', got 'public abstract final class [Ljava.lang.String;'.
Unexpected Class.toGenericString output; expected 'java.lang.String[][]', got 'public abstract final class [[Ljava.lang.String;'.
Unexpected Class.toGenericString output; expected 'int[][]', got 'public abstract final class [[I'.
Unexpected Class.toGenericString output; expected 'java.util.Map<K,V>[]', got 'public abstract final class [Ljava.util.Map;'.
Unexpected Class.toGenericString output; expected 'java.util.Map<K,V>[][]', got 'public abstract final class [[Ljava.util.Map;'.
java.lang.RuntimeException
	at GenericStringTest.main(GenericStringTest.java:70)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@9-adoptopenjdk/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@9-adoptopenjdk/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@9-adoptopenjdk/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@9-adoptopenjdk/Method.java:564)
	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:229)
	at java.lang.Thread.run(java.base@9-adoptopenjdk/Thread.java:835)
```
However I can't reproduce it with latest `OpenJ9` builds (AdoptOpenJDK `jdk-9.0.4+12` or latest OpenJ9 build) against latest `Java 9 JCK b68`.
```
	Mar 23, 2018, 5:13:30 PM Running api/java_lang/Class/togenericstring/index2.html#ToGenericString
	Mar 23, 2018, 5:13:31 PM Finished api/java_lang/Class/togenericstring/index2.html#ToGenericString Passed. test cases: 12; all passed
	Pass: 33  Fail: 0  Error: 0  Not-Run: 47    
```

Will attempt other sub-tests.

**Comment by JasonFengJ9** [comment] 2018-03-27 14:01
Not able to reproduce the same failures.
Latest AdoptOpenJDK JCK test seems in state of `Finished: UNSTABLE` at https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_j9_openjdktest_x86-64_linux/42/console.

**Comment by sophia-guo** [comment] 2018-03-27 14:11
@JasonFengJ9 tests are disabled. To reproduce you can launch a personal build : https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Personal-Test-Build-on-Jenkins

**Comment by smlambert** [comment] 2018-06-20 15:44
I am not sure that this issue is a comp:test one, though it is labelled that way.  

Were you able to rerun some tests here to reproduce?

**Comment by JasonFengJ9** [comment] 2018-08-07 15:26
Somehow missed Shelley's question here, I recall there was a setup issue and can't reproduce. Will have another look.

**Comment by smlambert** [comment] 2019-02-19 18:56
I am going to close this, as there are individual issues opened for the failures in LTS versions (jdk8,jdk11), and jdk9 is now retired.

**Closed by smlambert** 2019-02-19 18:56 UTC
Labels: comp:test, jdk9, test failure
