### ISSUE TITLE
-XX:+UseContainerSupport doesn't set max heap size when -Xms is set

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#10202] opened 2020-07-20 16:57 UTC
Related to https://github.com/eclipse/openj9/issues/10200, the https://www.eclipse.org/openj9/docs/xxusecontainersupport/ feature didn't appear to be working to set the default maximum java heap size to 75% of the container memory limit. It was discovered this was due to -Xms being set. Although this is documented https://www.eclipse.org/openj9/docs/xxinitialrampercentage/, it's not clear why -Xms affects setting the maximum heap size.

It seems the documentation is wrong anyway, and perhaps -Xms only affects -XX:+UseContainerSupport.
If nothing else, we should update https://www.eclipse.org/openj9/docs/xxusecontainersupport/ to mention the -Xms limitation.

Clearly -Xms doesn't affect -XX:MaxRAMPercentage in this test run on Java 11.

java -XX:MaxRAMPercentage=75 -Xms1m
> -Xmx12323328K

java -XX:MaxRAMPercentage=25 -Xms1m
> -Xmx4107776K

**Comment by pshipton** [comment] 2020-07-20 16:58
@dmitripivkine @amicic please take a look.

**Comment by dmitripivkine** [comment] 2020-07-24 14:47
By design:
`-XX:InitialRAMPercentage` is applied if `-Xms` is not specified https://github.com/eclipse/openj9/blob/25ba9af5f5ea3f672c194bc40ab1f900c4e1d2dd/runtime/gc_modron_startup/mminit.cpp#L2882

`-XX:MaxRAMPercentage` is applied if `-Xmx` is not specified
https://github.com/eclipse/openj9/blob/25ba9af5f5ea3f672c194bc40ab1f900c4e1d2dd/runtime/gc_modron_startup/mminit.cpp#L2887

There is no cross interference between (`-XX:MaxRAMPercentage` and `-Xms`) as well as (`-XX:InitialRAMPercentage` and `-Xmx`)

I believe this logic is reasonable. The only part needs to be improved is a documentation

**Comment by DanHeidinga** [comment] 2020-08-04 18:38
> I believe this logic is reasonable. The only part needs to be improved is a documentation

@dmitripivkine will the doc PR be opened before the 0.22.0 code split on Aug 9?  Want to confirm whether this will make the release

**Comment by dmitripivkine** [comment] 2020-08-04 19:09
> > I believe this logic is reasonable. The only part needs to be improved is a documentation
> 
> @dmitripivkine will the doc PR be opened before the 0.22.0 code split on Aug 9? Want to confirm whether this will make the release

Can this doc change be postponed to next release if there is no objection please?

**Comment by DanHeidinga** [comment] 2020-08-04 20:23
If we can't contain it, then it can be moved out.

@SueChaplain can you confirm the last date for doc changes for 0.22.0 (Sept Java 15 release)?  As the docs are a separate repo, I'm now wondering if the doc changes need to be in for the code split on Aug 9.

**Comment by SueChaplain** [comment] 2020-08-05 09:18
@DanHeidinga - we are aiming to complete the docs for MS2 on 2nd Sept, but we can go closer to the GA for last minute changes. As docs is a separate repo we don't need to tie the docs to the code split.

**Comment by DanHeidinga** [comment] 2020-08-05 12:35
@dmitripivkine Does the adapted timeline from Sue make this containable in the 0.22.0 release?

**Comment by dmitripivkine** [comment] 2020-08-05 13:22
Ok, we will try to address this in next two weeks.

**Comment by dmitripivkine** [comment] 2020-08-11 17:58
https://github.com/eclipse/openj9-docs/pull/617

**Comment by dmitripivkine** [comment] 2020-09-02 15:58
Document change request has been merged

**Closed by dmitripivkine** 2020-09-02 15:58 UTC
Labels: comp:gc, doc:externals, userRaised
