### ISSUE TITLE
Use openjdk-api-v3 to download bootjdk from AdoptOpenJDK

### ISSUE THREAD

**Issue by sophia-guo** [eclipse/openj9#9365] opened 2020-04-24 20:59 UTC
[ AdoptOpenJDK API v2 has been deprecated and will be removed. If you are using v2 please move to the latest version (documented below) as soon as possible](https://github.com/AdoptOpenJDK/openjdk-api-v3)

For example https://github.com/eclipse/openj9/blob/master/buildenv/docker/jdk14/x86_64/ubuntu16/Dockerfile#L86

Dockerfile is used also like a recipe card to determine the software dependencies that must be installed on the system. It would be better to do the update accordingly.

Also for jdk14 bootjdk should be jdk13 or jdk14 instead of jdk12.

**Comment by pshipton** [comment] 2020-04-24 22:32
@keithc-ca how far off is the script you are working on to replace the docker files?

**Comment by keithc-ca** [comment] 2020-04-25 01:10
I think the script is finished. We can make refinements to things like option names, etc. as people think of improvements. I have started updating documents that refer to the existing Dockerfiles, but I suppose the remaining part of that could be deferred.

Thoughts?

**Comment by pshipton** [comment] 2020-04-26 19:36
It would be good to remove the existing Dockerfiles and move to the script since many of the existing Dockerfiles are broken in various ways. I can help update documents.

**Comment by fjeremic** [comment] 2020-04-26 23:29
I just got bit by this on the s390 Dockerfiles in #9363. Those have been fixed but the issue is still present elsewhere. I agree with @pshipton that we need a way to keep those Dockerfiles maintained.

**Comment by keithc-ca** [comment] 2020-04-27 12:44
Ok, I'll make it a priority to get a pull request open this week.

**Comment by keithc-ca** [comment] 2020-04-29 20:58
I believe the concerns here are addressed by #9371.

**Closed by keithc-ca** 2020-04-29 20:58 UTC
Labels: userRaised
