### ISSUE TITLE
JTReg Test Failure: java/lang/Class/getMethods/StarInheritance.java

### ISSUE THREAD

**Issue by adam-thorpe** [eclipse/openj9#8255] opened 2020-01-09 09:48 UTC
Failure link
------------
Link to job: https://ci.adoptopenjdk.net/user/adam-thorpe/my-views/view/Nightly%20test%20openjdk%20openJ9/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac/115/
JDK: 8 only
Platforms: all
JVM: openj9 only

Optional info
-------------
- intermittent failure (yes|no): no
- regression or new test: new failing test (as in its an old test but just started failing)

Failure output (captured from console output)
---------------------------------------------
```
Test 4
  found methods: [public abstract void B4.m()]
  expected locations: [interface B4, interface D4]
java.lang.RuntimeException: found = 1; expected = 2
	at StarInheritance.test(StarInheritance.java:68)
	at StarInheritance.main(StarInheritance.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainActionHelper$AgentVMRunnable.run(MainActionHelper.java:298)
	at java.lang.Thread.run(Thread.java:821)

JavaTest Message: Test threw exception: java.lang.RuntimeException
JavaTest Message: shutting down test
```
Test sets up an inheritance structure and tests how many signatures of a specific method m there are. For Test 4:
```
interface A4 extends B4, C4 {}
interface B4 extends D4 { void m(); }
interface C4 extends D4 {}
interface D4 { void m(); }
```
It seems the method m is not being extended twice as it should be in this case. Note the structure from test 3:
```
interface A3 extends B3, C3 {}
interface B3 extends D3 { void m(); }
interface C3 extends D3 { void m(); }
interface D3 { void m() ; }
```
Returns both methods correctly, so it would seem that the method m is inherited from D4 to C4 but then not passed to A4.

**Comment by pshipton** [comment] 2020-01-09 14:16
> new failing test (as in its an old test but just started failing)

That is what "regression" means. @adam-thorpe Do you have the -version information for the last passing run? I version from the failing test link is as follows.

```
06:55:53  openjdk version "1.8.0_242"
06:55:53  OpenJDK Runtime Environment (build 1.8.0_242-202001090431-b06)
06:55:53  Eclipse OpenJ9 VM (build master-9771d87a4, JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200109_424 (JIT enabled, AOT enabled)
06:55:53  OpenJ9   - 9771d87a4
06:55:53  OMR      - 4d5712b26
06:55:53  JCL      - a9857e68ed based on jdk8u242-b06)
```

@DanHeidinga fyi

**Comment by pshipton** [comment] 2020-01-09 14:17
Tentatively assigned to the 0.18 milestone until we determine if the regression affects this release.

**Comment by adam-thorpe** [comment] 2020-01-09 14:24
Last passing build was: 
```
JRE 1.8.0 Mac OS X amd64-64-Bit Compressed References 20200107_422 (JIT enabled, AOT enabled)
20:35:59  OpenJ9   - ef79628fd
20:35:59  OMR      - 4d5712b26
20:35:59  JCL      - c978aa83 based on jdk8u242-b05
```

**Comment by DanHeidinga** [comment] 2020-01-09 14:24
@theresa-m Can you take a look at this?

**Comment by theresa-m** [comment] 2020-01-09 14:39
Yes looking into it.

**Comment by theresa-m** [comment] 2020-01-09 17:22
@DanHeidinga https://github.com/eclipse/openj9/pull/7788 and https://github.com/eclipse/openj9/pull/8134 should be reverted.

I misdiagnosed the `Class.getMethods` test failure from https://github.com/eclipse/openj9/issues/7623

The real problem with the https://github.com/eclipse/openj9/issues/7623 getMethods failure is that not all methods in the getMethods list are being looked at for replacement.

```
    interface X1 { default void x() {} }
    interface X2 extends X1 { void x(); }
    interface X3 extends X2, X1 { default void x() {} }
    interface X41 extends X1, X2, X3 { }
```

- getMethod iterates through superinterfaces in order
- since inherited abstract methods are not hidden in Java 8, {X1.m, X2.m} to intermediate list
- X3.m is discovered, which should trump everything in the intermediate list
- X3.m replaces X1.m so list is {X3.m, X2.m}
- "update" code does not continue and X2 is never replaced

**Comment by DanHeidinga** [comment] 2020-01-09 17:31
@theresa-m How risky would the real fix be at this point?  Is there a minimal change to the #7788 fix that could be applied to 0.18?

**Comment by theresa-m** [comment] 2020-01-09 17:46
I think it can be left out of 0.18.
Adding additional risk to the release seems unnecessary to me at this point given that 
- the described fix will not resolve https://github.com/eclipse/openj9/issues/7623 on its own (mine and Cheng's changes from https://github.com/eclipse/openj9/pull/8230 which is not going into 0.18 is also needed)
- this getMethods edge case caught by https://github.com/eclipse/openj9/issues/7623 has been around since at least 2017 and hasn't caused other issues so far

**Comment by DanHeidinga** [comment] 2020-01-09 18:13
Thanks @theresa-m I've reverted the change from both master and 0.18 now

**Comment by DanHeidinga** [comment] 2020-01-09 18:13
fyi @pshipton for awareness in the release process

**Comment by pshipton** [comment] 2020-01-09 21:30
I assume this can be closed since the problematic change has been reverted.

**Closed by pshipton** 2020-01-09 21:30 UTC
Labels: prio:high, test failure
