### ISSUE TITLE
jdk16 xLinux: cmdLineTester_pltest_j9sig_ext_0: Found zero nodes with memory even after NUMA was reported as supported

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12433] opened 2021-04-14 10:05 UTC
https://ci.adoptopenjdk.net/job/Test_openjdk16_j9_extended.functional_x86-64_linux/61/consoleFull
node: test-docker-fedora33-x64-3
Build:
```
01:31:51  openjdk version "16" 2021-03-16
01:31:51  OpenJDK Runtime Environment AdoptOpenJDK-16+36-202104122343 (build 16+36-202104122343)
01:31:51  Eclipse OpenJ9 VM AdoptOpenJDK-16+36-202104122343 (build master-9b90f0a09, JRE 16 Linux amd64-64-Bit Compressed References 20210412_18 (JIT enabled, AOT enabled)
01:31:51  OpenJ9   - 9b90f0a09
01:31:51  OMR      - 440f0991d
01:31:51  JCL      - 073accb86d based on jdk-16+36)
```
```
03:22:40   [ERR] ----------------------------------------
03:22:40   [ERR] j9cuda tests
03:22:40   [ERR] ----------------------------------------
03:22:40   [ERR] 
03:22:40   [ERR] 
03:22:40   [ERR] Starting test basic
03:22:40   [ERR]   j9cuda: found 0 devices
03:22:40   [ERR] Ending test basic
03:22:40   [ERR] 
03:22:40   [ERR] Starting test errors
03:22:40   [ERR]   error 0: no error
03:22:40   [ERR]   error 38: no CUDA-capable device is detected
03:22:40   [ERR]   error -500: named symbol not found
03:22:40   [ERR] Ending test errors
03:22:40   [ERR] 
03:22:40   [ERR] Starting test invalid device identifiers
03:22:40   [ERR] Ending test invalid device identifiers
```

**Comment by andrew-m-leonard** [comment] 2021-04-14 10:05
@sxa fyi

**Comment by keithc-ca** [comment] 2021-04-14 12:26
That's normal output for the j9cuda test on a machine that doesn't have any GPUs.
The real issue is just below that:
```
[2021-04-13T02:22:40.813Z]  [ERR] FAILURES DETECTED. Number of failed tests: 1
[2021-04-13T02:22:40.813Z]  [ERR] 
[2021-04-13T02:22:40.813Z]  [ERR] 1: j9vmem_test_numa
[2021-04-13T02:22:40.813Z]  [ERR] 	../../../../../../openj9/runtime/tests/port/j9vmemTest.c line 1810: Found zero nodes with memory even after NUMA was reported as supported (FAIL)
[2021-04-13T02:22:40.813Z]  [ERR] 
[2021-04-13T02:22:40.813Z]  [ERR] 		LastErrorNumber: -252
[2021-04-13T02:22:40.813Z]  [ERR] 		LastErrorMessage: Unknown error -1
```

**Comment by pshipton** [comment] 2021-04-14 12:37
@sxa We looked at this before, but I don't find an OpenJ9 issue, maybe there is an issue in one of the Adopt/Adoptium repos. Seems to me I didn't want to change the test, and we decided it was a machine config problem?

**Comment by sxa** [comment] 2021-04-14 15:16
This was the previous issue (Since Andrew had initially reported it as a CUDA failure I assumed it was something different)

**Comment by keithc-ca** [comment] 2021-04-14 16:36
Closing this as a duplicate of AdoptOpenJDK/openjdk-tests#2143.

**Closed by keithc-ca** 2021-04-14 16:36 UTC
Labels: comp:test, test failure
