### ISSUE TITLE
JIT crashes when compiling Java 10 with debugging enabled.

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/openj9#2392] opened 2018-07-16 14:04 UTC
I tried compiling OpenJ9 Java 10 per https://blog.openj9.org/2018/06/05/debugging-openj9-in-docker-with-gdb/ steps 6, 7, and 8.  I already had a Java 10 docker set up.

While building DDR, the JIT crashed:
```
Creating support/modules_libs/openj9.dtfj/ddr/j9ddr.jar
Compiling 4 files for BUILD_JIGSAW_TOOLS
Assertion failed at /macprojects/openj9/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-slowdebug/vm/compiler/../compiler/optimizer/J9TransformUtil.cpp:386: isFinalFieldPointingAtNativeStruct(symRef, comp)
VMState: 0x000513ff
	dereferenceStructPointerChain should be dealing with reference fields
compiling sun/nio/fs/NativeBuffers.copyCStringToNativeBuffer([BLsun/nio/fs/NativeBuffer;)V at level: warm
#0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x32 [0x2b7bfd669bca]
#1: function TR_Debug::printStackBacktrace()+0x1f [0x2b7bfd67c78b]
#2: /macprojects/openj9/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-slowdebug/jdk/lib/compressedrefs/libj9jit29.so(+0xab0e16) [0x2b7bfd2fee16]
#3: function TR::assertion(char const*, int, char const*, char const*, ...)+0xb3 [0x2b7bfd2fefa6]
#4: /macprojects/openj9/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-slowdebug/jdk/lib/compressedrefs/libj9jit29.so(+0x941520) [0x2b7bfd18f520]
#5: function J9::TransformUtil::transformIndirectLoadChainImpl(TR::Compilation*, TR::Node*, TR::Node*, void*, TR::Node**)+0x3a5 [0x2b7bfd192dd7]
#6: function J9::TransformUtil::transformIndirectLoadChainAt(TR::Compilation*, TR::Node*, TR::Node*, unsigned long*, TR::Node**)+0xdc [0x2b7bfd19293a]
#7: /macprojects/openj9/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-slowdebug/jdk/lib/compressedrefs/libj9jit29.so(+0xde7c57) [0x2b7bfd635c57]
#8: /macprojects/openj9/openj9-openjdk-jdk10/build/linux-x86_64-normal-server-slowdebug/jdk/lib/compressedrefs/libj9jit29.so(+0xde8231) [0x2b7bfd636231]
#9: function constrainIiload(OMR::ValuePropagation*, TR::Node*)+0x8c [0x2b7bfd63c606]
#10: function OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int)+0x13f [0x2b7bfd614c0d]
#11: function constrainChildren(OMR::ValuePropagation*, TR::Node*)+0x75 [0x2b7bfd668c99]
#12: function constrainIand(OMR::ValuePropagation*, TR::Node*)+0x47 [0x2b7bfd652ec4]
#13: function OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int)+0x13f [0x2b7bfd614c0d]
#14: function constrainChildren(OMR::ValuePropagation*, TR::Node*)+0x75 [0x2b7bfd668c99]
#15: function constrainAdd(OMR::ValuePropagation*, TR::Node*)+0x5b [0x2b7bfd64cb94]
#16: function OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int)+0x13f [0x2b7bfd614c0d]
#17: function constrainChildren(OMR::ValuePropagation*, TR::Node*)+0x75 [0x2b7bfd668c99]
#18: function constrainIshr(OMR::ValuePropagation*, TR::Node*)+0x42 [0x2b7bfd6520af]
#19: function OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int)+0x13f [0x2b7bfd614c0d]
#20: function constrainChildren(OMR::ValuePropagation*, TR::Node*)+0x75 [0x2b7bfd668c99]
#21: function OMR::ValuePropagation::launchNode(TR::Node*, TR::Node*, int)+0x13f [0x2b7bfd614c0d]
#22: function OMR::ValuePropagation::processTrees(TR::TreeTop*, TR::TreeTop*)+0x45d [0x2b7bfd60640f]
#23: function TR::GlobalValuePropagation::processBlock(TR_StructureSubGraphNode*, bool, bool)+0x5e8 [0x2b7bfd526d78]
#24: function TR::GlobalValuePropagation::processStructure(TR_StructureSubGraphNode*, bool, bool)+0x160 [0x2b7bfd52550e]
#25: function TR::GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*, bool, bool)+0x2da [0x2b7bfd526786]
#26: function TR::GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*, bool, bool)+0xbd [0x2b7bfd526569]
#27: function TR::GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*, bool, bool)+0xbd [0x2b7bfd526569]
#28: function TR::GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*, bool, bool)+0xbd [0x2b7bfd526569]
#29: function TR::GlobalValuePropagation::processRegionNode(TR_StructureSubGraphNode*, bool, bool)+0xbd [0x2b7bfd526569]
```

**Comment by fjeremic** [comment] 2018-07-16 14:08
@cathyzhyi FYI FSD failure in global VP.

**Comment by babsingh** [comment] 2018-07-16 14:52
This is duplicate of https://github.com/eclipse/openj9/issues/2088.

**Comment by fjeremic** [comment] 2018-07-16 18:27
Closing as duplicate.

**Closed by fjeremic** 2018-07-16 18:27 UTC
Labels: comp:jit
