### ISSUE TITLE
J9 failed to pass the JUnit test after throwing StackOverflowError for a previous test. When removing that "previous test", J9 pass the test.

### ISSUE THREAD

**Issue by fuzzy000** [eclipse/openj9#9381] opened 2020-04-28 13:35 UTC
Java -version output
--------------------
The issue happened in following versions:
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
Eclipse OpenJ9 VM (build openj9-0.17.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20191017_442 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 97b5ec8f383 based on jdk8u232-b09)
```
```
openjdk version "9.0.4-adoptopenjdk"
OpenJDK Runtime Environment (build 9.0.4-adoptopenjdk+12)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 9 Linux amd64-64-Bit Compressed References 20180814_248 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - feec4d2ae based on jdk-9.0.4+12)
```
```
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Linux amd64-64-Bit Compressed References 20191016_358 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)
```

Summary of problem
------------------
We made some changes to a class file in the JUnit project (junit.samples.money.Money), and let several JVMs run the corresponding test file (org.junit.samples.money.MoneyTest). 

In this test file ([MoneyTestSourceFile.zip](https://github.com/eclipse/openj9/files/4545936/MoneyTestSourceFile.zip)), there are two JUnit tests (we have simplified the test file), one is `testSimpleSubtract()`, the other is `zeroMoniesAreEqualRegardlessOfCurrency()`. The first test will get into an infinite loop, which will cause the JVMs to throw `StackOverflowError`. **When we remove the first test, OpenJDK and J9 both can successfully pass the second test**. But when we keep the first test, we found an **inconsistent** behavior of J9:

OpenJDK series throw `StackOverflowError` for the first test and pass the second test as before. J9 series throw `StackOverflowError` for the first test, and **fail the second test, throwing `AssertionError`**.

The `AssertionError` is thrown at `assertEquals(zeroDollars, zeroFrancs);` in `zeroMoniesAreEqualRegardlessOfCurrency()` method, this line uses the method `equals()` of class `Money` to do comparation. By decompiling the class `Money`, we found that the result returns by `equals()` is determined by the method `isZero()`, the result of `isZero()` is determined by `amount()`.

```
public boolean isZero() {
    int var1 = this.amount();
    Print.logPrint("<junit.samples.money.Money: boolean isZero()> **** Executed Line: **** 1 **** $i0 = virtualinvoke r0.<junit.samples.money.Money: int amount()>()");
    boolean var2;
    if (var1 == 0) {
        Print.logPrint("<junit.samples.money.Money: boolean isZero()> **** Executed Line: **** 2 **** if $i0 != 0 goto $z0 = 0");
        var2 = true;
        Print.logPrint("<junit.samples.money.Money: boolean isZero()> **** Executed Line: **** 3 **** $z0 = 1");
    } else {
        var2 = false;
        Print.logPrint("<junit.samples.money.Money: boolean isZero()> **** Executed Line: **** 5 **** $z0 = 0");
    }
    return var2;
}
```
Note that we also use several print statements in `zeroMoniesAreEqualRegardlessOfCurrency()`. From the printed message, we found that, when we keep the first test, J9 print the following message, which is really strange:
```
**********zeroDollars.amount(): 0**********
**********zeroFrancs.amount(): 0**********
**********zeroDollars.isZero(): false**********
**********zeroFrancs.isZero(): false**********
```
 We think maybe after throwing `StackOverflowError`, something has messed up in the JVM? It looks like a defect in J9 implementation. 

We hope our works and findings can make J9 better.

Diagnostic files
----------------

**The version that only has one test `zeroMoniesAreEqualRegardlessOfCurrency()`:**
[MoneyOneTest.zip](https://github.com/eclipse/openj9/files/4546016/MoneyOneTest.zip)
1. Extract it
2. In directory `MoneyOneTest`, run command `java -cp ./sootOutput/junit-junit/:hamcrest-core-1.3.jar  org.junit.runner.JUnitCore org.junit.samples.money.MoneyTest`

In this case, both J9 and OpenJDK will pass the test case.

**The version that have two tests `testSimpleSubtract()` and `zeroMoniesAreEqualRegardlessOfCurrency()`:**
[MoneyTwoTest.zip](https://github.com/eclipse/openj9/files/4546024/MoneyTwoTest.zip)
1. Extract it
2. In directory `MoneyTwoTest`, run command `java -cp ./sootOutput/junit-junit/:hamcrest-core-1.3.jar  org.junit.runner.JUnitCore org.junit.samples.money.MoneyTest`

In this case, OpenJDK series throw `StackOverflowError` for the first test and pass the second test as before. J9 series throw `StackOverflowError` for the first test, and **fail the second test, throwing `AssertionError`**. 

Execution environment
---------------------------------

- OS and version: Ubuntu 16.04.6 LTS
- CPU model: Intel(R) Xeon(R) CPU E5-4610 v4 @ 1.80GHz
- Number of CPU cores: 4CPUs, each has 10 cores
- Size of physical memory: 16384 MB * 20

**Comment by DanHeidinga** [comment] 2020-04-28 13:46
@gacholio can you look at this?

**Comment by gacholio** [comment] 2020-04-28 15:49
@DanHeidinga Likely not today - still looking at the decomp issue.

**Comment by gacholio** [comment] 2020-04-29 16:38
Looks like a JIT issue - the second test passes when run `-Xint`.

**Comment by gacholio** [comment] 2020-04-29 17:00
Fails with
```
-Xjit:count=0,optlevel=warm,limit={junit/samples/money/Money.equals(Ljava/lang/Object;)Z}
```
Passes with
```
-Xjit:count=0,optlevel=cold,limit={junit/samples/money/Money.equals(Ljava/lang/Object;)Z}
```

**Comment by gacholio** [comment] 2020-04-29 17:01
The test produces a vast amount of output - I suggest running with `| grep "Tests run"`.
A pass results in `Tests run: 2,  Failures: 1` whereas a failure is `Tests run: 2,  Failures: 2`.

**Comment by andrewcraik** [comment] 2020-05-19 14:38
@rpshukla could you take a look?

**Comment by rpshukla** [comment] 2020-05-19 17:27
A few observations:

1) This fails in `MoneyOneTest` with the following options: `-Xjit:count=0,optlevel=warm,limit={junit/samples/money/Money.equals(Ljava/lang/Object;)Z}`

2) It also fails with when limited to `junit/samples/money/Money.isZero()Z` (when Money.equals is compiled, isZero gets inlined)

3) I have narrowed down lastoptindex and lastoptsubindex. The lowest index and subindex that produces the failure is 21.5 (i.e. 21.4 passes): `-Xjit:lastoptindex=21,lastoptsubindex=5,count=0,optlevel=warm,limit={*isZero*}`

The opt with index 21 is treeSimplification:
```
simplifying block_2
[    11]  21.1    O^O TREE SIMPLIFICATION: Long compare narrower: equality with no upper bits [00007F3FF2E14F00]
simplifying block_9
simplifying block_6
[    12]  21.2    O^O TREE SIMPLIFICATION: Merge blocks: block_6 and block_7
set hasCommonedAncestor = true as BBStart 00007F3FF2E14C80 has refCount 0 > 1
set hasCommonedAncestor = true as BBEnd 00007F3FF2E14CD0 has refCount 0 > 1
simplifying block_10
[    13]  21.3    O^O TREE SIMPLIFICATION: Merge blocks: block_10 and block_11
set hasCommonedAncestor = true as BBStart 00007F3FF2E15680 has refCount 0 > 1
set hasCommonedAncestor = true as BBEnd 00007F3FF2E156D0 has refCount 0 > 1
[    14]  21.4    O^O TREE SIMPLIFICATION:  change conditional to unconditional n20n
[    15]  21.5    O^O TREE SIMPLIFICATION: Changing node [00007F3FF2D68B60] ificmpne into goto
set hasCommonedAncestor = true as ificmpne 00007F3FF2D68B60 has refCount 0 > 1
set hasCommonedAncestor = true as iconst 00007F3FF2D68A70 has refCount 1 > 1
set hasCommonedAncestor = true as iload 00007F3FF2D68A20 has refCount 1 > 1
simplifying block_17
simplifying block_4
simplifying block_19
simplifying block_20
simplifying block_5
simplifying block_8
simplifying block_22
simplifying block_12
simplifying block_23
simplifying block_24
simplifying block_15
simplifying block_25
simplifying block_18
simplifying block_21
```

I will look into what tree simplification is doing.

**Comment by rpshukla** [comment] 2020-05-22 20:42
The root cause of this issue seems to be in IL gen.

Immediately after IL gen the trees look like this:
```
n5n       BBStart <block_2>                                                                   [0x7f3ff2d686b0] bci=[-1,0,69] rc=0 vc=0 vn=- li=- udi=- nc=0
n10n      treetop                                                                             [0x7f3ff2d68840] bci=[-1,1,69] rc=0 vc=0 vn=- li=- udi=- nc=1
n9n         icalli  junit/samples/money/Money.amount()I[#361  virtual Method -88] [flags 0x500 0x0 ]  [0x7f3ff2d687f0] bci=[-1,1,69] rc=2 vc=0 vn=- li=- udi=- nc=2
n8n           aloadi  <vft-symbol>[#295  Shadow] [flags 0x18607 0x0 ]                         [0x7f3ff2d687a0] bci=[-1,1,69] rc=1 vc=0 vn=- li=- udi=- nc=1
n7n             aload  <'this' parm Ljunit/samples/money/Money;>[#359  Parm] [flags 0x40000107 0x0 ] (X!=0 sharedMemory )  [0x7f3ff2d68750] bci=[-1,0,69] rc=2 vc=0 vn=- li=- udi=- nc=0 flg=0x4
n7n           ==>aload
n11n      istore  <auto slot 0>[#362  Auto] [flags 0x3 0x0 ]                                  [0x7f3ff2d68890] bci=[-1,4,69] rc=0 vc=0 vn=- li=- udi=- nc=1
n9n         ==>icalli
n13n      ResolveCHK [#300]                                                                   [0x7f3ff2d68930] bci=[-1,5,69] rc=0 vc=0 vn=- li=- udi=- nc=1
n12n        aload  <string>[#363  unresolved Static +1858928] [flags 0x80000307 0x0 ]         [0x7f3ff2d688e0] bci=[-1,5,69] rc=2 vc=0 vn=- li=- udi=- nc=0
n15n      treetop                                                                             [0x7f3ff2d689d0] bci=[-1,7,69] rc=0 vc=0 vn=- li=- udi=- nc=1
n14n        call  Print.logPrint(Ljava/lang/String;)V[#365  static Method] [flags 0x500 0x0 ]  [0x7f3ff2d68980] bci=[-1,7,69] rc=1 vc=0 vn=- li=- udi=- nc=1
n12n          ==>aload
n20n      ificmpne --> block_4 BBStart at n1n ()                                              [0x7f3ff2d68b60] bci=[-1,11,69] rc=0 vc=0 vn=- li=- udi=- nc=2 flg=0x20
n16n        iload  <auto slot 0>[#362  Auto] [flags 0x3 0x0 ] (X!=0 )                         [0x7f3ff2d68a20] bci=[-1,10,69] rc=1 vc=0 vn=- li=- udi=- nc=0 flg=0x4
n17n        iconst 0                                                                          [0x7f3ff2d68a70] bci=[-1,11,69] rc=1 vc=0 vn=- li=- udi=- nc=0
n6n       BBEnd </block_2> =====                                                              [0x7f3ff2d68700] bci=[-1,11,69] rc=0 vc=0 vn=- li=- udi=- nc=0
```

Node `n20n` corresponds with `if (var1 == 0)` from the decompiled code. The value of `var1` is stored in `<auto slot 0>`. The problem here is that node `n16n` (which loads slot 0) has the `nodeIsNonZero` flag set. This is shown as the `(X!=0 )` annotation. Since the value in slot 0 is believed to be non-zero and it is compared with a constant 0, tree simplification changes the `ificmpne` to a `goto`. This causes the branch to always be taken, even if the value of `var1` is zero.

It looks like the `nodeIsNonZero` flag was set because IL gen assumed that slot 0 was still being used to store the receiver and thus the flag did not need to be reset. There is a method that is supposed to check if slot 0 was re-used so that flags can be reset: https://github.com/eclipse/openj9/blob/49b6ce63ea00fbaa1cd8cb51fe9d8bed84c84123/runtime/compiler/ilgen/J9ByteCodeIterator.cpp#L68 
However, it only has cases for `astore` bytecodes, not `istore`, `lstore`, etc.

This problem can be fixed by adding cases in `TR_J9ByteCodeIterator::isThisChanged` to handle other types of stores to slot 0. I have tested this locally and it seems to fix the problem. I will open a pull request to make this change.

**Closed** 2020-05-29 13:05 UTC
Labels: comp:jit, userRaised
