### ISSUE TITLE
Gradel project build fails with sealing violation when -Xshareclasses is enabled (JDK11)

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#4113] opened 2018-12-19 03:55 UTC
Problem reported here https://github.com/gradle/kotlin-dsl/issues/1290

**Comment by hangshao0** [comment] 2018-12-19 16:34
Do it fail with hotspot ? @ParkerM

**Comment by hangshao0** [comment] 2018-12-19 16:52
The code in the shared classes patch:
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/caa2ebd7b164280948029927ace6c5722e707124/src/java.base/share/classes/java/net/URLClassLoader.java#L740to#L745
is the same as the original OpenJDK code.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/java/net/URLClassLoader.java#L623to#L628

**Comment by ParkerM** [comment] 2018-12-19 18:01
@hangshao0 It succeeds as expected on hotspot as well as openj9 if the -Xshareclasses flag is not enabled.

**Comment by hangshao0** [comment] 2018-12-19 19:16
OK. Then this is interesting. We need to find out where the behavior begin to diverge

**Comment by ParkerM** [comment] 2018-12-19 23:56
Yeah, I've been hesitant to ascribe the issue to one specific thing since there's a lot going on there, and the narrowest reproduction I've found involves both the young kotlin-dsl and a specific/obscure flag in OpenJ9. The build seems to work fine when using a groovy-based buildscript, so kotlin-dsl was my best guess as the culprit. 
That said, one of the gradle devs did find another gradle-agnostic bug related to zipping files, but it's only reproducible in alpine-based images, so there's two competing culprits yet again. See here for their example: https://github.com/AdoptOpenJDK/openjdk-docker/issues/87.

**Comment by titou10titou10** [comment] 2018-12-21 00:35
Same problem for me with eclipse 2018-12 rcp win/64 and an eclipse-rcp application ([JMSToolBox](https://github.com/jmstoolbox/jmstoolbox)) when migrating from Java 8 to Java 11 and using Adopt OpenJKD/J9 v11

Disabling`-Xshareclasses` make it work again

**Comment by hangshao0** [comment] 2018-12-21 16:20
The shared classes patch on URLClassLoader is originally applied to Java 8, and then ported onto Java 9, 10 and 11. The patched methods in URLClassLoader might have been changed by OpenJDK from Java 8 to Java 11, we might consider reviewing (or possibly rewriting) the patch on Java 11.

**Comment by howlger** [comment] 2018-12-22 11:53
Example to reproduce this issue:
```
public class OpenJ9_Issue_4113 {
    public static void main(String[] args) throws java.io.IOException {
        java.util.HashMap<String, String> env = new java.util.HashMap<>();
        env.put("java.home", System.getProperty("java.home"));
        java.net.URI uri = java.net.URI.create("jrt:/");
        java.nio.file.FileSystems.newFileSystem(uri, env);
    }
}
```
There are no problems running `java -Xshareclasses:cacheDir=_cache OpenJ9_Issue_4113` for the first time. But when running it again (when the cache created on the first run is used), the following exception is thrown:
```
Exception in thread "main" java.lang.SecurityException: sealing violation: package jdk.internal.jimage is sealed
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:743)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:592)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider$JrtFsLoader.loadClass(JrtFileSystemProvider.java:147)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
	at java.base/jdk.internal.jrtfs.SystemImage.open(SystemImage.java:59)
	at java.base/jdk.internal.jrtfs.JrtFileSystem.<init>(JrtFileSystem.java:90)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:108)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:127)
	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at OpenJ9_Issue_4113.main(OpenJ9_Issue_4113.java:6)
```

**Comment by hangshao0** [comment] 2018-12-24 16:06
> Example to reproduce this issue:
> 
> public class OpenJ9_Issue_4113 {
>     public static void main(String[] args) throws java.io.IOException {
>     ...
>     ...

This issue goes away if I change getPackage() to getDefinedPackage() here :
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/390ca5bdb952732f29d7e2080254431bc061317f/src/java.base/share/classes/java/net/URLClassLoader.java#L737

getPackage() is deprecated since Java 9.

**Comment by howlger** [comment] 2018-12-25 22:11
@hangshao0 Thanks. That sounds promising. Could you please make a pull request so that the change can be tested in the nightly build once it has been merged?

Or is there another way to test the proposed change? Via `jimage extract --dir out modules` I can extract the file `modules` and replace the `.class` files, but I don't know how to recreate the changed `modules` file.

**Closed** 2018-12-28 03:49 UTC
Labels: comp:vm, userRaised

**Comment by ParkerM** [comment] 2018-12-28 07:47
Also can confirm my kotlin-dsl issue is resolved with @hangshao0's patch. Thanks for the help everybody!
