### ISSUE TITLE
OpenJ9 / OMR fails to build on AIX when using latest XLC v16.1 

### ISSUE THREAD

**Issue by groeges** [eclipse/openj9#5074] opened 2019-03-13 11:09 UTC
In OpenJDK jdk branch (jdk13) and hence the jdk13 extensions repository there have been changes to use xlclang/xlclang++ if available on AIX systems.

If XLC 16.1 is installed then xlclang/xlclang++ is provided and used when building OpenJ9/OMR.
When using  xlclang/xlclang++ there are quite a lot of compiler/linker options that are not supported anymore and cause the build to fail. 

This website shows all the options that are unsupported: https://www.ibm.com/support/knowledgecenter/SSGH3R_16.1.0/com.ibm.xlcpp161.aix.doc/migrate/migrate_to_xlclang.html  

The makefiles for OpenJ9 and OMR need to be modified to not use these unsupported options.

**Comment by pshipton** [comment] 2019-04-08 18:40
@groeges wrote:
Have just seen that the minimum compiler version for JDK 13 on AIX is now XLC 16.1 (so that the newer xlclang/xlclang++ can be used).

**Comment by DanHeidinga** [comment] 2019-05-09 19:58
related OMR issue: https://github.com/eclipse/omr/issues/3775

**Comment by vsebe** [comment] 2019-06-05 15:50
related OMR issue: https://github.com/eclipse/omr/issues/3927

**Comment by DanHeidinga** [comment] 2019-09-11 15:21
We're likely at the "go / no-go" point for AIX to make JDK 13.  

Build is broken so testing hasn't been run yet.
Let's limit the PRs for this going into 0.16 until we're sure we're going to ship it.

**Comment by pshipton** [comment] 2019-09-13 19:55
Too late for the 0.16 release now, moving to the next release.

**Comment by pshipton** [comment] 2019-09-23 17:27
Running a build with all the fixes applied and DDR disabled resulted in the following, Illegal instruction
```
12:23:07  Compiling 4 files for BUILD_JIGSAW_TOOLS

12:23:44  Optimizing the exploded image

12:23:58  /opt/freeware/bin/bash: line 1: 5505162 Illegal instruction     (core dumped) /home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk/bin/java -Xms64M -Xmx1600M -XX:ThreadStackSize=1536 -XX:+UseSerialGC -Xms32M -Xmx512M -XX:TieredStopAtLevel=1 -cp /home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/buildtools/tools_jigsaw_classes --add-exports java.base/jdk.internal.module=ALL-UNNAMED build.tools.jigsaw.AddPackagesAttribute /home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk > >(/opt/freeware/bin/tee -a /home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk/_optimize_image_exec.log) 2> >(/opt/freeware/bin/tee -a /home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk/_optimize_image_exec.log >&2)
12:23:58  ExplodedImageOptimize.gmk:39: recipe for target '/home/jenkins/workspace/Build_JDK13_ppc64_aix_Personal/build/aix-ppc64-server-release/jdk/_optimize_image_exec.marker' failed
```

**Comment by pshipton** [comment] 2019-09-24 00:31
@gita-omr the `Illegal instruction` happens when running `java -version`, but not `java -Xint -version`. I have the JVM which I can make accessible, can somebody pls take a look.
@zl-wang

**Comment by gita-omr** [comment] 2019-09-24 14:15
Sure, we'll take a look as soon as somebody is available.

**Comment by pshipton** [comment] 2019-09-25 14:38
I don't expect this is going to make the 0.17 release, so moving it out.

**Comment by gita-omr** [comment] 2019-09-26 15:44
@keithc-ca I heard you looked at the 'java -version' crash. Please let us know if we can help.

**Comment by keithc-ca** [comment] 2019-09-26 15:54
> @keithc-ca I heard you looked at the 'java -version' crash. Please let us know if we can help.

I have _not_ looked at that.

**Comment by gita-omr** [comment] 2019-09-26 16:02
> 
> 
> > @keithc-ca I heard you looked at the 'java -version' crash. Please let us know if we can help.
> 
> I have _not_ looked at that.

Sure, we will look into it

**Comment by gita-omr** [comment] 2019-09-26 19:23
It crashes on the first instruction (usually 'ld') of any compiled method. The instruction seems to be well formed. Perhaps, something is wrong with the memory allocated for the code cache.

**Comment by zl-wang** [comment] 2019-09-26 19:56
@gita-omr   I suspected it is PPCCodeSync.inc not compiled correctly, such that generated instructions are not synchronized (with iCache and IBUF).   xlclang++ might go down the path of
defined(__IBMC__) || defined(__IBMCPP__), but the built-in(s) are not recognized.  Since it is clang, it must recognize the gcc asm inlining. It can be changed to take the \#else path.

**Comment by gita-omr** [comment] 2019-09-27 12:59
Thanks for the lead but it did not seem to help. Most likely it has something to do with the way code cache is allocated. Trying to find the exact place in the port library where it happens.

**Comment by gita-omr** [comment] 2019-09-28 20:15
Progress so far:
1) Was able to build JDK 13 with xlclang++ and reproduce the problem with my build
2) applied the suggestion from @zl-wang above and rebuilt from scratch since incremental build does not seem to be working. Still got the same illegal instruction
3) looked at omrvmem.c : mprotect() is used to set memory properties. Put printfs into both JDK8 and JDK 13 builds and neither set PROT_EXEC bit when running 'java -version' (but JDK 8 works of course)
4) enforcing setting the bit did not help either
5) not being able to rebuild VM quickly (in both JDK8 and JDK 13) seriously hinders the investigation

Also, please note that as a part of this work, we also need to make sure we can do debug builds with the new compiler, in addition to all the functional and performance testing.

**Comment by gita-omr** [comment] 2019-09-29 16:29
Some interesting findings, on the same machine:

JDK 13 built with xlclang++ : fails
JDK 13 built with xlC 13 : fails (the same way)
JDK 8 built with xlC 13: works

**Comment by zl-wang** [comment] 2019-09-30 14:03
From the symptom description (IFU -- Instruction Fetch Unit -- saw invalid instruction from code cache, while debugger saw valid instruction),  the most likely crashing reason is still dCache <=> iCache synchronization issue.  If it were memory protection issue, it would be SIGSEGFAULT instead of  SIGILL.  The direct explanation is j9method->extra out of order with respect to codegen output.  There are a couple potential reasons to be investigated next:
1) there is memory barrier between codegen output and writing j9method->extra, but it could implicitly depend on ppcCodeSync() having that barrier. Check out on that;
2) makefile is changed such that, for example, TR_HOST_POWER is somehow undefined, so that ppcCodeSync() is empty.  No sync and barrier at all.  Check out that from -qlist or dump disassembly;
3) ppcCacheLineSize is wrong ... for example it is too big (e.g. 256) that compiling output codeCache is not walked completely (I admit this is unlikely though ... just throw it out here).

**Comment by gita-omr** [comment] 2019-09-30 14:14
Thanks. It also occurred to me  it would’ve been segmentation fault, not illegal instruction. Will check the macro...

**Comment by gita-omr** [comment] 2019-10-01 00:02
1) Verified that ppCodeSync calls all the right synchronization instructions
2) was able to step through the debugger and put a breakpoint on the bctr instruction that jumps to the compile code (from jitTransition())
3) ctr register points to the method entry and the method entry contains the right instruction
4) stepi gives "program not active". Note that this happens even before we get to the first method instruction (between bctr and the target instruction)

**Comment by gita-omr** [comment] 2019-10-04 14:16
A bit more progress:
1) did verbose build from scratch for JDK 8 and JDK 13. All compilation steps seem to be identical
2) enabled debug output in omrvmem.c. Again, code cache seems to be allocated in a similar way, with EXEC permissions:
[OUT8.txt](https://github.com/eclipse/openj9/files/3690910/OUT8.txt)
[OUT13.txt](https://github.com/eclipse/openj9/files/3690911/OUT13.txt)

3) tried to experiment with mixing object files from good and bad build, but  got into all kinds of make troubles
4) need to switch to an urgent PMR now

**Comment by gita-omr** [comment] 2019-10-04 14:33
Maybe somebody knows how to check that memory was actually allocated with the EXECUTE permissions? @gacholio

**Comment by gita-omr** [comment] 2019-10-04 15:43
@dmitripivkine please see above.

**Comment by dmitripivkine** [comment] 2019-10-04 17:08
Sorry I don't understand question.
If you are asking about issuers of memory allocation requests with OMRPORT_VMEM_MEMORY_MODE_EXECUTE there are only:
- J9::CodeCacheManager::allocateCodeCacheSegment() uses it as well as MEMORY_TYPE_CODE caused use the same flag for memory segments
- initS390WriteOnceHelpers() in compiler/runtime/Runtime.cpp

I believe I did not miss other callers

**Comment by gita-omr** [comment] 2019-10-04 17:12
My current theory is that maybe somehow the returned memory did not have that property satisfied. I was wondering if there is an API to check memory properties given its address.

**Comment by dmitripivkine** [comment] 2019-10-04 18:04
Well I am not an expert on Executable memory for AIX
There are two scenarios for AIX for EXECUTE:
- for 4k pages use `malloc()`
- for Large Pages (including default 64k) use `shmget()` with `S_IEXEC` flag
Do you know which case do you have?

I guess shmget() one...
`S_IEXEC` is described in https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/filesreference/mode.h.html as `Permits the owner of a file to execute the file or to search the file's directory.`
However this flag is NOT mentioned in `shmget()` manual https://www.ibm.com/support/knowledgecenter/en/ssw_aix_72/s_bostechref/shmget.html
Seems passing `S_IEXEC` to `shmget()` in `SharedMemoryFlag` field is not a legitimate (or obsolete) way (???)

**Comment by gita-omr** [comment] 2019-10-04 20:50
Thanks a lot for the info. I think it fails on AIX 71.

**Comment by zl-wang** [comment] 2019-10-07 14:36
i.e.  I highly suspected some commits (made for xlclang++) screwed something up somehow.

**Comment by gita-omr** [comment] 2019-10-07 16:08
Yes, I think it's a good idea. @vsebe maybe you can try to build JDK 13 with xlC 13 with the older source?  You might know better which commits were xlclang++ and which JDK 13 specific?

**Comment by vsebe** [comment] 2019-10-07 18:38
@zl-wang  OpenJ9 on Linux PPC64 LE uses gcc not xlc.
JDK13 with xlc 13 would use xlc as compiler not xlclang.
@gita-omr I do not have permissions to launch a build on https://ci.eclipse.org/openj9/.
To launch an AIX build using xlc 13 modify `PATH+XLC` in [defaults.yml](https://github.com/eclipse/openj9/blob/master/buildenv/jenkins/variables/defaults.yml) at L246:
replace 
`13: 'PATH+XLC=/opt/IBM/xlC/16.1.0/bin:/opt/IBM/xlc/16.1.0/bin CC=xlclang CXX=xlclang++'` 
with 
`13: 'PATH+XLC=/opt/IBM/xlC/13.1.3/bin:/opt/IBM/xlc/13.1.3/bin'`
then launch a [personal build](https://ci.eclipse.org/openj9/view/Build_Personal/job/Build_JDK13_ppc64_aix_Personal/) where VENDOR_REPO is your openj9 fork and VENDOR_BRANCH is the branch containing the above change.

**Comment by zl-wang** [comment] 2019-10-07 19:37
@vsebe yes, i knew.  for comparison (with AIX), i was suggesting to configure Linux build to use xlC.  There is no xlclang in xlC13.

**Comment by pshipton** [comment] 2019-10-07 19:54
On AIX, the OpenJDK code will fail to compile with xlc 13.

**Comment by pshipton** [comment] 2019-10-07 19:59
> On AIX, the OpenJDK code will fail to compile with xlc 13.

Although jdk12 has a patch to fix it. You could apply it to jdk13 in a personal build.
https://github.com/ibmruntimes/openj9-openjdk-jdk12/commit/d127ea8ed60ffb70e61cb3eefcb1f16737f572ef

I suspect trying to build plinux with xlc will be considerable work since OpenJDK doesn't support it.

**Comment by gita-omr** [comment] 2019-10-07 20:04
I think was able to build JDK 13 with xlC 13 at least to the same point when using xlC 16 (xlclang). java -version gave the same Illegal Instruction as with xlC 16(xlclang).

**Comment by pshipton** [comment] 2019-10-07 20:06
Here are the relevant xlc 16 changes I found:
https://github.com/eclipse/openj9/pull/6584
https://github.com/eclipse/openj9/pull/6694
https://github.com/eclipse/openj9/pull/7034
https://github.com/eclipse/omr/pull/4087
https://github.com/eclipse/omr/pull/4099 and https://github.com/eclipse/omr/pull/4119
https://github.com/eclipse/omr/pull/4285

**Comment by pshipton** [comment] 2019-10-07 20:07
> I think was able to build JDK 13 with xlC 13

Unless you had the harfbuzz fix, the OpenJDK code would fail to compile in a full build.

**Comment by gita-omr** [comment] 2019-10-07 20:47
Right, I am pretty sure I built JVM. I saw the tracing I inserted inside the port library.

**Comment by pshipton** [comment] 2019-10-08 21:08
Trying an xlc 13 build myself.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/65/

**Comment by gita-omr** [comment] 2019-10-08 21:45
Thanks @pshipton

**Comment by pshipton** [comment] 2019-10-08 22:39
Missed a step to set the VENDOR_REPO and BRANCH, try again
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/67/

**Comment by pshipton** [comment] 2019-10-09 02:54
It's not compiling because of harfbuzz code. I thought I applied the fix from jdk12. I'll have to check it and see if I missed something.

**Comment by pshipton** [comment] 2019-10-09 04:19
Still got illegal instruction as Gita said.
```
00:15:27  Optimizing the exploded image
00:15:32  /opt/freeware/bin/bash: line 1: 19202146 Illegal instruction
```

**Comment by gita-omr** [comment] 2019-10-09 14:44
Hm, so you excluded all these changes: https://github.com/eclipse/openj9/issues/5074#issuecomment-539181459  ?

**Comment by pshipton** [comment] 2019-10-09 14:52
No, but I don't see why they should be excluded. They only come into play when using xlc 16 but the build is using xlc 13. JDK12 and earlier still work with those changes and xlc 13. Need to do some brain storming what could be different with JDK13 that would affect the VM.

**Comment by pshipton** [comment] 2019-10-09 14:54
#7034 is not included in my build, as it's not a delivered change.

**Comment by pshipton** [comment] 2019-10-09 15:22
@gita-omr is there a particular change that seems suspect that I should remove and re-try?

**Comment by gita-omr** [comment] 2019-10-09 15:29
To be honest I would rather remove all of them and then do a binary search.

**Comment by gita-omr** [comment] 2019-10-09 15:35
If it passes with those removed, we will help with the binary search.

**Comment by pshipton** [comment] 2019-10-09 16:13
https://ci.eclipse.org/openj9/job/Build_JDK13_ppc64_aix_Personal/21/
Rebuild without the following
eclipse/omr#4087
eclipse/omr#4285

eclipse/omr#4099 and eclipse/omr#4119 are obsolete now.

**Comment by gita-omr** [comment] 2019-10-09 16:37
I am not sure how much I would bet on it :) but I am pretty sure it's the change in omrvmem.c in eclipse/omr#4087

**Comment by pshipton** [comment] 2019-10-09 16:38
Keep in mind we are running with that change for all other versions of java. Most of it isn't specific to any xlc version.

**Comment by gita-omr** [comment] 2019-10-09 16:39
A sign extension was introduced on some flags. We need to be careful either way.

**Comment by pshipton** [comment] 2019-10-09 16:42
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/72/
Rebuild without the OMR changes in https://github.com/eclipse/openj9/issues/5074#issuecomment-540073636 and also
#6584
#6694

As previously mentioned #7034 was already reverted.

**Comment by pshipton** [comment] 2019-10-09 17:30
both builds with the xlc 16 changes reverted still get "Illegal instruction".

**Comment by gita-omr** [comment] 2019-10-09 18:53
What is the harfbuzz fix? Is it the only thing that is still there?

**Comment by pshipton** [comment] 2019-10-09 19:49
harfbuzz is a graphical text shaping engine. It has nothing to do with this problem, but the code needs to be patched in order to compile with xlc 13. The code was patched in the jdk12 repo, but not the jdk13 repo because the patch isn't needed for xlc 16 compiles.

**Comment by zl-wang** [comment] 2019-10-09 20:21
This is very strange.  At this point, could I summarize the scenarios as follows?
1) same code base (let's limit to OpenJ9 and OMR), disregarding JCL and related natives;
2) on same machine with same compiler (xlC13)
3) essentially same makefile(s) ???

Java8/11/12 builds are fine, but Java13 is not.

**Comment by pshipton** [comment] 2019-10-09 20:28
Seems accurate.

**Comment by gita-omr** [comment] 2019-10-09 20:36
Should we try to build debug version? Will be easier to step through. E.g. we could break right after the code cache is allocated and try to jump there. Also will be interesting to see if it still fails.

**Comment by zl-wang** [comment] 2019-10-09 20:45
I went to confirm with AIX kernel folks:  what signal is mapped to, when executing from non-executable memory?  (we don't want to consider the scenario of non-synchronized iCache anymore, since we tested to confirm the PPCCodeSync routine executed on the memory in question)

Enlightening answer:  SIGILL     i.e.  somehow the JIT codecache is not executable (pages not marked executable) in Java13 build.

SED (Stack Execution Disable), if enabled, can cause writable-memory to be non-executable. But AIX default SED mode is "select"  (i.e.  SED is applied to selected programs).  I doubted so-far tested machines are set differently.  Not consider this anymore.

Maybe we should check for executable/shared-lib header flags (there is a deprecated F_NOEXEC flag).  This is remotely possible though (i.e. I wouldn't bet on this).

I can think of the last reason:  the allocated memory is not properly marked.  Wondering if we can read back the page-protection/permission flags after codeCache is allocated but some point before we start to execute from it.

**Comment by zl-wang** [comment] 2019-10-09 21:07
linker command is of course the problem ...  different options are used.

**Comment by gita-omr** [comment] 2019-10-09 21:09
Yes:
JDK8 link command:

/usr/vacpp/bin//xlc_r -q64 -q64 -brtl -bnolibpath -liconv -bexpall      -o /home/koblents/openj9-openjdk-jdk8/build/aix-ppc64-normal-server-release/jdk/objs/java_objs/java /home/koblents/openj9-openjdk-jdk8/build/aix-ppc64-normal-server-release/jdk/objs/java_objs/main.o   -L/home/koblents/openj9-openjdk-jdk8/build/aix-ppc64-normal-server-release/jdk/objs -ljli_static 

JDK13 link command:

( /opt/freeware/bin/rm -f /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/BUILD_LAUNCHER_java_link.log && /usr/vacpp/bin//xlc_r **-b64 -brtl -bnorwexec -bnolibpath -bexpall -bernotok -btextpsize:64K -bdatapsize:64K -bstackpsize:64K -q64** -L/home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base -o /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java_objs/java /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/main.o -ljli_static > >(/opt/freeware/bin/tee -a /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/BUILD_LAUNCHER_java_link.log) 2> >(/opt/freeware/bin/tee -a /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/BUILD_LAUNCHER_java_link.log >&2) || ( exitcode=$? && /opt/freeware/bin/cp /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/BUILD_LAUNCHER_java_link.log /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/make-support/failure-logs/support_native_java.base_java_BUILD_LAUNCHER_java_link.log && /opt/freeware/bin/cp /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/support/native/java.base/java/BUILD_LAUNCHER_java_link.cmdline /home/koblents/openj9-openjdk-jdk13/build/aix-ppc64-server-release/make-support/failure-logs/support_native_java.base_java_BUILD_LAUNCHER_java_link.cmdline && exit $exitcode ) ) ; 


Note the bunch of extra options and one of them: **-bnorwexec**

**Comment by pshipton** [comment] 2019-10-09 21:34
The change was https://github.com/ibmruntimes/openj9-openjdk-jdk13/commit/4684bdb39f02d0f39c170dab1639d6be0b5dd6d7

**Comment by gita-omr** [comment] 2019-10-09 21:44
I still a bit worry about the omrvmem.c change (eclipse/omr#4087), if it might cause some subtle issues in the future. But I don't know how the value is used really.

**Comment by zl-wang** [comment] 2019-10-10 12:37
FYI ...
I used ldedit to cancel F_NOEXEC on Peter's driver ... something like this:

milan:[zlwang] ldedit -b rwexec j9.64/bin/java
ldedit:  File j9.64/bin/java has been updated.

Now, I can run -version at least:

milan:[zlwang] j9.64/bin/java -version
openjdk version "13-internal" 2019-09-17
OpenJDK Runtime Environment (build 13-internal+0-adhoc.jenkins.openj9-openjdk-jdk13)
Eclipse OpenJ9 VM (build aixxlc16-2f6383c98, JRE 13 AIX ppc64-64-Bit Compressed References 20190923_000000 (JIT enabled, AOT enabled)
OpenJ9   - 2f6383c98
OMR      - 69029bae
JCL      - b4b82f558d based on jdk-13+33)

**Comment by zl-wang** [comment] 2019-10-10 13:10
I tested Peter's driver with jitt & vich on different options (count=0, hot, etc).  It was fine.

The running (of xlclang++ build) depends on the availability of libc++.so (LLVM version of std c++ lib). It is actually not available on most AIX installations.  So, the next immediate decision is about whether libc++ should be linked in statically.

As I had a suspicion before, it ran slower than I expected.  We need some detailed evaluations of its performance (especially JIT-compiler and GC).

**Comment by pshipton** [comment] 2019-10-10 14:04
@zl-wang note that build isn't a "final" build, the classes aren't in the correct format for fast loading, which would affect startup time, but not throughput.

**Comment by pshipton** [comment] 2019-10-11 15:03
@zl-wang how do you propose we fix this problem? Do we need to remove the link flag, or is there some way to set executable with the flag enabled. Strange that Hotspot can work with this flag.

**Comment by zl-wang** [comment] 2019-10-11 15:15
@pshipton yes, the straightforward fix is to remove that linker option (-bnorwexec).  i am not sure why it was put on in the first place.  F_NOEXEC was long deprecated.

**Comment by pshipton** [comment] 2019-10-11 15:26
@zl-wang I know it seems straightforward to remove `-bnorwexec`, but this is a patch to the OpenJDK code, which we are trying to avoid. Better to work around it in OpenJ9/OMR if possible.

The reason for the change is recorded as `8223307: enable the Stack Execution Disable flag for JDK binaries on AIX `, so in theory we are losing this stack execution protection by removing the flag.

**Comment by zl-wang** [comment] 2019-10-11 16:00
@pshipton  somebody read too much into SED (Stack Execution Disable) for HotSpot.  One characteristic of enforcing SED is writable and executable cannot co-exist on the same page. Thus, for java, it is a wrong reason (you have to write and execute from the same memory).
   SED enforcement doesn't depend on that XCOFF header flag at all (thus deprecated). There are SED-related XCOFF header flags:  system, request, and exempt. 
   sedmgr (SED manager) can set the global policy of a machine for SED (and do other things). If the global policy is "all" (SED enforced for all programs), we need to get java exempted (exempt flag) in order to run.  The default policy is "select"  (request SED for specific programs).
    Nothing is lost by removing that option.

**Comment by keithc-ca** [comment] 2019-10-11 16:01
The documentation for `shmget` at [1] suggests that it ought to fail with `EACCESS` when the flags include `S_IXUSR` set at [2], but it seems to just ignore `S_IXUSR` as it's not listed as a supported flag (it lists only 'subset of the access permissions that apply to files').

[1] https://www.ibm.com/support/knowledgecenter/beta/en/ssw_aix_72/s_bostechref/shmget.html
[2] https://github.com/eclipse/omr/blob/master/port/aix/omrvmem.c#L562

**Comment by keithc-ca** [comment] 2019-10-11 16:03
Would disabling write access after the code is produced allow execution? If pages are large, that isn't likely to be practical.

**Comment by zl-wang** [comment] 2019-10-11 16:13
it isn't practical at all. JIT runtime is patching JIT code regularly (for resolving, invalidation, and recompilation purposes).

**Comment by zl-wang** [comment] 2019-10-11 16:15
SED is a misnomer to me.  It really is Writable Execution Disable (WED).

**Comment by pshipton** [comment] 2019-10-11 17:29
If using the `-bnorwexec` flag is incorrect, we should be able to convince the OpenJDK project of the same and have the flag removed that way.
@andrew-m-leonard please see https://github.com/eclipse/openj9/issues/5074#issuecomment-541123269

**Comment by zl-wang** [comment] 2019-10-11 17:47
re using the strange option about HotSpot OpenJDK ... here is a trial for the latest java13 from Adopt:


-bash-5.0$ bin/java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:45), pid=8978666, tid=258
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  (13.0+33) (build )
# Java VM: OpenJDK 64-Bit Server VM (13+33, mixed mode, tiered, compressed oops, g1 gc, aix-ppc64)
# Core dump will be written. Default location: /home/zlwang/jdk-13+33/core or core.8978666
#
# An error report file with more information is saved as:
# /home/zlwang/jdk-13+33/hs_err_pid8978666.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
#
IOT/Abort trap (core dumped)

**Comment by zl-wang** [comment] 2019-10-11 17:50
hmm ... /#/ caused big faces of char(s)

**Comment by pshipton** [comment] 2019-10-11 17:53
and that Hotspot behavior is related to the global machine policy?

**Comment by zl-wang** [comment] 2019-10-11 17:54
no, i don't think so.

-bash-5.0$ sedmgr
Stack Execution Disable (SED) mode: select
SED configured in kernel: select

**Comment by pshipton** [comment] 2019-10-11 17:55
I'm thinking there must be something about the machine configuration which causes this. The Hotspot AIX build needed to run on the AdoptOpenJDK build machine in order to produce the published build.

**Comment by zl-wang** [comment] 2019-10-11 17:59
if it is SED related, SIGILL is expected.
Not sure if it is related to the OS level, i,.e  my OS level is backward relative to the build machine.

-bash-5.0$ oslevel -s
7100-04-01-1543

**Comment by pshipton** [comment] 2019-10-11 18:00
I just get `Dependent module libc++.a(shr_64.o) could not be loaded` but I'll look for a better machine.

**Comment by zl-wang** [comment] 2019-10-11 18:00
what is your OS level?

**Comment by keithc-ca** [comment] 2019-10-11 18:07
> I'm thinking there must be something about the machine configuration which causes this. The Hotspot AIX build needed to run on the AdoptOpenJDK build machine in order to produce the published build.

If AdoptOpenJDK uses jdk12 as the bootjdk, then it doesn't tell us that. That option is not used to build jdk12.

**Comment by keithc-ca** [comment] 2019-10-11 18:27
> If AdoptOpenJDK uses jdk12 as the bootjdk, then it doesn't tell us that. That option is not used to build jdk12.

But, as @pshipton reminded me privately, the build jdk *is* used so the option is relevant.

**Comment by pshipton** [comment] 2019-10-11 18:30
I'm on AIX 7.1 
On another 7.1 machine, which must have libc++.a I just get the same core dump.

**Comment by pshipton** [comment] 2019-10-11 18:33
Here is an JDK13 AIX build at Adopt, which was able to run -verison
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-aix-ppc64-hotspot/79/ but not sure what is different to allow this.
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33-201909260508)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33-201909260508, mixed mode)
```

**Comment by gita-omr** [comment] 2019-10-11 18:36
Is there any way to see if it JITted any methods?

**Comment by pshipton** [comment] 2019-10-11 18:45
Google found http://www.herongyang.com/JVM/Micro-Benchmark-Watch-JIT-Compilation-Log.html
but first we need to be able to successfully run the JVM on some machine.

**Comment by zl-wang** [comment] 2019-10-11 18:46
I tested that adopt HS driver ... same core dump.  I used ldedit to reset rwexec ... still same core dump.  So, it is not related to that linker option in this case.

**Comment by zl-wang** [comment] 2019-10-11 18:50
Looking at AIX header file more closely, F_NOEXEC (is deprecated) is reused for SED system/request/exempt flags.  -bnorwexec actualy set request (i.e. disregarding global SED policy, SED is enforced).

**Comment by pshipton** [comment] 2019-10-11 18:52
Ok, so back the original question then, how does OpenJ9 bypass SED in order to create a working code cache?

**Comment by zl-wang** [comment] 2019-10-11 18:53
I looked at the header section dump of HS java as well.  request is set (i.e. -bnorwexec).  so, I predicted:  even if you can get past the SIGABRT dump, you will see SIGILL next.

**Comment by pshipton** [comment] 2019-10-11 18:55
Yet somehow it runs -version on the AdoptOpenJDK machine.

**Comment by zl-wang** [comment] 2019-10-11 18:56
SED can be disabled globally on that machine.  run:   sedmgr     to see

**Comment by zl-wang** [comment] 2019-10-11 18:59
-bnorwexec is a contradictory to JIT period.  if you want to continue using that option, either:
1) disable SED globally on the machine;  or
2) exempt java explicitly (i.e. reset -bnorwexec)

**Comment by pshipton** [comment] 2019-10-11 19:05
I don't have access to the machines at Adopt, or any root access to any AIX machines.

**Comment by zl-wang** [comment] 2019-10-11 19:09
btw, sedmgr doesn't need root authority to run.  but you don't have accesses at all, no help.

**Comment by pshipton** [comment] 2019-10-11 19:10
I'll see if Shelley or somebody else can run sedmgr for us.

**Comment by andrew-m-leonard** [comment] 2019-10-14 13:06
```

**Comment by zl-wang** [comment] 2019-10-16 20:12
@pshipton  we asked xlC team, and they cannot fix it (linking in libc++.a by default), since the same command can be used for xlC build (as opposed to xlclang++ build) which doesn't need libc++.a.

we have to decide if libc++.a should be statically linked in as well (it is not available on most AIX installations).

**Comment by pshipton** [comment] 2019-10-16 20:25
@zl-wang is seems we have the start of a solution https://github.com/eclipse/openj9/pull/7034#issuecomment-542759782
Yes, it should be statically linked.

**Comment by pshipton** [comment] 2019-10-17 12:19
I ran an AIX build/test with xlc 13 with the OpenJDK 13.0.0 level. Besides the OpenJ9 change to compile with xlc 13, this requires the harfbuzz fix which was applied to openjdk12 to be applied to openjdk13. The standard functional and system testing passed.
https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-Release-Build/77

I'll have to retry this with the 13.0.1 level when it promotes. Using xlc 13 is fragile, as OpenJDK changes could break this at any time. i.e. even if it works for 13.0.1, it may not work for 13.0.2 in January. We can also try this with the jdk14 code to date.

I'll also try a xlc 16 build. This build won't have DDR support so test failures are expected, but we can see if anything else fails.

**Comment by pshipton** [comment] 2019-10-17 22:13
With xlc 16 we only got the expected DDR failures, all the other standard testing passed.

**Comment by pshipton** [comment] 2019-10-18 02:37
xlc 13 with jdk13.0.1 compiled fine. I didn't bother with testing.
https://ci.eclipse.org/openj9/job/Pipeline-Release-Build/80

**Comment by zl-wang** [comment] 2019-10-18 13:56
I have a preliminary performance tests of xlc13/16 builds (performance of C/C++ code, that is:  interpreter and JIT-compiler specifically).  I used javac helloWorld as the test case:  -Xint and -Xjit:count=0,optLevel=hot -Xnoaot (to exercise JIT-compiler).

-Xint run, xlc16 build looks 15% better;
JIT-compiler run, xlc13 build looks 8% better.

**Comment by zl-wang** [comment] 2019-10-18 14:00
Overall, I felt xlclang++ build is fine perf-wise.  Although, it has the glitch that I have to copy libc++.a and related to where I ran (and set LIBPATH).

**Comment by pshipton** [comment] 2019-10-18 14:31
As per https://github.com/eclipse/openj9/pull/7499, we are statically linking libc++

**Comment by zl-wang** [comment] 2019-10-18 14:35
you meant the xlc16 build link you gave above is supposed to be built with static linking already?

**Comment by pshipton** [comment] 2019-10-18 14:44
> you meant the xlc16 build link you gave above is supposed to be built with static linking already?

No, my earlier build wasn't statically linked. We are delivering a change to statically link in future builds. I'll provide a link to the build when it's ready.

**Comment by pshipton** [comment] 2019-10-18 16:37
Here is a statically linked xlc 16 build https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK13_ppc64_aix_Personal/36/OpenJ9-JDK13-ppc64_aix-20191018-143648.tar.gz

**Comment by pshipton** [comment] 2019-10-18 18:13
It's more than just the JIT which is linking to libc++ now, see https://github.com/eclipse/openj9/pull/7499#issuecomment-543867064, plus I don't think the JIT is statically linking properly yet, see https://github.com/eclipse/openj9/pull/7499#issuecomment-543864380

**Comment by pshipton** [comment] 2019-10-21 03:10
Seems jdk14 no longer supports compilation with xlc 13
`configure: error: xlclang++ version output check failed, output: /home/u0020236/workspace/Build_JDKnext_ppc64_aix_Personal/build/.configure-support/generated-configure.sh: line 40731: xlclang++: command not found`

**Comment by pshipton** [comment] 2019-12-12 23:21
#8055 is merged, DDR is enabled on AIX Java 13+, this is now complete, although #7579 is still open,

**Closed by pshipton** 2019-12-12 23:21 UTC
Labels: comp:build, userRaised
