### ISSUE TITLE
Smooth migration story:  JDK tools

### ISSUE THREAD

**Issue by zl-wang** [eclipse/openj9#5424] opened 2019-04-09 19:06 UTC
We were repeatedly asked by customers for JDK tools which are missing in OpenJ9.  List in order of importance (roughly):

jstack
jps
jstat
jinfo

**Comment by DanHeidinga** [comment] 2019-04-09 19:10
This is a duplicate of https://github.com/eclipse/openj9/issues/4655

**Closed by DanHeidinga** 2019-04-09 19:10 UTC
