### ISSUE TITLE
J9 throws a verify error (stack shape inconsistent), while HotSpot does not

### ISSUE THREAD

**Issue by myspringchen** [eclipse/openj9#302] opened 2017-10-12 09:00 UTC
J9 throws a verify error for the next file, while OpenJDK's HotSpot can run the app without throwing verifyerrors. I'm not very sure whether J9 is too strict for this.

Besides, if you cannot reproduce the difference or it is HotSpot's error, please also let me know.

How to reproduce: 
(1) download the file https://jbox.sjtu.edu.cn/l/xnc5De and unzip it.
(2) run: java Harness fop
(3) Result: 
IBM's jvm (build 2.9; J9VM - d56eb84) throws a VerifyError; HotSpot (build 9+181) fails to throw this error?
Reason: The count of local variables in the stackmap frame is less than 0

**Comment by ChengJin01** [comment] 2017-10-12 12:46
Will investigate what was happening in there.

**Comment by DanHeidinga** [comment] 2017-10-12 13:25
@ChengJin01 Please check both J9 and Hotspot using `-Xfuture` as that matches the level of verification done when JCKing the JVM.

**Comment by ChengJin01** [comment] 2017-10-12 16:52
The results on our build and Hotspot indicates:

1) Hotspot always works with and without -Xfuture
jdk-9_142/bin/java  -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+142)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+142, mixed mode)

[1] /jdk-9_142/bin/java  -Xfuture  Harness fop
===== DaCapo unknown fop starting =====
===== DaCapo unknown fop PASSED in 794 msec =====

[2] /jdk-9_142/bin/java  Harness fop
===== DaCapo unknown fop starting =====
===== DaCapo unknown fop PASSED in 748 msec =====

2) Our build always fails with / without -Xfuture
[1] xa6490/bin/java -Xfuture  Harness fop
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-internal/Native Method)
...
Caused by: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=org/apache/fop/cli/Main, method=startFOP([Ljava/lang/String;)V, pc=0
Exception Details:
  Location:
    org/apache/fop/cli/Main.startFOP([Ljava/lang/String;)V @0: JBldcw
  Reason:
    The count of local varibles in the stackmap frame is less than 0.
  Current Frame:
    bci: @0
    flags: { }
    locals: { top }
    stack: { }
  Exception Handler Table:
...

[2] xa6490/bin/java  Harness fop
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-internal/Native Method)
...
Caused by: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=org/apache/fop/cli/Main, method=startFOP([Ljava/lang/String;)V, pc=0
Exception Details:
  Location:
    org/apache/fop/cli/Main.startFOP([Ljava/lang/String;)V @0: JBldcw
  Reason:
    The count of local varibles in the stackmap frame is less than 0.
  Current Frame:
    bci: @0
    flags: { }
    locals: { top }
    stack: { }
  Exception Handler Table:
...

**Comment by ChengJin01** [comment] 2017-10-12 22:05
It seems the issue was caused by the incorrect count of local variables when decompressing the stackmap data in verifier as follows:

/runtime/bcverify/bcverify.c
parseLocals (J9BytecodeVerificationData * verifyData, U_8** stackMapData, J9BranchTargetStack * liveStack, IDATA localDelta, IDATA localsCount, IDATA maxLocals)
{
...
	if (localDelta < 0) {
		/* Clear the chopped elements */
		for (;localDelta; localDelta++) {
			localsCount--;
			if (localsCount < 0) {
				goto _underflow;
			}
			liveStack->stackElements[localsCount] = BCV_BASE_TYPE_TOP;
      ...                 
                        <---------- localsCount is set to 0
			stackEntry = liveStack->stackElements[localsCount - 1];
<---------- the code following that was totally mess up with liveStack->stackElements[-1]

			if ((BCV_BASE_TYPE_DOUBLE == stackEntry) || (BCV_BASE_TYPE_LONG == stackEntry)) {
				localsCount--;
				if (localsCount < 0) {
					goto _underflow; <-------------- unexpectedly captured here
				}
				liveStack->stackElements[localsCount] = BCV_BASE_TYPE_TOP;
			}

I already created a fix for the issue (it works for the benchmark)
/xa6490/bin/java Harness fop
===== DaCapo unknown fop starting =====
===== DaCapo unknown fop PASSED in 904 msec =====

/xa6490/bin/java -Xfuture  Harness fop
===== DaCapo unknown fop starting =====
===== DaCapo unknown fop PASSED in 751 msec =====

-------------------------
However,  a couple of JCK test case failures were triggered by the fix. 
Need to figure out what was wrong in the code changes.

**Comment by BrijeshNekkare** [comment] 2017-10-13 03:44
In verifyerror output, varibles should be spelt as variables

**Comment by ChengJin01** [comment] 2017-10-13 04:38
@BrijeshNekkare,
Thanks for reminder. Will update the output.

**Comment by myspringchen** [comment] 2017-12-13 08:15
Hi, ChengJin01, may you check the issue 811: [https://github.com/eclipse/openj9/issues/811]
I happened to hit the crash yesterday.

**Comment by ChengJin01** [comment] 2017-12-13 17:36
@myspringchen, 

I already tried with the latest build on linux at https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9 and it ended up with pretty much the same result as Oracle.  Please try with the latest build to double-check.

**Comment by myspringchen** [comment] 2017-12-14 06:06
@ChengJin01 
Thank you for sharing the latest build. I used the latest build and found that the issue 302 was not really fixed. Please test this case: [https://jbox.sjtu.edu.cn/l/toTT74](https://jbox.sjtu.edu.cn/l/toTT74), where OpenJ9 throws a verifyerror and HotSpot does not. Please recheck the instruction "JBbipush".

**Comment by ChengJin01** [comment] 2017-12-14 14:02
@myspringchen, 

It doesn't surprise me because the fix for issue 302 at https://github.com/eclipse/openj9/pull/324 has not yet merged to the build.  (still pending for review).  You need to verify your test after the fix gets merged.

**Closed** 2017-12-20 04:12 UTC
Labels: bug, comp:vm
