### ISSUE TITLE
Segmentation error on openj9-0.14.0 / JRE 1.8.0_212-b03 (x32) / Windows 7 - openssl MessageDigest

### ISSUE THREAD

**Issue by MNeuling** [eclipse/openj9#5611] opened 2019-04-25 10:03 UTC
Java -version output
--------------------
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b03)
Eclipse OpenJ9 VM (build openj9-0.14.0, JRE 1.8.0 Windows 7 x86-32-Bit 20190417_206 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 5590c4f818 based on jdk8u212-b03)

[javacore.20190424.151032.13012.0002.txt](https://github.com/eclipse/openj9/files/3116196/javacore.20190424.151032.13012.0002.txt)

[openj9-segmentation-error-dump.zip](https://github.com/eclipse/openj9/files/3116244/openj9-segmentation-error-dump.zip)

Summary of problem
------------------
If I start multiple instances of my application I get a segmentation error.
 
Diagnostic files
----------------
I have attached a zip file containing all dumps except the core dump since its size is 246 MB (compressed zip 47,1 MB / 7-zip 34,4 MB).

```bash
2019-04-24 15:10:31 FINEST sun.net.www.protocol.https.HttpsClient New Looking for HttpClient for URL https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz and proxy value of DIRECT
2019-04-24 15:10:31 FINEST sun.net.www.protocol.https.HttpsClient <init> Creating new HttpsClient with url:https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz and proxy:DIRECT with connect timeout:10000
Unhandled exception
Type=Segmentation error vmState=0x00000000
J9Generic_Signal_Number=00000004 ExceptionCode=c0000005 ExceptionAddress=1490123C ContextFlags=0001007f
Handler1=53166590 Handler2=62658580 DEPAddress=1490123C
EDI=0ABE4668 ESI=0E1CF000 EAX=1490123C EBX=00E92570
ECX=00361FF0 EDX=0E1CF04C
EIP=1490123C ESP=0E60F6B8 EBP=0E60F6D4 EFLAGS=00010202
GS=002B FS=0053 ES=002B DS=002B
Module=
Module_base_address=13A10000 Offset_in_DLL=00ef123c
Target=2_90_20190417_206 (Windows 7 6.1 build 7601 Service Pack 1)
CPU=x86 (8 logical CPUs) (0x7f9c9b000 RAM)
----------- Stack Backtrace -----------
2019-04-24 15:10:31 FINE sun.net.www.protocol.http.HttpURLConnection writeRequests sun.net.www.MessageHeader@59765a5a5 pairs: {GET /JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz HTTP/1.1: null}{User-Agent: Java/1.8.0_212}{Host: wwwt.gegis.net}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
2019-04-24 15:10:31 FINEST sun.net.www.http.HttpClient logFinest KeepAlive stream used: https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz
2019-04-24 15:10:31 FINE sun.net.www.protocol.http.HttpURLConnection getInputStream0 sun.net.www.MessageHeader@e4087afd8 pairs: {null: HTTP/1.1 404 Not Found}{Date: Wed, 24 Apr 2019 13:10:31 GMT}{Server: Apache-Coyote/1.1}{Strict-Transport-Security: max-age=31556926}{Content-Type: text/html;charset=utf-8}{Content-Length: 1168}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}
2019-04-24 15:10:31 INFO com.dakosy.client.distribution.util.DownloadUtils download Downloading file from URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz' to file 'E:\tmp\download-5286746948652717760.tmp' without caches.
2019-04-24 15:10:31 FINEST com.dakosy.client.distribution.util.DownloadUtils download Start download file from URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz'...
2019-04-24 15:10:31 FINEST com.dakosy.client.distribution.util.ProxyConfig detectProxy Proxy for URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz' is 'DIRECT'.
2019-04-24 15:10:31 FINEST com.dakosy.client.distribution.util.ProxyConfig getProxy No proxy proxy 'DIRECT'!
2019-04-24 15:10:31 FINEST sun.net.www.protocol.https.HttpsClient New Looking for HttpClient for URL https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz and proxy value of DIRECT
2019-04-24 15:10:32 FINEST sun.net.www.protocol.https.HttpsClient <init> Creating new HttpsClient with url:https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz and proxy:DIRECT with connect timeout:10000
(0x1490123C)
_Java_jdk_crypto_jniprovider_NativeCrypto_DigestUpdate@28+0x4a (0x6F8D11D3 [jncrypto+0x11d3])
WaitForSingleObjectEx+0xcb (0x778D165C [KERNELBASE+0x1165c])
(0x53155885 [j9vm29+0x65885])
---------------------------------------
JVMDUMP039I Speicherauszugsereignis "gpf", Detail "" um 2019/04/24 15:10:32 - bitte warten.
2019-04-24 15:10:32 FINE sun.net.www.protocol.http.HttpURLConnection writeRequests sun.net.www.MessageHeader@3e459cdb7 pairs: {GET /JGegis/net/JGegisClientMainNet-4.4.5-


SNAPSHOT.jar.pack.gz HTTP/1.1: null}{Cache-Control: no-cache}{Pragma: no-cache}{User-Agent: Java/1.8.0_212}{Host: wwwt.gegis.net}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von System mit "C:\Program Files (x86)\DAKOSY\AppStart\core.20190424.151032.13012.0001.dmp" an
2019-04-24 15:10:32 FINEST sun.net.www.http.HttpClient logFinest KeepAlive stream used: https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar.pack.gz
2019-04-24 15:10:32 FINE sun.net.www.protocol.http.HttpURLConnection getInputStream0 sun.net.www.MessageHeader@aa66083b8 pairs: {null: HTTP/1.1 404 Not Found}{Date: Wed, 24 Apr 2019 13:10:31 GMT}{Server: Apache-Coyote/1.1}{Strict-Transport-Security: max-age=31556926}{Content-Type: text/html;charset=utf-8}{Content-Length: 1168}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}
JVMDUMP030W Speicherauszug kann nicht in Datei C:\Program Files (x86)\DAKOSY\AppStart\core.20190424.151032.13012.0001.dmp geschrieben werden: (5) Zugriff verweigert
2019-04-24 15:10:32 INFO com.dakosy.client.distribution.util.DownloadUtils download Downloading file from URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar' to file 'C:\ProgramData\DAKOSY\AppStart\app\924c6da2c21b43044d78fa6c5db14e3d0aceea48d2ce966cdf7478e4e9f8fafa\content\net\JGegisClientMainNet-4.4.5-SNAPSHOT.jar' with caches.
2019-04-24 15:10:32 FINEST com.dakosy.client.distribution.util.DownloadUtils download Start download file from URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar'...
2019-04-24 15:10:32 FINEST com.dakosy.client.distribution.util.ProxyConfig detectProxy Proxy for URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar' is 'DIRECT'.
2019-04-24 15:10:32 FINEST com.dakosy.client.distribution.util.ProxyConfig getProxy No proxy proxy 'DIRECT'!
2019-04-24 15:10:32 FINEST sun.net.www.protocol.https.HttpsClient New Looking for HttpClient for URL https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar and proxy value of DIRECT
2019-04-24 15:10:32 FINEST sun.net.www.protocol.https.HttpsClient <init> Creating new HttpsClient with url:https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar and proxy:DIRECT with connect timeout:10000
2019-04-24 15:10:32 FINE sun.net.www.protocol.http.HttpURLConnection writeRequests sun.net.www.MessageHeader@42eb5a435 pairs: {GET /JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar HTTP/1.1: null}{User-Agent: Java/1.8.0_212}{Host: wwwt.gegis.net}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
2019-04-24 15:10:32 FINEST sun.net.www.http.HttpClient logFinest KeepAlive stream used: https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar
2019-04-24 15:10:32 FINE sun.net.www.protocol.http.HttpURLConnection getInputStream0 sun.net.www.MessageHeader@5cbc54be11 pairs: {null: HTTP/1.1 200 OK}{Date: Wed, 24 Apr 2019 13:10:31 GMT}{Server: Apache-Coyote/1.1}{Strict-Transport-Security: max-age=31556926}{Accept-Ranges: bytes}{ETag: W/"30935-1556108438000"}{Last-Modified: Wed, 24 Apr 2019 12:20:38 GMT}{Content-Type: application/java-archive}{Content-Length: 30935}{Keep-Alive: timeout=5, max=100}{Connection: Keep-Alive}
2019-04-24 15:10:32 FINEST com.dakosy.client.distribution.util.DownloadUtils download End download file from URL 'https://wwwt.gegis.net/JGegis/net/JGegisClientMainNet-4.4.5-SNAPSHOT.jar'.
JVMDUMP010I Speicherauszug von System in E:\tmp\core.20190424.151032.13012.0001.dmp geschrieben
JVMDUMP030W Speicherauszug kann nicht in Datei C:\Program Files (x86)\DAKOSY\AppStart\javacore.20190424.151032.13012.0002.txt geschrieben werden: (5) Zugriff verweigert
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Java mit "E:\tmp\javacore.20190424.151032.13012.0002.txt" an
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@591f94a0,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=1
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=2
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@cd59040c,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=2
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=3
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@8fa0c00c,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=3
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=4
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@9fa516a6,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=4
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=5
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@52795c84,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=5
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=6
2019-04-24 15:10:33 FINEST java.awt.EventDispatchThread pumpOneEventForFilters Dispatching: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.dakosy.client.distribution.main.ProgressSplash$$Lambda$31/0F8DD6D0@2cd7cd68,notifier=null,catchExceptions=false,when=1556111431947] on sun.awt.windows.WToolkit@244ea5e0
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar before max=68 / value=6
2019-04-24 15:10:33 WARNING com.dakosy.client.distribution.main.ProgressSplash lambda$execOnEDT$7 ProgressBar after max=68 / value=7
JVMDUMP010I Speicherauszug von Java in E:\tmp\javacore.20190424.151032.13012.0002.txt geschrieben
JVMDUMP032I JVM forderte als Antwort auf ein Ereignis einen Speicherauszug von Snap mit "C:\Program Files (x86)\DAKOSY\AppStart\Snap.20190424.151032.13012.0003.trc" an
JVMDUMP030W Speicherauszug kann nicht in Datei C:\Program Files (x86)\DAKOSY\AppStart\Snap.20190424.151032.13012.0003.trc geschrieben werden: (5) Zugriff verweigert
JVMDUMP010I Speicherauszug von Snap in E:\tmp\Snap.20190424.151032.13012.0003.trc geschrieben
JVMDUMP030W Speicherauszug kann nicht in Datei C:\Program Files (x86)\DAKOSY\AppStart\jitdump.20190424.151032.13012.0004.dmp geschrieben werden: (5) Zugriff verweigert
JVMDUMP007I JVM fordert JIT-Speicherauszug mit "E:\tmp\jitdump.20190424.151032.13012.0004.dmp" an.
JVMDUMP010I Speicherauszug von JIT in E:\tmp\jitdump.20190424.151032.13012.0004.dmp geschrieben
JVMDUMP013I Speicherauszugsereignis "gpf", Detail "" wurde verarbeitet.

```

OutOfMemoryError: Java Heap Space
---------------------------------
In the log file is no OutOfMemory condition reported.

**Comment by pshipton** [comment] 2019-04-25 15:01
@jerrylui803 @ashbm5

**Comment by pshipton** [comment] 2019-05-01 15:09
@vij-singh fyi

**Comment by ashbm5** [comment] 2019-05-01 15:19
@MNeuling try running your program with command line option -Djdk.nativeDigest=false does it still crash?

**Comment by MNeuling** [comment] 2019-05-02 16:52
@ashbm5 Yes it works if the program runs with the command line option.

On JRE 1.8.0_202-b08 (x32) the command line option is not needed.

**Comment by ashbm5** [comment] 2019-05-03 15:47
@MNeuling is there anything printed to the screen saying OpenSSL error? can you re-run your application with the tracing flag -Djavax.net.debug=all and pipe it to a file and attach here.

**Comment by MNeuling** [comment] 2019-05-03 17:57
@ashbm5 I ran the program again with option -Djavax.net.debug=all and without option-Djdk.nativeDigest=false.

Here are two files. The first one has only net traffic dumps and the second one includes logging messages.

[log.txt](https://github.com/eclipse/openj9/files/3143031/log.txt)
[cli_log.txt](https://github.com/eclipse/openj9/files/3143032/cli_log.txt)

**Comment by MNeuling** [comment] 2019-05-03 18:07
@ashbm5 these are the logs of another run.

[second_run_log.txt](https://github.com/eclipse/openj9/files/3143078/second_run_log.txt)
[second_run_cli_log.txt](https://github.com/eclipse/openj9/files/3143081/second_run_cli_log.txt)

**Comment by MNeuling** [comment] 2019-05-03 18:13
@ashbm5 the TLS version is 1.2 and the cipher suite is TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384.

**Comment by ashbm5** [comment] 2019-05-09 16:22
@MNeuling I'm trying to create a test case that reproduces this problem, would you be able to create one for me that shows this issue? or perhaps describe the behavior of the testcase. Looks like the problem is induced by the TLS/SSL code - perhaps you have multple threads creating TLS connections?

**Comment by MNeuling** [comment] 2019-05-10 17:34
@ashbm5 Yes the program uses multiple threads createing TLS connections to download files. It works as long as you only start a single vm instance of the program and multithreading also works fine.

The problem occurs if you start another vm instance running the program. In that vm instance and every new vm instance the problem occurs.

**Comment by MNeuling** [comment] 2019-05-10 18:00
@ashbm5 It is not realy easy to reproduce the problem. The program launcher for client application. It downloads applications and start them. There are different applications to download. 
Most of them work if you launch multiple application instances. It is only a single application that where the problem occurs.
Allways you launch a second instance of the application and the launcher has always a problem to download the same artefact via TLS.

**Comment by pshipton** [comment] 2019-05-15 14:59
The MessageDigest native crypto has been disabled in the 0.14.2 release branches.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/299
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/171

**Comment by DanHeidinga** [comment] 2019-06-04 18:19
@ashbm5 @vij-singh Any progress on this?  We're coming up on the deadlines for 0.15

**Comment by vij-singh** [comment] 2019-06-05 16:44
@ashbm5 Can you comment please?

**Comment by ashbm5** [comment] 2019-06-05 17:40
@DanHeidinga it looks like the issue is related to MessageDigest's native resources being released before they should be, perhaps due to object resurrection. Unfortunately thus far I've been unable to reproduce this issue myself, my current plan is to re-write MessageDigest's native resources management code and shift it from using finalizers to phantom references which should give us a safer mechanism to resource native openssl contexts.

**Comment by DanHeidinga** [comment] 2019-06-05 18:11
We're going to do the code split for `0.15.0` on June 24th

**Comment by DanHeidinga** [comment] 2019-06-11 14:00
@ashbm5 ping?  Is this likely to be ready for the June 24th code split?

**Comment by DanHeidinga** [comment] 2019-06-18 18:44
@ashbm5 Any update on this?

**Comment by pshipton** [comment] 2019-06-18 20:18
Disabling MessageDigest for the 0.15 release and beyond, until this is resolved.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/318
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/190
https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/59

**Comment by ashbm5** [comment] 2019-06-19 02:19
@DanHeidinga nearly done with the code, will likely open a PR tomorrow - didn't do any testing yet.

**Comment by pshipton** [comment] 2019-06-19 13:16
@ashbm5 reminder the code split occurs from Sunday night (June 23).

**Comment by pshipton** [comment] 2019-06-20 12:00
Doesn't seem like the fix will be ready in time. Moving to the 0.16 milestone and disabling MessageDigest for now (https://github.com/eclipse/openj9/issues/5611#issuecomment-503295467).

**Comment by pshipton** [comment] 2019-08-23 13:38
The MessageDigest support has been updated and re-enabled.
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/324
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/191
https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/69
https://github.com/ibmruntimes/openj9-openjdk-jdk13/pull/9
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/129

**Closed by pshipton** 2019-08-23 13:38 UTC
Labels: userRaised
