### ISSUE TITLE
URLClassLoder and -Dibm.cl.verbose=* problem when running using Java 9

### ISSUE THREAD

**Issue by ZhangLi1021** [eclipse/openj9#1382] opened 2018-03-08 08:27 UTC
This is z/OS XML team.
Our product is compiled using Java8 and executed using Java 8 and Java 9.
1. URLClassLoader ucl = (URLClassLoader)ClassLoader.getSystemClassLoader(); This line is executed right using Java8. But failed on Java 9, no error information is reported. 
If changing the line to be "ClassLoader ucl = ClassLoader.getSystemClassLoader();", no error occurred.
2. I use "URLClassLoader cl = new URLClassLoader(urls);" to load jar package dynamically in code.
Then running command line "java TestJosrGen /u/zhangli/a.xsd /u/zhangli/a6.osr"
When running in java 8, everything is OK.
When running in Java 9, the following error is reported.
K0319javax.xml.transform.TransformerFactoryConfigurationError: Provider org.apache.xalan.processor.TransformerFactoryImpl not found
	at javax.xml.transform.FactoryFinder.newInstance(java.xml@9-internal/FactoryFinder.java:198)
	at javax.xml.transform.FactoryFinder.find(java.xml@9-internal/FactoryFinder.java:275)
	at javax.xml.transform.TransformerFactory.newInstance(java.xml@9-internal/TransformerFactory.java:137)
	at com.ibm.xml.xlxp.xmlGenerator.impl.XMLGeneratorImpl.generate(XMLGeneratorImpl.java:249)
	at com.ibm.zos.xml.gxlOSRGenImpl.genSchemaXML(gxlOSRGenImpl.java:789)
	at com.ibm.zos.xml.gxlOSRGenImpl.genOSR(gxlOSRGenImpl.java:596)
	at TestJosrGen.main(TestJosrGen.java:10)
Caused by: java.lang.ClassNotFoundException: org.apache.xalan.processor.TransformerFactoryImpl
	at java.lang.Class.forNameImpl(java.base@9-internal/Native Method)
	at java.lang.Class.forName(java.base@9-internal/Class.java:368)
	at javax.xml.transform.FactoryFinder.getProviderClass(java.xml@9-internal/FactoryFinder.java:138)
	at javax.xml.transform.FactoryFinder.newInstance(java.xml@9-internal/FactoryFinder.java:180)
	... 6 more
3. I used "java -Dibm.cl.verbose=* TestJosrGen /u/zhangli/a.xsd /u/zhangli/a6.osr" to debug the above problem, the following error occurred. We do not use com.ibm.jvm.ClassLoaderDiagnosticsHelper in our code. So the following error is caused by -Dibm.cl.verbose. If Java 9 does not support this option, how I debug the above problem?
K0319java.lang.NoClassDefFoundError: com.ibm.jvm.ClassLoaderDiagnosticsHelper
	at java.net.URLClassLoader.findClass(java.base@9-internal/URLClassLoader.java:670)
	at java.lang.ClassLoader.loadClassHelper(java.base@9-internal/ClassLoader.java:1123)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:1043)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:1026)
	at com.ibm.zos.xml.gxlOSRGenerator.newOSRGenerator(gxlOSRGenerator.java:214)
	at TestJosrGen.main(TestJosrGen.java:8)
Caused by: java.lang.ClassNotFoundException: com.ibm.jvm.ClassLoaderDiagnosticsHelper
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:1022)
	... 6 more

I just want to load jar package dynamically in our code. I wrote 2 version of code. Each can be successful in Java 8. But all failed in Java 9. The first problem is for the first version. The second problem is for the second version.

**Comment by pshipton** [comment] 2018-03-08 12:14
Hi Lily. Java 9 is not compatible with Java 8. This is by design and its not something that will be "fixed" in Java 9. Your application needs to be fixed instead.

1. This is a problem with your application. In Java 9 ClassLoader.getSystemClassLoader() is no longer a subclass of URLClassLoader.

2. org.apache.xalan is part of IBM Java 8, but is not included in Java 9. I intended to direct you to IBM's migration guide https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.multiplatform.90.doc/user/compatibility_xml.html, but I see org.apache.xalan is not listed there. You need to include org.apache in your app if it is required.

3. This is a problem with your application, com.ibm.jvm.ClassLoaderDiagnosticsHelper is not part of Java 9, and -Dibm.cl.verbose is not supported by Java 9. Please let me know what API in com.ibm.jvm.ClassLoaderDiagnosticsHelper is being called by your app, but I don't expect this information to change anything.

**Comment by ZhangLi1021** [comment] 2018-03-09 02:56
Hi Peter,

I forgot to tell that Java 8 I used is the one that without xml.jar. I
removed xml.jar in Java 8 myself.
Since org.apache.xalan is not part of IBM Java 9, I package it along with
other class in xml.jar in a jar called gxlxml.jar. We do not want to change
customer behavior. So We want to load gxlxml.jar dynamically in our code
but not ask customers to add gxlxml.jar in their CLASSPATH.
To implement this, first I write the following code.
      URLClassLoader ucl = (URLClassLoader)ClassLoader.getSystemClassLoader
();
      Method add = URLClassLoader.class.getDeclaredMethod("addURL", new
Class[]{URL.class});
      add.setAccessible(true);
      add.invoke(ucl, xmlURLs[0]);

From your information, I know this code is not supported by Java 9. Then I
wrote the following code:

      urls[0]= new URL(urlStr+"gxlxml.jar");
      URLClassLoader cl = new URLClassLoader(urls);

In Java 8 without xml.jar, java.net.URLClassLoader found
org.apache.xalan.processor.TransformerFactoryImp.  But in Java 9, this
class can not be found. And I don't know how to debug this. Is there other
option instead of -Dibm.cl.verbose? This is the log printed by
-Dibm.cl.verbose in Java 8 without xml.jar.

java.net.URLClassLoader attempting to find
org.apache.xalan.processor.TransformerFactoryImpl
java.net.URLClassLoader using
classpath /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jar:/u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jar:/u/zhan
gli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jar
java.net.URLClassLoader could not find
org/apache/xalan/processor/TransformerFactoryImpl.class
in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jar
java.net.URLClassLoader could not find
org/apache/xalan/processor/TransformerFactoryImpl.class
in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jar
java.net.URLClassLoader found
org/apache/xalan/processor/TransformerFactoryImpl.class
in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jar


I am not familiar with how to load jar package dynamically in Java 9 just
like the jar package is added in CLASSPATH. It's very appreciated if you
can give me some advice on this.
Thanks very much!

Lily
zXML, CSL

**Comment by ZhangLi1021** [comment] 2018-03-09 05:21
Hi Lily,
 
> We want to load gxlxml.jar dynamically in our code
 
To provide a proper answer I need to understand how your code gets loaded. Is the idea to modify the JVM?
 
An easy migration is to put  gxlxml.jar on the module path, which will create an automatic module which is visible to everything on the class path. You can read about modularity and automatic modules here http://openjdk.java.net/projects/jigsaw/spec/sotms/
 
java --module-path gxlxml.jar ...
 
A better solution is to create a module-info.java in order to define a proper module. See also the modularity quick start guide http://openjdk.java.net/projects/jigsaw/quick-start
 
Peter
 
----- Original message -----From: Li EF Zhang/China/IBMTo: eclipse/openj9 <reply@reply.github.com>Cc: Peter Shipton/Ottawa/IBM@IBMCASubject: Re: [eclipse/openj9] URLClassLoder and -Dibm.cl.verbose=* problem when running using Java 9 (#1382)Date: Thu, Mar 8, 2018 9:56 PM Hi Peter,I forgot to tell that Java 8 I used is the one that without xml.jar. I removed xml.jar in Java 8 myself.Since org.apache.xalan is not part of IBM Java 9, I package it along with other class in xml.jar in a jar called gxlxml.jar. We do not want to change customer behavior. So We want to load gxlxml.jar dynamically in our code but not ask customers to add gxlxml.jar in their CLASSPATH.To implement this, first I write the following code.       URLClassLoader ucl = (URLClassLoader)ClassLoader.getSystemClassLoader();      Method add = URLClassLoader.class.getDeclaredMethod("addURL", new Class[]{URL.class});      add.setAccessible(true);      add.invoke(ucl, xmlURLs[0]);From your information, I know this code is not supported by Java 9. Then I wrote the following code:           urls[0]= new URL(urlStr+"gxlxml.jar");      URLClassLoader cl = new URLClassLoader(urls);In Java 8 without xml.jar, java.net.URLClassLoader found org.apache.xalan.processor.TransformerFactoryImp.  But in Java 9, this class can not be found. And I don't know how to debug this. Is there other option instead of -Dibm.cl.verbose? This is the log printed by -Dibm.cl.verbose in Java 8 without xml.jar.java.net.URLClassLoader attempting to find org.apache.xalan.processor.TransformerFactoryImpljava.net.URLClassLoader using classpath /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jar:/u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jar:/u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jarjava.net.URLClassLoader could not find org/apache/xalan/processor/TransformerFactoryImpl.class in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jarjava.net.URLClassLoader could not find org/apache/xalan/processor/TransformerFactoryImpl.class in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jarjava.net.URLClassLoader found org/apache/xalan/processor/TransformerFactoryImpl.class in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jarI am not familiar with how to load jar package dynamically in Java 9 just like the jar package is added in CLASSPATH. It's very appreciated if you can give me some advice on this.Thanks very much!LilyzXML, CSLPeter Shipton ---2018-03-08 下午 08:14:37---Hi Lily. Java 9 is not compatible with Java 8. This is by design and its not something that will beFrom: Peter Shipton <notifications@github.com>To: eclipse/openj9 <openj9@noreply.github.com>Cc: ZhangLi1021 <bjzhangl@cn.ibm.com>, Author <author@noreply.github.com>Date: 2018-03-08 下午 08:14Subject: Re: [eclipse/openj9] URLClassLoder and -Dibm.cl.verbose=* problem when running using Java 9 (#1382)
Hi Lily. Java 9 is not compatible with Java 8. This is by design and its not something that will be "fixed" in Java 9. Your application needs to be fixed instead.
        This is a problem with your application. In Java 9 ClassLoader.getSystemClassLoader() is no longer a subclass of URLClassLoader.        org.apache.xalan is part of IBM Java 8, but is not included in Java 9. I intended to direct you to IBM's migration guide https://www.ibm.com/support/knowledgecenter/SSYKE2_9.0.0/com.ibm.java.multiplatform.90.doc/user/compatibility_xml.html, but I see org.apache.xalan is not listed there. You need to include org.apache in your app if it is required.        This is a problem with your application, com.ibm.jvm.ClassLoaderDiagnosticsHelper is not part of Java 9, and -Dibm.cl.verbose is not supported by Java 9. Please let me know what API in com.ibm.jvm.ClassLoaderDiagnosticsHelper is being called by your app, but I don't expect this information to change anything.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ZhangLi1021** [comment] 2018-03-12 03:33
Hi Peter,

Yes, I want to modify JVM at runtime in order to load xml jar package
dynamically at run time. We do not want to change customer behavior to ask
them to set xml.jar in their classpath. Since our product is compiled using
Java 8, and run under java 8 and java 9. Is there a method that can be
compiled using Java 8 and run under Java 9? Thanks!

Thanks,
Lily
zXML, CSL



From:	Peter Shipton/Ottawa/IBM
To:	Li EF Zhang/China/IBM@IBMCN
Cc:	reply
            +023716e53a90849fc17abeb331e134be3f388bc30dfcfa0992cf0000000116b8eb2992a169ce12156f9b@reply.github.com
Date:	2018-03-09 下午 01:21
Subject:	Re: [eclipse/openj9] URLClassLoder and -Dibm.cl.verbose=*
            problem when running using Java 9 (#1382)



Hi Lily,

> We want to load gxlxml.jar dynamically in our code

To provide a proper answer I need to understand how your code gets loaded.
Is the idea to modify the JVM?

An easy migration is to put  gxlxml.jar on the module path, which will
create an automatic module which is visible to everything on the class
path. You can read about modularity and automatic modules here
http://openjdk.java.net/projects/jigsaw/spec/sotms/

java --module-path gxlxml.jar ...

A better solution is to create a module-info.java in order to define a
proper module. See also the modularity quick start guide
http://openjdk.java.net/projects/jigsaw/quick-start

Peter

 ----- Original message -----
 From: Li EF Zhang/China/IBM
 To: eclipse/openj9 <reply
 +023716e53a90849fc17abeb331e134be3f388bc30dfcfa0992cf0000000116b8eb2992a169ce12156f9b@reply.github.com>

 Cc: Peter Shipton/Ottawa/IBM@IBMCA
 Subject: Re: [eclipse/openj9] URLClassLoder and -Dibm.cl.verbose=* problem
 when running using Java 9 (#1382)
 Date: Thu, Mar 8, 2018 9:56 PM

 Hi Peter,

 I forgot to tell that Java 8 I used is the one that without xml.jar. I
 removed xml.jar in Java 8 myself.
 Since org.apache.xalan is not part of IBM Java 9, I package it along with
 other class in xml.jar in a jar called gxlxml.jar. We do not want to
 change customer behavior. So We want to load gxlxml.jar dynamically in our
 code but not ask customers to add gxlxml.jar in their CLASSPATH.
 To implement this, first I write the following code.
       URLClassLoader ucl =
 (URLClassLoader)ClassLoader.getSystemClassLoader();
       Method add = URLClassLoader.class.getDeclaredMethod("addURL", new
 Class[]{URL.class});
       add.setAccessible(true);
       add.invoke(ucl, xmlURLs[0]);

 From your information, I know this code is not supported by Java 9. Then I
 wrote the following code:

       urls[0]= new URL(urlStr+"gxlxml.jar");
       URLClassLoader cl = new URLClassLoader(urls);

 In Java 8 without xml.jar, java.net.URLClassLoader found
 org.apache.xalan.processor.TransformerFactoryImp.  But in Java 9, this
 class can not be found. And I don't know how to debug this. Is there other
 option instead of -Dibm.cl.verbose? This is the log printed by
 -Dibm.cl.verbose in Java 8 without xml.jar.

 java.net.URLClassLoader attempting to find
 org.apache.xalan.processor.TransformerFactoryImpl
 java.net.URLClassLoader using
 classpath /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jar:/u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jar:/u/zhan

 gli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jar
 java.net.URLClassLoader could not find
 org/apache/xalan/processor/TransformerFactoryImpl.class
 in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljosrgImpl.jar
 java.net.URLClassLoader could not find
 org/apache/xalan/processor/TransformerFactoryImpl.class
 in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxljapi.jar
 java.net.URLClassLoader found
 org/apache/xalan/processor/TransformerFactoryImpl.class
 in /u/zhangli/v2r4/d2.02/xmlss/lib/java_classes/gxlxml.jar


 I am not familiar with how to load jar package dynamically in Java 9 just
 like the jar package is added in CLASSPATH. It's very appreciated if you
 can give me some advice on this.
 Thanks very much!

 Lily
 zXML, CSL

 Peter Shipton ---2018-03-08 下午 08:14:37---Hi Lily. Java 9 is not
 compatible with Java 8. This is by design and its not something that will
 be

**Comment by JasonFengJ9** [comment] 2018-03-12 21:54
@ZhangLi1021 Pete is on vacation this week. I will see if anything I can help here.

>Since our product is compiled using Java 8, and run under java 8 and java 9. Is there a method that can be compiled using Java 8 and run under Java 9?

Binary back compatibility is not the issue here (at least not related to any problem reported in earlier comments), i.e., class files compiled by Java 8 should be able to run with Java 9 unless incompatible API are used (again not the case now).

To help your issue better, can you provide a standalone program to simulate the functionalities required by XML team and I can reproduce the exception you observed?

**Comment by ZhangLi1021** [comment] 2018-03-19 03:26
Hi Jason,

Thank you! I have solved this problem. You can close this issue.

Thanks,
Lily
zXML, CSL

**Closed** 2018-03-19 12:32 UTC
Labels: jdk9, question
