### ISSUE TITLE
Test_openjdk11_j9_extended.functional_x86-64_linux (+xl) threadMXBeanTestSuite1 SAXParseException

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#6498] opened 2019-07-17 12:30 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/94
```
===============================================
Running test threadMXBeanTestSuite1_5 ...
===============================================
threadMXBeanTestSuite1_5 Start Time: Wed Jul 17 06:12:03 2019 Epoch Time (ms): 1563358323550
variation: Mode301 -Xjit:noJitUntilMain,count=0,optlevel=warm
JVM_OPTIONS: -Xnocompressedrefs -Xgcpolicy:metronome -Xnocompressedrefs -Xjit:noJitUntilMain,count=0,optlevel=warm 
[TestNG] [ERROR] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 8; The processing instruction must begin with the name of the target.
Exception in thread "main" java.lang.NullPointerException
	at org.testng.TestNG.getStatus(TestNG.java:211)
	at org.testng.TestNG.main(TestNG.java:1324)

threadMXBeanTestSuite1_5_FAILED
```

**Comment by pshipton** [comment] 2019-07-17 20:54
This occurrence happened before the one above.
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_OpenJDK13/15
threadMXBeanTestSuite1_6
```
===============================================
Running test threadMXBeanTestSuite1_6 ...
===============================================
threadMXBeanTestSuite1_6 Start Time: Tue Jul 16 02:00:52 2019 Epoch Time (ms): 1563253252620
variation: Mode351 -Xjit:noJitUntilMain,count=0,optlevel=warm
JVM_OPTIONS: -Xcompressedrefs -Xgcpolicy:metronome -Xcompressedrefs -Xjit:noJitUntilMain,count=0,optlevel=warm 
[TestNG] [ERROR] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 8; The processing instruction must begin with the name of the target.
Exception in thread "main" java.lang.NullPointerException
	at org.testng.TestNG.getStatus(TestNG.java:211)
	at org.testng.TestNG.main(TestNG.java:1324)

threadMXBeanTestSuite1_6_FAILED
```

**Comment by pshipton** [comment] 2019-07-18 11:11
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_OpenJDK13/17
threadMXBeanTestSuite1_5

**Comment by pshipton** [comment] 2019-07-18 11:15
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/95
threadMXBeanTestSuite1_5

**Comment by pshipton** [comment] 2019-07-18 11:17
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/100
threadMXBeanTestSuite1_6

**Comment by pshipton** [comment] 2019-07-19 11:40
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_Nightly/101
threadMXBeanTestSuite1_6

**Comment by pshipton** [comment] 2019-07-23 14:49
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_Nightly/97

**Comment by pshipton** [comment] 2019-07-23 14:51
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/97

**Comment by pshipton** [comment] 2019-07-23 15:15
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_Nightly/2

**Comment by pshipton** [comment] 2019-07-23 16:01
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_OpenJDK13/19

**Comment by pshipton** [comment] 2019-07-23 16:02
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/103

**Comment by pshipton** [comment] 2019-07-26 12:01
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.functional_x86-64_linux_xl_Nightly/106

**Comment by pshipton** [comment] 2019-07-26 12:01
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_OpenJDK13/21

**Comment by pshipton** [comment] 2019-07-27 14:54
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.functional_x86-64_linux_xl_Nightly/103

**Comment by pshipton** [comment] 2019-08-20 12:51
https://ci.eclipse.org/openj9/job/Test_openjdk13_j9_extended.functional_x86-64_linux_xl_Nightly/14

@andrewcraik this has been failing a lot, can somebody take a look.

**Comment by andrewcraik** [comment] 2019-08-20 13:42
@liqunl can you please have a look?

**Comment by liqunl** [comment] 2019-08-20 17:16
This is a bug in TestNG which has been fixed in https://github.com/cbeust/testng/issues/1810. We need to upgrade our TestNG.

**Comment by liqunl** [comment] 2019-08-20 17:38
Tried the latest testng, the test still fail, but there's no NPE this time. The real failure is
```
[TestNG] [ERROR] org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 8; The processing instruction must begin with the name of the target.
```

**Comment by pshipton** [comment] 2019-08-20 17:58
@llxia can you please take a look. I've set it as prio:high since it fails fairly often.

**Comment by liqunl** [comment] 2019-08-20 18:02
Also found this failure occurs with -Xint
```
FAILED: testMonitorTraceTest
java.lang.UnsatisfiedLinkError: j9vm/test/monitor/Helpers.monitorEnter(Ljava/lang/Object;)I
        at org.openj9.test.java.lang.management.ThreadMXBean.MonitorTraceTest.testMultiFrame(MonitorTraceTest.java:211)
        at org.openj9.test.java.lang.management.ThreadMXBean.MonitorTraceTest.testMonitorTraceTest(MonitorTraceTest.java:41)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
        at org.testng.TestRunner.privateRun(TestRunner.java:648)
        at org.testng.TestRunner.run(TestRunner.java:505)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
        at org.testng.SuiteRunner.run(SuiteRunner.java:364)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
        at org.testng.TestNG.runSuites(TestNG.java:1049)
        at org.testng.TestNG.run(TestNG.java:1017)
        at org.testng.TestNG.privateMain(TestNG.java:1354)
        at org.testng.TestNG.main(TestNG.java:1323)
```

**Comment by pshipton** [comment] 2019-08-20 19:20
@liqunl does this mean the SAXParseException is a JIT issue?

**Comment by liqunl** [comment] 2019-08-20 20:12
@pshipton I'm still testing. It seems like we may have a bad xml. But since this error is intermittent, I can't tell if it's JIT issue or test issue.

**Comment by llxia** [comment] 2019-08-20 20:18
Ran the test 50 times with different jvm options:
- `​threadMXBeanTestSuite1_1` passed 50/50 (ran with `-Xnocompressedrefs -Xgcpolicy:metronome -Xnocompressedrefs -Xint`)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/3016/
- `threadMXBeanTestSuite1_5` is still running but it failed 16 so far (ran with `-Xnocompressedrefs -Xgcpolicy:metronome -Xnocompressedrefs -Xjit:noJitUntilMain,count=0,optlevel=warm`)
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/3017/

java -version
```
00:01:55.000  openjdk version "13-internal" 2019-09-17
00:01:55.000  OpenJDK Runtime Environment (build 13-internal+0-adhoc.jenkins.BuildJDK13x86-64linuxxlNightly)
00:01:55.000  Eclipse OpenJ9 VM (build ibm_sdk-0c1b17128d, JRE 13 Linux amd64-64-Bit 20190818_47 (JIT enabled, AOT enabled)
00:01:55.000  OpenJ9   - 0c1b17128d
00:01:55.000  OMR      - fb6439fe
00:01:55.000  JCL      - 2337332cb3a based on jdk-13+30)
```

It looks like a JIT issue to me.

**Comment by liqunl** [comment] 2019-08-20 21:42
@llxia Thanks for the runs, I'll continue my investigation.

**Comment by liqunl** [comment] 2019-08-21 17:19
@llxia I'm running the test locally and want to experiment with some options. Is there a way to feed the test customized options? Options that may be conflict with the hard coded ones. I'm using the following command to run the test
```
make _threadMXBeanTestSuite1_6
```

**Comment by smlambert** [comment] 2019-08-21 17:36
If you wish to append extra JVM options, export EXTRA_OPTIONS environment variable.  If you wish to fully replace the JVM options used in the test, export JVM_OPTIONS.  If you wish to do anything else, make changes in the command in the [playlist.xml file](https://github.com/eclipse/openj9/blob/master/test/functional/Java8andUp/playlist.xml#L1387) in your branch and run tests from your branch.

See "with a different set of JVM options" in 
https://github.com/eclipse/openj9/blob/master/test/docs/OpenJ9TestUserGuide.md#4-run-tests

or if using a Grinder, use those same environmental variables as params:
<img width="475" alt="Screen Shot 2019-08-21 at 10 32 25 AM" src="https://user-images.githubusercontent.com/2836948/63454162-1bae5f00-c3ff-11e9-9034-08129354d1b4.png">

**Comment by liqunl** [comment] 2019-08-23 15:31
I think the problem is the instructions generated for `BNDCHKwithSpineCHK` when the array length is folded.
Evaluator is taking advantage of the fact that array+4 will be 0 for discontiguous array and merges the two checks together into one compare instruction, which is the compare between the element offset and value at array+4. If the array is discontiguous, we'll always fail the check and go to the outline code. In the failing case the arraylength is folded to the real arraylength 0x00010000, thus the instruction degrades to just a bound check, then we're incorrectly bypassing the spine check when bound check passes.

The evaluator should be fixed to handle the case when arraylength is folded to a constant.

```
n16n     (  0)  BNDCHKwithSpineCHK [#1] (Unsigned spineCHKWithArrayElementChild )                    [0x7f2d5c4047c0] 
n21n     (  1)    bloadi  <array-shadow>[#230  Shadow] [flags 0x80000601 0x0 ] (in GPR_0081) (cannotOverflow )  [0x7f2
n20n     (  0)      aladd (X>=0 internalPtr sharedMemory )                                           [0x7f2d5c404900] 
n12n     (  0)        aload  com/sun/org/apache/xerces/internal/util/XMLChar.CHARS [B[#360  notAccessed final Static] 
n19n     (  0)        lsub (cannotOverflow )                                                         [0x7f2d5c4048b0] 
n18n     (  0)          i2l (X>=0 )                                                                  [0x7f2d5c404860] 
n92n     (  0)            ==>iRegLoad (in GPR_0064) (X>=0 cannotOverflow SeenRealReference )
n17n     (  0)          lconst -8 (X!=0 X<=0 )                                                       [0x7f2d5c404810] 
n12n     (  0)    ==>aload (in &GPR_0080) (X!=0 sharedMemory )
n14n     (  0)    iconst 0x10000 (X!=0 X>=0 )                                                        [0x7f2d5c404720] 
n92n     (  0)    ==>iRegLoad (in GPR_0064) (X>=0 cannotOverflow SeenRealReference )
-----------------------------

[0x7f2d5c525320]       mov     &GPR_0080, qword ptr [0x000000000200d508]               # L8RegMem, SymRef  com/sun/org
[0x7f2d5c525420]       cmp     GPR_0064, 0x00010000    # CMP4RegImm4
[0x7f2d5c5254c0]       jae     Outlined Label L0096                    # JAE4
[0x7f2d5c5256e0]       mov     GPR_0081, byte ptr [GPR_0064+1*&GPR_0080+0x8]           # L1RegMem, SymRef  <array-shad
[0x7f2d5c525ab0]       assocRegs                       # ASSOCREGS
       POST: [GPR_0064 : eax]
[0x7f2d5c525850]       Label L0097:                    # LABEL
       POST: [GPR_0000 : ebp]
```

**Comment by liqunl** [comment] 2019-08-23 18:11
Also, since the array is known object, there is an optimization opportunity to get rid of spine check if the array is contiguous.

**Closed** 2019-08-30 19:23 UTC
Labels: comp:jit, prio:high, test failure
