### ISSUE TITLE
ParallelStreamsLoadTest_CS_0 -Xgc:concurrentScavenge  Segmentation error vmState=0x00020026

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#12110] opened 2021-03-03 12:56 UTC
Failure link
------------

From an internal build `Test_openjdk17_j9_sanity.system_ppc64le_linux/6`
```
22:37:05  openjdk version "17" 2021-09-14
22:37:05  OpenJDK Runtime Environment AdoptOpenJDK (build 17+11-202103030214)
22:37:05  Eclipse OpenJ9 VM AdoptOpenJDK (build master-c72aa38fc, JRE 17 Linux ppc64le-64-Bit Compressed References 20210302_15 (JIT enabled, AOT enabled)
22:37:05  OpenJ9   - c72aa38fc
22:37:05  OMR      - 67ddc2873
22:37:05  JCL      - 28772d4468 based on jdk-17+11)
```
rebuild the failed tests in one link:
06:06:53  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=17&JDK_IMPL=openj9&JDK_VENDOR=adoptopenjdk&BUILD_LIST=system&PLATFORM=ppc64le_linux_mixed&TARGET=testList%20TESTLIST=DaaLoadTest_daa1_CS_5m_0,LambdaLoadTest_CS_5m_0,MathLoadTest_bigdecimal_CS_5m_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------
```
===============================================
Running test ParallelStreamsLoadTest_CS_0 ...
===============================================
ParallelStreamsLoadTest_CS_0 Start Time: Wed Mar  3 00:24:14 2021 Epoch Time (ms): 1614759854641
variation: -Xgcpolicy:gencon -Xgc:concurrentScavenge
JVM_OPTIONS:  -Xgcpolicy:gencon -Xgc:concurrentScavenge 
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00020026
LT  stderr Unhandled exception
LT  stderr Type=Segmentation error vmState=0x00020026
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=00003FFFA2CF32C0 Handler2=00003FFFA2C2C1C0
LT  stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000001
LT  stderr Handler1=00003FFFA2CF3780 Handler2=00003FFFA2C2C1C0
LT  stderr R0=00003FFFA1822A5C R1=00003FFFA3A69620 R2=00003FFFA1985600 R3=00003FFFA3A696B8
LT  stderr R4=00000000FFE00528 R5=0000010000061400 R6=FFF024D0FFF024B8 R7=0000000000000000
LT  stderr R8=0000000000000030 R9=0000000000000000 R10=0000000000000000 R11=00000000FFE00938
LT  stderr R12=0000000000000008 R13=00003FFFA3A76900 R14=00000000FFE004F0 R15=0000000000000010
LT  stderr R16=00003FFF9C05BBF8 R17=000000000000040C R18=0000000000000010 R19=0000000000000000
LT  stderr R20=0000000000000000 R21=0000000000000410 R22=00003FFF9C03E5A0 R23=0000000000000000
LT  stderr R24=0000000000000010 R25=00000000FFE00528 R26=00003FFFA3A696B8 R27=00003FFFA0090050
LT  stderr R28=000000000003B1D0 R29=00003FFF9C086070 R30=00003FFF9C05BBF8 R31=00000000FFF008D8
LT  stderr R0=00003FFFA18391D0 R1=00003FFF74CBB4F0 R2=00003FFFA1985600 R3=00003FFF74CBB588
LT  stderr R4=00000000FFE0A918 R5=00003C0000037400 R6=636170612F67726F R7=0000000000000000
LT  stderr R8=0000000000000030 R9=0000000000000000 R10=0000000000000000 R11=00000000FFE0E528
LT  stderr R12=0000000000000078 R13=00003FFF74CC6900 R14=00003FFF74CBF900 R15=0000000000050000
LT  stderr R16=FFFFFFFFFFFFFFF8 R17=0000000000000000 R18=0000000000000010 R19=0000000000000000
LT  stderr R20=00003FFF9C03E5A0 R21=0000000000000010 R22=0000000000000000 R23=00003FFF74CBB588
LT  stderr R24=0000000000003C10 R25=00000000FFE0A918 R26=00003FFFA00901B0 R27=00000000FFFFC018
LT  stderr R28=00003FFF20001AC8 R29=000000000010B368 R30=00003FFF9C086070 R31=00000000FFFFC018
LT  stderr NIP=00003FFFA1822AC4 MSR=800000010280F033 ORIG_GPR3=00000000000087D0 CTR=0000000000000000
LT  stderr LINK=00003FFFA1822A6C XER=0000000000000000 CCR=0000000024224202 SOFTE=0000000000000001
LT  stderr TRAP=0000000000000300 DAR=0000000000000018 dsisr=0000000040000000 RESULT=0000000000000000
LT  stderr NIP=00003FFFA1839230 MSR=800000010280F033 ORIG_GPR3=00000000000087D0 CTR=0000000000000000
LT  stderr LINK=00003FFFA18391E0 XER=0000000000000000 CCR=0000000024222202 SOFTE=0000000000000001
LT  stderr TRAP=0000000000000300 DAR=0000000000000018 dsisr=0000000040000000 RESULT=0000000000000000
LT  stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR1 4052f4eb60000000 (f: 1610612736.000000, d: 7.582687e+01)
LT  stderr FPR2 41e0000000000000 (f: 0.000000, d: 2.147484e+09)
LT  stderr FPR3 666e495f70697a5f (f: 1885960832.000000, d: 2.573819e+185)
LT  stderr FPR4 3fe3333340000000 (f: 1073741824.000000, d: 6.000000e-01)
LT  stderr FPR5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR6 3fe5555560000000 (f: 1610612736.000000, d: 6.666667e-01)
LT  stderr FPR7 3f27beb8a0000000 (f: 2684354560.000000, d: 1.811600e-04)
LT  stderr FPR8 4034000000000000 (f: 0.000000, d: 2.000000e+01)
LT  stderr FPR9 3fd99999c0000000 (f: 3221225472.000000, d: 4.000000e-01)
LT  stderr FPR10 3f41828360000000 (f: 1610612736.000000, d: 5.343572e-04)
LT  stderr FPR11 bfa33fa8a0000000 (f: 2684354560.000000, d: -3.759505e-02)
LT  stderr FPR12 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
LT  stderr FPR13 3fdb9b2820000000 (f: 536870912.000000, d: 4.313450e-01)
LT  stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR1 4052e706e0000000 (f: 3758096384.000000, d: 7.560979e+01)
LT  stderr FPR2 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
LT  stderr FPR3 5f6c616e6769535f (f: 1734955904.000000, d: 4.645038e+151)
LT  stderr FPR4 3fe3333340000000 (f: 1073741824.000000, d: 6.000000e-01)
LT  stderr FPR5 3fca181e80000000 (f: 2147483648.000000, d: 2.038611e-01)
LT  stderr FPR6 3fe5555560000000 (f: 1610612736.000000, d: 6.666667e-01)
LT  stderr FPR7 3f27beb8a0000000 (f: 2684354560.000000, d: 1.811600e-04)
LT  stderr FPR8 4034000000000000 (f: 0.000000, d: 2.000000e+01)
LT  stderr FPR9 3fd9999bc0000000 (f: 3221225472.000000, d: 4.000005e-01)
LT  stderr FPR10 3f66952be0000000 (f: 3758096384.000000, d: 2.756677e-03)
LT  stderr FPR11 bfb361d7e0000000 (f: 3758096384.000000, d: -7.571172e-02)
LT  stderr FPR12 3fc7565060000000 (f: 1610612736.000000, d: 1.823216e-01)
LT  stderr FPR13 3fdb9b2820000000 (f: 536870912.000000, d: 4.313450e-01)
LT  stderr FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/lib/default/libj9gc29.so
LT  stderr Module_base_address=00003FFFA1650000
LT  stderr Target=2_90_20210302_15 (Linux 3.10.0-1160.15.2.el7.ppc64le)
LT  stderr Module=/home/jenkins/workspace/Test_openjdk17_j9_sanity.system_ppc64le_linux_testList_2/openjdkbinary/j2sdk-image/lib/default/libj9gc29.so
LT  stderr Module_base_address=00003FFFA1650000
LT  stderr CPU=ppc64le (4 logical CPUs) (0xde750000 RAM)
LT  stderr Target=2_90_20210302_15 (Linux 3.10.0-1160.15.2.el7.ppc64le)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr CPU=ppc64le (4 logical CPUs) (0xde750000 RAM)
LT  stderr ----------- Stack Backtrace -----------
LT  stderr (0x00003FFFA2C268A4 [libj9prt29.so+0x368a4])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2C26968 [libj9prt29.so+0x36968])
LT  stderr (0x00003FFFA2C26AD0 [libj9prt29.so+0x36ad0])
LT  stderr (0x00003FFFA2C265A4 [libj9prt29.so+0x365a4])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2C26698 [libj9prt29.so+0x36698])
LT  stderr (0x00003FFFA2CF3140 [libj9vm29.so+0x43140])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2CF3474 [libj9vm29.so+0x43474])
LT  stderr (0x00003FFFA2C2C420 [libj9prt29.so+0x3c420])
LT  stderr __kernel_sigtramp_rt64+0x0 (0x00003FFFA3DA0478)
LT  stderr (0x00003FFFA1822A5C [libj9gc29.so+0x1d2a5c])
LT  stderr (0x00003FFFA1880348 [libj9gc29.so+0x230348])
LT  stderr (0x00003FFFA1831E68 [libj9gc29.so+0x1e1e68])
LT  stderr (0x00003FFFA18389CC [libj9gc29.so+0x1e89cc])
LT  stderr (0x00003FFFA184E2F0 [libj9gc29.so+0x1fe2f0])
LT  stderr (0x00003FFFA1853398 [libj9gc29.so+0x203398])
LT  stderr (0x00003FFFA17D593C [libj9gc29.so+0x18593c])
LT  stderr (0x00003FFFA184B624 [libj9gc29.so+0x1fb624])
LT  stderr (0x00003FFFA184D67C [libj9gc29.so+0x1fd67c])
LT  stderr (0x00003FFFA184DA48 [libj9gc29.so+0x1fda48])
LT  stderr (0x00003FFFA17BB230 [libj9gc29.so+0x16b230])
LT  stderr (0x00003FFFA184EF90 [libj9gc29.so+0x1fef90])
LT  stderr (0x00003FFFA184FCB0 [libj9gc29.so+0x1ffcb0])
LT  stderr (0x00003FFFA17A81CC [libj9gc29.so+0x1581cc])
LT  stderr (0x00003FFFA18C837C [libj9gc29.so+0x27837c])
LT  stderr (0x00003FFFA189DB04 [libj9gc29.so+0x24db04])
LT  stderr (0x00003FFFA17DBA20 [libj9gc29.so+0x18ba20])
LT  stderr (0x00003FFFA17DBC64 [libj9gc29.so+0x18bc64])
LT  stderr (0x00003FFFA17DA728 [libj9gc29.so+0x18a728])
LT  stderr (0x00003FFFA17DA8F8 [libj9gc29.so+0x18a8f8])
LT  stderr (0x00003FFFA17D9C98 [libj9gc29.so+0x189c98])
LT  stderr (0x00003FFFA17E2970 [libj9gc29.so+0x192970])
LT  stderr (0x00003FFFA16ACF5C [libj9gc29.so+0x5cf5c])
LT  stderr (0x00003FFFA2D7516C [libj9vm29.so+0xc516c])
LT  stderr (0x00003FFFA2E25014 [libj9vm29.so+0x175014])
LT  stderr (0x00003FFFA2CC6D08 [libj9vm29.so+0x16d08])
LT  stderr (0x00003FFFA2CD6CDC [libj9vm29.so+0x26cdc])
LT  stderr (0x00003FFFA2CD99EC [libj9vm29.so+0x299ec])
LT  stderr (0x00003FFFA2CDFC74 [libj9vm29.so+0x2fc74])
LT  stderr (0x00003FFFA2E660EC [libj9vm29.so+0x1b60ec])
LT  stderr (0x00003FFFA1365224 [libjclse29.so+0x25224])
LT  stderr Java_java_lang_ClassLoader_defineClassImpl+0x68 (0x00003FFFA1354438 [libjclse29.so+0x14438])
LT  stderr (0x00003FFF7CA10FB8 [<unknown>+0x0])
LT  stderr (0x00003FFFA2CC6D08 [libj9vm29.so+0x16d08])
LT  stderr (0x00003FFFA2CD6CDC [libj9vm29.so+0x26cdc])
LT  stderr (0x00003FFFA2CD99EC [libj9vm29.so+0x299ec])
LT  stderr (0x00003FFFA2D3B938 [libj9vm29.so+0x8b938])
LT  stderr (0x00003FFFA2D3C054 [libj9vm29.so+0x8c054])
LT  stderr ---------------------------------------
LT  stderr (0x00003FFFA2C268A4 [libj9prt29.so+0x368a4])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2C26968 [libj9prt29.so+0x36968])
LT  stderr (0x00003FFFA2C26AD0 [libj9prt29.so+0x36ad0])
LT  stderr (0x00003FFFA2C265A4 [libj9prt29.so+0x365a4])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2C26698 [libj9prt29.so+0x36698])
LT  stderr (0x00003FFFA2CF3140 [libj9vm29.so+0x43140])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA2CF3474 [libj9vm29.so+0x43474])
LT  stderr (0x00003FFFA2CF37D0 [libj9vm29.so+0x437d0])
LT  stderr (0x00003FFFA2C2C420 [libj9prt29.so+0x3c420])
LT  stderr __kernel_sigtramp_rt64+0x0 (0x00003FFFA3DA0478)
LT  stderr (0x00003FFFA18391D0 [libj9gc29.so+0x1e91d0])
LT  stderr (0x00003FFFA1852264 [libj9gc29.so+0x202264])
LT  stderr (0x00003FFFA1699F8C [libj9gc29.so+0x49f8c])
LT  stderr (0x00003FFFA16A420C [libj9gc29.so+0x5420c])
LT  stderr (0x00003FFFA2D4B25C [libj9vm29.so+0x9b25c])
LT  stderr (0x00003FFFA2D4C014 [libj9vm29.so+0x9c014])
LT  stderr (0x00003FFFA16A4308 [libj9gc29.so+0x54308])
LT  stderr (0x00003FFFA1699778 [libj9gc29.so+0x49778])
LT  stderr (0x00003FFFA1697C2C [libj9gc29.so+0x47c2c])
LT  stderr (0x00003FFFA169BB40 [libj9gc29.so+0x4bb40])
LT  stderr (0x00003FFFA184E3B0 [libj9gc29.so+0x1fe3b0])
LT  stderr (0x00003FFFA1853398 [libj9gc29.so+0x203398])
LT  stderr (0x00003FFFA17D4BD4 [libj9gc29.so+0x184bd4])
LT  stderr (0x00003FFFA17D4258 [libj9gc29.so+0x184258])
LT  stderr (0x00003FFFA2C2D5C8 [libj9prt29.so+0x3d5c8])
LT  stderr (0x00003FFFA17D39D0 [libj9gc29.so+0x1839d0])
LT  stderr (0x00003FFFA2BC13E8 [libj9thr29.so+0x113e8])
LT  stderr (0x00003FFFA3CD8CD4 [libpthread.so.0+0x8cd4])
LT  stderr clone+0xe4 (0x00003FFFA3BD7F14 [libc.so.6+0x127f14])
LT  stderr ---------------------------------------
ParallelStreamsLoadTest_CS_0_FAILED
```
Similar errors at a few other `-Xgc:concurrentScavenge ` tests such as `MathLoadTest_autosimd_CS_5m_0_FAILED`.
This is a failure across platform/streams.
fyi @dmitripivkine

**Comment by pshipton** [comment] 2021-03-03 13:32
The system tests didn't run night before last. Changes from the last working build below. We can narrow this down with a grinder on the previous night's build if necessary.

https://github.com/eclipse/openj9/compare/f021812...c72aa38
https://github.com/eclipse/openj9-omr/compare/eb4f5a8...67ddc28

**Comment by amicic** [comment] 2021-03-03 17:17
The root cause is https://github.com/eclipse/omr/pull/5795. By the end of day, we will either provide a fix or revert the change.

**Comment by bragaigor** [comment] 2021-03-03 18:09
I should have a PR opened in the next few hours that fixes the issue

**Comment by amicic** [comment] 2021-03-03 22:03
While we have fixes ready, they are somewhat suboptimal (duplicate some existing functionality). To clean them up will take a few more hours of testing, so we are ok to revert the OMR change (need a commiter, though).

**Comment by pshipton** [comment] 2021-03-03 22:24
Created https://github.com/eclipse/omr/pull/5840

**Comment by pshipton** [comment] 2021-03-04 00:23
The revert https://github.com/eclipse/omr/pull/5840 is merged and promoted to OpenJ9 builds.

**Comment by andrew-m-leonard** [comment] 2021-03-04 12:25
Presume this is the same as this?: https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_aarch64_linux/184/tapResults/
```
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00020026
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=f61f3868 Signal_Code=00000001
MLT stderr Handler1=000003FFAF5C6328 Handler2=000003FFAF4B2110 InaccessibleAddress=0000000000000000
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00020026
MLT stderr gpr0=000A050000000100 gpr1=0000000000000000 gpr2=000000000000000F gpr3=000003FFA8052960
MLT stderr gpr4=000003FFAD80F35A gpr5=000000000000040B gpr6=00000000A8E30420 gpr7=000003FFB0718050
MLT stderr gpr8=000003FFA808B600 gpr9=0000000000000014 gpr10=000003FFA8060EE8 gpr11=00000000A8F30730
MLT stderr gpr12=00000000A8FF3B08 gpr13=000000000008D720 gpr14=000003FFAD80F35A gpr15=000003FFB04F9788
MLT stderr psw=000003FFAD80F3BE mask=0705000180000000 fpc=00080000 bea=000003FFAD810082
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=f61f3868 Signal_Code=00000001
MLT stderr Handler1=000003FFAF5C66B8 Handler2=000003FFAF4B2110 InaccessibleAddress=0000000000000000
MLT stderr gpr0=00089A000000FC00 gpr1=0000000000000000 gpr2=000003FF00000014 gpr3=00000000A8E43200
MLT stderr gpr4=000003FFAD826986 gpr5=000000000000FC0B gpr6=0000000000000010 gpr7=00000000A9015010
MLT stderr gpr8=0000000000126238 gpr9=000003FF40001AC8 gpr10=000003FFA808B600 gpr11=00000000A9015010
MLT stderr gpr12=000003FFB081B000 gpr13=0000000000000000 gpr14=000003FFAD826986 gpr15=000003FFAF47DD70
MLT stderr psw=000003FFAD8269E4 mask=0705000180000000 fpc=00080000 bea=000003FFAD827836
MLT stderr fpr0 4297a75b00000000 (f: 0.000000, d: 6.501888e+12)
MLT stderr fpr1 3ecccccea8060ee8 (f: 2818969344.000000, d: 3.433231e-06)
MLT stderr fpr2 3e3ab28300000000 (f: 0.000000, d: 6.215952e-09)
MLT stderr fpr3 3e638e2a00000001 (f: 1.000000, d: 3.642464e-08)
MLT stderr fpr4 bd19fd4500000000 (f: 0.000000, d: -2.308317e-14)
MLT stderr fpr5 41a00000b04fa188 (f: 2958008832.000000, d: 1.342178e+08)
MLT stderr fpr6 bc9be974a808b600 (f: 2819143168.000000, d: -9.683898e-17)
MLT stderr fpr7 3f2aaaac43b92010 (f: 1136205824.000000, d: 2.034507e-04)
MLT stderr fpr8 0000000000800000 (f: 8388608.000000, d: 4.144523e-317)
MLT stderr fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr10 000003ffafd00000 (f: 2949644288.000000, d: 2.172259e-311)
MLT stderr fpr11 000003ffd787f1dd (f: 3616010752.000000, d: 2.172588e-311)
MLT stderr fpr12 000003ffdc8fbfec (f: 3700408320.000000, d: 2.172630e-311)
MLT stderr fpr13 000003ffea77d4e8 (f: 3933721856.000000, d: 2.172745e-311)
MLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr15 000003ff4877d968 (f: 1215814016.000000, d: 2.171402e-311)
MLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.system_s390x_linux/openjdkbinary/j2sdk-image/jre/lib/s390x/default/libj9gc29.so
MLT stderr Module_base_address=000003FFAD680000
MLT stderr Target=2_90_20210303_923 (Linux 4.4.0-201-generic)
MLT stderr CPU=s390x (4 logical CPUs) (0x1f7231000 RAM)
MLT stderr fpr0 429676f300000000 (f: 0.000000, d: 6.175035e+12)
MLT stderr fpr1 3ecccda2b04fc787 (f: 2958018560.000000, d: 3.433617e-06)
MLT stderr fpr2 3e3ab28300000000 (f: 0.000000, d: 6.215952e-09)
MLT stderr fpr3 3e638f4eb0701078 (f: 2960134144.000000, d: 3.643296e-08)
MLT stderr fpr4 be0f2cf100000298 (f: 664.000000, d: -9.073280e-10)
MLT stderr fpr5 41a00000b04fb750 (f: 2958014208.000000, d: 1.342178e+08)
MLT stderr fpr6 bd95b6f100000000 (f: 0.000000, d: -4.937332e-12)
MLT stderr fpr7 3f2aab3443b92010 (f: 1136205824.000000, d: 2.034665e-04)
MLT stderr fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
MLT stderr fpr9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr10 000003ffaf440000 (f: 2940469248.000000, d: 2.172254e-311)
MLT stderr fpr11 000003ffd787f1dd (f: 3616010752.000000, d: 2.172588e-311)
MLT stderr fpr12 000003ffdc8fbfec (f: 3700408320.000000, d: 2.172630e-311)
MLT stderr fpr13 000003ffea77d4e8 (f: 3933721856.000000, d: 2.172745e-311)
MLT stderr fpr14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
MLT stderr fpr15 000003ff4877d968 (f: 1215814016.000000, d: 2.171402e-311)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr Module=/home/jenkins/workspace/Test_openjdk8_j9_sanity.system_s390x_linux/openjdkbinary/j2sdk-image/jre/lib/s390x/default/libj9gc29.so
MLT stderr Module_base_address=000003FFAD680000
MLT stderr Target=2_90_20210303_923 (Linux 4.4.0-201-generic)
MLT stderr CPU=s390x (4 logical CPUs) (0x1f7231000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x000003FFAD80F3BE [libj9gc29.so+0x18f3be])
MLT stderr (0x000003FFAD864A1A [libj9gc29.so+0x1e4a1a])
MLT stderr (0x000003FFAD81EEE0 [libj9gc29.so+0x19eee0])
MLT stderr (0x000003FFAD83AA50 [libj9gc29.so+0x1baa50])
MLT stderr (0x000003FFAD7CB5C6 [libj9gc29.so+0x14b5c6])
MLT stderr (0x000003FFAD8383AA [libj9gc29.so+0x1b83aa])
MLT stderr (0x000003FFAD839F66 [libj9gc29.so+0x1b9f66])
MLT stderr (0x000003FFAD83A224 [libj9gc29.so+0x1ba224])
MLT stderr (0x000003FFAD7B698A [libj9gc29.so+0x13698a])
MLT stderr (0x000003FFAD83B596 [libj9gc29.so+0x1bb596])
MLT stderr (0x000003FFAD83C5B2 [libj9gc29.so+0x1bc5b2])
MLT stderr (0x000003FFAD7A6A7E [libj9gc29.so+0x126a7e])
MLT stderr (0x000003FFAD8A23E0 [libj9gc29.so+0x2223e0])
MLT stderr (0x000003FFAD87DA96 [libj9gc29.so+0x1fda96])
MLT stderr (0x000003FFAD7CF6EC [libj9gc29.so+0x14f6ec])
MLT stderr (0x000003FFAD7CEC32 [libj9gc29.so+0x14ec32])
MLT stderr (0x000003FFAD7D5B30 [libj9gc29.so+0x155b30])
MLT stderr (0x000003FFAD6CF214 [libj9gc29.so+0x4f214])
MLT stderr (0x000003FFAF637410 [libj9vm29.so+0xb7410])
MLT stderr (0x000003FFAF621320 [libj9vm29.so+0xa1320])
MLT stderr (0x000003FFAF714B3C [libj9vm29.so+0x194b3c])
MLT stderr ---------------------------------------
MLT stderr (0x000003FFAD8269E4 [libj9gc29.so+0x1a69e4])
MLT stderr (0x000003FFAD83E1B6 [libj9gc29.so+0x1be1b6])
MLT stderr (0x000003FFAD6C7A00 [libj9gc29.so+0x47a00])
MLT stderr (0x000003FFAF60D9D4 [libj9vm29.so+0x8d9d4])
MLT stderr (0x000003FFAF60E1D8 [libj9vm29.so+0x8e1d8])
MLT stderr (0x000003FFAD6C7AC4 [libj9gc29.so+0x47ac4])
MLT stderr (0x000003FFAD6BEC4A [libj9gc29.so+0x3ec4a])
MLT stderr (0x000003FFAD6BD56A [libj9gc29.so+0x3d56a])
MLT stderr (0x000003FFAD6C087C [libj9gc29.so+0x4087c])
MLT stderr (0x000003FFAD83AB16 [libj9gc29.so+0x1bab16])
MLT stderr (0x000003FFAD7CAA50 [libj9gc29.so+0x14aa50])
MLT stderr (0x000003FFAD7CA2D8 [libj9gc29.so+0x14a2d8])
MLT stderr (0x000003FFAF4B327E [libj9prt29.so+0x3327e])
MLT stderr (0x000003FFAD7C9C98 [libj9gc29.so+0x149c98])
MLT stderr (0x000003FFAF405A14 [libj9thr29.so+0x5a14])
MLT stderr (0x000003FFB0807934 [libpthread.so.0+0x7934])
MLT stderr (0x000003FFB05EDD5A [libc.so.6+0xedd5a])
MLT stderr ---------------------------------------
```

**Comment by pshipton** [comment] 2021-03-04 13:40
@andrew-m-leonard I expect so. It's fixed on March 3 ~6:30pm EST, so it shouldn't be seen in subsequent builds.

**Comment by pshipton** [comment] 2021-03-04 14:02
Closing this since this problem is resolved by backing out the problematic change. https://github.com/eclipse/openj9/pull/12116 is in progress to fix and re-introduce the changes.

**Closed by pshipton** 2021-03-04 14:02 UTC
Labels: blocker, comp:gc, segfault, test failure
