### ISSUE TITLE
JTReg test fail - Linux s390 : java/lang/invoke/VarHandles/VarHandleTestAccessString.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#4640] opened 2019-02-07 15:12 UTC
Consistent failures ...

```
config VarHandleTestAccessString.setup(): success
test VarHandleTestAccessString.testAccess("VarHandle -> Instance final field", VarHandleBaseTest$VarHandleAccessTestCase@3a44a29a): success
test VarHandleTestAccessString.testAccess("VarHandle -> Instance final field unsupported", VarHandleBaseTest$VarHandleAccessTestCase@3a6fa1c5): success
test VarHandleTestAccessString.testAccess("VarHandle -> Static final field", VarHandleBaseTest$VarHandleAccessTestCase@5a159dbe): failure
java.lang.AssertionError: get String value expected [foo] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at VarHandleTestAccessString.testStaticFinalField(VarHandleTestAccessString.java:338)
	at VarHandleTestAccessString$$Lambda$9.0000000034174C80.action(Unknown Source)
	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
	at VarHandleTestAccessString.testAccess(VarHandleTestAccessString.java:232)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
test VarHandleTestAccessString.testAccess("VarHandle -> Static final field unsupported", VarHandleBaseTest$VarHandleAccessTestCase@162d5cc4): success
test VarHandleTestAccessString.testAccess("VarHandle -> Instance field", VarHandle -> Instance field): success
test VarHandleTestAccessString.testAccess("VarHandle -> Instance field unsupported", VarHandleBaseTest$VarHandleAccessTestCase@f53ae49a): success
test VarHandleTestAccessString.testAccess("VarHandle -> Static field", VarHandle -> Static field): failure
java.lang.AssertionError: set String value expected [foo] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at VarHandleTestAccessString.testStaticField(VarHandleTestAccessString.java:646)
	at VarHandleTestAccessString$$Lambda$13.00000000341761C0.action(Unknown Source)
	at VarHandleBaseTest$AccessTestCase.testAccess(VarHandleBaseTest.java:405)
	at VarHandleTestAccessString.testAccess(VarHandleTestAccessString.java:232)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

... of test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/VarHandles/VarHandleTestAccessString.java on Linux s390.

Latest failure - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_s390x_linux/141/testReport/junit/java_lang_invoke_VarHandles_VarHandleTestAccessString/java/VarHandleTestAccessString

See also - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_s390x_linux/141/consoleText

No such issue on Linux - https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux/276/testReport/java_lang_invoke_VarHandles_VarHandleTestAccessString/java/VarHandleTestAccessString

100x run shows a 100% failure rate - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/996

Kicked off 100x with -Xint - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1013

**Comment by pdbain-ibm** [comment] 2019-02-07 15:50
Maybe a duplicate of 
https://github.com/eclipse/openj9/issues/3180.  
@DanHeidinga or @pshipton what's the prognosis for https://github.com/eclipse/openj9/pull/4458?

**Comment by smlambert** [comment] 2019-02-07 16:10
Excluded via: https://github.com/AdoptOpenJDK/openjdk-tests/pull/865

**Comment by StephanieMeakins** [comment] 2019-02-12 15:23
I've also now seen this issue on AIX and attached the console out. I have also excluded the test on AIX.

[4640.txt](https://github.com/eclipse/openj9/files/2856413/4640.txt)

**Comment by pdbain** [comment] 2019-02-13 15:35
Issue #4458 is nominally resolved as of 11 February.  The test log shows the JVM is older:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+8-201902021914)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-03a061a, JRE 11 AIX ppc64-64-Bit Compressed References 20190202_116 (JIT enabled, AOT enabled)
```
@StephanieMeakins or @ben-walsh would you kindly retest with a current build?
Thank you.
    -p

**Comment by pdbain-ibm** [comment] 2019-03-19 17:46
@StephanieMeakins or @ben-walsh Can we close this?

**Comment by ben-walsh** [comment] 2019-03-20 12:01
Retests using Nightly ...
AIX : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1315
zLinux : https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1316

**Comment by ben-walsh** [comment] 2019-03-20 12:55
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1315/consoleText (AIX) shows consistent failures, as originally raised (https://github.com/eclipse/openj9/issues/4640#issue-407747824)

**Comment by ben-walsh** [comment] 2019-03-20 15:38
@pdbain-ibm Doesn't look like the fix has resolved the problem ^

**Comment by pdbain-ibm** [comment] 2019-03-21 18:55
@ben-walsh Does this occur on Linux?

**Comment by ben-walsh** [comment] 2019-03-22 10:29
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1316/consoleText (zLinux) finally completed - that shows such failures BUT not consistently.

I have kicked off an xLinux run - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1339 and pLinux run - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1340.

**Comment by ben-walsh** [comment] 2019-03-22 10:47
xLinux 3x clear - rebuilding with 30x - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1343
pLinux 3x clear - rebuilding with 30x - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1344

**Comment by ben-walsh** [comment] 2019-03-22 14:07
Both xLinux and pLinux 30x runs clear.

**Comment by pdbain-ibm** [comment] 2019-03-22 14:12
> https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1316/consoleText (zLinux) finally completed - that shows such failures BUT not consistently.
> 

Sounds like a timing issue.  Will investigate.

**Comment by ben-walsh** [comment] 2019-03-22 14:33
Agreed. I've kicked off an internal 100x run to gather more evidence. Will update this issue with console text once it has completed.

**Comment by ben-walsh** [comment] 2019-03-22 17:04
100x run result : [consoleText.txt](https://github.com/eclipse/openj9/files/2997509/consoleText.txt)

**Comment by pdbain-ibm** [comment] 2019-03-22 20:05
Reproduced on Linux390.

**Comment by pdbain-ibm** [comment] 2019-03-25 19:01
Does not manifest on Linux X86.  Fails with `-Xint`.

**Comment by pdbain-ibm** [comment] 2019-03-28 16:08
~Fails with -Xint.~  My mistake: the test runs twice, once with `-Xint` and again without.
The test fails without `-Xint`.
Forcing both to run without the JIT: `make JVM_OPTIONS=-Xint _jdk_custom` makes the test pass consistently.
This appears to be a JIT issue.  FYI @fjeremic would you kindly triage.  I have a test setup on a zLinux box if you need access.

**Comment by fjeremic** [comment] 2019-03-28 16:30
> This appears to be a JIT issue. FYI @fjeremic would you kindly triage. I have a test setup on a zLinux box if you need access.

Sure, I'll contact you on Slack to get a reporduction going.

**Comment by pdbain-ibm** [comment] 2019-03-28 16:52
The symptoms are that we create a `BruteArgumentMoverHandle` on the first use of the VarHandle `vh` to a static String field.  After ~1000 iterations of the test, `vh` starts returning null and we see another call to the `BruteArgumentMoverHandle` constructor.

**Comment by fjeremic** [comment] 2019-03-28 17:06
Issue happens due to the UnsafeFastPath optimization. It seems to transform the following trees:

```
n17n      NULLCHK on n7n [#30]                                                                [     0x3ff95201890] bci=[-1,16,124] rc=0 vc=0 vn=- li=- udi=- nc=1
n16n        acall  jdk/internal/misc/Unsafe.getObject(Ljava/lang/Object;J)Ljava/lang/Object;[#365  final native virtual Method -192] [flags 0x20500 0x0 ] (sharedMemory )  [     0x3ff9520184n7n           aload  java/lang/invoke/VarHandle._unsafe Ljdk/internal/misc/Unsafe;[#359  final Static] (obj1) [flags 0x20307 0x0 ]  [     0x3ff95201570] bci=[-1,5,124] rc=1 vc=0 vn=- li=- u
n9n           ==>aloadi
n14n          ==>lloadi
```

into

```
n45n      treetop                                                                             [     0x3ff95202150] bci=[-1,5,124] rc=0 vc=0 vn=- li=- udi=- nc=1
n7n         aload  java/lang/invoke/VarHandle._unsafe Ljdk/internal/misc/Unsafe;[#359  final Static] (obj1) [flags 0x20307 0x0 ]  [     0x3ff95201570] bci=[-1,5,124] rc=1 vc=0 vn=- li=- udin46n      treetop                                                                             [     0x3ff952021a0] bci=[-1,9,124] rc=0 vc=0 vn=- li=- udi=- nc=1
n42n        aloadi  <ramStaticsFromClass>[#292  Shadow +72] [flags 0x10607 0x0 ]              [     0x3ff95202060] bci=[-1,9,124] rc=2 vc=0 vn=- li=- udi=- nc=1
n41n          aloadi  <classFromJavaLangClass>[#290  Shadow +8] [flags 0x10607 0x0 ]          [     0x3ff95202010] bci=[-1,9,124] rc=1 vc=0 vn=- li=- udi=- nc=1
n9n             ==>aloadi
n47n      treetop                                                                             [     0x3ff952021f0] bci=[-1,13,124] rc=0 vc=0 vn=- li=- udi=- nc=1
n44n        land (X>=0 )                                                                      [     0x3ff95202100] bci=[-1,13,124] rc=2 vc=0 vn=- li=- udi=- nc=2 flg=0x100
n14n          ==>lloadi
n43n          lconst -2                                                                       [     0x3ff952020b0] bci=[-1,13,124] rc=1 vc=0 vn=- li=- udi=- nc=0
n50n      compressedRefs                                                                      [     0x3ff952022e0] bci=[-1,16,124] rc=0 vc=0 vn=- li=- udi=- nc=2
n16n        aloadi  <unsafe shadow sym>[#366  Shadow] [flags 0x80000607 0x100 ]               [     0x3ff95201840] bci=[-1,16,124] rc=2 vc=0 vn=- li=- udi=- nc=1
n48n          aladd                                                                           [     0x3ff95202240] bci=[-1,9,124] rc=1 vc=0 vn=- li=- udi=- nc=2
n42n            ==>aloadi
n44n            ==>land
n49n        lconst 0                                                                          [     0x3ff95202290] bci=[-1,16,124] rc=1 vc=0 vn=- li=- udi=- nc=0
```

I'm not sure how exactly it got rid of the `NULLCHK` or why it did it. In any way I don't see anything wrong with what the codegen generates. This looks like a faulty optimization. 

@liqunl @andrewcraik FYI re-tagging this as an optimizer issue. I've attached the trace log below and how to reproduce the issue on Peter's setup.

[get.trace.txt](https://github.com/eclipse/openj9/files/3019316/get.trace.txt)

```
cd /home/pdbain/openjdk-tests/TestConfig/test_output_15536288419910/jdk_custom_0
export TR_Options='limit={java/lang/invoke/StaticFieldVarHandle$StaticFieldVarHandleOperations$OpObject.get(Ljava/lang/invoke/VarHandle;)Ljava/lang/Object;}(lastoptindex=4,tracefull,log=/home/pdbain/openjdk-tests/TestConfig/test_output_15536288419910/jdk_custom_0/log.trace)'
./unittest.sh
```

**Comment by fjeremic** [comment] 2019-03-28 17:09
FYI also fails on AIX (see above).

**Comment by liqunl** [comment] 2019-03-28 18:25
The `NULLCHK` is removed because this is internal code and we know it can't be null. I think the problematic part is the `compressedRefs` anchor on the unsafe shadow, as the unsafe shadow points to a static field that won't get compressed. Will get the fix.

**Comment by liqunl** [comment] 2019-04-01 19:06
Tested the change with Peter's set up, the issue is fixed.

**Closed** 2019-04-03 19:14 UTC
Labels: comp:jit, test excluded, test failure

**Comment by pdbain-ibm** [comment] 2019-04-08 14:07
> Excluded via: [AdoptOpenJDK/openjdk-tests#865](https://github.com/AdoptOpenJDK/openjdk-tests/pull/865)

@smlambert This is fixed.  Would you kindly re-enable the test?  @ben-walsh FYI.
Thanks

**Comment by ben-walsh** [comment] 2019-04-08 14:21
PR to de-exclude - https://github.com/AdoptOpenJDK/openjdk-tests/pull/1063

**Comment by smlambert** [comment] 2019-04-09 01:29
test reincluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/1063
