### ISSUE TITLE
JDK11 JIT Server : MathLoadTest_bigdecimal_special_18 POSSIBLE HANG DETECTED

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9270] opened 2020-04-17 00:46 UTC
Failure link
------------

From an internal build `Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/298`:
```
22:39:08  openjdk version "11.0.7-internal" 2020-04-14
22:39:08  OpenJDK Runtime Environment (build 11.0.7-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
22:39:08  Eclipse OpenJ9 VM (build ibm_sdk-2ef1e03d1c, JRE 11 Linux amd64-64-Bit Compressed References 20200415_51 (JIT enabled, AOT enabled)
22:39:08  OpenJ9   - 2ef1e03d1c
22:39:08  OMR      - da8f4f55b
22:39:08  JCL      - cc6eef2754e based on jdk-11.0.7+10)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
=============================================== 
Running test MathLoadTest_bigdecimal_special_18 ... ===============================================

STF 02:19:24.105 - Heartbeat: Process MLT is still running
MLT 02:19:26.005 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:19:46.053 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:20:05.998 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:20:26.047 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:20:45.993 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:21:06.038 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:21:21.633 - **POSSIBLE HANG DETECTED**
STF 02:21:21.982 - **FAILED** Process MLT has hung
STF 02:21:21.982 - Collecting dumps for: MLT
STF 02:21:21.983 - Sending SIG 3 to the java process to generate a javacore
STF 02:21:21.983 - Running command: kill -3 8993
STF 02:21:21.983 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stderr
STF 02:21:21.983 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stdout
STF 02:21:21.987 - Pausing for 30 seconds
STF 02:21:51.987 - Sending SIG 3 to the java process to generate a javacore
STF 02:21:51.988 - Running command: kill -3 8993
STF 02:21:51.988 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stderr
STF 02:21:51.988 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stdout
STF 02:21:51.991 - Pausing for 30 seconds
STF 02:22:21.992 - Sending SIG 3 to the java process to generate a javacore
STF 02:22:21.993 - Running command: kill -3 8993
STF 02:22:21.993 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stderr
STF 02:22:21.993 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_3.stdout
STF 02:22:21.996 - Pausing for 30 seconds
STF 02:22:51.997 - Sending SIGABRT (kill -6) to the java process to generate a core
STF 02:22:51.998 - Running command: kill -6 8993
STF 02:22:51.998 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_6.stderr
STF 02:22:51.998 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_6.stdout
STF 02:22:52.002 - Pausing for 30 seconds
STF 02:23:22.002 - Sending SIGXCPU (kill -24) to the java process to generate an OS dump
STF 02:23:22.003 - Running command: kill -24 8993
STF 02:23:22.004 - Redirecting stderr to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_24.stderr
STF 02:23:22.004 - Redirecting stdout to /home/jenkins/workspace/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15870049861659/MathLoadTest_bigdecimal_special_18/20200416-020419-MathLoadTest/results/1.MLT.kill_24.stdout
MLT 02:21:26.048 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:21:26.650 - **POSSIBLE HANG DETECTED**
MLT 02:21:31.662 - **POSSIBLE HANG DETECTED**
MLT 02:21:36.674 - **POSSIBLE HANG DETECTED**
MLT 02:21:41.686 - **POSSIBLE HANG DETECTED**
MLT 02:21:45.996 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:21:46.698 - **POSSIBLE HANG DETECTED**
MLT 02:21:51.710 - **POSSIBLE HANG DETECTED**
MLT 02:21:56.726 - **POSSIBLE HANG DETECTED**
MLT 02:22:01.737 - **POSSIBLE HANG DETECTED**
MLT 02:22:06.047 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:22:06.749 - **POSSIBLE HANG DETECTED**
MLT 02:22:11.760 - **POSSIBLE HANG DETECTED**
MLT 02:22:16.771 - **POSSIBLE HANG DETECTED**
MLT 02:22:21.783 - **POSSIBLE HANG DETECTED**
MLT 02:22:25.993 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:22:26.795 - **POSSIBLE HANG DETECTED**
MLT 02:22:31.807 - **POSSIBLE HANG DETECTED**
MLT 02:22:36.818 - **POSSIBLE HANG DETECTED**
MLT 02:22:41.829 - **POSSIBLE HANG DETECTED**
MLT 02:22:46.040 - Completed 0.3%. Number of tests started=3 (+0)
MLT 02:22:46.842 - **POSSIBLE HANG DETECTED**
MLT 02:22:51.854 - **POSSIBLE HANG DETECTED**
MLT stderr JVMDUMP039I Processing dump event "user", detail "" at 2020/04/16 02:21:21 - please wait.

MathLoadTest_bigdecimal_special_18_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=system/mathLoadTest&PLATFORM=x86-64_linux&TARGET=MathLoadTest_bigdecimal_special_18

**Comment by pshipton** [comment] 2020-04-17 01:16
@mpirvu

**Comment by harryyu1994** [comment] 2020-04-17 18:41
Launched 10x grinder: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7141/

**Comment by JasonFengJ9** [comment] 2020-04-22 23:56
Another _POSSIBLE HANG DETECTED_ occurrence at JDK8 JIT Server `Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly/334`.

**Comment by dmitry-ten** [comment] 2020-04-28 18:33
I'll look into this.

**Comment by dmitry-ten** [comment] 2020-04-29 17:02
Ran the test 20 times in [Jenkins](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7489/), no hangs. Seems the problem is intermittent at best.
Will try running it for more iterations.

**Comment by dmitry-ten** [comment] 2020-05-05 16:33
Did another 20 runs [here](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/7685/), everything passed again. Hopefully, it seems like the problem went away, probably due to some other changes

**Comment by EmanElsaban** [comment] 2020-11-05 22:28
Ran 100 tests on Grinder, all tests passed. https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11877/ 

Output from console:

Java version:
```
15:28:14  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9-ea+11)
15:28:14  Eclipse OpenJ9 VM AdoptOpenJDK (build master-f702659ca, JRE 11 Linux amd64-64-Bit Compressed References 20201028_818 (JIT enabled, AOT enabled)
15:28:14  OpenJ9   - f702659ca
15:28:14  OMR      - bb2458426
15:28:14  JCL      - fd18c0317c based on jdk-11.0.9+11)
```
FYI: @mpirvu

**Comment by mpirvu** [comment] 2020-11-12 14:45
Closing based on the last comment

**Comment by EmanElsaban** [comment] 2020-11-12 14:46
I checked the past nightly builds in https://hyc-runtimes-jenkins.swg-devops.com/view/Nightly/job/Test_openjdk11_j9_special.system_x86-64_linux_jit_Nightly/ for ```MathLoadTest_bigdecimal_special_18``` test failure from recent build going back to build 544 (28-10-2020) and it passes in all. I also checked in jdk8: https://hyc-runtimes-jenkins.swg-devops.com/view/Nightly/job/Test_openjdk8_j9_special.system_x86-64_linux_jit_Nightly/ from recent build to build 547 (28-10-2020) and I see the test passing in all these builds as well.

It looks like the problem went away, I think the issue should be closed @mpirvu

**Closed by mpirvu** 2020-11-12 14:45 UTC
Labels: comp:jitserver, test failure
