### ISSUE TITLE
extended.system JIT crash running HCRLateAttachWorkload_0

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#5832] opened 2019-05-22 14:50 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_ppc64le_linux_Nightly/40
`Type=Illegal instruction vmState=0x00000000`
`Compiled_method=com/ibm/jit/JITHelpers.putCharInArrayByIndex(Ljava/lang/Object;IC)V`

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/42
`Type=Segmentation error vmState=0x00050080`
`Method_being_compiled=java/lang/String.charAt(I)C`

https://ci.eclipse.org/openj9/job/Test_openjdk12_j9_extended.system_ppc64_aix_Nightly/36
`Type=Segmentation error vmState=0x0005ff09`
`Method_being_compiled=java/lang/String.length()I`

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_s390x_linux_Nightly/40
`Type=Illegal instruction vmState=0x00000000`
`Compiled_method=unknown (In JIT code segment 000003FF880A91D8 but no method found)`

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/38
`Type=Illegal instruction vmState=0x00000000`
`Compiled_method=net/adoptopenjdk/test/hcrAgent/agent/AgentLogger.printThis(Ljava/lang/String;I)V`

**Comment by pshipton** [comment] 2019-05-22 14:50
@andrewcraik @fjeremic @gita-omr

**Comment by fjeremic** [comment] 2019-05-22 15:29
@andrewcraik could these be possible related to RAT changes that landed yesterday?

**Comment by andrewcraik** [comment] 2019-05-22 15:48
@fjeremic If you had asked me without any context I would say not likely since all the change does is defer clean up of assumptions from the RAT - the assumption is marked dead and not looked at once fired. That being said it is possible there is some kind of issue still. There is an env var in my change `TR_forceAggressiveRATCleaning` which if set to 1 will restore the previous mode of cleanup. Perhaps someone could launch a grinder to see if the failures go away with the env var? If they do I'll open a PR to revert while we figure out what went wrong. It would have to be some code that runs when the assumption is deallocated rather than when it is fired which didn't seem possible or some kind of race (which shouldn't happen because of the locking in the code), but perhaps I missed something...

**Comment by fjeremic** [comment] 2019-05-22 17:10
The issue is between 83e41afd and 653324d. I've confirmed via internal grinders (2404 and 2406). The compare https://github.com/eclipse/openj9/compare/83e41afd...653324d shows only a handful of commits. The OMR SHAs are identical so it's only those commits which could have caused the issues.

The most likely suspects there are from @DanHeidinga and @andrewcraik. I'm still trying to get a Grinder out with `export TR_forceAggressiveRATCleaning=1` which may not be supported, so we may have to get a build with that change reverted to isolate which commit introduced the issue.

**Comment by fjeremic** [comment] 2019-05-22 18:32
@andrewcraik the issue seems to be with the RAT change in #5826. I've confirmed via internal grinders:

Grinder 2404 against 83e41af: 0 / 10 failures
Grinder 2406 against 653324d: 3 / 10 failures
Grinder 2408 against 653324d: 0 / 10 failures (with `export TR_forceAggressiveRATCleaning=1`)

**Comment by pshipton** [comment] 2019-05-22 18:47
I'm going to revert #5826.

**Comment by pshipton** [comment] 2019-05-22 18:50
Thanks @fjeremic for tracking this down.

**Comment by andrewcraik** [comment] 2019-05-22 18:56
Ok the 3/10 would be why it didn't show up in the testing I did do - thanks for finding the cause.

**Closed** 2019-05-22 18:55 UTC
Labels: blocker, comp:jit, test failure

**Comment by kobinau** [comment] 2019-05-28 15:23
Ran grinder 1/4 failure rate.
https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/2465/
