### ISSUE TITLE
Test-Sanity-JDK8-linux_ppc-64 cmdLineTester_decompilationTests_1 decomp002 assert

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#2139] opened 2018-06-08 23:47 UTC
https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/289/

Occurred during omr acceptance.

```
Testing: decomp002
Test start time: 2018/06/08 21:55:41 Coordinated Universal Time
Running command: "/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/j2sdk-image/jre/bin/java"  -Xcompressedrefs -Xcompressedrefs -Xgcpolicy:gencon -Xjit:enableOSR,count=0  -Xdump -Xgcthreads1  -Xdump:system:events=abort  -agentlib:jvmtitest=test:decomp002 -cp "/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/TestConfig/scripts/testKitGen/../../../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 4 milliseconds
Time spent executing: 9943 milliseconds
Test result: FAILED
Output from test:
 [OUT] *** Testing [1/1]:	testStepping
 [OUT] 	Step 10000000 times
 [ERR] 21:55:50.926 0x12a00j9codertvm(j9ji.104    *   ** ASSERTION FAILED ** at decomp.cpp:584: (((IDATA)pendingStackHeight >= 0))
 [ERR] JVMDUMP039I Processing dump event "traceassert", detail "" at 2018/06/08 21:55:50 - please wait.
 [ERR] JVMDUMP032I JVM requested System dump using '/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/core.20180608.215550.19560.0001.dmp' in response to an event
 [ERR] JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.19612.
 [ERR] 
 [ERR] JVMDUMP010I System dump written to /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/core.20180608.215550.19560.0001.dmp
 [ERR] JVMDUMP032I JVM requested Java dump using '/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/javacore.20180608.215550.19560.0002.txt' in response to an event
 [ERR] JVMDUMP010I Java dump written to /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/javacore.20180608.215550.19560.0002.txt
 [ERR] JVMDUMP032I JVM requested Snap dump using '/home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/Snap.20180608.215550.19560.0003.trc' in response to an event
 [ERR] JVMDUMP010I Snap dump written to /home/jenkins/jenkins-agent/workspace/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/openj9/test/functional/cmdLineTests/jvmtitests/Snap.20180608.215550.19560.0003.trc
 [ERR] JVMDUMP013I Processed dump event "traceassert", detail "".
>> Success condition was not found: [Return code: 0]
```

**Comment by DanHeidinga** [comment] 2018-06-28 02:04
@gacholio can you take a look at this?

**Comment by gacholio** [comment] 2018-07-11 20:13
Discussing similar customer issue with @klangman, it looks like the FSD code is calling the wrong monitor enter helper for an inline synchronized method.

Pattern is:

Resolve frame (monitor enter)
inline synchronized method C at bytecode 0 calls jitMonitorEntry
inline method B calls C
method A calls B

This should be:

Resolve frame (method monitor enter)
inline synchronized method C at bytecode 0 calls jitMethodMonitorEntry
inline method B calls C
method A calls B

**Comment by gacholio** [comment] 2018-07-11 20:17
@cathyzhyi - I don't recall what we decided was correct here, using the method monitor enter helper for inlines, or the normal monitor enter helper before entering the inline frame.  I think the former sounds more correct for the decompile cases.

**Comment by cathyzhyi** [comment] 2018-07-11 20:33
@gacholio JIT has been calling normal monitor enter helper for inlined synchronized callee. We don't have any special logic for fsd [https://github.com/eclipse/openj9/blob/f7532ad249abdbc623be520445794db699fa4afe/runtime/compiler/ilgen/IlGenerator.cpp#L993-L996](url).

**Comment by gacholio** [comment] 2018-07-11 22:45
@cathyzhyi This will need to change.  The problem is that the inline reports that it's at bytecode 0, which means the pending stack is empty, but the decompile logic knows that for a normal monitor enter, the sync object is on the stack and must be removed, resulting in a stack height of -1, causing the assertion.

**Comment by gacholio** [comment] 2018-07-12 15:57
Looking at the VM support code, it looks like I am anticipating jitMethodMonitorEntry being used for inline frames.  This is definitely required to maintain consistency for reporting method entry for inline frames that get decompiled (decompile during jitMonitorEntry does not report the method enter upon return to the interpreter).

**Comment by pshipton** [comment] 2018-07-16 19:30
https://ci.eclipse.org/openj9/job/Test-Sanity-JDK8-linux_ppc-64_cmprssptrs_le/377/tapResults/

**Comment by gacholio** [comment] 2018-07-19 01:49
@cathyzhyi has this been fixed?

**Comment by cathyzhyi** [comment] 2018-07-20 13:36
@gacholio I am testing the fix. does this apply to OSR mode in general or only FSD?

**Comment by gacholio** [comment] 2018-07-20 13:39
If method enter is enabled, I believe that turns FSD on.  Fast HCR won't be reporting these events.

**Comment by cathyzhyi** [comment] 2018-07-20 13:53
>This will need to change. The problem is that the inline reports that it's at bytecode 0, which means the pending stack is empty, but the decompile logic knows that for a normal monitor enter, the sync object is on the stack and must be removed, resulting in a stack height of -1, causing the assertion.

I see. So this logic only happens in method enter reporting and doesn't apply to decompilation in general right?

**Comment by gacholio** [comment] 2018-07-20 14:02
Sorry, I was confused.  This is monitor enter, not method enter, so it technically applies everywhere, but in practice, fast HCR would never attempt an OSR at this point, only FSD would.  Having said that, there's no reason to restrict this fix to FSD - it's much simpler to just call the correct helper in all cases.

**Comment by cathyzhyi** [comment] 2018-07-20 14:20
Thanks for the clarification. Another question, is MethodMonitorEnter helper gonna be more expensive than normal monitor enter? OSR mode is on by default, would there be performance impact or that's negligible?

**Comment by gacholio** [comment] 2018-07-20 14:54
The helpers are essentially identical - the method one has a different stack frame type and some extra code in the case where the enter fails (which basically never happens).

**Comment by gacholio** [comment] 2018-07-25 19:47
Not closed by merging PR for some reason.

**Closed by gacholio** 2018-07-25 19:47 UTC
Labels: comp:jit, prio:high, test failure

**Comment by pshipton** [comment] 2018-07-25 19:56
> Not closed by merging PR for some reason.

The PR needs to contain a keyword, like "closes #2139", "fixes #2139", etc.

**Comment by pshipton** [comment] 2018-07-25 19:57
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by gacholio** [comment] 2018-07-25 19:58
Ah, it only said "issue".
