### ISSUE TITLE
OpenJDK9/10 with OpenJ9 is slower at Xint than OpenJDK8 with OpenJ9

### ISSUE THREAD

**Issue by mpirvu** [eclipse/openj9#1888] opened 2018-05-10 14:35 UTC
I took the following builds from adoptopenjdk.net
OpenJDK8-OPENJ9_x64_Linux_20180507
OpenJDK9-OPENJ9_x64_Linux_20180509
OpenJDK10-OPENJ9_x64_Linux_20180509

I ran `time java -Xint -version` and found the following running times:

OpenJDK8-OPENJ9_x64_Linux_20180507
```
real    0m0.042s
user    0m0.040s
sys     0m0.000s
```
OpenJDK9-OPENJ9_x64_Linux_20180509
```
real    0m0.115s
user    0m0.076s
sys     0m0.036s
```
OpenJDK9-OPENJ9_x64_Linux_20180509
```
real    0m0.123s
user    0m0.052s
sys     0m0.068s
```

There is a large increase in the system time and a small increase in the user time when moving from OpenJDK8 to OpenJDK9/10.
I collected a profile with `perf record -e cycles -c 200000 -- java -Xint -version`
In OpenJDK9/10 I see many ticks in kernel related functions like `unmap_page_range` and `free_pgd_range`, but also more ticks in the interpreter code. Some excerpts:

OpenJDK8
```
   6.27%            51  main             libj9vm29.so           [.] _ZN22VM_BytecodeInterpreter3runEP10J9VMThread         
   5.90%            48  java             libj9vm29.so           [.] zipCache_searchFileList
   3.08%            25  java             libj9vm29.so           [.] zipCache_addElement
   2.46%            20  main             libj9vm29.so           [.] _ZN15ClassFileOracle27walkMethodCodeAttributeCodeEt
   2.34%            19  java             libc-2.23.so           [.] __memcmp_sse4_1
   2.21%            18  java             libj9vm29.so           [.] _ZN15ClassFileOracle27walkMethodCodeAttributeCodeEt
   1.23%            10  Attach API init  libj9vm29.so           [.] _ZN22VM_BytecodeInterpreter3runEP10J9VMThread
   1.23%            10  java             libc-2.23.so           [.] __memcpy_avx_unaligned
   0.98%             8  java             libj9vm29.so           [.] _ZN14ROMClassWriter12writeMethodsEP6CursorS1_S1_b
   0.98%             8  main             libj9vm29.so           [.] _ZN14ROMClassWriter10writeUTF8sEP6Cursor
   0.86%             7  java             [kernel.kallsyms]      [k] copy_user_enhanced_fast_string
   0.86%             7  java             libc-2.23.so           [.] __strncmp_sse42
   0.86%             7  java             libj9prt29.so          [.] parse_catalog
   0.86%             7  main             libc-2.23.so           [.] __memcmp_sse4_1
```

OpenJDK9
```
  17.04%           496  java             [kernel.kallsyms]   [k] unmap_page_range
  11.99%           349  java             [kernel.kallsyms]   [k] free_pgd_range
  10.96%           319  main             libj9vm29.so        [.] _ZN22VM_BytecodeInterpreter3runEP10J9VMThread
   4.33%           126  java             [kernel.kallsyms]   [k] _cond_resched
   2.85%            83  java             [kernel.kallsyms]   [k] entry_SYSCALL_64
   2.06%            60  java             [kernel.kallsyms]   [k] entry_SYSCALL_64_fastpath
   1.48%            43  java             [kernel.kallsyms]   [k] vma_compute_subtree_gap
   1.17%            34  java             [kernel.kallsyms]   [k] find_vma
   1.06%            31  java             [kernel.kallsyms]   [k] entry_SYSCALL_64_after_swapgs
   0.79%            23  main             libj9vm29.so        [.] _ZN15ClassFileOracle27walkMethodCodeAttributeCodeEt
   0.79%            23  main             libj9vm29.so        [.] checkForJsrs
   0.79%            23  main             libj9vm29.so        [.] internHashFn
   0.72%            21  java             libj9prt29.so       [.] compareAndSwapUDATA
   0.69%            20  java             [kernel.kallsyms]   [k] perf_event_aux_ctx
   0.65%            19  main             libj9vm29.so        [.] _ZN15ConstantPoolMap30computeConstantPoolMapAndSizesEv
   0.62%            18  java             [kernel.kallsyms]   [k] perf_event_aux.part.57
   0.58%            17  java             [kernel.kallsyms]   [k] arch_get_unmapped_area_topdown
   0.58%            17  java             [kernel.kallsyms]   [k] mmap_region
   0.58%            17  java             libj9vm29.so        [.] _ZN15ClassFileOracle27walkMethodCodeAttributeCodeEt
```

**Comment by pshipton** [comment] 2018-05-10 18:13
The cost of booting with modularity? Does OpenJDK have similar performance?

**Comment by babsingh** [comment] 2018-07-04 21:59
I used the following **perf** commands:
1) **perf record:** `perf record --call-graph dwarf -- <java_cmd>`
2) **perf report:** `perf report --stdio -i <perf_data_file>` 
3) **perf diff:** `perf diff -f perf_jdk8_dwarf.data perf_jdk9_dwarf.data` [baseline - Java 8]

**Subset of perf diff report**:
```
# Baseline  Delta Abs  Shared Object      Symbol                                                               
# ........  .........  .................  .....................................................................
#
              +18.67%  [kernel.kallsyms]  [k] unmap_page_range
     1.90%    +17.44%  libj9vm29.so       [.] VM_BytecodeInterpreter::run
    17.50%    -17.37%  libj9vm29.so       [.] readAttributes
               +7.86%  libj9vm29.so       [.] StringInternTable::areAddressesInSRPRange
     5.90%     -4.54%  libj9vm29.so       [.] ClassFileOracle::walkMethodCodeAttributeCode
     4.57%     -4.48%  libj9vm29.so       [.] j9bcutil_verifyCanonisizeAndCopyUTF8
               +3.70%  libj9vm29.so       [.] VM_BytecodeInterpreter::inlineSendTarget
     0.40%     +3.38%  libj9vm29.so       [.] ROMClassWriter::Helper::writeUTF8Block
               +2.84%  libj9vm29.so       [.] VM_BytecodeInterpreter::putfield
               +2.70%  [kernel.kallsyms]  [k] syscall_return_via_sysret
     2.78%     -2.70%  libj9vm29.so       [.] VM_BytecodeInterpreter::iinc
               +2.40%  libj9vm29.so       [.] Cursor::writeBigEndianU16
               +1.86%  [kernel.kallsyms]  [k] __check_heap_object
               +1.72%  libj9prt29.so      [.] omrmem_categories_increment_bytes
               +1.65%  [kernel.kallsyms]  [k] free_pgd_range
               +1.34%  libj9prt29.so      [.] update_vmemIdentifier
               +1.27%  libj9vm29.so       [.] VM_AtomicSupport::lockCompareExchange
               +1.15%  libj9vm29.so       [.] VM_BytecodeInterpreter::getfieldLogic
     0.06%     +1.10%  [kernel.kallsyms]  [k] find_vma
```
In @mpirvu's perf data above, 
1) In Java 9, `unmap_page_range` and `free_pgd_range` consume +850 ticks. 
2) In Java 9, `VM_BytecodeInterpreter::run` consumes 319 ticks. In Java 8, `VM_BytecodeInterpreter::run` only consumes 51 ticks.
 
**Hot code paths:**
1) The call stack below shows that `omrvmem_free_memory` is the source of `unmap_page_range`, `free_pgd_range` and `syscall_return_via_sysret` calls in Java 9. `omrvmem_free_memory` is related to `omrvmem_reserve_memory_ex`. The source of `omrvmem_reserve_memory_ex` is `j9gc_initialize_heap`. **Adding GC members to look at this:** @dmitripivkine @amicic.

```
   25.17%     0.14%  java             libj9prt29.so          [.] omrvmem_free_memory
            |          
             --25.03%--omrvmem_free_memory
                       |          
                        --24.95%--__GI___munmap
                                  |          
                                  |--22.57%--entry_SYSCALL_64_fastpath
                                  |          sys_munmap
                                  |          vm_munmap
                                  |          |          
                                  |           --22.50%--do_munmap
                                  |                     |          
                                  |                     |--20.47%--unmap_region
                                  |                     |          |          
                                  |                     |          |--18.67%--unmap_vmas
                                  |                     |          |          unmap_single_vma
                                  |                     |          |          unmap_page_range
                                  |                     |          |          
                                  |                     |           --1.72%--free_pgtables
                                  |                     |                     |          
                                  |                     |                      --1.65%--free_pgd_range
                                  |                     |          
                                  |                      --1.12%--find_vma
                                  |          
                                   --2.23%--syscall_return_via_sysret
```

```
              |--3.61%--j9gc_initialize_heap
               |          MM_Configuration::createHeap
               |          MM_ConfigurationGenerational::createHeapWithManager
               |          MM_ConfigurationStandard::createHeapWithManager
               |          MM_HeapVirtualMemory::newInstance
               |          MM_HeapVirtualMemory::initialize
               |          MM_MemoryManager::createVirtualMemoryForHeap
               |          MM_VirtualMemory::newInstance
               |          MM_VirtualMemory::initialize
               |          MM_VirtualMemory::reserveMemory
               |          omrvmem_reserve_memory_ex
               |          getMemoryInRangeForDefaultPages
               |          |          
               |           --3.29%--default_pageSize_reserve_memory
               |                     |          
               |                     |--1.95%--__mmap64
               |                     |          |          
               |                     |           --1.81%--entry_SYSCALL_64_fastpath
               |                     |                     |          
               |                     |                      --1.74%--sys_mmap
               |                     |                                sys_mmap_pgoff
               |                     |                                vm_mmap_pgoff
               |                     |                                do_mmap
               |                     |                                |          
               |                     |                                 --1.34%--mmap_region
               |                     |                                           |          
               |                     |                                            --0.65%--perf_event_mmap
               |                     |                                                      |          
               |                     |                                                       --0.57%--perf_iterate_sb
               |                     |                                                                 |          
               |                     |                                                                  --0.50%--perf_iterate_ctx
               |                     |          
               |                      --1.34%--update_vmemIdentifier

```

2) The call stack below shows `StringInternTable::areAddressesInSRPRange` is called +7.86% in Java 9 from `initializeKnownClasses`. **VM changes:** @DanHeidinga @pshipton.

 ```
--8.03%--initializeKnownClasses
               |                     resolveStaticFieldRef
               |                     resolveStaticFieldRefInto
               |                     resolveClassRef
               |                     internalFindClassUTF8
               |                     internalFindClassInModule
               |                     loadNonArrayClass
               |                     attemptDynamicClassLoad
               |                     internalDefineClass
               |                     createROMClassFromClassFile
               |                     internalLoadROMClass
               |                     callDynamicLoader
               |                     j9bcutil_buildRomClass
               |                     ROMClassBuilder::buildROMClass
               |                     ROMClassBuilder::prepareAndLaydown
               |                     ROMClassBuilder::finishPrepareAndLaydown
               |                     ROMClassStringInternManager::visitUTF8
               |                     |          
               |                      --7.95%--StringInternTable::findUtf8
               |                                |          
               |                                 --7.86%--StringInternTable::areAddressesInSRPRange
```

3) Source of +3.70% `VM_BytecodeInterpreter::inlineSendTarget` in Java 9. **VM changes:** @DanHeidinga @pshipton.

```
--3.46%--VM_BytecodeInterpreter::invokedynamic
            |          |          resolveInvokeDynamic
            |          |          sendResolveInvokeDynamic
            |          |          c_cInterpreter
            |          |          bytecodeLoop
            |          |          VM_BytecodeInterpreter::run
            |          |          |          
            |          |           --3.21%--VM_BytecodeInterpreter::initialStaticMethod
            |          |                     resolveStaticMethodRef
            |          |                     resolveStaticMethodRefInto
            |          |                     initializeClass
            |          |                     classInitStateMachine
            |          |                     initializeImpl
            |          |                     sendClinit
            |          |                     c_cInterpreter
            |          |                     bytecodeLoop
            |          |                     VM_BytecodeInterpreter::run
            |          |                     VM_BytecodeInterpreter::sendTargetSmallNonSync
            |          |                     VM_BytecodeInterpreter::inlineSendTarget


```

4) Source of +3.38% `ROMClassWriter::Helper::writeUTF8Block` in Java 9. **VM changes:** @DanHeidinga @pshipton.

```
--4.18%--VM_BytecodeInterpreter::initialStaticMethod
               |          |          resolveStaticMethodRef
               |          |          resolveStaticMethodRefInto
               |          |          |          
               |          |          |--3.66%--resolveClassRef
               |          |          |          internalFindClassUTF8
               |          |          |          internalFindClassInModule
               |          |          |          loadNonArrayClass
               |          |          |          |          
               |          |          |           --3.55%--attemptDynamicClassLoad
               |          |          |                     internalDefineClass
               |          |          |                     createROMClassFromClassFile
               |          |          |                     internalLoadROMClass
               |          |          |                     callDynamicLoader
               |          |          |                     j9bcutil_buildRomClass
               |          |          |                     ROMClassBuilder::buildROMClass
               |          |          |                     ROMClassBuilder::prepareAndLaydown
               |          |          |                     ROMClassBuilder::finishPrepareAndLaydown
               |          |          |                     ROMClassBuilder::layDownROMClass
               |          |          |                     ROMClassWriter::writeROMClass
               |          |          |                     ROMClassWriter::writeUTF8s
               |          |          |                     ROMClassWriter::Helper::writeUTF8Block

```

5) `VM_BytecodeInterpreter::putfield` (+2.84% in Java 9) is directly called from `VM_BytecodeInterpreter::run`. **VM changes:** @DanHeidinga @pshipton.

6) Source of +2.40% `Cursor::writeBigEndianU16` in Java 9. **VM changes:** @DanHeidinga @pshipton.

```
--2.40%--VM_BytecodeInterpreter::inlClassForNameImpl
               |          |          internalFindClassString
               |          |          internalFindClassInModule
               |          |          loadNonArrayClass
               |          |          attemptDynamicClassLoad
               |          |          internalDefineClass
               |          |          createROMClassFromClassFile
               |          |          internalLoadROMClass
               |          |          callDynamicLoader
               |          |          j9bcutil_buildRomClass
               |          |          ROMClassBuilder::buildROMClass
               |          |          ROMClassBuilder::prepareAndLaydown
               |          |          ROMClassBuilder::getSizeInfo
               |          |          ROMClassWriter::writeROMClass
               |          |          ROMClassWriter::writeMethods
               |          |          Cursor::writeBigEndianU16

```

- [perf_data_files.zip](https://github.com/eclipse/openj9/files/2164411/perf_data_files.zip) - Includes perf profiles for Java 8 and Java 9: `perf_jdk8_dwarf.data` and `perf_jdk9_dwarf.data`.

**Comment by DanHeidinga** [comment] 2018-07-05 04:21
> VM_BytecodeInterpreter::invokedynamic

This is likely due to more lambda expressions in the core class libraries in JDK9 than in JDK8.

> --8.03%--initializeKnownClasses

Have the number of known classes increased between 8 & 9?  Classes in the vmconstantpool are eagerly loaded which may slow startup.

The other interesting data point would be to compare -verbose:class output from 8 & 9 to see if how many additional classes are being loaded.

**Comment by dmitripivkine** [comment] 2018-07-05 15:19
I can not explain or reproduce difference between "OpenJ9 JDK9 -Xint -version" and "OpenJ9 JDK9 -Xint -Xmx8g -version". Which machine was used for testing? I obviously need to investigate. However this is just a side issue.
There is easy to reproduce case when exactly the same command line for Java 8 and Java 9 (used latest iBuild) takes ~50% (2 way) to ~100% (80 way) longer for Java 9

**Comment by charliegracie** [comment] 2018-07-09 19:33
@babsingh can you still reproduce the GC issue on your machine when omitting the `-Xmx` option? If so could you gather a verbose:gc log and a javacore for a `good` and `bad` run so I can compare them?

**Comment by babsingh** [comment] 2018-07-09 19:39
@charliegracie the local Ubuntu machine is at home. i will post `verbose:gc` and javacore(s) in the evening. At what event should I generate the javacore(s)?

**Comment by charliegracie** [comment] 2018-07-09 19:44
`vmstart` should be sufficient, I think.

**Comment by pshipton** [comment] 2018-07-09 20:51
Re https://github.com/eclipse/openj9/issues/1888#issuecomment-403593283, what are the extra classes loaded by OpenJ9 over OpenJDK?

**Comment by babsingh** [comment] 2018-07-09 21:32
> what are the extra jdk9 classes loaded by OpenJ9 over OpenJDK?

Difference between OpenJ9 JDK9 and OpenJDK JDK9 verbose log: [openjdk_openj9_extra_classes.txt](https://github.com/eclipse/openj9/files/2178061/openjdk_openj9_extra_classes.txt).

There are three sections in the above report:
1) **Section 1:** 139 classes used by OpenJ9 JDK9 but not used by OpenJDK JDK9.
2) **Section 2:** 57 classes used by OpenJDK JDK9 but not used by OpenJ9 JDK9.
3) **Section 3:** 415 common classes between OpenJ9 JDK9 and OpenJDK JDK9.

**Individual verbose logs:**
- [OpenJ9 JDK9 Verbose Log](https://github.com/eclipse/openj9/files/2178067/openj9_jdk9_vc.log)
- [OpenJDK JDK9 Verbose Log](https://github.com/eclipse/openj9/files/2178069/openjdk_jdk9_vc.log)

**Comment by babsingh** [comment] 2018-07-10 00:46
> can you still reproduce the GC issue on your machine when omitting the -Xmx option? If so could you gather a verbose:gc log and a javacore for a good and bad run so I can compare them?

With `-Xmx4g`:
1. [javacore_gc_good.txt](https://github.com/eclipse/openj9/files/2178448/javacore_gc_good.txt)
2. [verbose_gc_good.txt](https://github.com/eclipse/openj9/files/2178449/verbose_gc_good.txt)
3. [time_output_gc_good.txt](https://github.com/eclipse/openj9/files/2178450/time_output_gc_good.txt)

Without `-Xmx4g`:
1. [javacore_gc_bad.txt](https://github.com/eclipse/openj9/files/2178452/javacore_gc_bad.txt)
2. [verbose_gc_bad.txt](https://github.com/eclipse/openj9/files/2178453/verbose_gc_bad.txt)
3. [time_output_gc_bad.txt](https://github.com/eclipse/openj9/files/2178454/time_output_gc_bad.txt)

fyi - @charliegracie 

The only noticeable difference is in  **maxHeapSize**:
- Without `-Xmx4g`: `<attribute name="maxHeapSize" value="0xf4da0000" />` **[3917.6 MB]**
- With `-Xmx4g`: `<attribute name="maxHeapSize" value="0x100000000" />` **[4096 MB]**

**Comment by charliegracie** [comment] 2018-07-10 14:46
@babsingh on the machine where this is reproducible can you try with `-Xnocompressedrefs` to see if you see the same variation?  We have some ideas about what may be causing the fluctuation but it would only happen in a compressed references JVM.

**Comment by keithc-ca** [comment] 2018-07-10 21:29
The extra execution time in `default_pageSize_reserve_memory` when `-Xmx` is *not* specified seems similar to that discussed in https://github.com/eclipse/openj9/issues/967.

**Comment by babsingh** [comment] 2018-07-10 22:28
@charliegracie the issue is not seen with `-Xnocompressedrefs`. with `-Xnocompressedrefs`, OpenJ9 always performs well. the issue only happens with `-Xcompressedrefs`.

**Comment by pshipton** [comment] 2018-07-10 22:43
fyi, I'm thinking this explains our 7 hour linux 390 sanity builds #2329

**Comment by dmitripivkine** [comment] 2018-07-16 20:51
There is consistent delta time between Java 9 and Java 8 even after elimination of different size heap allocation effect:

[scratch.txt](https://github.com/eclipse/openj9/files/2199272/scratch.txt)

**Comment by babsingh** [comment] 2018-07-16 21:05
in the absence of the heap allocation effect, delta between OpenJ9 JDK8 and JDK9 is comparable to the delta between OpenJDK JDK8 and JDK9. this is reflected in my `time` results posted earlier.

the delta between OpenJ9 JDK8 and JDK9 exists because more classes are loaded in OpenJ9 JDK9+. the delta can be reduced if the number of classes loaded is reduced at startup (`java -version`).

**Comment by babsingh** [comment] 2018-07-17 16:02
> re: Difference between OpenJ9 JDK9 and OpenJDK JDK9 verbose log: [openjdk_openj9_extra_classes.txt](https://github.com/eclipse/openj9/files/2178061/openjdk_openj9_extra_classes.txt).

The earlier difference in `verbose:class` was noticed because OpenJDK JDK9 (9.0.4-adoptopenjdk+11) and OpenJ9 JDK9 (jdk-9.0.4+12) were using different JCLs. With the same JCLs, the difference in classes loaded should reduce.

Since the delta between OpenJ9 JDK8 and JDK9 is comparable to the delta between OpenJDK JDK8 and JDK9, we can close this issue once the heap allocation effect is resolved.

**Comment by pshipton** [comment] 2018-07-25 14:17
One of the problems is fixed by https://github.com/eclipse/omr/pull/2743, however there is still a problem outstanding. The QUICK memory allocation algorithm can fail to find a suitable candidate but then it falls back to a brute force search which also won't find any suitable memory and can be very slow.

**Comment by irinarada** [comment] 2018-07-25 16:46
do we have a PR to follow and an ETA for the outstanding problem... wondering if it's @keithc-ca as well.

**Comment by pshipton** [comment] 2018-07-25 17:02
Yes, Keith is working on a fix. There is no PR created yet.

**Comment by keithc-ca** [comment] 2018-07-25 17:18
Peter was a little too quick (or I was a little too slow): I created https://github.com/eclipse/omr/pull/2796.

**Comment by irinarada** [comment] 2018-07-25 17:41
Thanks @pshipton and @keithc-ca . Will that fix issues 1888, 2388, and 2329?

**Comment by pshipton** [comment] 2018-07-25 18:00
> Will that fix issues 1888, 2388, and 2329?

That is the idea.

**Comment by pshipton** [comment] 2018-07-25 23:18
The remaining problem appears resolved by https://github.com/eclipse/omr/pull/2796.
See #2329 for details.

**Comment by keithc-ca** [comment] 2018-07-31 12:57
Closing via https://github.com/eclipse/omr/pull/2796.

**Closed by keithc-ca** 2018-07-31 12:57 UTC
Labels: comp:vm, perf
