### ISSUE TITLE
JDK8 JIT Server j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/MarkingSchemeRootMarker.cpp:53

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9424] opened 2020-05-01 00:02 UTC
Failure link
------------

From an internal build `Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/64`:
```
23:44:28  openjdk version "1.8.0_252-internal"
23:44:28  OpenJDK Runtime Environment (build 1.8.0_252-internal-jenkins_2020_04_29_21_16-b00)
23:44:28  Eclipse OpenJ9 VM (build ibm_sdk-6ba300b5c3, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200429_65 (JIT enabled, AOT enabled)
23:44:28  OpenJ9   - 6ba300b5c3
23:44:28  OMR      - 325acab89
23:44:28  JCL      - 127abdd0797 based on jdk8u252-b09)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
MLT 20:54:10.385 -   103 ArbitraryJava[net.adoptopenjdk.test.autosimd.AutoSIMDTestLong testSums]  Weighting=1 
MLT 20:54:10.385 -   104 JUnit[net.adoptopenjdk.test.math.MathAPITest]  Weighting=1 
MLT 20:54:10.427 - Starting thread. Suite=0 thread=0
MLT 20:54:10.429 - Starting thread. Suite=0 thread=1
MLT 20:54:10.433 - Starting thread. Suite=0 thread=2
MLT stderr 00000000003C2200: J9_INVALID_OBJECT in thread load-0
MLT stderr 00000000003C2200:	O-Slot=00007FCE0E1056D8
MLT stderr 00000000003C2200:	O-Slot value=FFFFFFFFFFFFFFFF
MLT stderr 00000000003C2200:	PC=00007FCE0F4BDDF4
MLT stderr 00000000003C2200:	framesWalked=1
MLT stderr 00000000003C2200:	arg0EA=00000000003CD398
MLT stderr 00000000003C2200:	walkSP=00000000003CD2D0
MLT stderr 00000000003C2200:	literals=0000000000000000
MLT stderr 00000000003C2200:	jitInfo=00007FCE0E23FAF8
MLT stderr 00000000003C2200:	method=00000000003BF4C8 (.
MLT stderr ) (JIT)
MLT stderr 00000000003C2200:	stack=00000000003C68D0-00000000003CD8E0
MLT stderr 03:54:16.463 0x112600    j9mm.479    *   ** ASSERTION FAILED ** at ../../gc_glue_java/MarkingSchemeRootMarker.cpp:53: ((MM_StackSlotValidator(MM_StackSlotValidator::NOT_ON_HEAP, object, stackLocation, walkState).validate(_env)))
MLT stderr JVMDUMP039I Processing dump event "traceassert", detail "" at 2020/04/29 20:54:16 - please wait.
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/core.20200429.205416.7121.0001.dmp' in response to an event
MLT stderr JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.7158.
MLT stderr 
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/core.20200429.205416.7121.0001.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/javacore.20200429.205416.7121.0002.txt' in response to an event
STF 20:54:19.203 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/javacore.20200429.205416.7121.0002.txt
STF 20:54:19.204 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/core.20200429.205416.7121.0001.dmp
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/javacore.20200429.205416.7121.0002.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/core.20200429.205416.7121.0001.dmp
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/javacore.20200429.205416.7121.0002.txt
MLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/Snap.20200429.205416.7121.0003.trc' in response to an event
STF 20:54:19.305 - Found dump at: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/Snap.20200429.205416.7121.0003.trc
MLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/Snap.20200429.205416.7121.0003.trc
MLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/results/Snap.20200429.205416.7121.0003.trc
MLT stderr JVMDUMP013I Processed dump event "traceassert", detail "".
STF 20:54:19.406 - **FAILED** Process MLT ended with exit code (255) and not the expected exit code/s (0)
STF 20:54:19.406 - Monitoring Report Summary:
STF 20:54:19.406 -   o Process MLT has crashed unexpectedly
STF 20:54:19.407 - Killing processes: MLT
STF 20:54:19.407 -   o Process MLT is not running
**FAILED** at step 1 (Run math load test). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/../TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/execute.pl line 94.
STF 20:54:19.479 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 20:54:19.479 - 
STF 20:54:19.479 - ====================   T E A R D O W N   ====================
STF 20:54:19.479 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/openjdk-tests/TKG/../TKG/test_output_15882184398387/MathLoadTest_all_ConcurrentScavenge_0/20200429-205407-MathLoadTest/tearDown.pl
STF 20:54:19.537 - TEARDOWN stage completed
STF 20:54:19.540 - 
STF 20:54:19.540 - =====================   R E S U L T S   =====================
STF 20:54:19.540 - Stage results:
STF 20:54:19.540 -   setUp:     pass
STF 20:54:19.540 -   execute:  *fail*
STF 20:54:19.540 -   teardown:  pass
STF 20:54:19.540 - 
STF 20:54:19.540 - Overall result: **FAILED**

MathLoadTest_all_ConcurrentScavenge_0_FAILED
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-64_linux&TARGET=MathLoadTest_all_ConcurrentScavenge_0

**Comment by pshipton** [comment] 2020-05-01 00:47
@mpirvu

**Comment by dmitripivkine** [comment] 2020-05-01 13:27
most likely duplicate of https://github.com/eclipse/openj9/issues/9123

**Comment by EmanElsaban** [comment] 2020-11-06 14:52
Ran 100 tests on grinder, everything passed. https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11878/

From console output:
java -version:
```
19:54:30  set TEST_ROOT to /home/jenkins/workspace/Grinder/openjdk-tests/TKG/..
19:54:30  set JDK_VERSION to 8
19:54:30  set JDK_IMPL to openj9
19:54:30  set JVM_VERSION to openjdk8-openj9
19:54:30  set JCL_VERSION to latest
19:54:30  set JAVA_HOME to /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image
19:54:30  set SPEC to linux_x86-64_cmprssptrs
19:54:30  Running MathLoadTest_all_ConcurrentScavenge_0 ...
19:54:30  There are 1 test targets in MathLoadTest_all_ConcurrentScavenge_0
19:54:30  "/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java" -version
19:54:30  openjdk version "1.8.0_272"
19:54:30  OpenJDK Runtime Environment (build 1.8.0_272-202011041720-b10)
19:54:30  Eclipse OpenJ9 VM (build master-a236ce7ee, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20201104_839 (JIT enabled, AOT enabled)
19:54:30  OpenJ9   - a236ce7ee
19:54:30  OMR      - e5f5e201d
19:54:30  JCL      - 289ae443 based on jdk8u272-b10)
```
FYI: @mpirvu

**Comment by EmanElsaban** [comment] 2020-11-11 16:11
I checked the past nightly builds in (https://hyc-runtimes-jenkins.swg-devops.com/view/Nightly/job/Test_openjdk8_j9_extended.system_x86-64_linux_jit_Nightly/) for ```mathLoadTest_all_ConcurrentScavenge_0``` test failure going back to build 204 (9-10-2020), since this is the latest build I had access to. In all these build, the test passed.
Also, this issue seems to be a duplicate of issue #9123, which has been solved according to this comment (https://github.com/eclipse/openj9/issues/9123#issuecomment-699100519) @mpirvu

**Comment by mpirvu** [comment] 2020-11-12 14:26
Closing based on the comment (duplicate of an issue that has been fixed and 100 tests passing)

**Closed by mpirvu** 2020-11-12 14:26 UTC
Labels: comp:jitserver, test failure
