### ISSUE TITLE
JDK 15 : StringJoinerTest.java OutOfMemoryError: UTF16 String size is 2147483639, should be less than 1073741823

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10149] opened 2020-07-10 18:16 UTC
Failure link
------------

From an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/8`:
```
22:31:31  openjdk version "15-internal" 2020-09-15
22:31:31  OpenJDK Runtime Environment (build 15-internal+0-adhoc.jenkins.BuildJDK15ppc64lelinuxNightly)
22:31:31  Eclipse OpenJ9 VM (build master-d8cd2a6fb35, JRE 15 Linux ppc64le-64-Bit Compressed References 20200707_19 (JIT enabled, AOT enabled)
22:31:31  OpenJ9   - d8cd2a6fb35
22:31:31  OMR      - 281f29d31a6
22:31:31  JCL      - 8e963ae8ecc based on jdk-15+30)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
23:01:37  --------------------------------------------------
23:03:54  TEST: java/util/StringJoiner/StringJoinerTest.java
23:03:54  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image
23:03:54
23:03:54  rerun:
23:03:54  cd /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/scratch/2 && \
23:03:54  DISPLAY=:1 \
23:03:54  HOME=/home/jenkins \
23:03:54  LANG=en_US.UTF-8 \
23:03:54  PATH=/bin:/usr/bin:/usr/sbin \
23:03:54      /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/bin/javac \
23:03:54          -J-ea \
23:03:54          -J-esa \
23:03:54          -J-Xmx512m \
23:03:54          -J-Xdump:system:none \
23:03:54          -J-Xdump:heap:none \
23:03:54          -J-Xdump:system:events=gpf+abort+traceassert+corruptcache \
23:03:54          -J-Dtest.vm.opts='-ea -esa -Xmx512m -Xdump:system:none -Xdump:heap:none -Xdump:system:events=gpf+abort+traceassert+corruptcache' \
23:03:54          -J-Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m -J-Xdump:system:none -J-Xdump:heap:none -J-Xdump:system:events=gpf+abort+traceassert+corruptcache' \
23:03:54          -J-Dtest.compiler.opts= \
23:03:54          -J-Dtest.java.opts= \
23:03:54          -J-Dtest.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
23:03:54          -J-Dcompile.jdk=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image \
23:03:54          -J-Dtest.timeout.factor=8.0 \
23:03:54          -J-Dtest.root=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk \
23:03:54          -J-Dtest.name=java/util/StringJoiner/StringJoinerTest.java \
23:03:54          -J-Dtest.file=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner/StringJoinerTest.java \
23:03:54          -J-Dtest.src=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner \
23:03:54          -J-Dtest.src.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner \
23:03:54          -J-Dtest.classes=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/classes/1/java/util/StringJoiner/StringJoinerTest.d \
23:03:54          -J-Dtest.class.path=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/classes/1/java/util/StringJoiner/StringJoinerTest.d \
23:03:54          -J-Dtest.class.path.prefix=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/classes/1/java/util/StringJoiner/StringJoinerTest.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner \
23:03:54          -J-Dtest.modules=java.base/jdk.internal.util \
23:03:54          --add-modules java.base \
23:03:54          --add-exports java.base/jdk.internal.util=ALL-UNNAMED \
23:03:54          -d /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/classes/1/java/util/StringJoiner/StringJoinerTest.d \
23:03:54          -sourcepath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner \
23:03:54          -classpath /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/TKG/test_output_15941758497297/jdk_util_j9_0/work/classes/1/java/util/StringJoiner/StringJoinerTest.d:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/testng.jar:/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/jvmtest/openjdk/jtreg/lib/jcommander.jar /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdk-tests/openjdk/openjdk-jdk/test/jdk/java/util/StringJoiner/StringJoinerTest.java
23:03:54  
23:03:54  test StringJoinerTest.OOM1(): failure
23:03:54  java.lang.OutOfMemoryError: UTF16 String size is 2147483639, should be less than 1073741823
23:03:54  	at java.base/java.lang.StringUTF16.newBytesFor(StringUTF16.java:50)
23:03:54  	at java.base/java.lang.String.repeat(String.java:3967)
23:03:54  	at StringJoinerTest.OOM1(StringJoinerTest.java:330)
23:03:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:03:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
23:03:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:03:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:03:54  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
23:03:54  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
23:03:54  	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
23:03:54  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
23:03:54  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
23:03:54  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
23:03:54  	at org.testng.TestRunner.privateRun(TestRunner.java:773)
23:03:54  	at org.testng.TestRunner.run(TestRunner.java:623)
23:03:54  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
23:03:54  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
23:03:54  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
23:03:54  	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
23:03:54  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
23:03:54  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
23:03:54  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
23:03:54  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
23:03:54  	at org.testng.TestNG.run(TestNG.java:1018)
23:03:54  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
23:03:54  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
23:03:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
23:03:54  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
23:03:54  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
23:03:54  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
23:03:54  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
23:03:54  	at java.base/java.lang.Thread.run(Thread.java:851)
```
To rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=ppc64le_linux&TARGET=jdk_util_j9_0

**Comment by tajila** [comment] 2020-09-08 13:05
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment] 2020-09-08 14:58
Looking into it.

**Comment by mikezhang1234567890** [comment] 2020-09-08 20:23
Looks like the issue is when `StringUTF16.newBytesFor` throws an error when the length is greater than a max length:
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/6df70d08c8f14fc19a8f7235090fa2091039940f/src/java.base/share/classes/java/lang/StringUTF16.java#L49-L52

However, the max length refers to byte pairs and is defined to be `Integer.MAX_VALUE >> 1`. In our `String.repeat` code, we simply pass the byte length, which throws the exception. Will probably need to change everywhere we call `StringUTF16.newBytesFor` to use half of the byte length.

**Comment by tajila** [comment] 2020-09-09 13:40
String::repeat() calls `lengthInternal()` which should be doing the correct thing for noncompressed Strings. 

```
	int lengthInternal() {
		if (enableCompression) {
			return value.length >> coder;
		} else {
			return value.length >> 1;
		}
	}
```

**Comment by tajila** [comment] 2020-09-09 14:10
Looking at the test, it seems they are doing something like `String MAX_STRING = "*".repeat(Integer.MAX_VALUE - 8)`, if we don't have string compression enabled the max we can do is `Integer.MAX_VALUE >> 1`. 

@fjeremic does that match your expectations?

**Comment by fjeremic** [comment] 2020-09-09 16:26
> @fjeremic does that match your expectations?

That's correct. HotSpot will fail in the same way if you disable String compression.

**Comment by tajila** [comment] 2020-09-09 17:28
@llxia Is it possible to hard code an option for this test?

**Comment by llxia** [comment] 2020-09-09 17:41
We can add the option in variation
https://github.com/AdoptOpenJDK/openjdk-tests/blob/53bed4dc3ff14a713d0a93c1779b767e935f184c/openjdk/playlist.xml#L659

**Comment by tajila** [comment] 2020-09-09 17:45
@mikezhang1234567890 can you please try updating the playlist as Lan mentioned and verify that we pass the test

**Comment by tajila** [comment] 2020-09-09 17:46
we will need to do the same for https://github.com/eclipse/openj9/issues/10316

**Comment by DanHeidinga** [comment] 2020-09-09 18:06
Given this is a test case relying on string compression to be enabled by default, I don't think its stop ship.  I'm going to move it out of the 0.22.0 release.  We can modify the test options in the main branch and pick it up for 0.23.

**Comment by mikezhang1234567890** [comment] 2020-09-09 19:58
Updating the playlist there makes `XX:+CompactStrings` apply to all tests in java_util, and that causes some other tests to fail when they involve creating a `Scanner` with locales.

**Comment by mikezhang1234567890** [comment] 2020-09-09 20:50
Is it possible to add the option to the individual tests themselves? @llxia

**Comment by llxia** [comment] 2020-09-10 15:07
We can separate `StringJoinerTest` out and run it with the specific option in playlist.xml. The rest `jdk_util_j9` runs without this test.

@sophia-guo do you have any other suggestions for this?

**Comment by mikezhang1234567890** [comment] 2020-09-10 15:20
It looks like we can also edit the `@run` annotation in `StringJoinerTest.java` and `MergeTest.java` to add the option directly (https://github.com/ibmruntimes/openj9-openjdk-jdk15/blob/ad829e12c8f52c9774b8b8705fe438cb7a9d58cb/test/jdk/java/util/StringJoiner/StringJoinerTest.java#L29).

**Comment by llxia** [comment] 2020-09-10 16:06
I did notice this [action tag](https://openjdk.java.net/jtreg/tag-spec.html). However, this means that we need to directly update the test material. If we do this, we will have to update/maintain the future test material from openjdk.

**Comment by tajila** [comment] 2020-09-11 14:48
@mikezhang1234567890 
> Updating the playlist there makes XX:+CompactStrings apply to all tests in java_util, and that causes some other tests to fail when they involve creating a Scanner with locales.

Can you post a link to one of the tests that failed?

> I did notice this action tag. However, this means that we need to directly update the test material. If we do this, we will have to update/maintain the future test material from openjdk.

Avoiding this is my preference.

> We can separate StringJoinerTest out and run it with the specific option in playlist.xml. The rest jdk_util_j9 runs without this test.

@llxia with this approach do we still need to update/maintain the future test material from openjdk?

**Comment by mikezhang1234567890** [comment] 2020-09-11 15:12
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/10086/ has failing tests, but is internal to IBM. A stack trace from one of the failing tests is:
```
16:31:25  java.lang.AssertionError
16:31:25  	at java.base/java.lang.StringUTF16.indexOfLatin1Unsafe(StringUTF16.java:444)
16:31:25  	at java.base/java.lang.StringUTF16.indexOfLatin1(StringUTF16.java:437)
16:31:25  	at java.base/java.lang.String.indexOf(String.java:2074)
16:31:25  	at java.base/java.lang.String.indexOf(String.java:2042)
16:31:25  	at java.base/java.lang.String.indexOf(String.java:2016)
16:31:25  	at java.base/java.util.regex.Pattern.quote(Pattern.java:1353)
16:31:25  	at java.base/java.util.Scanner.useLocale(Scanner.java:1298)
16:31:25  	at java.base/java.util.Scanner.<init>(Scanner.java:543)
16:31:25  	at java.base/java.util.Scanner.<init>(Scanner.java:554)
16:31:25  	at java.base/java.util.Scanner.<init>(Scanner.java:679)
16:31:25  	at java.base/java.util.Scanner.<init>(Scanner.java:657)
16:31:25  	at ScannerStreamTest.makeFileScanner(ScannerStreamTest.java:109)
16:31:25  	at ScannerStreamTest.findAllFileTest(ScannerStreamTest.java:125)
```

**Comment by llxia** [comment] 2020-09-11 16:59
> >We can separate StringJoinerTest out and run it with the specific option in playlist.xml. The rest jdk_util_j9 runs without this test.
>
>@llxia with this approach do we still need to update/maintain the future test material from openjdk?

No, this change is at the playlist.xml level, so we do not need to update/maintain the future test material. I would prefer this solution atm.

**Comment by tajila** [comment] 2020-09-14 13:49
> No, this change is at the playlist.xml level, so we do not need to update/maintain the future test material. I would prefer this solution atm.

This seems like the best solution. @mikezhang1234567890 can you please make this change.

**Comment by tajila** [comment] 2020-09-15 15:14
Update: @andrew-m-leonard is going to add the `-XX:+CompactStrings` to the upstream repo for StringJoinerTest.java and MergeTest.java

**Comment by pshipton** [comment] 2020-09-16 01:35
Should be resolved by the following, will close after verifying this.
https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/26
https://github.com/ibmruntimes/openj9-openjdk-jdk15/pull/27
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/233

**Comment by pshipton** [comment] 2020-09-16 13:16
These failures didn't occur in the jdk15 release testing last night, closing as resolved.
https://ci.eclipse.org/openj9/job/Pipeline-Release-0.22.0-Build15/4/

**Closed by pshipton** 2020-09-16 13:16 UTC
Labels: comp:vm, jdk15, test failure
