### ISSUE TITLE
JDK8 HCRLateAttachWorkload_0_FAILED : NPE at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:67)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10504] opened 2020-09-01 15:21 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/471/tapResults/
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
00:23:31  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system&PLATFORM=x86-64_linux_xl&TARGET=HCRLateAttachWorkload_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
LT  The agent's agentmain method was called.
LT  To re-run this agent with these options, pass this option to the agent on the command line: "percentage=50,threads=10,threadsTimeout=60000,duration=240,seed=1531850877123421942"
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  Exception seen while transforming String.
LT  stderr Exception in thread "Attachment 40585" java.lang.reflect.InvocationTargetException
LT  stderr 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
LT  stderr 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
LT  stderr 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
LT  stderr 	at java.lang.reflect.Method.invoke(Method.java:498)
LT  stderr 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:401)
LT  stderr 	at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:426)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.loadAgentLibraryImpl(Native Method)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.loadAgentLibrary(Attachment.java:346)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.parseLoadAgent(Attachment.java:324)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.doCommand(Attachment.java:190)
LT  stderr 	at openj9.internal.tools.attach.target.Attachment.run(Attachment.java:150)
LT  stderr Caused by: java.lang.Error: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.AgentLogger.throwErrors(AgentLogger.java:52)
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringModifierAgent.agentmain(StringModifierAgent.java:131)
LT  stderr 	... 11 more
LT  stderr Caused by: java.lang.Error: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:84)
LT  stderr 	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
LT  stderr 	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:443)
LT  stderr 	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
LT  stderr 	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
LT  stderr 	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
LT  stderr 	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:304)
LT  stderr 	at java.lang.invoke.MethodHandle.invokeBsm(MethodHandle.java:900)
LT  stderr 	at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:951)
LT  stderr 	at org.apache.logging.log4j.core.util.BasicAuthorizationProvider.<init>(BasicAuthorizationProvider.java:49)
LT  stderr 	at org.apache.logging.log4j.core.config.ConfigurationFactory.authorizationProvider(ConfigurationFactory.java:216)
LT  stderr 	at org.apache.logging.log4j.core.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:189)
LT  stderr 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:687)
LT  stderr 	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)
LT  stderr 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
LT  stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
LT  stderr 	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
LT  stderr 	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
LT  stderr 	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:669)
LT  stderr 	at net.adoptopenjdk.loadTest.LoadTest.<clinit>(LoadTest.java:46)
LT  stderr Caused by: java.lang.NullPointerException
LT  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.StringTransformer.transform(StringTransformer.java:67)
LT  stderr 	... 19 more
LT  stderr Agent failed to start!
LT  stderr JVMJ9TI064E Agent initialization function Agent_OnAttach failed for library instrument, return code 102
AG  stderr Exception in thread "main" com.sun.tools.attach.AgentInitializationException: ATTACH_ERR AgentInitializationException102
AG  stderr 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.parseResponse(OpenJ9VirtualMachine.java:372)
AG  stderr 	at com.ibm.tools.attach.attacher.OpenJ9VirtualMachine.loadAgent(OpenJ9VirtualMachine.java:265)
AG  stderr 	at net.adoptopenjdk.test.hcrAgent.agent.Attacher.main(Attacher.java:75)
STF 00:05:48.134 - **FAILED** Process AG  ended with exit code (1) and not the expected exit code/s (0)
STF 00:05:48.134 - Monitoring Report Summary:
STF 00:05:48.135 -   o Process AG  ended with exit code (1) and not the expected exit code/s (0)
STF 00:05:48.135 -   o Process LT  is still running
STF 00:05:48.135 - Killing processes: AG  LT 
STF 00:05:48.136 -   o Process AG  is not running
STF 00:05:59.138 -   o Process LT  killed
LT  00:05:49.421 - Load test parameters
LT  00:05:49.433 -   Time limited         = true
LT  00:05:49.433 -   Time limit         = 5m
LT  00:05:49.433 -   abortIfOutOfMemory   = true
LT  00:05:49.433 -   reportFailureLimit   = 1
LT  00:05:49.433 -   abortAtFailureLimit  = 10
LT  00:05:49.434 -   maxTotalLogFileSpace = 209715200
LT  00:05:49.434 -   maxSingleLogSize     = 8388608
LT  00:05:49.434 - Parameters for suite 0
LT  00:05:49.434 -   Suite name     = mini-mix
LT  00:05:49.434 -   Number threads = 3
LT  00:05:49.435 -   Supplied seed  = -1
LT  00:05:49.435 -   Inventory file = /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/results/1.LT.inventory/openjdk.test.load/config/inventories/util/util.xml
LT  00:05:49.435 -   Exclude file   = /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/results/1.LT.inventory/openjdk.test.load/config/inventories/util/util_exclude.xml
LT  00:05:49.437 -   Number tests   = -1
LT  00:05:49.437 -   Repeat count   = 1
LT  00:05:49.438 -   Thinking time  = 0ms..0ms
LT  00:05:49.438 -   Selection mode = sequential
LT  00:05:49.713 - Parsing inventory file. Root=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/results/1.LT.inventory File=openjdk.test.load/config/inventories/util/util.xml
LT  00:05:49.750 - Reading exclusion file. File=openjdk.test.load/config/inventories/util/util_exclude.xml
LT  00:05:49.750 - Parsing inventory file. Root=/home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/results/1.LT.inventory File=openjdk.test.load/config/inventories/util/util_exclude.xml
LT  00:05:49.755 - Final test list:
LT  00:05:49.755 -   0 ArbitraryJava[net.adoptopenjdk.test.util.calendars.CalendarTest run]  Weighting=1 
LT  00:05:49.755 -   1 ArbitraryJava[net.adoptopenjdk.test.util.hashmap.Hog run]  Weighting=1 
LT  00:05:49.755 -   2 JUnit[net.adoptopenjdk.test.util.lilac.TestArrays]  Weighting=1 
LT  00:05:49.756 -   4 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapAPITest]  Weighting=1 
LT  00:05:49.756 -   5 JUnit[net.adoptopenjdk.test.util.treemap.TreeMapTest]  Weighting=1 
LT  00:05:49.820 - Starting thread. Suite=0 thread=0
LT  00:05:49.823 - Starting thread. Suite=0 thread=1
LT  00:05:49.823 - Starting thread. Suite=0 thread=2
**FAILED** at step 3 (Wait for Agent to complete, followed by the MiniMix test seconds later.). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/execute.pl line 149.
STF 00:05:59.261 - **FAILED** execute script failed. Expected return value=0 Actual=1
STF 00:05:59.261 - 
STF 00:05:59.261 - ====================   T E A R D O W N   ====================
STF 00:05:59.261 - Running teardown: perl /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../TKG/test_output_15989287384205/HCRLateAttachWorkload_0/20200901-000541-HCRLateAttachWorkload/tearDown.pl
STF 00:05:59.385 - TEARDOWN stage completed
STF 00:05:59.392 - 
STF 00:05:59.392 - =====================   R E S U L T S   =====================
STF 00:05:59.393 - Stage results:
STF 00:05:59.393 -   setUp:     pass
STF 00:05:59.393 -   execute:  *fail*
STF 00:05:59.393 -   teardown:  pass
STF 00:05:59.393 - 
STF 00:05:59.393 - Overall result: **FAILED**

HCRLateAttachWorkload_0_FAILED
```

**Comment by pshipton** [comment] 2020-09-16 17:02
Setting as a blocker since it's a regression. Guessing it's JIT due to the intermittent nature.

First occurrence I can find, although the problem is intermittent.
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_x86-64_mac_Nightly/470

It occurs across platforms, https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_extended.system_ppc64le_linux_Nightly/489/

Changes from previous build.
https://github.com/eclipse/openj9/compare/d5de935...dd041d8
https://github.com/eclipse/omr/compare/97452b4...23ce7a1
OpenJDK didn't change.

**Comment by pshipton** [comment] 2020-09-16 17:03
@andrewcraik can someone look at this pls.

**Comment by andrewcraik** [comment] 2020-09-16 17:12
@rpshukla can you have a look and see what you can make of this? A binary search of the changes may be the best way to find the problem. Only opt related change seems to be in GRA...

**Comment by rpshukla** [comment] 2020-09-16 21:27
Ran an xlinux grinder and 2/10 runs failed:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3932/

Also ran a similar grinder with `-Xjit:disableGRA` and 6/10 runs failed:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3933/

Since the failure occurs even when GRA is disabled, it doesn't appear to be a problem with GRA.

**Comment by rpshukla** [comment] 2020-09-21 15:39
I'm currently running through a binary search of the openj9 and omr commits. I ran 10 runs in grinder with the following shas and they all passed:

```
OpenJ9   - f88d5fee203
OMR      - b52454a206a
JCL      - 182efd27241 based on jdk8u265-b01)
```

**Comment by rpshukla** [comment] 2020-09-21 18:37
Saw the failure in a grinder with the following shas:
```
OpenJ9   - f88d5fee203
OMR      - 53e26890171
JCL      - 182efd27241 based on jdk8u265-b01)
```

This suggests that the error was introduced here: https://github.com/eclipse/omr/compare/b52454a206a...53e26890171

**Comment by andrewcraik** [comment] 2020-09-22 13:23
The only real opt change in this range is the GRA change from @0xdaryl could you do a run without that change and confirm if it is involved?

**Comment by rpshukla** [comment] 2020-09-22 19:50
I reverted the GRA change and still saw the failure.

**Comment by rpshukla** [comment] 2020-09-22 19:54
I did 10 runs with this memcpy change reverted and saw no failures:
https://github.com/eclipse/omr/pull/5492/commits/53e268901718ba11f03440febaeb64fed8ddf1c1

**Comment by rpshukla** [comment] 2020-09-24 16:46
I was able to reproduce this issue on an internal grinder with `-Xint`. It appears this is not a jit problem.

**Comment by pshipton** [comment] 2020-09-24 18:23
This is a system test, are you sure the JVM getting NPE is running with -Xint?

@tajila fyi the previous comment. Note this is set as a blocker for the release, and occurs frequently in the builds.

**Comment by andrewcraik** [comment] 2020-09-24 18:41
I would note the lack of JIT changes in the windows pointed out by @rpshukla - there isn't much different in the JIT so there is some reason to think it isn't the compiler. I suggested trying a compiler swap to see if we can recreate in the bad build with the good JIT to make sure the defect has the right home.

**Comment by rpshukla** [comment] 2020-09-24 21:27
> I suggested trying a compiler swap to see if we can recreate in the bad build with the good JIT to make sure the defect has the right home.

I'll try a compiler swap.

**Comment by pshipton** [comment] 2020-09-24 21:40
The problem is intermittent, we don't know the build previous to the first failing build is the "good" build, so https://github.com/eclipse/openj9/issues/10504#issuecomment-693537179 may not be the right set of changes to look at.

**Comment by pshipton** [comment] 2020-09-24 21:42
https://github.com/eclipse/openj9/issues/10504#issuecomment-696198224 is based on only 10 runs, which may not be enough to prove it's a "good" build.

**Comment by rpshukla** [comment] 2020-09-24 21:57
> [#10504 (comment)](https://github.com/eclipse/openj9/issues/10504#issuecomment-696198224) is based on only 10 runs, which may not be enough to prove it's a "good" build.

I agree.


> The problem is intermittent, we don't know the build previous to the first failing build is the "good" build, so [#10504 (comment)](https://github.com/eclipse/openj9/issues/10504#issuecomment-693537179) may not be the right set of changes to look at.

I was going to make "good" and "bad" builds using these changes but I guess we don't know if the previous build is "good".

@pshipton is there a reason that the JVM in a system test wouldn't pick up the -Xint flag?

**Comment by pshipton** [comment] 2020-09-25 03:13
> is there a reason that the JVM in a system test wouldn't pick up the -Xint flag?

If multiple JVMs are started, the -Xint flag may not be passed into the JVM which gets the NPE. Another way to check this is to set an -Xdump option to create a javacore file on NPE, and (a) see if the javacore is created (b) if there is a javacore created, confirm that -Xint is set.

**Comment by rpshukla** [comment] 2020-09-25 21:11
I did some runs with the options `-Xint -Xdump:java:events=throw+systhrow,filter=java/lang/NullPointerException#net/adoptopenjdk/test/hcrAgent/agent/StringTransformer.transform*,request=exclusive+preempt` and saw the same NPE in `StringTransformer.transform`.

I looked at one of the failed runs. There were six javacores created. I don't see the usual `UserArgs` section but they do say `JIT disabled`:

```
NULL           ------------------------------------------------------------------------
0SECTION       ENVINFO subcomponent dump routine
NULL           =================================
1CIJAVAVERSION JRE 1.8.0 Linux amd64-64 (build 1.8.0_272-202009241719-b08)
1CIVMVERSION   20200924_789
1CIJ9VMVERSION 5189fd7a1
1CIJITVERSION  unavailable (JIT disabled)
1CIOMRVERSION  b5e3f1002_CMPRSS
1CIJCLVERSION  a4527bef based on jdk8u272-b08
1CIJITMODES    unavailable (JIT disabled)
1CIRUNNINGAS   Running as 1INTERNAL      In-flight data encountered. Output may be missing or incomplete.
0SECTION       NATIVEMEMINFO subcomponent dump routine
NULL           =================================
```

**Comment by pshipton** [comment] 2020-09-25 21:55
@tajila Since it occurs with -Xint, please find someone to take a look.

**Comment by pshipton** [comment] 2020-09-25 22:04
Before they disappear, here is the previous nightly build data.

#1016 - Nightly Aug 28, 2020 9:30 PMOpenJ9: dd041d8 OMR: 23ce7a1 OpenJDK8: 182efd2 - openj9-openjdk-jdk8
#1015 - Nightly Aug 27, 2020 9:30 PMOpenJ9: d5de935 OMR: 97452b4 OpenJDK8: 182efd2 - openj9-openjdk-jdk8
#1014 - Nightly Aug 26, 2020 9:30 PMOpenJ9: ab44069OMR: 97452b4OpenJDK8: 182efd2 - openj9-openjdk-jdk8

The first one is the first failing build from https://github.com/eclipse/openj9/issues/10504#issuecomment-693537179

1016:
```
================================================
timestamp: 20200828-225022
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-tests.git
sha:
2b06a53c276f3efdf764df392533c48671586cf0
================================================
timestamp: 20200828-225022
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/TKG.git
sha:
d2ba40d72ede4562e97b8baff0fcffa1a2a1feb6
================================================
timestamp: 20200828-225324
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/openj9
git repo: 
  Fetch URL: https://github.com/eclipse/openj9.git
sha:
dd041d8eb295ac0128e0119f55cfe69602223dd5
================================================
timestamp: 20200828-225447
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../system/stf
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/stf.git
sha:
b5efc99cfcb40dda66858e4208e7d1e5198045c5
================================================
timestamp: 20200828-225455
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../system/openjdk-systemtest
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-systemtest.git
sha:
fed7a6a856d7f4e63fe5bd7052391f05e3ca539c
================================================
timestamp: 20200828-225457
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_x86-64_linux_xl_Nightly/openjdk-tests/TKG/../system/openj9-systemtest
git repo: 
  Fetch URL: https://github.com/eclipse/openj9-systemtest.git
sha:
00eb7d2f0e1bfb35872072edf9db56b53223d8c7
```

1015:
```
================================================
timestamp: 20200827-230713
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-tests.git
sha:
2b06a53c276f3efdf764df392533c48671586cf0
================================================
timestamp: 20200827-230713
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/TKG.git
sha:
d2ba40d72ede4562e97b8baff0fcffa1a2a1feb6
================================================
timestamp: 20200827-230752
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/openj9
git repo: 
  Fetch URL: https://github.com/eclipse/openj9.git
sha:
d5de935395512281ded4ad0d6c1173aaa01e9393
================================================
timestamp: 20200827-231801
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/stf
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/stf.git
sha:
b5efc99cfcb40dda66858e4208e7d1e5198045c5
================================================
timestamp: 20200827-231803
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/openjdk-systemtest
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-systemtest.git
sha:
fed7a6a856d7f4e63fe5bd7052391f05e3ca539c
================================================
timestamp: 20200827-231804
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/openj9-systemtest
git repo: 
  Fetch URL: https://github.com/eclipse/openj9-systemtest.git
sha:
00eb7d2f0e1bfb35872072edf9db56b53223d8c7
```

1014:
```
================================================
timestamp: 20200826-231554
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-tests.git
sha:
3f23748e11ba8ca94d6d4b83dfeff6eb102446de
================================================
timestamp: 20200826-231554
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/TKG.git
sha:
d2ba40d72ede4562e97b8baff0fcffa1a2a1feb6
================================================
timestamp: 20200826-231630
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/openj9
git repo: 
  Fetch URL: https://github.com/eclipse/openj9.git
sha:
ab44069ea9a7ad451b383d0317ba73e16a66687f
================================================
timestamp: 20200826-232729
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/stf
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/stf.git
sha:
b5efc99cfcb40dda66858e4208e7d1e5198045c5
================================================
timestamp: 20200826-232731
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/openjdk-systemtest
git repo: 
  Fetch URL: https://github.com/AdoptOpenJDK/openjdk-systemtest.git
sha:
fed7a6a856d7f4e63fe5bd7052391f05e3ca539c
================================================
timestamp: 20200826-232732
repo dir: /home/jenkins/workspace/Test_openjdk8_j9_extended.system_ppc64_aix_Nightly/openjdk-tests/TKG/../system/openj9-systemtest
git repo: 
  Fetch URL: https://github.com/eclipse/openj9-systemtest.git
sha:
00eb7d2f0e1bfb35872072edf9db56b53223d8c7
```

**Comment by pshipton** [comment] 2020-09-25 22:09
Confirmed HCRLateAttachWorkload_0 is running in the 1014 build.

**Comment by tajila** [comment] 2020-09-28 12:21
@mikezhang1234567890 Can you please take a look at this

**Comment by mikezhang1234567890** [comment] 2020-09-28 14:40
Will take a look.

**Comment by mikezhang1234567890** [comment] 2020-09-30 22:34
The problem is className being passed to the transformer is `null` here: https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/2d9430d2bfa085d0074d8ce23b22a6d46c5da1ca/openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringTransformer.java#L67

Looks like it's caused by my change at https://github.com/eclipse/openj9/pull/10483. If a class is being defined after the transformer is registered, then the transformer will trigger, with the `className` variable being null. This is in line with Hotspot's behaviour though.

We should add a condition to the test to check make sure either `className` is not null or `classBeingRedefined` is not null so that it only runs the string equality check if there is actually a name.

**Comment by pshipton** [comment] 2020-10-01 00:04
Same failure on Hotspot seen here https://trss.adoptopenjdk.net/output/test?id=5f73ff6211d26031c1bd2924

I assume you will create a PR to fix it.
https://github.com/AdoptOpenJDK/openjdk-systemtest/blob/master/openjdk.test.debugging/src/test.debugging/net/adoptopenjdk/test/hcrAgent/agent/StringTransformer.java#L67

**Comment by mikezhang1234567890** [comment] 2020-10-01 15:16
@pshipton test change is merged

**Comment by pshipton** [comment] 2020-10-01 16:11
Thanks, I'll go ahead and close this. The failure has been happening quite often in the nightly builds, looking forward to not seeing it any more.

**Closed by pshipton** 2020-10-01 16:11 UTC
Labels: test failure
