### ISSUE TITLE
openj9 simply ignores the invalid "-XX:" options without reporting any error/message

### ISSUE THREAD

**Issue by gpadasal** [eclipse/openj9#526] opened 2017-11-07 07:07 UTC
There is no strict checking in openj9 for most of the "-XX:" options specified .
For instance , the GC policy -XX:+UseConcMarkSweepGC when used with openj9 silently ignores the option without reporting any error/message . 
```
# ./jre/bin/java -XX:+UseConcMarkSweepGC -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9-openjdk-jdk9)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170918_000000 (JIT enabled, AOT enabled)
J9VM - ead54ef
JIT  - ead54ef
OMR  - 617de12
OpenJDK  - fdc150a based on jdk-9+181)
```
Use of any random characters in the option is also accepted. 
```
# ./jre/bin/java -XX:+ertxxxxxx -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9-openjdk-jdk9)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170918_000000 (JIT enabled, AOT enabled)
J9VM - ead54ef
JIT  - ead54ef
OMR  - 617de12
OpenJDK  - fdc150a based on jdk-9+181)
```
This creates confusion as the user thinks the option is indeed supported by J9 VM which is not true .
The combination of optthruput policy with UseConcMarkSweepGC is accepted which is not correct although the later option is simply ignored by VM .
```
# ./jre/bin/java -Xgcpolicy:optthruput -XX:+UseConcMarkSweepGC -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc..openj9-openjdk-jdk9)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20170918_000000 (JIT enabled, AOT enabled)
J9VM - ead54ef
JIT  - ead54ef
OMR  - 617de12
OpenJDK  - fdc150a based on jdk-9+181)
```
There should be some way for the VM to detect such invalid options and report the error/message just like open JDK does as shown below.
```
jdk-9.0.1#./bin/java -XX:+UseConcMarkSweep -version
Unrecognized VM option 'UseConcMarkSweep'
Did you mean '(+/-)UseConcMarkSweepGC'? Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
Ideally, the unrecognized options should be reported by default via error/warning message, but if that is not feasible, there should be a way to optionally enable reporting of these errors/warnings. 
This option can be enabled the first few times a user tries to migrate an application from other jvms to openj9 .

**Comment by pshipton** [comment] 2017-11-07 14:20
This enhancement request should not be confused with -XX:+IgnoreUnrecognizedVMOptions, which is disabled by default, and causes unrecognized options like -Xfred to be ignored.

**Comment by DanHeidinga** [comment] 2018-09-21 15:42
This has come up in discussion again.  Closing this as a duplicate of https://github.com/eclipse/openj9/issues/2977

**Closed by DanHeidinga** 2018-09-21 15:42 UTC
Labels: comp:vm, enhancement, userRaised
