### ISSUE TITLE
jdk-17 builds broken: PointerGenerator Invalid option : -r

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#12229] opened 2021-03-17 09:25 UTC
Affects all jdk-17 platforms: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-openj9/261/console
```
09:21:56  Generating DDR pointer and structure class files
09:21:57  Generating DDR pointer class source files
09:21:57  superset directory name : /home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/build/linux-x86_64-server-release/vm/
09:21:57  superset file name : superset.dat
09:21:57  Writing generated classes to /home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/build/linux-x86_64-server-release/support/gensrc/openj9.dtfj/com/ibm/j9ddr/vm29/pointer/generated
09:21:57  Generating DDR structure stub source files
09:21:58  Invalid option : -r
09:21:58  Usage :
09:21:58  
09:21:58  java PointerGenerator -p <package name> -o <output path> -f <path to structure file> [-s <superset file name> -l <legacy mode>]
09:21:58  
09:21:58  <package name>           : the package name for all the generated classes e.g. com.ibm.dtfj.j9.structures
09:21:58  <relative output path>   : where to write out the class files.  Full path to base of package hierarchy e.g. c:\src\
09:21:58  <path to structure file> : full path to the J9 structure file
09:21:58  <superset file name>     : optional file name of the superset to be used for input / output
09:21:58  <legacy mode>            : optional flag set to true or false indicating if legacy DDR is used
09:21:58  gmake[4]: *** [/home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/build/linux-x86_64-server-release/support/ddr/gensrc-structures.done] Error 1
09:21:58  gmake[4]: *** Waiting for unfinished jobs....
09:21:58  /home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/closed/DDR.gmk:124: recipe for target '/home/adoptopenjdk/workspace/build-scripts/jobs/jdk/jdk-linux-x64-openj9/workspace/build/src/build/linux-x86_64-server-release/support/ddr/gensrc-structures.done' failed
09:21:58  Unhandled structure type: big_int_unionPointer->i128 __int128
09:21:59  Unhandled structure type: _IO_FILEPointer->_lock _IO_lock_t*
09:21:59  Unhandled structure type: J9CudaLinkerStatePointer->createOptions $JitOptions
09:22:00  Processing complete
09:22:00  gmake[3]: *** [all] Error 2
09:22:00  Gensrc.gmk:25: recipe for target 'all' failed
09:22:00  gmake[2]: *** [openj9.dtfj-gensrc-src] Error 1
```

**Comment by keithc-ca** [comment] 2021-03-17 12:47
The problem is that the module `openj9.dtfj` in the bootjdk includes an old version of `StructureStubGenerator` that does not include eclipse/openj9#12210. The old version is being used rather than the one just compiled by `DDR.gmk`, hence the unsupported option error. I have a solution and expect to open pull requests soon.

**Comment by keithc-ca** [comment] 2021-04-07 20:22
Fixed via the three pull requests referenced above: closing.

**Closed by keithc-ca** 2021-04-07 20:22 UTC
Labels: blocker, comp:build, jdk11, jdk16, jdk17
