### ISSUE TITLE
jdk14: JlmRemote testcases failing, unsure why...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [eclipse/openj9#10156] opened 2020-07-14 09:07 UTC
https://ci.adoptopenjdk.net/job/Test_openjdk14_j9_sanity.system_x86-64_linux_xl/145/consoleFull
test-scaleway-ubuntu1604-x64-1

01:43:17  FAILED test targets:
01:43:17  	TestJlmRemoteClassNoAuth_0
01:43:17  	TestJlmRemoteMemoryAuth_0
01:43:17  	TestJlmRemoteMemoryNoAuth_0
01:43:17  	TestIBMJlmRemoteClassAuth_0
01:43:17  	TestIBMJlmRemoteClassNoAuth_0
01:43:17  	TestIBMJlmRemoteMemoryAuth_0
01:43:17  	TestIBMJlmRemoteMemoryNoAuth_0
```
00:06:20  STF 23:06:16.340 - Heartbeat: Process LT1 is still running
00:06:39  CL1 j> 2020/07/13 23:06:35.635 Monitored VM not ready at Jul 13, 2020, 11:06:35 PM (attempt 6).
00:06:39  CL1 j> 2020/07/13 23:06:35.635 Wait 10 secs and trying again...
00:06:39  CL1 j> 2020/07/13 23:06:35.636 Trying to connect using JMXConnectorFactory
00:09:02  CL1 j> 2020/07/13 23:08:53.065 Monitored VM not ready at Jul 13, 2020, 11:08:53 PM (attempt 7).
00:09:02  CL1 j> 2020/07/13 23:08:53.066 Wait 10 secs and trying again...
00:09:02  CL1 j> 2020/07/13 23:08:53.066 Trying to connect using JMXConnectorFactory
00:11:25  CL1 j> 2020/07/13 23:11:10.504 Monitored VM not ready at Jul 13, 2020, 11:11:10 PM (attempt 8).
00:11:25  CL1 j> 2020/07/13 23:11:10.505 Wait 10 secs and trying again...
00:11:25  CL1 j> 2020/07/13 23:11:10.505 Trying to connect using JMXConnectorFactory
00:11:25  STF 23:11:16.003 - Heartbeat: Process CL1 is still running
00:13:34  CL1 j> 2020/07/13 23:13:27.824 Monitored VM not ready at Jul 13, 2020, 11:13:27 PM (attempt 9).
00:13:34  CL1 j> 2020/07/13 23:13:27.826 Wait 10 secs and trying again...
00:13:34  CL1 j> 2020/07/13 23:13:27.827 Trying to connect using JMXConnectorFactory
00:15:57  CL1 j> 2020/07/13 23:15:45.225 Monitored VM not ready at Jul 13, 2020, 11:15:45 PM (attempt 10).
00:15:57  CL1 j> 2020/07/13 23:15:45.225 Wait 10 secs and trying again...
00:15:57  CL1 j> 2020/07/13 23:15:45.226 Trying to connect using JMXConnectorFactory
00:16:17  STF 23:16:16.269 - Heartbeat: Process LT1 is still running
00:16:30  STF 23:16:28.367 - **FAILED** Process LT1 has ended unexpectedly
```
No clear reason why

**Comment by pshipton** [comment] 2020-07-14 13:24
Some kind of network problem on the machine?
1.LT1.stdout
```
22:13:47.264 - Completed 100.0%. Number of tests started=260268 (+3437)
...
22:13:54.985 - Thread completed. Suite=0 thread=21
22:13:55.055 - Thread completed. Suite=0 thread=12
22:13:55.121 - Test stopped due to reaching runtime limit
22:13:55.122 - Load test completed
22:13:55.122 -   Ran     : 260268
22:13:55.123 -   Passed  : 260268
22:13:55.123 -   Failed  : 0
22:13:55.124 -   Result  : PASSED
```

**Comment by adamfarley** [comment] 2020-07-20 14:50
I think this could be a duplicate of https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/246

**Comment by lumpfish** [comment] 2020-10-15 12:46
This is different to the failures seen in AdoptOpenJDK/openjdk-systemtest#246 (and similar issues) which was fixed by AdoptOpenJDK/openjdk-systemtest#246.

As @pshipton suggests above there appears to be some issue with the test machine preventing the test processes connecting.

https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1627 has been raised at AdoptOpenJDK.

**Comment by pshipton** [comment] 2020-10-15 13:00
Since we have the issue raised at Adopt, I'll close this.

**Closed by pshipton** 2020-10-15 13:00 UTC
Labels: test failure
