### ISSUE TITLE
Iprofiling data of a callsite contains a class loaded by classloader different than the one that loaded the callsite/caller class

### ISSUE THREAD

**Issue by liqunl** [eclipse/openj9#2001] opened 2018-05-28 14:46 UTC
This problem is found in a core dump which is generated by a crash in the JIT when it was trying to compile a method using bad iprofiling data.

I have a change in the JIT  https://github.com/eclipse/openj9/pull/1980 to avoid the crash. However, the real problem is in the iprofiler. 

I suspect ROM class sharing is causing the problem.

During the crash, we have
`A.foo -> A.bar`, and `B.bar` overrides `A.bar`

Class files of A and B are loaded again by a different classloader, resulting 
`A'.foo -> A'.bar`, `B'.bar` overrides `A'.bar`

`A` and `A'` share the same ROM class, same for `B` and `B'`

The iprofiling data for callsite `A.bar` in `A.foo` contains class `B'`. We don't expect that since `A`, `B` and `A'`, `B'` are in different class hierarchies (their superclasses/interfaces don't share the same ROM class).

Unfortunately, we don't have a test case. I can provide more info from the core dump if you need.

**Comment by liqunl** [comment] 2018-05-28 14:48
FYI @DanHeidinga

**Comment by DanHeidinga** [comment] 2018-05-28 15:01
@liqunl To a large degree, this is SharedClasses working as designed.

If a classloader is sharedclasses enabled, the VM will check the cache for an appropriate ROMClass.  Being a ROMClass, this is the ROM version of the classfile.  All the hierarchy info apart from this classes superclass and directly implemented interfaces, lives in either other ROMClasses or the J9Class.

We don't track whether a ROMClass has been used by this VM already.  This is a deliberate decision to save footprint as there are applications that reuse the same classes in different loaders, as you're seeing here.

When the VM is doing iprofiling, it writes the PC from the ROMClass into the buffer.  We can write more data to disambiguate this case but it will likely slow down startup as more time will be spent processing buffers with less data or increase footprint due to using larger buffers.

This is a constraint the processing of the profiler buffers will need to take into account.  What can you do in that code to address this?

**Comment by andrewcraik** [comment] 2018-05-28 15:12
As mentioned above the is a Pull Request in #1980 which will add the appropriate safety checks. The subtlety of this case is what was surprising. If this is working as intended when shared classes are enabled then we can close this item as working as designed and the checks in #1980 will be sufficient for safety and correctness.

**Comment by liqunl** [comment] 2018-05-28 15:30
Closed the issue as working as designed.

**Closed** 2018-05-28 15:29 UTC
