### ISSUE TITLE
Is -Xjit:perfTool (OpenJ9) == -XX:+PreserveFramePointer (Hotspot)?

### ISSUE THREAD

**Issue by babsingh** [eclipse/openj9#3497] opened 2018-10-31 18:26 UTC
**-XX:(+/-)PreserveFramePointer:**
> The x86-specific PreserveFramePointer flag selects between using the RBP register as a general purpose register (-XX:-PreserveFramePointer) and using the RBP register to hold the frame pointer of the currently executing method (-XX:+PreserveFramePointer). If the frame pointer is available, external profiling tools (e.g., Linux perf) can construct more accurate stack traces. 

Are JVM options `-Xjit:perfTool` in OpenJ9 and `-XX:+PreserveFramePointer` in Hotspot similar?

**Comment by babsingh** [comment] 2018-10-31 18:31
fyi - @zl-wang @mstoodle @DanHeidinga

**Comment by fjeremic** [comment] 2018-10-31 18:53
I don't think so. @ymanton recently answered this on Slack:
https://openj9.slack.com/archives/C8312LCV9/p1540929332005700

**Comment by DanHeidinga** [comment] 2018-10-31 19:10
As @fjeremic mentioned, the answer is:
```
It's not documented, but it causes the JIT to produce a `/tmp/perf-<pid>.map` file for JIT compiled code, which the perf command uses to associate samples to symbols. It's not documented in the perf man page either, but there are plenty of pages on the web that describe that stuff
```
(Reproduced here as I don't know how long slack links are good for)

@mstoodle / @ymanton had looked at the the equivalent of `-XX:+PreserveFramePointer` a number of years back but I'm not sure what became of that work.

**Comment by ymanton** [comment] 2018-10-31 20:37
> @mstoodle / @ymanton had looked at the the equivalent of -XX:+PreserveFramePointer a number of years back but I'm not sure what became of that work.

I came to the conclusion that it would be very difficult (on all platforms, not just x86). Preserving the frame pointer is a minor x86 problem, our bigger problems (on all platforms) are that:

We have two separate stacks (Java and native) and execution can weave between the two. Any general tool that wants to walk the stack to show you an accurate backtrace or to construct a call graph profile is going to be thwarted by that.

We also probably don't produce ABI-compliant stack frames so even if they were all on one stack these kinds of tools wouldn't know how to walk them.

On top of that profiling tools sample threads at arbitrary points, where as our stacks are really only safely walkable at GC points.

**Comment by DanHeidinga** [comment] 2018-11-02 19:46
@ymanton Does the code to preserve the frame pointer on x86 still exist?  I would expect keeping the framepointer and saving it in the appropriate stackslot would be sufficient for perf to walk the jitted frames.

Providing only the jitted stack frames would give a great deal more info than is currently available and would cover the most interesting frames for users.

**Comment by dsouzai** [comment] 2018-11-02 20:38
At least on x86, part of the problem was using rbp for the vmThread reg. I think @lmaisons looked into this issue at one point.

**Comment by zl-wang** [comment] 2018-11-05 13:43
perf doesn't know anything about OpenJ9/OMR frame shapes at all.  It cannot weave between java and native frames.  it possibly can deal with single-stack mixed-mode VM.  On the other hand, is there a stack-walking JVM TI service available for perf? jprof SCS (Sampled Call Stack) seemed able to do it.

**Comment by DanHeidinga** [comment] 2018-11-05 14:02
> It cannot weave between java and native frames.

I don't think it matters.  The user is likely to care about the currently executing frames and as much of the stack as we can give them.  Something is better than the nothing we currently display.

For x86 at least, a valid instruction pointer along with being able to chain through basepointer should be sufficient to get a good sample of the stack.

If we limit it initially to x86, is this something doable in a reasonable amount of time?

**Comment by andrewcraik** [comment] 2018-11-05 14:22
I don't think it is something that can be done in a reasonable amount of time for all the reasons listed by @ymanton - register conventions are not in place to match what perf expects, GC maps are not reliable outside of GC points, ABI compliance of frames is unknown and likely to need more work, handling stack swap and C code on the java stack for fast helpers is not trivial. From the point of view of supporting perf the best we have managed in the past is to get perf method instruction range information for pc mapping - we have not made the frames walkable by perf itself and the private linkage and other associated engineer mean it is not likely we ever will without major re-engineering.

**Comment by andrewcraik** [comment] 2018-11-05 21:43
I think the original question raised by this issue has been answered - namely the two options are not similar and are not aliasable. Since the discussion seems to have resolved I am going to close this issue. If we want to continue discussing changes to the internal linkage etc to try and support perf that is probably better done in an issue dedicated to that task since we are diverging from the original question here.

**Closed by andrewcraik** 2018-11-05 21:43 UTC

**Comment by kgibm** [comment] 2021-12-15 19:00
By the way, another dimension to this -- investigating performance issues in the JVM itself -- is that it seems J9 is compiled without `-fno-omit-frame-pointer` and thus `perf` can't walk back native stacks using the base frame pointer (besides not being able to walk back JITted stacks). HotSpot doesn't seem to suffer from this. The workaround for J9 is to use `perf record --call-graph dwarf [...]`.

**Comment by babsingh** [comment] 2021-12-15 19:15
@kgibm This blog covers using Linux perf while resolving symbols for JIT compiled methods: https://blog.openj9.org/2019/07/18/inspecting-openj9-performance-with-perf-on-linux-jit-compiled-methods/.

**Comment by kgibm** [comment] 2021-12-21 18:51
@babsingh Yes, that is useful for JIT compiled methods but my point was that the JVM itself seems to be compiled with frame pointer omission, so call stack walking using the frame pointer doesn't work if the stack happens to be in the JVM itself.

This can be demonstrated on both Semeru Runtime Open Edition 17 and IBM Java 8 as shown below. This demonstration searches for JIT Compilation thread stacks to demonstrate a known native stack but this can also happen on application threads (as observed in a recent customer situation where bytecode interpretation was driving JIT compilation request queuing but it was hard to tell from `perf` because we could only see a the top stack frame of `omrthread_spinlock_acquire`). The below also demonstrates that using `perf record --call-graph dwarf` avoids this issue, but this is an obscure thing to know.

Note: Running `perf` with `podman` requires `sysctl -w kernel.perf_event_paranoid=-1` in addition to `--privileged`, so first run `podman system connection default podman-machine-default-root` to switch the `podman` connection to `root`-based.

In the following output, we `grep` for the top 2 stack frames. The issue is reproduced when the second stack frame is blank or `[unknown]`; otherwise, if the second stack frame is meaningful, then the issue is not reproduced.

Reproduced with Semeru Runtime Open Edition 17 (notice that the default `perf record` with `--call-graph fp` can't walk past `omrthread_spinlock_acquire` and an `OMR` method, for examples; whereas, with `--call-graph dwarf`, it can):

```
$ podman run --privileged -it --rm ibm-semeru-runtimes:open-17-jdk sh -c 'sysctl -w kernel.perf_event_paranoid=-1 && apt-get update && DEBIAN_FRONTEND=noninteractive TZ=${TZ:-UTC} apt-get -y install python python3 build-essential make gcc g++ flex bison libelf-dev libdw-dev libslang2-dev libssl-dev libiberty-dev libunwind-dev libbfd-dev libcap-dev libnuma-dev libperl-dev python-dev libzstd-dev git && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git && cd linux/tools/perf && make && echo "public class main { public static void main(String... args) { for (int i = 0; i < 50000; i++) { byte[] b = new byte[(int)(Math.random()*10)*1048576]; } } }" > main.java && javac main.java && echo "= Running test =" && echo "== --call-graph fp (default) ==" && ./perf record -F 99 -a -g -- java main && ./perf script | grep -A 2 -e "JIT Compilation" && echo "== --call-graph dwarf ==" && ./perf record --call-graph dwarf -F 99 -a -g -- java main && ./perf script | grep -A 2 -e "JIT Compilation"'
[...]
== --call-graph fp (default) ==
[ perf record: Woken up 8 times to write data ]
[ perf record: Captured and wrote 2.475 MB perf.data (6072 samples) ]
JIT Compilation  6752 [002]   374.833112:   10101010 cpu-clock:pppH: 
	           11fc8 omrthread_spinlock_acquire+0xa8 (/opt/java/openjdk/lib/default/libj9thr29.so)

--
JIT Compilation  6752 [002]   374.903633:   10101010 cpu-clock:pppH: 
	           11fc8 omrthread_spinlock_acquire+0xa8 (/opt/java/openjdk/lib/default/libj9thr29.so)

--
JIT Compilation  6752 [002]   374.913915:   10101010 cpu-clock:pppH: 
	          569223 OMR::Node::getByteCodeIndex+0x3 (/opt/java/openjdk/lib/default/libj9jit29.so)
	    7f92af104a40 [unknown] ([unknown])
[...]
== --call-graph dwarf ==
[ perf record: Woken up 60 times to write data ]
[ perf record: Captured and wrote 15.459 MB perf.data (6140 samples) ]
JIT Compilation  6781 [000]   395.395643:   10101010 cpu-clock:pppH: 
	           11fc8 omrthread_spinlock_acquire+0xa8 (/opt/java/openjdk/lib/default/libj9thr29.so)
	            4d9c monitor_enter_three_tier.constprop.17+0x8c (/opt/java/openjdk/lib/default/libj9thr29.so)
--
JIT Compilation  6780 [002]   395.396107:   10101010 cpu-clock:pppH: 
	           11fc8 omrthread_spinlock_acquire+0xa8 (/opt/java/openjdk/lib/default/libj9thr29.so)
	            4d9c monitor_enter_three_tier.constprop.17+0x8c (/opt/java/openjdk/lib/default/libj9thr29.so)
--
JIT Compilation  6780 [002]   395.416554:   10101010 cpu-clock:pppH: 
	          8ff7a0 OMR::X86::TreeEvaluator::integerRegLoadEvaluator+0x0 (/opt/java/openjdk/lib/default/libj9jit29.so)
	          50680e OMR::CodeGenerator::evaluate+0x3e (/opt/java/openjdk/lib/default/libj9jit29.so)
[...]
```

Reproduced with IBM Java 8 (same symptoms as above):

```
$ podman run --privileged -it --rm ibmjava:8-sdk sh -c 'sysctl -w kernel.perf_event_paranoid=-1 && apt-get update && DEBIAN_FRONTEND=noninteractive TZ=${TZ:-UTC} apt-get -y install python python3 build-essential make gcc g++ flex bison libelf-dev libdw-dev libslang2-dev libssl-dev libiberty-dev libunwind-dev libbfd-dev libcap-dev libnuma-dev libperl-dev python-dev libzstd-dev git && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git && cd linux/tools/perf && make && echo "public class main { public static void main(String... args) { for (int i = 0; i < 50000; i++) { byte[] b = new byte[(int)(Math.random()*10)*1048576]; } } }" > main.java && javac main.java && echo "= Running test =" && echo "== --call-graph fp (default) ==" && ./perf record -F 99 -a -g -- java main && ./perf script | grep -A 2 -e "JIT Compilation" && echo "== --call-graph dwarf ==" && ./perf record --call-graph dwarf -F 99 -a -g -- java main && ./perf script | grep -A 2 -e "JIT Compilation"'
[...]
= Running test =
== --call-graph fp (default) ==
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0.968 MB perf.data (8104 samples) ]
JIT Compilation  6961 [001]  1060.098589:   10101010 cpu-clock:pppH: 
	           11fc5 omrthread_spinlock_acquire+0x115 (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9thr29.so)

--
JIT Compilation  6961 [001]  1060.179671:   10101010 cpu-clock:pppH: 
	          5f388e OMR::OptimizationManager::OptimizationManager+0x5e (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9jit29.so)
	               1 [unknown] ([unknown])
[...]
== --call-graph dwarf ==
[ perf record: Woken up 71 times to write data ]
[ perf record: Captured and wrote 17.969 MB perf.data (8080 samples) ]
JIT Compilation  6987 [001]  1085.685643:   10101010 cpu-clock:pppH: 
	           11f58 omrthread_spinlock_acquire+0xa8 (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9thr29.so)
	            4d2c monitor_enter_three_tier.constprop.17+0x8c (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9thr29.so)
--
JIT Compilation  6987 [001]  1085.826916:   10101010 cpu-clock:pppH: 
	          4486b0 OMR::Node::getExtendedChild+0x0 (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9jit29.so)
	          64c9cc OMR::TransformUtil::recursivelySetNodeVisitCount+0xec (/opt/ibm/java/jre/lib/amd64/compressedrefs/libj9jit29.so)
[...]
```

The blog post you linked to further links to this blog post: https://blog.openj9.org/2018/10/18/inspecting-openj9-performance-with-perf-on-linux/

That post supposes that the JVM was recompiled without frame pointer ommission:

> ```
> export VMDEBUG=-fno-omit-frame-pointer
> export VMLINK=-fno-omit-frame-pointer
> export CFLAGS=-fno-omit-frame-pointer
> export CXXFLAGS=-fno-omit-frame-pointer
> ```

However, later, perf is run with `--call-graph dwarf`:

> ```
> perf record --call-graph dwarf -- <JAVA_COMMAND>
> ```

These are contradictory claims; if `-fno-omit-frame-pointer` had worked, then `--call-graph dwarf` wouldn't have been needed as the default `--call-graph fp` should have worked.

**Comment by babsingh** [comment] 2022-01-05 15:40
@kgibm Thanks for the clarification. 

> These are contradictory claims; if -fno-omit-frame-pointer had worked, then --call-graph dwarf wouldn't have been needed as the default --call-graph fp should have worked.

The OpenJ9 build framework has evolved since the **Inspecting-Openj9-Performance-with-Perf-on-Linux** blog was written. I will revisit the blog, and update it accordingly.
