### ISSUE TITLE
Windows Print throws ArrayIndexOutOfBoundsException intermittently with JIT

### ISSUE THREAD

**Issue by toshiona** [eclipse/openj9#7748] opened 2019-11-12 13:00 UTC
Java -version output
--------------------
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.17.0, JRE 11 Windows Server 2016 amd64-64-Bit Compressed References 20191016_357 (JIT enabled, AOT enabled)
OpenJ9   - 77c1cf708
OMR      - 20db4fbc
JCL      - 2a7af5674b based on jdk-11.0.5+10)

Summary of problem
------------------
During Windows Printing, ArrayIndexOutOfBoundsException was thrown intermittently.
The problem didn't occur with JIT off. (-Xint)
The problem didn't occur with Hotspot.

Diagnostic files
----------------
Uploaded the sample code and "-Xjit:verbose" log.

[vlogfile.20191112.213104.5184.txt](https://github.com/eclipse/openj9/files/3836198/vlogfile.20191112.213104.5184.txt)
[TextureTest.java.txt](https://github.com/eclipse/openj9/files/3836201/TextureTest.java.txt)

Recreate steps
----------------
1. Compile the attached TextureTest.java
2. Launch the sample. 
3. Click the mouse on the frame, then Print dialog will appear.
4. Select XPS or PDF printer and set file output.
5. Sometime AIOOBE was thrown.
In my environment, it occurred about 10%.
Just as the result of trial, "-Xcheck:jit" option increased frequency to 100%. (I don't know the reason.)
>java -Xcheck:jni:nonfatal -Xjit:verbose,vlog=vlogfile TextureTest

Additional Information
----------------
I tried to print arguments value by injecting System.out.println.
Then, I found an argument was changed before and after method calling.
For example, TexturePaintContext.getRaster() had "(int)Y=4" just before calling setRaster();
But, TexturePaintContext.setRaster() recorded "y=-1717986944".
(These values are not solid.)

Environment
----------------
Windows Server 2012, Windows Server 2016, and Windows 10.
At the least, 3 machines could recreate the issue.

Exception
----------------
```
java.lang.ArrayIndexOutOfBoundsException
        at java.desktop/java.awt.TexturePaintContext$Int.setRaster(TexturePaintContext.java:472)
        at java.desktop/java.awt.TexturePaintContext.getRaster(TexturePaintContext.java:225)
        at java.desktop/sun.java2d.pipe.AlphaPaintPipe.renderPathTile(AlphaPaintPipe.java:124)
        at java.desktop/sun.java2d.pipe.SpanShapeRenderer$Composite.renderBox(SpanShapeRenderer.java:60)
        at java.desktop/sun.java2d.pipe.SpanShapeRenderer.renderRect(SpanShapeRenderer.java:165)
        at java.desktop/sun.java2d.pipe.SpanShapeRenderer.fill(SpanShapeRenderer.java:107)
        at java.desktop/sun.java2d.pipe.PixelToShapeConverter.fillRect(PixelToShapeConverter.java:62)
        at java.desktop/sun.java2d.pipe.ValidatePipe.fillRect(ValidatePipe.java:76)
        at java.desktop/sun.java2d.SunGraphics2D.fillRect(SunGraphics2D.java:2424)
        at java.desktop/sun.print.ProxyGraphics2D.fillRect(ProxyGraphics2D.java:475)
        at TextureTest.print(TextureTest.java:57)
        at java.desktop/sun.print.RasterPrinterJob.printPage(RasterPrinterJob.java:2430)
        at java.desktop/sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1654)
        at java.desktop/sun.print.RasterPrinterJob.print(RasterPrinterJob.java:1484)
        at TextureTest$MyMouseAdapter.mouseClicked(TextureTest.java:42)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
        at java.desktop/java.awt.Component.processEvent(Component.java:6397)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Window.processEvent(Window.java:2049)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:704)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by pshipton** [comment] 2019-11-12 16:48
@andrewcraik can you please take a look.

**Comment by andrewcraik** [comment] 2019-11-26 15:44
@Charlmzz could you verify if this still happens with the latest OpenJ9 and OMR? If so can you please try to find a failing method and opt so we can investigate further?

**Comment by Charlmzz** [comment] 2019-11-27 19:27
> Select XPS or PDF printer and set file output

@toshiona Could you please clarify what does `set file output` mean here?

>Just as the result of trial, "-Xcheck:jit" option increased frequency to 100%

Also, by saying `"-Xcheck:jit"`, did you mean the `-Xcheck:jni:nonfatal` option you mentioned below?

**Comment by toshiona** [comment] 2019-11-28 12:54
@Charlmzz Sorry for unclear descriptions.
This problem could be recreated by creating a file, like "C:\temp\a.xps", instead of real printing papers.
Yes. "-Xcheck:jni:nofatal" is better I think.

**Comment by andrewcraik** [comment] 2020-01-04 07:15
@Charlmzz & @cathyzhyi any updates on this one since it is targeted to 0.18 atm

**Comment by cathyzhyi** [comment] 2020-01-06 16:16
> @Charlmzz & @cathyzhyi any updates on this one since it is targeted to 0.18 atm

Charlene has collected the logs from a passing run and a failing run. I will take a look today.

**Comment by DanHeidinga** [comment] 2020-01-08 17:10
Moving this out of 0.18 as it's too late in the release cycle

**Comment by andrewcraik** [comment] 2020-02-05 13:41
@cathyzhyi where did this get to?

**Comment by cathyzhyi** [comment] 2020-02-05 15:30
> @cathyzhyi where did this get to?

We've collected some logs and need to take a look but got distracted.

**Comment by DanHeidinga** [comment] 2020-02-25 19:28
@cathyzhyi What's the current status on this?

**Comment by cathyzhyi** [comment] 2020-02-25 20:51
> @cathyzhyi What's the current status on this?

Working on a fix. Will paste the PR here soon.

**Comment by cathyzhyi** [comment] 2020-02-25 21:34
https://github.com/eclipse/omr/pull/4866

**Comment by cathyzhyi** [comment] 2020-02-28 17:27
I am able to reproduce this problem with a microtest case: [Test copy.java.txt](https://github.com/eclipse/openj9/files/4268225/Test.copy.java.txt)
expected output is `a = 5, a0 = 6, x = 0, y = 0` and the one we get is `a = 5, a0 = 0, x = 0, y = 0` I am uploading the log and testcase here to document what I found before we go down to the road fixing the problem. [fail_log.txt](https://github.com/eclipse/omr/files/4268144/fail_log.txt)

The argument `esi` for call at `[0x7f938055df50] call Test.foo(IIII)I`  contains the wrong value. 
The spill at `0x7f938060b110 mov  rsi, qword ptr [rsp+0x38]`  is the spill causing the wrong value.
The first fill in the mainlain for that same virtual register GPR_0051 is `0x7f9380611500 mov  qword ptr [rsp+0x58], rax` and following `Outlined Label L0057`: 
```
0x7f9380610dc0  mov  rax, qword ptr [rsp+0x58]
....
0x7f9380610110 mov  qword ptr [rsp+0x38], rax
```

RA is going backwards, so we created the spill `0x7f938060b110 mov  rsi, qword ptr [rsp+0x38]` first and freed it in `0x7f9380610110]  mov  qword ptr [rsp+0x38], rax` in OOL. Then inside, OOL created another spill `0x7f9380610dc0  mov  rax, qword ptr [rsp+0x58]` and freed this one in `0x7f9380611500  mov  qword ptr [rsp+0x58], rax` in the mainline.  As a result, in program order, in mainline code the first freeSpill `0x7f9380611500 mov  qword ptr [rsp+0x58], rax` doesn't match the last spill `0x7f938060b110 mov  rsi, qword ptr [rsp+0x38]`

**Comment by pshipton** [comment] 2020-03-04 16:26
Moving forward since I don't see any fix in hand and it's becoming too late to update the 0.19 release. Note the branch for the 0.20 release occurs on March 8.

**Comment by pshipton** [comment] 2020-03-18 21:09
@cathyzhyi is there any update on this?

**Comment by cathyzhyi** [comment] 2020-03-24 01:31
> @cathyzhyi is there any update on this?

It should be fixed very soon. The PR is ready to be merged.

**Comment by pshipton** [comment] 2020-03-30 15:11
We're past Milestone 2 for the 0.20.0 release, moving this forward to the next release.
If a low risk fix does become available in the next couple of weeks, please raise it for consideration.

**Closed** 2020-03-31 20:47 UTC
Labels: comp:jit, userRaised

**Comment by pshipton** [comment] 2020-04-03 17:40
The OMR fix for this problem promoted yesterday and has gone through the nightly builds. @cathyzhyi  @0xdaryl what is the risk of the change, is it something we should consider for the 0.20.0 release?

**Comment by cathyzhyi** [comment] 2020-04-06 14:36
> The OMR fix for this problem promoted yesterday and has gone through the nightly builds. @cathyzhyi @0xdaryl what is the risk of the change, is it something we should consider for the 0.20.0 release?

@pshipton  Risk should be low. I can port it to 0.20.0 release.

**Comment by cathyzhyi** [comment] 2020-04-06 14:52
> The OMR fix for this problem promoted yesterday and has gone through the nightly builds. @cathyzhyi @0xdaryl what is the risk of the change, is it something we should consider for the 0.20.0 release?

@pshipton  Hey Peter, I opened a PR for 0.20.0 https://github.com/eclipse/openj9-omr/pull/58
