### ISSUE TITLE
openjdk11_j9_extended.system_s390x_linux_xl MathLoadTest_all_ConcurrentScavenge_0_FAILED Segmentation error vmState=0x00000000

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#8344] opened 2020-01-20 13:30 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/49/tapResults/

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
MLT 07:04:50.834 -   104 JUnit[net.adoptopenjdk.test.math.MathAPITest]  Weighting=1 
MLT 07:04:50.878 - Starting thread. Suite=0 thread=0
MLT 07:04:50.879 - Starting thread. Suite=0 thread=1
MLT 07:04:50.879 - Starting thread. Suite=0 thread=2
MLT stderr Unhandled exception
MLT stderr Type=Segmentation error vmState=0x00000000
MLT stderr J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00808ab8 Signal_Code=00000001
MLT stderr Handler1=000003FF955C17A0 Handler2=000003FF951A8098 InaccessibleAddress=FE0003FF8F030000
MLT stderr gpr0=000003FF90141020 gpr1=FE0003FF1220E108 gpr2=FE0003FF1220E108 gpr3=01FFFFFFFFFFF000
MLT stderr gpr4=FE0003FF8F02F730 gpr5=01FFFFFFFFFFF000 gpr6=000000000000000F gpr7=000003FF9497E468
MLT stderr gpr8=000003FF9497E1A0 gpr9=000003FF9497E1A8 gpr10=000003FF9497E468 gpr11=000003FF1220E100
MLT stderr gpr12=000000000000E619 gpr13=000003FF1220E100 gpr14=000003FF9457B81E gpr15=000003FF9497E100
MLT stderr psw=000003FF96211394 mask=0705200180000000 fpc=0018ff00 bea=000003FF962112B0
MLT stderr fpr0 486c9b2a00000000 (f: 0.000000, d: 7.787324e+40)
MLT stderr fpr1 bda157c5a6866b54 (f: 2793827072.000000, d: -7.886619e-12)
MLT stderr fpr2 486c9b2a9497ddc0 (f: 2492980736.000000, d: 7.787326e+40)
MLT stderr fpr3 bda3760991b555e7 (f: 2444580352.000000, d: -8.849876e-12)
MLT stderr fpr4 3f80000094689340 (f: 2489881344.000000, d: 7.812504e-03)
MLT stderr fpr5 3f317200991ec522 (f: 2568930560.000000, d: 2.661945e-04)
MLT stderr fpr6 b6d7e00090068dd0 (f: 2416348672.000000, d: -1.672801e-44)
MLT stderr fpr7 bdba200000000000 (f: 0.000000, d: -2.376055e-11)
MLT stderr fpr8 0000000000040000 (f: 262144.000000, d: 1.295163e-318)
MLT stderr fpr9 000003ff900b75f0 (f: 2416670208.000000, d: 2.171996e-311)
MLT stderr fpr10 000003ff94940000 (f: 2492727296.000000, d: 2.172033e-311)
MLT stderr fpr11 000003ffc587f26f (f: 3314020864.000000, d: 2.172439e-311)
MLT stderr fpr12 000003ff902164f8 (f: 2418107648.000000, d: 2.171996e-311)
MLT stderr fpr13 000003fffb0fd2c8 (f: 4212118272.000000, d: 2.172883e-311)
MLT stderr fpr14 0000000000000022 (f: 34.000000, d: 1.679823e-322)
MLT stderr fpr15 000003ffc787edf8 (f: 3347574272.000000, d: 2.172456e-311)
MLT stderr Module=/lib/s390x-linux-gnu/libc.so.6
MLT stderr Module_base_address=000003FF96180000
MLT stderr Target=2_90_20200119_50 (Linux 4.4.0-170-generic)
MLT stderr CPU=s390x (4 logical CPUs) (0x1f723a000 RAM)
MLT stderr ----------- Stack Backtrace -----------
MLT stderr (0x000003FF96211394 [libc.so.6+0x91394])
MLT stderr (0x000003FF9457B81E [libj9gc29.so+0x17b81e])
MLT stderr (0x000003FF945B6EE2 [libj9gc29.so+0x1b6ee2])
MLT stderr (0x000003FF94615E06 [libj9gc29.so+0x215e06])
MLT stderr (0x000003FF8FD364D2 [libj9jit29.so+0xa364d2])
MLT stderr ---------------------------------------
MLT stderr JVMDUMP039I Processing dump event "gpf", detail "" at 2020/01/19 07:04:51 - please wait.
MLT stderr JVMDUMP032I JVM requested System dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/core.20200119.070451.4674.0001.dmp' in response to an event
MLT stderr JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/share/apport/apport %p %s %c %d %P" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.4700.
MLT stderr 
MLT stderr JVMDUMP010I System dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/core.20200119.070451.4674.0001.dmp
MLT stderr JVMDUMP032I JVM requested Java dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/javacore.20200119.070451.4674.0002.txt' in response to an event
STF 07:04:52.650 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/javacore.20200119.070451.4674.0002.txt
STF 07:04:52.650 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/core.20200119.070451.4674.0001.dmp
MLT stderr javacore file generated - /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/javacore.20200119.070451.4674.0002.txt
MLT stderr core file generated - /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/core.20200119.070451.4674.0001.dmp
MLT stderr JVMDUMP010I Java dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/javacore.20200119.070451.4674.0002.txt
MLT stderr JVMDUMP032I JVM requested Snap dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/Snap.20200119.070451.4674.0003.trc' in response to an event
STF 07:04:52.913 - Found dump at: /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/Snap.20200119.070451.4674.0003.trc
MLT stderr Snap file generated - /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/Snap.20200119.070451.4674.0003.trc
MLT stderr JVMDUMP010I Snap dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/Snap.20200119.070451.4674.0003.trc
MLT stderr JVMDUMP007I JVM Requesting JIT dump using '/home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/jitdump.20200119.070451.4674.0004.dmp'
MLT stderr JVMDUMP010I JIT dump written to /home/jenkins/workspace/Test_openjdk11_j9_extended.system_s390x_linux_xl_Nightly/openjdk-tests/TKG/test_output_15794174376472/MathLoadTest_all_ConcurrentScavenge_0/20200119-070448-MathLoadTest/results/jitdump.20200119.070451.4674.0004.dmp
MLT stderr JVMDUMP013I Processed dump event "gpf", detail "".
STF 07:04:53.015 - **FAILED** Process MLT ended with exit code (255) and not the expected exit code/s (0)

MathLoadTest_all_ConcurrentScavenge_0_FAILED
```

This is a `MathLoadTest_all_ConcurrentScavenge` test with `libj9gc29.so` in the native stacktrace, any chance related to https://github.com/eclipse/openj9/issues/8020?
fyi @dmitripivkine

**Comment by dmitripivkine** [comment] 2020-01-20 18:15
> This is a `MathLoadTest_all_ConcurrentScavenge` test with `libj9gc29.so` in the native stacktrace, any chance related to #8020?

Yes, this failure looks like a duplicate of #8020

**Comment by dmitripivkine** [comment] 2020-01-20 18:16
Closing as duplicate of #8020

**Closed by dmitripivkine** 2020-01-20 18:16 UTC
Labels: test failure

**Comment by amicic** [comment] 2020-02-05 14:30
I'll keep this closed, but it's actually duplicate of https://github.com/eclipse/openj9/issues/8478 as suggested before. 

The key sympthoms are Concurrent Scavenger and crash with registers:

gpr3=01FFFFFFFFFFF000
gpr5=01FFFFFFFFFFF000 
gpr6=000000000000000F

Likely, could be any workload/test.
