### ISSUE TITLE
OutOfMemoryErrors on AIX with openj9-0.15.1

### ISSUE THREAD

**Issue by JonDGH** [eclipse/openj9#7503] opened 2019-10-18 08:57 UTC
I'm currently trying to get to the bottom of why an application running in WebSphere Liberty Application Server on AIX 7.2 can be started using an IBM VM, but not with an OpenJ9 VM.  I believe the problem is caused by JIT.  The 2 VMs I'm using are:

Java(TM) SE Runtime Environment (build 8.0.5.20 - pap6480sr5fp20-20180802_01(SR5 FP20))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20180731_393394 (JIT enabled, AOT enabled)
OpenJ9   - bd23af8
OMR      - ca1411c
IBM      - 98805ca)
JCL - 20180719_01 based on Oracle jdk8u181-b12

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190717_374 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c64
OMR      - ec782f2
JCL      - f147086 based on jdk8u222-b10)

Using OpenJ9, I'm seeing OutOfMemoryErrors being thrown.  The only way I've found to prevent this is to specify:

-Xnojit

I've also experimented with LDR_CNTRL and -Xlp:codecache:pagesize but with no success.

JIT memory usage in the javacore file doesn't look excessive:

1MEMUSER       JRE: 1,017,715,352 bytes / 23398 allocations
1MEMUSER       |
               :
2MEMUSER       +--JIT: 48,773,848 bytes / 2469 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Code Cache: 18,874,944 bytes / 9 allocations
2MEMUSER       |  |
3MEMUSER       |  +--JIT Data Cache: 6,291,648 bytes / 3 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Other: 23,607,256 bytes / 2457 allocations

**Comment by DanHeidinga** [comment] 2019-10-18 09:16
On an OutOfMemory, OpenJ9 generates some diagnostic files - a javacore, system core, and heapdump - that can be used to investigate the cause of the OOM.

Can you share those files?  We'll have an easier time to resolving this if we can see what was happening at the time it occurred.

**Comment by JonDGH** [comment] 2019-10-25 10:23
Hi Dan,

Thanks for your response.  I finally got the go-ahead to upload these files, they can be found here:

https://github.com/JonDGH/j9-aix-oom

Regards,
Jon

**Comment by pshipton** [comment] 2019-10-25 17:50
You made reference to the javacore, but I don't see it in the collection of diagnostic files.

**Comment by pshipton** [comment] 2019-10-25 17:55
Nm, I see it now.

**Comment by pshipton** [comment] 2019-10-25 18:04
Seems pthread_create() is returning EAGAIN:
EAGAIN | If WLM is running, the limit on the number of threads in the class is reached.
EAGAIN | The limit on the number of threads per process has been reached.

**Comment by JonDGH** [comment] 2019-10-26 10:40
Thanks for this.  I won't have access to the AIX box until Wednesday now.  but iirc the core.dmp file was showing that there were around 180 threads running.  I don't believe that WLM is running or that there are any limits set on the number of threads a process can start,

Anyway, thanks again - I'll do some more digging on Wednesday.

**Comment by JonDGH** [comment] 2019-11-01 17:38
The javacore file shows:

2CIUSERLIMIT   RLIMIT_THREADS                   unlimited            unlimited
2CIUSERLIMIT   RLIMIT_NPROC                     unlimited            unlimited

I've also managed to get the server to start by setting the native thread stack size (-Xmso) down from 256K to 176K (the IBM VM runs the server happily with this set to 1024K).

**Comment by JonDGH** [comment] 2019-11-04 15:30
Even though I can get the application to start, I don't have confidence that it will run successfully.

There looks to be a more general problem with the creation of threads using that J9 VM.  I've written some simple code that starts a number of threads that all just sleep "forever".  Running with:

java -Xmx1024m -Xss256K -Xmso256K StartThreads 1000

This completes successfully for the IBM VM, but the the J9 VM fails around the 300 mark.  The code, class file and traces are in:

https://github.com/JonDGH/j9-aix-oom

Regards,
Jon

**Comment by pshipton** [comment] 2019-11-04 15:43
@zl-wang can you spot anything in the executable header which is different between IBM and OpenJ9 builds that would explain this behavior?

Not sure it matters, but there are two different compiler versions used.
IBM Java uses xlc 12.0.1
OpenJ9 uses xlc 13.1.3

**Comment by zl-wang** [comment] 2019-11-04 18:47
I saw nothing stood out except the fact that OpenJ9 text/data are in the way of java heap allocation (but that is irrelevant to this issue with 1GB heap).

It appeared to me an ulimit issue.  Before I unlimited various limits, I can recreate this on my machine even with -Xint.  After I unlimited them, it ran through without problem:
# openj9_8.0.15/bin/java -Xmx1024m -Xss256K -Xmso256K StartThreads 1000
Started: 1
Started: 2
Started: 3
Started: 4
Started: 5
Started: 6
Started: 7
Started: 8
Started: 9
Started: 10
Started: 11
Started: 12
Started: 13
Started: 14
Started: 15
Started: 16
Started: 17
Started: 18
Started: 19
Started: 20
Started: 21
Started: 22
Started: 23
Started: 24
Started: 25
Started: 26
Started: 27
Started: 28
Started: 29
Started: 30
Started: 31
Started: 32
Started: 33
Started: 34
Started: 35
Started: 36
Started: 37
Started: 38
Started: 39
Started: 40
Started: 41
Started: 42
Started: 43
Started: 44
Started: 45
Started: 46
Started: 47
Started: 48
Started: 49
Started: 50
Started: 51
Started: 52
Started: 53
Started: 54
Started: 55
Started: 56
Started: 57
Started: 58
Started: 59
Started: 60
Started: 61
Started: 62
Started: 63
Started: 64
Started: 65
Started: 66
Started: 67
Started: 68
Started: 69
Started: 70
Started: 71
Started: 72
Started: 73
Started: 74
Started: 75
Started: 76
Started: 77
Started: 78
Started: 79
Started: 80
Started: 81
Started: 82
Started: 83
Started: 84
Started: 85
Started: 86
Started: 87
Started: 88
Started: 89
Started: 90
Started: 91
Started: 92
Started: 93
Started: 94
Started: 95
Started: 96
Started: 97
Started: 98
Started: 99
Started: 100
Started: 101
Started: 102
Started: 103
Started: 104
Started: 105
Started: 106
Started: 107
Started: 108
Started: 109
Started: 110
Started: 111
Started: 112
Started: 113
Started: 114
Started: 115
Started: 116
Started: 117
Started: 118
Started: 119
Started: 120
Started: 121
Started: 122
Started: 123
Started: 124
Started: 125
Started: 126
Started: 127
Started: 128
Started: 129
Started: 130
Started: 131
Started: 132
Started: 133
Started: 134
Started: 135
Started: 136
Started: 137
Started: 138
Started: 139
Started: 140
Started: 141
Started: 142
Started: 143
Started: 144
Started: 145
Started: 146
Started: 147
Started: 148
Started: 149
Started: 150
Started: 151
Started: 152
Started: 153
Started: 154
Started: 155
Started: 156
Started: 157
Started: 158
Started: 159
Started: 160
Started: 161
Started: 162
Started: 163
Started: 164
Started: 165
Started: 166
Started: 167
Started: 168
Started: 169
Started: 170
Started: 171
Started: 172
Started: 173
Started: 174
Started: 175
Started: 176
Started: 177
Started: 178
Started: 179
Started: 180
Started: 181
Started: 182
Started: 183
Started: 184
Started: 185
Started: 186
Started: 187
Started: 188
Started: 189
Started: 190
Started: 191
Started: 192
Started: 193
Started: 194
Started: 195
Started: 196
Started: 197
Started: 198
Started: 199
Started: 200
Started: 201
Started: 202
Started: 203
Started: 204
Started: 205
Started: 206
Started: 207
Started: 208
Started: 209
Started: 210
Started: 211
Started: 212
Started: 213
Started: 214
Started: 215
Started: 216
Started: 217
Started: 218
Started: 219
Started: 220
Started: 221
Started: 222
Started: 223
Started: 224
Started: 225
Started: 226
Started: 227
Started: 228
Started: 229
Started: 230
Started: 231
Started: 232
Started: 233
Started: 234
Started: 235
Started: 236
Started: 237
Started: 238
Started: 239
Started: 240
Started: 241
Started: 242
Started: 243
Started: 244
Started: 245
Started: 246
Started: 247
Started: 248
Started: 249
Started: 250
Started: 251
Started: 252
Started: 253
Started: 254
Started: 255
Started: 256
Started: 257
Started: 258
Started: 259
Started: 260
Started: 261
Started: 262
Started: 263
Started: 264
Started: 265
Started: 266
Started: 267
Started: 268
Started: 269
Started: 270
Started: 271
Started: 272
Started: 273
Started: 274
Started: 275
Started: 276
Started: 277
Started: 278
Started: 279
Started: 280
Started: 281
Started: 282
Started: 283
Started: 284
Started: 285
Started: 286
Started: 287
Started: 288
Started: 289
Started: 290
Started: 291
Started: 292
Started: 293
Started: 294
Started: 295
Started: 296
Started: 297
Started: 298
Started: 299
Started: 300
Started: 301
Started: 302
Started: 303
Started: 304
Started: 305
Started: 306
Started: 307
Started: 308
Started: 309
Started: 310
Started: 311
Started: 312
Started: 313
Started: 314
Started: 315
Started: 316
Started: 317
Started: 318
Started: 319
Started: 320
Started: 321
Started: 322
Started: 323
Started: 324
Started: 325
Started: 326
Started: 327
Started: 328
Started: 329
Started: 330
Started: 331
Started: 332
Started: 333
Started: 334
Started: 335
Started: 336
Started: 337
Started: 338
Started: 339
Started: 340
Started: 341
Started: 342
Started: 343
Started: 344
Started: 345
Started: 346
Started: 347
Started: 348
Started: 349
Started: 350
Started: 351
Started: 352
Started: 353
Started: 354
Started: 355
Started: 356
Started: 357
Started: 358
Started: 359
Started: 360
Started: 361
Started: 362
Started: 363
Started: 364
Started: 365
Started: 366
Started: 367
Started: 368
Started: 369
Started: 370
Started: 371
Started: 372
Started: 373
Started: 374
Started: 375
Started: 376
Started: 377
Started: 378
Started: 379
Started: 380
Started: 381
Started: 382
Started: 383
Started: 384
Started: 385
Started: 386
Started: 387
Started: 388
Started: 389
Started: 390
Started: 391
Started: 392
Started: 393
Started: 394
Started: 395
Started: 396
Started: 397
Started: 398
Started: 399
Started: 400
Started: 401
Started: 402
Started: 403
Started: 404
Started: 405
Started: 406
Started: 407
Started: 408
Started: 409
Started: 410
Started: 411
Started: 412
Started: 413
Started: 414
Started: 415
Started: 416
Started: 417
Started: 418
Started: 419
Started: 420
Started: 421
Started: 422
Started: 423
Started: 424
Started: 425
Started: 426
Started: 427
Started: 428
Started: 429
Started: 430
Started: 431
Started: 432
Started: 433
Started: 434
Started: 435
Started: 436
Started: 437
Started: 438
Started: 439
Started: 440
Started: 441
Started: 442
Started: 443
Started: 444
Started: 445
Started: 446
Started: 447
Started: 448
Started: 449
Started: 450
Started: 451
Started: 452
Started: 453
Started: 454
Started: 455
Started: 456
Started: 457
Started: 458
Started: 459
Started: 460
Started: 461
Started: 462
Started: 463
Started: 464
Started: 465
Started: 466
Started: 467
Started: 468
Started: 469
Started: 470
Started: 471
Started: 472
Started: 473
Started: 474
Started: 475
Started: 476
Started: 477
Started: 478
Started: 479
Started: 480
Started: 481
Started: 482
Started: 483
Started: 484
Started: 485
Started: 486
Started: 487
Started: 488
Started: 489
Started: 490
Started: 491
Started: 492
Started: 493
Started: 494
Started: 495
Started: 496
Started: 497
Started: 498
Started: 499
Started: 500
Started: 501
Started: 502
Started: 503
Started: 504
Started: 505
Started: 506
Started: 507
Started: 508
Started: 509
Started: 510
Started: 511
Started: 512
Started: 513
Started: 514
Started: 515
Started: 516
Started: 517
Started: 518
Started: 519
Started: 520
Started: 521
Started: 522
Started: 523
Started: 524
Started: 525
Started: 526
Started: 527
Started: 528
Started: 529
Started: 530
Started: 531
Started: 532
Started: 533
Started: 534
Started: 535
Started: 536
Started: 537
Started: 538
Started: 539
Started: 540
Started: 541
Started: 542
Started: 543
Started: 544
Started: 545
Started: 546
Started: 547
Started: 548
Started: 549
Started: 550
Started: 551
Started: 552
Started: 553
Started: 554
Started: 555
Started: 556
Started: 557
Started: 558
Started: 559
Started: 560
Started: 561
Started: 562
Started: 563
Started: 564
Started: 565
Started: 566
Started: 567
Started: 568
Started: 569
Started: 570
Started: 571
Started: 572
Started: 573
Started: 574
Started: 575
Started: 576
Started: 577
Started: 578
Started: 579
Started: 580
Started: 581
Started: 582
Started: 583
Started: 584
Started: 585
Started: 586
Started: 587
Started: 588
Started: 589
Started: 590
Started: 591
Started: 592
Started: 593
Started: 594
Started: 595
Started: 596
Started: 597
Started: 598
Started: 599
Started: 600
Started: 601
Started: 602
Started: 603
Started: 604
Started: 605
Started: 606
Started: 607
Started: 608
Started: 609
Started: 610
Started: 611
Started: 612
Started: 613
Started: 614
Started: 615
Started: 616
Started: 617
Started: 618
Started: 619
Started: 620
Started: 621
Started: 622
Started: 623
Started: 624
Started: 625
Started: 626
Started: 627
Started: 628
Started: 629
Started: 630
Started: 631
Started: 632
Started: 633
Started: 634
Started: 635
Started: 636
Started: 637
Started: 638
Started: 639
Started: 640
Started: 641
Started: 642
Started: 643
Started: 644
Started: 645
Started: 646
Started: 647
Started: 648
Started: 649
Started: 650
Started: 651
Started: 652
Started: 653
Started: 654
Started: 655
Started: 656
Started: 657
Started: 658
Started: 659
Started: 660
Started: 661
Started: 662
Started: 663
Started: 664
Started: 665
Started: 666
Started: 667
Started: 668
Started: 669
Started: 670
Started: 671
Started: 672
Started: 673
Started: 674
Started: 675
Started: 676
Started: 677
Started: 678
Started: 679
Started: 680
Started: 681
Started: 682
Started: 683
Started: 684
Started: 685
Started: 686
Started: 687
Started: 688
Started: 689
Started: 690
Started: 691
Started: 692
Started: 693
Started: 694
Started: 695
Started: 696
Started: 697
Started: 698
Started: 699
Started: 700
Started: 701
Started: 702
Started: 703
Started: 704
Started: 705
Started: 706
Started: 707
Started: 708
Started: 709
Started: 710
Started: 711
Started: 712
Started: 713
Started: 714
Started: 715
Started: 716
Started: 717
Started: 718
Started: 719
Started: 720
Started: 721
Started: 722
Started: 723
Started: 724
Started: 725
Started: 726
Started: 727
Started: 728
Started: 729
Started: 730
Started: 731
Started: 732
Started: 733
Started: 734
Started: 735
Started: 736
Started: 737
Started: 738
Started: 739
Started: 740
Started: 741
Started: 742
Started: 743
Started: 744
Started: 745
Started: 746
Started: 747
Started: 748
Started: 749
Started: 750
Started: 751
Started: 752
Started: 753
Started: 754
Started: 755
Started: 756
Started: 757
Started: 758
Started: 759
Started: 760
Started: 761
Started: 762
Started: 763
Started: 764
Started: 765
Started: 766
Started: 767
Started: 768
Started: 769
Started: 770
Started: 771
Started: 772
Started: 773
Started: 774
Started: 775
Started: 776
Started: 777
Started: 778
Started: 779
Started: 780
Started: 781
Started: 782
Started: 783
Started: 784
Started: 785
Started: 786
Started: 787
Started: 788
Started: 789
Started: 790
Started: 791
Started: 792
Started: 793
Started: 794
Started: 795
Started: 796
Started: 797
Started: 798
Started: 799
Started: 800
Started: 801
Started: 802
Started: 803
Started: 804
Started: 805
Started: 806
Started: 807
Started: 808
Started: 809
Started: 810
Started: 811
Started: 812
Started: 813
Started: 814
Started: 815
Started: 816
Started: 817
Started: 818
Started: 819
Started: 820
Started: 821
Started: 822
Started: 823
Started: 824
Started: 825
Started: 826
Started: 827
Started: 828
Started: 829
Started: 830
Started: 831
Started: 832
Started: 833
Started: 834
Started: 835
Started: 836
Started: 837
Started: 838
Started: 839
Started: 840
Started: 841
Started: 842
Started: 843
Started: 844
Started: 845
Started: 846
Started: 847
Started: 848
Started: 849
Started: 850
Started: 851
Started: 852
Started: 853
Started: 854
Started: 855
Started: 856
Started: 857
Started: 858
Started: 859
Started: 860
Started: 861
Started: 862
Started: 863
Started: 864
Started: 865
Started: 866
Started: 867
Started: 868
Started: 869
Started: 870
Started: 871
Started: 872
Started: 873
Started: 874
Started: 875
Started: 876
Started: 877
Started: 878
Started: 879
Started: 880
Started: 881
Started: 882
Started: 883
Started: 884
Started: 885
Started: 886
Started: 887
Started: 888
Started: 889
Started: 890
Started: 891
Started: 892
Started: 893
Started: 894
Started: 895
Started: 896
Started: 897
Started: 898
Started: 899
Started: 900
Started: 901
Started: 902
Started: 903
Started: 904
Started: 905
Started: 906
Started: 907
Started: 908
Started: 909
Started: 910
Started: 911
Started: 912
Started: 913
Started: 914
Started: 915
Started: 916
Started: 917
Started: 918
Started: 919
Started: 920
Started: 921
Started: 922
Started: 923
Started: 924
Started: 925
Started: 926
Started: 927
Started: 928
Started: 929
Started: 930
Started: 931
Started: 932
Started: 933
Started: 934
Started: 935
Started: 936
Started: 937
Started: 938
Started: 939
Started: 940
Started: 941
Started: 942
Started: 943
Started: 944
Started: 945
Started: 946
Started: 947
Started: 948
Started: 949
Started: 950
Started: 951
Started: 952
Started: 953
Started: 954
Started: 955
Started: 956
Started: 957
Started: 958
Started: 959
Started: 960
Started: 961
Started: 962
Started: 963
Started: 964
Started: 965
Started: 966
Started: 967
Started: 968
Started: 969
Started: 970
Started: 971
Started: 972
Started: 973
Started: 974
Started: 975
Started: 976
Started: 977
Started: 978
Started: 979
Started: 980
Started: 981
Started: 982
Started: 983
Started: 984
Started: 985
Started: 986
Started: 987
Started: 988
Started: 989
Started: 990
Started: 991
Started: 992
Started: 993
Started: 994
Started: 995
Started: 996
Started: 997
Started: 998
Started: 999
Started: 1000
root at abruzzo - /ppc_abruzzo/zlwang [!]
# openj9_8.0.15/bin/java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190717_374 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c64
OMR      - ec782f2
JCL      - f147086 based on jdk8u222-b10)
root at abruzzo - /ppc_abruzzo/zlwang [!]
# ulimit -a
core file size          (blocks, -c) 1048575
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 2000
pipe size            (512 bytes, -p) 64
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
root at abruzzo - /ppc_abruzzo/zlwang [!]

**Comment by pshipton** [comment] 2019-11-04 20:29
On AIX 7.2 using the same JVM parameters, I am also able to create 1000 threads with OpenJ9 0.15.1. I also tried with 10,000 and it worked.

**Comment by pshipton** [comment] 2019-11-04 20:33
This seems unrelated to the java heap placement, as in both the original javacore from https://github.com/eclipse/openj9/issues/7503#issuecomment-546297230 and on my machine, the object heap is located at 0xE0000000.

**Comment by JonDGH** [comment] 2019-11-05 11:20
These are the hard limits on the AIX box that I'm using:

#-> ulimit -aH
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        4194304
memory(kbytes)       unlimited
coredump(blocks)     unlimited
nofiles(descriptors) 65536
threads(per process) unlimited
processes(per user)  unlimited

And the soft limits:

#-> ulimit -aS
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     2097151
nofiles(descriptors) 32768
threads(per process) unlimited
processes(per user)  unlimited

If I set the soft limit for data to unlimited the J9 VM runs in the same way as the IBM VM.  Shouldn't the VM be setting the soft limit based on the -Xmx value?

https://www.ibm.com/developerworks/community/blogs/troubleshootingjava/entry/ulimit_and_xmx?lang=en

**Comment by pshipton** [comment] 2019-11-05 13:45
The machine I'm using has the same soft limits, but no problem creating 10,000 threads.
`bin/java -Xmx1024m -Xss256K -Xmso256K StartThreads 10000`
```
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited
```
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b10)
Eclipse OpenJ9 VM (build openj9-0.15.1, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190717_374 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c64
OMR      - ec782f2
JCL      - f147086 based on jdk8u222-b10)
```

For reference here are the hard limits on my machine as well.
```
core file size        (blocks, -c) unlimited
data seg size         (kbytes, -d) unlimited
file size             (blocks, -f) unlimited
max memory size       (kbytes, -m) unlimited
open files                    (-n) unlimited
pipe size          (512 bytes, -p) 64
stack size            (kbytes, -s) hard
cpu time             (seconds, -t) unlimited
max user processes            (-u) 128
virtual memory        (kbytes, -v) unlimited
```

**Comment by pshipton** [comment] 2019-11-05 13:56
The only change to the limits done by OpenJ9 (and the IBM Java VM) is to the file descriptors.
https://github.com/eclipse/openj9/blob/200fc549e0400c6d25820866220d85507df77394/runtime/vm/jvminit.c#L1855

It seems that IBM Java does set the RLIMIT_DATA limit in the JCL code, but this change is specific to IBM Java and isn't in OpenJDK. OpenJ9 builds use OpenJDK.

@andrew-m-leonard can you please look at this, perhaps we can contribute this change to OpenJDK. The IBM setrlimit() code is in jdk/src/java.base/unix/native/libjli/java_md_solinux.c

**Comment by pshipton** [comment] 2019-11-05 13:57
I suppose we could also consider making this change in OpenJ9.
@DanHeidinga

**Comment by JonDGH** [comment] 2019-11-05 14:46
Assuming the data limits code is along the lines of the file descriptor limits, it seems like the workaround for us is to add: ulimit -d -S $(ulimit -d -H)

to our launch script.

Am I correct in thinking that this isn't specific to AIX?

If there's no code to adjust the limits, it seems odd that this is the case: "The machine I'm using has the same soft limits, but no problem creating 10,000 threads."

**Comment by pshipton** [comment] 2019-11-05 15:32
Agreed, I don't understand why it works on the machines we have, but not yours.
@andrew-m-leonard can you get any history of why the change was added to IBM Java?

The IBM Java change to adjust the RLIMIT_DATA limit is specific to AIX.

**Comment by pshipton** [comment] 2019-11-05 15:41
@JonDGH I do notice that you have a stack limit `stack(kbytes) 4194304`, while the other machines do not. Not sure if this is related. @zl-wang any ideas?

**Comment by JonDGH** [comment] 2019-11-05 15:51
I see the same issue even with the stack size set to unlimited, so seems like it's solely down to the data limit:

#-> ulimit -aH
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        unlimited
memory(kbytes)       unlimited
coredump(blocks)     unlimited
nofiles(descriptors) 65536
threads(per process) unlimited
processes(per user)  unlimited

#-> ulimit -aS
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         131072
stack(kbytes)        32768
memory(kbytes)       32768
coredump(blocks)     2097151
nofiles(descriptors) 32768
threads(per process) unlimited
processes(per user)  unlimited

**Comment by DanHeidinga** [comment] 2019-11-05 17:10
> I suppose we could also consider making this change in OpenJ9.

+1 I support fixing this in OpenJ9 rather than having a patch to the Extensions repo.  Given there's a patch in the IBM JDK for this, we've clearly identified a need for it in the past.

**Comment by zl-wang** [comment] 2019-11-05 17:29
What is the DATA-limit fix (in JCL)? Set it to accommodate the java heap?  That is missing the target, since java heap is typically not budgeted from C/system heap where DATA-limit applies. It looks to me it just happens to work out.

**Comment by andrew-m-leonard** [comment] 2019-11-05 17:55
Will investigate, https://github.ibm.com/runtimes/openjdk-contribution/issues/1079
@pshipton

**Comment by pshipton** [comment] 2019-11-05 18:26
> What is the DATA-limit fix (in JCL)? Set it to accommodate the java heap?

@zl-wang the JCL fix sets RLIMIT_DATA to RLIM64_INFINITY if it isn't already. If RLIM64_INFINITY can't be set, it prints the message below. I don't know that this change is related to the java heap. In this case it is affecting the number of threads which can be created, and not the size of the heap which can be used. When the JVM fails to allocate a thread, an OOM error occurs. `Detail "java/lang/OutOfMemoryError" "Failed to create a thread: retVal -1073741830, errno 11" received`
```
WARNING: JVM is running with hard ulimit not set to unlimited, out of memory errors may occur
If an out of memory error occurs try running \"chuser data_hard=-1 username\" as root
before running java
```

**Comment by pshipton** [comment] 2019-11-05 18:29
@zl-wang if you didn't catch it, see https://github.com/eclipse/openj9/issues/7503#issuecomment-549781070 `If I set the soft limit for data to unlimited the J9 VM runs in the same way as the IBM VM.` meaning that 1000 threads can be created with OpenJ9, rather than getting OOM after 300 threads.

**Comment by zl-wang** [comment] 2019-11-05 18:48
That makes senses. It should be applied to all platforms (of resource limitation), shouldn't it?

**Comment by pshipton** [comment] 2019-11-05 18:56
> That makes senses. It should be applied to all platforms (of resource limitation), shouldn't it?

@zl-wang It has never been applied to all platforms before, and afaik nobody has reported a problem on other platforms. We'll see if Andrew can get any more information from investigating why the limit change was introduced on AIX. 

What we still don't understand is why the machine I'm using, and the one you are using, doesn't have the same limitation, although at least my machine and the problematic machine have the same soft limit for data. Likely we have different revisions of AIX 7.2, but I'm not sure what to check. I did notice the order of lines in the hard limit output (ulimit -aH) is different between the machines. The `uname -a` output on my machine is `AIX aix72p7vm14 2 7 00F72C294C00`

**Comment by JonDGH** [comment] 2019-11-05 19:29
I'm not sure if any of this is helpful, but on my machine:
$ uname -a
AIX paix303 2 7 00FB112A4C00

$ oslevel -q
Known Maintenance Levels
------------------------
7.2.0.0

**Comment by zl-wang** [comment] 2019-11-05 19:42
@pshipton  on my machine, i indeed needed to (re)set the limits in order to run that test case, as i described in https://github.com/eclipse/openj9/issues/7503#issuecomment-549493444.

**Comment by pshipton** [comment] 2019-11-05 19:57
ok, so seems only my machine is wonky. It does seem to be a different level (00F72C294C00 instead of 00FB112A4C00), perhaps there was a bug.

**Comment by JonDGH** [comment] 2019-11-06 09:06
Thanks for all the assistance on this.  I don't think the dumps and code in my repo (https://github.com/JonDGH/j9-aix-oom) are of any value now, so I'll be deleting it shortly.  I can always make anything it contained available again if it's needed.

**Comment by M-Davies** [comment] 2019-11-28 15:03
@pshipton Looking into rt-patch for `setrlimit()` and why/where it was implemented in IBM Java

**Comment by M-Davies** [comment] 2019-11-28 15:33
`setrlimit()` was implemented in IBM Java as a merge from Oracle. Still looking through jazz to see if there is a reason on why this was ported over.
```
jse-9135.2
jdk8u20-b08 merge: merge Oracle aix porting changes into this patch.
```

**Comment by M-Davies** [comment] 2019-12-02 15:36
My suspicion is that the full details on why this was included in OpenJDK in the first place are behind Oracle's closed doors. There is no record of this being implemented in jazz and I could not see any definitive reference to this being fixed in jdk8u20-b08.

@pshipton Other than jazz and the reviews at http://cr.openjdk.java.net/~amurillo/8u20/hs25.20-b08-jdk8u20-b08.webrev/ are there any other places worth looking into if I wanted to dig deeper into this?

**Comment by pshipton** [comment] 2019-12-03 18:36
There should be history in OpenJDK for the addition, did you track that down?

**Comment by pshipton** [comment] 2019-12-03 18:38
i.e. if you figure which of the changes in http://cr.openjdk.java.net/~amurillo/8u20/hs25.20-b08-jdk8u20-b08.webrev/ added the code, you can look at the individual change. Like https://bugs.openjdk.java.net/browse/JDK-8037915

**Comment by pshipton** [comment] 2019-12-03 18:49
@M-Davies are you sure the setrlimit came from OpenJDK? It seems unlikely, because it's not in OpenJDK now. The IBM Java code is tagged `IBM-aix-bringup`. I think this can be traced back in the IBM Java 8 code stream.

**Comment by M-Davies** [comment] 2019-12-04 11:57
> i.e. if you figure which of the changes in http://cr.openjdk.java.net/~amurillo/8u20/hs25.20-b08-jdk8u20-b08.webrev/ added the code, you can look at the individual change. Like https://bugs.openjdk.java.net/browse/JDK-8037915
> 

I looked through those changes already and couldn't see it. Looking into hotspot's source, they also don't seem to use `setrlimit` either. I believe you're right in that it is a IBM Java addition. 

> @M-Davies are you sure the setrlimit came from OpenJDK? It seems unlikely, because it's not in OpenJDK now. The IBM Java code is tagged `IBM-aix-bringup`. I think this can be traced back in the IBM Java 8 code stream.

@andrew-m-leonard is looking into getting me access to the IBM Java 8 source over IBM Java 9 at the moment so I can track this change back

**Comment by M-Davies** [comment] 2019-12-04 17:21
Src code itself doesn't reveal much, only that the changes in Java 9 are identical to the ones in Java 8 so it's possible they were introduced to both versions at the same time. I'll have a look through the changelogs at https://developer.ibm.com/javasdk/downloads/sdk8/, see if I can find any references to OutOfMemory errors or setting rlimits

**Comment by M-Davies** [comment] 2019-12-04 18:26
@pshipton Ref https://jazz103.hursley.ibm.com:9443/jazz/web/projects/JTC-JAT#action=com.ibm.team.workitem.viewWorkItem&id=70929

- The 2nd attachment `Jazz-70929_oracle_to_ibm.diff` appears to be where `setrlimit` was implemented in Java 8 (Line 1383)

- The jazz work item lists
```
9, src/solaris/bin/java_md_solinux.c
- use LIBPATH env var instead of LD_LIBRARY_PATH for AIX
- added AIX def for platform specific code.
10, src/solaris/bin/java_md_solinux.h
- definition of installation dirs for AIX
```
as the changes made but the diff also includes extra changes not listed here. Note, these are both from IBM (not OpenJDK). The details of these may be included in OJDK JIRA but no details are given on this.

**Comment by pshipton** [comment] 2019-12-04 21:57
@M-Davies the title of 70929 is "basic class library bringup changes" which means these changes have been forward ported from an older version of Java. You need to look back further at the version of Java where the change was first introduced.

**Comment by M-Davies** [comment] 2019-12-09 16:27
Jazz/rtc doesn't have any more relevant information on why this was included. @andrew-m-leonard and I had a look through Jira but it didn't reveal much information there either. I'm certain that this was either an IBM or Oracle change that is documented in a closed location.

**Comment by pshipton** [comment] 2019-12-09 16:38
Perhaps the Current Release JCL team can help track it down.

**Comment by M-Davies** [comment] 2019-12-10 15:59
Posted a message in #rt-java-cr. Is there anyone in particular on the JCL team that would be good to contact about this?

**Comment by M-Davies** [comment] 2019-12-10 17:07
Paul Cheeseman found a small extract back from 2001. From sov defect 29024 in CMVC:
```
The src/tools/pfm/java_md.c routine setLibAndExec()
needs to have the #ifdef !defined(__64BIT__) removed
from around the testing and setting of the environment
variable LDR_CNTRL=MAXDATA=0x80000000

This change must be in place when the fix for aix defect
328297 arrives.

The README will document a workaround for 64-bit
OutOfMemoryError problems which is to use the command
"ulimit -d unlimited" before the test or application which
previously reported OutOfMemoryError.
```
This was later refined to the current setlimit64 form. I cannot access CMVC however

**Comment by pshipton** [comment] 2020-01-13 20:07
Below is the information found in old reports in 2001, which seems to correspond to Java 1.3. There is no setLibAndExec() function any more I could find, or any mention of LDR_CNTRL or MAXDATA. We did recently make this change https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/349

The [thread and threadgroups] tests fail since they run out of malloc'ed space to allocate thread stacks. Test succeeds
if ulimit -d unlimited is run first. Test also succeeds with smaller stack sizes. The behaviour of
malloc on 64-bit is due to be changed so that MAXDATA can be set to indicate
the soft data rlimit.

java_md.c setLibAndExec() needs to have the
`#if !defined(__64BIT__)` and corresponding
`#endif`
removed so that the MAXDATA setting is used for
both 32- and 64-bit JVMs.
...from around the testing and setting of the environment
variable LDR_CNTRL=MAXDATA=0x80000000

**Closed** 2020-01-23 16:07 UTC
Labels: userRaised
