### ISSUE TITLE
JDK8 [AIX] 80 JIT_Extended.Fiorano_RandomMix.NoOptions - VMState: 0x0005ff0a : Return address is out of range

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#11667] opened 2021-01-15 17:45 UTC
Failure link
------------

From an internal build `ibuild 463694`:
```
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pap3280sr7-20201221_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc-32-Bit 20210114_463694 (JIT enabled, AOT enabled)
OpenJ9   - 8f7d53d
OMR      - 78b2752
IBM      - 358762e)
JCL - 20201217_01 based on Oracle jdk8u281-b09
```

Optional info
-------------

- intermittent failure (yes|no): yes 7/100 failed at grinder `463723`

Failure output (captured from console output)
---------------------------------------------
```
*************************************************************************************************
Workload randomization is enabled.
Fiorano will generate a randomized class repository for this test.
To rerun Fiorano with the previously used class repository, append the following to the EXTRA_OPTIONS parameter in Grinder command line: -randomSeed 667539581.

Alternatively, following steps can also be used to rerun Fiorano with a previously used repository: 
(1) Locate the result directory Jar for the failed job in Axxon result store
(2) Obtain workmap.txt, methodmap.txt and threadlifetimemap.txt files in the result directory
(3) Rerun Fiorano with these 3 additional command line options (append them to the EXTRA_OPTIONS parameter in Grinder command line):
                        -useWorkMap <workmap file path> -useMethodMap <method map file path> -useThreadLifetimeMap <thread lifetime map file path>
************************************************************************************************

Random Seed being used for generating repository is : 667539581
Generating 15 Interfaces...
Job mix will include the following workload types : 
Lucene Search
Jasmin Transform
Indexing to directory '/tmp/bld_463694/fioranoTestCommon/667539581/index'...
adding /bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lucene/Homer/Odyssey.txt
adding /bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lucene/JohnLock/EssayConcerningHumaneUnderstanding1.txt
adding /bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lucene/JohnLock/EssayConcerningHumaneUnderstanding2.txt
adding /bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lucene/Russell/Russel_HistoryOfWesternPhilosophy.txt
adding /bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lucene/Shakespeare/The_Complete_Works_of_Willia.txt
Generating 15 abstract super parent classes...
Generating Caller Thread
Generating TestAppRunner
Generating Validator
Total unique search key used in Lucene job : 102
\
        echo Compiling generated classes..; \
        cd /tmp/bld_463694/fioranoTestCommon/667539581/jittestgen; \
        /bluebird/builds/bld_463694/sdk/ap3280/bin/javac -cp "/bluebird/builds/bld_463694/jvmtest/JIT/fiorano/fiorano.jar:/bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lib/lucene-core-3.3.0.jar:"/bluebird/builds/bld_463694/jvmtest/VM/lib/log4j.jar":/bluebird/javatest/HEAD_382595/test/../../j9unversioned/fioranostatics/lib/openjpa-all-2.1.1.jar" ./*.java \
        || perl "-I/bluebird/javatest/HEAD_382595/test/lib/perl" -mResultStore::Uploader -e "ResultStore::Uploader::upload('.',463694,667539581,'vmfarm.ottawa.ibm.com:31','results-667539581')"
Compiling generated classes..
warning: Supported source version 'RELEASE_6' from annotation processor 'org.apache.openjpa.persistence.meta.AnnotationProcessor6' less than -source '1.8'
Assertion failed at /tmp/bld_463694/bld_aix_ppc/compiler/../compiler/p/codegen/J9UnresolvedDataSnippet.cpp:259: comp->target().cpu.isTargetWithinIFormBranchRange(targetAddress, (intptr_t)cursor)
VMState: 0x0005ff0a
        Return address is out of range
compiling com/sun/tools/javac/comp/Lower.visitMethodDef(Lcom/sun/tools/javac/tree/JCTree$JCMethodDecl;)V at level: warm
+0x320
+0x130
+0x81c
+0x120
+0xf8
+0x70c
+0x2b8
+0x5c8
+0x18c0
+0x1114
+0x21d0
+0x608
+0x840
+0xa5c
+0x76c
+0x148
+0x5f4
+0x608
+0x584
+0x230
_pthread_body+0x11c
+0x0

JVMDUMP039I Processing dump event "abort", detail "" at 2021/01/14 23:35:40 - please wait.
JVMDUMP032I JVM requested System dump using '/tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/core.20210114.233540.15008216.0001.dmp' in response to an event
JVMDUMP010I System dump written to /tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/core.20210114.233540.15008216.0001.dmp
JVMDUMP032I JVM requested Java dump using '/tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/javacore.20210114.233540.15008216.0002.txt' in response to an event
JVMDUMP010I Java dump written to /tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/javacore.20210114.233540.15008216.0002.txt
JVMDUMP032I JVM requested Snap dump using '/tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/Snap.20210114.233540.15008216.0003.trc' in response to an event
JVMDUMP010I Snap dump written to /tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/Snap.20210114.233540.15008216.0003.trc
JVMDUMP032I JVM requested JIT dump using '/tmp/bld_463694/fioranoTestCommon/667539581/jittestgen/jitdump.20210114.233540.15008216.0004.dmp' in response to an event
Assertion failed at /tmp/bld_463694/bld_aix_ppc/compiler/../compiler/p/codegen/J9UnresolvedDataSnippet.cpp:259: comp->target().cpu.isTargetWithinIFormBranchRange(targetAddress, (intptr_t)cursor)
VMState: 0x0005ff0a
        Return address is out of range
compiling com/sun/tools/javac/comp/Lower.visitMethodDef(Lcom/sun/tools/javac/tree/JCTree$JCMethodDecl;)V at level: warm
+0x320
+0x130
+0x81c
+0x120
+0xf8
+0x70c
+0x2b8
+0x5c8
+0x18c0
+0x1114
+0x21d0
+0x608
+0x840
+0xa5c
+0x76c
+0x148
+0x5f4
+0x608
+0x584
+0x230
_pthread_body+0x11c
+0x0

/bin/sh[4]: 15008216 IOT/Abort trap(coredump)
```

**Comment by pshipton** [comment] 2021-01-15 17:57
`vmState [0x5ff0a]: {J9VMSTATE_JIT_CODEGEN} {EmitSnippets}`

**Comment by pshipton** [comment] 2021-01-15 17:58
@gita-omr @0xdaryl fyi

**Comment by pshipton** [comment] 2021-01-15 17:59
7/100 failure seems high enough to be a blocker?

**Comment by gita-omr** [comment] 2021-01-15 18:14
I think it's a duplicate of https://github.com/eclipse/openj9/issues/11511

@rmnattas @aviansie-ben : fyi

**Comment by pshipton** [comment] 2021-02-25 01:26
Closing as a dup of #11511

**Closed by pshipton** 2021-02-25 01:26 UTC
Labels: arch:power, comp:jit, test failure
