### ISSUE TITLE
Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR Segmentation error vmState=0x00000000 when compiling the test

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#7967] opened 2019-12-05 12:41 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/374/console

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
21:42:57  init:
21:42:57      [mkdir] Created dir: /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/bin
21:42:57  
21:42:57  compile:
21:42:57       [echo] Ant version is Apache Ant(TM) version 1.9.9 compiled on February 2 2017
21:42:57       [echo] ============COMPILER SETTINGS============
21:42:57       [echo] ===fork:                         yes
21:42:57       [echo] ===debug:                        on
21:42:57      [javac] Compiling 13 source files to /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/bin
21:42:58      [javac] Unhandled exception
21:42:58      [javac] Type=Segmentation error vmState=0x00000000
21:42:58      [javac] J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
21:42:58      [javac] Handler1=09001000A0ABEC08 Handler2=09001000A09B1618
21:42:58      [javac] R0=0000000000000000 R1=00000100100457B0 R2=09001000A0AC26D0 R3=0000000030008200
21:42:58      [javac] R4=0000000030056EB0 R5=0000000030056EB0 R6=0000000000000020 R7=0000000000000020
21:42:58      [javac] R8=0000000000000000 R9=00000000300082F8 R10=0000000000000000 R11=0000000000000000
21:42:58      [javac] R12=0000000022000840 R13=000001001004E800 R14=00000000300CCDE8 R15=0000000030008200
21:42:58      [javac] R16=000001001178DE38 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=0000000000000000
21:42:58      [javac] R20=0000000000000001 R21=09001000A09A9C68 R22=0000000000000000 R23=0A000100000B1098
21:42:58      [javac] R24=000000003FFFFFF8 R25=0000000000000000 R26=0000000000000001 R27=0000000000000000
21:42:58      [javac] R28=0000000000000001 R29=0000000030056EB0 R30=0000000000000020 R31=0000000030008200
21:42:58      [javac] IAR=0900000004895300 LR=0900000004895514 MSR=A00000000200D032 CTR=09000000048954E0
21:42:58      [javac] CR=224008402000000C FPSCR=8200000000000000 XER=2000000C82000000
21:42:58      [javac] FPR0 0000000000000001 (f: 1.000000, d: 4.940656e-324)
21:42:58      [javac] FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
21:42:58      [javac] FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
21:42:58      [javac] FPR3 433000000007c701 (f: 509697.000000, d: 4.503600e+15)
21:42:58      [javac] FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
21:42:58      [javac] FPR6 411f1c0400000000 (f: 0.000000, d: 5.096970e+05)
21:42:58      [javac] FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR8 43300000000347a9 (f: 214953.000000, d: 4.503600e+15)
21:42:58      [javac] FPR9 40fb3936eaefafcf (f: 3941576704.000000, d: 1.115074e+05)
21:42:58      [javac] FPR10 407816625220ec6e (f: 1377889408.000000, d: 3.853990e+02)
21:42:58      [javac] FPR11 3fbc73cd95d5986d (f: 2513803264.000000, d: 1.111420e-01)
21:42:58      [javac] FPR12 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
21:42:58      [javac] FPR13 0000000000000003 (f: 3.000000, d: 1.482197e-323)
21:42:58      [javac] FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
21:42:58      [javac] Module=/home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdkbinary/j2sdk-image/jre/lib/ppc64/compressedrefs/libj9vm29.so
21:42:58      [javac] Module_base_address=0900000004814000
21:42:58      [javac] Target=2_90_20191204_417 (AIX 7.1)
21:42:58      [javac] CPU=ppc64 (8 logical CPUs) (0x200000000 RAM)
21:42:58      [javac] ----------- Stack Backtrace -----------
21:42:58      [javac] resolveStaticFieldRef+0x30 (0x0900000004895514 [libj9vm29.so+0x81514])
21:42:58      [javac] old_slow_jitResolveStaticField+0xfc (0x0900000004E4DE60 [libj9jit29.so+0x198e60])
21:42:58      [javac] (0x0900000004E42E3C [libj9jit29.so+0x18de3c])
21:42:58      [javac] runCallInMethod+0x264 (0x090000000487C3C8 [libj9vm29.so+0x683c8])
21:42:58      [javac] gpProtectedRunCallInMethod__FPv+0x48 (0x090000000486CD2C [libj9vm29.so+0x58d2c])
21:42:58      [javac] signalProtectAndRunGlue+0x28 (0x0900000004866FAC [libj9vm29.so+0x52fac])
21:42:58      [javac] omrsig_protect+0x488 (0x0900000004B0FDCC [libj9prt29.so+0x69dcc])
21:42:58      [javac] gpProtectAndRun+0xf8 (0x09000000048670FC [libj9vm29.so+0x530fc])
21:42:58      [javac] gpCheckCallin+0x100 (0x090000000486CCA4 [libj9vm29.so+0x58ca4])
21:42:58      [javac] callStaticVoidMethod+0x48 (0x09000000048C318C [libj9vm29.so+0xaf18c])
21:42:58      [javac] (0x0000010000003F68 [javac+0x3f68])
21:42:58      [javac] _pthread_body+0xf0 (0x090000000056AE14 [libpthreads.a+0x3e14])
21:42:58      [javac] ---------------------------------------
21:42:58      [javac] JVMDUMP039I Processing dump event "gpf", detail "" at 2019/12/04 20:24:04 - please wait.
21:42:58      [javac] JVMDUMP032I JVM requested System dump using '/home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/core.20191204.202404.4194770.0001.dmp' in response to an event
21:43:02      [javac] JVMDUMP010I System dump written to /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/core.20191204.202404.4194770.0001.dmp
21:43:02      [javac] JVMDUMP032I JVM requested Java dump using '/home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/javacore.20191204.202404.4194770.0002.txt' in response to an event
21:43:02      [javac] JVMDUMP010I Java dump written to /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/javacore.20191204.202404.4194770.0002.txt
21:43:02      [javac] JVMDUMP032I JVM requested Snap dump using '/home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/Snap.20191204.202404.4194770.0003.trc' in response to an event
21:43:02      [javac] JVMDUMP010I Snap dump written to /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/Snap.20191204.202404.4194770.0003.trc
21:43:02      [javac] JVMDUMP007I JVM Requesting JIT dump using '/home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/jitdump.20191204.202404.4194770.0004.dmp'
21:43:02      [javac] JVMDUMP010I JIT dump written to /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/jitdump.20191204.202404.4194770.0004.dmp
21:43:02      [javac] JVMDUMP013I Processed dump event "gpf", detail "".
21:43:02  
21:43:02  BUILD FAILED
21:43:02  /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/build_tools.xml:53: The following error occurred while executing this line:
21:43:02  /home/u0020236/workspace/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR/openjdk-tests/TKG/scripts/build_tools.xml:34: Compile failed; see the compiler error output for details.
21:43:02  
21:43:02  Total time: 5 seconds
21:43:02  gmake: *** [run_configure.mk:29: testconfig] Error 1
```

**Comment by JasonFengJ9** [comment] 2019-12-05 12:49
https://ci.eclipse.org/openj9/job/Build_JDK11_ppc64_aix_OMR/421/console


```
19:30:28  Compiling 4 files for BUILD_JIGSAW_TOOLS
19:30:31  Unhandled exception
19:30:31  Type=Segmentation error vmState=0x00000000
19:30:31  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000032
19:30:31  Handler1=09001000B2376DF8 Handler2=09001000B234F618
19:30:31  R0=0000000000000000 R1=000001001004BB60 R2=09001000B237A7E8 R3=0000000030008200
19:30:31  R4=00000000301527C0 R5=00000000301527C0 R6=0000000000000020 R7=0000000000000020
19:30:31  R8=0000000000000000 R9=00000000300082F8 R10=8000000000001032 R11=0000000000000000
19:30:31  R12=0000000022000220 R13=0000010010057800 R14=00000000300F4FF8 R15=0000000030008200
19:30:31  R16=0000010020EFADB8 R17=FFFFFFFFFFFFFFFF R18=0000000000000000 R19=00000000FFA27B10
19:30:31  R20=0000000000000009 R21=000000000000000D R22=0000000000000000 R23=0A0001000020EDC0
19:30:31  R24=000000003FFFFFF8 R25=0000000000000000 R26=0000000000000001 R27=0000000000000000
19:30:31  R28=0000000000000001 R29=00000000301527C0 R30=0000000000000020 R31=0000000030008200
19:30:31  IAR=0900000285D69F00 LR=0900000285D6A114 MSR=A00000000200D032 CTR=0900000285D6A0E0
19:30:31  CR=2240022020000000 FPSCR=8200000000000000 XER=2000000082000000
19:30:31  FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR1 c3e0000000000000 (f: 0.000000, d: -9.223372e+18)
19:30:31  FPR2 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
19:30:31  FPR3 4330000000027803 (f: 161795.000000, d: 4.503600e+15)
19:30:31  FPR4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR5 4330000000000000 (f: 0.000000, d: 4.503600e+15)
19:30:31  FPR6 4103c01800000000 (f: 0.000000, d: 1.617950e+05)
19:30:31  FPR7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR8 433000000001d2a7 (f: 119463.000000, d: 4.503600e+15)
19:30:31  FPR9 40fb39343ff01715 (f: 1072699136.000000, d: 1.115073e+05)
19:30:31  FPR10 412e848000000000 (f: 0.000000, d: 1.000000e+06)
19:30:31  FPR11 3fbc73cd95d5986d (f: 2513803264.000000, d: 1.111420e-01)
19:30:31  FPR12 3ff0000000000000 (f: 0.000000, d: 1.000000e+00)
19:30:31  FPR13 0000000000000003 (f: 3.000000, d: 1.482197e-323)
19:30:31  FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
19:30:31  Module=/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/build/aix-ppc64-normal-server-release/jdk/lib/compressedrefs/libj9vm29.so
19:30:31  Module_base_address=0900000285CE8000
19:30:31  Target=2_90_20191204_421 (AIX 7.1)
19:30:31  CPU=ppc64 (8 logical CPUs) (0x200000000 RAM)
19:30:31  ----------- Stack Backtrace -----------
19:30:31  resolveStaticFieldRef+0x30 (0x0900000285D6A114 [libj9vm29.so+0x82114])
19:30:31  old_slow_jitResolveStaticField+0xfc (0x0900000286291E60 [libj9jit29.so+0x198e60])
19:30:31  (0x0900000286286E3C [libj9jit29.so+0x18de3c])
19:30:31  initializeAttachedThreadImpl+0x38c (0x0900000285D4CDF0 [libj9vm29.so+0x64df0])
19:30:31  initializeAttachedThread+0x5c (0x0900000285D533C0 [libj9vm29.so+0x6b3c0])
19:30:31  standardInit+0x730 (0x0900000287B1A194 [libjclse29.so+0x42194])
19:30:31  J9VMDllMain+0x314 (0x0900000287B67558 [libjclse29.so+0x8f558])
19:30:31  runJ9VMDllMain@AF74_49+0xf4 (0x0900000285CFD098 [libj9vm29.so+0x15098])
19:30:31  pool_do+0xf8 (0x0900000285D0795C [libj9vm29.so+0x1f95c])
19:30:31  IPRA.$runInitializationStage+0xc4 (0x0900000285CFB028 [libj9vm29.so+0x13028])
19:30:31  protectedInitializeJavaVM+0xde0 (0x0900000285CF2EA4 [libj9vm29.so+0xaea4])
19:30:31  omrsig_protect+0x488 (0x0900000285FE5DCC [libj9prt29.so+0x69dcc])
19:30:31  initializeJavaVM+0x218 (0x0900000285CF1BBC [libj9vm29.so+0x9bbc])
19:30:31  J9_CreateJavaVM+0xa4 (0x0900000285D111A8 [libj9vm29.so+0x291a8])
19:30:31  JNI_CreateJavaVM+0x984 (0x0900000285CAE008 [libjvm.so+0x28008])
19:30:31  JNI_CreateJavaVM+0x1c4 (0x0900000285C700C8 [libjvm.so+0x250c8])
19:30:31  JNI_CreateJavaVM+0x1c4 (0x0900000285C350C8 [libjvm.so+0x250c8])
19:30:31  JavaMain+0xdc (0x00000100000066A0 [java+0x66a0])
19:30:31  _pthread_body+0xf0 (0x0900000000526E14 [libpthreads.a+0x3e14])
19:30:31  ---------------------------------------
19:30:31  JVMDUMP039I Processing dump event "gpf", detail "" at 2019/12/04 18:30:30 - please wait.
19:30:31  JVMDUMP032I JVM requested System dump using '/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/core.20191204.183030.22609992.0001.dmp' in response to an event
19:30:35  JVMDUMP010I System dump written to /home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/core.20191204.183030.22609992.0001.dmp
19:30:35  JVMDUMP032I JVM requested Java dump using '/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/javacore.20191204.183030.22609992.0002.txt' in response to an event
19:30:35  JVMDUMP010I Java dump written to /home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/javacore.20191204.183030.22609992.0002.txt
19:30:35  JVMDUMP032I JVM requested Snap dump using '/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/Snap.20191204.183030.22609992.0003.trc' in response to an event
19:30:35  JVMDUMP010I Snap dump written to /home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/Snap.20191204.183030.22609992.0003.trc
19:30:35  JVMDUMP007I JVM Requesting JIT dump using '/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/jitdump.20191204.183030.22609992.0004.dmp'
19:30:35  JVMDUMP010I JIT dump written to /home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/make/jitdump.20191204.183030.22609992.0004.dmp
19:30:35  JVMDUMP013I Processed dump event "gpf", detail "".
19:30:35  ExplodedImageOptimize.gmk:40: recipe for target '/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/build/aix-ppc64-normal-server-release/jdk/_packages_attribute.done' failed
19:30:35  gmake[3]: *** [/home/u0020236/workspace/Build_JDK11_ppc64_aix_OMR/build/aix-ppc64-normal-server-release/jdk/_packages_attribute.done] Error 255
19:30:35  make/Main.gmk:351: recipe for target 'exploded-image-optimize' failed
19:30:35  gmake[2]: *** [exploded-image-optimize] Error 2
19:30:35  
19:30:35  ERROR: Build failed for target 'all' in configuration 'aix-ppc64-normal-server-release' (exit code 2) 
19:30:35  Stopping sjavac server
19:30:35  
```

**Comment by pshipton** [comment] 2019-12-05 14:29
@fjeremic @dchopra001 
https://openj9.slack.com/archives/CDS7QE9HB/p1575508443088500

**Comment by cathyzhyi** [comment] 2020-03-18 15:44
looks like this one is fixed already. Shall it be closed? @fjeremic @dchopra001

**Comment by fjeremic** [comment] 2020-03-18 16:06
Closing since it has been 3 months without a reproduction. We can reopen if issue appears again.

**Closed by fjeremic** 2020-03-18 16:06 UTC
Labels: arch:power, blocker, comp:jit, segfault, test failure

**Comment by pshipton** [comment] 2020-03-18 19:14
According to the Slack comments, it was fixed by https://github.com/eclipse/omr/pull/4650
