### ISSUE TITLE
JTreg test fail : java/lang/invoke/lambda/LogGeneratedClassesTest.java

### ISSUE THREAD

**Issue by ben-walsh** [eclipse/openj9#3399] opened 2018-10-22 15:14 UTC
Test https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/java/lang/invoke/lambda/LogGeneratedClassesTest.java has three failures ...

```
test LogGeneratedClassesTest.testDumpDirIsFile(): failure
java.lang.AssertionError: only show error once expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:267)
	at LogGeneratedClassesTest.testDumpDirIsFile(LogGeneratedClassesTest.java:161)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
test LogGeneratedClassesTest.testDumpDirNotExist(): failure
java.lang.AssertionError: only show error once expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:267)
	at LogGeneratedClassesTest.testDumpDirNotExist(LogGeneratedClassesTest.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
test LogGeneratedClassesTest.testDumpDirNotWritable(): failure
java.lang.AssertionError: only show error once expected [1] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:267)
	at LogGeneratedClassesTest.testDumpDirNotWritable(LogGeneratedClassesTest.java:219)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:115)
	at java.base/java.lang.Thread.run(Thread.java:825)
```

Digging deeper into these failures, compiling and executing the following example class taken from the test ...

```
package com.example;
public class TestLambda {
    interface I {
        int foo();
    }
    public static void main(String[] args) {
        System.setSecurityManager(new SecurityManager());
        I lam = () -> 10;
        Runnable r = () -> {
            System.out.println("Runnable");
        };
        r.run();
        System.out.println("Finish");
    }
}
```

... shows ...

When "dumpDir" is a directory which exists and is writeable ...

```
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -cp . -Djdk.internal.lambda.dumpProxyClasses=dumpDir com.example.TestLambda
Runnable
Finish
```

... the example class executes as expected without a problem.

When "notExist" is neither an existing file nor directory ...

```
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -cp . -Djdk.internal.lambda.dumpProxyClasses=notExist com.example.TestLambda
Exception in thread "main" java/lang/ExceptionInInitializerError
	at java/lang/J9VMInternals.ensureError (java.base@9/J9VMInternals.java:191)
	at java/lang/J9VMInternals.recordInitializationFailure (java.base@9/J9VMInternals.java:180)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
java/lang/NullPointerException
	at java/util/Objects.requireNonNull (java.base@9/Objects.java:221)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.<init> (java.base@9/LazyLoggers.java:126)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.makeAccessor (java.base@9/LazyLoggers.java:293)
	at jdk/internal/logger/LazyLoggers$JdkLazyLogger.<init> (java.base@9/LazyLoggers.java:371)
	at jdk/internal/logger/LazyLoggers.getLazyLogger (java.base@9/LazyLoggers.java:441)
	at sun/util/logging/PlatformLogger.getLogger (java.base@9/PlatformLogger.java:297)
	at java/lang/invoke/ProxyClassesDumper.getInstance (java.base@9/ProxyClassesDumper.java:78)
	at java/lang/invoke/InnerClassLambdaMetafactory.<clinit> (java.base@9/InnerClassLambdaMetafactory.java:92)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
```

... the example class produces an unexpected NPE.

When "dumpFile" is a file rather than a directory as required ...

```
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -cp . -Djdk.internal.lambda.dumpProxyClasses=dumpFile com.example.TestLambda
Exception in thread "main" java/lang/ExceptionInInitializerError
	at java/lang/J9VMInternals.ensureError (java.base@9/J9VMInternals.java:191)
	at java/lang/J9VMInternals.recordInitializationFailure (java.base@9/J9VMInternals.java:180)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
java/lang/NullPointerException
	at java/util/Objects.requireNonNull (java.base@9/Objects.java:221)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.<init> (java.base@9/LazyLoggers.java:126)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.makeAccessor (java.base@9/LazyLoggers.java:293)
	at jdk/internal/logger/LazyLoggers$JdkLazyLogger.<init> (java.base@9/LazyLoggers.java:371)
	at jdk/internal/logger/LazyLoggers.getLazyLogger (java.base@9/LazyLoggers.java:441)
	at sun/util/logging/PlatformLogger.getLogger (java.base@9/PlatformLogger.java:297)
	at java/lang/invoke/ProxyClassesDumper.getInstance (java.base@9/ProxyClassesDumper.java:78)
	at java/lang/invoke/InnerClassLambdaMetafactory.<clinit> (java.base@9/InnerClassLambdaMetafactory.java:92)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
```

... the example class produces an unexpected NPE.

When "dumpDirNoWrite" is a directory which exists but is not writeable by the user ...

```
walshbp@bendev:~/jtreg_testing$ $PRODUCT_HOME/bin/java -cp . -Djdk.internal.lambda.dumpProxyClasses=dumpDirNoWrite com.example.TestLambda
Exception in thread "main" java/lang/ExceptionInInitializerError
	at java/lang/J9VMInternals.ensureError (java.base@9/J9VMInternals.java:191)
	at java/lang/J9VMInternals.recordInitializationFailure (java.base@9/J9VMInternals.java:180)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
java/lang/NullPointerException
	at java/util/Objects.requireNonNull (java.base@9/Objects.java:221)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.<init> (java.base@9/LazyLoggers.java:126)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.makeAccessor (java.base@9/LazyLoggers.java:293)
	at jdk/internal/logger/LazyLoggers$JdkLazyLogger.<init> (java.base@9/LazyLoggers.java:371)
	at jdk/internal/logger/LazyLoggers.getLazyLogger (java.base@9/LazyLoggers.java:441)
	at sun/util/logging/PlatformLogger.getLogger (java.base@9/PlatformLogger.java:297)
	at java/lang/invoke/ProxyClassesDumper.getInstance (java.base@9/ProxyClassesDumper.java:78)
	at java/lang/invoke/InnerClassLambdaMetafactory.<clinit> (java.base@9/InnerClassLambdaMetafactory.java:92)
	at java/lang/invoke/LambdaMetafactory.metafactory (java.base@9/LambdaMetafactory.java:324)
	at java/lang/invoke/MethodHandle.resolveInvokeDynamic (java.base@9/MethodHandle.java:1106)
	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:253)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:296)
	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:286)
	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:354)
	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:217)
	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:217)
	at java/lang/Thread.initialize (java.base@9/Thread.java:422)
	at java/lang/Thread.<init> (java.base@9/Thread.java:153)
```

... the example class produces an unexpected NPE.

Test passes against Hotspot.

Log archive : [LogGenClassesProb.tar.gz](https://github.com/eclipse/openj9/files/2501958/LogGenClassesProb.tar.gz)

**Comment by tajila** [comment] 2018-10-25 18:38
I believe the problem is caused by an issue with the `sun/util/logging/PlatformLogger`. It is not assigned to a module (module field is null in the class) which causes NPEs later on

**Comment by smlambert** [comment] 2019-01-09 18:32
Test excluded: https://github.com/AdoptOpenJDK/openjdk-tests/pull/658

**Comment by JasonFengJ9** [comment] 2019-01-15 19:53
Will look at this.

**Comment by JasonFengJ9** [comment] 2019-01-30 16:15
This test failure was caused by couple of `Lamda` expression added within `jdk.internal.loader.BuiltinClassLoader` for `OpenJ9 shared classes`. 
`jdk.internal.lambda.dumpProxyClasses` triggered `Module` related method calls at VM bootstrap stage before `java.base` creation, `sun/util/logging/PlatformLogger.class.getModule()` returns `null` and `NPE` eventually.
This will be fixed by https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/67, https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/6, and https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/113.

In addition, this test hits another `NPE` after fixing the issue above as following:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:191)
	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:180)
	at java.base/com.ibm.tools.attach.target.AttachHandler.initializeAttachAPI(AttachHandler.java:131)
Caused by: java.lang.NullPointerException
	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:632)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/java.lang.Class.cacheField(Class.java:3950)
	at java.base/java.lang.Class.getDeclaredField(Class.java:901)
	at java.base/java.lang.Class.getEnumVars(Class.java:2906)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:2969)
	at java.base/java.lang.Access.getEnumConstantsShared(Access.java:91)
	at java.base/java.util.EnumSet.getUniverse(EnumSet.java:406)
	at java.base/java.util.EnumSet.noneOf(EnumSet.java:109)
	at java.base/java.util.EnumSet.of(EnumSet.java:283)
	at java.base/com.ibm.tools.attach.target.IPC.<clinit>(IPC.java:65)
```
This is due to the field `jdk.internal.reflect.ReflectionFactory.langReflectAccess` hasn't been initialized yet.
The code snippet in question `Method root = langReflectAccess.getRoot(method);` should be `Method root = langReflectAccess().getRoot(method);` just like https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/ReflectionFactory.java#L281.
 
The code to be fixed are as following:
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/ReflectionFactory.java#L178
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/ReflectionFactory.java#L200 
https://github.com/ibmruntimes/openj9-openjdk-jdk/blob/openj9/src/java.base/share/classes/jdk/internal/reflect/ReflectionFactory.java#L236

Requested `JCL` team to raise an `OpenJDK` bug against streams `head`, `jdk12` and `jdk11`.

**Comment by pshipton** [comment] 2019-01-30 17:04
Rather than changing the code not to use a lambda, can we do something to cause langReflectAccess to be initialized earlier in bootstrap? i.e. call `Modifier.isPublic(Modifier.PUBLIC);` in OpenJ9 bootstrap?

**Comment by JasonFengJ9** [comment] 2019-01-30 19:08
@pshipton Removal of `lambda` expression from `jdk.internal.loader.BuiltinClassLoader` OpenJ9 shared classes code is to avoid `null Module` object returned from `sun/util/logging/PlatformLogger.class.getModule()` as per https://github.com/eclipse/openj9/issues/3399#issuecomment-459004840.

 `null langReflectAccess` issue only shows up when the issue above has been fixed.

**Comment by pshipton** [comment] 2019-01-30 21:24
Is there a stack trace for the PlatformLogger.class.getModule() NPE?

**Comment by JasonFengJ9** [comment] 2019-01-30 21:32
Here it is (from this PR description):
```
java/lang/NullPointerException
	at java/util/Objects.requireNonNull (java.base@9/Objects.java:221)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.<init> (java.base@9/LazyLoggers.java:126)
	at jdk/internal/logger/LazyLoggers$LazyLoggerAccessor.makeAccessor (java.base@9/LazyLoggers.java:293)
	at jdk/internal/logger/LazyLoggers$JdkLazyLogger.<init> (java.base@9/LazyLoggers.java:371)
	at jdk/internal/logger/LazyLoggers.getLazyLogger (java.base@9/LazyLoggers.java:441)
	at sun/util/logging/PlatformLogger.getLogger (java.base@9/PlatformLogger.java:297)
```

**Comment by pshipton** [comment] 2019-01-31 23:10
All the changes are merged, can this be closed now?

**Comment by JasonFengJ9** [comment] 2019-02-01 00:15
Yes, I believe so.

@ben-walsh, could you give the test another spin?

**Comment by pshipton** [comment] 2019-02-01 02:41
I'll close it, and we can reopen or create a new issue if a problem still exists.

**Closed by pshipton** 2019-02-01 02:41 UTC
Labels: test excluded, test failure

**Comment by ben-walsh** [comment] 2019-02-11 15:46
Job submitted - https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1040

**Comment by ben-walsh** [comment] 2019-02-12 15:37
[consoleText.txt](https://github.com/eclipse/openj9/files/2856458/consoleText.txt) from job shows 100% pass rate. De-excluding test accordingly.

**Comment by smlambert** [comment] 2019-02-12 17:30
re-included: https://github.com/AdoptOpenJDK/openjdk-tests/pull/886
