### ISSUE TITLE
zos_390-64 SE80_GIT cmdLineTester_fieldwatchtests_0 fw001-[1, 4] failures

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#6324] opened 2019-07-03 16:20 UTC
Failure link
------------
```
[zos_390-64] SE80_GIT cmdLineTester_fieldwatchtests_0
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 8.0.6.0 - pmz6480sr6-20190627_04(SR6))
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20190630_421310 (JIT enabled, AOT enabled)
OpenJ9   - 609e59a
OMR      - 0742e2a
IBM      - 3791562)
JCL - 20190626_01 based on Oracle jdk8u221-b79
```

Optional info
-------------

- intermittent failure (no): 
- new test [1]:  

[1] https://github.ibm.com/runtimes/openj9/commit/8bf50f502d0c5e0631aa7b9891f95e2126e78f61

Failure output
--------------

```
"/j9vm/ebcdic/builds/bld_421310/sdk/mz6480/jre/bin/java" -Xnocompressedrefs  -Xdump  -XX:+JITInlineWatches -Xjit:disableAsyncCompilation,inhibitRecompilation,dontInline={*jitme*},disableSuffixLogs,{*jitme*}(count=0,traceFull,traceCG,log=unresolvedTrace.log) -agentlib:jvmtitest=test:fw001 -cp "/j9vm/ebcdic/builds/bld_421310/jvmtest/test/SE80/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner

---TEST RESULTS---
Number of PASSED tests: 2 out of 6
Number of FAILED tests: 4 out of 6

---SUMMARY OF FAILED TESTS---
fw001-1
fw001-2
fw001-3
fw001-4
-----------------------------

```

fyi: @dchopra001

**Comment by dchopra001** [comment] 2019-07-03 16:28
Taking a look at this currently.

**Comment by dchopra001** [comment] 2019-07-03 22:46
One of the crashes will be fixed by: https://github.com/eclipse/omr/pull/4100. Similar checks exist elsewhere in this evaluator. I'm not sure how this escaped tests on linux.

There are other issues in the test related to fieldwatches not being reported. I'm still investigating those.

**Comment by fjeremic** [comment] 2019-07-03 23:11
> One of the crashes will be fixed by: [eclipse/omr#4100](https://github.com/eclipse/omr/pull/4100). Similar checks exist elsewhere in this evaluator. I'm not sure how this escaped tests on linux.

Just a wild guess based on the fact that this PR is for a NULLCHK evaluator. On z/OS we have resumable traps disabled so we need to perform explicit null checking whereas on Linux we use implict traps on the load instructions. I suspect this hides the bug on Linux. You can test by disabling resumable traps on Linux and see if we can reproduce.

**Comment by dchopra001** [comment] 2019-07-04 16:09
> Just a wild guess based on the fact that this PR is for a NULLCHK evaluator. On z/OS we have resumable traps disabled so we need to perform explicit null checking whereas on Linux we use implict traps on the load instructions

That's a good point. We can only end up at this code if resumable traps are not enabled. 

On linux we will always take this forward path:
https://github.com/eclipse/omr/blob/6dc0df4b587c4d651a3104d44c7308093067857b/compiler/z/codegen/ControlFlowEvaluator.cpp#L2171

**Comment by fjeremic** [comment] 2019-07-04 16:18
eclipse/omr#4100 has now been merged. This is no longer a problem. Closing. Please reopen if you see another occurrence.

**Comment by dchopra001** [comment] 2019-07-04 21:18
Update:

I have a fix for the other issue as well now. Going to do a bit more testing today to make sure everything is good and then will open a PR tonight.

**Comment by pshipton** [comment] 2020-04-03 05:42
I assume this was resolved since the failures no longer occur.

**Closed by pshipton** 2020-04-03 05:42 UTC
Labels: arch:z, os:zos, test failure
