### ISSUE TITLE
JDK11 JIT Server : NPE at jdk/internal/misc/InnocuousThread.<clinit> (java.base@9/InnocuousThread.java:178)

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#9846] opened 2020-06-11 00:00 UTC
Failure link
------------

From an internal build `Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Nightly_testList_1/11`:
```
03:02:02  openjdk version "11.0.8-internal" 2020-07-14
03:02:02  OpenJDK Runtime Environment (build 11.0.8-internal+0-adhoc.jenkins.BuildJDK11x86-64linuxjitNightly)
03:02:02  Eclipse OpenJ9 VM (build ibm_sdk-31dd6df6f8, JRE 11 Linux amd64-64-Bit Compressed References 20200607_104 (JIT enabled, AOT enabled)
03:02:02  OpenJ9   - 31dd6df6f8
03:02:02  OMR      - a29414f42
03:02:02  JCL      - 72bf42d051a based on jdk-11.0.8+6)
```

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
=============================================== 
Running test cmdLineTester_jvmtitests_7 ... 
===============================================


Testing: emex001
Test start time: 2020/06/08 03:40:34 Eastern Standard Time
Running command: "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Nightly_testList_1/openjdkbinary/j2sdk-image/bin/java" -XX:+UseJITServer -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump    -agentlib:jvmtitest=test:emex001 -cp "/home/jenkins/workspace/Test_openjdk11_j9_sanity.functional_x86-64_linux_jit_Nightly_testList_1/openjdk-tests/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 3 milliseconds
Time spent executing: 339 milliseconds
Test result: FAILED
Output from test:
 [ERR] JITServer is currently a technology preview. Its use is not yet supported
 [ERR] Exception in thread "main" java/lang/Error: java.lang.NullPointerException
 [ERR] 	at jdk/internal/misc/InnocuousThread.<clinit> (java.base@9/InnocuousThread.java:178)
 [ERR] 	at jdk/internal/ref/CleanerFactory$1$1.run (java.base@9/CleanerFactory.java:48)
 [ERR] 	at jdk/internal/ref/CleanerFactory$1$1.run (java.base@9/CleanerFactory.java:45)
 [ERR] 	at java/security/AccessController.doPrivileged (java.base@9/AccessController.java:678)
 [ERR] 	at jdk/internal/ref/CleanerFactory$1.newThread (java.base@9/CleanerFactory.java:45)
 [ERR] 	at jdk/internal/ref/CleanerImpl.start (java.base@9/CleanerImpl.java:116)
 [ERR] 	at java/lang/ref/Cleaner.create (java.base@9/Cleaner.java:203)
 [ERR] 	at jdk/internal/ref/CleanerFactory.<clinit> (java.base@9/CleanerFactory.java:42)
 [ERR] 	at sun/nio/fs/NativeBuffer.<init> (java.base@9/NativeBuffer.java:60)
 [ERR] 	at sun/nio/fs/NativeBuffers.allocNativeBuffer (java.base@9/NativeBuffers.java:63)
 [ERR] 	at sun/nio/fs/UnixNativeDispatcher.copyToNativeBuffer (java.base@9/UnixNativeDispatcher.java:44)
 [ERR] 	at sun/nio/fs/UnixNativeDispatcher.stat (java.base@9/UnixNativeDispatcher.java:316)
 [ERR] 	at sun/nio/fs/UnixFileSystemProvider.isRegularFile (java.base@9/UnixFileSystemProvider.java:518)
 [ERR] 	at java/nio/file/Files.isRegularFile (java.base@9/Files.java:2273)
 [ERR] 	at jdk/internal/loader/BuiltinClassLoader.setJimageURL (java.base@9/BuiltinClassLoader.java:270)
 [ERR] 	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.convertJrtToFileURL (java.base@9/BuiltinClassLoader.java:309)
 [ERR] 	at jdk/internal/loader/BuiltinClassLoader$LoadedModule.<init> (java.base@9/BuiltinClassLoader.java:299)
 [ERR] 	at jdk/internal/loader/BuiltinClassLoader.loadModule (java.base@9/BuiltinClassLoader.java:367)
 [ERR] 	at jdk/internal/loader/BootLoader.loadModule (java.base@9/BootLoader.java:109)
 [ERR] 	at jdk/internal/module/ModuleBootstrap.boot (java.base@9/ModuleBootstrap.java:233)
 [ERR] 	at java/lang/ClassLoader.initializeClassLoaders (java.base@9/ClassLoader.java:211)
 [ERR] 	at java/lang/Thread.initialize (java.base@9/Thread.java:430)
 [ERR] 	at java/lang/Thread.<init> (java.base@9/Thread.java:155)
>> Success condition was not found: [Return code: 0]
```

For example, to rebuild the failed tests in <Jenkins URL>=https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder, use the following links:
05:09:54  https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?JDK_VERSION=11&JDK_IMPL=openj9&BUILD_LIST=functional&PLATFORM=x86-64_linux&TARGET=cmdLineTester_jvmtitests_7

**Comment by pshipton** [comment] 2020-06-11 00:40
@mpirvu

**Comment by a7ehuo** [comment] 2020-06-11 21:20
50x [grinder 8314](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/8341/tapResults/) - passed. 
30x local runs of JDK11 `cmdLineTester_jvmtitests_5/7/8` - passed. 

Likely this is a very intermittent issue.  The test failed with `emex001` which is executed in `cmdLineTester_jvmtitests_5`, `cmdLineTester_jvmtitests_7` and `cmdLineTester_jvmtitests_8`. 
- passed in`cmdLineTester_jvmtitests_5` and `cmdLineTester_jvmtitests_8`.
- failed in `cmdLineTester_jvmtitests_7`.  

`cmdLineTester_jvmtitests_7` runs with `-XX:+UseCompressedOops`  and `-Xgcpolicy:balanced`. However other tests such as `emeng001` that runs with `-XX:+UseCompressedOops`  and `-Xgcpolicy:balanced` also passed.

**Comment by EmanElsaban** [comment] 2020-11-06 18:49
This issue seems to be related to issue: #9024. @mpirvu @dmitry-ten

**Comment by dmitry-ten** [comment] 2020-11-06 18:50
Yes, it appears to be the same bug that should be fixed by https://github.com/eclipse/omr/pull/5658.

**Comment by EmanElsaban** [comment] 2020-11-09 20:30
Ran the grinder 200 times.All 200 times failed: https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/11937/.

Console Output:
```
 19:49:29  Testing: gaste001_multiple
19:49:29  Test start time: 2020/11/06 16:49:29 Pacific Standard Time
19:49:29  java.lang.NullPointerException
19:49:29  	at java.base/java.lang.String.decompressedArrayCopy(String.java)
19:49:29  	at java.base/java.lang.String.getBytes(String.java:107)
19:49:29  	at java.base/java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1667)
19:49:29  	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
19:49:29  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:174)
19:49:29  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:85)
19:49:29  	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:573)
19:49:29  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:204)
19:49:29  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:85)
19:49:29  	at java.base/com.ibm.oti.util.Util.appendTo(Util.java:225)
19:49:29  	at java.base/com.ibm.oti.util.Util.printStackTraceElement(Util.java:303)
19:49:29  	at java.base/java.lang.StackTraceElement.toString(StackTraceElement.java:232)
19:49:29  	at java.base/java.lang.String.valueOf(String.java:2971)
19:49:29  	at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
19:49:29  	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:584)
19:49:29  	at java.base/java.lang.Throwable.printStackTraceHelper(Throwable.java:338)
19:49:29  	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:318)
19:49:29  	at TestSuite.printStackTrace(TestSuite.java:477)
19:49:29  	at TestSuite.runTest(TestSuite.java:104)
19:49:29  	at TestIterator.addTest(TestIterator.java:84)
19:49:29  	at TestConfigParser$TestConfigDocumentHandler.xmlEndElement(TestConfigParser.java:309)
19:49:29  	at com.oti.j9.exclude.XMLParser._scan_element_close(XMLParser.java:370)
19:49:29  	at com.oti.j9.exclude.XMLParser._scan_element_or_instruction(XMLParser.java:391)
19:49:29  	at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:442)
19:49:29  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:470)
19:49:29  	at com.oti.j9.exclude.XMLParser.parse(XMLParser.java:459)Exception in thread "main" java.lang.ExceptionInInitializerError
19:49:29  	at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:185)
19:49:29  	at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:174)
19:49:29  	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:872)
19:49:29  	at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
19:49:29  	at java.base/java.lang.Thread.uncaughtException(Thread.java:1345)
19:49:29  Caused by: java.lang.NullPointerException
19:49:29  	at java.base/java.lang.String.decompressedArrayCopy(String.java)
19:49:29  	at java.base/java.lang.String.<init>(String.java:749)
19:49:29  	at java.base/java.util.Properties.loadConvert(Properties.java:644)
19:49:29  	at java.base/java.util.Properties.load0(Properties.java:452)
19:49:29  	at java.base/java.util.Properties.load(Properties.java:404)
19:49:29  	at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:202)
19:49:29  	at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
19:49:29  	at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
19:49:29  	at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
19:49:29  	... 3 more
19:49:29  
19:49:29  cmdLineTester_jvmtitests_7_FAILED
```

**Comment by EmanElsaban** [comment] 2020-11-09 21:52
Reproduced it locally. It failed the first time I ran the test.

output:
```
Testing: gaste001_multiple
Test start time: 2020/11/09 13:44:55 Pacific Standard Time
Running command: "/root/openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/images/jdk/bin/java" -XX:+UseJITServer -XX:+UseCompressedOops -Xjit -Xgcpolicy:balanced  -Xdump    -Xjit:count=0 -agentlib:jvmtitest=test:gaste001 -agentlib:jvmtitest=test:gaste001 -cp "/root/openj9-openjdk-jdk11/openj9/test/TKG/../../jvmtest/functional/cmdLineTests/jvmtitests/jvmtitest.jar" com.ibm.jvmti.tests.util.TestRunner
Time spent starting: 2 milliseconds
Time spent executing: 2193 milliseconds
Test result: PASSED
java.lang.NullPointerException
        at java.base/java.lang.String.decompressedArrayCopy(String.java)
        at java.base/java.lang.String.getCharsNoBoundChecks(String.java:1866)
        at java.base/java.lang.String.getChars(String.java:1853)
        at com.oti.j9.exclude.XMLStringBuffer.append(XMLStringBuffer.java:77)
        at com.oti.j9.exclude.XMLStringBuffer.append(XMLStringBuffer.java:64)
        at com.oti.j9.exclude.XMLParser._scan_comment(XMLParser.java:323)
        at com.oti.j9.exclude.XMLParser._scan_doctype_or_comment(XMLParser.java:353)
        at com.oti.j9.exclude.XMLParser._scan_element_or_instruction(XMLParser.java:386)
        at com.oti.j9.exclude.XMLParser.parseXML(XMLParser.java:442)
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NullPointerException
        at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.open(SystemModuleFinders.java:448)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:434)
        at java.base/jdk.internal.loader.BootLoader.findResourceAsStream(BootLoader.java:146)
        at java.base/java.lang.Module.getResourceAsStream(Module.java:1569)
        at java.base/com.ibm.oti.vm.MsgHelp.loadMessages(MsgHelp.java:185)
        at java.base/com.ibm.oti.util.PriviAction.run(PriviAction.java:172)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:678)
        at java.base/com.ibm.oti.util.Msg.<clinit>(Msg.java:63)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:872)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
        at java.base/java.lang.Thread.uncaughtException(Thread.java:1345)
Caused by: java.lang.NullPointerException
        at java.base/com.ibm.jit.JITHelpers.getCharFromArrayByIndex(JITHelpers.java:534)
        at java.base/java.lang.String.lastIndexOf(String.java:2136)
        at java.base/java.lang.String.lastIndexOf(String.java:2094)
        at java.base/java.lang.Class.getNonArrayClassPackageName(Class.java:1958)
        at java.base/java.lang.Class.getPackageName(Class.java:1991)
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassModuleVisibility(MethodHandles.java:721)
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:504)
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:409)
        at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:358)
        at java.base/java.lang.invoke.MethodHandles$Lookup.revealDirect(MethodHandles.java:1386)
        at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:133)
        at java.base/java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:159)
        at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:324)
        at java.base/java.lang.invoke.MethodHandleResolver.invokeBsm(MethodHandleResolver.java:182)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:238)
        ... 11 more
cmdLineTester_jvmtitests_7_FAILED
```
Ran 30 iterations, it failed in the first iteration:
```
Testing: gaste001_multiple
Test start time: 2020/11/09 13:48:24 Pacific Standard Time
Exception in thread "main" java.lang.ExceptionInInitializerError
        at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:185)
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:174)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:872)
        at java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:866)
        at java.base/java.lang.Thread.uncaughtException(Thread.java:1345)
Caused by: java.lang.NullPointerException
        at java.base/java.lang.String.decompressedArrayCopy(String.java)
        at java.base/java.lang.String.<init>(String.java:1001)
        at java.base/java.lang.invoke.MethodTypeHelper.getBytecodeStringName(MethodTypeHelper.java:162)
        at java.base/java.lang.invoke.MethodType.createMethodDescriptorString(MethodType.java:790)
        at java.base/java.lang.invoke.MethodType.intern(MethodType.java:602)
        at java.base/java.lang.invoke.MethodType.methodType(MethodType.java:556)
        at java.base/java.lang.invoke.MethodType.insertParameterTypes(MethodType.java:497)
        at java.base/java.lang.invoke.DirectHandle.directMethodType(DirectHandle.java:110)
        at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:47)
        at java.base/java.lang.invoke.DirectHandle.<init>(DirectHandle.java:43)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecialImpl(MethodHandles.java:606)
        at java.base/java.lang.invoke.MethodHandles$Lookup.findSpecial(MethodHandles.java:574)
        at java.base/java.lang.invoke.MethodHandleResolver.sendResolveMethodHandle(MethodHandleResolver.java:318)
        at java.base/java.lang.invoke.MethodHandleResolver.getCPMethodHandleAt(Native Method)
        at java.base/java.lang.invoke.MethodHandleResolver.getAdditionalBsmArg(MethodHandleResolver.java:464)
        at java.base/java.lang.invoke.MethodHandleResolver.resolveInvokeDynamic(MethodHandleResolver.java:229)
        at java.base/jdk.internal.module.SystemModuleFinders$SystemModuleReader.open(SystemModuleFinders.java:448)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceAsStream(BuiltinClassLoader.java:434)java/lang/ExceptionInInitializerError
        at java/lang/J9VMInternals.ensureError (java.base@9/J9VMInternals.java:185)
        at java/lang/J9VMInternals.recordInitializationFailure (java.base@9/J9VMInternals.java:174)
        at java/lang/ThreadGroup.uncaughtException (java.base@9/ThreadGroup.java:872)
        at java/lang/ThreadGroup.uncaughtException (java.base@9/ThreadGroup.java:866)
        at java/lang/Thread.uncaughtException (java.base@9/Thread.java:1345)
java/lang/NullPointerException
        at java/lang/String.decompressedArrayCopy (java.base@9/String.java:4294967295)
        at java/lang/String.<init> (java.base@9/String.java:1001)
        at java/lang/invoke/MethodTypeHelper.getBytecodeStringName (java.base@9/MethodTypeHelper.java:162)
        at java/lang/invoke/MethodType.createMethodDescriptorString (java.base@9/MethodType.java:790)
        at java/lang/invoke/MethodType.intern (java.base@9/MethodType.java:602)
        at java/lang/invoke/MethodType.methodType (java.base@9/MethodType.java:556)
        at java/lang/invoke/MethodType.insertParameterTypes (java.base@9/MethodType.java:497)
        at java/lang/invoke/DirectHandle.directMethodType (java.base@9/DirectHandle.java:110)
        at java/lang/invoke/DirectHandle.<init> (java.base@9/DirectHandle.java:47)
        at java/lang/invoke/DirectHandle.<init> (java.base@9/DirectHandle.java:43)
        at java/lang/invoke/MethodHandles$Lookup.findSpecialImpl (java.base@9/MethodHandles.java:606)
        at java/lang/invoke/MethodHandles$Lookup.findSpecial (java.base@9/MethodHandles.java:574)
        at java/lang/invoke/MethodHandleResolver.sendResolveMethodHandle (java.base@9/MethodHandleResolver.java:318)
        at java/lang/invoke/MethodHandleResolver.getCPMethodHandleAt (java.base@9/NativeMethod:4294967295)
        at java/lang/invoke/MethodHandleResolver.getAdditionalBsmArg (java.base@9/MethodHandleResolver.java:464)
        at java/lang/invoke/MethodHandleResolver.resolveInvokeDynamic (java.base@9/MethodHandleResolver.java:229)
        at jdk/internal/module/SystemModuleFinders$SystemModuleReader.open (java.base@9/SystemModuleFinders.java:448)
        at jdk/internal/loader/BuiltinClassLoader.findResourceAsStream (java.base@9/BuiltinClassLoader.java:434)
        at jdk/internal/loader/BootLoader.findResourceAsStream (java.base@9/BootLoader.java:146)
        at java/lang/Module.getResourceAsStream (java.base@9/Module.java:1569)
        at com/ibm/oti/vm/MsgHelp.loadMessages (java.base@9/MsgHelp.java:185)
        at com/ibm/oti/util/PriviAction.run (java.base@9/PriviAction.java:172)
        at java/security/AccessController.doPrivileged (java.base@9/AccessController.java:678)
        at com/ibm/oti/util/Msg.<clinit> (java.base@9/Msg.java:63)
        at java/lang/ThreadGroup.uncaughtException (java.base@9/ThreadGroup.java:872)
        at java/lang/ThreadGroup.uncaughtException (java.base@9/ThreadGroup.java:866)
        at java/lang/Thread.uncaughtException (java.base@9/Thread.java:1345)

cmdLineTester_jvmtitests_7_FAILED(ITER_1)


cmdLineTester_jvmtitests_7_FAILED
```

**Comment by dmitry-ten** [comment] 2020-11-09 23:02
Yeah, I've been looking into this today.
Note that these failures are caused by  eclipse/omr#5658. 
I heavily suspect it's due to recompilation counter address being incorrect, since methods throwing NPE contain recompilation counter, and disabling recompilation makes the test pass. I guess the address was computed correctly when it was using relative addressing. Need to determine how it's done for AOT to fix.

**Comment by dmitry-ten** [comment] 2020-11-09 23:18
Actually, disregard the previous comment, recompilation counters always require address load instruction and are relocated, so that can't be a problem.

**Comment by dmitry-ten** [comment] 2020-12-03 16:36
@mpirvu 200 [tests](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/12372/) passed, this should be closed.

**Comment by mpirvu** [comment] 2020-12-03 17:07
Fixed by https://github.com/eclipse/omr/pull/5658
Closing based on the previous message.

**Closed by mpirvu** 2020-12-03 17:07 UTC
Labels: comp:jitserver, test failure
