### ISSUE TITLE
JDK15 java/util/StringJoiner/StringJoinerTest.java : java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by JasonFengJ9** [eclipse/openj9#10631] opened 2020-09-17 11:53 UTC
Failure link
------------

https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/51/consoleFull
win2012r2-x86-4
For example, to rebuild the failed tests in <Jenkins URL>=https://ci.eclipse.org/openj9/job/Grinder, use the following links:
05:03:22  https://ci.eclipse.org/openj9/job/Grinder/parambuild/?JDK_VERSION=15&JDK_IMPL=openj9&BUILD_LIST=openjdk&PLATFORM=x86-64_windows&TARGET=jdk_lang_j9_0

Optional info
-------------

Failure output (captured from console output)
---------------------------------------------

```
04:55:33  --------------------------------------------------
04:55:33  TEST: java/util/StringJoiner/StringJoinerTest.java
04:55:33  TEST JDK: C:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdkbinary\j2sdk-image
04:55:33  
04:55:33  STDERR:
04:55:33  JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2020/09/17 03:55:18 - please wait.
04:55:33  JVMDUMP032I JVM requested Java dump using 'C:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16003311963713\jdk_util_j9_0\work\scratch\3\javacore.20200917.035518.5088.0001.txt' in response to an event
04:55:33  JVMDUMP010I Java dump written to C:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16003311963713\jdk_util_j9_0\work\scratch\3\javacore.20200917.035518.5088.0001.txt
04:55:33  JVMDUMP032I JVM requested Snap dump using 'C:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16003311963713\jdk_util_j9_0\work\scratch\3\Snap.20200917.035518.5088.0002.trc' in response to an event
04:55:33  JVMDUMP010I Snap dump written to C:\Users\jenkins\workspace\Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly\openjdk-tests\TKG\test_output_16003311963713\jdk_util_j9_0\work\scratch\3\Snap.20200917.035518.5088.0002.trc
04:55:33  JVMDUMP013I Processed dump event "systhrow", detail "java/lang/OutOfMemoryError".
04:55:33  org.testng.TestNGException: 
04:55:33  An error occurred while instantiating class StringJoinerTest: Java heap space
04:55:33  	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:394)
04:55:33  	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:295)
04:55:33  	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:118)
04:55:33  	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:183)
04:55:33  	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:128)
04:55:33  	at org.testng.TestRunner.initMethods(TestRunner.java:415)
04:55:33  	at org.testng.TestRunner.init(TestRunner.java:241)
04:55:33  	at org.testng.TestRunner.init(TestRunner.java:211)
04:55:33  	at org.testng.TestRunner.<init>(TestRunner.java:158)
04:55:33  	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:546)
04:55:33  	at org.testng.SuiteRunner.init(SuiteRunner.java:159)
04:55:33  	at org.testng.SuiteRunner.<init>(SuiteRunner.java:114)
04:55:33  	at org.testng.TestNG.createSuiteRunner(TestNG.java:1260)
04:55:33  	at org.testng.TestNG.createSuiteRunners(TestNG.java:1247)
04:55:33  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
04:55:33  	at org.testng.TestNG.run(TestNG.java:1018)
04:55:33  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:94)
04:55:33  	at com.sun.javatest.regtest.agent.TestNGRunner.main(TestNGRunner.java:54)
04:55:33  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:55:33  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
04:55:33  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:55:33  	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
04:55:33  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
04:55:33  	at java.base/java.lang.Thread.run(Thread.java:845)
04:55:33  Caused by: java.lang.OutOfMemoryError: Java heap space
04:55:33  	at java.base/java.lang.String.repeat(String.java:3959)
04:55:33  	at StringJoinerTest.<clinit>(StringJoinerTest.java:58)
04:55:33  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
04:55:33  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
04:55:33  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
04:55:33  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
04:55:33  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
04:55:33  	at org.testng.internal.ObjectFactoryImpl.newInstance(ObjectFactoryImpl.java:29)
04:55:33  	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:382)
04:55:33  	... 23 more
04:55:33  
04:55:33  JavaTest Message: Test threw exception: org.testng.TestNGException: 
04:55:33  An error occurred while instantiating class StringJoinerTest: Java heap space
04:55:33  JavaTest Message: shutting down test
04:55:33  
04:55:33  STATUS:Failed.`main' threw exception: org.testng.TestNGException: An error occurred while instantiating class StringJoinerTest: Java heap space
```

**Comment by pshipton** [comment] 2020-09-17 18:10
@jonoommen @amicic could this be related to https://github.com/eclipse/omr/pull/5377 ?

**Comment by amicic** [comment] 2020-09-17 18:15
not so likely. most of code (GC anyway) is inactive/disabled.

**Comment by pshipton** [comment] 2020-09-17 19:48
I suspect a machine problem https://github.com/eclipse/openj9/issues/10639

**Comment by JasonFengJ9** [comment] 2020-09-18 11:55
Another occurrence at `win2012r2-x86-3`
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/52/consoleFull
```
02:48:02  Caused by: java.lang.OutOfMemoryError: Java heap space
02:48:02  	at java.base/java.lang.String.repeat(String.java:3959)
02:48:02  	at StringJoinerTest.<clinit>(StringJoinerTest.java:58)
02:48:02  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by pshipton** [comment] 2020-09-18 14:57
So likely not a machine problem then. This is the test that was failing until we recently started running it with `-XX:+CompactStrings`. https://github.com/eclipse/openj9/issues/10149

@dmitripivkine can you take the first look pls to see if there is a real problem here.

**Comment by pshipton** [comment] 2020-09-18 15:03
@jdekonin can you pls check the swap space on the machine is big enough to accommodate all the memory. I saw some message about insufficient swap space recently in some other Windows failure.

**Comment by jdekonin** [comment] 2020-09-18 18:12
8G ram, 2G swap is how all the windows machines are configured by default from the ibmcloud.  The playbook doesn't have any preset or suggested swapfile size for windows, but if there is something preferred/suggested we can make that change.

**Comment by pshipton** [comment] 2020-09-18 19:26
"The default automatic behavior is to have a minimum [swap] size 1.5 times the amount of actual RAM."

Although I'm fine with a swap file which is the same size as the available RAM. I suspect the 2G size has been causing problems recently.

**Comment by pshipton** [comment] 2020-09-23 19:27
Another one
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/57
win2012-x86-6
```
1STGCHTYPE     GC History  
3STHSTTYPE     05:35:42:277797671 GMT j9mm.101 -   J9AllocateIndexableObject() returning NULL! 2147483648 bytes requested for object of class 0000000000049600 from memory space 'Generational' id=0000003DFFD91640 
3STHSTTYPE     05:35:42:277731355 GMT j9mm.134 -   Allocation failure end: newspace=1771936/3014656 oldspace=5202368/6291456 loa=0/0 
3STHSTTYPE     05:35:42:277688071 GMT j9mm.470 -   Allocation failure cycle end: newspace=1771936/3014656 oldspace=5202368/6291456 loa=0/0 
3STHSTTYPE     05:35:42:277596717 GMT j9mm.475 -   GlobalGC end: workstackoverflow=0 overflowcount=0 memory=6974304/9306112 
3STHSTTYPE     05:35:42:277452395 GMT j9mm.506 - * Failed to commit memory: address=00000007005F0000, size=3063152640 

1STHEAPTYPE    Object Memory
NULL           id                 start              end                size               space/region
1STHEAPSPACE   0x0000003DFFD91640         --                 --                 --         Generational 
1STHEAPREGION  0x0000003DFFD69190 0x00000006FFFF0000 0x00000007005F0000 0x0000000000600000 Generational/Tenured Region 
1STHEAPREGION  0x0000003DFFD68FD0 0x00000007FFD10000 0x00000007FFF00000 0x00000000001F0000 Generational/Nursery Region 
1STHEAPREGION  0x0000003DFFD69B30 0x00000007FFF00000 0x00000007FFFF0000 0x00000000000F0000 Generational/Nursery Region 
NULL
1STHEAPTOTAL   Total memory:                     9306112 (0x00000000008E0000)
1STHEAPINUSE   Total memory in use:              2352288 (0x000000000023E4A0)
1STHEAPFREE    Total memory free:                6953824 (0x00000000006A1B60)

1MEMUSER       JRE: 5,240,530,008 bytes / 5217 allocations
1MEMUSER       |
2MEMUSER       +--VM: 4,933,026,352 bytes / 4865 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Classes: 330,342,384 bytes / 385 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Shared Class Cache: 314,572,800 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 15,769,584 bytes / 384 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Modules: 504,920 bytes / 2004 allocations
2MEMUSER       |  |
3MEMUSER       |  +--Memory Manager (GC): 4,380,744,608 bytes / 552 allocations
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Java Heap: 4,295,028,736 bytes / 1 allocation
3MEMUSER       |  |  |
4MEMUSER       |  |  +--Other: 85,715,872 bytes / 551 allocations
```

`Failed to commit memory: address=00000007005F0000, size=3063152640`
as per https://github.com/eclipse/openj9/issues/10650#issuecomment-696333582 we now have 8G swap space on this machine. Not sure what is going on, we should be able to allocate 3G on a 8G machine, in particular with 8G swap.

I wonder if the JVM supporting jenkins is taking too much resource.

@jdekonin can someone log into the machine and see if there are processes left running, and use task manager to look at what is consuming the memory.

**Comment by jdekonin** [comment] 2020-09-24 16:03
@pshipton I had looked but the systems appears fine.  No extra processes.  Maybe checking closer to the time of the failure would give a different picture.

**Comment by pshipton** [comment] 2020-09-24 18:01
@jdekonin what about memory usage on the machine?

**Comment by jdekonin** [comment] 2020-09-24 19:18
It was hovering around 1.2G in use when it was idle.  I did notice something odd though, the system has only been up for 17 hours, so its rebooted since that test ran.  I wasn't able to determine the cause for the reboot though.  It wasn't windows update as that is off and updates are performed manually.

**Comment by pshipton** [comment] 2020-09-24 21:49
Likely there will be another occurrence, which I'll record here when it occurs so we can look.

**Comment by pshipton** [comment] 2020-09-28 21:48
Another one, on win2012-x86-6
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Release/6

**Comment by pshipton** [comment] 2020-09-30 13:27
Another on win2012-x86-6
https://ci.eclipse.org/openj9/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows_Nightly/64

**Comment by JasonFengJ9** [comment] 2020-10-20 21:20
Another failure at JDK15 `java/util/StringJoiner/StringJoinerTest.java` with `Segmentation error vmState=0x00060000` from an internal build `Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/95`
```
22:51:27  --------------------------------------------------
22:51:27  TEST: java/util/StringJoiner/StringJoinerTest.java
22:51:27  TEST JDK: /home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image
22:51:27  
22:51:27  STDERR:
22:51:27  Unhandled exception
22:51:27  Type=Segmentation error vmState=0x00060000
22:51:27  J9Generic_Signal_Number=00000018 Signal_Number=0000000b Error_Value=00000000 Signal_Code=00000003
22:51:27  Handler1=00007824232ED3D0 Handler2=00007824231435C0
22:51:27  R0=0000782423366280 R1=0000782423CBD430 R2=0000782423416F00 R3=0000000000000001
22:51:27  R4=000078241C1E0740 R5=3830282018100801 R6=000078241C1C37A8 R7=01C1814100C08040
22:51:27  R8=7870686058504840 R9=C1814100C0804000 R10=0000000000000020 R11=0000782423CBD368
22:51:27  R12=0000000042022224 R13=0000782423CC6900 R14=000078241C1C39D8 R15=00000000000000A7
22:51:27  R16=00007824234142D8 R17=0000000000000000 R18=000078241C1C1DB0 R19=FFFFFFFFFFFFFF7F
22:51:27  R20=FFFFFFFFFFFFFFFF R21=00007823FBFD0614 R22=000078241C1C39E0 R23=0000000000000001
22:51:27  R24=0000000000000001 R25=00007823FBFD0674 R26=000078241C1C39E0 R27=000078241C1C39B8
22:51:27  R28=000000000000002E R29=000000000000002B R30=0000000000000001 R31=000078241C1C2798
22:51:27  NIP=0000782423364C34 MSR=800000000280F033 ORIG_GPR3=000078242336628C CTR=0000782422CF5690
22:51:27  LINK=0000782423366280 XER=0000000000000000 CCR=0000000024022244 SOFTE=0000000000000001
22:51:27  TRAP=0000000000000380 DAR=C181B924DC9C77A8 dsisr=0000000040000000 RESULT=0000000000000000
22:51:27  FPR0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR1 405559e100000000 (f: 0.000000, d: 8.540436e+01)
22:51:27  FPR2 41e0000000000000 (f: 0.000000, d: 2.147484e+09)
22:51:27  FPR3 4030000000000000 (f: 0.000000, d: 1.600000e+01)
22:51:27  FPR4 3fe8000000000000 (f: 0.000000, d: 7.500000e-01)
22:51:27  FPR5 bfa01f0600000000 (f: 0.000000, d: -3.148669e-02)
22:51:27  FPR6 3f9a0ffc40000000 (f: 1073741824.000000, d: 2.545160e-02)
22:51:27  FPR7 3f453a01e0000000 (f: 3758096384.000000, d: 6.477842e-04)
22:51:27  FPR8 3fc46ba980000000 (f: 2147483648.000000, d: 1.595356e-01)
22:51:27  FPR9 4036000000000000 (f: 0.000000, d: 2.200000e+01)
22:51:27  FPR10 3fd84bf800000000 (f: 0.000000, d: 3.796368e-01)
22:51:27  FPR11 41cdcd6500000000 (f: 0.000000, d: 1.000000e+09)
22:51:27  FPR12 3830282018100800 (f: 403703808.000000, d: 4.748039e-38)
22:51:27  FPR13 bfb7440000000000 (f: 0.000000, d: -9.088135e-02)
22:51:27  FPR14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR16 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR17 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR18 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR19 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR20 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR21 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR22 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR23 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR24 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR25 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR26 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR27 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR28 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR29 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR30 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  FPR31 0000000000000000 (f: 0.000000, d: 0.000000e+00)
22:51:27  Module=/home/jenkins/workspace/Test_openjdk15_j9_sanity.openjdk_ppc64le_linux_Nightly/openjdkbinary/j2sdk-image/lib/compressedrefs/libj9vm29.so
22:51:27  Module_base_address=0000782423240000
22:51:27  Target=2_90_20201019_111 (Linux 4.15.0-66-generic)
22:51:27  CPU=ppc64le (64 logical CPUs) (0xff80f0000 RAM)
22:51:27  ----------- Stack Backtrace -----------
22:51:27  (0x0000782423364C34 [libj9vm29.so+0x124c34])
22:51:27  (0x0000782423366280 [libj9vm29.so+0x126280])
22:51:27  (0x0000782423276544 [libj9vm29.so+0x36544])
22:51:27  (0x0000782423260078 [libj9vm29.so+0x20078])
22:51:27  (0x0000782423321D6C [libj9vm29.so+0xe1d6c])
22:51:27  (0x00007824232D3BA8 [libj9vm29.so+0x93ba8])
22:51:27  (0x00007824232F2370 [libj9vm29.so+0xb2370])
22:51:27  (0x0000782423350A08 [libj9vm29.so+0x110a08])
22:51:27  (0x00007824231449C8 [libj9prt29.so+0x349c8])
22:51:27  (0x0000782423350ADC [libj9vm29.so+0x110adc])
22:51:27  (0x00007824232F4CB4 [libj9vm29.so+0xb4cb4])
22:51:27  (0x00007824232F1AA0 [libj9vm29.so+0xb1aa0])
22:51:27  (0x000078242403C5C0 [libjli.so+0xc5c0])
22:51:27  (0x0000782424041A88 [libjli.so+0x11a88])
22:51:27  (0x0000782423FF8040 [libpthread.so.0+0x8040])
22:51:27  clone+0x98 (0x0000782423F13BB0 [libc.so.6+0x123bb0])
22:51:27  ---------------------------------------
```

**Comment by pshipton** [comment] 2020-10-20 21:53
@JasonFengJ9 pls open a separate issue when the problem is different, even when the test might be the same. The original problem is OOM heap space, while the previous comment is a crash in the bytecode verifier (vmState=0x00060000).

**Comment by pshipton** [comment] 2020-10-20 21:56
The original OOM problem was resolved by fixing the machines, https://github.com/eclipse/openj9/issues/10650#issuecomment-704939166, I'm going to go ahead and close this one.

**Closed by pshipton** 2020-10-20 21:56 UTC
Labels: test failure
