### ISSUE TITLE
J9 JVMTI GetStackTrace 

### ISSUE THREAD

**Issue by NatiZel** [eclipse/openj9#1633] opened 2018-04-08 07:39 UTC
There is an issue getting the current thread stack trace from JVMTI using

`**jvmtiError (JNICALL *GetStackTrace) (jvmtiEnv* env, jthread thread, jint start_depth, jint max_frame_count, jvmtiFrameInfo* frame_buffer, jint* count_ptr); `

By Dan Heidinga, J9 (and now Eclipse OpenJ9) assumes that all invoke bytecodes are 3 bytes so that return bytecodes can unconditionally increment by 3 to get the next PC.  Since invokeinterface is defined as a 5 byte bytecode with two must be zero bytes, OpenJ9 uses the sequence "invokeinterface2 0 invokeinterface cpIndex1, cpIndex2" with invokeinterface2 acting as a 2 byte nop.

This is causing that for some frames, the method return  invalid frame locations, shifted by 2 bytes, for example:
when 'java/lang/reflect/Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;'  is on stack, frame location returned is 59, although we are looking for the 'invokeinterface' at location 57.
This issue is only happening when invokeinterface opcode is present, and it is the instruction on the original searched location (in our example, java/lang/reflect/Method.invoke the 'invokeinterface' is at location 57).
 
This issue is reproduced across java versions (1.6 - 1.8).

**Comment by DanHeidinga** [comment] 2018-04-09 16:16
This will affect all versions of OpenJ9 as the `invokeinterface2 nop invokeinterface cpIndex cpIndex` pattern is used by all versions.

**Comment by DanHeidinga** [comment] 2018-04-19 14:55
@NatiZel Do you have a minimal test case that reproduces this issue?

@gacholio pointed out there is already code in https://github.com/eclipse/openj9/blob/d5839e9dd7b37b512f6dfb383738dc1aeec8df0a/runtime/jvmti/jvmtiStackFrame.c#L489 to handle the invokeinterface/invokeinterface2 case.

A test case would help to validate the code and what would need to change

**Comment by NatiZel** [comment] 2018-04-22 06:42
@DanHeidinga  I don't have simple tester for that, guess it's connected to the fact that the class is instrumented, will try to provide one.. 
It seems that the code in jvmtiStackFrame.c is not executed in my case, returning 2 bytes shift ahead..

**Comment by DanHeidinga** [comment] 2018-06-04 15:15
@NatiZel Any luck with creating a test case for this issue?  Even a larger application is fine as long as there's something for us to investigate.

**Comment by NatiZel** [comment] 2018-06-06 07:07
@DanHeidinga Not yet, used a workaround for now, sorry for the delay, hope I will be able to provide one soon.

**Comment by DanHeidinga** [comment] 2018-07-10 14:30
@NatiZel Have you been able to get back to this?  A test case would help us to address the issue

**Comment by DanHeidinga** [comment] 2019-04-22 15:41
Closing this now.  We can reopen it if a test case demonstrating the issue is provided

**Closed by DanHeidinga** 2019-04-22 15:41 UTC
Labels: comp:vm, userRaised
