### ISSUE TITLE
special.system_s390x_linux DaaLoadTest testMultiplyPackedDecimalTwoBigInteger

### ISSUE THREAD

**Issue by pshipton** [eclipse/openj9#7299] opened 2019-10-01 13:24 UTC
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_special.system_s390x_linux_Nightly/449
DaaLoadTest_daa1_special_22
variation: Mode687
JVM_OPTIONS: -Xcompressedrefs -XX:+UseCompressedOops -Xjit -Xgcpolicy:gencon -Xaggressive 
```
DLT 04:55:31.987 - Test failed
DLT   Failure num.  = 1
DLT   Test number   = 2
DLT   Test details  = 'JUnit[net.openj9.test.arithmetics.TestArithmeticOperations]'
DLT   Suite number  = 0
DLT   Thread number = 0
DLT >>> Captured test output >>>
DLT testStarted : testAddPackedDecimal(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testAddPackedDecimal(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testRemainderByZero(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testRemainderByZero(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testAddPackedPrecsionTooSmallOverflowSetAsTrueOddToEvenSameByte(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testAddPackedPrecsionTooSmallOverflowSetAsTrueOddToEvenSameByte(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testDividePackedDecimalTwoBigInteger(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testDividePackedDecimalTwoBigInteger(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testSubtractPackedDecimalRandomPossibleNegativeNumbers(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testSubtractPackedDecimalRandomPossibleNegativeNumbers(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testAddPackedPrecsionTooSmallOverflowSetAsFalseOddToEvenSameByte(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testAddPackedPrecsionTooSmallOverflowSetAsFalseOddToEvenSameByte(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testSubtractPrecisionTooSmallOverflowSetAsTrueOddToOdd(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testSubtractPrecisionTooSmallOverflowSetAsTrueOddToOdd(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testLessThanPackedDecimal(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testLessThanPackedDecimal(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testDivideByZero(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFinished: testDivideByZero(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testStarted : testMultiplyPackedDecimalTwoBigInteger(net.openj9.test.arithmetics.TestArithmeticOperations)
DLT testFailure: testMultiplyPackedDecimalTwoBigInteger(net.openj9.test.arithmetics.TestArithmeticOperations): testMultiplyPackedDecimalTwoBigInteger: arrays first differed at element [1]; expected:<80> but was:<0>
DLT testMultiplyPackedDecimalTwoBigInteger: arrays first differed at element [1]; expected:<80> but was:<0>
DLT 	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
DLT 	at org.junit.Assert.internalArrayEquals(Assert.java:532)
DLT 	at org.junit.Assert.assertArrayEquals(Assert.java:341)
DLT 	at net.openj9.test.arithmetics.TestArithmeticOperations.testMultiplyPackedDecimalTwoBigInteger(TestArithmeticOperations.java:14359)
DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
DLT 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
DLT 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
DLT 	at java.lang.reflect.Method.invoke(Method.java:498)
DLT 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
DLT 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
DLT 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
DLT 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
DLT 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
DLT 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
DLT 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:128)
DLT 	at org.junit.runners.Suite.runChild(Suite.java:27)
DLT 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
DLT 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
DLT 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
DLT 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
DLT 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
DLT 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
DLT 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
DLT 	at net.adoptopenjdk.loadTest.adaptors.JUnitAdaptor.executeTest(JUnitAdaptor.java:130)
DLT 	at net.adoptopenjdk.loadTest.LoadTestRunner$2.run(LoadTestRunner.java:182)
DLT 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
DLT 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
DLT 	at java.lang.Thread.run(Thread.java:819)
DLT Caused by: java.lang.AssertionError: expected:<80> but was:<0>
DLT 	at org.junit.Assert.fail(Assert.java:88)
DLT 	at org.junit.Assert.failNotEquals(Assert.java:834)
DLT 	at org.junit.Assert.assertEquals(Assert.java:118)
DLT 	at org.junit.Assert.assertEquals(Assert.java:144)
DLT 	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
DLT 	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
DLT 	... 37 more
```

Perhaps related to #7275 

https://ci.eclipse.org/openj9//job/Grinder/parambuild/?JDK_VERSION=8&JDK_IMPL=openj9&BUILD_LIST=system/daaLoadTest&JenkinsFile=openjdk_s390x_linux&TARGET=DaaLoadTest_daa1_special_22&SDK_RESOURCE=upstream&CUSTOMIZED_SDK_URL=https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_s390x_linux_Nightly/162/OpenJ9-JDK8-s390x_linux-20191001-031326.tar.gz%20https://140-211-168-230-openstack.osuosl.org/artifactory/ci-eclipse-openj9/Build_JDK8_s390x_linux_Nightly/162/native-test-libs.tar.gz&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=ab89294b-5ba1-48e9-8c85-107daca5a2e9

**Comment by fjeremic** [comment] 2019-10-01 14:53
This is almost surely a duplicate of #7275 given the options and the type of test. @r30shah FYI.

**Closed** 2019-11-18 15:17 UTC
Labels: arch:z, comp:jit, test failure
