### ISSUE TITLE
Calling JVMTI function GetAllStackTraces crashes JVM during shutdown

### ISSUE THREAD

**Issue by quijote** [eclipse/openj9#9516] opened 2020-05-11 09:37 UTC
We observed crashes of IBM JVM 8 and multiple versions of AdoptOpenJDK J9 during shutdown of Jetty 9.

To reproduce the problem I built a simple JVMTI agent that calls GetAllStackTraces 10000 times in VMDeath event:

[GetAllStackTracesCrashReproducer.zip](https://github.com/eclipse/openj9/files/4608715/GetAllStackTracesCrashReproducer.zip)

After starting Jetty like this

    java -agentpath:GetAllStackTracesCrashReproducer.dll -jar start.jar

I see the following output after triggering shutdown with Ctrl-C:

	Unhandled exception
	Type=Segmentation error vmState=0x00000000
	Windows_ExceptionCode=c0000005 J9Generic_Signal=00000004 ExceptionAddress=00007FFE77B072A6 ContextFlags=0010005f
	Handler1=00007FFE11F0E940 Handler2=00007FFE23B8AB20 InaccessibleWriteAddress=0000000000000024
	RDI=0000000000000000 RSI=0000000000000000 RAX=0000000000000000 RBX=0000029B71A84A28
	RCX=0000029B71A84A28 RDX=00000000FFFFFFFA R8=0000000000000000 R9=0000029B71A84A00
	R10=00000000003C0001 R11=000000B1609FF798 R12=0000000000000000 R13=000000B1604EA000
	R14=0000000000000001 R15=0000000000000000
	RIP=00007FFE77B072A6 RSP=000000B1609FF540 RBP=000000B1609FF700 GS=002B
	FS=0053 ES=002B DS=002B
	XMM0 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM1 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM2 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM3 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM4 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM5 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM6 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
	Module=C:\WINDOWS\SYSTEM32\ntdll.dll
	Module_base_address=00007FFE77B00000 Offset_in_DLL=00000000000072a6
	Target=2_90_20200422_551 (Windows 10 10.0 build 10240)
	CPU=amd64 (4 logical CPUs) (0x5fc3bf000 RAM)
	----------- Stack Backtrace -----------
	RtlDllShutdownInProgress+0xc6 (0x00007FFE77B072A6 [ntdll+0x72a6])
	RtlEnterCriticalSection+0x1f6 (0x00007FFE77B1B576 [ntdll+0x1b576])
	RtlEnterCriticalSection+0x40 (0x00007FFE77B1B3C0 [ntdll+0x1b3c0])
	omrthread_get_state+0x2c (omrthreadinspect.c:244, 0x00007FFE4DEB8A9C [J9THR29+0x8a9c])
	getVMThreadStateHelper+0x80 (thrinfo.c:233, 0x00007FFE11E60820 [j9jvmti29+0x30820])
	getVMThreadObjectStatesAll+0x1d (thrinfo.c:95, 0x00007FFE11E6058D [j9jvmti29+0x3058d])
	getThreadState+0x3c (jvmtihelpers.c:644, 0x00007FFE11E41F9C [j9jvmti29+0x11f9c])
	jvmtiGetAllStackTraces+0x1ca (jvmtistackframe.c:138, 0x00007FFE11E4FDFA [j9jvmti29+0x1fdfa])
	VMDeath+0x7b (GetAllStackTracesCrashReproducer.cpp:33, 0x00007FFE636010FB [GetAllStackTracesCrashReproduce+0x10fb])
	jvmtiHookVMShutdown+0xa7 (jvmtihook.c:1238, 0x00007FFE11E45BD7 [j9jvmti29+0x15bd7])
	J9HookDispatch+0x150 (hookable.cpp:237, 0x00007FFE6DBC1470 [J9HOOKABLE29+0x1470])
	protectedDestroyJavaVM+0x225 (jniinv.c:346, 0x00007FFE11F1C365 [j9vm29+0x8c365])
	omrsig_protect+0x24f (omrsignal.c:297, 0x00007FFE23B8CC9F [j9prt29+0x1cc9f])
	DestroyJavaVM+0x2d6 (jniinv.c:503, 0x00007FFE11F1B146 [j9vm29+0x8b146])
	DestroyJavaVM+0x1f (jvm.c:531, 0x00007FFE4D88000F [jvm+0x1000f])
	JLI_ReportMessage+0x26b (0x00007FFE6A4D5273 [jli+0x5273])
	_beginthreadex+0x142 (0x00007FFE74C50E72 [ucrtbase+0x20e72])
	BaseThreadInitThunk+0x14 (0x00007FFE77777BD4 [KERNEL32+0x17bd4])
	RtlUserThreadStart+0x21 (0x00007FFE77B6CE51 [ntdll+0x6ce51])
	---------------------------------------

[javacore.20200511.113431.11724.0002.txt](https://github.com/eclipse/openj9/files/4608772/javacore.20200511.113431.11724.0002.txt)

**Comment by gacholio** [comment] 2020-05-11 15:51
Does not reproduce on Linux.

**Comment by gacholio** [comment] 2020-05-28 19:27
@quijote Can you please try this with a current nightly build? I'm hoping this has been fixed by #9630 

If it doesn't, can you please provide a link to download the `start.jar` (assuming this issue has anything to do with what application is running).

**Comment by quijote** [comment] 2020-05-29 11:48
I tried this build:
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2020-05-29-10-23/OpenJDK11U-jdk_x64_windows_openj9_2020-05-29-10-23.zip

It did not crash.

I also need to correct myself. Crash occurred not with Ctrl-C but when shutting down Jetty with a shutdown command. Sorry, I did not notice this made a difference when creating the ticket.

So here are the full steps to reproduce:

1. Download Jetty: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.29.v20200521/jetty-distribution-9.4.29.v20200521.zip
2. Unzip
3. Start Jetty with `java -agentpath:GetAllStackTracesCrashReproducer.dll -DSTOP.PORT=60000 -DSTOP.KEY=a -jar start.jar`
4. Stop Jetty with `java -DSTOP.PORT=60000 -DSTOP.KEY=a -jar start.jar --stop`

**Comment by quijote** [comment] 2020-05-29 11:51
I assume Jetty stop command does something similar as described here: https://github.com/eclipse/openj9/issues/9558

In a daemon thread, first end all non-daemon threads, then call System.exit.

**Comment by gacholio** [comment] 2020-05-29 11:55
Calling System.exit from a daemon thread is exactly what was fixed.

If you're satisfied that the issue is fixed, please close this ite,.

**Comment by gacholio** [comment] 2020-06-08 21:53
The fix has caused some other problems, so it has been reverted. Reopening this until a proper fix can be developed.

**Comment by gacholio** [comment] 2020-06-16 16:59
Correct changes are in master and will appear in the 0.21 release.

**Closed by gacholio** 2020-06-16 16:59 UTC
Labels: comp:vm, segfault, userRaised
