### ISSUE TITLE
Intermittent crashes or hangs in JIT compiled code using ConcurrentHashMap with -XX:+EnableValhalla

### ISSUE THREAD

**Issue by hzongaro** [eclipse/openj9#10869] opened 2020-10-13 13:09 UTC
The following test displays intermittent crashes or hangs running with the option `-XX:+EnableValhalla`.  The problem appears to be some sort of interaction between `monitorenter`/`monitorexit` and `acmp` expansion in lower trees in JIT-compiled trees for `ConcurrentHashMap.putVal`.

```
import java.util.concurrent.ConcurrentHashMap;

public class TestACMP {
    public static final void main(String[] args) throws InterruptedException {
        final ConcurrentHashMap<Integer, Integer> map = new ConcurrentHashMap<Integer, Integer>();
        final int nthreads = 256;
        final int nvals = 1024;

        Thread[] tarr = new Thread[nthreads];

        for (int i = 0; i < tarr.length; i++) {
            final int tnum = i;
            tarr[i] = new Thread() {
                public void run() {
                    for (int j = 0; j < nvals; j++) {
                        map.put(Integer.valueOf(j), Integer.valueOf(j));
                    }
                };
            };
        }

        for (int i = 0; i < tarr.length; i++) {
            tarr[i].start();
        }

        for (int i = 0; i < tarr.length; i++) {
            tarr[i].join();
        }
    }
}
```

Run with `-Xjit:count=1,disableAsyncCompilation`

**Comment by hzongaro** [comment] 2020-10-13 18:01
> Does it exhibit this behaviour with -Xint?

No.  Sorry, I should have been more explicit that this is a JIT problem.

**Comment by hzongaro** [comment] 2020-12-17 14:21
> This issue should be fixed

Thanks for the reminder!  I'll have to go back to the original test, to verify that the problem is fully resolved

**Comment by a7ehuo** [comment] 2020-12-17 16:25
Sorry I should've updated this issue with the root cause of the crash: the crash happened because the live local info is missing in the newly split block after splitPostGRA. #11214 runs liveness analysis in post tree lowering. It should fix it. I just run `TestACMP` with the following build. I don't see crash any more.  

```
$JAVA_HOME -XX:+EnableValhalla -Xverify:none '-Xjit:count=1,disableAsyncCompilation' TestACMP

openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.root.openj9-openjdk-jdk)
Eclipse OpenJ9 VM (build master-468d3c4, JRE 16 Linux amd64-64-Bit Compressed References 20201217_000000 (JIT enabled, AOT enabled)
OpenJ9   - 468d3c4
OMR      - adb322c
JCL      - 20fac7d based on jdk-16+27)
JVMJ9VM193W Since Java 13 -Xverify:none and -noverify were deprecated for removal and may not be accepted options in the future.
```

**Comment by Leonardo2718** [comment] 2021-02-25 16:34
#11968 has been merged now, so we should double-check that this failure no longer happens.

**Comment by a7ehuo** [comment] 2021-02-25 17:34
Run `100x` with the following build that contains #11968. All passed. 

```
$JAVA_HOME -XX:+EnableValhalla -Xverify:none -Xjit:count=1,disableAsyncCompilation TestACMP

openjdk version "16-internal" 2021-03-16
OpenJDK Runtime Environment (build 16-internal+0-adhoc.root.openj9-openjdk-jdk16)
Eclipse OpenJ9 VM (build master-3dcfa9804, JRE 16 Linux amd64-64-Bit Compressed References 20210225_000000 (JIT enabled, AOT enabled)
OpenJ9   - 3dcfa9804
OMR      - 116004c6a
JCL      - 96da0b31991 based on jdk-16+36)
```

**Closed** 2021-03-01 16:56 UTC
Labels: comp:jit, project:valhalla
